### ISSUE TITLE
Something like this for Discord?

### ISSUE THREAD

**Issue by Somfic** [khanhas/spicetify-cli#1]
First of all, thank you a lot for this tool. I used to have it on Rainmeter but I prefere console :)

I'm somewhat sure both Spotify and Discord run on Electron. Would it be possible to have this tool, or something like this, for Discord too?

Many thanks,

Lucas.

**Comment by Somfic** [comment]
EDIT:  [Spotify actually uses the Chromium Embedded Framework directly instead of running via electron](http://josephg.com/blog/electron-is-flash-for-the-desktop/) :(

Would it still be possible, though?

**Comment by mininmobile** [comment]
- betterdiscord (least performant)
    - win https://github.com/rauenzi/BetterDiscordApp/releases
    - linux https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172
- enhanced discord
    - win/ubuntu 18.04+ https://github.com/joe27g/EnhancedDiscord
- beautiful discord (themes only, most performant)
    - python https://github.com/leovoel/BeautifulDiscord

**Comment by Somfic** [comment]
Thanks @mininmobile !
