### ISSUE TITLE
Zombified Spotify ? Can´t play music.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [khanhas/spicetify-cli#10]
![Capture d’écran_2019-03-27_18-20-00](https://user-images.githubusercontent.com/13170204/55097965-33d2ba00-50bd-11e9-9721-c4af8d0ab967.png)
![Capture d’écran_2019-03-27_18-21-03](https://user-images.githubusercontent.com/13170204/55097967-33d2ba00-50bd-11e9-8efb-77425080a3a0.png)
![Capture d’écran_2019-03-27_18-21-25](https://user-images.githubusercontent.com/13170204/55097968-346b5080-50bd-11e9-870d-25fc51d567ef.png)
So, after installing it, configured it and everything without no issues at all. (Outside of reinstalling Spotify the way it is explained), I´ve been able to apply Spicetify with some extensions and config settings flawlessly.
However.. Let´s say that Spotify has died just at that moment. Isn´t able to access to the account history, albums and some other settings. (But strangely can´t still has the recent playlist, and custom made ones for example).
I´ve did tested if it wasn´t a network issue by testing with my smartphone, everything work well, and it synchonise nicely on the app too. You can even control the phone music feed ! But, once you decide to switch to the PC. Nope, doesn´t work.
Another weird thing, It can´t even play local files...
And well, what´s wrong, is that removing the configuration does make it work great again !

**Comment by khanhas** [comment]
Try:
`spicetify restore clear backup apply`

**Comment by PoorPocketsMcNewHold** [comment]
Nope. Same exact same thing.

**Comment by khanhas** [comment]
Can you open Devtool and see if it throws any error to console

**Comment by PoorPocketsMcNewHold** [comment]
Sorry, I´ve should have wait. I´ve since removed spotify, and i will reinstall it now. I´ll confirm if this still happen or any new details to add.

**Comment by PoorPocketsMcNewHold** [comment]
So, despite i´ve removed it, it still was stuck like this. So, I´ve applied the chmod rule, and reapplied spicetify on it. There indeed, one error in the console.
`zlink.bundle.js:177 Uncaught (in promise) Error: Cosmos Request Error. Status: 0
    at zlink.bundle.js:177
    at zlink.bundle.js:55
    at zlink.bundle.js:16
    at zlink.bundle.js:16`

**Comment by PoorPocketsMcNewHold** [comment]
I´ve removed Spicetify from my computer via Homebrew since i´ve used it to install it.

> brew remove spicetify

And removed, and then reinstalled Spotify. Despite any coinfiguration of spicetify being loaded, it does keep those issues. So i doubt this would be due to Spicetify in itself, even if i´m almost certain that Spotify was working fine after i´ve switched from a snap format, to a package installation.
Otherwise, if it´s indeed, not due to spicetify, sorry for reporting that issue.

**Comment by khanhas** [comment]
Sorry I can't help you much.
Tbh I don't what could cause that and the error is irrelevant

**Comment by elijaholmos** [comment]
@PoorPocketsMcNewHold did you ever determine the source of this issue?

**Comment by PoorPocketsMcNewHold** [comment]
Not at all. I’ve since fixed it with a new install, as I’m using another OS since the time of that report, but I never knew what it was.

**Comment by elijaholmos** [comment]
thank you for replying. spotify was having API issues last night at the time of my comment, and the problem was resolved on my machine this morning when I woke up.
