### ISSUE TITLE
React.cloneElement(...): The argument must be a React element, but you passed null.

### ISSUE THREAD

**Issue by rsa16** [khanhas/spicetify-cli#1003]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. Add any custom_app to spicetify config
2. Run `spicetify apply`
3. Spotify will show "Something Went Wrong, try reloading the page."

Note: I am using OnePunch theme.

### ✔️ Expected result

The custom app is working correctly.

### ❌ Actual result

Spotify shows something went wrong

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/47797856/131148072-07efc979-a671-445d-9571-72b9f4a75f8d.png)
I tried opening devtools to check the console.
![image](https://user-images.githubusercontent.com/47797856/131148214-f620c428-9482-400f-8810-2ff36fdec366.png)
I then visited the webpage the error told me to. [This One.](https://reactjs.org/docs/error-decoder.html/?invariant=267&args[]=null)
And it told me the error was `React.cloneElement(...): The argument must be a React element, but you passed null.`

**Comment by CharlieS1103** [comment]
@rsa16 Windows or mac?

**Comment by rsa16** [comment]
Windows.

**Comment by CharlieS1103** [comment]
Alright good just wanted to check something. Anyways i'll work on fixing it soon, shouldn't be super difficult
