### ISSUE TITLE
Show genre of the song

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#1005]
## 📝 The Idea

When exploring new music, knowing the genre of the music even before playing it. 

Why? Because:

- First of all we'd know what to expect from a track
- We can skip genres that we don't like 

## 🔮 Future

What this extension could be (to be implemented in the future)

- auto-skipping could be a extra feature 
- show genre in friend activity tab
  - ability to hide "auto-skipped" genres
- Show top genres of a playlist (I don't think this is a great idea given the rates of the Spotify API. But something like [playlistmachinery](organizeyourmusic.playlistmachinery.com/) comes to my mind.)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by elijaholmos** [comment]
I will warn you that the way Spotify classifies genres is alarmingly inconsistent and very questionable. The biggest example I can offer is that individual tracks have no genre data- it's all stored in the album the track is apart of or the artist who published the track. This would mean the information handled is generally inaccurate and could cause unintentional results.

**Comment by KorayUlusan** [comment]
elijaholmos is right.
