### ISSUE TITLE
No search button in spotify after installing

### ISSUE THREAD

**Issue by tarmichal** [khanhas/spicetify-cli#1006]
## ℹ Computer information

- Spotify version: ?
- Spicetify version: newest

## 📝 Provide detailed reproduction steps (if any)

1. Im installed the spicetify and run spotify
2. And I can't find the button to search for song title and author

### ✔️ Expected result

idk 

### ❌ Actual result

There are only "home", "create playlist", "your episodes" tabs

## 📷 Screenshots

![github 3](https://user-images.githubusercontent.com/87128340/131228851-990f5494-8004-42b6-a57f-60bf208370ad.PNG)

**Comment by afonsojramos** [comment]
Are you sure you didn't edit the sidebar?

**Comment by tarmichal** [comment]
> Are you sure you didn't edit the sidebar?


Oh shit, I actually had to hit the hide button by accident ;)
I am closing the thread.

**Comment by afonsojramos** [comment]
@tarmichal ahaha happens, happy to help!
