### ISSUE TITLE
React Minified error (And what I've found so far)

### ISSUE THREAD

**Issue by CharlieS1103** [khanhas/spicetify-cli#1007]
## ℹ Computer information:
Mac catalina

- Spotify version: 1.1.66.580.gbd43cbc9-a
- Spicetify version: v2.5.0-itsmeow-patch4

## Info

When using custom apps/extensions on Spotify with spicetify, you see the something went wrong page and console shows the below react minified error

## 📷 Screenshots
<img width="733" alt="Screen Shot 2021-08-28 at 6 13 03 PM" src="https://user-images.githubusercontent.com/60494758/131232272-9fc98cbf-508a-4b77-aee9-e07f5546a777.png">

_Are there any useful screenshots?_
This is the function in question
<img width="634" alt="Screen Shot 2021-08-28 at 6 15 18 PM" src="https://user-images.githubusercontent.com/60494758/131232313-e4a884c0-410e-48ad-a6f8-64914bf28644.png">
This is the line where it is called
<img width="617" alt="Screen Shot 2021-08-28 at 6 15 28 PM" src="https://user-images.githubusercontent.com/60494758/131232315-64be15e0-7a7e-4606-a967-d57252573e27.png">
And this regex is where i believe the main issue lies
<img width="626" alt="Screen Shot 2021-08-28 at 6 16 06 PM" src="https://user-images.githubusercontent.com/60494758/131232327-609ae2e3-36da-4b60-bba3-fae6cf0a5f87.png">

You can find the line where its called at around line 843 in spicetifywrapper.js. and

the regex at line 205 in apply.go

@itsmeow

**Comment by itsmeow** [comment]
this is because the CSS mappings are broken, see #845

**Comment by CharlieS1103** [comment]
Oh so it returns null because main-navbar-navbarlink doesn't exist or something?

**Comment by itsmeow** [comment]
Yep, that exactly.

**Comment by CharlieS1103** [comment]
Do you know of anyone working on it atm or is it kinda just sitting there? @itsmeow

**Comment by itsmeow** [comment]
Someone said "I might write the script" in reference to a mapping script between old vs new names, but I don't know. I'm a bit busy rn but you can see I posted a css.zip on 845, you can try yourself. It's just finding the new classnames for all the old ones.

**Comment by CharlieS1103** [comment]
Oh that doesn't seem too difficult, i'll probably find a time to grind through all that when my brain decides to be motivated at 4am.

**Comment by SebiTalent04** [comment]
Soo... Any updates on this?

**Comment by TheGeeKing** [comment]
We are working on the css remapping so it should be fixed when the css remap will be finished
