### ISSUE TITLE
Spicetify's default theme using squares instead of symbols

### ISSUE THREAD

**Issue by Gemuki** [khanhas/spicetify-cli#101]
Basically what the title says, the default theme for Spicetify on my end is using squares rather than the symbols that are meant to be there.

Here's a image of these squares popping up.
![image](https://user-images.githubusercontent.com/34210449/68070259-83244b80-fd6c-11e9-8f8c-990027e4a5ef.png)

**Comment by khanhas** [comment]
Run:
```
spicetify restore backup apply
```

**Comment by Gemuki** [comment]
Apologies for the silence, i rarely end up using GitHub.

I'll see if it works.

**Comment by Gemuki** [comment]
This did sadly not work.

**Comment by Gemuki** [comment]
And now i've fixed it myself, re-installing Spotify itself got those squares taken care of.

Thanks for the help.
