### ISSUE TITLE
Right-Clicking anything now show developer context menu

### ISSUE THREAD

**Issue by Satanarious** [khanhas/spicetify-cli#1010]
Right-Clicking anywhere in the Spotify UI now shows a developer context menu. This is not a problem but, in some cases, it overrides the Spotify context menu, making it lose some functionality. In this case, when I right-click the currently playing song's art, instead of showing the Spotify context menu, which enables sharing a song or adding a song to a playlist, it shows the developer context menu.

![image](https://user-images.githubusercontent.com/42642682/131497055-34b5365e-8fab-45b4-942b-89ab1a866e90.png)

Also, when right-clicking the currently playing song's title on the bottom right brings up the developer context menu instead of the Spotify one.

![image](https://user-images.githubusercontent.com/42642682/131497339-86c2e2e0-1176-4dd0-b020-477280834e1e.png)

It still works for most of the cases like right-clicking currently playing song's artist, which is the expected behaviour.

![image](https://user-images.githubusercontent.com/42642682/131497558-3d9bdc1a-dc1d-4dd6-82ed-4a992a080ddd.png)

But clicking anywhere on the Spotify UI except buttons/links now brings up the developer context menu and in some cases like the above shows developer context menu instead of the Spotify Context Menu

**Comment by TheGeeKing** [comment]
Are you sure that you don't have devtool enable?
If so `spicetify disable-devtool`
If it still persists, please send your config file

**Comment by Satanarious** [comment]
Even though I never enabled devtools. The command you provided now don't show the developer context menu. But, right-clicking the currently playing song's art/artist doesn't show any context menu at all, not even the expected Spotify context menu.

**Comment by Satanarious** [comment]
Here's my config file,

```ini
[Patch]

[Setting]
color_scheme            = 
inject_css              = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\satya\AppData\Roaming\Spotify
current_theme           = onepunch
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
prefs_path              = C:\Users\satya\AppData\Roaming\Spotify\prefs

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
extensions     = shuffle+.js|trashbin.js|webnowplaying.js|hidePodcasts.js
custom_apps    = reddit|lyrics-plus
sidebar_config = 1
home_config    = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.65.643.g2d707698
with    = 2.5.0-itsmeow-patch4

```

**Comment by TheGeeKing** [comment]
> Even though I never enabled devtools. The command you provided now don't show the developer context menu. But, right-clicking the currently playing song's art/artist doesn't show any context menu at all, not even the expected Spotify context menu.

Not sure but i think the album picture and the title of the song have no context menu so it is normal that nothing appear.
Just tried on Spotify 1.1.65.643.g2d707698-a and there is no context menu. The artist has a context menu if you right click on it.
