### ISSUE TITLE
spicetify upgrade to 2.6.0 fails

### ISSUE THREAD

**Issue by citizenserious** [khanhas/spicetify-cli#1011]
## ℹ Computer information

- Spotify version: 1.1.67.584
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. open power shell as admin
2. spicetify upgrade
3. spicetify -v

## different approach

1.  remove spicetify
2. Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

--> result here: shows the download of the 2.6.0 zip file but still installs the 2.5.0-itsmeow-patch4

### ✔️ Expected result

upgrade to 2.6.0

### ❌ Actual result

stays on 2.5.0-itsmeow-patch4

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/62773866/131524891-fdf541ca-f31e-48cb-8c2c-463dcdbab473.png)
![Screenshot 2021-08-31 170101](https://user-images.githubusercontent.com/62773866/131526851-043ecc04-d232-41fe-a4a7-0606f2976bc8.png)

**Comment by TheGeeKing** [comment]
Duplicate of #973

**Comment by citizenserious** [comment]
sorry, overlooked the Duplicate of #973

**Comment by TheGeeKing** [comment]
for info Spotify : 1.1.67.584 doesn't exists

**Comment by citizenserious** [comment]
> 
> 
> for info Spotify : 1.1.67.584 doesn't exists

![image](https://user-images.githubusercontent.com/62773866/131529758-f696477d-074d-4415-b1c4-753f15fb6b0b.png)

so I thought it will get updated after a restart... but it wasn't ... nevermind
