### ISSUE TITLE
Cannot find symbol for Custom app React symbols - oh how we love spotify :)

### ISSUE THREAD

**Issue by Nerxxy** [khanhas/spicetify-cli#1020]
## ℹ Computer information

- Spotify version: 1.1.67.584.gc0d1ad42
- Spicetify version: 2.6.0

## 📝 Provide detailed reproduction steps (if any)

just update Spotify...

**Comment by M4kaze** [comment]
Got Spicetify version 2.6.2 and Spotify version 1.1.62.583.gdac868ed-a and have the same Problem. 
Because of this none of my Extensions are loading...

**Comment by TheGeeKing** [comment]
If you use Spotify 1.1.65.643 or below you should use Spicetify 2.6 or below not 2.6.1 or 2.6.2

**Comment by M4kaze** [comment]
Downloaded 2.6.0 but its shows only as 2.5.0-itsmeow-patch4.
But still the same issue.

**Comment by TheGeeKing** [comment]
It's normal that spicetify 2.6 show patch4. What are your extensions and custom apps?

**Comment by M4kaze** [comment]
Extensions:

- dribbblish.js
- autoSkipVideo.js
- bookmark.js
- autoSkipExplicit.js
- fullAppDisplay.js
- loopyLoop.js
- newRelease.js
- queueAll.js
- shuffle+.js
- webnowplaying.js
- trashbin.js
- copyPlaylist.js
- historyShortcut.js

Custom Apps:
- new-releases

**Comment by TheGeeKing** [comment]
What happens if you remove all your extensions and custom apps? If it works try to add them one by one

**Comment by M4kaze** [comment]
Even if I remove all it says "Cannot find symbol for Custom app React symbols", but without the runtime error.

**Comment by TheGeeKing** [comment]
OK thanks. We are aware of this issue and we are investigating to fix it as quickly as possible.

**Comment by Nerxxy** [comment]
Since posting ive updated Spotify (1.1.67.586.gbb5ef64e) and spicetify (2.6.1) and i can see my theme, but still get the custom apps thing, i dont have any apps running, normally when i got that custom apps error it didnt allow for themes to load

**Comment by Nerxxy** [comment]
I also have another thing... so i when i right click in spotify i get the dev menu option? Not sure if this is spicetify or spotify... even happens when i do "spicetify restore" ?

**Comment by TheGeeKing** [comment]
Do `spicetify disable-devtool`

**Comment by Nerxxy** [comment]
Thats the thing, i dont remember ever doing `spicetify devtool` or `...enable-devtool` whatever the command is

**Comment by Nerxxy** [comment]
I probably did, just dont remember it lmao

**Comment by ALBERTOBYING** [comment]
I have the same problem. In powershell...
Applying additional modifications:
Cannot find symbol for Custom app React symbols

![Captura de pantalla (469)](https://user-images.githubusercontent.com/51053307/133445261-1a1ee6b9-d6da-40dd-9e86-5e5a899b240c.png)

**Comment by Xerons21** [comment]
I have the same problem with custom apps ;C
