### ISSUE TITLE
Cannot reinstall Spicetify/Gives error on installation

### ISSUE THREAD

**Issue by AydanSummers** [khanhas/spicetify-cli#1021]
- Spotify version: Latest
- Spicetify version: 2.6.1

1. Pasted in admin PowerShell:

\\ Add-Type -AssemblyName PresentationFramework
\\ Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
\\ spicetify
\\ spicetify backup apply enable-devtool
\\ [System.Windows.MessageBox]::Show('Please drag the themes into the themes folder located at | C:\Users\YourUserName\.spicetify\Themes |')
\\ spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
\\ spicetify apply
\\ pause

2. Text in admin PowerShell:

\\ PS C:\Windows\system32> spicetify
\\ Program 'spicetify.exe' failed to run: Access is deniedAt line:1 char:1
\\ + spicetify
\\ + ~~~~~~~~~.
\\ At line:1 char:1
\\ + spicetify
\\ + ~~~~~~~~~
\\     + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
\\     + FullyQualifiedErrorId : NativeCommandFailed

**Comment by afonsojramos** [comment]
Not sure, but maybe it has to do with where you are running the command (System32). Additionally, you do not need to use an admin powershell, the normal one should be fine.
