### ISSUE TITLE
New Releases Custom App config menu no longer shows up

### ISSUE THREAD

**Issue by Pandasdontfly** [khanhas/spicetify-cli#1022]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9-a
- Spicetify version: 2.6.1

### ✔️ Expected result

The Config Menu To be shown and accessible 

### ❌ Actual result

Nothing appears making it so i cannot edit the filters

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/87935732/131632542-b3e9d2b2-663a-4f02-9742-ac23d4dd89af.png)

**Comment by afonsojramos** [comment]
We are aware of this issue, it is also highly deformed, but the other option was for the custom apps to not work at all sooo 😅

**Comment by itsmeow** [comment]
Error due to `Spicetify.Menu` hook being broken.

**Comment by itsmeow** [comment]
Working locally with both my PRs merged.
![image](https://user-images.githubusercontent.com/10366817/132192674-670453e0-15b2-42fb-9b1d-6c42688a7550.png)

I also went ahead and fixed the broken CSS for the cards in my mappings PR, so that fixes the weird linear formatting.
