### ISSUE TITLE
Bookmark.js extension working incorrectly.

### ISSUE THREAD

**Issue by benpashiro** [khanhas/spicetify-cli#1027]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9-a
- Spicetify version: 2.6.1

## 📝 Reproduction Steps

1. Use bookmark.js 

### ✔️ Expected result

[This](https://camo.githubusercontent.com/09bf34a4f5c626c38fcdc7fea9cd21d4468524cac00bf37a7fd8293dab2c06ff/68747470733a2f2f692e696d6775722e636f6d2f697367553454532e706e67)

### ❌ Actual result

[A](https://imgur.com/a/L2IAb9K)
[B](https://imgur.com/a/CF8h1OP)

**Comment by benpashiro** [comment]
> Hi,
> 
> It's due to the new css. The 2.6.1 was release just so people can have access to the newer version of Spotify. A bigger release will be made later this weekend hopefully and will fix almost everything.

Hopefully! Thanks for the info.

**Comment by afonsojramos** [comment]
@benpashiro can you check if it has been fixed in 2.6.6?

**Comment by TheGeeKing** [comment]
> @benpashiro can you check if it has been fixed in 2.6.6?

Checked and it's properly working so you can close this issue.

**Comment by akh8zm** [comment]
I'm having this issue after adding trying out bookmark.js for the first time. Not sure if it's a problem on my end or perhaps the new spicetify version? I switched back to the default theme.
Spotify version: 1.1.70.610.g4585142b
Spicetify version: 2.7.0
![image](https://user-images.githubusercontent.com/56124630/137251060-1e8780dd-fbb8-4093-bba5-8c47446fc59c.png)
![image](https://user-images.githubusercontent.com/56124630/137250975-9ce701e0-2b80-4852-971b-26994391e38e.png)
