### ISSUE TITLE
Broken UI using Dribblish

### ISSUE THREAD

**Issue by drag0nst0ne** [khanhas/spicetify-cli#1031]
## ℹ Computer information

- Spotify version: 1.1.67.586.gbb5ef64e
- Spicetify version: 2.6.1

## 📝 Provide detailed reproduction steps (if any)

No steps, i just open the app and looks like that

### ✔️ Expected result

Expected to look normal as it always has been

### ❌ Actual result

Left panel its blank, progress bar is broken.... 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/50338430/132021263-612b3c30-4b65-4274-b1dc-9c7690ee9f8b.png)

**Comment by CharlieS1103** [comment]
Being fixed atm. ETA: 2 weeks

**Comment by drag0nst0ne** [comment]
Ok Thx, Should i close the issue or wait for it be fixed before??

**Comment by TheGeeKing** [comment]
You should close it and make a new one if the issue persist after the update is released.
