### ISSUE TITLE
Linux: permissions also need to be changed on distros other than Arch

### ISSUE THREAD

**Issue by mileskrell** [khanhas/spicetify-cli#1032]
## ℹ Computer information

- Spotify version: 1.1.55.498.gf9a83c60
- Spicetify version: 2.6.1
- OS version: Kubuntu 20.04

## 📝 Provide detailed reproduction steps (if any)

1. [Install Spotify via apt](https://www.spotify.com/us/download/linux/)
2. Install spicetify
3. Call `spicetify`
4. Call `spicetify backup apply enable-devtool`

Results in the following:
```
$ spicetify backup apply enable-devtool
spicetify v2.6.1
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
fatal unlinkat /usr/share/spotify/Apps/buddy-list.spa: permission denied
```

However, running the following commands appears to fix it:
```
$ sudo chmod a+wr /usr/share/spotify
$ sudo chmod a+wr /usr/share/spotify/Apps -R
```

Upon running the earlier command again, that error is now gone, and Spotify opens after with a theme applied:
```
$ spicetify backup apply enable-devtool
spicetify v2.6.1
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!
success DevTool enabled!
```

I think it would be helpful to edit the installation docs to say that these permission changes might be necessary on distros other than Arch as well :)

**Comment by afonsojramos** [comment]
This is actually already detailed in the Wiki, however, I do see why you might have not seen it. On the following day I will try to do some spring cleaning to the Wiki.

**Comment by mileskrell** [comment]
Oh, I see what you mean - this step is given under the section titled "Spotify installed from Snap", but I didn't install Spotify through Snap so I just didn't think to look in this section. Yeah, I think maybe just saying above the installation method-specific instructions something along the lines of "permissions for the Spotify installation folder must be modified for Spicetify to be able to work; for details, see the section for your chosen installation method below" would do the trick.
