### ISSUE TITLE
Fluent Theme Broken

### ISSUE THREAD

**Issue by AshKetchum101** [khanhas/spicetify-cli#1033]
## ℹ Computer information

- Spotify version: Latest
- Spicetify version: V2.6.2

## 📝 Provide detailed reproduction steps (if any)

1. … Just on the Fluent theme with fluent.js and popupLyrics enabled

### ✔️ Expected result

Normal Theme Working
with popupLyrics

### ❌ Actual result

Play and Pause button blank
Playlist covers not showing up
Shuffle and repeat buttons no clickable/working
No button for popupLyrics

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/90083448/132084337-9f996d35-e3d2-440b-af2d-6659e88a4331.png)

**Comment by zjeffer** [comment]
Same issue here with my own theme. It looks like Spotify updated their css again.

**Comment by TheGeeKing** [comment]
@AshKetchum101 please close this issue as it is a known issue
