### ISSUE TITLE
Spotify broken after downgrade

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1035]
## ℹ Computer information

- Spotify version: 1.1.62.583
- Spicetify version: 2.6.2

## 📝 Provide detailed reproduction steps (if any)

1. Followed instructions in [this video](https://www.youtube.com/watch?v=lPUFzDes_Eg) downgrade to 1.1.62.583 due to #1029 

### ✔️ Expected result

Should be able to apply spicetify theme and use custom apps.

### ❌ Actual result

Unable to use Spotify. Error persists after running `spicetify restore`.

## 📷 Screenshots

Error message in Spotify after trying to apply the theme:
![image](https://user-images.githubusercontent.com/63046776/132092860-71ceeb6d-12c9-4f95-bd35-4244e81681ed.png)

Spicetify error message after trying to apply the theme:
![image](https://user-images.githubusercontent.com/63046776/132092873-7187d2cf-2026-47c1-9d5c-3b845c35b7e2.png)

**Comment by lemonnuggets** [comment]
Tried restoring spotify to fix issue but nothing changed.

**Comment by TheGeeKing** [comment]
If you use Spotify 1.1.65.643 or below you should use Spicetify 2.6 or below not 2.6.1 or 2.6.2

**Comment by lemonnuggets** [comment]
Yeah upgrading to 1.1.66 worked out for me. Closing this issue now.
