### ISSUE TITLE
Spicetify Dribblish theme missing playlist icons on sidebar + default media play/pause buttons on previous versions of Spicetify and Spotify

### ISSUE THREAD

**Issue by kuraie** [khanhas/spicetify-cli#1036]
I have recently installed an older version of Spotify (version 1-1-65-643), because on the latest version of Spotify and Spicetify, Dribblish has issues such as no playlist icons on the left sidebar, and the play/pause icons are similar to the default Spotify theme, unlike the ones seen in the screenshots for the theme. I would like to install version 2.6 of Spicetify as that seems to have been closer to the version I have just installed of Spotify. Would this be the proper route to go? Do you have any suggestions that I should do, or is everything fine here, and the previous versions should work as intended.

**Comment by TheGeeKing** [comment]
You can't post an issue with just a title and nothing else. The title doesn't even say what's your issue. Give more info or close this issue.

**Comment by TheGeeKing** [comment]
That's a little better. https://github.com/khanhas/spicetify-cli/wiki/Installation `$v="1.2.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
`

With `$v=1.2.1` the version of spicetify you want

**Comment by kuraie** [comment]
As I was posting my issue, I accidentally hit enter on the title. It somehow just submitted without me even having anything as my description. Anyways, it has been fixed.

**Comment by TheGeeKing** [comment]
> I would like to install version 2.6 of Spicetify as that seems to have been closer to the version I have just installed of Spotify. Would this be the proper route to go?

Spicetify 2.6 will be perfect with Spotify 1.1.65.643

**Comment by kuraie** [comment]
> 
> 
> Spicetify 2.6 will be perfect with Spotify 1.1.65.643

Thanks. Is there a way to fully install Spicetify without the use of Git? I installed Git and uninstalled it after installing Spicetify, it's too much of a hassle to reinstall it. I'm following a different method of installing Spicetify now, the one seen in this video: https://www.youtube.com/watch?v=rRhratE0KNk

This video links to a pastebin with an installation code for Spicetify. I can just add "$v="2.6.0";" before it and proceed as seen in the video, correct? I believe it you have to manually drag the themes into the theme folder, so I can fully install without the use of Git.

**Comment by TheGeeKing** [comment]
Check https://github.com/khanhas/spicetify-cli/wiki/Installation

There is the command I posted, change the version you want and run it in PowerShell

**Comment by kuraie** [comment]
I've already done `$v="2.6.0"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression` but I get:
`PS C:\Windows\system32> spicetify --version
2.5.0-itsmeow-patch4`

Although I did get an older version of spicetify, I'm still getting the issues as I had with the latest version of Spicetify + Spotify.
![Screenshot 2021-09-04 223440](https://user-images.githubusercontent.com/85814229/132098114-95f7ba74-3136-4d27-96ea-844fa3e9040d.png)

Missing playlist icons on the left sidebar + default play/pause buttons.

**Comment by kuraie** [comment]
Apparently this is a prevalent issue among other users. I have tried downgrading to version 1.1.62.583 of Spotify and 2.5.0 of Spicetify to get things working as intended, but the issue still occurs, it's in an even worse state. With the volume of issues I experienced downgrading, I'm giving up, and will be waiting patiently for when the fix for this will come later down the line.
