### ISSUE TITLE
After applying latest spotify upgrade on arch linux, almost all extensions and custom apps are broken

### ISSUE THREAD

**Issue by sasiya69** [khanhas/spicetify-cli#1037]
## ℹ Computer information
- OS: archlinux (spicetify and spotify from AUR)
 - Spotify version: spotify 1:1.1.67.586-1
 - Spicetify version : 2.5.0-1  ( From pacman -Q spicetify-cli, spicetify -v gives blank output)

## 📝 Provide detailed reproduction steps (if any)
1. spicetify config custom_apps reddit
2. spicetify config custom_apps lyrics-plus
3. spicetify config extensions fullAppDisplay.js
4. spicetify apply

### ✔️ Expected result

Extensions and apps should work as expected

### ❌ Actual result

full app display extension's progress bar and current time on song seems broken, reddit and lyric-plus app shows something went wrong page

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/71586084/132106383-4281362e-b897-4642-a833-e9b711617bcd.png)
![image](https://user-images.githubusercontent.com/71586084/132106398-ca373711-8a6a-4ade-b3c8-b347cd494d26.png)

**Comment by CharlieS1103** [comment]
Idk if you can because you're on linux. But try to installt the latest version of spicetify via the github, not a package manager

**Comment by KoNickss** [comment]
of course he can, it's Linux, I also have this issue and I'll be trying the GH version, I'll be back with the result.

**Comment by KoNickss** [comment]
yes that fixes the issue for me at least, waiting for op to give the final verdict, (for anyone trying this just remember to use the local install of spicetify if you use the install.sh script in ~/spicetify-cli/spicetify), 'till then, consider the issue solved

**Comment by afonsojramos** [comment]
@sasiya69 any updates?

**Comment by PolpOnline** [comment]
I would suggest using the `-git` version from the AUR, so you can have the latest fixes.

**Comment by sasiya69** [comment]
The git version now seems working, closing the issue !
