### ISSUE TITLE
Any Custom app errors Spotify 

### ISSUE THREAD

**Issue by RaspberryKitty1** [khanhas/spicetify-cli#1039]
## ℹ Computer information

- Spotify version: 1.1.65.643.g2d707698-a
- Spicetify version: Latest
- OS version: Windows 11 Version 21H2 (OS Build 22000, 168)

## 📝 Provide detailed reproduction steps (if any)

1. installed Spotify and spicetify
2. open command prompt/powershell
3. spicetify config custom_apps <anything>

I tried all 4 of these all same results. 
1.lyrics-plus
2.new-releases
3.reddit
4.volume-profiles

### ✔️ Expected result

load the custom app/apps

### ❌ Actual result

Spotify just errors

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/28585042/132165558-a143be2b-e397-4c6f-a7dd-9a071568e506.png)

**Comment by TheGeeKing** [comment]
Hi @RaspberryKitty1,

If you use Spotify 1.1.65.643, you will need to use Spicetify 2.6 not 2.6.1 or 2.6.1

You may need to block updates

https://www.filepuma.com/download/spotify_1.1.65.643-29529/

`del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R`

**Comment by RaspberryKitty1** [comment]
i tried that same issue
![image](https://user-images.githubusercontent.com/28585042/132241785-6623a617-957e-43a6-a854-ea5decd0dd3f.png)
![image](https://user-images.githubusercontent.com/28585042/132241866-98f690a5-bcb0-4dad-b50c-82aa6dc87992.png)

**Comment by RMZtherealone** [comment]
Is spicetify dead ? I downgraded Spotify, created a Update folder, deny all... but nothing seems to work. I was using it for the webnowplugin.

**Comment by TheGeeKing** [comment]
> i tried that same issue
> ![image](https://user-images.githubusercontent.com/28585042/132241785-6623a617-957e-43a6-a854-ea5decd0dd3f.png)
> ![image](https://user-images.githubusercontent.com/28585042/132241866-98f690a5-bcb0-4dad-b50c-82aa6dc87992.png)
> 
> 

Can you send a screenshot of your Spotify version? Is there any error in the devtool?

**Comment by TheGeeKing** [comment]
> Is spicetify dead ? I downgraded Spotify, created a Update folder, deny all... but nothing seems to work. I was using it for the webnowplugin.

What are your Spicetify and Spotify versions? Is it the same issue (when you apply a custom app it doesn't work)?

**Comment by RaspberryKitty1** [comment]
> Can you send a screenshot of your Spotify version? Is there any error in the devtool?

![image](https://user-images.githubusercontent.com/28585042/132264543-38e59319-a017-4ab2-a2bb-b903a45a1857.png)
![image](https://user-images.githubusercontent.com/28585042/132264561-79db38e6-ae67-420a-a7c9-c15fd03ac076.png)

**Comment by Satanarious** [comment]
I have tried to run each command one by one to see what breaks Spotify. I found out that custom_apps are causing the problem for me. If I don't install custom_apps , everything starts working fine without them. I have tested this for both custom_apps(reddit and lyrics-plus).

**Comment by TheGeeKing** [comment]
> I have tried to run each command one by one to see what breaks Spotify. I found out that custom_apps are causing the problem for me. If I don't install custom_apps , everything starts working fine without them. I have tested this for both custom_apps(reddit and lyrics-plus).
> Spotify Version: 1.1.65.643.g2d707698-a
> Spicetify Version: 2.6.2

Man, Spicetify 2.6.1 and 2.6.2 are not compatible with Spotify 1.1.65.643 you need to rollback to 2.6

**Comment by TheGeeKing** [comment]
> 
> > Can you send a screenshot of your Spotify version? Is there any error in the devtool?
> 
> ![image](https://user-images.githubusercontent.com/28585042/132264543-38e59319-a017-4ab2-a2bb-b903a45a1857.png)
> ![image](https://user-images.githubusercontent.com/28585042/132264561-79db38e6-ae67-420a-a7c9-c15fd03ac076.png)
> 

In spicetify 2.6 the only working custom apps is lyrics-plus. You should maybe try without your theme

**Comment by Satanarious** [comment]
> > I have tried to run each command one by one to see what breaks Spotify. I found out that custom_apps are causing the problem for me. If I don't install custom_apps , everything starts working fine without them. I have tested this for both custom_apps(reddit and lyrics-plus).
> > Spotify Version: 1.1.65.643.g2d707698-a
> > Spicetify Version: 2.6.2
> 
> Man, Spicetify 2.6.1 and 2.6.2 are not compatible with Spotify 1.1.65.643 you need to rollback to 2.6

It's working fine though.

**Comment by brenmadeit** [comment]
> > > Can you send a screenshot of your Spotify version? Is there any error in the devtool?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/28585042/132264543-38e59319-a017-4ab2-a2bb-b903a45a1857.png)
> > ![image](https://user-images.githubusercontent.com/28585042/132264561-79db38e6-ae67-420a-a7c9-c15fd03ac076.png)
> 
> In spicetify 2.6 the only working custom apps is lyrics-plus. You should maybe try without your theme

couldnt get custom apps to work, and some extensions dont seem to work, like shuffle+

**Comment by gunacorn** [comment]
I have Windows 10 21H1 19043.1165, Spotify 1.1.67, and Spicetify 2.6.2, and custom apps seem to break due to a missing react symbol? 
![image](https://user-images.githubusercontent.com/62181389/132764423-dcdf7d82-a061-49e2-a537-92652f8e3e27.png)

**Comment by RaspberryKitty1** [comment]
> In spicetify 2.6 the only working custom apps is lyrics-plus. You should maybe try without your theme

I have tried. same results that's why I made an issue for it. also, I don't see why a theme would prevent a custom app from working

**Comment by afonsojramos** [comment]
Currently tracking this issue on #980.
