### ISSUE TITLE
Carlsystem998@gmail.com 

### ISSUE THREAD

**Issue by CarlmodeAnonn** [khanhas/spicetify-cli#1040]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by RaspberryKitty1** [comment]
you did not fill in any of the needed info you just summited the template...

**Comment by TheGeeKing** [comment]
@afonsojramos please close this spam
