### ISSUE TITLE
lyrics plus doesnt load

### ISSUE THREAD

**Issue by junkypurr** [khanhas/spicetify-cli#1045]
every time i try to use lyrics plus, i get this error (see image). im running spotify version 1.1.66.580 and my spicetify is up to date. 
![image](https://user-images.githubusercontent.com/50148641/132801119-8851c403-ee1b-4c25-b7db-07b975707daa.png)

**Comment by itsmeow** [comment]
Duplicate of #980

**Comment by afonsojramos** [comment]
Currently tracking this issue on #980.
