### ISSUE TITLE
LoopyLoop Extension do not work

### ISSUE THREAD

**Issue by Aldrichyl** [khanhas/spicetify-cli#1048]
Hi ! I've added the extension loopyLoop and it doesn't seem to work, or maybe i do not know how to use it.
When i try right click on the progression bar, i only get the usual right click options (Print, View PAge Source, Reload...)
Can someone enlighten me ? Or help me fix this issue ? Thank you !

**Comment by TheGeeKing** [comment]
The issue will be fixed when Spicetify 2.6.3 roll-out.

**Comment by Aldrichyl** [comment]
Thanks!
