### ISSUE TITLE
Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#1049]
![image](https://user-images.githubusercontent.com/81705406/132958141-803daf0b-7c87-495e-9fd6-d31bb022f01d.png)
Spotify version latest. Same as spicetify-cli
It's the same error as before, but there's some added stuff at the bottom.

**Comment by sicr0** [comment]
I've got the same message running the latest Spotify from AUR, spicetify-cli from GitHub, and DribbblishDynamic from GitHub. But without the panic error, the theme just looks broken

**Comment by coledeb** [comment]
Also having this issue when only trying to use webnowplaying.js (all theming set to 0), although I don't receive a panic error. cleartext with Rainmeter is not working either. Tried removing spicetify & spotify then reinstalling, same issue.

**Comment by TheGeeKing** [comment]
This issue will be fixed in spicetify 2.6.3 You can close this issue

**Comment by Copimox** [comment]
> This issue will be fixed in spicetify 2.6.3 You can close this issue

ok, closing

**Comment by devilAPI** [comment]
well it wasnt fixed in 2.6.3 -_-

**Comment by TheGeeKing** [comment]
Should have been. At the moment we have bigger problems with the release of Spotify 1.1.68: a lot of things have gotten worse.

**Comment by afonsojramos** [comment]
>well it wasnt fixed in 2.6.3 -_-

@devilAPI so apparently not everyone has the new React hooks. For example, I also have the old hooks while still being at 1.1.68 🤷

**Comment by afonsojramos** [comment]
@Copimox so, the solution to this problem goes by completely deleting you spicetify-cli and .spicetify folders and doing a clean install of Spicetify.
This is likely due to some old extensions/custom apps that were left behind and are now breaking the app.

**Comment by namvinhkhang** [comment]
i was using spicetify 2.6 and spotify 1.1.62.583.gdac868ed and stumbled across this issue
Should i update to the latest spicetify or spotify or both 
![Desktop Screenshot 2021 09 21 - 13 31 23 60](https://user-images.githubusercontent.com/83082969/134122530-dd9d6dfe-92e3-4115-916f-0f920fa081ee.png)
?

**Comment by afonsojramos** [comment]
@namvinhkhang both! Thank you for commenting here and not opening a new issue ❤️

**Comment by namvinhkhang** [comment]
@afonsojramos  thanks man, after digging in a bunch of old issues I use spicetify 2.6 and spotify 1.1.65 working flawlessly for now. Ive tried spicetify 2.6.4 and with the latest spotify and spotify 1.1.62 , neither of them work, problably because of my fault during the installation.

**Comment by namvinhkhang** [comment]
I did but still didnt work for me, try differents spicetify version (2.6->2.4) but none works for spotify version 1.1.62. Guess it is too old  ?

**Comment by TheGeeKing** [comment]
Spicetify 2.6.0 and lower work for Spotify 1.1.65 and lower. So you can't use 2.6.4 with 1.1.65 or 1.1.62 that's why

**Comment by namvinhkhang** [comment]
Oh thanks man.
