### ISSUE TITLE
[Extention request] Start in system tray

### ISSUE THREAD

**Issue by kevinsnijder** [khanhas/spicetify-cli#105]
Hey,
I love the work you guys have done on this mod!

I do have a tiny request, could there be an extention so Spotify can be started in the system tray on boot?
Spotify only offers the option to
- Not start on boot at all
- Start full screen
- Start minimized

I hope you guys will consider this.

Thanks!

**Comment by khanhas** [comment]
Sorry of late reply.
There is no way to manipulate application boot behaviour at Chrominium level.
