### ISSUE TITLE
Lyrics Plus not working

### ISSUE THREAD

**Issue by Aldrichyl** [khanhas/spicetify-cli#1050]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9-a
- Spicetify version: 2.6.2

## 📝 Provide detailed reproduction steps (if any)

1. I installed the custom app " Lyrics-Plus"
2. I opened Spotify and went over to the "Lyrics" Section
3. It do not work

### ✔️ Expected result

- Lyrics-Plus working
### ❌ Actual result

- Something Went Wrong & Try Reloading the page

**Comment by afonsojramos** [comment]
Currently tracking this issue on #980.

**Comment by ZoomMan2** [comment]
I received this error page in 2023 after updating to the most recent Spotify version.
![Screenshot 2023-05-28 135524](https://github.com/spicetify/spicetify-cli/assets/83414274/bfb58642-9519-4a74-a59a-f868fc984ab2)

**Comment by kyrie25** [comment]
> I received this error page in 2023 after updating to the most recent Spotify version.
> 
> The Marketplace tab is also broken. (not showing tabs)
> 
> - Spotify version: 1.2.12.902.g1924b088
> 
> - Spicetify version: v2.17.2
> 
> ![Screenshot 2023-05-28 135524](https://github.com/spicetify/spicetify-cli/assets/83414274/bfb58642-9519-4a74-a59a-f868fc984ab2)
> 
> ![Screenshot 2023-05-28 140313](https://github.com/spicetify/spicetify-cli/assets/83414274/3c6026dd-5bc5-47bb-8bd9-d94cf246d857)
> 
> 
> 
> 

Outdated Spicetify version. Run `spicetify upgrade` then `spicetify restore backup apply`
