### ISSUE TITLE
Can't using Lyrics Plus

### ISSUE THREAD

**Issue by spread5789** [khanhas/spicetify-cli#1051]
## ℹ Computer information

- Spotify version: 1.1.67.586
- Spicetify version: 2.6.2

## 📝 Provide detailed reproduction steps (if any)

1. … Install Spotify & Spicetify (Both lastest)
2. … run PowerShell and type command

### ✔️ Expected result
work everything.

### ❌ Actual result
can't see Lyrics Tab and error during run *spicetify apply* in powershell

## 📷 Screenshots
![1](https://user-images.githubusercontent.com/73854324/132995851-dfeb3072-4ab1-4a7d-970d-0135c392b992.png)

![2](https://user-images.githubusercontent.com/73854324/132995853-bd74ba2d-20ec-4d2b-bfc1-3106040f9662.PNG)

![3](https://user-images.githubusercontent.com/73854324/132995931-724a5d7c-01ab-4d0d-98ab-77e27a7faa3b.PNG)

**Comment by spread5789** [comment]
I've read other Issue posts, so I'll wait

**Comment by afonsojramos** [comment]
Currently tracking this issue on #980. Update will arrive in the next few days.
