### ISSUE TITLE
brew version is outdated 

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#1054]
Current version is 2.6.2 but when I try to install it with homebrew its 2.5.0
```
$ brew info khanhas/tap/spicetify-cli
khanhas/tap/spicetify-cli: stable 2.5.0
Command-line tool to customize Spotify client
```

and also, when is the new release?

**Comment by afonsojramos** [comment]
Until @khanhas is back we can't update that. Is there no option on brew to install what is currently on master?

**Comment by KorayUlusan** [comment]
The thing is it's not from this repo, but from [khanhas/homebrew-tap](https://github.com/khanhas/homebrew-tap/blob/HEAD/spicetify-cli.rb), which hardcoded `url "https://github.com/khanhas/spicetify-cli/archive/v2.5.0.tar.gz"`. So no, cannot install what is currently on master. 

I don't know if there is an technical reason behind this decision, but to me it makes more sense to have it in this repo.

**Comment by TheGeeKing** [comment]
> [khanhas/homebrew-tap](https://github.com/khanhas/homebrew-tap/blob/HEAD/spicetify-cli.rb), which hardcoded `url "https://github.com/khanhas/spicetify-cli/archive/v2.5.0.tar.gz"`.

If you check the PR someone changed the code to download the last version.

> and also, when is the new release?

No release date for the moment, but you can check the PR or the discord on how to have a prerelease of 2.6.3

**Comment by afonsojramos** [comment]
> he thing is it's not from this repo, but from khanhas/homebrew-tap

@KorayUlusan Unfortunately, I do not have access to that repo either

**Comment by nullmaxwell** [comment]
Opened an issue on that repo and linked it to this one. like @TheGeeKing said, there's an open pull request there that should solve the issue once it's approved.

**Comment by TheGeeKing** [comment]
Good. @KorayUlusan, you can close this issue now.

**Comment by itsmeow** [comment]
Updated now
