### ISSUE TITLE
Spotify v1.1.68 support

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#1056]
## ℹ Computer information

- Spotify version: 1.1.68.628.geb44bd66
- Spicetify version: 2.6.2

## 📝 Provide detailed reproduction steps (if any)

1. Can someone test this new Spotify version on Spicetify, because I don't know how to install the dev version.
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by afonsojramos** [comment]
@applekillerbyjames thank you for the issue, we are aware of the problem, but, please, next time be clearer while creating the issue.

**Comment by applekillerbyjames** [comment]
how do I install the dev version

**Comment by afonsojramos** [comment]
This version just came out, so Spicetify does not fully support it yet

**Comment by applekillerbyjames** [comment]
i know, but how do I install the dev version

**Comment by afonsojramos** [comment]
Just build from source, you can find instructions in the wiki

**Comment by TheGeeKing** [comment]
> i know, but how do I install the dev version

I made a thread on the discord: https://discord.gg/VnevqPp2Rr
