### ISSUE TITLE
User.css not found. Can't install.

### ISSUE THREAD

**Issue by ZeldrexK0DE** [khanhas/spicetify-cli#1057]
## ℹ Computer information

- Spotify version: 
1.1.67.586.gbb5ef64e
- Spicetify version: 1.1.0 (downloaded 2.6.2)

## 📝 Provide detailed reproduction steps (if any)

1. Install Spotify and SPicetify
2. ran "spicetify backup apply enable-devtool" in elevated powershell
3. Install Fails to find user.css even on new installed builds of spotify

### ✔️ Expected result

I do not know what this file does but it should work

### ❌ Actual result

PS C:\Users\Kairos> spicetify backup apply enable-devtool
spicetify v1.1.0
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
fatal open C:\Users\<user>\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

**Comment by ZeldrexK0DE** [comment]
EDIT:
Spicetify installed after running "spicetify upgrade" but i still do not know why it kept installing the 1.1.0 version on a new install.

**Comment by TheGeeKing** [comment]
Do `where spicetify` and remove the folder and your .spicetify folder. After retry a fresh installation of spicetify 2.6.2

**Comment by TonDar0n** [comment]
I had the same problem, resolved it by creating user.css (empty text file) in C:\Users<user>\AppData\Roaming\Spotify\Apps\zlink\css\.

**Comment by ZeldrexK0DE** [comment]
> Do `where spicetify` and remove the spicetify-cli folder and your .spicetify folder. After retry a fresh installation of spicetify 2.6.2

Already did this and it doesn't find the .css file regardless.

**Comment by TheGeeKing** [comment]
You are trying to download spicetify 2.6.4 right?

**Comment by afonsojramos** [comment]
Please delete the old Spicetify completely before installing the new version.

**Comment by afonsojramos** [comment]
Closing over inactivity.
