### ISSUE TITLE
2.6.3 | Spotify 

### ISSUE THREAD

**Issue by y0himba** [khanhas/spicetify-cli#1058]
## ℹ Computer information

- Spotify version: Latest
- Spicetify version: 2.6.3

## 📝 Provide detailed reproduction steps (if any)

1. …Upgrade Spicetify (Spicetify Upgrade)
2. …Spicetify restore backup apply
3. …Error

### ✔️ Expected result

_What is the expected result of the above steps?_ 
Spotify runs without an error

### ❌ Actual result

_What is the actual result of the above steps?_
SPicetify throws an error
## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/11462603/133594961-f247b756-9724-4718-adf2-d4cd6f013f73.png)
![image](https://user-images.githubusercontent.com/11462603/133594999-8451ed9a-2657-4a95-b29a-ce1f270b5163.png)

**Comment by Sellis97** [comment]
Did you get backup and Spotify version mismatch error? I upgraded like this: spicetify upgrade, spicetify backup and then spicetify restore backup apply and it worked.

**Comment by y0himba** [comment]
Nope. I ran Spicetify restore backup apply, now the webnowplaying extension
isn't working.

**Comment by TheGeeKing** [comment]
Check #983

**Comment by y0himba** [comment]
> Check #983

That's been there almost 30 days.  Mine was working fine until this morning, when I updated Spicetify, and I think it is related to the error.  

I removed and reinstalled Spotify, nothing. Downgraded, it works. I'm using Cleartext which #983 states they don't know if Cleartext uses WebNowPlaying, but it does, it's right in the settings. No other skins are working either with WebNowPlaying.js since this morning, was working fine until I ran updates. 


It appears my color was applied to Spotify though.
![image](https://user-images.githubusercontent.com/11462603/133635035-3aaad595-8040-419c-8fc2-732537d502a3.png)

**Comment by afonsojramos** [comment]
Yeah, we're still analyzing the Spotify changes from this update.

**Comment by y0himba** [comment]
> Yeah, we're still analyzing the Spotify changes from this update.

I figured as much.  Not too worried about it.  I just wanted to report the error.  Thanks for the update!

**Comment by iamMG** [comment]
Can anyone tell which is the latest Spotify app version that runs most issue-free? :)

**Comment by afonsojramos** [comment]
1.1.67 should be working fine @iamMG

**Comment by afonsojramos** [comment]
@y0himba can you re-check using 2.6.4?

**Comment by y0himba** [comment]
I just did, sorry just got home from work.

My theme applies, and webnowplaying.js is working, no errors.  

Thank you for the fix!
