### ISSUE TITLE
Playlist covers appearing instead of playlist name in sidebar

### ISSUE THREAD

**Issue by fowlis** [khanhas/spicetify-cli#1061]
## ℹ Computer information

- Spotify version: Latest I would assume, since it updated 5 mins ago when I launched it
- Spicetify version: 2.5.0-itsmeow-patch4 (according to the `spicetify -v` command)

## 📝 Provide detailed reproduction steps (if any)

1. Backed up spicetify after recent Spotify update
2. Reapplied spicetify
3. ???

### ✔️ Expected result

_What is the expected result of the above steps?_

Spotify should display the playlists as the correct names 

### ❌ Actual result

_What is the actual result of the above steps?_

Whatever this is:
![image](https://user-images.githubusercontent.com/84232621/133694767-16d0b6af-78cb-4064-9284-b76f4d933857.png)
Playlists look like this on the side
The folder name at the bottom is fine, but the playlists inside also have the issue

## 📷 Screenshots
_Are there any useful screenshots?_
 Above

**Comment by fowlis** [comment]
Config file screenshot if needed: 
![image](https://user-images.githubusercontent.com/84232621/133695233-08f6f7f0-683e-4618-aaf1-0062e8f2e142.png)

If I need to provide anything else for more info, please let me know

**Comment by TheGeeKing** [comment]
Update your spicetify: `spicetify upgrade`

**Comment by choolwe** [comment]
Tried this but still does not work. 

> Update your spicetify: `spicetify upgrade`

**Comment by Salaron** [comment]
Remove ```dribbblish.js``` from extensions.

**Comment by fowlis** [comment]
> Remove `dribbblish.js` from extensions.

Can confirm doing this worked (for me).

It threw this error while applying, but I can't figure out anything in the app that isn't working, so I won't worry about it.
![image](https://user-images.githubusercontent.com/84232621/133782917-8927489e-7cfa-42f8-9655-6dd98644241f.png)

Thank you for the reply, I don't use the Dribbblish theme anymore, but I didn't think leaving the extension would cause the issue.



> Update your spicetify: `spicetify upgrade`

I also tried this last night, but it didn't seem to upgrade to the new version.
![image](https://user-images.githubusercontent.com/84232621/133783131-23d763d8-0c88-4091-8f31-3c67c6c2bb9b.png)
I tried it again just now.

For now my playlists look fine again, so until something else breaks I'll not bother trying to figure out why it isn't updating correctly.

**Comment by choolwe** [comment]
> > Tried this but still does not work.
> > > Update your spicetify: `spicetify upgrade`
> 
> Do you have spicetify 2.6.3 now?

Yes i do have spicetify 2.6.3. have it. I have also tried removing  dribbblish.js and run the command `spicetify apply`. but still no change.

**Comment by TheGeeKing** [comment]
Open an issue and give information as your spicetify Spotify versions and config file
