### ISSUE TITLE
Lyrics-Plus continues to not work

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#1062]
## ℹ Computer information

- Spotify version: 1.1.68.628.geb44bd66
- Spicetify version: 2.6.3

## 📝 Provide detailed reproduction steps (if any)

1. load lyrics-plus page
2. something went wrong
3. reload page doesn't work

### ✔️ Expected result

_What is the expected result of the above steps?_
Page loads

### ❌ Actual result

_What is the actual result of the above steps?_
Page didn't load

## 📷 Screenshots

_Are there any useful screenshots?_
<img width="1440" alt="Screen Shot 2021-09-16 at 4 25 20 PM" src="https://user-images.githubusercontent.com/43358890/133700662-6e2dea4d-262b-4473-9a84-c06a3e5afec7.png">

**Comment by applekillerbyjames** [comment]
additionally there are issues with fullAppDisplay and pop-up lyric
<img width="739" alt="Screen Shot 2021-09-16 at 4 52 37 PM" src="https://user-images.githubusercontent.com/43358890/133703487-bd0badac-6433-4235-9c4b-5daa14081421.png">
s
<img width="739" alt="Screen Shot 2021-09-16 at 4 52 12 PM" src="https://user-images.githubusercontent.com/43358890/133703493-5db70d2e-3738-4bad-8dcd-0241514f9308.png">

.

**Comment by TheGeeKing** [comment]
We are currently working on that.

**Comment by imjustcaden** [comment]
> Hi @applekillerbyjames,
> 
> Can you please try to upgrade to spicetify 2.6.4 and see if it works?

I'm having the same issue and updating to 2.6.4 did not fix the issue

**Comment by TheGeeKing** [comment]
> I'm having the same issue and updating to 2.6.4 did not fix the issue

Is there any error in the devtool?

**Comment by PrivateGER** [comment]
The git version of spicetify throws this error in the dev console:
```
vendor~xpui.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at zs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at ra (vendor~xpui.js:29)
    at la (vendor~xpui.js:29)
    at aa (vendor~xpui.js:29)
    at oa (vendor~xpui.js:29)
    at xs (vendor~xpui.js:29)
    at ws (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at vs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at t.unstable_runWithPriority (vendor~xpui.js:29)
    at hi (vendor~xpui.js:29)
    at yi (vendor~xpui.js:29)
    at vi (vendor~xpui.js:29)
    at bs (vendor~xpui.js:29)
    at Un (vendor~xpui.js:29)
    at HTMLDocument.r (vendor~xpui.js:1)
(anonymous) @ vendor~xpui.js:1
wa @ vendor~xpui.js:29
Ua.o.componentDidCatch.n.callback @ vendor~xpui.js:29
zi @ vendor~xpui.js:29
Hi @ vendor~xpui.js:29
Is @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
hi @ vendor~xpui.js:29
Ps @ vendor~xpui.js:29
vs @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
hi @ vendor~xpui.js:29
yi @ vendor~xpui.js:29
vi @ vendor~xpui.js:29
bs @ vendor~xpui.js:29
Un @ vendor~xpui.js:29
r @ vendor~xpui.js:1
vendor~xpui.js:1 

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at zs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at ra (vendor~xpui.js:29)
    at la (vendor~xpui.js:29)
    at aa (vendor~xpui.js:29)
    at oa (vendor~xpui.js:29)
    at xs (vendor~xpui.js:29)
    at ws (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at vs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at t.unstable_runWithPriority (vendor~xpui.js:29)
    at hi (vendor~xpui.js:29)
    at yi (vendor~xpui.js:29)
    at vi (vendor~xpui.js:29)
    at bs (vendor~xpui.js:29)
    at Un (vendor~xpui.js:29)
    at HTMLDocument.r (vendor~xpui.js:1)
```

**Comment by applekillerbyjames** [comment]
2.6.4 did not work
@TheGeeKing

**Comment by KorayUlusan** [comment]
I'm currently on 2.6.4 and it kinda works for me. Just need to toggle "Noise Overlay" from settings 

Its better if you see it yourself, I'm bad at explaining such things. https://youtu.be/uan7zS_lsHY

**Comment by TheGeeKing** [comment]
> I'm currently on 2.6.4 and it kinda works for me. Just need to toggle "Noise Overlay" from settings 
> 
> 
> 
> Its better if you see it yourself, I'm bad at explaining such things. https://youtu.be/uan7zS_lsHY

Thank you very much for this quick fix. I think we will now be able to more easily fix it.

**Comment by applekillerbyjames** [comment]
<img width="1091" alt="Screen Shot 2021-09-23 at 8 20 20 PM" src="https://user-images.githubusercontent.com/43358890/134613130-8aa55d3a-5bd2-41af-be1c-7b631dbf1c47.png">
It still doesn't work without enabling noise overlay first.
On 2.6.5

**Comment by afonsojramos** [comment]
Try again at 2.6.6 @applekillerbyjames

**Comment by brenmadeit** [comment]
![image](https://user-images.githubusercontent.com/83563626/134845662-1843acbe-4f31-4d20-8314-7672e6cdc0e6.png)

I dont have the lyrics plus config tho how should i get it to toggle the noise overlay?

**Comment by TheGeeKing** [comment]
You should not have this issue anymore. Reinstall spicetify to 2.6.6

**Comment by brenmadeit** [comment]
> You should not have this issue anymore. Reinstall spicetify to 2.6.6

I upgrade to 2.6.6 already but still it didnt work

**Comment by brenmadeit** [comment]
update it worked. But the the progress bar went missing.

**Comment by afonsojramos** [comment]
@brenmadeit I believe this has to do with the theme itself. Be sure that the theme is up to date as well.
