### ISSUE TITLE
Lyrics-Plus going blank after change tab

### ISSUE THREAD

**Issue by surya27895** [khanhas/spicetify-cli#1063]
## ℹ Computer information

- Spotify version: 1.1.67.586.gbb5ef64e
- Spicetify version: 2.6.3
- Devtool Enabled

## 📝 Provide detailed reproduction steps (if any)

1. Open Spotify
2. Play Song
3. Open lyrics-plus tab
4. Open another tab like home tab etc.
5. Back to lyrics-plus tab again

### ✔️ Expected result

lyric-plus tab show lyrics instantly

### ❌ Actual result

lyrics-plus going blank

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/22859567/133718155-d16d404f-7fed-4c88-83bf-c917e80b48dc.png)

**Comment by TheGeeKing** [comment]
Hi, we are already aware of that issue. Someone posted three quick "fixes" on discord:

>https://discord.com/channels/842219447716151306/842819117630750790/888154906773553184
> Lyrics+ stop working (the option bar like Karaoke,... also disappear) after changing to other tabs (Playlists, Queue,...).
I found 3 ways to make it work again:
1. Reload Spotify (Ctrl+R) -> double click Lyrics (to show option bar again) -> Right click Synced option twice (maybe 4 times with left click).
2. Edit its config to show the option bar.
3. Turn off/on shuffle/repeat mode.
> Spotify for Windows
1.1.67.586.gbb5ef64e
Spicetify: 2.6.2 and 2.6.3
>video: https://streamable.com/42fxmc
