### ISSUE TITLE
Playlist covers are appearing instead of playlist name in sidebar

### ISSUE THREAD

**Issue by choolwe** [khanhas/spicetify-cli#1066]
## ℹ Computer information

- Spotify version: 1.168.628.geb44bd66
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. Open Spotify  

### ✔️ Expected result

Sidebar should show playlist names and not images

### ❌ Actual result

Sidebar is showing images

## 📷 Screenshots

_Are there any useful screenshots?_
![Spicetify Sidebar error](https://user-images.githubusercontent.com/6590366/133812478-e4fff573-65c2-41fc-8006-d1d0f220642d.jpg)

Config file (Changed extension to .txt for upload purpose):
[config-xpui.txt](https://github.com/khanhas/spicetify-cli/files/7186811/config-xpui.txt)

**Comment by Salaron** [comment]
Your current theme is "default" but you have ```fluent.js``` extension, that replaces playlist names with covers. Just remove it.

**Comment by TheGeeKing** [comment]
You should have read more deeply #1061 as it was a rather similar case.

**Comment by choolwe** [comment]
> Your current theme is "default" but you have a `fluent.js` extension that replaces playlist names with covers. Just remove it.

Thanks working well now.
