### ISSUE TITLE
Ability to add tracks/albums to beginning of queue

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1067]
Spotify's add to queue feature only adds to the end of the queue. It would be helpful to add tracks to the beginning of the queue as well because sometimes you have a lot of tracks added to a queue while you might still want to listen to a track right now.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by daksh2k** [comment]
I whipped up an [extension](https://github.com/daksh2k/Spicetify-backup/blob/master/Extensions/playNext.js). Check it out!
Currently it only works on tracks.
To use right-click on a track> Choose `Play Next`
