### ISSUE TITLE
Webnowplaying Theme not working

### ISSUE THREAD

**Issue by RobzHD** [khanhas/spicetify-cli#1069]
## ℹ Computer information

- Spotify version: 1.168.628.0
- Spicetify version: 2.6.4

### ✔️ Expected result

Theme to work after applying spicetify.

### ❌ Actual result

Theme not working.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/52350305/133886193-a53b0a11-ef10-4d6c-9f89-23d16964cb48.png)

**Comment by megaUwU-ui** [comment]
i think u should clean install bold spotify and spicetify cus my still work

**Comment by afonsojramos** [comment]
@RobzHD please provide more info, otherwise I'll have to close this ticket.

**Comment by RobzHD** [comment]
@megaUwU-ui Could you show me how?

**Comment by RobzHD** [comment]
@afonsojramos When I apply spicetify to Spotify, the theme won't connect at all. No input or anything shows up on that theme. That's about all there is to it.

**Comment by RobzHD** [comment]
@megaUwU-ui I have done what you told me. This has fixed my spicetify issues I had such as start-up etc and it's fully injected. But the theme still won't connect?

**Comment by TheGeeKing** [comment]
* Verify that your theme is in a folder in .spicetify/Themes
* The name is correct in config file
* Check the css files in devtool

**Comment by RobzHD** [comment]
> * Verify that your theme is in a folder in .spicetify/Themes
> * The name is correct in config file
> * Check the css files in devtool

Theme works with YouTube for some reason, but not Spotify.
