### ISSUE TITLE
[MacOS] Not able to apply updates

### ISSUE THREAD

**Issue by ohjasry** [khanhas/spicetify-cli#107]
Whenever I try to `spicetify update`, I get the following error message
`fatal open /Applications/Spotify.app/Contents/Resources/Apps/zlink/css/user.css: no such file or directory`

The issue was also described on [spectrum](https://spectrum.chat/spicetify/general/not-working-on-mac~5083c133-7b46-4fdc-afe8-62963a546e73)
Newest Spotify, MacOS and Spicetify version

**Comment by khanhas** [comment]
Can you access to this folder: `/Applications/Spotify.app/Contents/Resources/Apps/`?

**Comment by gusdaghost** [comment]
I have a similar issue on Fedora 31 with the latest spotify update (1.1.10.546.ge08ef575). 
```
spicetify v0.9.5
fatal open /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/zlink/css/user.css: no such file or directory
```
I have verified that `user.css` and its enclosing directories don't exist so its not a permissions issue.

**Comment by ohjasry** [comment]
Yes, the folder is filled with `.spa` files (including `zlink.spa`)

**Comment by khanhas** [comment]
Your spicetify received an update.
So you need to run `spicetify backup apply` every new Spotify update to customise on new app assets.

**Comment by gusdaghost** [comment]
@khanhas 
Output of `spicetify backup apply`
```
spicetify v0.9.5
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK                            
Preprocessing:
OK                            
OK                            
success Everything is ready, you can start applying now!
Copying raw assets:
fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/login.spa: permission denied
```
Then `spicetify update`
```
spicetify v0.9.5
Copying raw assets:
fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/login.spa: permission denied
```
Theming isn't applied

**Comment by khanhas** [comment]
@gusdaghost Change Spotify directory permission first:
```bash
sudo chmod 777 -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
```

**Comment by gusdaghost** [comment]
@khanhas didn't realise permissions had been changed after update, thanks
