### ISSUE TITLE
Fatal error with spicetify 2.6.4

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#1074]
## ℹ Computer information

- Spotify version: 
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. Install Latest Spicetify
2. Run `spicetify restore backup apply`
3. Press N
4. Run `spicetify backup`

### ✔️ Expected result

_Backup clearing and adding new backup for spotify_

### ❌ Actual result

_FATAL error_

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/81705406/134038500-9dbc06db-919b-42f5-ac3f-e6a96e0056d3.png)

**Comment by afonsojramos** [comment]
Please provide required Spotify version.

**Comment by TheGeeKing** [comment]
@Copimox please give your Spotify version as afonso asked. You can found it in the top left coner of Spotify in Help and About Spotify section. If you don't respond we will need to close this issue.

**Comment by afonsojramos** [comment]
Closing.
