### ISSUE TITLE
PopupLyrics black cover

### ISSUE THREAD

**Issue by Thiagoedlp151** [khanhas/spicetify-cli#1075]
## ℹ Computer information

- Spotify version: 1.1.68.628.geb44bd66
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. …Choose any song
2. Open PopupLyrcis extension
3. Mark the option "show cover" on the extension's settings
4. Black cover on the Popup window

### ✔️ Expected result

Show Cover on PopupLyrics extension.

### ❌ Actual result

Black cover 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/84394684/134041141-7fa4d2a7-6cdf-487a-9355-da035d2275de.png)

**Comment by TheGeeKing** [comment]
Hi @Thiagoedlp151,
You can now close this issue as #1087 fixed it in spicetify 2.6.5.
