### ISSUE TITLE
spicetifyWrapper Uncaught TypeError

### ISSUE THREAD

**Issue by hgjuk** [khanhas/spicetify-cli#1076]
## ℹ Win10

- Spotify version: Spotify for Windows
1.1.68.628.geb44bd66
- Spicetify version: spicetify v2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. apply Dribbblish Nord-dark theme
2. look at the console

### ✔️ Expected result
No errors
_What is the expected result of the above steps?_

### ❌ Actual result
```
Uncaught TypeError: Spicetify.Player.origin2.state.addProgressListener is not a function
    at waitOrigins (spicetifyWrapper.js:182)
    at r (vendor~xpui.js:1)
```
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/57110899/134062104-2a2b23e0-56bd-44a7-b9c0-c35642118d82.png)

_Are there any useful screenshots?_

**Comment by afonsojramos** [comment]
Can you verify using `spicetify -v` that you are running spicetify v2.6.4?

**Comment by applekillerbyjames** [comment]
same issue for me

**Comment by hgjuk** [comment]
It's a fresh install.
`PS C:\WINDOWS\system32> spicetify -v
2.6.4`
