### ISSUE TITLE
When run backup, command fails

### ISSUE THREAD

**Issue by eserkelleci** [khanhas/spicetify-cli#1078]
## ℹ Computer information

Edition	Windows 10 Pro
Version	21H1
OS build	19043.1237

- Spotify version: 1.1.67.586
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. run from command line 
> spicetify backup

### ✔️ Expected result

Just backup the existing spicetify

### ❌ Actual result
I got the below error.

```
C:\Users\eserk\spicetify-cli>spicetify backup
spicetify v2.6.4
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x711cb6]

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/preprocess.Start.func1(0xc00000b4d0, 0x2c, 0x0, 0x0, 0x81c700, 0xc00033a000, 0xc00025c050, 0x4f)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:94 +0x56
path/filepath.Walk(0xc00000b4d0, 0x2c, 0xc00010fd30, 0x0, 0x0)
        C:/Program Files/Go/src/path/filepath/path.go:499 +0x8a
github.com/khanhas/spicetify-cli/src/preprocess.Start(0x816614, 0x5, 0xc00000a450, 0x27, 0x101010101)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:93 +0x32e
github.com/khanhas/spicetify-cli/src/cmd.Backup(0x816614, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/backup.go:61 +0x845
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:186 +0x5b2

C:\Users\eserk\spicetify-cli>
```

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/3031096/134219556-b7ca02ec-caf3-44dc-917f-3125f9919f6e.png)

**Comment by casungo** [comment]
This has the same error as #968 (most recent issue)
If you installed Spotify from the Microsoft store spicetify will not work, you need to install Spotify from the [official site](https://www.spotify.com/us/download/windows/)

**Comment by eserkelleci** [comment]
I ve already installed Spotify from the official site and not from Microsoft Store.
You can see there is a user named "Afonso" (which is the developers name) in C drive in exception details.

**Comment by TheGeeKing** [comment]
Can you apply any theme or extension? Can you send the path of your Spotify?

**Comment by afonsojramos** [comment]
> You can see there is a user named "Afonso"

@eserkelleci That is just for debugging purposes.

Any updates? Should be fixed by doing a clean install by deleting `spicetify-cli` and `.spicetify` folders.

**Comment by afonsojramos** [comment]
Closing over inactivity.
