### ISSUE TITLE
Question: Applying themes to Spotify's web version?

### ISSUE THREAD

**Issue by tbergeron** [khanhas/spicetify-cli#108]
I don't know if it has ever been asked and if it's even possible but:

I use the web version and wonder if it would be possible to theme it?

I tried using user stylesheets but it seems a bit more complex to theme Spotify than I thought.

Any idea? Thanks!

PS: Feel free to just close this issue if it's too unrelated to the project.

**Comment by khanhas** [comment]
Yup. It is unrelated.
Web player is completely different from desktop app. They don't share any same code or stylesheet.
So, sorry.

**Comment by Bluscream** [comment]
userstyles.org
