### ISSUE TITLE
Home config broken

### ISSUE THREAD

**Issue by francescoaracu** [khanhas/spicetify-cli#1083]
## ℹ Computer information

- Spotify version: latest (1.1.68.632.g2b11de83), was happening also in 1.1.68.628
- Spicetify version: latest (2.6.4)

## 📝 Provide detailed reproduction steps (if any)

1. Click on "Home config" switch under profile menu
2. Options in home tiles are appearing
3. Customize and finish

### ✔️ Expected result

You can config as you wish your home page.

### ❌ Actual result

Single blocks in home page are not moving, options are not appearing.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/48188510/134320630-e257a13b-45e7-4e31-be04-3b7a015feb18.png)

**Comment by KorayUlusan** [comment]
cannot reproduce in 1.1.67

**Comment by afonsojramos** [comment]
Can confirm that it is happening in 1.1.68. But it is weird that it is working on 1.1.67 @KorayUlusan , can you send a screenshot?

**Comment by francescoaracu** [comment]
> Can confirm that it is happening in 1.1.68. But it is weird that it is working on 1.1.67 @KorayUlusan , can you send a screenshot?

IIRC, in 1.1.67 Home sections' titles are not clickable; in 1.1.68 they are clickable and this lends to a new page in which that particular section is displayed, with nothing else.

**Comment by KorayUlusan** [comment]
@afonsojramos of course, using 2.6.4 btw. 

<img width="1280" alt="Screen Shot 2021-09-25 at 12 27 42 PM" src="https://user-images.githubusercontent.com/65815347/134766698-6602a4a2-3653-4d6a-bcf6-192b34335570.png">

**Comment by itsmeow** [comment]
Still broken in #1125 on 1.1.69 btw, I didn't fix the hook

**Comment by Aldrichyl** [comment]
It's still broken I guess, too bad tbh the only use I have with it is to bring down the "Good Morning/Evening" thing that Spotify just refuses to fix. Can't they just give us the option to remove it ?

**Comment by itsmeow** [comment]
You can probably reproduce the effects using CSS manually if you want to hide a certain button.

**Comment by TheGeeKing** [comment]
![image](https://user-images.githubusercontent.com/58857539/135764748-ad96deae-74ec-44ea-ac39-a960eaf539ea.png)
![image](https://user-images.githubusercontent.com/58857539/135764750-6395699c-3291-4ced-bcf4-caedbc576b6f.png)

**Comment by itsmeow** [comment]
I have yet to fix the hook. It is not a high priority.

**Comment by TheGeeKing** [comment]
Can be close now https://github.com/khanhas/spicetify-cli/commit/9cd430f3a267414d071f790f55602e632d355790
