### ISSUE TITLE
Full App Display's progress bar and timestamp doesn't move

### ISSUE THREAD

**Issue by ktmtrash** [khanhas/spicetify-cli#1084]
## ℹ Computer information
os: Pop!_OS 21.04
- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. Open Spotify
2. Click on Full App Display on the top left or press F11

### ✔️ Expected result

Full App Display should open up and the progress bar and the timestamp should sync up with the actual song that is playing.

### ❌ Actual result

Full App Display does open up, however the progress bar is stuck on the timestamp before entering fullappdisplay and doesn't change even when changing the song through the controls

## 📷 Screenshots

https://user-images.githubusercontent.com/88025515/134329216-3e7b9ebc-032c-43f9-a915-2e3c5c20f2e9.mp4

**Comment by afonsojramos** [comment]
Yeah, this is related to a known problem over on #1062

**Comment by TheGeeKing** [comment]
Hi @ktmtrash,
You can now close this issue as #1087 fixed it in spicetify 2.6.5.
