### ISSUE TITLE
[macOS] Error on backup

### ISSUE THREAD

**Issue by nvelichkin** [khanhas/spicetify-cli#109]
I tried to install both versions (pre-built, brew). When trying to backup first time it returns me error
`spicetify v0.9.5`
`Backing up app files:`
`open /Applications/Spotify.app/Apps: no such file or directory`

If i try to create this folder it returns error 
`spicetify v0.9.5`
`Backing up app files:`
`error Cannot backup app files. Reinstall Spotify and try again.`

Any advices?

**Comment by khanhas** [comment]
Open `~/spicetify_data/config.ini` file
`spotify_path` field should be `/Applications/Spotify.app/Contents/Resources`
