### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by gibranlp** [khanhas/spicetify-cli#1091]
Is there a way i can make Spotify reload colors without having to close it and open it again?

Thanks

**Comment by daksh2k** [comment]
When you update the color.ini file or user.css you just need to run `spicetify update`
And reload the spotify client by pressing `Ctrl+Shift+R`
No need to close and open the client.

**Comment by gibranlp** [comment]
Is there an easy way to overrride the Ctrl+Shift+R? or maybe a way to script it?

**Comment by daksh2k** [comment]
Yes actually, Spicetify has a mode where it auto reloads for you. It is helpful when creating themes and extensions.
Run
`spicetify -l watch` for auto reloading when it detects changes in the theme file or add the flag `-e` for auto reloading on extensions.


I think you can check out all the available commands and their help information in spicetfy-cli by running. It has all this info and other useful commands!
`spicetify -h`

**Comment by afonsojramos** [comment]
I'll close this but you can keep discussing if you want.

**Comment by powwu** [comment]
For anyone on Linux having issues with `spicetify update` and finding this issue on Google, here's my solution to reloading:
```
spicetify watch -s &
sleep 1 && pkill spicetify
```
`spicetify watch -s` will update colors and then refresh the window without restarting. using `&` puts it in the background so the script can keep executing. `sleep 1 && pkill spicetify` waits one second and then kills all spicetify processes, so you don't have a stray `spicetify watch` process.

I recommend aliasing this in your shell's `.rc` file.

**Comment by ErfanRasti** [comment]
> spicetify watch -s &
> sleep 1 && pkill spicetify

When I run these spicetify says this and restarts the spotify:
```
success  Enabled DevTools!
 info  Restarted Spotify with debugger on. Waiting...
```

Is there a solution for this?

**Comment by Richard-Apps** [comment]
> > spicetify watch -s &
> > sleep 1 && pkill spicetify
> 
> When I run these spicetify says this and restarts the spotify:
> 
> ```
> success  Enabled DevTools!
>  info  Restarted Spotify with debugger on. Waiting...
> ```
> 
> Is there a solution for this?

@ErfanRasti You can use the -n flag to disable restarting spotify for this command, so: 

```
spicetify watch -s -n &
sleep 1 && pkill spicetify
```

**Comment by aervxa** [comment]
> Is there a solution for this?

That is the solution. Now if you update the color file, it should auto-reload without restarting the app

A better script that I found:

```bash
if pgrep -x spotify > /dev/null
then
    pkill -x spicetify
    spicetify watch -s &
fi
```

credits: [@Mikuwu](https://github.com/Mikyuwu)

**Comment by ErfanRasti** [comment]
> if pgrep -x spotify > /dev/null
> then
>     pkill -x spicetify
>     spicetify watch -s &
> fi

Even these make Spotify reopen (app closes completely and then opens again, but if I run this script multiple times after opening Spotify, it just reopens Spotify for the first time):

```
 info  Restarted Spotify with debugger on. Waiting...
 success  Updated theme's styles                                                                  
 success  Reloaded Spotify
```
Unless I change the `spotify.desktop` to open with the debugger by default, but even if I do this, there is another problem:
The script you've provided creates a `spicetify` process and leaves it running. Even if Spotify itself is closed, that process remains. It can be fixed by using an event loop to terminate the `spicetify` process when Spotify itself is closed, but I think it's a little overwhelming and uses extra resources all the time, and I would rather switch back to Spotify and press `CTRL+SHIFT+r` instead.
I actually wrote a script that switches to Spotify and presses `CTRL+SHIFT+R` using `ydotool`. I should mention that I'm on Hyprland. Another thing is that this script is a one-time run script with no background activity.
[The script](https://github.com/ErfanRasti/dotfiles/blob/f5fdcc28517f8fc4926bdbda92aca4cfcf0aea86/dotfiles/matugen/.config/matugen/scripts/spiceitfy_theme_apply.sh)

**Comment by aervxa** [comment]
I don't ever close my spotify, and even if I do, I always open it back later on, so spicetify running isn't really a big problem

Your script is pretty interesting icl, I've had some headaches with ydotool and never really used it again (probably because I was on KDE back then)

Kudos! I'm on Hyprland too 🤭

**Comment by ErfanRasti** [comment]
Spotify usually uses some CPU for me (10% - 20%), and on my personal laptop, power usage and battery life are crucial, so I usually close it when it is unused—combined with Spicetify, power usage even increases, especially when the laptop is on battery.

P.S.: Try `niri`, I'm trying that, and it's impressive.

**Comment by aervxa** [comment]
Understandable

ps: I actually looked into it, its cool asl, but it's not ready for a full switch

**Comment by powwu** [comment]
> > if pgrep -x spotify > /dev/null
> > then
> > pkill -x spicetify
> > spicetify watch -s &
> > fi
> 
> Even these make Spotify reopen (app closes completely and then opens again, but if I run this script multiple times after opening Spotify, it just reopens Spotify for the first time):
> 
> ```
>  info  Restarted Spotify with debugger on. Waiting...
>  success  Updated theme's styles                                                                  
>  success  Reloaded Spotify
> ```
> 
> Unless I change the `spotify.desktop` to open with the debugger by default, but even if I do this, there is another problem: The script you've provided creates a `spicetify` process and leaves it running. Even if Spotify itself is closed, that process remains. It can be fixed by using an event loop to terminate the `spicetify` process when Spotify itself is closed, but I think it's a little overwhelming and uses extra resources all the time, and I would rather switch back to Spotify and press `CTRL+SHIFT+r` instead. I actually wrote a script that switches to Spotify and presses `CTRL+SHIFT+R` using `ydotool`. I should mention that I'm on Hyprland. Another thing is that this script is a one-time run script with no background activity. [The script](https://github.com/ErfanRasti/dotfiles/blob/f5fdcc28517f8fc4926bdbda92aca4cfcf0aea86/dotfiles/matugen/.config/matugen/scripts/spiceitfy_theme_apply.sh)

@ErfanRasti Since posting my reply, I've actually moved to the former solution you've mentioned (modifying spotify.desktop). I have it set to run `spicetify watch -s`, and that way the process closes when the window closes, and I get the benefits of automatic reload.

**Comment by ErfanRasti** [comment]
@powwu Thanks for your comment, but there is a problem for me personally. I use some parameters in my `spotify.desktop` file. The exec line uses some arguments:
```desktop
Exec=spotify --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --uri=%u
```
If I use `Exec=spicetify watch -s` instead, these arguments won't be applied.
I've tried something like this too:
```desktop
Exec=spotify --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --uri=%u;sleep 1;spicetify watch -s
```
But it doesn't work, and the Spicetify doesn't update the theme afterward. I even removed `--uri=%u` too, but nothing again.

**Comment by rxri** [comment]
At this point it's a chromium/spotify's fault. We send a valid javascript via DevTools websocket. Why is it this buggy? We have no idea. Sometimes it works fine, sometimes it doesn't. On Linux it mostly fails. Linux version of Spotify is not "being taken care of" anyway...
