### ISSUE TITLE
High CPU/GPU usage when showing progress bar in FullAppDisplay

### ISSUE THREAD

**Issue by BluTree** [khanhas/spicetify-cli#1092]
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.6.5

## 📝 Provide detailed reproduction steps (if any)

1. Enable the progress display in FullAppDisplay

### ✔️ Expected result

Do not have a performance peak when displaying progress bar

### ❌ Actual result

The CPU usage is aroundly at 30% when displaying the progress and 10% for the GPU.
I checked the console, but there is nothing about the extension
![image](https://user-images.githubusercontent.com/11920536/134554880-4f49ddb6-344a-43ce-b7d1-339a3a98aa1c.png)

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/11920536/134554151-f40ae148-6cd9-49bd-b75d-f8c569397484.png)
Spotify without displaying the progress bar

![image](https://user-images.githubusercontent.com/11920536/134554251-27372532-fb89-41fc-881f-88eb270fca18.png)
Spotify while displaying the progress bar

**Comment by itsmeow** [comment]
Likely an issue on my side, I just redid the progress bar logic. May I ask what processor you have as well, just for context?

**Comment by BluTree** [comment]
I have an Intel i7-9750H (6 cores at 2.7/4.5GHz, it's a laptop CPU)

**Comment by TheGeeKing** [comment]
It will soon be fixed.

**Comment by SaberAkiyama** [comment]
Update v2.6.6. Check on Release link

**Comment by afonsojramos** [comment]
This has now been fixed in #1093!
