### ISSUE TITLE
If you open popupLyrics and press the 'x' button to close it, the renewal of the lyrics will stop.

### ISSUE THREAD

**Issue by Lseoksee** [khanhas/spicetify-cli#1096]
## ℹ Computer information

- Spotify version: 1.1.68.632
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. … open popupLyrics.
2. … Press the 'x' button to close it.
3. … open popupLyrics again

### ✔️ Expected result

The lyrics are updated properly.

### ❌ Actual result

The lyrics are not being updated.

**Comment by TheGeeKing** [comment]
Edit your spicetify version :)

**Comment by Lseoksee** [comment]
> Edit your spicetify version :)

Thank you.

**Comment by afonsojramos** [comment]
This is related to #1090 I believe. @itsmeow try popuplyrics to test maybe?
