### ISSUE TITLE
Shuffle+ do not show up

### ISSUE THREAD

**Issue by Aldrichyl** [khanhas/spicetify-cli#1097]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9-a
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. Install the Shuffle+ extension through Powershell
2. Copy Paste the Js File in the .spicetify folder
3. Run Spicetify Apply in Powershell

### ✔️ Expected result

_ See Shuffle+ in Spotify

### ❌ Actual result

_ No Shuffle+ available in Spotify

**Comment by itsmeow** [comment]
Can you try updating your Spotify to 1.1.68?

**Comment by Aldrichyl** [comment]
Yes, I just did and nothing has changed

**Comment by znicuuu** [comment]
For me on Spotify Version 1.1.68.632.g2b11de83 with Spicetify 2.6.6 it works fine.

**Comment by afonsojramos** [comment]
Can you show your config file?

**Comment by Aldrichyl** [comment]
Oh sorry I'm reinstalling Spicetify right now, if the problem remains I will get back to you, also how do I get to see my config file ?

**Comment by TheGeeKing** [comment]
`spicetify -c`

**Comment by AntServiceApps** [comment]
Had this issue a week ago but it's been fixed with the last version

**Comment by afonsojramos** [comment]
@Aldrichyl let us know if you're still having issues

**Comment by Aldrichyl** [comment]
It's solved now thank you!
