### ISSUE TITLE
pop up lyrics not working properly

### ISSUE THREAD

**Issue by shallowswimmer** [khanhas/spicetify-cli#1098]
The pop-up lyrics window disappears when the size is increased beyond a certain point.
Sometimes it gets stuck on one song and then I have to close and re-open Spotify for it to work properly.
The options menu should not be as transparent as it is imo too.

**Comment by TheGeeKing** [comment]
Please make a proper issue post with the template and all information required.

**Comment by afonsojramos** [comment]
Being tracked at #1090
