### ISSUE TITLE
Spicetify Cli Installation Location

### ISSUE THREAD

**Issue by derekstephen** [khanhas/spicetify-cli#11]
I am currently using Spicetify Cli on Windows.

I was wondering if there is there a way to install Spicetify and decide where it installs and stores the config and other files?

Sorry in advanced if it possible and I just see it!

**Comment by khanhas** [comment]
1. I guess you used PS install script to install Spicetify. On default, it extracts to `$HOME\.spicetify` folder.
If you want to install somewhere else, please download binary package in [release page](https://github.com/khanhas/spicetify-cli/releases).  Then extract anywhere you want.

2. Sorry, you can't change where to store config files, backup and user assets. But you can put your themes, extensions and apps in `spicetify-cli` executable folder (where you extract in first answer).

**Comment by derekstephen** [comment]
Thank you so much for what to do!

I'll close the issue since there isn't anything wrong!
