### ISSUE TITLE
Cannot detect prefs file location (I have put in prefs path in config.ini)

### ISSUE THREAD

**Issue by arcunofox** [khanhas/spicetify-cli#110]
Pretty much the title. I have tried reinstalling spicetify, rebooting, everything. I have given permissions to /opt/spotify AND /usr/bin/spotify but nothing works. If I run`spicetify apply` I get this:
`fatal unlinkat /opt/spotify/Apps/show.spa: permission denied`
And if I run `sudo spicetify apply` I get
`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini`
This is my config.ini (well, at least the [Settings] part)
`[Setting]
spotify_path     = /opt/spotify
prefs_path       = /home/daniel/.config/spotify/prefs/
current_theme    = SpicetifyDefault
color_scheme     = 
inject_css       = 1
replace_colors   = 1
overwrite_assets = 0`
I have done `find | grep "spotify/prefs$` and I get `./.config/spotify/prefs` but I have tried that; and it didnt work. So basically... I have followed all the available troubleshooting plus some of my own and I cant seem to fix anything. Any help?

**Comment by DanX951** [comment]
Did you find a solution? I'm also having this issue

**Comment by king-gizzard** [comment]
any updates on this? i'm running into the same issue, maybe some more insight as to why this was closed would be helpful to me and/or others who encounter this.

**Comment by TernishNoddy** [comment]
@king-gizzard the permission denied issue or the prefs location issue?

**Comment by Kingmk13** [comment]
Same problem here.
I think the second problem (prefs path not found) depend of the first one. With sudo, we use the root's "_config.ini_" (_**/root/.config/spicetify/config.ini**_) and it is indeed not configured. The one we configure with "_spicetify config..._" is the normal user's "_config.ini_" (for me it is "_**/home/kingmk13/.config/spicetify/config.ini**_").
**So the real problem is something related to the "_permission denied_".**

**Comment by TernishNoddy** [comment]
Same versions without issues here - try double checking if you gave the right [permissions](https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur).

It would be nice with the option to pass an argument like `--config /file/location/here` to solve the root config issue. Ran into it when I called spicetify in a pacman hook.

**Comment by Kingmk13** [comment]
Sorry, I missed the step with the permission. That (_sudo chmod 777 /opt/spotify -R_) solved my problem of "_permission denied_".
Thank you for your help !

**Comment by aamodvarma** [comment]
Try running it without the sudo part and only "spicetify apply"

**Comment by zubayrrr** [comment]
> Try running it without the sudo part and only "spicetify apply"

yay that worked!

**Comment by TimestaticYT** [comment]
@Kingmk13 Thank you! This solved it for me. I am using Manjaro Gnome Kernel 5.11
