### ISSUE TITLE
global.d.ts file doesn't include Spicetify.Locale

### ISSUE THREAD

**Issue by theRealPadster** [khanhas/spicetify-cli#1102]
## ℹ Computer information

- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. Open CustomApps/reddit/index.js
2. It contains references to `Spicetify.Locale`
```js
const typesLocale = {
    album: Spicetify.Locale.get("album"),
    song: Spicetify.Locale.get("song"),
    playlist: Spicetify.Locale.get("playlist"),
};
```
3. Open global.d.ts and search for "Locale"
4. No results

### ✔️ Expected result

Expecting to have type definitions for `Spicetify.Locale`.

### ❌ Actual result

There are no type definitions for `Spicetify.Locale`.

**Comment by afonsojramos** [comment]
Not sure if this is even needed, or if it even makes sense since Spotify might change these at will.
A quick hop at DevTools shows some examples of what you can find:
![image](https://user-images.githubusercontent.com/19473034/134900342-b9e3bd2d-ec90-4ab1-915f-d8f184ffb704.png)

**Comment by afonsojramos** [comment]
Closing this issue. If you need to reopen it let me know @theRealPadster

**Comment by theRealPadster** [comment]
Is there any way to get them included, or it's an internal Spotify thing and doesn't have any definitions to begin with? Not the end of the world but it is kind of annoying trying to work with TypeScript/linting when they're not present.
