### ISSUE TITLE
Lyrics plus showing something went wrong

### ISSUE THREAD

**Issue by brenmadeit** [khanhas/spicetify-cli#1103]
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.6.6

### ✔️ Expected result
lyrics plus working and loading lyrics
_What is the expected result of the above steps?_

### ❌ Actual result
shows something went wrong and reloading button didnt work
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/83563626/134871533-fc80e77e-16e1-4625-975e-394df7aa0ffb.png)

**Comment by Anguslam228** [comment]
Same issue for me too. Also happens for new-release custom app as well.

**Comment by brenmadeit** [comment]
> Same issue for me too. Also happens for new-release custom app as well.

but for reddit it works for me tho. And I cant get the lyrics plus config to appear.

**Comment by afonsojramos** [comment]
Please run `spicetify enable-devtool` and then check out the console to see what it says.

**Comment by Anguslam228** [comment]
I get:
success DevTool enabled!
But same issue appears when I restart Spotify.

**Comment by afonsojramos** [comment]
Okay, but now right click somewhere on Spotify and open DevTools.
![image](https://user-images.githubusercontent.com/19473034/134901190-e268cae6-c73a-49a9-86ec-12c52071f35a.png)
Navigate to console afterwards.
![image](https://user-images.githubusercontent.com/19473034/134901239-e33ce860-8907-42b6-9097-a467dcab7a49.png)

**Comment by Anguslam228** [comment]
<img width="778" alt="Screen Shot 2021-09-27 at 10 05 41 AM" src="https://user-images.githubusercontent.com/47729178/134954174-1eff644f-47de-4a7d-9688-60a008dbdd3d.png">
Looks like the same thing for me

**Comment by afonsojramos** [comment]
@Anguslam228 @Unixkitty you have outdated Spicetify code for some reason. I'd recommend a full reinstall of spicetify by first deleting `.spicetify` and `spicetify-cli`. Let me know if it works!

**Comment by Anguslam228** [comment]
@afonsojramos I ran the following:
cd ~
rm -r spicetify-cli
rm -r .spicetify

But it seems that I don't have .spicetify, since I get this:
rm: .spicetify: No such file or directory

I still have a spicetify_data folder. Should I remove that before the reinstall?

**Comment by TheGeeKing** [comment]
Spicetify folders are normally in C:\Users\USERNAME

**Comment by afonsojramos** [comment]
@TheGeeKing that is for Windows.

@Anguslam228 for linux it should be `~/.config/spicetify` I believe.

**Comment by Anguslam228** [comment]
Ok I removed both folders and reinstalled, but the same issue appears. 

I first tried installing with homebrew, but the following error appeared:
![image](https://user-images.githubusercontent.com/47729178/134967345-ef4ca50f-f9fd-47ca-81f8-866c1a696ae6.png)

So instead, I installed using the shell method, which showed no errors. However, when I try to add lyrics-plus again, the 'Something went wrong' error appears again.

**Comment by afonsojramos** [comment]
Okay, I see what is happening here... This is due to the fact that the brew version is out of date... 
Right now we are not able to update it, so I'd ask you to install through this method:
```
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
```
Maybe try uninstalling from brew first though!

**Comment by Loudsquid** [comment]
Hey, also having an issue with Lyrics plus saying something went wrong. Any help would be appreciated. Here is my Dev Console if that helps.
![Capture](https://user-images.githubusercontent.com/56938800/134983994-e9c36797-faa8-4158-8984-9d557563e617.PNG)

**Comment by TheGeeKing** [comment]
Delete spicetify-cli and .spicetify folder and reinstall spicetify.

**Comment by Anguslam228** [comment]
Ok it's fixed now. Turns out i didn't properly uninstall from brew previously. Thanks!

**Comment by brenmadeit** [comment]
![image](https://user-images.githubusercontent.com/83563626/135000739-a8f5a433-e017-47f7-bc7c-bb77a466db1b.png)

**Comment by brenmadeit** [comment]
update: I reinstalled by deleting .spicetify and spicetify-cli and it works prefectly. Thanks for the help, btw the code up there to reinstall didnt work for me, I went to the original way to install it instead.

**Comment by Unixkitty** [comment]
Can confirm that updating to latest git commit resolved the problems. 
73be35fc61f9fb2e22b90acc86f53515e3664a9a -> 74aa8764eea5aeabf876ec23003f8801331899c4

**Comment by Pkapakapa** [comment]
![Untitled](https://user-images.githubusercontent.com/91627695/135320444-7c2bb8eb-8572-4a65-9608-9cbd762dd705.png)

**Comment by afonsojramos** [comment]
> 
> 
> update: I reinstalled by deleting .spicetify and spicetify-cli and it works prefectly. Thanks for the help, btw the code up there to reinstall didnt work for me, I went to the original way to install it instead.

It depends on the platform and what you have really, no solution is the same for everyone 🤷‍♂️

@Pkapakapa that seems to be a different issue. Please create another issue with more details as I'll close this one.
