### ISSUE TITLE
Song progress bar went missing

### ISSUE THREAD

**Issue by brenmadeit** [khanhas/spicetify-cli#1107]
## ℹ Computer information

- Spotify version:  2.6.6
- Spicetify version: 1.1.68.632.g2b11de83

## 📝 Provide detailed reproduction steps (if any)

1. … 
2. …
3. …

### ✔️ Expected result
Song progress bar appearing
_What is the expected result of the above steps?_

### ❌ Actual result
Song progress bar went missing.
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/83563626/135035074-00112b6e-8f10-4c40-93cc-595554782846.png)

_Are there any useful screenshots?_

**Comment by TheGeeKing** [comment]
It is mostly due to your theme.

**Comment by brenmadeit** [comment]
> It is mostly due to your theme.
but from my last thread other peoples with the same theme is working

**Comment by Ballasi** [comment]
Are you using the Dribbblish theme? If so, make sure you [correctly apply the dribbblish.js script](https://github.com/khanhas/spicetify-cli/issues/915#issuecomment-890334810), this is what loads the progress bar.

Hope that helps!

**Comment by brenmadeit** [comment]
Yes thanks for pointing it out, my bad here for not noticing.

> Are you using the Dribbblish theme? If so, make sure you [correctly apply the dribbblish.js script](https://github.com/khanhas/spicetify-cli/issues/915#issuecomment-890334810), this is what loads the progress bar.
> 
> Hope that helps!
