### ISSUE TITLE
zsh: command not found

### ISSUE THREAD

**Issue by Anguslam228** [khanhas/spicetify-cli#1108]
## ℹ Computer information

- Spotify version: 
Spotify for macOS (Apple Silicon)
1.1.68.632.g2b11de83

- Spicetify version: latest (unable to check)

## 📝 Provide detailed reproduction steps (if any)

Deleted and reinstalled Spotify
Reinstalled Spicetify using shell method for Mac multiple times

### ✔️ Expected result

Cannot access Spicetify commands
Tried uninstalling and reinstalling multiple times, but the same issue happens after a while

### ❌ Actual result

![image](https://user-images.githubusercontent.com/47729178/135048251-0007fa18-637d-4070-8133-82d3ac159fb0.png)

**Comment by TheGeeKing** [comment]
Please do a proper post with the versions you are using and not just "latest".

Try to manually delete spicetify folders: on windows there is a .spicetify and spicetify-cli might also be 2 folders on mac.

**Comment by Anguslam228** [comment]
@TheGeeKing Sorry for the missing details. I'm not sure how to check my spicetify version, but I have updated my Spotify version above. Regarding your comment, should I manually delete the two folders and try reinstalling again?

**Comment by TheGeeKing** [comment]
Yeah you should delete those folders as it seems spicetify isn't correctly installed. Check the installation guide to install spicetify

**Comment by afonsojramos** [comment]
Previously we would recommend MacOS users to install through brew, but we haven't been able to update it due to lack of permissions.

As a last resource, try to install using brew `brew install khanhas/tap/spicetify-cli` but then run `spicetify upgrade`

**Comment by Anguslam228** [comment]
> Previously we would recommend MacOS users to install through brew, but we haven't been able to update it due to lack of permissions.
> 
> As a last resource, try to install using brew `brew install khanhas/tap/spicetify-cli` but then run `spicetify upgrade`

This seems to have solved the problem now. Thanks!

**Comment by afonsojramos** [comment]
Awesome, anytime 🎉
