### ISSUE TITLE
Refresh spicetify on xrdb refresh

### ISSUE THREAD

**Issue by chrisJuresh** [khanhas/spicetify-cli#1110]
## Reread the colors used by spicetify whenever pywal is activated

_Instead of having to kill and relaunch (spicetify apply) add a way for it to reread xrdb whenever a new wallpaper is added by pywal so you can switch wallpapers quickly to show off the different colors generated by it._

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by afonsojramos** [comment]
The only way I see this being possible of being implemented is with JS as an extension.

**Comment by khanhas** [comment]
One option is that you always launch Spotify with remote debugging mode on (add `--remote-debugging-port=9222` after Spotify binary). Then whenever you want to reload without restarting Spotify, just use this script:
```bash
url=$(curl http://localhost:9222/json/list | jq -r ".[] | .webSocketDebuggerUrl")
wscat --connect $url --execute '{\"id\":1,\"method\":\"Page.reload\"}'
```
Required packages : `jq` and `node-ws`
