### ISSUE TITLE
1.1.69 - Something went wrong

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#1112]
## ℹ Computer information

- Spotify version: 1.1.69.612.gb7409abc
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. spicetify apply
2. black screen
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
Spicetify applies correctly
### ❌ Actual result

_What is the actual result of the above steps?_
Spicetify shows a blank screen
## 📷 Screenshots

_Are there any useful screenshots?_
<img width="742" alt="Screen Shot 2021-09-29 at 9 06 57 AM" src="https://user-images.githubusercontent.com/43358890/135307177-37946304-d71f-422c-ab1f-cb1917c03951.png">

**Comment by applekillerbyjames** [comment]
<img width="1552" alt="Screen Shot 2021-09-29 at 9 09 27 AM" src="https://user-images.githubusercontent.com/43358890/135307306-acc6d399-3363-4e20-a9b4-a1984d31a063.png">

**Comment by TheGeeKing** [comment]
Can you send a screenshot of the comma that cause the issue, please?

**Comment by applekillerbyjames** [comment]
![Uploading Screen Shot 2021-09-29 at 9.31.20 AM.png…]()

**Comment by applekillerbyjames** [comment]
<img width="1552" alt="Screen Shot 2021-09-29 at 9 31 20 AM" src="https://user-images.githubusercontent.com/43358890/135310897-b237008c-a9ac-4f73-9c53-f727b04da2df.png">

**Comment by afonsojramos** [comment]
Oh no 😰

**Comment by amd64fox** [comment]
@afonsojramos 
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.69.612.gb7409abc-16.exe

**Comment by itsmeow** [comment]
output from my custom hook debugger build:
```
warning Hook fail: Spicetify.Player.origin2
warning Failed to find API promises (Spicetify.Platform hook fail)
warning Hook fail: Spicetify.Menu
warning Hook fail: Spicetify._sidebarItemToClone
warning Hook fail: Home config 1
```

**Comment by LittleHaku** [comment]
Isn't there a way to go back to 1.1.68 until the new spicetify version comes?

**Comment by SaberAkiyama** [comment]
Guess I downgrade to 1.1.68

**Comment by TheGeeKing** [comment]
> Isn't there a way to go back to 1.1.68 until the new spicetify version comes?

For windows:
https://www.filepuma.com/download/spotify_1.1.68.632-29974/

```
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

```

**Comment by SaberAkiyama** [comment]
> > Isn't there a way to go back to 1.1.68 until the new spicetify version comes?
> 
> For windows: https://www.filepuma.com/download/spotify_1.1.68.632-29974/
> 
> ```
> del %localappdata%\Spotify\Update
> 
> mkdir %localappdata%\Spotify\Update
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":D
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":R
> ```

I'm already modified it
