### ISSUE TITLE
How do i modify the gradient on the top of every page?

### ISSUE THREAD

**Issue by C0DK** [khanhas/spicetify-cli#112]
Essentially related to this issue, but it's on the outdated version of the system. I'd love if this gradient was some how added to the colors / user.css - i've removed all gradient i could find but it still shows up. 
https://github.com/khanhas/Spicetify/issues/65

On my system it creates an almost identical box between the two, due to the colors... somehow.. 
![image](https://user-images.githubusercontent.com/9048078/69014044-8df2f900-0986-11ea-827e-e16d7628e58f.png)

It isn't the best. Do you have a clue which class i have to modify, and even better, how i generally find these classes? the color is `2e3340` but ought to be `2e3440`

**Comment by khanhas** [comment]
```
.Header__background-color, .glue-page-header__background-color {
    background-image: linear-gradient(to bottom, <color 1>, <color 2>) !important;
}
```
That should do as long as you don't have any solid background on top of them.
Also next time, keep CSS customising questions on Spectrum. More people can help you and you can get help faster.
