### ISSUE TITLE
Lyrics Plus showing Something went wrong page after upgrading to Spicetify Version 2.7.0

### ISSUE THREAD

**Issue by znicuuu** [khanhas/spicetify-cli#1126]
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.7.0

## 📝 Provide detailed reproduction steps (if any)

1. spicetify upgrade
2. spicetify restore backup apply
3. …

### ✔️ Expected result

Lyrics Plus working normally

### ❌ Actual result

Lyrics Plus Page showing "Something went wrong"

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/73033465/135617804-0d8ef190-7867-40bc-b184-15914292dd02.png)

**Comment by TheGeeKing** [comment]
Spicetify 2.7.0 is only for Spotify >=1.1.69

https://github.com/khanhas/spicetify-cli/releases/tag/v2.7.0

**Comment by znicuuu** [comment]
> Spicetify 2.7.0 is only for Spotify >=1.1.69
> 
> https://github.com/khanhas/spicetify-cli/releases/tag/v2.7.0

Oh, I didn't notice. Sorry

**Comment by bilgehnbilge** [comment]
Same issiues on 2.7.0 Spotify 1.1.69.612.gb7409abc

**Comment by TheGeeKing** [comment]
Not same issue

**Comment by guttitto** [comment]
i had the same issue but firstly i forgot to replace the lyricsplus folder by the new one and do spicetify apply. after that it works as expected.

**Comment by bilgehnbilge** [comment]
> 
> 
> i had the same issue but firstly i forgot to replace the lyricsplus folder by the new one and do spicetify apply. after that it works as expected.

It's work me thanks
