### ISSUE TITLE
How to fully uninstall spicetify

### ISSUE THREAD

**Issue by Anguslam228** [khanhas/spicetify-cli#1128]
## ℹ Computer information

- Spotify version: unknowon (can't open because it keeps crashing)
- Spicetify version: 2.7.0

## 📝 Provide detailed reproduction steps (if any)

Trying to uninstall completely and then reinstall, but it's not being removed.

1. removed spicetify_data folder 
2. ran ' brew uninstall khanhas/tap/spicetify-cli '

### ❌ Actual result

After the steps above, I can still run 'spicetify' command in my terminal and generate spicetify_data again. Also, Spotify app immediately crashes when I open it.

**EDIT: I still cannot remove spicetify completely, but it seems that Spotify crashes for one specific user login. I tried signing out from my Spotify account and logging in with another profile, then Spotify does not crash. Any possible explanation for this?

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/47729178/135693781-1b2b24e2-2ce4-4822-9078-819258104750.png)

**Comment by itsmeow** [comment]
Brew failed to uninstall it, as you can see by "No available formula or cask". Try `brew uninstall spicetify-cli`, or maybe `brew uninstall SpicetifyCli`, without the tap stuff.
You can run `which spicetify` to find where it is on the filesystem.

As for the crashing, maybe check the Spotify install folder, it has a few logs there that might have some information.

**Comment by Anguslam228** [comment]
> Brew failed to uninstall it, as you can see by "No available formula or cask". Try `brew uninstall spicetify-cli`, or maybe `brew uninstall SpicetifyCli`, without the tap stuff. You can run `which spicetify` to find where it is on the filesystem.
> 
> As for the crashing, maybe check the Spotify install folder, it has a few logs there that might have some information.

I was able to manually delete using `which spicetify`, and the Spotify logs helped me fix the crash. Thanks!
