### ISSUE TITLE
romaji.mjs extension example on wiki still works?

### ISSUE THREAD

**Issue by UltimateLight** [khanhas/spicetify-cli#1130]
I tried following the steps, but it seemed to not work, am I doing something wrong or is the example outdated?

**Comment by itsmeow** [comment]
It appears it still injects it with `type=module`. Maybe you're doing something wrong?
See: https://github.com/khanhas/spicetify-cli/blob/57fa6d5df80be69b69c65ed4f8b1ca3e942a98ef/src/apply/apply.go#L90-L94

**Comment by TheGeeKing** [comment]
Any update @UltimateLight?
