### ISSUE TITLE
FullAppDisplay: Add option for lyrics

### ISSUE THREAD

**Issue by MudkipBanana** [khanhas/spicetify-cli#1131]
## 📝 Provide a description of the new feature
Add an option to enable lyrics similar to LyricsPlus or PopupLyrics in FullAppDisplay
_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_
The expected behavior of the proposed feature is to show lyrics underneath the song information. This could be used to sing along to songs you don't know the lyrics to, without the UI of the app distracting you.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by CharlieS1103** [comment]
Would probably be more efficient to just make a full screen feature for lyrics plus

**Comment by TheGeeKing** [comment]
hi @MudkipBanana,
I made what you were asking for: https://github.com/TheGeeKing/spicetify-extensions/tree/main/toggleLyricsPlusFullscreen
I Will soon check to implement it directly in Lyrics-plus 😀
