### ISSUE TITLE
Wikipedia Integration

### ISSUE THREAD

**Issue by shallowswimmer** [khanhas/spicetify-cli#1132]
## 📝 Provide a description of the new feature
Basically this extension would add the functionality to display the Wikipedia page of the album or the artist depending on if it pressed on the artist page or the album page, show all the info and pretty much that because I always find myself going on Wikipedia for an album to know more about it and I'm sure other people do too so yeah.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

It will show the Wikipedia page or the info from it depending if its pressed on the artist page in that case it will show the info about artist's Wikipedia page or if done on an album show info about it.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by TheGeeKing** [comment]
@CharlieS1103 you can display info about artist in `artist-artistOverview-about` and for albums there is no place so you can maybe create one or use the Friend Activity Panel and display on the right Wikipedia infos

**Comment by TheGeeKing** [comment]
Can be closed I think @shallowswimmer? It Will still be updated and improved
