### ISSUE TITLE
spicetify upgrade on Windows doesnt have an extra slash to resemble path

### ISSUE THREAD

**Issue by CryoRenegade** [khanhas/spicetify-cli#1133]
## ℹ Computer information

- Spotify version: N/A
- Spicetify version: 2.6.7

## 📝 Provide detailed reproduction steps (if any)

spicetify upgrade (on versions below current)
    Fetch latest release info:
    OK
    info Current version: 2.6.7
    info Latest release: 2.7.0
    Downloading:
    fatal open C:\Tempspicetify-2.7.0.zip: Access is denied.

### ✔️ Expected result

Spicetify should properly upgrade

### ❌ Actual result

It does not because it wants to put a file in the direct C: directory

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/23038070/135775282-7039c8dd-2287-4ffd-9ab9-b53db856e1f5.png)

_Are there any useful screenshots?_

**Comment by TheGeeKing** [comment]
Hi @CryoRenegade,

Try to completely uninstall spicetify (delete .spicetify and spicetify-cli folder) and install spicetify with `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
` should be good

**Comment by CryoRenegade** [comment]
> Hi @CryoRenegade,
> 
> Try to completely uninstall spicetify (delete .spicetify and spicetify-cli folder) and install spicetify with `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
> ` should be good

Yeah that's what I did

**Comment by ririxidev** [comment]
Working on it.
