### ISSUE TITLE
Lyrics Plus only occasionally works even with correct token

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#1134]
## ℹ Computer information

- Spotify version: 1.1.69.612.gb7409abc
- Spicetify version: 2.7.0

## 📝 Provide detailed reproduction steps (if any)

1. load lyrics-plus
2. error face
3. re-enter token
4. relaunch spotify 
5. lyrics-plus works

### ✔️ Expected result

_What is the expected result of the above steps?_
lyrics plus works immediately

### ❌ Actual result

_What is the actual result of the above steps?_
lyrics plus shows error

## 📷 Screenshots

_Are there any useful screenshots?_
<img width="742" alt="Screen Shot 2021-10-03 at 4 47 59 PM" src="https://user-images.githubusercontent.com/43358890/135777651-2dde44fb-3f16-447e-8501-d33da611a66d.png">

**Comment by applekillerbyjames** [comment]
<img width="736" alt="Screen Shot 2021-10-03 at 4 57 53 PM" src="https://user-images.githubusercontent.com/43358890/135777807-e899d660-e606-4f88-add3-b6d23c8bcfe7.png"
<img width="736" alt="Screen Shot 2021-10-03 at 4 58 03 PM" src="https://user-images.githubusercontent.com/43358890/135777808-a6589d76-fe91-4155-bb70-3b81e806cfaa.png">
>

**Comment by TheGeeKing** [comment]
Can you send a screenshot of your token in lyrics plus settings please

**Comment by applekillerbyjames** [comment]
<img width="563" alt="Screen Shot 2021-10-04 at 1 12 13 PM" src="https://user-images.githubusercontent.com/43358890/135918011-dafbb79a-ef4a-4f94-adfb-7d467af16662.png">

**Comment by TheGeeKing** [comment]
It is working no? Seems like you have lyrics in background

**Comment by kotobuki09** [comment]
It's maybe a one-time thing. Cause I also got a similar issue like that today. I know for sure the song have lyrics cause I listen to it many time, but it's showing no lyrics for me as well. After restart, it's working back to normal
