### ISSUE TITLE
Restore naming convention for added albums

### ISSUE THREAD

**Issue by depascalis** [khanhas/spicetify-cli#1136]
## 🤬 Opening rant
_For some reason, Spotify has made the genius move to remove the artist name when you add an album to your library / playlist folder. I don't know if this is a bug, but seeing how Spotify has been evolving lately I bet it's a feature. Earlier they reversed the order in the naming convention to "Album – Artist" depending on how you saved the album which was bad enough. I know some people at Spotify so I asked them to talk with the devs about it. The answer was that it wasn't possible to restore the naming convention due to how the client was built, what a load of bull._

## 📝 Description of the new feature  

When adding an album (collection of tracks) to your library or a playlist folder, the name of the playlist should be "Artist – Album" (notice the `&ndash;`). Keep in mind that there are many ways to save albums.
Is this something Spicetify can do?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by afonsojramos** [comment]
Sorry, I'm all for it someone developing this. But I don't see it as being relevant to this repo.
