### ISSUE TITLE
Unable to save playlist with custom image cover

### ISSUE THREAD

**Issue by Livewire13** [khanhas/spicetify-cli#1149]
## ℹ Computer information

- Spotify version: Spotify for macOS (Intel)
                            1.1.69.612.gb7409abc
- Spicetify version: v.2.7.0

## 📝 Provide detailed reproduction steps (if any)

1. Create new playlist 
2. Edit details of playlist
3. Add a GIF for playlist cover
3. Clicking on save
4. Error: Failed to save playlist changes. Please try again.

### ✔️ Expected result

Edited playlist has custom cover 

### ❌ Actual result

Error when saving: Failed to save playlist changes. Please try again.

## 📷 Screenshots
![error](https://user-images.githubusercontent.com/69797396/136649023-d79624c0-1446-4808-a137-fff6bb2ccb4d.png)
 
"edit - Removed png, png works fine, only gif has a problem"

**Comment by AshleyGainey** [comment]
You cannot use GIFs for a playlist cover picture.

**Comment by ririxidev** [comment]
@afonsojramos to be closed.
