### ISSUE TITLE
Profile picture replacement will not save

### ISSUE THREAD

**Issue by 3raxton** [khanhas/spicetify-cli#115]
First off, great work on the spicetify cli, I could not appreciate it more! 

A problem that I wanted to mention which I'm dealing with is the saving of a new photo. When I go to my profile and upload a new display image, it shows as replaced, but after refreshing, the new image doesn't show. Is there a way to write this into the code that I could do on my own, or is there more to it?

If you could let me know, that would be great. Thanks again for all the work you've done!

**Comment by khanhas** [comment]
Cannot reproduce at any version.
