### ISSUE TITLE
Close/Minimise to system tray for Linux

### ISSUE THREAD

**Issue by Argus-Kan** [khanhas/spicetify-cli#1151]
## 📝 Adding the ability to close (or minimise) Spotify to the system tray for the Linux client.

Even though Spotify goes through the hassle of making a client for Linux, they didn't give it the ability to close to the system tray like it is possible in Windows, it's a shame that such a basic feature is missing from the Linux client. I think a lot of people would appreciate it if this feature was added.

**Comment by theRealPadster** [comment]
I don't think this is something that Spicetify is capable of doing, but feel free anyone to correct me if I'm wrong.

**Comment by khanhas** [comment]
theRealPadster is right. Spicetify can't modify or add new feature at window level.
