### ISSUE TITLE
Didn't work in windows 8.1

### ISSUE THREAD

**Issue by VoXaN24** [khanhas/spicetify-cli#116]
I have this error :
https://i.imgur.com/a2gD7Dq.png

**Comment by khanhas** [comment]
Please upgrade Powershell version to the latest.
Or extract the downloaded package yourself.

**Comment by VoXaN24** [comment]
> 
> 
> Please upgrade Powershell version to the latest.
> Or extract the downloaded package yourself.

My windows has all update

**Comment by khanhas** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=54616
