### ISSUE TITLE
CSS Mapping

### ISSUE THREAD

**Issue by Sahil-Deshpande** [khanhas/spicetify-cli#1171]
## ℹ Computer information

- Spotify version: 1.1.70.610.g4585142b
- Spicetify version:  2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Right-clicking on a song/playlist/etc. gives black text that is barely readable.
2. …
3. …

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/89779119/137583781-1afc4335-8c74-4d6e-89a2-46dd6ca1d2c2.png)

### ❌ Actual result

![image](https://user-images.githubusercontent.com/89779119/137583801-33e77482-29dc-4df4-869f-fe52bf8f0971.png)

**Comment by afonsojramos** [comment]
@TheGeeKing The play button also needs remapping
![image](https://user-images.githubusercontent.com/19473034/137591951-290f8a95-14eb-480b-ac72-0ce9898c9ea2.png)

**Comment by afonsojramos** [comment]
This issue has already been fixed, please follow @ririxidev's advice to update the CSS Map
