### ISSUE TITLE
[popupLyrics] Always on Top switch

### ISSUE THREAD

**Issue by rickvandijck** [khanhas/spicetify-cli#1175]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Not have it "always on top", or have a switch to enable/disable it. I'm looking to implement it to my RainMeter setup, so just have the lyrics on my desktop. Now it's on top of everything

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Picture-in-picture is always on top. There is no way to get around that.
