### ISSUE TITLE
[macOS] Changing config directory

### ISSUE THREAD

**Issue by non-identity** [khanhas/spicetify-cli#119]
Currently, spicetify-cli uses `$HOME/spicetify_data` as the config directory in macOS. This adds clutter to home directory while browsing files. Is there any way to change this behavior?

Can the default config directory be changed to `$HOME/.spicetify_data`?

And thank you for creating this tool! This rocks!

**Comment by khanhas** [comment]
Set your desired path to environment variable `SPICETIFY_CONFIG`

**Comment by non-identity** [comment]
That worked. Thanks!
