### ISSUE TITLE
Use ~/.config/spicetify for configuration instead of ~/.spicetify

### ISSUE THREAD

**Issue by nsilvestri** [khanhas/spicetify-cli#12]
It's common practice to have user configuration files for Linux applications in `~/.config` (for example: pcmanfm, polybar, GTK, Qt, redshift, rofi, ranger, xfce). There's no reason to have spicetify use its own `~/.spicetify` directory, as it's another hidden file cluttering up `~`. I suggest that Spicetify start using `~/.config/spicetify` to conform with configuration file location convention.

**Comment by khanhas** [comment]
That makes sense. I will change in next version.
Thank you!

**Comment by vesim987** [comment]
To be more precise you should first try to read `XDG_CONFIG_HOME` environment variable and fallback to `~/.config/` when the env var is missing.

**Comment by khanhas** [comment]
I added this feature in v0.8
Please check it out and tell me if it works correctly.

**Comment by zeue** [comment]
working for me

**Comment by zeue** [comment]
@khanhas works for me! cheers

**Comment by Dorsug** [comment]
It is also common practice on macos. Moreover `~/spicetify_data` isn't a hidden file.
I'm completly happy for now using `SPICETIFY_CONFIG="$XDG_CONFIG_HOME/spicetify`, but is there any reason why it isn't the same on macos?

**Comment by jonathanlaniado** [comment]
> It is also common practice on macos. Moreover `~/spicetify_data` isn't a hidden file.
> I'm completly happy for now using `SPICETIFY_CONFIG="$XDG_CONFIG_HOME/spicetify`, but is there any reason why it isn't the same on macos?

+1, is this something macOS users can also do?

**Comment by khanhas** [comment]
@jonathanlaniado Have you tried it? I added that feature ages ago.

**Comment by jonathanlaniado** [comment]
Yes, thanks for checking. Was able to make it work with $HOME. :)

**Comment by alichtman** [comment]
This is broken for me on `spicetify v1.0.2`

**Comment by khanhas** [comment]
@alichtman XDG is only for linux
In all platform, use `$SPICETIFY_CONFIG`

**Comment by alichtman** [comment]
Thanks.

Why can't the XDG spec be supported on macOS? It is UNIX compliant.

**Comment by itsmeboy0** [comment]
> Thanks.
> 
> Why isnt't the XDG spec supported on macOS? It is UNIX compliant.

+1 for this. Not just for macOS, this should be supported even on Windows. I do not like clutter on **any platform** at all.

**Comment by alichtman** [comment]
> macOS has its own "spec" about where apps should keep their data etc.

Sure, but you're not following it. It doesn't say that you should dump configs in highly visible user directories, like `~`.

This data should go in `/Users/user/Library/Application Support/Spicetify` or something.

**Comment by itsmeboy0** [comment]
> Correct. We don't do it because spicetify is not really an "macOS application". More explanation here; [#967 (comment)](https://github.com/spicetify/spicetify-cli/issues/967#issuecomment-933496179) [#967 (comment)](https://github.com/spicetify/spicetify-cli/issues/967#issuecomment-933570431)

CLI apps in macOS still keep their config in `~/.config` (and sometimes even in Windows, alternative option is `%LOCALAPPDATA%` or `%APPDATA`). Spicetify should follow that too.

**Comment by sitiom** [comment]
> > And configs for spicetify are in ~/.config/spicetify.
> > ![image](https://user-images.githubusercontent.com/9348108/176999265-22728dc5-1e60-4aa9-9d0c-25afb8d5c9a8.png)

That leaves us with Windows then. `~/.spicetify` is cluttering up my home directory.
