### ISSUE TITLE
Expose spicetify-cli version in Spicetify object

### ISSUE THREAD

**Issue by SendNukez** [khanhas/spicetify-cli#1202]
It would be nice to have the current spicetify-cli version exposed somewhere in the Spicetify object. For example in a theme I'm working on there is an option to copy the OS, Spotify and Theme versions to the clipboard to paste them in issues. The ability to have the current spicetify-cli version too would be nice as the user won't have to manually add it.

This could also be useful for themes to notify the user that the current spicetify-cli version is outdated.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by itsmeow** [comment]
Adding to the Platform hook is a bad idea. Something like this would be annoying to implement because it requires patching the javascript at apply-time, as spicetify is only a toolchain, the js wrapper is entirely seperate from the exe's version, aside from the fact that it's downloaded at the same time.

**Comment by JulienMaille** [comment]
> Adding to the Platform hook is a bad idea. Something like this would be annoying to implement because it requires patching the javascript at apply-time, as spicetify is only a toolchain, the js wrapper is entirely seperate from the exe's version, aside from the fact that it's downloaded at the same time.

Well, with all my respect, just because you don't know how to do this doesn't make it a bad idea.
The version number is already stored in `config-xpui.ini` at apply-time. Can't we find a way to read that from the js?
