### ISSUE TITLE
Extension to remove "Your shows" from home screen

### ISSUE THREAD

**Issue by leehambley** [khanhas/spicetify-cli#1203]
## 📝 Provide a description of the new feature

_What is the expected behaviour of the proposed feature?  What is the scenario this would be used?_

Lots of people are not thrilled with seeing Podcasts forced at them on the home screen (because they don't listen to podcasts, or because Spotify recommendations are recommending borderline sexualized content to them and it cannot be hidden) 

This is one of the top requested features from the spofity community since ~2018 (remove your shows from home screen, or remove podcasts from "your shows").

Cynics on the Spotify support forum are convinced after three years of inaction that this is because Spotify's investors are pushing podcast content hard because they often don't pay royalties, and it's "free money".

Frankly I think a product manager at Spotify is a megalomaniac and has decided that we're going to have podcasts whether we want them or not.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by TheGeeKing** [comment]
any update @leehambley? if your request has been answered please close this issue.
