### ISSUE TITLE
Spotify 1.1.71 once again broken

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#1204]
## ℹ Computer information

- Spotify version: 1.1.71.560.gc21c3367
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. spicetify apply
2. spicetify doesn't apply
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
spicetify correctly applies

### ❌ Actual result

_What is the actual result of the above steps?_
It doesn't

## 📷 Screenshots

_Are there any useful screenshots?_
<img width="737" alt="Screen Shot 2021-10-28 at 7 05 50 PM" src="https://user-images.githubusercontent.com/43358890/139361855-8b96a202-ea08-449a-ac5a-f06d31a7b15e.png">

**Comment by theRealPadster** [comment]
Not sure if this helps at all, but this is the line of code (in xpui.js) that errors when I apply the spicetify marketplace custom app. 

![image](https://user-images.githubusercontent.com/1565883/139518320-af90c7a1-0c08-455e-b756-dd4e270b6f9c.png)

**Comment by neemanthnub** [comment]
> Spicetify.React is undefined

so are we supposed to remove it?

**Comment by theRealPadster** [comment]
I feel like it's an essential thing that Spicetify needs and something with the updated Spotify is breaking it so it's not being added in properly.

**Comment by neemanthnub** [comment]
> I feel like it's an essential thing that Spicetify needs and something with the updated Spotify is breaking it so it's not being added in properly.

oh is there a fix for it?

**Comment by theRealPadster** [comment]
Idk. Last time something like this happened it was months before things were working again.

**Comment by applekillerbyjames** [comment]
@afonsojramos @itsmeow

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/139532652-4a174f4e-e35f-4370-847a-e8aec2c49044.png)
Fun

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/139533000-974c5bf3-2442-4d6b-aa72-4cd3c0e37980.png)
Good news, it was JUST the React hook!!!! The others just sort of depend on it.

**Comment by pWoLiAn** [comment]
Can somebody add the fix to the latest release

**Comment by applekillerbyjames** [comment]
@afonsojramos

**Comment by TheGeeKing** [comment]
> @afonsojramos 

He will do a release when he has the time.
