### ISSUE TITLE
PopupLyrics show "Requested error: 401: captcha - undefined"

### ISSUE THREAD

**Issue by phucdt1234** [khanhas/spicetify-cli#1207]
## ℹ Computer information

- Spotify version: 1.1.71.560.gc21c3367
- Spicetify version: 2.7.1

### ✔️ Expected result

popupLyrics run normally

### ❌ Actual result

show "Requested error: 401: captcha - undefined"

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/77624484/139519191-8833ed2b-d653-42af-9e7a-1043475ae099.png)

**Comment by applekillerbyjames** [comment]
discuss on #1204

**Comment by applekillerbyjames** [comment]
discuss on #2

**Comment by ajiou** [comment]
> 
> 
> discuss on #1204

This should be related to #1090

**Comment by itsmeow** [comment]
Duplicate of #1090

**Comment by TheGeeKing** [comment]
> discuss on #1204
i know you love your issue post about spicetify 1.1.71 but check before posting than on everything.

@phucdt1234 issue is known and we are working on a fix. No date for the moment.
