### ISSUE TITLE
spicetify and rainmeter

### ISSUE THREAD

**Issue by HybridRaven** [khanhas/spicetify-cli#1209]
## ℹ Computer information

- Spotify version: 1.1.71
- Spicetify version: 2.71
- Rainmeter version: 4.5.4

Hi there! 
Long time I was able to connect spicetify with rainmeter (current playing song etc).
And there was info here sth like "Spicetify Installation for Rainmeter users" but currently I dont see it. 

Can anybody explain to me step by step how to connect spicetify with rainmeter? 

thx!

**Comment by ririxidev** [comment]
I don't think you really can? Unless someone did extension that makes some API server where rainmeter can get stuff

**Comment by ajiou** [comment]
web-now-playing?
https://github.com/khanhas/spicetify-cli/wiki/Extensions#web-now-playing

**Comment by TheGeeKing** [comment]
> Hi there! Long time I was able to connect spicetify with rainmeter (current playing song etc). And there was info here sth like "Spicetify Installation for Rainmeter users" but currently I dont see it.

There were issues with rainmeter when Spotify updated and it should have been fixed since. You can check this old issue thread: https://github.com/khanhas/spicetify-cli/issues/983

> Can anybody explain to me step by step how to connect spicetify with rainmeter?

The wiki doesn't seem to have any more explanation than: https://github.com/khanhas/spicetify-cli/wiki/Extensions#web-now-playing.

**Comment by HybridRaven** [comment]
@ajiou thx for the info.... webnowplaying extension I had installed
@TheGeeKing thx for the info.... 

I was needed only one command "Run command "spicetify config extensions webnowplaying.js"" and I didnt rememebr that command... 

All works great now... and thx for the help guys! 


cheers!
