### ISSUE TITLE
Unable to Intall on Windows 7

### ISSUE THREAD

**Issue by IamKayrox** [khanhas/spicetify-cli#121]
Unable to install on Windows 7. Invoke-WebRequest is not recognized neither curl

**Comment by Drgabi18** [comment]
What version of Powershell do you have?
Do `$PSVersionTable.PSVer` inside Powershell and copy paste what it says. If you don't have 5.0, try installing Powershell 5.0 and do the command to install again.
Pasting `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression` should have just worked, tpye just `spicetify` after to see if it works (or says that it dosen't work)

**Comment by AdrianoCahete** [comment]
By default, Win 7 comes with PowerShell 2.0. If you didn't updated, is still the default one. The `Invoke-WebRequest` cmdlet comes with version 3.

You need to update the PowerShell version to that one, at least. My personal recommended version is  the 5.1.
You can update it updating/installing the Windows Management Framework here: https://www.microsoft.com/en-us/download/details.aspx?id=54616
