### ISSUE TITLE
Fluent theme is broken

### ISSUE THREAD

**Issue by LuckeeDev** [khanhas/spicetify-cli#1211]
## ℹ Computer information

- Spotify version: 1.71.560.gc21c3367
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Apply Fluent theme

### ✔️ Expected result

_What is the expected result of the above steps?_

The buttons should show up correctly.

### ❌ Actual result

_What is the actual result of the above steps?_

Play and track control buttons don't work, alongside other pieces of UI that seem to be broken.

## 📷 Screenshots

_Are there any useful screenshots?_

![IMG-20211101-WA0039.jpg](https://user-images.githubusercontent.com/61506420/139684861-bfd7fdf6-d4c5-4f98-bcee-19a693519b71.jpg)

**Comment by TheGeeKing** [comment]
This repo is for spicetify, not content related to it. If you have an issue with fluent theme find the proper repo to post the issue.

**Comment by LuckeeDev** [comment]
I'm sorry, I'll close the issue and move it to the Fluent theme repo. Thanks!
