### ISSUE TITLE
Spotify crash with 2.7.1 and BlockTheSpot

### ISSUE THREAD

**Issue by xerta555** [khanhas/spicetify-cli#1212]
## ℹ Windows 10 21H2

- Spotify version: 1.1.71.560
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Updating Spotify Windows client to last version
2. Updating Spicetify to last version (2.7.1 from 2.7.0)
3. Applying Spicetify update with `spicetify restore backup apply` command
4. Applying BlockTheSpot last version to Spotify install folder (C:\Users\Username\AppData\Roaming\Spotify\)

### ✔️ Expected result

Playing a music

### ❌ Actual result

Spotify client crash without any error message.

Here is the logfile:
[windows_events_log.txt](https://github.com/khanhas/spicetify-cli/files/7455737/windows_events_log.txt)

I have tried few BlockTheSpot old versions, no changes, same issue. But i don't have tried with any previous Spicetify version(s) as i would like to avoid to make a clean setup of my Spotify client.
Idk if this issue come from Spicetify or from BlockTheSpot, it's the first time that i get this type of crash.

Thanks in advance.

**Comment by Davoleo** [comment]
it was a BlockTheSpot bug, but it's been fixed check out this thread https://github.com/mrpond/BlockTheSpot/issues/244

**Comment by xerta555** [comment]
> 
> 
> it was a BlockTheSpot bug, but it's been fixed check out this thread [mrpond/BlockTheSpot#244](https://github.com/mrpond/BlockTheSpot/issues/244)

Effectivly after having run the `BlockTheSpot.bat` file, it appear to works successfully on last version, thanks.
