### ISSUE TITLE
LoginFatal system can't find specified file

### ISSUE THREAD

**Issue by SunkenInTime** [khanhas/spicetify-cli#1214]
## ℹ Computer information

- Spotify version: 
- Spotify for Windows
1.1.71.560.gc21c3367
- Spicetify version: 
2.2.7

## 📝 Provide detailed reproduction steps (if any)

1. Download spicetify
2. Run spicetify backup apply
3. Error

### ✔️ Expected result
Back up to apply and for Spotify to work.

### ❌ Actual result
PS C:\WINDOWS\system32> spicetify backup apply
success Default config-xpui.ini generated.
spicetify v2.2.7
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
[ 2 / 2 ] loginfatal open C:\Users\shawn\.spicetify\Backup\settings.spa: The system cannot find the file specified.
PS C:\WINDOWS\system32>

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/76637177/139963356-398a8d37-0cf7-4489-9f47-b353fe064005.png)

_Are there any useful screenshots?_

**Comment by itsmeow** [comment]
You are running Spicetify 2.2. Please update.
`spicetify upgrade`
