### ISSUE TITLE
Blank Window On Apply

### ISSUE THREAD

**Issue by y0himba** [khanhas/spicetify-cli#1215]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.71.560.gc21c3367
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. …Update Spotify to Spotify for Windows 1.1.71.560.gc21c3367
2. …Spicetify backup
3. …Spicetify apply

### ✔️ Expected result

_What is the expected result of the above steps?_

Spotify is spiced up and working as the previous version was, with theme applied and WebNowPlaying.js working as intended. 

### ❌ Actual result

_What is the actual result of the above steps?_

As seen in the screenshot I get a blank Spotify Window, the 3 dot menu works, but when I tried to get the about info, there was no dialog, but it was there since I couldn't click through it.

Also, WebNowPlaying.js no longer works. 

## 📷 Screenshots

_Are there any useful screenshots?_
![error](https://user-images.githubusercontent.com/11462603/140003816-1ac06496-10e3-42d2-bdc4-93e860851735.jpg)

**Comment by applekillerbyjames** [comment]
there is a PR #1208 that fixes this issue, but it has to be released again.

**Comment by y0himba** [comment]
Thank you,

**Comment by TheGeeKing** [comment]
Duplicate of #1204. Please close this issue

**Comment by y0himba** [comment]
> Duplicate of #1204. Please close this issue

Sorry.  New to Github and old, so I wasn't aware it was etiquette for me to close this.
