### ISSUE TITLE
Menu of fullappdisplay and popuplyrics Not Available

### ISSUE THREAD

**Issue by lunadu321** [khanhas/spicetify-cli#1218]
## ℹ Computer information
- Spotify version: Spotify for Windows 1.1.71.560.gc21c3367
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps
1. Right click in FullAppDisplay mode trying to open setting menu.
2. Right click at the microphone icon to open menu of popuplyrics .

### ✔️ Expected result
I want to open the corresponding setting menu.

### ❌ Actual result
Nothing happens at all, there's no menu and I cannot change the setting (it worked fine before the recent Spotify update.)

**Comment by afonsojramos** [comment]
Try updating to 2.7.2 and let us know if it still happening.

**Comment by lunadu321** [comment]
Yes it's working now Thanks a lot!
