### ISSUE TITLE
Volume bug?

### ISSUE THREAD

**Issue by JacobRReed** [khanhas/spicetify-cli#1221]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.71.560.gc21c3367
- Spicetify version: latest

## 📝 Provide detailed reproduction steps (if any)

1. Launch spotify
2. set volume
3. exit spotify completely
4. launch spotify
5. notice the volume is set to 100%

### ✔️ Expected result
 - Volume setting stays

### ❌ Actual result
 - volume is set to 100%

## 📷 Screenshots
n/a

**Comment by afonsojramos** [comment]
Does this happen only when you have Spicetify applied? If you run `spicetify restore` does this behavior not happen?

**Comment by JacobRReed** [comment]
correct. I tried `spicetify restore` and this behavior does not persist

**Comment by JacobRReed** [comment]
after further investigation it seems this only happens on initial startup of system. exiting spotify completely and reopening after setting the volume the first time works. Maybe a bug with Spotify and swapping audio devices which i do often?

**Comment by TheGeeKing** [comment]
Yeah this volume bug is something common. It happens if you spicetify apply or close it or open it in a certain way. After everything is setup, normal usage should fix it.

**Comment by Bunnybanxy** [comment]
can someone help, i tried spicetify restore and it did nothing for me
