### ISSUE TITLE
Spicetify not compatible with Spotify 1.71

### ISSUE THREAD

**Issue by CharlieS1103** [khanhas/spicetify-cli#1223]
version = 1.1.71.560.gc21c3367
with    = 2.7.2

Assume it's the broken hooks as per usual, should probably try and see if there's an alternative than just manually fixing it everytime something goes wrong.

**Comment by CharlieS1103** [comment]
@itsmeow

**Comment by itsmeow** [comment]
Um, what? I fixed it? Try reinstalling spotify?

**Comment by TheGeeKing** [comment]
Issue on Charlie side.

**Comment by CharlieS1103** [comment]
I did, will test more later.

**Comment by accik** [comment]
Working here.
Spicetify version: 2.7.2 
Spotify version: 1.1.71.560.gc21c3367
Win 10 20H2

**Comment by CharlieS1103** [comment]
@itsmeow Yeah that's mb, school internet apparentally blocks spotify somehow.
