### ISSUE TITLE
Popup Lyrics is displaying "Cannot read property 'message' of undefined"

### ISSUE THREAD

**Issue by samfundev** [khanhas/spicetify-cli#1224]
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.7.2

## 📝 Provide detailed reproduction steps (if any)

1. Open popup lyrics

### ✔️ Expected result

The lyrics to be displayed or that they couldn't be fetched.

### ❌ Actual result

"Cannot read property 'message' of undefined" is displayed.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/6759716/140419194-ae3ba802-65cf-4b06-881c-e4031cfe9722.png)

**Comment by TheGeeKing** [comment]
Update your Spotify and extensions.

**Comment by samfundev** [comment]
@TheGeeKing I have Spotify installed through apt and that's the latest version available there. The popupLyrics.js that I have is the same as the one available in this repo. I thought the extensions included with spticetify are updated when you update spicetify. Is there something else I need to do to update them?

**Comment by ajiou** [comment]
@samfundev could you paste the link to the song?

**Comment by samfundev** [comment]
@ajiou As far as I can tell this seems to be happening on every song I try to play. Regardless, the song in the screenshot is [That Funny Feeling by Bo Burnham](https://open.spotify.com/track/7uCq4vBPffjaTMlE8EQzJD?si=6a4058284b2a4c50).

**Comment by samfundev** [comment]
Here's where the error seems to be occurring:
![Screenshot from 2021-11-05 02-00-06](https://user-images.githubusercontent.com/6759716/140465452-582356d6-e89e-4251-a216-4ccdf96a6024.png)

**Comment by ajiou** [comment]
It seems like musixmatch didn't send the full response

The full response should look like these:
![image](https://user-images.githubusercontent.com/35028055/140478774-cdb7e790-bfb6-4c96-8ba6-aab40c7e0c31.png)

**Comment by TheGeeKing** [comment]
> @TheGeeKing I have Spotify installed through apt and that's the latest version available there. The popupLyrics.js that I have is the same as the one available in this repo. I thought the extensions included with spticetify are updated when you update spicetify. Is there something else I need to do to update them?

OK so roll back your spicetify to 2.6.9 I think not sure though but Spotify 1.1.68 is not compatible with spicetify >=2.7.0

**Comment by afonsojramos** [comment]
As @TheGeeKing said, you will need to rollback Spicetify to a supported version as we can only focus on the latest version of Spotify. For 2.7.2 you need the latest version.

**Comment by samfundev** [comment]
@TheGeeKing @afonsojramos I've reverted to 2.6.7 and the error doesn't get displayed but the same error is happening.

**Comment by TheGeeKing** [comment]
> @TheGeeKing @afonsojramos I've reverted to 2.6.7 and the error doesn't get displayed but the same error is happening.

🤨More precisely. Not displayed but same error?

**Comment by samfundev** [comment]
Yes, the error wasn't being displayed like in the screenshot but using the debugger I could see that the error was still happening.

Regardless, I've fixed it. Using my token from the musixmatch website seemed to be the issue. I grabbed a token from the desktop client and it seems to be working.
