### ISSUE TITLE
Add 2.7.2 spicetify to chocolatey

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#1225]
## ℹ Computer information

- Spotify version: Latest idk
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. run `cup spicetify-cli` or `choco upgrade spicetify-cli`
2. see screenshot

### ✔️ Expected result

spicetify upgrading to 2.7.2

### ❌ Actual result

doesnt upgrade

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/81705406/140568438-8bd5d935-585d-45a8-b2f5-324d7cdb6176.png)

**Comment by itsmeow** [comment]
We do not maintain the chocolatey repository, that is at the discretion of its maintainers.
