### ISSUE TITLE
Unable to scroll playlist

### ISSUE THREAD

**Issue by Crylia** [khanhas/spicetify-cli#1226]
## ℹ Computer information

- Spotify version: 1:1.1.68.632.g2b11de83
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

Install Spotify from apt and Spicetify as described in the readme

### ✔️ Expected result

Scrolling trough your playlist like normal no matter how many you've gotten.

### ❌ Actual result

No matter which skin I use I can't scroll down to reach all my playlists.
When making the window really small its possible to scroll, but not all the way down it kinds stops half wayish.

**Comment by TheGeeKing** [comment]
Wrong Spotify or Spicetify version.
Rollback Spicetify or update Spotify

**Comment by Crylia** [comment]
@TheGeeKing I got the latest spotify build and even updating spicetify to 2.7.2 didnt help. Is there a known good spotify/spicetify combo that works?

**Comment by TheGeeKing** [comment]
Spotify 1.1.71 and spicetify 2.7.2 work
Spotify 1.1.69 and spicetify 2.7.0 work
Spotify 1.1.68 and spicetify 2.6.7 work
Spotify 1.1.65 and spicetify 2.6.0 work

**Comment by Crylia** [comment]
I tried several spicetify versions with my current spotify version and none of them seem to fix my problem, downgrading spotify is not possible with the apt repo as far as i know

**Comment by Crylia** [comment]
Pulling the latest theme changes fixed it for me
