### ISSUE TITLE
Stuck in Preprocessing

### ISSUE THREAD

**Issue by plkm001** [khanhas/spicetify-cli#1227]
## ℹ Computer information

- Spotify version: 1.1.7.1.560.gc21c3367
- Spicetify version:  2.7.2

I wait for 30 minutes but nothing change

![image](https://user-images.githubusercontent.com/69071862/140609448-60ed3739-b8da-40c0-b1ae-b87551a7c7a0.png)

**Comment by TheGeeKing** [comment]
did you retry? connection issue?

**Comment by plkm001** [comment]
i retry many times, no vpn, no connection issue

**Comment by afonsojramos** [comment]
That is very weird... Keep trying :shrug: Maybe some firewall block

**Comment by plkm001** [comment]
i copied file from other computer, it solved
