### ISSUE TITLE
[Bug] Dissapearing cover art

### ISSUE THREAD

**Issue by fernandossmm** [khanhas/spicetify-cli#123]
The cover art on the bottom left corner has two modes. When switching between them, image sometimes disappears. Restoring doesn't bring it back, it just vanishes. Started happening when using custom CSS, Gradiento. To fix I have to reinstall Spotify completely.

Running Spicetify on Windows 10.

**Comment by bemug** [comment]
I have a somehow similar issue I think it's worth to put it here: I only have cover art of downloaded songs.
I'm using the midnight-light theme.

**Comment by khanhas** [comment]
I have none of this problem with stock Spotify or SpicetifyDefault theme. So, your chosen theme might cause it. Best solution is taking a look at your theme's `user.css`, indentify CSS blocks that intervene with big/small cover mechanism and remove them.

**Comment by bemug** [comment]
Here is the [CSS for Midnight-Light theme](https://github.com/morpheusthewhite/spicetify-themes/blob/master/Midnight-Light/user.css) I'm using right now.
As you can see it doesn't do much, and unfortunately does not affect the cover at all.
