### ISSUE TITLE
Trojan detected?

### ISSUE THREAD

**Issue by MyBigFan2** [khanhas/spicetify-cli#1233]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.71.560.gc21c3367
- Spicetify version: v2.7.2

## 📝 Provide detailed reproduction steps (if any)

1. update from v2.7.1 using `spicetify upgrade` in powershell
2. updates ok
3. windows defender doesnt like new update

### ✔️ Expected result

windows defender being chill about it

### ❌ Actual result

windows defender mad

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/27133275/140639310-f3537392-dcb5-4f01-a989-32162894ad8d.png)

## Additional
i have also let defender delete spicetify and reinstalling it using a powershell command
defender thinks a clean install is a trojan as well

**Comment by TheGeeKing** [comment]
False positive. Add an exception for the folder.
