### ISSUE TITLE
Wont Install

### ISSUE THREAD

**Issue by AnjeloGee** [khanhas/spicetify-cli#1239]
Remove-Item : Cannot find path 'C:\Users\KN Tech\spicetify-cli\CustomApps\lyrics-plus\' because it does not exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:411
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\KN Tec...ps\lyrics-plus\:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by afonsojramos** [comment]
I almost can't even understand the problem... Please edit the issue with more info, until then, it will remain closed.
