### ISSUE TITLE
Issue Running First Time on MacOS

### ISSUE THREAD

**Issue by motorboeterz** [khanhas/spicetify-cli#124]
(Please don't judge, I'm a complete noob with this stuff)

When I run spicetify through Terminal, it seems to open, however I'm unable to input any commands such as "spicetify backup apply" to intialize the program, and I cant type past the "Process Completed". Is there something I'm doing wrong?

![Screen Shot 2019-12-19 at 9 05 56 pm](https://user-images.githubusercontent.com/59050238/71166459-e2033d00-22a6-11ea-8bd9-ffbfe03e12ed.png)

**Comment by motorboeterz** [comment]
I've attempted to run a new command in the same Shell via the File menu, however I've had no success

**Comment by khanhas** [comment]
Try running: 
```
/Users/boetersluke/spicetify/spicetify backup apply
```

**Comment by motorboeterz** [comment]
Appreciate it
