### ISSUE TITLE
Themes Broken With 2.7.2

### ISSUE THREAD

**Issue by ohitstom** [khanhas/spicetify-cli#1240]
## ℹ Computer information

- Spotify version: 1.1.71.560 (Latest)
- Spicetify version: 2.7.2 (Latest)

## 📝 Provide detailed reproduction steps (if any)

1. Install Latest Spicetify And Spotify
2. Apply fluent and its .js (Or Dribblish)
3. Weird color problems, fluent has loads of missing icons such as play and pause.

### ✔️ Expected result

Working Themes

### ❌ Actual result

Non Working Themes

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/22730962/140658661-67a2eef4-8d8d-489a-9305-311728a8e159.png)

**Comment by ohitstom** [comment]
Downgrading spicetify and spotify seem to be the only fix (To version 2.7.0) 
However that update has its own slew of problems, would love to see this fixed for 2.7.3.

Or if the problem lies in the theme makers hands for not updating their themes then let me know.

**Comment by TheGeeKing** [comment]
As said in #1211.

This repo is for spicetify, not content related to it. If you have an issue with fluent or dribbblish theme find the proper repo to post the issue.

**Comment by ohitstom** [comment]
yes but the issue isnt to do with fluent, its most likely to do with spicetify.

**Comment by TheGeeKing** [comment]
Add a help wanted tag and try to debug it if you want but you should directly contact the theme creator on his repo.

**Comment by afonsojramos** [comment]
This is not an issue for this repo, but for spicetify-themes. However, I'd recheck if there aren't any new updates to that repo that you need to do to fix this before creating a new issue there.
