### ISSUE TITLE
Hide window frame

### ISSUE THREAD

**Issue by fugkco** [khanhas/spicetify-cli#1241]
Hello, does spicetify have full access to the Electron app (namely, change parameters for `BrowserWindow`)? If so, is it possible to add an option to hide the window frame? I don't know much about Electron and I'm going by [this article](https://www.christianengvall.se/electron-frameless-window/).

Reason I ask for this is because I'm using Pop!_OS which allows for hiding the window frames for _all_ windows, but for reasons Spotify isn't being affected by the setting. Would be nice if I can achieve the same result for Spotify.

**Comment by TheGeeKing** [comment]
You might want to add the help wanted tag.

Some people are trying to find a way to fix SpotifyNoControl that doesn't work for some reason now on Windows. You can join the discord and try to find a solution.

**Comment by itsmeow** [comment]
Spotify is not an Electron app, it's a Chromium Embedded app.

**Comment by itsmeow** [comment]
To do this it would require patching Spotify.exe, or at least the cef client arguments, which I don't think is currently possible.

**Comment by rcompier** [comment]
> You might want to add the help wanted tag.
> 
> Some people are trying to find a way to fix SpotifyNoControl that doesn't work for some reason now on Windows. You can join the discord and try to find a solution.

Weirdly enough, it does work on some versions of spotify, I'm currently not home to verify the version but I believe it's specifically 1.67

**Comment by ohitstom** [comment]
The issue with current nocontrols is its inability to detect the running process that renders the titlebar. 

Im working on fixing it but it wont be for a long time, other than that i can look into injecting c++ code into spotify with an extension + chromium.
