### ISSUE TITLE
Virus in new update (?)

### ISSUE THREAD

**Issue by DaikiDxD** [khanhas/spicetify-cli#1242]
## ℹ Computer information

- Spotify version: 1.1.71.560.gc21c3367
- Spicetify version: Updating to 2.72 from 2.71

## 📝 Provide detailed reproduction steps (if any)

1. Ran "spicetify upgrade"
2. Accidentally typed "spicetift restore backup apply"
3. Then ran "spicetify restore backup apply"

### ✔️ Expected result

_What is the expected result of the above steps?_

Spicetify should update.

### ❌ Actual result

_What is the actual result of the above steps?_

My terminal and Windows Defender telling me that spicetify-cli has a virus

## 📷 Screenshots

_Are there any useful screenshots?_

![image](https://user-images.githubusercontent.com/90215948/140662177-72f88edf-cd19-4fba-8f66-da9ff38db2f7.png)

![image](https://user-images.githubusercontent.com/90215948/140662186-a7459924-318f-451b-9f8c-a149b92c1d2d.png)

(Note: I uninstalled Spicetify immediately)

**Comment by TheGeeKing** [comment]
Whitelist it. Simple as that

**Comment by DaikiDxD** [comment]
Ok,, ty.

**Comment by ririxidev** [comment]
When learn that antiviruses false positives apps when they aren't signed with certification that gives ability to skip smartscreen etc.

**Comment by DaikiDxD** [comment]
Oh, ok, tysm.

**Comment by pWoLiAn** [comment]
I cant seem to download the zip whatsoever.upgrade is stuck at downloading.
![image](https://user-images.githubusercontent.com/49567139/140904419-b9a80c73-aa4d-4338-b0f8-c79c29fa7edc.png)

**Comment by pWoLiAn** [comment]
![image](https://user-images.githubusercontent.com/49567139/140906317-6edecb77-5676-4436-b744-d286167cae23.png)

**Comment by itsmeow** [comment]
btw, I replaced the release assets for 2.7.2 with a rebuilt version that doesn't flag antivirus.
