### ISSUE TITLE
LyricsPlus: Add automatic scrolling for unsynced lyrics

### ISSUE THREAD

**Issue by federicodilo** [khanhas/spicetify-cli#1243]
I wonder if it could be possible to add an option to enable automatic scrolling for all unsynced lyrics.
It also would be useful to add a slider to set the scrolling speed.
Thanks.
___
If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by afonsojramos** [comment]
How would this even work? If the lyrics are unsynced, how do you expect to know where the music is?

**Comment by federicodilo** [comment]
Please have a look [here.](https://www.accordiespartiti.it/accordi/internazionali/acdc/testo-e-tablatura-di-back-in-black-acdc/)

Regards

**Comment by afonsojramos** [comment]
What are you trying to suggest @federicodilo ?

**Comment by TheGeeKing** [comment]
> What are you trying to suggest @federicodilo ?

Something that moves at a constant speed

**Comment by afonsojramos** [comment]
Oh, I see, okay, in that case I'll reopen as it actually seems like a good idea! Sorry for the misunderstanding @federicodilo!

**Comment by TheGeeKing** [comment]
js can scroll I think so it can be something cool and simple to add.

Btw I think Spotify api can give bpm. So can add an automate speed by bpm as generally faster music sing faster.

**Comment by federicodilo** [comment]
It's OK, maybe I haven't been clear enough.
I was thinking on an option to scroll the lyrics automatically (instead of doing it by the mouse) at a constant speed rate.
Making this rate variable (settable) would let the user choose the best rate based on font size and/or window size.

Think of it as a way to sincronize the lyrics "manually".
