### ISSUE TITLE
Lyrics-plus doesn't change lyrics after song change

### ISSUE THREAD

**Issue by frodo36** [khanhas/spicetify-cli#1248]
## ℹ Computer information

- Spotify version: Spotify for Windows
1.1.71.560.gc21c3367
- Spicetify version: 2.7.3

I have been using Lyrics-plus for a while now, and for no apparent reason now this issue happens. There isn't any specific thing to trigger it as far as I know.  I have already tried reinstalling the custom app, reinstalling spicetify and spotify, however none of them seemed to do anything. When you simply leave the lyrics-plus window and open it again, the correct lyrics are displayed.
As a quick disclaimer, I don't have any experience with programming or anything like that, whatsoever.

## 📝 Provide detailssed reproduction steps (if any)

1. Play a song on spotify
2. Go to the Lyrics-plus tab
3. Skip to another song 

### ✔️ Expected result

Lyrics-plus changes the lyrics to the next song

### ❌ Actual result

Lyrics-plus still shows the lyrics of the previous song

## 📷 Screenshots

![Screenshot 2021-11-10 192502](https://user-images.githubusercontent.com/88240067/141171564-1c68a785-7024-42cf-89e8-b5adf1fc6c8a.png)

**Comment by itsmeow** [comment]
Is there any error output in the developer console? (Ctrl+Shift+I, Console tab)

**Comment by frodo36** [comment]
![image](https://user-images.githubusercontent.com/88240067/141240159-e4d29d51-f201-4599-a4a9-ededdb3ee651.png)
this is what my condole looks when this issue happens. There are some errors, but those were already there before the issue.

**Comment by afonsojramos** [comment]
The 403 means unauthorized, therefore I'll ask, what token are you using for lyrics plus? The one that comes or one that you got from MusicXMatch?

**Comment by frodo36** [comment]
I retrieved my own Musixmatch token from the app a while ago.

**Comment by frodo36** [comment]
I got my own Token from the Musixmatch app and i am using it for lyrics-plus

**Comment by frodo36** [comment]
I just noticed something. This problem only occurs when I am using shuffle+

**Comment by itsmeow** [comment]
shuffle+ hooks into the queue system, it may be possible my reimplemenation of the queue hook makes shuffle+ interact in a way that lyrics plus doesn't understand. @khanhas thoughts?

**Comment by khanhas** [comment]
Can't reproduce, shuffle+ and lyrics-plus still work fine on mine. Either track change or hit skip button.

https://user-images.githubusercontent.com/26436809/141601809-d63e1f86-2787-42a4-94f0-180baf1b4aff.mp4

**Comment by frodo36** [comment]
I am using spicetify 2.8.1 with the latest versions of shuffle+ and lyrics-plus, but it still doesn't work.
To me, it looks like this:

https://user-images.githubusercontent.com/88240067/141649592-dde25663-e1b5-4d27-923d-e0a7e455b216.mp4

**Comment by khanhas** [comment]
I think is the problem with how shuffle+ queue Liked Tracks.
Can you go into Queue page, hit Clear the queue, shuffle+ a playlist and see if the bug happens in this case in your end.

**Comment by frodo36** [comment]
I tried, and also with playlists, the issue persists. However, I noticed that this only happens when I select all songs by hitting ctr + a and then shuffle them. If I just click on the 3 dot menu and click "play with shuffle+" everything seems to work fine.

**Comment by frodo36** [comment]
The issue seems fixed after the last lyrics-plus patch. Everything works as expected now. Thanks!
