### ISSUE TITLE
lyrics bugged out

### ISSUE THREAD

**Issue by ncax** [khanhas/spicetify-cli#1250]
## ℹ Computer information

- Spotify version: windows 1.1.71.560.gc21c3367
- Spicetify version: v2.7.3

## 📝 Provide detailed reproduction steps (if any)

1. load up spicetify (with lyrics plus)
2. go to the lyrics tab
3. i played "all i want is you" by Rebzyyx so play that

### ✔️ Expected result

to display the lyrics of the song

### ❌ Actual result

it will display a bunch of chinese and the word baby and tell me in between some of it 

## 📷 Screenshots

https://i.imgur.com/1vp7OT6.png

**Comment by afonsojramos** [comment]
Maybe it has to do with Netease provider. Can you switch the order so Netease is the last provider to see if it still happens?
