### ISSUE TITLE
Custom app route binding broken on 1.1.72

### ISSUE THREAD

**Issue by itsmeow** [khanhas/spicetify-cli#1252]
## ℹ Computer information

- Spotify version: 1.1.72
- Spicetify version: 2.8.0

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/10366817/141275605-fceb4f5b-0179-4672-a7d2-d31bd761e511.png)

![image](https://user-images.githubusercontent.com/10366817/141275582-6087ce85-7234-49f7-aa26-90cd7721e195.png)

```
xpui.js:formatted:53168 ChunkLoadError: Loading chunk spicetify-routes-lyrics-plus failed.
(missing: https://xpui.app.spotify.com/spicetify-routes-lyrics-plus.js)
    at Object.s.f.j (xpui.js:formatted:67545)
    at xpui.js:formatted:67298
    at Array.reduce (<anonymous>)
    at Function.s.e (xpui.js:formatted:67298)
    at xpui.js:formatted:30749
    at vendor~xpui.js:29
    at xs (vendor~xpui.js:29)
    at Ts (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at vs (vendor~xpui.js:29)
```

![image](https://user-images.githubusercontent.com/10366817/141275653-468dbb3e-f3ca-4517-a916-8d9c391ec293.png)
![image](https://user-images.githubusercontent.com/10366817/141275695-8b4d337a-0b83-48fd-8ff5-a36dff8d5ceb.png)

**Comment by nanchaara** [comment]
same problem happened to me

**Comment by TheGeeKing** [comment]
Logic. Fact

**Comment by marcfrankel** [comment]
Also have the same issue

**Comment by TheGeeKing** [comment]
It's a known issue so no need to point it out.

**Comment by ririxidev** [comment]
> Logic. Fact

> It's a known issue so no need to point it out.

ok, and? Literally you don't need to say it over and over, this is GitHub issue that can be bumped if people experience the same thing like @itsmeow or someone else. Be kind.

**Comment by TheGeeKing** [comment]
I'm kind just saying that maintainers/contributors are aware of it so it not a small bug that some can encounter it is a fact everyone will experience it. So no need to pollute the thread.

**Comment by ririxidev** [comment]
🤣 🤣 🤣 🤣 🤣 🤣

**Comment by khanhas** [comment]
Fixed.
