### ISSUE TITLE
New Update Breaks Fluent Theme

### ISSUE THREAD

**Issue by ItzCoolChenz** [khanhas/spicetify-cli#1253]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Update Spotify to 1.1.72.439
2. Apply Fluent Theme

### ✔️ Expected result

Completely broken UI

### ❌ Actual result

The theme to work normally

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/94136368/141349888-83336207-808a-4cd7-b8ec-8ceb3304ddca.png)

**Comment by itsmeow** [comment]
Yeah so the CSS map had to be rebuilt mostly from scratch and thus has a lot of issues @TheGeeKing If you could look into this it would be greatly appreciated

**Comment by TheGeeKing** [comment]
> Yeah so the CSS map had to be rebuilt mostly from scratch and thus has a lot of issues @TheGeeKing If you could look into this it would be greatly appreciated

@ItzCoolChenz uses Spicetify 2.7.1 with Spotify 1.1.72 and some elements of dribbblish and fluent are broken. 

I can only do css map for Spicetify not check if themes are up to date and working.

@itsmeow I saw some css that your generator is not sure if you can send them to me with where I can find them (home, library, ...) I can take a look and manually fix them.

If someone find some css broken you  can comment it on #1254

**Comment by itsmeow** [comment]
Oh. Yeah update to 2.8, that should fix the theming issues.

**Comment by TheGeeKing** [comment]
@itsmeow you can close it I guess
