### ISSUE TITLE
[BUG] Spicetify 2.8.0 - Crash with LyricsPlus

### ISSUE THREAD

**Issue by Tumeez** [khanhas/spicetify-cli#1255]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.69.612.gb7409abc
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Install Spicetify-cli 2.8.0 which is newest atm
2. spicetify config custom_apps lyrics-plus
3. spicetify apply
4. "Something went wrong!" box comes up and Spotify is unusable
5. spicetify config custom_apps lyrics-plus- (which remove lyrics-plus)
6. spicetify apply
7. Everything work like a charm

### ✔️ Expected result

Working Spotify app with LyricsPlus custom app

### ❌ Actual result

"Something went wrong!" box comes up and Spotify is unusable

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/52361553/141380126-e47e4e39-8001-41f5-b535-585a92cb674d.png)

**Comment by TheGeeKing** [comment]
OH GOD. Don't use Spicetify 2.8.0 with Spotify 1.1.69. Search for the correct matching version

**Comment by Tumeez** [comment]
> OH GOD(saw this issue too much today). Don't use Spicetify 2.8.0 with Spotify 1.1.69. Search for the correct matching version

That's my user error and I'm sorry!
