### ISSUE TITLE
[BUG] Spicetify 2.8.0 - Access denied

### ISSUE THREAD

**Issue by Tumeez** [khanhas/spicetify-cli#1256]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e-33
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Download spicetify-2.8.0-windows-x64 and extract it
2. Go to that folder with cmd
3. spicetify.exe -v
4. Access is denied.
5. Repeat 1-3 with version 2.7.3
6. cmd told version 2.7.3

### ✔️ Expected result

CMD should tell spicetify version to 2.8.0, not access denied. THAT INCLUDES EVERY COMMAND WITH 2.8.0 SPICETIFY

### ❌ Actual result

Access is denied.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/52361553/141388511-cb398a1c-d298-484b-89d6-c43c7bacb433.png)

---------------------------------

![image](https://user-images.githubusercontent.com/52361553/141388587-022374a8-6281-416c-a061-1dfb51127701.png)

**Comment by TheGeeKing** [comment]
A strange known issue. It seems it is related to Windows permissions. Why? We don't know yet.

**Comment by ririxidev** [comment]
That's an issue from your end a.k.a broken permissions (non-admin user etc. etc.) To fix it, you can use TakeOwnership file that can be downloaded from [there (add-takeownership.zip)](https://github.com/khanhas/spicetify-cli/files/7528752/add-takeownership.zip) and run it on spicetify file from context menu.

**Comment by Tumeez** [comment]
> That's an issue from your end a.k.a broken permissions (non-admin user etc. etc.) To fix it, you can use TakeOwnership file that can be downloaded from [there (add-takeownership.zip)](https://github.com/khanhas/spicetify-cli/files/7528752/add-takeownership.zip) and run it on spicetify file from context menu.

![image](https://user-images.githubusercontent.com/52361553/141504595-63a29f23-6881-4b6e-907c-983a052ec49e.png)

No matter if owner is Tuomas, my regular daily-drive account (Standard user) or Supervisor, only administrative tasks (Administrator user). Access is denied still appear.

**Comment by ririxidev** [comment]
Well,
then only thing that comes in mind is just windows being weird,
![image](https://user-images.githubusercontent.com/9348108/141590972-f4b59a69-9df0-4312-81af-d2e7fdb30f28.png)
works fine on my end, even with adding `.exe` (don't mind this version)

**Comment by khanhas** [comment]
Try v2.8.1 and see if it still happens

**Comment by Tumeez** [comment]
> Try v2.8.1 and see if it still happens

It looks like 2.8.1 fixed it. 2.8.1 works like a charm!

**Comment by ririxidev** [comment]
That's not really spicetify issue but okay 🤷
