### ISSUE TITLE
Spotify does not load once LyricsPlus installed

### ISSUE THREAD

**Issue by mizzunet** [khanhas/spicetify-cli#1258]
## ℹ Computer information

- Spotify version: spotify 1:1.1.68.632-1
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Install LyricsPlus `spicetify config custom_apps lyrics-plus`
2. Apply it `spicetify apply`
3. Launch Spotify

### ✔️ Expected result

Open and load Spotify normally and the Lyrics option in the sidebar

### ❌ Actual result

Appears an error saying, something went wrong 

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/10193999/141424639-fcd150f9-20a2-4e12-b126-792bf1aff4de.png)

**Comment by mizzunet** [comment]
So I removed the problematic custom app by `spicetify config custom_apps lyrics-plus-`
Now Spotify run fine though

**Comment by TheGeeKing** [comment]
Duplicate of #1255

**Comment by mizzunet** [comment]
@TheGeeKing alright, then this issue to be closed
