### ISSUE TITLE
Variables breaking @import

### ISSUE THREAD

**Issue by NYRI4** [khanhas/spicetify-cli#1259]
## ℹ Computer information

- Spotify version: `1.1.72.439`

- Spicetify version: `2.8.0`

## 📝 Provide detailed reproduction steps (if any)

1. Create a theme with an `@import` in it
2. Add some variables in the `color.ini`

### ✔️ Expected result

The `@import` rule should be at the top of the generated `user.css`, before the variables of the `color.ini`.

### ❌ Actual result

The `@import` is set after the variables of the `color.ini`, making the `@import` rule invalid.

More information : https://drafts.csswg.org/css-cascade-3/#at-import

## 📷 Screenshots

![Spotify_CidqBPDFrG](https://user-images.githubusercontent.com/65369563/141487704-5bdb4c2e-b93d-401d-bc99-eeb672910b5f.png)

**Comment by itsmeow** [comment]
Feature: line comment css to place it before root definition like `@import ... // spicetify-before-root`

**Comment by khanhas** [comment]
SHould be fixed in next patch.
