### ISSUE TITLE
Translucid window

### ISSUE THREAD

**Issue by AdrianoCahete** [khanhas/spicetify-cli#126]
I don't know if this software can change something on [CEF](https://www.spotify.com/opensource/) side or just on already loaded code inside CEF.

If the answer is yes, can we change the CEF options (like [backgroundColor](https://bitbucket.org/chromiumembedded/cef/src/master/tests/shared/common/client_switches.cc?at=master) settings) to make background transparent?
If actual answer is no, it's possible to make this available in the future?

**Comment by khanhas** [comment]
Sorry, there still is a black opaque layer under CEF layer. So the answer is no.
