### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Kaokiwa** [khanhas/spicetify-cli#1260]
- Spotify version: 1.1.72.439
- Spicetify version: 2.8.0

### ✔️ Expected result

Friend activity to be coloured and the UI working perfectly.

### ❌ Actual result

Friend activity looks off and 3 dots are below where they are meant to be. 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/91981266/141492918-4efda879-ea61-4dc6-8721-ec69b3ebf371.png)

**Comment by ririxidev** [comment]
Theme specific issue, you should go to spicetify themes repo and create new issue [here](https://github.com/morpheusthewhite/spicetify-themes/issues/new)

**Comment by Kaokiwa** [comment]
> Theme specific issue, you should go to spicetify themes repo and create new issue [here](https://github.com/morpheusthewhite/spicetify-themes/issues/new)

sorry my bad :)
