### ISSUE TITLE
Don't automatically push every update to AUR, since it can break things

### ISSUE THREAD

**Issue by theRealPadster** [khanhas/spicetify-cli#1261]
## ℹ Computer information

- Spotify version: 1.1.68.632-1
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Install Spotify from AUR
2. Install Spicetify from AUR
3. It's broken

### ✔️ Expected result

If 2.8.0 is only compatible with Spotify 1.1.72, then it shouldn't have the update pushed to the AUR, since it's all broken now. 

### ❌ Actual result

Update installed automatically and breaks Spicetify. 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/1565883/141498480-0a2dcb45-8cb8-413f-976d-a51e3f2dcf9f.png)

It looks like this is #1257, by the way

**Comment by ririxidev** [comment]
Well, @itsmeow can always add to PKGBUILD e.g. `depends=(spotify=1:1.1.72.439-1)`

**Comment by itsmeow** [comment]
spicetify needs a version mapping scheme, is what I'm thinking here. Maybe the regex content could be spotify version based.

**Comment by ririxidev** [comment]
@itsmeow, if you actually can get spotify version, then what's the problem of just getting this version and checking what version had support for this x spotify version (can be implemented) and it would just fallback to this version css-map from github.

**Comment by itsmeow** [comment]
The problem is not css map, it's also hooks. Ideally we could externalize hooks somehow and then do a similar tag matching system that matches Spotify versions instead.

**Comment by ririxidev** [comment]
Ah right, but yeah maybe there is some way to just downloading hooks from github and then just using specific hooks for specific version 🤔

**Comment by khanhas** [comment]
Upgrade spicetify v2.8.1 and everything should work normally now.
Note other contributors, please try your best to backward compatible with Spotify on Linux, regardless of how old its version is.

**Comment by theRealPadster** [comment]
Thanks! Ironically, right they just released 1.1.72 on Linux now
![image](https://user-images.githubusercontent.com/1565883/141602799-d6f34fac-a93f-4864-b5b8-b7b58135db01.png)
