### ISSUE TITLE
Getting error-dialog.generic.header on macOS Spotify when trying to use any theme. 

### ISSUE THREAD

**Issue by j3r1ch0** [khanhas/spicetify-cli#1266]
Ok, so whenever I try to use any theme I'm getting the error "error-dialog.generic.header". I'm on the latest Spotify version. I have attached a picture of the error. There aren't any console errors or anything like that, and it says everything was applied correctly. Does anyone have any experience with this? I'm on macOS Monterrey with a 13" MacBook Pro M1. I can provide any additional information if it is needed. I'd love to try and get this solved. Ultimately I think it comes down to the "fatal-error.button-label" tag. Thanks. 

<img width="530" alt="Screen Shot 2021-11-13 at 3 00 17 PM" src="https://user-images.githubusercontent.com/5798179/141657458-535ea849-5539-4de8-92cf-352b4476b4ed.png">
,

**Comment by ririxidev** [comment]
Not used issue template, you provided no information about your spotify version nor spicetify version. We can't really help without this stuff. Also saying "latest" can be relevant because spotify is rolling 1.72 to some users and some users have 1.71. Just need to know.

**Comment by TheGeeKing** [comment]
@j3r1ch0

**Comment by j3r1ch0** [comment]
It was my fault. I ended up fixing it. Sorry to clutter up your issues. Mismatched Spotify/Spicetify. I closed the issue.
