### ISSUE TITLE
Blank screen on latest update [Linux/AUR]

### ISSUE THREAD

**Issue by megz15** [khanhas/spicetify-cli#1267]
## ℹ Computer information

- Spotify version: <i>spotify-1:1.1.72.439-1</i>
- Spicetify version: <i>spicetify-cli-2.7.1-1</i>

## 📝 Provide detailed reproduction steps (if any)

1. Update spotify to the latest version (aur/chaotic aur)
2. Open spotify
3. Blank screen with just the background color of spotify theme (songs can be played using media control buttons/playerctl)

### ✔️ Expected result

_Spotify should work_

### ❌ Actual result

_It's opening to a blank screen_

## PS
I tried reinstalling spotify and doing `spicetify backup apply` as stated [here](https://github.com/khanhas/spicetify-cli/issues/125), but that didn't work. I'm using the last known version of spotify to work for now

**Comment by khanhas** [comment]
Upgrade spicetify.

**Comment by megz15** [comment]
Welp, I didn't check the aur version but the chaotic aur one... after updating to 2.8.1 it is working
Apologies, and thank you :)
