### ISSUE TITLE
Spicetify not working after upgrading spotify (latest version of spicetify)

### ISSUE THREAD

**Issue by ElectronicApple** [khanhas/spicetify-cli#1268]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.72.439.gc253025e
- Spicetify version:  2.8.1

## 📝 Provide detailed reproduction steps (if any)

1. Download themes
2. Apply them
3. Open spotify

### ✔️ Expected result

The theme is applied and spotify works as normal

### ❌ Actual result

Blank background, background color is theme's background color though.

![image](https://user-images.githubusercontent.com/77444973/141682307-72da0787-488e-4a3c-91a5-1336c8d43a83.png)

**Comment by ElectronicApple** [comment]
Extra note, just downgraded to spicetify v2.8.0 to no avail

**Comment by TheGeeKing** [comment]
Can you provide your config file please?

**Comment by ririxidev** [comment]
Well, I bet you are using Windows Store version 🤔, install spotify from https://spotify.com/download and reinstall spicetify.

**Comment by ElectronicApple** [comment]
> Can you provide your config file please? Is there anything in devtool?

```
[Patch]

[Setting]
spotify_path            = C:\Users\<user>\AppData\Roaming\Spotify
color_scheme            = 
inject_css              = 1
overwrite_assets        = 0
prefs_path              = C:\Users\<user>\AppData\Roaming\Spotify\prefs
current_theme           = BurntSienna
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.72.439.gc253025e
with    = 2.8.0

```
I dont seem to be able to open DevTools via Ctrl+Shift+I or F12



> Well, I bet you are using Windows Store version 🤔, install spotify from https://spotify.com/download and reinstall spicetify.

Nope, not using winstore version

**Comment by ElectronicApple** [comment]
Re installed, this time manually and it seems to have worked 🤷‍♂️
thanks for the help though :)
