### ISSUE TITLE
fatal unlinkat (OpenSUSE Tumbleweed)

### ISSUE THREAD

**Issue by DankeBrutus** [khanhas/spicetify-cli#1273]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.8.1

## 📝 Provide detailed reproduction steps (if any)

1. Run command: `spicetify-cli backup apply enable-devtool`
2. Error: `fatal unlinkat /usr/lib64/spotify-client/Apps/login.spa: permission denied`
3. Run command: `sudo chmod 777 -R /usr/lib64/spotify-client/Apps/login.spa`
4. Run command: `spicetify-cli restore backup apply`
5. Error: `fatal unlinkat /usr/lib64/spotify-client/Apps/login.spa: permission denied`
6. Run command: `spicetify-cli backup apply`
7. Error: 
```
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
fatal unlinkat /usr/lib64/spotify-client/Apps/login.spa: permission denied
```

### ✔️ Expected result

Spicetify to modify Spotify and apply theming

### ❌ Actual result

fatal error, the commands have been run with sudo + permissions have been changed in the file manager, still the same error

## 📷 Screenshots

no

**Comment by ririxidev** [comment]
Your issue, you don't have permissions on `/usr/lib64/spotify-client` folder, we can't help in this situation. It's mostly openSUSE permissions problem but, you should be able to chmod this folder with right combination of permissions and it should be fine 👍 
@itsmeow to close - not related to spicetify.

**Comment by jonas-w** [comment]
Is there a workaround? Same thing happens on Ubuntu 21.10.

**Comment by jonas-w** [comment]
Got it [https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-snap](Change these permissions)
