### ISSUE TITLE
Extensions not working but themes are working. Could anyone help.

### ISSUE THREAD

**Issue by Scemworks** [khanhas/spicetify-cli#1274]
Here's my config
```
[AdditionalOptions]
extensions            = popupLyrics.js|fullAppDisplay.js|fluent.js|keyboardShortcuts.js
custom_apps           = 
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Setting]
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\PmShadin\AppData\Roaming\Spotify
current_theme           = Fluent
replace_colors          = 1
spotify_launch_flags    = 
prefs_path              = C:\Users\PmShadin\AppData\Roaming\Spotify\prefs
color_scheme            = dark
inject_css              = 1

[Preprocesses]
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.72.439.gc253025e
with    = 2.8.1

```

**Comment by Scemworks** [comment]
I tried [FullAppDisplay][https://github.com/khanhas/spicetify-cli/blob/master/Extensions/fullAppDisplay.js], [KeyboardSHortcuts][https://github.com/khanhas/spicetify-cli/blob/master/Extensions/keyboardShortcut.js] and [PopupLyrics][https://github.com/khanhas/spicetify-cli/blob/master/Extensions/popupLyrics.js].

**Comment by mix3d** [comment]
What I noticed on my hidePodcasts.js extension, it depended on the classnames being written out, but they were all obfuscated, so it didn't work anymore. Unsure what the resolution will be.

**Comment by TheGeeKing** [comment]
> What I noticed on my hidePodcasts.js extension, it depended on the classnames being written out, but they were all obfuscated, so it didn't work anymore. Unsure what the resolution will be.

What are your Spotify and spicetify versions?

**Comment by mix3d** [comment]
Aha! I thought I had updated my spicetify with `spicetify update`, but the correct command was `spicetify upgrade`. Moving from v2.7.1 to v2.8.1 fixed my issues. Hooray!

**Comment by TheGeeKing** [comment]
> I tried [FullAppDisplay](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/fullAppDisplay.js), [KeyboardSHortcuts](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/keyboardShortcut.js) and [PopupLyrics](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/popupLyrics.js.) and it didn't work.
> 

Can you send a screenshot of your devtool?

**Comment by Scemworks** [comment]
>Can you send a screenshot of your devtool?

How to find devtool in spotify??

**Comment by Scemworks** [comment]
> > I tried [FullAppDisplay](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/fullAppDisplay.js), [KeyboardSHortcuts](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/keyboardShortcut.js) and [PopupLyrics](https://github.com/khanhas/spicetify-cli/blob/master/Extensions/popupLyrics.js.) and it didn't work.
> 
> Can you send a screenshot of your devtool?

Can you send a screenshot of your devtool?

**Comment by TheGeeKing** [comment]
`spicetify enable-devtool`
Ctrl + shift + i or right click

**Comment by Scemworks** [comment]
> `spicetify enable-devtool` Ctrl + shift + i or right click

what should I take screenshot in devtool?

**Comment by TheGeeKing** [comment]
Console

**Comment by Scemworks** [comment]
> Console

![image](https://user-images.githubusercontent.com/93836208/142269015-a8951681-e22d-4a26-9a27-920005920df5.png)

**Comment by TheGeeKing** [comment]
You have an unexpected token error at the top for the tree extensions you are trying to use.

I can only recommend to delete and reinstall Spicetify.

**Comment by Scemworks** [comment]
How to delete and reinstall Spicetify??

**Comment by TheGeeKing** [comment]
Delete spicetify-cli and .spicetify folders

**Comment by y0himba** [comment]
I use shuffle+.js, loopyloop.js, and webnowplaying.js.  None of them are working.  The only one throwing an error that I can see is webnowplaying.js, it's unable to open a websocket.  It worked with 2.8.1 however and has only been doing this for about a week.  Nothing has changed on my system. 
 
 Spotify for Windows
1.1.72.439.gc253025e

Spicetify 2.8.2

![image](https://user-images.githubusercontent.com/11462603/143016749-38d0e819-a51f-4279-abad-c0b5f24051bb.png)

**Comment by khanhas** [comment]
@y0himba can I see your config file?

**Comment by y0himba** [comment]
Sorry, was at work.  Is this what you need?
`[Setting]
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 1
spotify_path            = C:\Users\y0himba\AppData\Roaming\Spotify
current_theme           = SpicetifyDefault
inject_css              = 1
prefs_path              = C:\Users\y0himba\AppData\Roaming\Spotify\prefs
color_scheme            = Purple

[Preprocesses]
disable_sentry        = 0
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = webnowplaying.js|shuffle+.js|loopyloop.js
custom_apps           = reddit|lyrics-plus|new-releases
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.72.439.gc253025e
with    = 2.8.2

`

**Comment by khanhas** [comment]
I can't identify the problem.
Please just set `experimental_features` to `0` in config file and run `spicetify apply`.

**Comment by y0himba** [comment]
No change after setting `experimental_features` to `0`.  I applied it, no change, so I did a restore then backup and apply again to be sure.

**Comment by CharlieS1103** [comment]
@y0himba Try it without webnowplaying extension, if that doesn't work try it without loopyloop, etc...

**Comment by y0himba** [comment]
Just got home from work and tried each extension on it's own.  None of them are working. I even disabled custom apps to be thorough. 

I am wondering if it is something to do with the websocket not connecting.  I have no idea how to fix that.  Is there a way I can change the address from 127.0.0.1 to this machine's 192.xxx.xxx.xxx? I'm not even sure that would help, just stabbing in the dark at this point.

**Comment by khanhas** [comment]
Yeah sorry, I don't think we can identify the problem anymore. Your case is very bizarre. I don't see why webnowplaying work but not the others. I well tested every extensions on every Spotify versions.
Did these extensions work before?

**Comment by y0himba** [comment]
Yes, they all worked until 2.8.2. Webnowplaying.js doesn't work either.

**Comment by afonsojramos** [comment]
I'd suggest a clean install. First, delete both the `.spicetify` and the `spicetify-cli` folders, then proceed to install everything again.

**Comment by y0himba** [comment]
I've never re-installed Spicetify believe it or not.  Where is it recommended to extract the archive to?

**Comment by y0himba** [comment]
I removed '.spicetify' and 'spicetify-cli'. Used Powershell to re-install per in the install instructions. Uninstalled Spotify, cleaned the directories left behind. Re-installed Spotify. 

Pretty sure at this point it's something on my end. Thanks for the troubleshooting assistance and advice. Sorry to take up everyone's time.

**Comment by TheGeeKing** [comment]
Hi @Scemworks, any update on your issue? Is it fixed?
