### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by luximus-hunter** [khanhas/spicetify-cli#1275]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.8.1

## 📝 Provide detailed reproduction steps (if any)

1. Run `spicetify apply`
2. See error

### ✔️ Expected result

Applied theme

### ❌ Actual result

Error message

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/49814847/142031406-b89a661a-a5f7-4122-802f-dbda9db9127b.png)

**Comment by khanhas** [comment]
Is it still happening?
Maybe something to do with the global internet outtake yesterday.

**Comment by luximus-hunter** [comment]
That's probably what caused it, yeah. I removed all spicetify files and reinstalled it, and that seemed to fix it.

**Comment by CEbbinghaus** [comment]
Can this issue be Reopened. I am having this problem and its stopping me from being able to use spiceify.

Running this on Windows 11 22000.675
Spotify for Windows 1.1.85.895.g2a71e1b8
Spicetify Version 2.9.9 installed via Scoop:
```
success Default config-xpui.ini generated.
spicetify v2.9.9
Backing up app files:
OK
Extracting:
OK
Preprocessing:
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/utils.FetchLatestTag()
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/vcs.go:29 +0x129
github.com/spicetify/spicetify-cli/src/preprocess.FetchLatestTagMatchingOrMaster({0xeeb978, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/preprocess/preprocess.go:544 +0x2d
github.com/spicetify/spicetify-cli/src/preprocess.Start({0xeeb978, 0x5}, {0xc0000cc480, 0x27}, {0x1, 0x1, 0x1, 0x1, 0x1})
        /home/runner/work/spicetify-cli/spicetify-cli/src/preprocess/preprocess.go:76 +0x145
github.com/spicetify/spicetify-cli/src/cmd.Backup({0xeeb978, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/backup.go:61 +0x84b
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:219 +0x7e9
```


This issue occurs whenever i try to run spicetify even if i have cleared all the local data and reinstalled Spotify, Spicetify or both
