### ISSUE TITLE
Musixmatch tokens don't work anymore

### ISSUE THREAD

**Issue by frodo36** [khanhas/spicetify-cli#1277]
## ℹ Computer information

- Spotify version: 1.1.72
- Spicetify version: 2.8.1

This isn't really a spicetify issue, but I noticed that getting a new Usertoken from the Musixmatch app or website doesnt work anymore. The Token I get is a few characters shorter and neither Popup-lyrics nor Lyrics-plus will accept it. However my Token that i got a while ago still works. Is there just something I did wrong, or did Musixmatch change something with their tokens?

## 📝 Provide detailed reproduction steps (if any)

1. Follow the steps on the spicetify wiki to obtain a Musixmatch token
2. Put the token into lyrics-plus or Popup-lyrics

### ✔️ Expected result

Lyrics-plus and Popup-lyrics will accept the token and fetch lyrics from Musixmatch

### ❌ Actual result

The token is not accepted 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/88240067/142145317-aa3bc525-128d-43ca-ad66-bbc7dac46b87.png)

**Comment by khanhas** [comment]
Yeah token from the website doesn't work for me too but the one from windows app still works fine.
Here a free one for you: 211117e30ad03b818a41fd7d38b8191cadf33e797bef89ae809017

**Comment by frodo36** [comment]
Damn, thanks a lot for the token! 
Strange, for me also the app doesn't work for some reason. But I got a token now, so I guess my problem is fixed.
