### ISSUE TITLE
spicetify setups for spotify dissapired. linux fedora

### ISSUE THREAD

**Issue by bigkrp** [khanhas/spicetify-cli#1280]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: v2.7.2

## 📝 Provide detailed reproduction steps (if any)

1. Open spotify app

### ✔️ Expected result
I have extensions according to my config(Lyrics extension)

### ❌ Actual result
No extensions on Spotify Client

## 📷 Screenshots
![Снимок экрана от 2021-11-18 14-20-42](https://user-images.githubusercontent.com/11586744/142414420-30924429-a147-4b10-b534-ed19cd05a26e.png)

My config:
![Снимок экрана от 2021-11-18 14-21-36](https://user-images.githubusercontent.com/11586744/142414496-762b8df6-8205-44c3-ba49-ed4e8746a16b.png)

**Comment by afonsojramos** [comment]
Try running just `spicetify`. You will see that you will need to update spicetify ;)
