### ISSUE TITLE
[linux] right click menu disappears instantly

### ISSUE THREAD

**Issue by franciskafieh** [khanhas/spicetify-cli#1281]
## ℹ Computer information

- Spotify version:
```
/usr/libexec/spotify/spotify --version
/usr/libexec/spotify/spotify: /usr/libexec/spotify/libcurl-gnutls.so.4: no version information available (required by /usr/libexec/spotify/spotify)
Spotify version 1.1.72.439.gc253025e, Copyright (c) 2021, Spotify Ltd
```

- Spicetify version: 
```
./spicetify -v     
2.8.1
```

- Kernel: Linux 5.13.19_1 x86_64
- Distro: Void (completely updated system)

## 📝 Provide detailed reproduction steps (if any)
./spicetify enable-devtool
./spicetify apply

### ✔️ Expected result
I can use devtools with `ctrl + shift + i` to get a dev tools menu.

### ❌ Actual result
I must hold `ctrl` or `shift` and right click to get a proper menu.

## 📷 Screenshots
 desired menu (when i hold shift or ctrl and right click)
![image](https://user-images.githubusercontent.com/93789670/142690380-70d17fe8-0a84-45a8-9531-dbc708636dad.png)

**Comment by khanhas** [comment]
Not spicetify bug.
Spotify poorly implement that for Linux and nothing I can do about it.

**Comment by franciskafieh** [comment]
whoops. i thought i closed this. i realized shortly after that this is not a spicetify thing. thanks!
