### ISSUE TITLE
Using Lyrics Plus instead of the built-in lyrics feature

### ISSUE THREAD

**Issue by ErickHoward** [khanhas/spicetify-cli#1282]
Is there any point in using Lyrics Plus after now that Spotify has built-in lyrics support? Would it be possible to extend the built-in lyrics feature with more features similar to Lyrics Plus?

*The built-in lyrics feature:*
![spotify built-in lyrics censored](https://user-images.githubusercontent.com/78889625/142713357-a7bdef1e-4010-4e14-adb0-6a8123dd9d04.png)

**Comment by khanhas** [comment]
Lyrics-plus app is built upon default Lyrics app, include its lyrics provider. So what you asked is already done.
Explore lyrics-plus and decide yourself. Whether you want lyrics-plus custom app's advanced customisations or you like default lyrics app's simplicity.
