### ISSUE TITLE
FullAppDisplay display incorrectly on tall Spotify window

### ISSUE THREAD

**Issue by hiranokite** [khanhas/spicetify-cli#1283]
## ℹ Computer information

- Spotify version: any version
- Spicetify version: any version

## 📝 Provide detailed reproduction steps (if any)

1. Just set spotify window with big height and low width, and start FullAppDisplay

### ✔️ Expected result

Show FullAppDisplay correctly

### ❌ Actual result

Mess the top of FullAppDisplay

## 📷 Screenshots

![bug](https://user-images.githubusercontent.com/5361459/142718335-0fd57b45-7192-42d6-b2f9-5fc3254334a5.png)

**Comment by TheGeeKing** [comment]
Duplicate #835. Can you reopen it @khanhas @itsmeow ?
