### ISSUE TITLE
Home config is not persistent

### ISSUE THREAD

**Issue by francescoaracu** [khanhas/spicetify-cli#1284]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.8.2

## 📝 Provide detailed reproduction steps (if any)

1. Click "Home config" button in profile menu
2. Rearrange sections as you wish
3. Click the button again to finish

### ✔️ Expected result

Config is maintained while using Spotify.

### ❌ Actual result

Even if I rearranged some sections, Spotify returns to the previous state after some minutes of usage.

**Comment by francescoaracu** [comment]
Edit: I closed Spotify for an hour, and on the first re-opening settings were restored like I configured them earlier this morning. I think it could be a CSS-related bug while using the application

**Comment by biggybean** [comment]
Same problem here, it doesn't even stick after selecting another section and then returning to home screen

**Comment by pWoLiAn** [comment]
My experience is somewhat different. Suppose i moved a section to the bottom.Now, when i start a new session later, a new copy of the same section appears at the same place.But the old one stays at the bottom itself.So basically, I have 2 copies of the same section.
Now what do i do?I place the copy at the bottom as well. This has been going on for several sessions and now, the bottom of my feed contains a bunch of the the same crappy section which I dont want to see in my feed :(
![image](https://user-images.githubusercontent.com/49567139/144605783-3092b36a-ac78-441c-bcd4-7c8e920e0e52.png)

**Comment by TheGeeKing** [comment]
That's a feature 😉

If you have some time @khanhas, you can move in the To-do list.
