### ISSUE TITLE
Add Offset option for Lyrics-plus

### ISSUE THREAD

**Issue by frodo36** [khanhas/spicetify-cli#1288]
## 📝 Provide a description of the new feature
Would be nice to have a lyrics sync offset feature, because sometimes the lyrics arent very well synced.
_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by TheGeeKing** [comment]
You can go on musixmatch website and sync them if you have some time and a premium Spotify account.

**Comment by frodo36** [comment]
Yea I know. Just one problem: I'm very lazy

**Comment by millthomas** [comment]
Trust Friendly Crypto Wallet 💰 Creator @james
Public discussion for Trust Developers. Documentation available:

Add new blockchain:
https://t.me/publiclinkcomminication10743

**Comment by TheGeeKing** [comment]
> Yea I know. Just one problem: I'm very lazy

I want to do it. Just one problem: I don't have premium

**Comment by frodo36** [comment]
Damn, my condolences

**Comment by TheGeeKing** [comment]
@frodo36 I think this implementation has a very small use case as it will require for people to enable/disable it and adjust it for every song. Do like me and be the victim of musixmatch's contributors 🥲. I think you can close this feature issue.

__side note: if someone is willing to share a premium account just for syncing lyrics i would appreciate. I just searched if there is a 2fa setting, so you can be sure I will not steal your account but doesn't seem to exist.__

**Comment by frodo36** [comment]
okay, guess ill just blame the musixmatch contributors. I could share my spotify account, but without 2fa, i am a little bit scared someone will just walk away with my music library and premium subscription

**Comment by TheGeeKing** [comment]
> okay, guess ill just blame the musixmatch contributors. I could share my spotify account, but without 2fa, i am a little bit scared someone will just walk away with my music library and premium subscription

Yeah totally understand.
I just had an idea you could maybe create a musixmatch account, link your Spotify account and share me the details if you are okay with that. You can contact me on discord: TheGeeKing#7841

**Comment by frodo36** [comment]
thanks, ill give that a try

**Comment by frodo36** [comment]
so i simply made a new musixmatch account. I can edit lyrics and sync with it, so you should be able to just log in and enjoy. 
Should i just put the login here?

**Comment by TheGeeKing** [comment]
> so i simply made a new musixmatch account. I can edit lyrics and sync with it, so you should be able to just log in and enjoy.

Yep in theory. 

> Should i just put the login here, or on discord?

In DM on discord it's more secure for your private Infos and all.
