### ISSUE TITLE
webNowPlaying does not fetch cover art from local songs

### ISSUE THREAD

**Issue by in1tiate** [khanhas/spicetify-cli#129]
Might be better to file this over on the WebNowPlaying GitHub, but it only really affects Spotify so I'm putting it here.

When playing local music through Spotify's "local files" feature, WebNowPlaying doesn't seem to fetch it. Rainmeter skins displaying WebNowPlaying's output only display title, artist, album, etc. but either display the last cover art WebNowPlaying _did_ fetch or if there isn't any, no cover art at all.

Might be related to the way the WebNowPlaying plugin grabs album art.

**Comment by khanhas** [comment]
WebNowPlaying downloads cover art via links fed from Spotify client. Since there is no "link" to local files cover arts (they are loaded internally the client), WebNowPlaying cannot download it.

**Comment by in1tiate** [comment]
I see. Are there any possible workarounds, like pointing WebNowPlaying at a `file:///` link?

**Comment by luis815** [comment]
It's a WebNowPlaying problem.  It's up to it to check if the input should be a url or however local files store covers.
