### ISSUE TITLE
Scoop repo for windows is pretty much unmaintained

### ISSUE THREAD

**Issue by zwxi** [khanhas/spicetify-cli#1290]
The scoop repo listed in the wiki spews a whole lot of errors since a lot of legacy extensions and themes are still being used in the automated scripts used to run the installer. 

@TheRandomLabs who owns the repo hasn't been active for over a year and multiple issues and PRs remain unattended.

**Comment by zwxi** [comment]
FYi I've fixed this issue but since @TheRandomLabs is not responding I've [forked](https://github.com/nexus-codes/Scoop-Spotify) this repo and added all the fixes there.

**Comment by sitiom** [comment]
I have just added [`spicetify-cli`](https://github.com/ScoopInstaller/Main/blob/master/bucket/spicetify-cli.json) and [`spotify`](https://github.com/ScoopInstaller/Extras/blob/master/bucket/spotify.json) to the official main and extras bucket, which should solve this issue as well.
