### ISSUE TITLE
Spicetify.expFeatureOverride is not a function with newest versions of spicetify and Spotify

### ISSUE THREAD

**Issue by urbanjackjr** [khanhas/spicetify-cli#1292]
## ℹ Computer information

- Spotify version: 1:1.1.72.439-1 (AUR)
- Spicetify version: 2.8.2

## 📝 Provide detailed reproduction steps (if any)

1. Opening the app with spicetify
2. Error as shown above occurs

### ✔️ Expected result

Well, working theme

### ❌ Actual result

Error message as shown on the screenshot

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/61840218/142937329-f5ce33e3-6089-4abb-b067-ae11f33eabac.png)

**Comment by khanhas** [comment]
Reinstall Spotify
Run `spicetify backup apply`

**Comment by urbanjackjr** [comment]
Still no luck. Tried uninstalling Spotify multiple times, deleting config files, but the error still appears. Even when applying backup.

**Comment by afonsojramos** [comment]
@urbanjackjr did you try removing the `spicetify-cli` and `.config/spicetify` folders?

**Comment by afonsojramos** [comment]
Closing over inactivity.
