### ISSUE TITLE
[LyricsPlus] Apply user preference consistently

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1293]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.72.439.gc253025e
- Spicetify version: v2.8.2

## 📝 Provide detailed reproduction steps (if any)
1. Go to lyric plus config.
2. Set alignment preference.

### ✔️ Expected result
Setting alignment preference should ensure that regardless of karaoke/synced/unsynced/genius lyrics the user's preference must be respected.

### ❌ Actual result

User preference doesn't change the interface for unsynced or genius lyrics.

## 📷 Screenshots

1. Config
![image](https://user-images.githubusercontent.com/63046776/143075507-0e013914-2fc6-4e27-8e55-f7bc661b9633.png)

2. Synced Lyrics
![image](https://user-images.githubusercontent.com/63046776/143075342-50312145-6fcf-4352-98f3-d7577449364b.png)

3. Unsynced Lyrics
![image](https://user-images.githubusercontent.com/63046776/143075626-1108ff8e-5647-40e2-b333-4ea01dd5b6cf.png)

4. Genius Lyrics
![image](https://user-images.githubusercontent.com/63046776/143075775-c40dfb5b-9617-405b-9d0b-deb2587e682a.png)

**Comment by SupLiCatinG** [comment]
How can i make lyrics plus background blurred ? What is your theme name ?

**Comment by afonsojramos** [comment]
Valid request, at the time the suggestion was to solely implement for Synced lyrics, but I'll take a look!

**Comment by lemonnuggets** [comment]
> How can i make lyrics plus background blurred ? What is your theme name ?

@SupLiCatinG the theme I'm using is https://github.com/JulienMaille/spicetify-dynamic-theme

**Comment by khanhas** [comment]
Fixed v2.8.3
