### ISSUE TITLE
WebNowPlaying and FullAppDisplay Loading but Not Working

### ISSUE THREAD

**Issue by Fosmos** [khanhas/spicetify-cli#1296]
## ℹ Computer information

- Spotify version: 1.1.73.515.g85e282e2
- Spicetify version: 2.8.2

## 📝 Provide detailed reproduction steps (if any)

1. Set webnowplayin.js and fullAppDisplay.js extensions in the config
2. Apply

### ✔️ Expected result

- WebNowPlaying working or at least showing an error in Rainmeter logs
- FullAppDisplay displayed when icon or hotkey pressed

### ❌ Actual result
The config applies without any problems but the extensions don't do anything. WebNowPlaying shows no issue on Rainmeter, but also doesn't seem to do anything. FullAppDisplay shows the icon correctly, but can't be activated through either the icon or the F11. As a side note the custom app 'New Release' page shows but it never loads in data, so my guess is that extensions as a whole are busted in the latest spotify.

**Comment by khanhas** [comment]
Wait til later today for new Spicetify update.

**Comment by khanhas** [comment]
Upgrade Spicetify to v2.8.3
