### ISSUE TITLE
CosmosAsync is missing in Spotify 1.1.73.515

### ISSUE THREAD

**Issue by theRealPadster** [khanhas/spicetify-cli#1297]
## ℹ Computer information

- Spotify version: Spotify for macOS (Intel) 1.1.73.515.g85e282e2
- Spicetify version: 2.8.2

## 📝 Provide detailed reproduction steps (if any)

1. Install specified versions
2. Open dev tools
3. Run `Spicetify.CosmosAsync`

### ✔️ Expected result

`Spicetify.CosmosAsync` exists

### ❌ Actual result

`Spicetify.CosmosAsync` is `undefined`

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/1565883/143380614-568866f5-0bcd-4b6c-ad73-f27135802cd6.png)
![image](https://user-images.githubusercontent.com/1565883/143382234-068e9bb6-0592-49a4-afe4-59199e564504.png)

**Comment by khanhas** [comment]
Fixed
