### ISSUE TITLE
Trying to make it work on Flatpak

### ISSUE THREAD

**Issue by rawlife56** [khanhas/spicetify-cli#13]
I have been trying to make it work on Flatpak installation of Spotify but looks like css is packed differently. 
Is there any workaround for this ?

**Comment by khanhas** [comment]
1. You need to find where Flatpak stores your Spotify client. As in Manjaro, it stores mine in:
```
/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
```

![image](https://user-images.githubusercontent.com/26436809/57563050-81408780-73dc-11e9-92e8-d0cc60502ff3.png)

2. Set `spotify_path` in config file to that directory:
![image](https://user-images.githubusercontent.com/26436809/57563057-9ddcbf80-73dc-11e9-82d8-d31cdf7e9cef.png)

3. In terminal, set read/write permission for it:
```
sudo chmod 777 -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
```

4. Happy customizing!

**Comment by rien333** [comment]
What does spotify path exactly refer to? The binary? Or the `/usr/share/spotify` folder that I have on Arch Linux?

**Comment by RobinOpletal** [comment]
For me, the prefs path for flatpak isn't in .config/spotify/prefs

spicetify apply
spicetify v0.9.8
error /home/myusername/.config/spotify/prefs does not exist or is not a valid path.

Do you know where the flatpak version of spotify stores it's configuration? Thanks!

**Comment by AzizStark** [comment]
`~/.var/app/com.spotify.Client/config/spotify/prefs`

**Comment by lucaliceti** [comment]
> `~/.var/app/com.spotify.Client/config/spotify/prefs`

I have flatpak spotify as that exact path, but copying/pasting it still gives me the same error.

**Comment by mjamilrahman** [comment]
The problem is. Where is config file location. I don't see in documentation hahahha

**Comment by GinoongFlores** [comment]
> The problem is. Where is config file location. I don't see in documentation hahahha

I hope you found the config file location. For those who haven't yet. Base on my experience on Fedora, there's no config file after installing the scripts, you need to relaunch your terminal to refresh the system and enter `spicetify` that generates a `config-xpu.ini` a config file in the dir of `/home/yourusername/.config/spicetify` in which you can modify base on the instructions.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I cant really find the config-xpu.ini file either
