### ISSUE TITLE
fullAppDisplay background problem

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1300]
## ℹ Computer information
- Windows 10 Home Single Language (21H2) 
- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.8.3

### ✔️ Expected result
Blurry background in "fullAppDisplay.js" extension (if i change song it fixes itself) 
_What is the expected result of the above steps?_

### ❌ Actual result

Shown in screenshots (in default theme it doesnt even working properly) 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/94017480/143422877-33a209fd-a91c-46e5-9ca5-af9659eb4d2f.png)

![image](https://user-images.githubusercontent.com/94017480/143423180-cf90cb60-7dc6-42de-9da7-b78debf8e5e8.png)

**Comment by khanhas** [comment]
Yeah, I have no idea what causes that. It does that randomly and only in Full screen mode.

**Comment by TrialExpired** [comment]
In case it hasn't been documented yet, I've been having a similar issue, but instead of just removing the blur it also removes the background cover art so the normal UI is visible.
![image](https://user-images.githubusercontent.com/61850321/144298776-4c646007-33dd-4348-9dd3-dd81d0e2661b.png)

**Comment by TheGeeKing** [comment]
> In case it hasn't been documented yet, I've been having a similar issue, but instead of just removing the blur it also removes the background cover art so the normal UI is visible.
> ![image](https://user-images.githubusercontent.com/61850321/144298776-4c646007-33dd-4348-9dd3-dd81d0e2661b.png)
> 

#1302

**Comment by SupLiCatinG** [comment]
![image](https://user-images.githubusercontent.com/94017480/144300514-7f695e7b-ed6c-461f-9952-69c18e2a7f0b.png)
Just uncheck Enable fullscreen until next update. That fix 98% of problem(s).

**Comment by TrialExpired** [comment]
Noted, thanks

**Comment by khanhas** [comment]
Fixed
