### ISSUE TITLE
FullAppDisplay bug when disable integrated lyrics

### ISSUE THREAD

**Issue by TheGeeKing** [khanhas/spicetify-cli#1302]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.73.515.g85e282e2
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. does the steps to enable lyrics in fad
2. disable lyrics in fad

### ✔️ Expected result

_What is the expected result of the above steps?_
go back to fad without lyrics enable

### ❌ Actual result

_What is the actual result of the above steps?_
fad background disappear but cover stays and fullscreen mode stays 
user needs to escape fad and enable it back

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/58857539/143501466-8cf4bc27-de61-4987-8f6a-d39b8905c767.png)
![image](https://user-images.githubusercontent.com/58857539/143501510-91537bd0-abc7-49af-9043-d811704a8564.png)

**Comment by TheGeeKing** [comment]
update: as mentioned in #1303 had to update the custom app lyrics-plus to get the lyrics on the side but still issue with the UI

![image](https://user-images.githubusercontent.com/58857539/143503091-f2f3d845-31b2-4101-adb2-ae257abc025c.png)

**Comment by khanhas** [comment]
Fixed
