### ISSUE TITLE
spicetify upgrade doesn't upgrade extensions and custom apps

### ISSUE THREAD

**Issue by TheGeeKing** [khanhas/spicetify-cli#1303]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.73.515.g85e282e2
- Spicetify version: spicetify 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. spicetify upgrade

### ✔️ Expected result

_What is the expected result of the above steps?_
updates extensions and custom apps

### ❌ Actual result

_What is the actual result of the above steps?_
doesn't update extensions
user needs to manually download files and replace them...
same for custom apps
and upgrade and other commands should implicitly restore, backup or apply depending on the situation.

**Comment by daksh2k** [comment]
It works as intended on my end.
It does update them but you have to run
`spicetify restore backup apply` after upgrading to push the new stuff to the client.

**Comment by TheGeeKing** [comment]
Never worked for me and a lot of people. I use spicetify since 2.5.0 patch 4

**Comment by CharlieS1103** [comment]
Worked for me, only way I could see it not working is if you have your extensions and custom apps downloaded jn your config folder and not the spicetify-cli folder.

**Comment by ayyneya** [comment]
GeeKing helped me sort out my issue with shuffle+ and the reason was upgrade not updating the custom apps
