### ISSUE TITLE
Lyrics Translation from Musixmatch feature  

### ISSUE THREAD

**Issue by kotobuki09** [khanhas/spicetify-cli#1304]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_
As the music language is universal, we also need a translation in lyrics so we can all understand what a song is about.
The lyrics would be even more meaningful, if there might be a translation below it like in the musixmatch application.

[https://i.pinimg.com/originals/82/3b/47/823b4796bccc3d39a7d47315b267e7ee.jpg](url)
https://developer.musixmatch.com/documentation/api-reference/track-subtitle-translation-get

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Nope. Desktop app API is different than developer API. They don't have same set of method. As far as I checked, desktop one only has synced original language track lyrics and nothing else. No translation or RichSync method.
