### ISSUE TITLE
[Full App Display] Font isn't visible on white/black album covers

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1306]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.72.439.gc253025e
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Enable FAD Lyrics Plus Integration.
2. Listen to music with black or white album art.

### ✔️ Expected result

The background should be blurred or something so that font is still clearly visible.

### ❌ Actual result

Letters aren't clearly visible cuz of same color as the background.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/63046776/143558297-4dbc9e2f-6a94-4d20-9e71-036c27e33c6c.png)

**Comment by khanhas** [comment]
Duplicate https://github.com/khanhas/spicetify-cli/issues/1300
