### ISSUE TITLE
shuffle+ not working properly

### ISSUE THREAD

**Issue by znicuuu** [khanhas/spicetify-cli#1307]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb on Windows 11
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. enable shuffle+.js extension
2. right click on any playlist and press play with shuffle+ 
3. error code shows up

### ✔️ Expected result

shuffle+ works normally

### ❌ Actual result

error code shows up and it doesnt do anything

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/73033465/143594976-be998409-dbac-4d55-b0fb-cbfbb3ede782.png)

![image](https://user-images.githubusercontent.com/73033465/143595111-c2837479-084b-4110-bddc-b73a0e499247.png)

**Comment by frodo36** [comment]
Try updating spicetify and shuffle+ to their latest version

**Comment by znicuuu** [comment]
> Try updating spicetify and shuffle+ to their latest version

thanks its fixed with the new version
