### ISSUE TITLE
FAD lyrics do not work

### ISSUE THREAD

**Issue by Fuzqi** [khanhas/spicetify-cli#1312]
## ℹ Computer information

OS: Windows v10.0.22000 (Windows 11)
Spotify: v1.1.73.517
Spicetify: v2.8.3
Dribbblish: v4.0.0-8ba60b4

## 📝 Provide detailed reproduction steps (if any)

1. Go on FAD and go to settings
2. Enable lyrics intergration

### ✔️ Expected result

Lyrics that go with the song will pop up beside the album cover and name of song

### ❌ Actual result

I don't have any lyrics that pop up, the album cover just moves to the left and there is a big blank space on the right of my screen where the lyrics are meant to be.

## 📷 Screenshots
With lyrics intergrations on:
![image](https://user-images.githubusercontent.com/74432053/143682464-5aa24c46-759c-4805-9a7d-d819fe916b31.png)

Without lyrics integration on:
![image](https://user-images.githubusercontent.com/74432053/143682520-a9d7405c-0f2a-474e-889b-0d7e6746db0f.png)

**Comment by frodo36** [comment]
Have you updates spicetify FAD and Lyrics-plus? It won't work if you don't update lyrics-plus

**Comment by Fuzqi** [comment]
> Have you updates spicetify FAD and Lyrics-plus? It won't work if you don't update lyrics-plus

How do I get/update lyrics-plus

**Comment by frodo36** [comment]
Download the lyrics-plus custom app from the spicetify repo. Then replace the lyrics-plus folder in .spicetify

**Comment by Fuzqi** [comment]
> Download the lyrics-plus custom app from the spicetify repo. Then replace the lyrics-plus folder in .spicetify

I installed the reddit one by accident how do i remove it

**Comment by frodo36** [comment]
Open the config file and remove "reddit" from the "custom_apps" category. Then run "spicetify apply" in powershell. You have to run "spicetify apply" after you replace the lyrics-plus folder too btw

**Comment by khanhas** [comment]
lyrics-plus comes with spicetify by default. You don't need to download anything. Just add `lyrics-plus` to custom_apps field in config file and run `spicetify apply`.

If you already download and copy to your ".spiceitfy\CustomApps". You might want to remove it because it would prevent you to receive new update in the future.
