### ISSUE TITLE
[FullApp Display] Scrollbars show up when using genius lyrics.

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1317]
## ℹ Computer information

- Spotify version: 
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Enable Lyrics Plus Integration with Full App Display
2. Play song that uses Genius lyrics.

### ✔️ Expected result

Like other times no scrollbars should show up.

### ❌ Actual result

Scrollbars show up on the bottom and the side where the lyrics are displayed.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/63046776/143875359-45ba874d-e427-4230-8a36-2992202b597c.png)

**Comment by khanhas** [comment]
Nah.
