### ISSUE TITLE
Add three dots before lyrics like in Apple Music

### ISSUE THREAD

**Issue by frodo36** [khanhas/spicetify-cli#1318]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Maybe add something like the three dots in Apple Music before the lyrics starts. I know this is really just extra fanciness, but it would still be cool to add it, if there's an easy implementation, in my opinion.

https://user-images.githubusercontent.com/88240067/143888204-bbf67c3d-a17f-44ff-ba02-3fd8969eeeda.mp4

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Added.
