### ISSUE TITLE
(fullAppDisplay) Auto collapse when no available lyrics for Music

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1319]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Auto collapse lyrics pane when no available lyrics for selected Music.

Spicetiy:

https://user-images.githubusercontent.com/94017480/143920970-c1e7675e-3cbf-4ed4-99ed-c0a07d2a3677.mov

How it should be:

https://user-images.githubusercontent.com/94017480/143921028-ecef51f1-b680-4728-bf40-2c407410d7f2.mov

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Nah
