### ISSUE TITLE
(fullAppDisplay) Quick toggle button for Lyrics Pane

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1320]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Quick toogle for Lyrics Pane 

https://user-images.githubusercontent.com/94017480/143921515-9a533e74-d810-40ec-a92d-e840c9668a70.mov

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Nah.
