### ISSUE TITLE
(fullAppDisplay) A working seek bar 

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1321]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Working seek bar for fullAppDisplay

We have an options for media control on fullAppDisplay but why we cant seek music through ? 

https://user-images.githubusercontent.com/94017480/143921981-5691d036-2b84-478d-a0d8-b6b512b58d0c.mov

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Nah.
