### ISSUE TITLE
(fullAppDisplay) Independent size control for fullAppDisplay

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1322]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

We can control Spotiy's UI with CMD/CTRL + (+/-). That is working on fullAppDisplay too but it affects Spotify's ui.
I just want to adjust fullAppDisplay's size, if it is impossible to make working can we make album art bigger ? Because in high resulution screens it is looking so small. 

Here is a demonstration

https://user-images.githubusercontent.com/94017480/143922858-897eac18-f1e5-41fa-beca-bc6bc365aa95.mov

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Added.

**Comment by Alehaaaa** [comment]
> Added.

Where is the option/hotkey or how can we zoom-in without messing with Spotify's scale? I can't find it anywhere.
