### ISSUE TITLE
Playback Speed Control 

### ISSUE THREAD

**Issue by BotAndis** [khanhas/spicetify-cli#1324]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Change the Playback Speed of songs. Change Song speed for what ever reason, in my case I would use it to speed up my podcast, which is not marked as a Podcast (split in 3 min parts).

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Not possible.
