### ISSUE TITLE
Cannot detect Spotify location

### ISSUE THREAD

**Issue by BitMap4** [khanhas/spicetify-cli#1326]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Run `spicetify` after installing.

### ✔️ Expected result

Spicetify generates a `config-xpui.ini` file with a `spotify_path` value.

### ❌ Actual result

The `config-xpui.ini` file does not have a value for `spotify_path` and displays an error on the terminal.

## 📷 Screenshots

![Screenshot 2021-12-02 at 12 27 58 PM](https://user-images.githubusercontent.com/64366765/144373263-e48cf7d3-0c43-42f6-a3ea-b7d78283e975.png)

**Comment by khanhas** [comment]
OS?

**Comment by BitMap4** [comment]
MacOS 11.5.1

**Comment by khanhas** [comment]
I think you need to identify Spotify location yourself and set it to config file
Default location is: `/Applications/Spotify.app/Contents/Resources`

**Comment by BitMap4** [comment]
Ah, I did try setting it manually, but I didn't add the `Contents/Resources` part, and that was leading to another error when I tried using the backup command. The backup command worked now, thanks.
By the way, was it not able to find the location because of some error in the code or was the error on my side?

**Comment by SupLiCatinG** [comment]
> Ah, I did try setting it manually, but I didn't add the `Contents/Resources` part, and that was leading to another error when I tried using the backup command. The backup command worked now, thanks. By the way, was it not able to find the location because of some error in the code or was the error on my side?

Works perfectly for me macOS 11.6.1

**Comment by khanhas** [comment]
Idk. That path I gave is always where Spotify locates. You are the first ever reported that Spotify location is different.

**Comment by BitMap4** [comment]
I have Spotify installed on the Home user, so the location in my case was `/Users/Home/Applications/Spotify.app/Contents/Resources` (i.e. `~/Applications/Spotify.app/Contents/Resources`).
I'm guessing spicetify tried `/Applications/Spotify.app/Contents/Resources`
