### ISSUE TITLE
Artist name not working on rainmeter skin

### ISSUE THREAD

**Issue by Elsynia** [khanhas/spicetify-cli#1327]
## ℹ Computer information

- Spotify version: 1.1.34 (and version before, the issue was still here)
- Spicetify version: 2.8.3 (and 2.8.2 was the same, still the issue)

### ✔️ Expected result

To see artist, name, cover, etc.. on my rainmeter skin

### ❌ Actual result

Everything is working except artist name but rainmeter keep getting error to fetch the artist (and rating, but I don't need rating) and I have no idea why

## 📷 Screenshots
![image_2021-12-02_093010](https://user-images.githubusercontent.com/95407652/144385584-00631574-accd-4bbe-9b75-e57cedef07cb.png)
![image](https://user-images.githubusercontent.com/95407652/144385626-82d6c7de-f41e-458b-a02e-e9dfdb940337.png)

_Are there any useful screenshots?_

**Comment by nodgear** [comment]
Just tested the websocket connection, and there's no issue with webnowplaying.js.
i tested against my own project, which listens for the same format.

**Comment by nodgear** [comment]
![image](https://user-images.githubusercontent.com/22383863/144843488-2047dafb-9350-4d18-b246-20b0075ce767.png)
Here's both title and artist name being shown using the same webnowplaying.js structure.

**Comment by Elsynia** [comment]
So it's supposed to be working ? (Sorry but i'm kinda lost and english is not my native language) ^^'
I'm just looking for help and couldn't find any post somewhere with my issues

**Comment by nodgear** [comment]
Yes, it's supposed to be working.

**Comment by TheGeeKing** [comment]
Why ping edit?

@Elsynia with spicetify 2.8.3 you are supposed to use Spotify 1.1.73

**Comment by nodgear** [comment]
> Why ping edit?
> 
> @Elsynia with spicetify 2.8.3 you are supposed to use Spotify 1.1.73

oh, lmao.
force of habit (forums).

**Comment by Elsynia** [comment]
Oh, so it's because my spotify version is not correct, gonna try to get this one, thanks !
