### ISSUE TITLE
Lyrics-plus animation bugs out

### ISSUE THREAD

**Issue by frodo36** [khanhas/spicetify-cli#1330]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: 2.8.3

## 📝 Provide detailsed reproduction steps (if any)
Play a song and go to the lyrics-plus tab. On seemingly random times, the lyrics animation will bug out.
1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
The animation plays normally

### ❌ Actual result

_What is the actual result of the above steps?_
The lyrics animation bugs out

## 📷 Screenshots

https://user-images.githubusercontent.com/88240067/144548825-6f148f48-405a-45f7-93f0-a7edf46be22a.mp4

_Are there any useful screenshots?_

**Comment by khanhas** [comment]
Yeah. It's hard to have lines switching animation + center aligned current active line. It's the best I can do.
