### ISSUE TITLE
Spotify not opening.

### ISSUE THREAD

**Issue by iDCoded** [khanhas/spicetify-cli#1331]
## ℹ Computer information

- Spotify version: **Spotify for Windows 1.1.73.517.gbef50fdb**
- Spicetify version: **2.8.3**

## 📝 Provide detailed reproduction steps (if any)

When I open Spotify using a shortcut (taskbar), it says '*The Spotify application is not responding.*' 
But, when I open Spotify from the tray icon, it opens and works properly.

### ✔️ Expected result

Open Spotify using the shortcut. 

### ❌ Actual result
Displays a dialog box saying '*The Spotify application is not responding.*' as seen in the screenshot. 

## 📷 Screenshots

![spotify warning](https://user-images.githubusercontent.com/65074550/144574048-4dd582bb-225c-4aed-b125-931e54534714.png)

**Comment by SupLiCatinG** [comment]
This isnt a spicetify bug. Mostly due to lack of hardware resources spotify doing this. Just close the app on the Task Manager and re-open it.

**Comment by iDCoded** [comment]
> This isnt a spicetify bug. Mostly due to lack of hardware resources spotify doing this. Just close the app on the Task Manager and re-open it.

Well I restarted my PC and it seemed to fix the issue. 
Thank you for your assistance. :)
