### ISSUE TITLE
[Linux] Spofify crashed during startup

### ISSUE THREAD

**Issue by jackbillstrom** [khanhas/spicetify-cli#134]
Hi, currently on my `Ubuntu 19.04` and had some trouble lately while starting the Spotify-client after customizing it.

**Errors**
`[0121/103753.603463:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`

`Segmentation error (memory print created)` 

**Temporary solution**
While the launcher opened the client without wanted parameters, I'll use the terminal for now.
`spotify --disable-gpu`

**Comment by khanhas** [comment]
`spicetify` does nothing to executable binary file so it is very unlikely `spicetify` is the cause.
Try uninstall and install Spotify and apply `spicetify` again.

**Comment by jackbillstrom** [comment]
Noticed now that Spotifys own **.deb* is what must be causing this.

The snap package is the only one that runs smooth appearently.

Works fine though if I startup Spotify without a internet connection
