### ISSUE TITLE
(fullAppDisplay) Volume Slider for FAD

### ISSUE THREAD

**Issue by ScottyHoover** [khanhas/spicetify-cli#1341]
## 📝 Provide a description of the new feature
_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Volume slier next to controls so you don't have to exit FAD when you want to change the volume.

If you'd like to see this feature implemented, add a 👍 reaction to this post.
ima cry if khanhas responds nah :(

**Comment by khanhas** [comment]
Ctrl Up/Down
