### ISSUE TITLE
[Full App Display] Background doesn't blur at times

### ISSUE THREAD

**Issue by TheMayhem6328** [khanhas/spicetify-cli#1343]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: 2.8.3
- OS: Windows 11 Version 21H2 (OS Build 22000.348)
- Monitor Resolutions:
  - 1920 x 1080 x 32
  - 1680 x 1050 x 32

## 📝 Provide detailed reproduction steps (if any)

1. Load a track with a different album cover
2. Go fullscreen
3. Record result

### ✔️ Expected result

Background cover should stay blurred upon loading track with different album cover

### ❌ Actual result

Blur apparently is missing - to fix, one has to get out of fullscreen and get back in

## 📷 Screenshots
Upon loading fullscreen first time an album cover is loaded (blur missing):

![image](https://user-images.githubusercontent.com/56154436/144978986-8d01eb88-4c7a-4241-a0a9-7dd291e99b84.png)

After getting out of fullscreen and going back (blur restored):

![image](https://user-images.githubusercontent.com/56154436/144979048-6fbcf339-47c4-4fc4-be10-ac5de9a15fbf.png)

**Comment by frodo36** [comment]
This issue was already fixed, but you won't receive the fix with spicetify update. You need to copy the fullAppDisplay.js from the repo into your extensions folder and apply

**Comment by TheMayhem6328** [comment]
> This issue was already fixed, but you won't receive the fix with spicetify upgrade. You need to copy the fullAppDisplay.js from the repo into your extensions folder and apply

Thanks for clarifying, and sorry for not trying that out first😅

**Comment by frodo36** [comment]
its fine, glad i could help

**Comment by TheGeeKing** [comment]
> Thanks for clarifying, and sorry for not trying that out first😅

It's not an issue really on your side but spicetify side. 

As I said in #1303, @khanhas upgrade command is not perfect and improvements should be made from my point of view. I will test more deeply limitation of upgrade command and update the close issue with what I find.

**Comment by khanhas** [comment]
@TheGeeKing fad and lyrics-plus fixes aren't released yet. Their commit were only pushed to repo. Upgrade command pulls latest release, not latest commit.
