### ISSUE TITLE
C:\Users\DragonrealmDR\.spicetify\Backup\settings.spa this file is missing

### ISSUE THREAD

**Issue by Shefer6713** [khanhas/spicetify-cli#1347]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: https://pastebin.com/qYLUFYig

## 📝 Provide detailed reproduction steps (if any)

1. https://raw.githubusercontent.com/khanhas/spicetify-cli/master/Extensions/webnowplaying.js save this to my downloads folder as a      js file
2. https://pastebin.com/qYLUFYig cop this raw paste data
3. run powershell as admin and right click, It downloads spicrtify and stuff
4. wait until the pop-up and then drag the javascript from step 1 to the extensions directory then hit 'Ok' on the pop up 

### ✔️ Expected result

_What is the expected result of the above steps?_
![Screenshot 2021-12-07 203936](https://user-images.githubusercontent.com/83560787/145079341-9a45b1ec-a65d-4c96-a643-4a3f508ad1a7.png)

### ❌ Actual result

_What is the actual result of the above steps?_
![Screenshot 2021-12-07 204012](https://user-images.githubusercontent.com/83560787/145079398-bf615409-b02c-4889-b291-4a4c278100ae.png)

settings.spa is missing, I have tried reinstalling spotify but still didn't work

**Comment by SupLiCatinG** [comment]
Your spicetify version is too old for 1.1.73 Spotify version. Just delete spicetify files from user folder (.spicetfiy and spicetify-cli) and re download again.

**Comment by Shefer6713** [comment]
> Your spicetify version is too old for 1.1.73 Spotify version. Just delete spicetify files from user folder (.spicetfiy and spicetify-cli) and re download again.

Can I please have a link to newer version of Spicetify?

**Comment by SupLiCatinG** [comment]
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
 paste it to powershell
