### ISSUE TITLE
(lyricsPlus) Text feedback when no available lyrics for song

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1348]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Spotify's lyric solution has this feature

![image](https://user-images.githubusercontent.com/94017480/145093036-7b92a402-904e-4864-8ea5-002a46942557.png)

And while popUpLyrics can show Instrumental tag for song why LyricsPlus cant do this ? 

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
It already showed sad face. What kind of cue you need other than that to know it doesn't have lyrics.
