### ISSUE TITLE
.config/spicetify/Backup: no such file or directory

### ISSUE THREAD

**Issue by hsspratt** [khanhas/spicetify-cli#1353]
## ℹ Computer information

- Spotify version: Spotify for macOS (Intel) - 1.1.74.631.g0b24d9ad
- Spicetify version: spicetify v2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Download Spotify 
2. Install spicetify - curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
3. Run spicetify
4. Run spicetify backup apply enable-devtool

### ✔️ Expected result

Spicetify updates Spotify

### ❌ Actual result

- Nothing changes 
- Why does this occur: /Users/harold/.config/spicetify/Backup: no such file or directory
- Should the file be automatically generated?

## 📷 Screenshots

<img width="1135" alt="Screenshot 2021-12-09 at 13 52 19" src="https://user-images.githubusercontent.com/42693405/145409027-75a7e241-7c29-449e-8fae-710a6d1f2a87.png">
<img width="698" alt="Screenshot 2021-12-09 at 13 48 27" src="https://user-images.githubusercontent.com/42693405/145409030-c788e16d-64d3-4399-be74-4b2733c85e71.png">

**Comment by SupLiCatinG** [comment]
✔️ Expected result
Spicetify updates Spotify

just try spicetify upgrade command

**Comment by hsspratt** [comment]
I followed your steps rigorously I think but the same error pops up

<img width="694" alt="Screenshot 2021-12-09 at 14 35 28" src="https://user-images.githubusercontent.com/42693405/145416057-1ec20b46-5a79-4c97-8301-63e761389a01.png">

**Comment by hsspratt** [comment]
Is it possible to manually create that file?

**Comment by SupLiCatinG** [comment]
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/harold/Library/Application Support/Spotify/prefs
change it in config-xpui.ini

**Comment by hsspratt** [comment]
Sorry if this is a simple question but where config-xpui.ini found, I can't find it in .config or .spicetify

**Comment by SupLiCatinG** [comment]
> Sorry if this is a simple question but where config-xpui.ini found, I can't find it in .config or .spicetify

you can find in with typing spicetify --config

**Comment by SupLiCatinG** [comment]
Maybe you are having problem with network download 2.8.3 from releases page for Intel Mac darwin amd64
extract into /Users/harold/.spicetify if you doesnt have .spicetify folder just create it

**Comment by hsspratt** [comment]
Ah perfect! Thats fixed it, just had to make the folder myself and all sorted now. Thats much appreciated, spent ages trying to fix it.
