### ISSUE TITLE
theme works, but extensions dont work

### ISSUE THREAD

**Issue by MythicScythe** [khanhas/spicetify-cli#1358]
## ℹ Computer information

- Spotify version: 
latest
- Spicetify version: 
latest

## 📝 Provide detailed reproduction steps (if any)

1. tried to restore backup
2. tried to reinstall spotify and spicetify

### ✔️ Expected result

extensions to work

### ❌ Actual result

not working

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/80054101/145615018-b1d3027c-90cd-40bd-ba18-cc068bd9c110.png)

**Comment by TheGeeKing** [comment]
We can't help with latest as info. Be more precise.

**Comment by MythicScythe** [comment]
> We can't help with latest as info. Be more precise.

Spotify for Windows
1.1.74.631.g0b24d9ad

Spicetify
2.8.3

**Comment by DM1-5** [comment]
Hi! I have the same problem, so meanwhile, the devs solve it, I [Downgraded](https://www.youtube.com/watch?v=lPUFzDes_Eg) The extensions work well on 1.1.72.439.gc253025e

**Comment by MythicScythe** [comment]
> Hi! I have the same problem, so meanwhile, the devs solve it, I [Downgraded](https://www.youtube.com/watch?v=lPUFzDes_Eg) The extensions work well on 1.1.72.439.gc253025e

hello, just downgraded, now i just get a blank screen 
![image](https://user-images.githubusercontent.com/80054101/145653436-2f9cb04e-8db0-42c3-82df-7705600585aa.png)

**Comment by Ddangkri** [comment]
Did you reinstall spicetify? Run command `spicetify update` and `spicetify upgrade` in powershell (Administrator mode) and if it doesn't works, reinstall spicetify. There is `Err` message in the command line, which means spicetify is broken and has to be updated.

**Comment by MythicScythe** [comment]
> Did you reinstall spicetify? Run command `spicetify update` and `spicetify upgrade` in powershell (Administrator mode) and if it doesn't works, reinstall spicetify. There is `Err` message in the command line, which means spicetify is broken and has to be updated. Maybe similar with #1356

done spicetify update got this:
spicetify v2.8.3
Err
fatal open C:\Users\USER\AppData\Roaming\Spotify\Apps\xpui\colors.css: The system cannot find the path specified.
upgrade says latest update

**Comment by TheGeeKing** [comment]
@MythicScythe with spicetify 2.8.3, you should use spotify 1.1.73. I recommend you to downgrade to that version and block updates:
``` in cmd
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R
```

**Comment by SupLiCatinG** [comment]
Anyone have 1.1.73 for mac ?

**Comment by MythicScythe** [comment]
> @MythicScythe with spicetify 2.8.3, you should use spotify 1.1.73. I recommend you to downgrade to that version and block updates (in cmd):
> 
> ```
> del %localappdata%\Spotify\Update
> 
> mkdir %localappdata%\Spotify\Update
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":D
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":R
> ```

Thank you this worked.

**Comment by TheGeeKing** [comment]
@MythicScythe please close this issue as it is a duplicate of #1344

**Comment by SupLiCatinG** [comment]
This issue was fixed with latest css-map as you can see extensions and custom apps working again
![image](https://user-images.githubusercontent.com/94017480/145873247-5bdcd0f8-92c6-4916-b5c3-d46a28be1673.png)

![image](https://user-images.githubusercontent.com/94017480/145873097-586efff1-2373-49da-96f4-2fbe0cf4d9f6.png)

**Comment by SupLiCatinG** [comment]
Even enchance playlists feauture in experimental features tab works with 1.1.74
Before 1.1.74 that was not possible

![image](https://user-images.githubusercontent.com/94017480/145874317-69538445-d465-4d9f-ae41-aec4ada03fea.png)
