### ISSUE TITLE
Cant use extensions

### ISSUE THREAD

**Issue by Dschogo** [khanhas/spicetify-cli#136]
Extensions are loading, but no controls to enable or use them.

Loaded: -for example th djmode extension
![image](https://user-images.githubusercontent.com/36862419/73498874-d420fb80-43be-11ea-981e-5892907abf7e.png)

But no buttons are added to the dropdown. (also for shuffle+ etc)
![image](https://user-images.githubusercontent.com/36862419/73498954-0df20200-43bf-11ea-90a4-5a167d521f04.png)

Did i forget something? (tried it a few times, including restalling spotify and spicetify as mentiont in the Readme)

**Comment by luis815** [comment]
From what I understand, you have to register the file you want to use.  On the terminal, something along the line of:

```
spicetify config extensions djMode.js
```

**Comment by Dschogo** [comment]
Dont think so... your command just writes the config entry (like me but just in notepad).

![image](https://user-images.githubusercontent.com/36862419/73518806-909ab180-43ff-11ea-9a3e-c7525e30da65.png)

Tried and doesn't work better.

**Comment by angelo799** [comment]
Same issue. Trash bin extension is not working either

**Comment by ShadyThGod** [comment]
It probably has something to do with the new Spotify update.
I think there are a few reasons as to why this might be happening:
- Spotify changed how the menu works completely

or more likely,
- Spotify changed some names of elements causing issues with registering a new menu button.

**Comment by Dschogo** [comment]
Maybe. Tried using extension 2 months ago and they didn't worked. Though about Update issues and waited. If thats the problem. Maybe i have jsut an extreme unlucky timing.

**Comment by khanhas** [comment]
There was some changes in zlink app source and it ruined my exposed API injection.
Currently investigating...

**Comment by Dschogo** [comment]
All right good to know. Is there any ETA?

**Comment by ShadyThGod** [comment]
@khanhas I'll be happy to help if you can let me know where the code for said API injection is located. I'll test some stuff out.

**Comment by khanhas** [comment]
Fixed in v0.9.7

**Comment by ShadyThGod** [comment]
Still not working for me

**Comment by khanhas** [comment]
@ShadyThGod Run `spicetify restore backup apply`

**Comment by ShadyThGod** [comment]
@khanhas Okay, it's working now. Didn't know the `restore` command was necessary. I ran it with just `backup apply` and it didn't work then. Thanks!
