### ISSUE TITLE
Spotify keeps updating itself

### ISSUE THREAD

**Issue by disc0nct** [khanhas/spicetify-cli#1363]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

The "disable_upgrade_check = 1" in "config-xpui.ini" doesn't work apparently because I always get Spotify updated!

### ✔️ Expected result

Spotify doesn't upgrade itself automatically.

### ❌ Actual result

It upgrades itself once there is a new update!

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/17936240/145670429-ed4f4967-7cd3-4990-a359-c467f64bdfba.png)

**Comment by huhridge** [comment]
That's not for Spotify, its for spicetify upgrade check

**Comment by disc0nct** [comment]
@huhridge  you re right!
