### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Jaime-06** [khanhas/spicetify-cli#1365]
## ℹ Computer information

- Spotify version: 1.1.74.631.g0b24d9ad
- Spicetify version: v2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Just opening Spotify with Spicetify applied

### ✔️ Expected result

Spotify working

### ❌ Actual result

Spotify not loading and popping up a "something went wrong" message

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/63646743/145676711-3e130fcd-df25-452d-a3e5-91bce5b06a1e.png)

**Comment by Delta18-Git** [comment]
I think this is a new update that has to be fixed.

**Comment by lemonnuggets** [comment]
see issue #1344

**Comment by TheGeeKing** [comment]
Duplicate of #1344. Please close this issue. @khanhas @itsmeow

**Comment by Jaime-06** [comment]
didn't realize there was already an issue open, sorry!
