### ISSUE TITLE
Bookmark extension - Back up bookmarks

### ISSUE THREAD

**Issue by grastraa** [khanhas/spicetify-cli#1367]
An import/export feature to restore bookmark list when a full wipe of spotify is required.

**Comment by TheGeeKing** [comment]
Data are stored at AppData\Local\Spotify\Browser\. I guess it is in \Local Storage folder. At the moment, you can save this folder somewhere and paste it when update is done.

**Comment by p1usminus** [comment]
I had been backing up the ..\Browser\Local Storage folder following the tip in the post above...

but I have just updated my Spotify version, restored my backup, and found that some of my recent bookmarks are missing! It appears my backup is several months old, that is, Spotify has not changed the files in these folders in many months (though I have definitely added bookmarks recently!)

I believe the folder that is now used is AppData\Local\Spotify\**Default**\Local Storage\leveldb

**Comment by ohitstom** [comment]
this folder is likely to change between cef versions, have a quick Google before backing up next time to make sure it's the right path!

you can check your cef version in the about Spotify section

**Comment by p1usminus** [comment]
> this folder is likely to change between cef versions, have a quick Google before backing up next time to make sure it's the right path!
> 
> you can check your cef version in the about Spotify section

This would be a prudent step, but I have not found any useful release notes or changelogs or commits for CEF that I could use to find out about a change like this. There has been [one other person](https://magpcss.org/ceforum/viewtopic.php?f=6&t=20047) who has commented about the same change in folders.

I can only hope it stays the same for a while 😅
