### ISSUE TITLE
Bookmark extension - button does not appear

### ISSUE THREAD

**Issue by andreyuv** [khanhas/spicetify-cli#137]
Hi,

The bookmark extension doesn't seem to be working for me anymore.
Before there was a bookmark button near the search bar, but it's not there anymore:

![image](https://user-images.githubusercontent.com/20476201/73947442-1f2b9900-4900-11ea-9da6-87adc1efb6ba.png)

The app still appears in the left side menu:

![image](https://user-images.githubusercontent.com/20476201/73948989-703c8c80-4902-11ea-8eaa-cb76e43b0e35.png)

I am able to see my past saved bookmarks, as well as delete them. I just can't save any new ones.

I did a short superficial debugging and it seems the extension fails because Spicetify.LocalStorage doesn't exist. It never exists this loop:

```
    if (!Spicetify.LocalStorage) {  
        setTimeout(Bookmark, 1000);  
        return;  
    }

```

I don't know enough to fix it, so I was hoping somebody could help me out. Is this a known issue?

**Comment by khanhas** [comment]
Upgrade Spicetify to v0.9.8
Then run
```
spicetify restore backup apply
```

**Comment by andreyuv** [comment]
Thank you for your help, that fixed it.
