### ISSUE TITLE
Full App Display background disappears

### ISSUE THREAD

**Issue by rickstienstra** [khanhas/spicetify-cli#1371]
## ℹ Computer information

- Windows 11 Pro
- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. FullAppDisplay with settings:
- Enable progress bar
- Trim title
- Enable Fullscreen
- Enable song change animation

Opening FAD on second 4k monitor
Sometimes when opening FAD there is no background. This also happens when the next song comes up. Makes no difference with the fullscreen check on or off.

### ✔️ Expected result

Normal blurred album art as background

![2021-12-14_12-12-55_Spotify](https://user-images.githubusercontent.com/38384114/145987899-74dd0c03-0565-4347-9d6f-c4c2c6af9ac9.png)

### ❌ Actual result

No background image

![2021-12-14_12-10-53_Spotify](https://user-images.githubusercontent.com/38384114/145987952-b3c43fcf-7cbe-44f7-9303-4e210c281e50.png)

**Comment by frodo36** [comment]
What version of spicetify are you using?

**Comment by rickstienstra** [comment]
Listed in main issue; Spicetify version: 2.8.3

**Comment by huhridge** [comment]
can you check console for any errors?

**Comment by rickstienstra** [comment]
Following is the output of "Spotify.exe --show-console" when opening FullAppDisplay with a non blurry background, switching to the next song and transitions to a blurry background.

> 19:35:15.847 D [/connect:116                    ] active device is local device
19:35:15.847 D [/connect:266                    ] ConnectState::updateCluster: didUpdateCluster 1. Cluster timestamp 1639510517808
19:35:15.855 I [/f:477                          ] Request for file b790049a22dbc2526f4736be9807ce0be90444f8 complete (code: success (0))
19:35:15.855 I [/f:225                          ] Requesting data (2097152 -> 2621440)
19:35:15.905 I [/f:477                          ] Request for file b790049a22dbc2526f4736be9807ce0be90444f8 complete (code: success (0))
19:35:15.905 I [/f:225                          ] Requesting data (2621440 -> 3058456)
19:35:15.944 I [/f:477                          ] Request for file b790049a22dbc2526f4736be9807ce0be90444f8 complete (code: success (0))
19:35:18.008 I [/f:79                           ] CosmosContainsRequest: created(0), reply(0)
19:35:20.442 I [/f:181                          ] Prefetch: start prefetching track  spotify:track:75UvJXVZZKA6lMSupSf46d : e444ebfeaeaffc36cac3b5441efb0669d9666644
19:35:20.481 I [/f:225                          ] Requesting data (0 -> 10485760)
19:35:20.592 I [/f:33                           ] Prefetch: key prefetched for track: spotify:track:75UvJXVZZKA6lMSupSf46d (file: e444ebfeaeaffc36cac3b5441efb0669d9666644)
19:35:20.644 I [/f:430                          ] High request latency: https://audio-fa.scdn.co/audio took 162 ms
19:35:22.375 I [/f:186                          ] mdata: 46b4d77f: Task from `playlist` finished. 46/51 entity URIs requested/needed (9.8% cached). 46/51 extensions requested/needed (0.0% w/ ETags, 9.8% cached). 0 unfinished task(s).
19:35:24.927 I [/f:205                          ] ConcurrentCollector ran mark cycle for 16.002ms, total: 64.999ms.
19:35:27.014 I [/f:591                          ] aq: LWS got LWS_CALLBACK_CLIENT_WRITEABLE
19:35:27.036 I [/f:591                          ] aq: LWS got LWS_CALLBACK_CLIENT_RECEIVE_PONG
19:35:27.036 I [/f:591                          ] aq: LWS got LWS_CALLBACK_CLIENT_WRITEABLE
19:35:28.142 D [/connect:116                    ] active device is local device
19:35:28.154 I [/f:676                          ] Close track (playback_id d023359ca51f962ff68ba8f89e7415be)
19:35:28.155 I [/f:677                          ]     source_end: playlist
19:35:28.155 I [/f:678                          ]     reason_end: fwdbtn
19:35:28.156 I [/f:679                          ]     resumable_session: false
19:35:28.157 I [/f:62                           ] Saved 1 log messages to 'C:\Users\RMSti\AppData\Roaming\Spotify\Users\itzrickk_-user\log-tracked'
19:35:28.158 I [/f:461                          ] Playing music set to 'false'
19:35:28.158 I [/f:187                          ] Scheduling emission of signal.
19:35:28.159 I [/f:614                          ] Open playback of track (playback_id 0f7006d0b7e83a2e3060a2370470faa4, parent_playback_id 00000000000000000000000000000000)
19:35:28.162 I [/f:279                          ]     Creating track player for track (playback_id 0f7006d0b7e83a2e3060a2370470faa4)
19:35:28.163 I [/f:281                          ]         track_uri: spotify:track:75UvJXVZZKA6lMSupSf46d
19:35:28.163 I [/f:282                          ]         speed: 1.000000
19:35:28.164 I [/f:283                          ]         normalization: track
19:35:28.165 I [/f:284                          ]         stream_type: default
19:35:28.165 I [/f:285                          ]         urgency: now
19:35:28.165 I [/f:286                          ]         track_select_flag: 0
19:35:28.166 I [/f:465                          ] Metadata extensions cache hit
19:35:28.167 I [/f:96                           ] karaoke: Disabled
19:35:28.170 I [/f:313                          ]     Open track player (playback_id 0f7006d0b7e83a2e3060a2370470faa4)
19:35:28.170 I [/f:314                          ]         position: 0 ms
19:35:28.171 I [/f:315                          ]         paused: false
19:35:28.171 I [/f:407                          ] track gain: (-10.1623Db), track peak: (1.0042dB), album gain: (-10.1623dB), album peak: (1.0135dB), normalization: trackgain
19:35:28.171 I [/f:316                          ]         transition: none
19:35:28.172 I [/f:300                          ] Opening sink for playback.
19:35:28.173 I [/f:301                          ]     codec: vorbis
19:35:28.173 I [/f:302                          ]     bitrate: 160000 bits/s
19:35:28.173 I [/f:303                          ]     sample rate: 44100 Hz
19:35:28.174 I [/f:304                          ]     channels: 2
19:35:28.174 I [/f:305                          ]     sample format: 32-bit-float-pcm
19:35:28.177 I [/f:308                          ]     duration: 135227 ms
19:35:28.179 I [/f:399                          ] Entry (137F4298) is buffering
19:35:28.179 I [/f:364                          ] Created entry (137F4298) for player in AudioPlayerQueue
19:35:28.179 I [/f:365                          ]     stream type: default
19:35:28.180 I [/f:611                          ] Starting playback.
19:35:28.180 I [/f:366                          ]     paused: false
19:35:28.180 I [/f:613                          ]     min limit 4000 ms.
19:35:28.181 I [/f:367                          ]     transition: none
19:35:28.181 I [/f:614                          ]     compressed buffer: 71639 bytes
19:35:28.182 I [/f:368                          ]     fade in start: -1 ms
19:35:28.183 I [/f:616                          ]     decompressed buffer: 0 ms
19:35:28.183 I [/f:369                          ]     fade in duration: -1 ms
19:35:28.185 I [/f:370                          ]     fade out start: -1 ms
19:35:28.184 I [/f:618                          ]     sink buffer: 1021 ms
19:35:28.185 I [/f:371                          ]     fade out duration: -1 ms
19:35:28.185 I [/f:619                          ]     final source buffer: false
19:35:28.187 I [/f:399                          ] Entry (137F4298) is not buffering
19:35:28.188 I [/f:461                          ] Playing music set to 'true'
19:35:28.188 I [/f:187                          ] Scheduling emission of signal.
19:35:28.192 D [/connect:116                    ] active device is local device
19:35:28.208 I [/f:246                          ] Prefetch: looks like a skip or partial context change - halving window size to 1
19:35:28.212 I [/f:163                          ] Emitting signal.
19:35:28.214 D [/connect:116                    ] active device is local device
19:35:28.229 D [/connect:116                    ] active device is local device
19:35:28.244 D [/connect:116                    ] active device is local device
19:35:28.257 I [/f:163                          ] Emitting signal.
19:35:28.259 I [/f:186                          ] mdata: 63ec76de: Task from `recently_played` finished. 0/26 entity URIs requested/needed (100.0% cached). 0/26 extensions requested/needed (0.0% w/ ETags, 100.0% cached). 2 unfinished task(s).
19:35:28.261 I [/f:186                          ] mdata: 12eef701: Task from `recently_played` finished. 0/1 entity URIs requested/needed (100.0% cached). 0/1 extensions requested/needed (0.0% w/ ETags, 100.0% cached). 1 unfinished task(s).
19:35:28.264 D [/connect:116                    ] active device is local device
19:35:28.266 D [/connect:116                    ] active device is local device
19:35:28.272 D [/connect:116                    ] active device is local device
19:35:28.277 D [/connect:116                    ] active device is local device
19:35:28.279 I [/f:186                          ] mdata: dc3de97: Task from `unknown` finished. 0/0 entity URIs requested/needed (0.0% cached). 0/0 extensions requested/needed (0.0% w/ ETags, 0.0% cached). 0 unfinished task(s).`

**Comment by rickvandijck** [comment]
I found a workaround until this gets fixed. 
When the background disappears, go back one song.
For me it keeps working after doing that

**Comment by huhridge** [comment]
are there any errors in the developer's tools console? it seems like a problem with the canvas

**Comment by Lasermasterluke** [comment]
also had the same issue occur on a friend's w11 machine

**Comment by rickstienstra** [comment]
Also happens at a friend's Windows 10 machine, exact same Spicetify and Spotify version. Let me know if I can provide any kind of log!

**Comment by rickstienstra** [comment]
Tried testing a bit more. Can't find anything in the CSS in DevTools that creates this issue. It only seems to happen now when skipping a song for the first time after activating FAD. The next song won't have a blurred background anymore.

**Comment by mayurankv** [comment]
This is still an issue for me!
