### ISSUE TITLE
Lyrics-Plus prioritizing synced lyrics of providers that has unsynced lyrics even when they don't have synced lyrics

### ISSUE THREAD

**Issue by Ballasi** [khanhas/spicetify-cli#1374]
## ℹ Computer information

- Spotify version: 1.1.72.439-3
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Play the song _Alone In My Mind (For Mannington Bowes)_ by _Eaves_ with Spotify as main lyrics provider and Musixmatch as secondary lyrics provider.
2. Go to lyrics and the Synced tab, see that there are no lyrics
3. Disable Spotify as a lyrics provider, reboot Spotify
4. Go to lyrics and the Synced tab, see that synced lyrics are available

### ✔️ Expected result

_What is the expected result of the above steps?_

Synced lyrics should appear in both cases.
Since it's unavailable for Spotify, it should fallback to Musixmatch automatically, but does not since there are unsynced lyrics on Spotify.
The issue will probably be solved automatically for the given song when Spotify automatically scraps the new information from Musixmatch's database, but if synced lyrics are unavailable for a provider, it should check automatically with the next providers.

### ❌ Actual result

_What is the actual result of the above steps?_

When a provider has unsynced lyrics of a song but does not have a synced lyrics of this song, it should check with other providers if they have synced lyrics.

## 📷 Screenshots

_Are there any useful screenshots?_

With Spotify enabled:
![image](https://user-images.githubusercontent.com/1565959/146448692-6d8c0eeb-2f0a-45c5-b024-fe433a0ab497.png)

Without Spotify enabled:
![image](https://user-images.githubusercontent.com/1565959/146448698-81d25e3d-ca7d-4fde-ab64-c5b931e99d6c.png)

**Comment by Ddangkri** [comment]
You'll see little buttle on the side of "Synced" button. That means you are now prioritizing synced lyrics rather than others. Try dubble-clicking that button and the little circle will disappear. Then you'll get what you want.

**Comment by Ballasi** [comment]
> You'll see little buttle on the side of "Synced" button. That means you are now prioritizing synced lyrics rather than others. Try dubble-clicking that button and the little circle will disappear. Then you'll get what you want.

This isn't what I was pointing out. I'm talking about the priorities on providers, not on the type of lyrics you want to get.
If your top provider has unsynced lyrics but does not have synced lyrics, it will not check with your next providers if they have synced lyrics. Therefore the result I have on the screenshots. I tried to make it clear but it's a bit hard to put it into words.

**Comment by Ddangkri** [comment]
Oh I see. Sry for missing the point.
