### ISSUE TITLE
Custom extensions in .spicetify/Extensions folder are not working

### ISSUE THREAD

**Issue by francescoaracu** [khanhas/spicetify-cli#1378]
## ℹ Computer information

- Spotify version: 1.1.74.631.g0b24d9ad
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Copy some custom extensions into `.spicetify/Extensions` folder
2. Add them to config via `spicetify config extensions <filename>`
3. Run `spicetify apply`

### ✔️ Expected result

Extensions are loaded and work correctly.

### ❌ Actual result

The only extensions that are actually working are the ones packaged with Spicetify (eg. loopyLoop). Custom theme is working.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/48188510/146676343-28a02076-9914-41c5-adbc-21d16ab3bf5a.png)
![image](https://user-images.githubusercontent.com/48188510/146676352-4bef1c79-7819-417e-9a79-5feaf550ecec.png)

**Comment by khanhas** [comment]
Run `spicetify path -e` to see if it actually recognises your extensions paths correctly

**Comment by francescoaracu** [comment]
> Run `spicetify path -e` to see if it actually recognises your extensions paths correctly
Yes, it seems that path is recognised.
![image](https://user-images.githubusercontent.com/48188510/146678158-bbf9ed9c-89e9-468f-961f-656fa9ec29e6.png)

**Comment by khanhas** [comment]
Well sorry then, I can't see any reason it wouldn't work.
I can confirm they work fine on mine.
Console log might shed some light

**Comment by francescoaracu** [comment]
Console says "unexpected token" for all of them 4.
![image](https://user-images.githubusercontent.com/48188510/146681158-7ea1a824-58cd-48f6-b268-7b56377f445d.png)

**Comment by khanhas** [comment]
You better check their contents then, fix the syntax error and run `spicetify apply`

**Comment by francescoaracu** [comment]
Ok, fixed it! I downloaded them in a wrong way from GitHub, now it's all good! Thx a lot
