### ISSUE TITLE
FAD Lyrics pushing album details out of view

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#1380]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.74.631.g0b24d9ad
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. Enable FAD
2. Enable Lyrics Plus integration

### ✔️ Expected result

The album info should be on the screen no matter what the lyrics do.

### ❌ Actual result

https://user-images.githubusercontent.com/63046776/146684475-a3ef9500-2251-4b2c-ab5a-0de10fbd751c.mp4

Pressing `Ctrl+Tab` makes lyrics disappear and `Ctrl+Shift+Tab` brings them back. I guess it must have something to do with the fact that the Keyboard Shortcuts uses `Ctrl+Tab` to switch from the Lyrics Plus custom app.

**Comment by afonsojramos** [comment]
Another FAD issue @CharlieS1103 :eyes:

**Comment by lemonnuggets** [comment]
The issue seems to have resolved itself with the new update so I will go ahead and close this issue now.

**Comment by CharlieS1103** [comment]
@afonsojramos Haha, seems like it worked :)
