### ISSUE TITLE
--left-sidebar-width and --right-sidebar-width set as 'NaNpx'

### ISSUE THREAD

**Issue by oeed** [khanhas/spicetify-cli#139]
I'm not sure if this is a Spotify bug or Spicetify bug, so sorry if it's unrelated.

For some readon --left-sidebar-width and --right-sidebar-width are being overridden and set to 'NaNpx', which usually suggests that there's a divide by zero or similar operation. It was fine about a week or two ago.

<img width="441" alt="Screen Shot 2020-02-18 at 5 30 25 PM" src="https://user-images.githubusercontent.com/3835991/74704470-69543900-5275-11ea-84b1-e824719e1026.png">

**Comment by khanhas** [comment]
Spotify version?

**Comment by oeed** [comment]
1.1.26.501.gbe11e53b on macOS 10.15.2.

Sorry I didn't think to try clearing Spicetify and checking - it is indeed a Spotify issue, not Spicetify.
