### ISSUE TITLE
After Spotify Player Update, Spicetify Doesn't Work When Custom Apps Are Used 

### ISSUE THREAD

**Issue by DawnAura** [khanhas/spicetify-cli#1392]
So, my spotify just got auto-updated to the latest version, Spotify for Windows 1.1.76.447.g11f432d8, and now when I turned on Spotify after the update, my Spicetify theme wasn't loaded. So, I tried to re-apply the theme, but, when I had any custom app loaded, the error,
PS C:\Windows\system32> spicetify apply
spicetify v2.8.3
Err
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc000776000, 0x1758bd, 0x1758bd, 0xc000776000)
        D:/Code/spicetify-cli/src/apply/apply.go:220 +0xd8f
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0003b4080, 0x3d, 0xc000417910)
        D:/Code/spicetify-cli/src/utils/utils.go:191 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0003b4080, 0x3d, 0xc0001d0000, 0x7, 0x8, 0xc000196060, 0x1, 0x2, 0x10101, 0xc000010b11, ...)
        D:/Code/spicetify-cli/src/apply/apply.go:188 +0xc5
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000a9f0, 0x30, 0xc0001d0000, 0x7, 0x8, 0xc000196060, 0x1, 0x2, 0x10101, 0xc000010b11, ...)
        D:/Code/spicetify-cli/src/apply/apply.go:37 +0x57d
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x1328c34, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:72 +0x68c
main.main()
        D:/Code/spicetify-cli/spicetify.go:194 +0x4f9
        occurs. But, if I run spotify without any custom apps, the client works just fine. Is it just me having this issue, or are other people facing similar/the same issue?
![image](https://user-images.githubusercontent.com/89002405/148241582-63332ebf-7bb4-46a1-b056-f18704ab6a6c.png)

**Comment by CharlieS1103** [comment]
Hooks are broken again unfortunately, I don't really know how to update them but will ask around

**Comment by HerrKnarz** [comment]
I have the same issue! Is there a work around other than reverting to an older version of spotify? It's very annoying that spotify doesn't have an option to disable automatic updates and apply them manually...

**Comment by CharlieS1103** [comment]
@HerrKnarz I patched it recently, just need to wait for a new release

**Comment by xerta555** [comment]
> @HerrKnarz I patched it recently, just need to wait for a new release

For me also on Spotify 1.1.76.447, wait for the next update, but apparently it works without custom MOD.

**Comment by afonsojramos** [comment]
This should have been fixed, will close now.

**Comment by xerta555** [comment]
> This should have been fixed, will close now.

With this commit?
https://github.com/khanhas/spicetify-cli/commit/f9efada85def6919d67b03e4cb8db2a50b1349bc

**Comment by afonsojramos** [comment]
Yes, can you just `spicetify upgrade` and then `spicetify restore backup apply`?

**Comment by xerta555** [comment]
> Yes, can you just `spicetify upgrade` and then `spicetify restore backup apply`?

I had updated Spotify even before the last Spotify update and it didn't prevent me from getting the error about custom apps that i don't use, so i don't have a problem with it either.
