### ISSUE TITLE
Keyboard extension error

### ISSUE THREAD

**Issue by noxan-dev** [khanhas/spicetify-cli#1397]
## ℹ Computer information

- Spotify version: 1.7.4
- Spicetify version: 2.8.4

## 📝 Provide detailed reproduction steps (if any)

1. Run PowerShell to install Keyboard shortcut
2. See an error
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
Keyboard shortcut to be installed
### ❌ Actual result

_What is the actual result of the above steps?_
Extention errors out
## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/59417659/148695311-30ce0a8f-bba6-48c9-a678-319a1ddca7b6.png)

**Comment by ajiou** [comment]
Does the js file exist in the spicetify-cli/extensions directory?
Like this:
![image](https://user-images.githubusercontent.com/35028055/148695584-741f6978-453b-487c-8f7d-fc3299203178.png)

**Comment by noxan-dev** [comment]
yup. it exists in both the .spicetify and the cli. the check is looking for keybord, not keyboard. missing an a

**Comment by ajiou** [comment]
That looks like you have a typo in the last command:
![image](https://user-images.githubusercontent.com/35028055/148696160-ee06506b-095b-4cd5-8000-6863649700d6.png)

Just edit the .spicetify/config-xpui.ini and apply again

**Comment by noxan-dev** [comment]
🤷‍♀️ seems to have been applied. I didn't do anything but I sure won't be touching anything now.

**Comment by afonsojramos** [comment]
So, as I think this got solved, I'll close this issue.
