### ISSUE TITLE
Allow Themes to overwrite image assets

### ISSUE THREAD

**Issue by Chrissi2812** [khanhas/spicetify-cli#14]
As Example the Connect Image in the SpicetifyDefaultTheme has a Dark Background.

![image](https://user-images.githubusercontent.com/6141652/57071030-79485f80-6cd9-11e9-8dfb-a833c76c1c44.png)

You can however achiev this already by manually copying the image from `Extracted/Raw/zlink/images/connect_devices.svg` to `Extracted/Themed/zlink/images/connect_devices.svg` and make some changes to the colors and it will look like this:
![image](https://user-images.githubusercontent.com/6141652/57071216-0986a480-6cda-11e9-8d9d-5bda58d1c7aa.png)

So maybe allow themes to include override for apps, like this `Theme Folder / apps / zlink / images / spotify_connect.svg` to override that specific file.
And only allow images and css overrides 🤔

**Comment by khanhas** [comment]
Great idea.
I will add it this weekend

**Comment by PoorPocketsMcNewHold** [comment]
Same goes for the Friends activity list, and also for the UI parts when offline. 
![image](https://user-images.githubusercontent.com/13170204/57316634-88267c00-70f6-11e9-9279-3106649f9e0d.png)

**Comment by khanhas** [comment]
I added this feature in v0.8
Please check it out and tell me if it works correctly.

**Comment by PoorPocketsMcNewHold** [comment]
![image](https://user-images.githubusercontent.com/13170204/57568137-94a32100-73e3-11e9-9379-843543998bd4.png)
Still having those issue like I’ve reported.
Completely reinstalled fresh Spotify app, and the latest spicetify version correctly installed. Didn’t tested with my assets tho.

**Comment by khanhas** [comment]
Ah. I didnt make or edit any asset. Might do if I have time in the future.

**Comment by PoorPocketsMcNewHold** [comment]
Oh, sorry, I was confused if you´ve actually updated the theme, or just allowed to replace assets. I didn’t know what to test really.

**Comment by khanhas** [comment]
Yeah, the reply was meant for @Chrissi2812 to test if he can inject his own asset correctly?

**Comment by Chrissi2812** [comment]
Works perfectly, thanks @khanhas  🎉

 ![image](https://user-images.githubusercontent.com/6141652/57605013-ed9ac280-7565-11e9-82ad-f6cf4f287abd.png)
