### ISSUE TITLE
Not able to apply updates

### ISSUE THREAD

**Issue by edwardsaunders7** [khanhas/spicetify-cli#140]
Whenever I try to update or apply themes I get this error message

`spicetify apply
spicetify v0.9.7
Copying raw assets:
fatal unlinkat /opt/spotify/Apps/artist.spa: permission denied
`
`spicetify update
spicetify v0.9.7
fatal open /opt/spotify/Apps/zlink/css/user.css: no such file or directory
`

Using Manjaro KDE-Plasma - trying to apply spicetify-themes-git themes

**Comment by king-gizzard** [comment]
as manjaro is arch-based, this will probably apply to you:

> Spotify installed from AUR
> Before applying Spicetify, you need to gain write permission on Spotify files, by running command:
> sudo chmod 777 /opt/spotify -R

this is mentioned [here](https://github.com/khanhas/spicetify-cli/wiki/Installation), i had this issue as well until i stumbled upon this bit...
