### ISSUE TITLE
Simplifying FAD + Lyrics Plus

### ISSUE THREAD

**Issue by stpnwf** [khanhas/spicetify-cli#1400]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

I would expect FAD to replace the default Spotify display mode. Instead of having two extra buttons (FAD Projector and Lyrics Plus button), I would just like to see the FAD Projector button replace the expand button in the bottom right. Users should be able to click on the FAD button, and there have as an option three display modes: **1.** just FAD, **2.** FAD + Lyrics Plus integration, or **3.** just Lyrics Plus.

It would also be helpful to be able to choose different backgrounds to be displayed (album art or artist cover for modes 1. and 2., and Lyrics color or custom color for mode 3.)

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by afonsojramos** [comment]
@khanhas do you believe this is valid?

**Comment by huhridge** [comment]
> It would also be helpful to be able to choose different backgrounds to be displayed (album art or artist cover for modes 1. and 2., and Lyrics color or custom color for mode 3.)

if you want to display a colored background based on the album art, my [extension](https://github.com/huhridge/huh-spicetify-extensions/tree/main/fullAppDisplayModified), does that.
(It is a choice between blurred album art and color)
