### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by theofrgs** [khanhas/spicetify-cli#1404]
## ℹ Computer information

- System version:
  Distributor ID:	Ubuntu
  Description:	Ubuntu 20.04.3 LTS
  Release:	20.04
  Codename:	focal

## 📝 Provide detailed reproduction steps (if any)

1. Installation 
2. -> ╰─ curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh                         ─╯

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

  DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest
  curl: (22) The requested URL returned error: 403

## 📷 Screenshots

![Screenshot from 2022-01-12 16-05-45](https://user-images.githubusercontent.com/60193575/149166160-eccebce0-cb7a-4212-9045-d66c2fc5e50c.png)

**Comment by ririxidev** [comment]
HTTP error 403 - no access. Could be when github had some issues, but it should be fine.
![image](https://user-images.githubusercontent.com/9348108/149622810-938d52bb-04bb-4356-8442-cf850b5de60a.png)
Link from where it's downloading release works fine on my end. Try again and if it works, close this issue.
