### ISSUE TITLE
”warning Spotify version and backup version are mismatched.“; What should I do?

### ISSUE THREAD

**Issue by shanyan-wcx** [khanhas/spicetify-cli#1405]
spicetify backup apply
spicetify v2.8.4
Backing up app files:
OK
Extracting:
OK
Preprocessing:
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/utils.FetchLatestTag(0x1ece7070598, 0x30, 0xc000ed4060, 0x8)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/vcs.go:29 +0x1e6
github.com/khanhas/spicetify-cli/src/preprocess.FetchLatestTagMatchingOrMaster(0xad8cf4, 0x5, 0x2, 0xc0001822a0, 0x2e, 0x819345)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:544 +0x3b
github.com/khanhas/spicetify-cli/src/preprocess.Start(0xad8cf4, 0x5, 0xc00000a600, 0x29, 0x101010101)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:76 +0x12c
github.com/khanhas/spicetify-cli/src/cmd.Backup(0xad8cf4, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/backup.go:61 +0x845
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:188 +0x592

**Comment by shanyan-wcx** [comment]
spicetify update
spicetify v2.8.4
warning Spotify version and backup version are mismatched.
info Please run "spicetify backup apply".
Continue anyway? [y/N] y
fatal open C:\Users\shanyan\AppData\Roaming\Spotify\Apps\xpui\colors.css: The system cannot find the path specified.

**Comment by shanyan-wcx** [comment]
spicetify apply
spicetify v2.8.4
warning Spotify version and backup version are mismatched.
info Please run "spicetify backup apply".
Continue anyway? [y/N] y
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
Transferring custom apps:
OK
success Spotify is spiced up!
info Preprocessed Spotify data is outdated. Please run "spicetify restore backup apply" to receive new features and bug fixes
PS C:\Users\shanyan> spicetify restore backup apply
spicetify v2.8.4
warning Spotify version and backup version are mismatched.
Continue restoring anyway? [y/N] y
success Spotify is restored.
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/utils.FetchLatestTag(0x1b68fc50108, 0x30, 0xc000092690, 0x8)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/vcs.go:29 +0x1e6
github.com/khanhas/spicetify-cli/src/preprocess.FetchLatestTagMatchingOrMaster(0xad8cf4, 0x5, 0x2, 0xc0000a0210, 0x2e, 0x819345)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:544 +0x3b
github.com/khanhas/spicetify-cli/src/preprocess.Start(0xad8cf4, 0x5, 0xc00000a600, 0x29, 0x101010101)
        C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:76 +0x12c
github.com/khanhas/spicetify-cli/src/cmd.Backup(0xad8cf4, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/backup.go:61 +0x845
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:188 +0x592

**Comment by shanyan-wcx** [comment]
Can anyone answer my question?

**Comment by ririxidev** [comment]
There is no need to flood comments with all these commands. Remove spotify (%appdata% or %localappdata%) and remove spicetify-cli (~/.spicetify) and spicetify-cli folder then reinstall. From what it seems it's just issue from your end you probably installed spicetify wrongly

**Comment by shanyan-wcx** [comment]
Thank you. It works.

**Comment by H1roDarling** [comment]
I don't understand any of this, especially what "spicetify backup apply" is, I got the issue and I don't know whether "spicetify backup apply" is an app, a website, or anything. Please help.

**Comment by afonsojramos** [comment]
@H1roDarling it is a command `spicetify backup apply`, since Spicetify is a CLI (Command Line Interface). Please refer to https://spicetify.app/ if you have more doubts regarding the functioning of Spicetify.

**Comment by nadiahko** [comment]
> Thank you. It works.

i have the same troublem, can u teach me how to fix it?

**Comment by shanyan-wcx** [comment]
> > Thank you. It works.
> 
> i have the same troublem, can u teach me how to fix it?

Uninstall spotify and spotify completely, and then reinstall them.

**Comment by nadiahko** [comment]
> > > Thank you. It works.
> > 
> > 
> > i have the same troublem, can u teach me how to fix it?
> 
> Uninstall spotify and spotify completely, and then reinstall them.

still not working at all 😣

**Comment by zhooshi** [comment]
I'm very late, but this just happened to me. 

I didn't have to uninstall and reinstall Spotify. Instead, I restored backup copy I made of Spotify's contents, reloaded and the errors went away.

**Comment by NightRaven0** [comment]
> I'm very late, but this just happened to me.
> 
> I didn't have to uninstall and reinstall Spotify. Instead, I restored backup copy I made of Spotify's contents, reloaded and the errors went away.

can you elaborate on this? i have this issue now and i cant seem to fix it no matter what version i install or how many times i re-install

**Comment by cbxcvl** [comment]
here same problem
