### ISSUE TITLE
being able to change your country

### ISSUE THREAD

**Issue by gk98s** [khanhas/spicetify-cli#1407]
its kinda annoying to get forced to see the songs and playlists and podcasts that u dont like. and spotify doesnt let u change your country unless u have a premium account. is there a way to fake it so that u can change your country? if so itd be really nice to see that being added to spicetify

**Comment by amd64fox** [comment]
Most likely this is a server function and it is almost impossible to do this. You can try disabling ads and podcasts [here](https://github.com/amd64fox/SpotX).

**Comment by gk98s** [comment]
> Most likely this is a server function and it is almost impossible to do this. You can try disabling ads and podcasts [here](https://github.com/amd64fox/SpotX).

Thank u sooo much for that repository I finally got rid of these annoyingass podcasts
