### ISSUE TITLE
Panic error during preprocessing

### ISSUE THREAD

**Issue by 8k4** [khanhas/spicetify-cli#1409]
## ℹ Computer information

- Spotify version: 1.1.10.546
- Spicetify version: Latest using bash install script
- OS: Debian 11 Bullseye

## 📝 Provide detailed reproduction steps (if any)
1. Ran curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
2. After folder was created in my home folder, moved folder to ~/.spicetify-cli and added alias to .bashrc to run spicetify easily.
3. Ran spicetify backup enable-devtool which lead to error down below.
4. Ran sudo chmod a+wr /usr/share/spotify and sudo chmod a+wr /usr/share/spotify/Apps -R in attempt to correct any permissions errors. Did not result in success.

### ✔️ Expected result

Spotify would have backup made, hopefully spicetify would generate a config file. I was hoping to add the sleek theme from @morpheusthewhite but was unable to. 

### ❌ Actual result
Immediately after running spicetify backup apply dev-tool, I get panic error:

**spicetify v2.8.4
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6af8cf]

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/preprocess.Start.func1(0xc00018ba00, 0x31, 0x0, 0x0, 0x7b2540, 0xc000186900, 0xc00001e140, 0x4f)
	C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:93 +0x4f
path/filepath.Walk(0xc00018ba00, 0x31, 0xc00008dd30, 0x0, 0x0)
	C:/Program Files/Go/src/path/filepath/path.go:499 +0x7e
github.com/khanhas/spicetify-cli/src/preprocess.Start(0x7ac2ec, 0x5, 0xc00001c270, 0x2c, 0x101010101)
	C:/Users/Afonso/GitHub/spicetify-cli/src/preprocess/preprocess.go:92 +0x325
github.com/khanhas/spicetify-cli/src/cmd.Backup(0x7ac2ec, 0x5)
	C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/backup.go:61 +0x845
main.main()
	C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:188 +0x592**

**Comment by 8k4** [comment]
Problem resolved. Re-installed Spotify after autoremove purging every configuration file and restarting from scratch.

Thanks

**Comment by ririxidev** [comment]
Close this issue then.
