### ISSUE TITLE
error: not a directory

### ISSUE THREAD

**Issue by verajosemanuel** [khanhas/spicetify-cli#141]
installed from debian / ubuntu package

```
which spotify
/usr/bin/spotify

spicetify
config file created successfully
info Run "spicetify -h" for commands list.

spicetify -c
/home/jose/.config/spicetify/config.ini


 spicetify backup apply enable-devtool
spicetify v0.9.7
Backing up app files:
open /usr/bin/spotify/Apps: not a directory
```

**Comment by khanhas** [comment]
What are files' permissions in `/usr/bin/spotify`?

**Comment by verajosemanuel** [comment]
lrwxrwxrwx 1 root root 24 feb  4 00:19 /usr/bin/spotify -> ../share/spotify/spotify

**Comment by khanhas** [comment]
You need to change `spotify_path` in config file to `../share/spotify/spotify` (please expand the `..` for me)

**Comment by verajosemanuel** [comment]
That was done prior to this error.  Config y properly set to correct path
full path is /usr/share/spotify

**Comment by khanhas** [comment]
So, does it work normally now?

**Comment by verajosemanuel** [comment]
no. What I said is that the correct spotify path was set "before" getting this error. This is not working

**Comment by khanhas** [comment]
Can you check that does `/usr/share/spotify` is symlink to anywhere else?
