### ISSUE TITLE
How to get rid of top right icons

### ISSUE THREAD

**Issue by shakthiasu** [khanhas/spicetify-cli#142]
![image](https://user-images.githubusercontent.com/56283616/75097869-d8c77280-556c-11ea-84a6-88d9ccaf2acc.png)
I also installed the google themed skins and I am getting the drop down arrows but IT still shows the X _ and Square icons on the top left. How do I get rid of it.

I am also not getting the rounded corners

**Comment by khanhas** [comment]
1. Cannot remove window controlling buttons in Windows.
2. Cannot have rounded corners in Windows unless using 3rd party theme.
