### ISSUE TITLE
Play button disapeared on all spicetify themes

### ISSUE THREAD

**Issue by Sonicx9876** [khanhas/spicetify-cli#1420]
![Screenshot 2022-01-21 105703](https://user-images.githubusercontent.com/87156430/150584416-9d84e917-f6d3-40c8-8f04-1fcb6dfa93a5.png)
The play button and skip forward and back buttons are invisible.
Themes tried Dribblish and fluent

**Comment by CharlieS1103** [comment]
Send your config file.

**Comment by Sonicx9876** [comment]
> Send your config file.
![Screenshot 2022-01-21 114920](https://user-images.githubusercontent.com/87156430/150591190-5309de53-463b-4223-887a-adc6d5580553.png)
![Screenshot 2022-01-21 114819](https://user-images.githubusercontent.com/87156430/150591216-42c18c53-be62-44a0-bcc5-c0c1ae815cc3.png)

**Comment by redalpha01** [comment]
Yeah there seems to be new custom variables and a change on which is called where for the play buttons

**Comment by CharlieS1103** [comment]
Remove fluent.js

**Comment by CharlieS1103** [comment]
As well as fluent theme, they're broken

**Comment by CharlieS1103** [comment]
The only time you should have a js file for a theme installed is if you're currently running that theme btw, otherwise it'll break things

**Comment by redalpha01** [comment]
Happens unrelated to that (I have no extraneous extensions)
Seems like the themes need to be updated but I don't know if the custom css variables are implemented properly for that yet.

**Comment by CharlieS1103** [comment]
Okay send me your config not using fluent or fluent.js, not dribblish or dribblish.js and a screenshot of what your spotify looks like.

**Comment by afonsojramos** [comment]
Closing this as it is related to theme related extensions and mappings.
