### ISSUE TITLE
Blank spotify :/ Help would be appreciated [ARCH LINUX]

### ISSUE THREAD

**Issue by mattBrighto** [khanhas/spicetify-cli#1427]
## ℹ Computer information

- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.8.4

## 📝 Provide detailed reproduction steps (if any)

1. install spotify 
2. install spicetify-cli
3. install themes into theme folder
4. specify the theme in config
5. backup apply enable-devtool
6. wait till it applies the theme
7. open spotify

### ✔️ Expected result

Spotify with nice theme 

### ❌ Actual result

blank spotify :/ but i can play music with media buttons on my keyboard
also tried removing /opt/spotify and it did make spotify normal but when i tried installing spicetify it bugs again

i also tried running spotify through console with --show-console agrument but i dont know if theres something weird.

## 📷 Screenshots
Normal Spotify
![image](https://user-images.githubusercontent.com/78876597/150911045-83c1dd49-3aca-4a30-b1b1-44cfae82d47a.png)

After Applying
![image](https://user-images.githubusercontent.com/78876597/150911212-30f87350-7e02-4d62-8394-b0aabedc287b.png)

My Config
![image](https://user-images.githubusercontent.com/78876597/150911278-233be2c8-10fa-4ffb-b9e8-a682e1e83321.png)
![image](https://user-images.githubusercontent.com/78876597/150911381-b1be1f94-dfea-448d-8dfe-b3c652111c52.png)

Ranger Screens (everything is in the correct place)
![image](https://user-images.githubusercontent.com/78876597/150911344-8d497162-700a-46ec-9359-4aa299832e8b.png)
![image](https://user-images.githubusercontent.com/78876597/150911534-5e287367-64d4-43a8-83ce-14f8e23f7871.png)

config dir
![image](https://user-images.githubusercontent.com/78876597/150911418-bb505369-b465-4273-9c3a-2fe7030e38d5.png)

color dir
![image](https://user-images.githubusercontent.com/78876597/150911512-6552bfe8-2e31-41d9-b1d9-749154650a1c.png)

**Comment by mattBrighto** [comment]
i did changed the config because i havent set the color_scheme but i had no effect :/

**Comment by ririxidev** [comment]
Looks like broken theme. So you should close this issue here and open on spicetify-themes repo.

**Comment by mattBrighto** [comment]
> Looks like broken theme. So you should close this issue here and open on spicetify-themes repo.

well, if thats the case then why doesnt any theme work :/ ?

**Comment by afonsojramos** [comment]
Are the themes up to date?

**Comment by CharlieS1103** [comment]
Try downgrading your spicetify or updating your spotify

**Comment by mattBrighto** [comment]
> Are the themes up to date?

yes they are just downloaded them from github

**Comment by mattBrighto** [comment]
> Try downgrading your spicetify or updating your spotify

doesnt work

**Comment by mattBrighto** [comment]
missclick

**Comment by afonsojramos** [comment]
Have you tried to delete your config and all the folders and start from scratch?

**Comment by mattBrighto** [comment]
> Have you tried to delete your config and all the folders and start from scratch?
sorry for inactiviy, yea i tried that

**Comment by afonsojramos** [comment]
Including the `.spicetify` folder? If even after you delete everything it doesn't work, maybe it is on your side. Try asking Discord for help.

**Comment by ririxidev** [comment]
https://github.com/khanhas/spicetify-cli/commit/809453b488f3ea572400ad6bd0a7f44cea30dcdb beacuse spotify has been updated. you need to wait for new release or just compile spicetify by yourself.

**Comment by mattBrighto** [comment]
> 

thought so
