### ISSUE TITLE
DevTools on progress bars bug

### ISSUE THREAD

**Issue by xerta555** [khanhas/spicetify-cli#1429]
## ℹ Computer information

- Spotify version: 1.1.77.643
- Spicetify version: 2.8.4

## 📝 Provide detailed reproduction steps (if any)

1. Open spotify
2. Open the DevTools
3. Point the one of the two progress bar (the volume or audio progress)
4. Wait some seconds
5. Spotify ant eh DevTools clients reload (like if the user press F5 keyboard key)

### ✔️ Expected result

Spotify client and DevTools shouldn't reload

### ❌ Actual result

Spotify client and DevTools reload after some seconds

This bug appear on my side only when i point the one of progress bars, no problem with any other UI element of spotify.

**Comment by CharlieS1103** [comment]
@xerta555 This is because the progress bar updates the percentage filled each second, you simply need to freeze the UI in order to get it to stay.

**Comment by xerta555** [comment]
> @xerta555 This is because the progress bar updates the percentage filled each second, you simply need to freeze the UI in order to get it to stay.

I specify that the bug occurs regardless of the playing state

**Comment by CharlieS1103** [comment]
The fix remains the same.

**Comment by xerta555** [comment]
> The fix remains the same.

Is it normal that i didn't have this problem with previous versions of Spotify?
