### ISSUE TITLE
Devtools don't work on v2.28.4

### ISSUE THREAD

**Issue by OlaoluwaM** [khanhas/spicetify-cli#1431]
## ℹ Computer information
     OS: Linux (Fedora 35)
     DE: Gnome

- Spotify version:  1.1.72.439.gc253025e (Flatpak)
- Spicetify version: 2.8.4

## 📝 Provide detailed reproduction steps (if any)
    It worked the first time I did it but stopped after I closed Spotify
    I also tried right-clicking the spaces on the player

   1.  Enable devtools
   2.  Press `Ctrl + Shift + I` or Right click
   3.  No context menu or dev tools
   

### ✔️ Expected result

    _What is the expected result of the above steps?_
     The dev tools ought to open on `Ctrl + Shift + I`

### ❌ Actual result

     _What is the actual result of the above steps?_
     Nothing Happens

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by afonsojramos** [comment]
This seems to be something very specific to you. Maybe try finding help in the Discord, but it seems that you are forgetting something.

**Comment by gui-baeta** [comment]
I'm having the same issue as @OlaoluwaM mentioned.
I'm running Fedora 35 (Silverblue), Gnome and also have Spotify installed as a Flatpak.
Any news regardings this issue? Thanks!

**Comment by bruteforks** [comment]
@OlaoluwaM @gui-baeta messing around with immutable linux as well. Did you install the flatpak inside a container?

**Comment by gui-baeta** [comment]
> @OlaoluwaM @gui-baeta messing around with immutable linux as well. Did you install the flatpak inside a container?

Hi! I did not. Flatpak comes in the base Fedora Silverblue OS so I don't need to install it. But wouldn't try to install it in a container since that would probably have it's problems.
I use Spotify as a Flatpak package, installed with Flatpak running on the base/host OS and I can't access Dev tools of Spotify app. That's probably disabled by the Spotify devs, but can't say for certain.
I have since lost the need to use the Dev tools because I stopped tinkering with it. The new stock skin is actually not bad.
Any news on this thou?

**Comment by bruteforks** [comment]
@gui-baeta sorry I meant how did you install spicetify? inside the container? I am unable to get spicetify to access the spotify flatpak on the host. No news, but if I find a way I will tag you

**Comment by gui-baeta** [comment]
> @gui-baeta sorry I meant how did you install spicetify? inside the container? I am unable to get spicetify to access the spotify flatpak on the host. No news, but if I find a way I will tag you

Oh that I was able to! Any Flatpak app is accessible, the path is ridiculously long thou.
I remember finding a better explanation on where it's stored but this could help: https://askubuntu.com/questions/1051438/where-to-find-application-after-flatpak-installation-gimp

Basically, in this example, Gimp is installed in "/var/lib/flatpak/app/org.gimp.GIMP/"
So it should be similar to where Spotify is.
The rest you just need to follow spicetify's tutorial of how to setup.

I hope I was able to help.

**Comment by bruteforks** [comment]
@gui-baeta hey I was finally able to enable the devtools, but it never popped up for me either.

```
on host machine export path to spictify:
export PATH=$PATH:/home/user/.spicetify
spicetify restore backup
spicetify backup apply enable-devtools
spicetify enable-devtools
```

**Comment by gui-baeta** [comment]
> @gui-baeta hey I was finally able to enable the devtools, but it never popped up for me either.
> 
> ```
> on host machine export path to spictify:
> export PATH=$PATH:/home/user/.spicetify
> spicetify restore backup
> spicetify backup apply enable-devtools
> spicetify enable-devtools
> ```

Oh that's very cool! So that's a feature of spicetify itself? 
Thank you for the reply! Next time I fiddle with Spotify I will be sure to do that since that helps a lot in debugging CSS issues.
