### ISSUE TITLE
Spicetify (COSMOS) _Volume property

### ISSUE THREAD

**Issue by nodgear** [khanhas/spicetify-cli#1436]
## ℹ Computer information

- Spotify version: 2.8.4
- Spicetify version: 1.1.77

## 📝 Provide detailed reproduction steps (if any)
No step required.

### ✔️ Expected result

_What is the expected result of the above steps?_
`Spicetify.Player.origin` should contain the `_volume` property, which is missing.

### ❌ Actual result

 Missin property
 Spicetify.Player.getVolume() smells the `undefined` 👃🏻 
 
_What is the actual result of the above steps?_
 This leads to extensions (especially webnowplaying) to break and stop updating.

**Comment by afonsojramos** [comment]
This has now been fixed in #1424.
