### ISSUE TITLE
Can't backup spicetify

### ISSUE THREAD

**Issue by not-alaris** [khanhas/spicetify-cli#1437]
## ℹ Computer information
Macbook Pro 2019
Monterey 12.2

- Spotify version: Spotify for macOS (Intel)
1.1.77.643.g3c4c6fc6
- Spicetify version: spicetify v2.8.4

## 📝 Provide detailed reproduction steps (if any)

1. Did the simple installation for macOS- 
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/CharlieS1103/spicetify-marketplace/main/install.sh | sh

2. Than I generated the config file, and tried to run spicetify backup apply enable-devtool, but it gives me the error "Cannot backup app files. Reinstall Spotify and try again." I've tried re-installing twice and nothing works, I can't backup. Same thing if I just run spicetify backup.

### ✔️ Expected result

_What is the expected result of the above steps? I'm trying to get spicetify to backup.

### ❌ Actual result

_What is the actual result of the above steps? Doesn't allow me to backup; thus preventing me from using themes.

## 📷 Screenshots

_Are there any useful screenshots?_
<img width="1242" alt="Screen Shot 2022-01-30 at 9 10 40 AM" src="https://user-images.githubusercontent.com/72212608/151703234-dc168faa-53ac-4d1e-aca7-56ef6b111b3a.png">

**Comment by SukritTM** [comment]
The same happened to me, I reinstalled Spotify, reran the command and it worked. Make sure you delete the .spicetify folder before you rerun tho
