### ISSUE TITLE
Need help with plugin and general bug fixes

### ISSUE THREAD

**Issue by BigFlubba** [khanhas/spicetify-cli#1447]
I have been having some struggles being able to install plugins properly and getting things set up along with some bugs I have found. I do not know if these bugs are my error or not. Here's what I found...
I do not know what the `1` is and do not know why it is there.
![image](https://user-images.githubusercontent.com/69104450/152089135-c121e066-6d5c-4de3-bf8b-6ad16eb823d1.png)

**Comment by huhridge** [comment]
Check your config, you probably have custom app named '1' in there

**Comment by BigFlubba** [comment]
![image](https://user-images.githubusercontent.com/69104450/152090744-2d187f8d-c19e-4ed1-8cc1-738492c4530f.png)

**Comment by huhridge** [comment]
Yeah, remove the '1' from extensions and custom apps, there are supposed to be names there like
'extensions = fullAppDisplay.js | webnowplaying.js |' and so on
and same for custom apps like 'custom_apps = spicetify-marketplace | new-releases' ,etc.
I would recommend installing marketplace, it may make these things easier.

**Comment by BigFlubba** [comment]
I also keep getting this too.
![image](https://user-images.githubusercontent.com/69104450/152091451-090dc37b-cf61-4bab-8e30-c6e2ab4a35c4.png)

**Comment by huhridge** [comment]
Name the theme to what you have
Leave blank for no theme

**Comment by BigFlubba** [comment]
This?
![image](https://user-images.githubusercontent.com/69104450/152091765-e63e1f34-1161-4618-9ac3-5bfb42f6c74d.png)

**Comment by huhridge** [comment]
Does your css work, because you need a theme to inject css, put the css in 'custom' folder in 'Themes', set the theme to 'custom' and color scheme to nothing. And ignore the error

**Comment by BigFlubba** [comment]
Yes, everything is set up like that and it works.

**Comment by huhridge** [comment]
The error is happening because there is no color.ini, since you do not want to theme spicetify, so everything is normal and I suggest you close this

**Comment by BigFlubba** [comment]
Got it.
