### ISSUE TITLE
Playlist radios won't start

### ISSUE THREAD

**Issue by biggybean** [khanhas/spicetify-cli#1448]
## ℹ Computer information

- Spotify version: Spotify für Windows 1.1.77.643.g3c4c6fc6
- Spicetify version: 2.8.5

## 📝 Provide detailed reproduction steps (if any)

1. Take any playlist
2. Choose menu point "Playlist radio"
3. Playlist Radio appears, click play button

### ✔️ Expected result

Playlist radio starts

### ❌ Actual result

Error message: "Unsupported fetching URI type: station"

## 📷 Screenshots

![2022-02-02 19_30_49-Pim Stones - We Have It All](https://user-images.githubusercontent.com/22399149/152216560-a874defa-8a05-476b-93c9-b0010382d894.png)

**Comment by SupLiCatinG** [comment]
Are you using adblocker for spotify ?

**Comment by biggybean** [comment]
Not that I'm aware of - didn't even know there is such a thing.


Am 3. Februar 2022 13:50:30 schrieb SupLiCatinG ***@***.***>:

**Comment by huhridge** [comment]
it's a shuffle+ problem. You probably have 'auto-shuffle' on. Switching it off fixes it. I'll make a commit to fix it soon anyways.
