### ISSUE TITLE
Spotify shows a blank/black screen

### ISSUE THREAD

**Issue by Daksh777** [khanhas/spicetify-cli#1449]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: Spotify for Windows 1.1.78.765.g5ea20b00
- Spicetify version: 2.8.5
```

### 📝 Description

Spotify doesn't load and shows a blank screen

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/43648146/152365210-6c97f4a2-9eb5-4a30-b72b-27a4d0140ab4.png)

**Comment by itsmeow** [comment]
Windows update link
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.78.765.g5ea20b00-15.exe
