### ISSUE TITLE
Spicetify not detecting spotify location

### ISSUE THREAD

**Issue by rhoriguchi** [khanhas/spicetify-cli#1453]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.77.643.g3c4c6fc6
- Spicetify version: 2.8.5
```

### 📝 Description

[Here](https://github.com/rhoriguchi/nixos-setup/blob/5b5c6fac262b8f630106b13598fbd269f0193c31/configuration/overlays/spotify-unwrapped.nix) you can see how I use it. The portion that is relevant is the `postInstall` block and the `configFile` variable.

Error message:
```console
success Config is updated.
error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini
```

For sanity check I ran `tree` on `$out/share/spotify` and this is the result:
```console
/nix/store/mcjlsdd7qwl9q67nqd925pz14v43sy19-spotify-unwrapped-1.1.77.643.g3c4c6fc6/share/spotify
|-- Apps
|   |-- login.spa
|   `-- xpui.spa
|-- apt-keys
|   `-- spotify-2021-10-27-5E3C45D7B312C643.gpg
|-- chrome_100_percent.pak
|-- chrome_200_percent.pak
|-- icons
|   |-- spotify-linux-128.png
|   |-- spotify-linux-16.png
|   |-- spotify-linux-22.png
|   |-- spotify-linux-24.png
|   |-- spotify-linux-256.png
|   |-- spotify-linux-32.png
|   |-- spotify-linux-48.png
|   |-- spotify-linux-512.png
|   |-- spotify-linux-64.png
|   `-- spotify_icon.ico
|-- icudtl.dat
|-- libEGL.so
|-- libGLESv2.so
|-- libcef.so
|-- libvk_swiftshader.so
|-- libvulkan.so.1
|-- locales
|   `-- en-US.pak
|-- resources.pak
|-- snapshot_blob.bin
|-- spotify
|-- spotify.desktop
|-- swiftshader
|   |-- libEGL.so
|   `-- libGLESv2.so
|-- v8_context_snapshot.bin
`-- vk_swiftshader_icd.json

5 directories, 30 files
```

This seems to be the same directory as shown in the [Advanced Installation](https://spicetify.app/docs/getting-started/advanced-installation#spotify-installed-from-flatpak) documentation.

**Comment by afonsojramos** [comment]
Damn... 🔥 First of all I'm impressed at all those configuration files!!

Second of all, I think you just need to manually set the path, like so:
```sh
spicetify config prefs_path ~/.var/app/com.spotify.Client/config/spotify/prefs
```

**Comment by rhoriguchi** [comment]
> Damn... fire First of all I'm impressed at all those configuration files!!

Thx :smiley:

> Second of all, I think you just need to manually set the path, like so:
> 
> ```shell
> spicetify config prefs_path ~/.var/app/com.spotify.Client/config/spotify/prefs
> ```

I've tried that, sadly that does not work. When I run `spicetify-cli config prefs_path "$out/prefs"` it just fails at that step with the same error message. Also setting `spotify_path` with `spicetify-cli config spotify_path "$out/share/spotify"` raises the same error.

The other issue is Nix has no home while building, that's why I have to do `export HOME=$TMP`, the build step is isolated from the rest of the OS. In Nix all packages are ready only, the only time they are mutable is in the build step, to assure everything is idempotent.

**Comment by afonsojramos** [comment]
Oh, sorry, just re-read the issue, do you mind re-checking again but for the `spotify_path`?

In theory, you are doing this, but is it case insensitive? 
Can you try doing this with the cli? 
If that does not solve it, can you also make sure of the Spotify location?
```sh
substituteInPlace $spicetifyDir/config-xpui.ini \
      --replace "PREFS_PATH" "$out/prefs" \
      --replace "SPOTIFY_PATH" "$out/share/spotify"
```

**Comment by rhoriguchi** [comment]
Done that, sadly no success. Any `spicetify-cli` will give the same error, even if I try to set the config path with `spicetify-cli config spotify_path "$out/share/spotify"`. The reason for the `substituteInPlace` is that I don't know the path beforehand and what I replace is the right hand side.

```console
> echo $(spicetify-cli -c)
/build/.config/spicetify/config-xpui.ini

> echo $spicetifyDir/config-xpui.ini
/build/.config/spicetify/config-xpui.ini

> echo $out/prefs
/nix/store/qa6xalc29cp6qbxhbsv8mxi3c9751diw-spotify-unwrapped-1.1.77.643.g3c4c6fc6/prefs

> echo $out/share/spotify
/nix/store/qa6xalc29cp6qbxhbsv8mxi3c9751diw-spotify-unwrapped-1.1.77.643.g3c4c6fc6/share/spotify

> cat $spicetifyDir/config-xpui.ini
...
[setting]
...
prefs_path=/nix/store/6lh41hn5yypqkmjmq5iwv57scgahiag6-spotify-unwrapped-1.1.77.643.g3c4c6fc6/prefs
...
spotify_path=/nix/store/6lh41hn5yypqkmjmq5iwv57scgahiag6-spotify-unwrapped-1.1.77.643.g3c4c6fc6/share/spotify
```

**Comment by afonsojramos** [comment]
But with that it still printed the `error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini
` error? Then it is very weird because you spotify folder looks okay 🤔

**Comment by rhoriguchi** [comment]
> But with that it still printed the `error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini ` error? Then it is very weird because you spotify folder looks okay thinking

I guess I'll have to dig into the source code and figure out why it does not detect it correctly.

**Comment by rhoriguchi** [comment]
This was poor stupidity on my part. The config keys are case sensitive and I mistyped and tipped `setting` in lower case.

https://github.com/khanhas/spicetify-cli/blob/65295b6bb2ed51bde63d372855e6570d48e5818e/src/cmd/cmd.go#L43-L52

**Comment by afonsojramos** [comment]
Glad to be the rubber duck! 🐥
Thank you for showing me NixOS! That seems exciting and scary at the same time 😨 It still seems a little bonkers to have so much configuration in such a packaged manner!

**Comment by rhoriguchi** [comment]
> Glad to be the rubber duck! 🐥 Thank you for showing me NixOS! That seems exciting and scary at the same time 😨 It still seems a little bonkers to have so much configuration in such a packaged manner!

Pleasure to show you the joy of NixOS. It's a great OS witch can be a bit rough to use but once your used to it and know how to us it, you'll never want to go back.

**Comment by ceebss** [comment]
Hi there im having the same issue i have no experience in terminal, i know the tiniest bit of cmd on windows but here is my problem:

jonnyvalenta@Jonnys-MacBook-Pro ~ % curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
FETCHING Version 2.11.1
DOWNLOADING https://github.com/spicetify/spicetify-cli/releases/download/v2.11.1/spicetify-2.11.1-darwin-arm64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/jonnyvalenta/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/jonnyvalenta/.spicetify/spicetify
REMOVING /Users/jonnyvalenta/.spicetify/spicetify.tar.gz
Manually add the directory to your $PATH through your shell profile
export SPICETIFY_INSTALL="/Users/jonnyvalenta/.spicetify"
export PATH="$PATH:/Users/jonnyvalenta/.spicetify"

spicetify v2.11.1 was installed successfully to /Users/jonnyvalenta/.spicetify
Run 'spicetify --help' to get started
DOWNLOADING https://github.com/spicetify/spicetify-marketplace/archive/refs/heads/dist.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini
jonnyvalenta@Jonnys-MacBook-Pro ~ %

**Comment by gohansaneric** [comment]
if anyone is having this issue i managed to fix mine by simply uninstalling the Microsoft store version and downloading the Setup online in the spotify website

**Comment by JLNoxx** [comment]
> if anyone is having this issue i managed to fix mine by simply uninstalling the Microsoft store version and downloading the Setup online in the spotify website

I did this and it worked, it no longer gave me the problem "cannot detect spotify location. please manually set "spotify_path" in config-xpui.ini"

**Comment by Ganesh-Sharma786** [comment]
> if anyone is having this issue i managed to fix mine by simply uninstalling the Microsoft store version and downloading the Setup online in the spotify website

yes its work for me

**Comment by lamthiennhan-anewbie** [comment]
> if anyone is having this issue i managed to fix mine by simply uninstalling the Microsoft store version and downloading the Setup online in the spotify website

DAmn thx bro so much , hope you have a good day

**Comment by benleitc** [comment]
> if anyone is having this issue i managed to fix mine by simply uninstalling the Microsoft store version and downloading the Setup online in the spotify website

bro you saved me thx

**Comment by jordiamoros** [comment]
> Si alguien tiene este problema, logré solucionar el mío simplemente desinstalando la versión de Microsoft Store y descargando la configuración en línea en el sitio web de Spotify.

y eso como se hace?

**Comment by gohansaneric** [comment]
> > Si alguien tiene este problema, logré solucionar el mío simplemente desinstalando la versión de Microsoft Store y descargando la configuración en línea en el sitio web de Spotify.
> 
> y eso como se hace?

Busca en Google Spotify y en la website debería tener una option para descargar el installer.exe
