### ISSUE TITLE
Not compatible with last Spotify version?

### ISSUE THREAD

**Issue by xerta555** [khanhas/spicetify-cli#1454]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.78.765
- Spicetify version: 2.8.5
```

### 📝 Description

- Updating Spotify client to last version (1.1.78.765)
- Applying Spicetify with `spicetify backup apply` command
- Spotify client appear hidden

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/20888017/152586737-b90592e0-0dfb-4a05-817a-e6890658dbf1.png)

**Comment by misocathy** [comment]
Also having the same problem, version 1.1.78.765 here too
![image](https://user-images.githubusercontent.com/97983857/152588961-3595817a-1850-4e76-820b-512f51200fb1.png)

**Comment by jeroentvb** [comment]
PR https://github.com/khanhas/spicetify-cli/pull/1450 fixed the issue, and has already been merged, but not released yet.

There are 2 things you can do right now:
1. Wait for the next release
2. Build spicetify-cli yourself and run the apply command with the built binary until you can upgrade spicetify normally

**Comment by xerta555** [comment]
> PR #1450 fixed the issue, and has already been merged, but not released yet.
> 
> There are 2 things you can do right now:
> 
>     1. Wait for the next release
> 
>     2. Build spicetify-cli yourself and run the apply command with the built binary until you can upgrade spicetify normally

Not wrong
I didn't realise it

**Comment by afonsojramos** [comment]
Please upgrade to `2.9.0` as soon as you can! It will fix that, thanks!
