### ISSUE TITLE
Searchbar not focused when clicked on and being on another tab

### ISSUE THREAD

**Issue by DanBeast1337** [khanhas/spicetify-cli#1456]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.78.765.g5ea20b00
- Spicetify version: 2.9.0
```

### 📝 Description

When clicking on the search bar, it's not focused anymore after it has loaded, when previously **not being on the search page.**

If you are on the search page, one click is enough to stay focused, otherwise you have to click on the search bar and click another time to focus again. 

This can cause some irritation if wanting to search something and then instead using shortcuts for other things (i often removed songs from my favorites like this). 

Not sure if this is a spotify-side issue (haven't used vanilla really) or spicetify, either way there may be a fix!?

### 📸 Screenshots
(first showing clicking on the search bar from another tab (doesn't matter which one, as long as it's not the search page) and then from inside the search page (which keeps it focused))

![2022-02-05_14h-09m-08s](https://user-images.githubusercontent.com/9980963/152643570-27cdb057-c0c2-48d2-99e4-153a68dcaa52.gif)

**Comment by sagars007** [comment]
Hmm I'm unable to recreate this issue in Vanilla Spotify and using SpicetifyDefault theme. Seems like a problem with Dribbblish theme?

**Comment by huhridge** [comment]
Yeah that search bar is added by dribbblish, may want to open an issue there

**Comment by DanBeast1337** [comment]
Already thought about it, thank you for testing/confirming.

**Comment by DanBeast1337** [comment]
Already thought about it, thank you for testing/confirming.
