### ISSUE TITLE
Spicetify not updating????

### ISSUE THREAD

**Issue by VincentH06** [khanhas/spicetify-cli#1459]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: v1.1.78.765
- Spicetify version:v2.8.5
```

### 📝 Description

I got a popup saying to upgrade to Spicetify v2.9.0 so I followed all the steps and in Powershell it says I am v2.9.0 but then on Spotify it still says I am on v2.8.5

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/99091162/152652339-aa777e28-0237-4fb3-b791-cd67ef7c7ac5.png)
![image](https://user-images.githubusercontent.com/99091162/152652369-ed487a7f-aea7-42d6-a8e0-450caf748c48.png)

**Comment by afonsojramos** [comment]
A popup? Is this some spicetify marketplace feature @CharlieS1103 @theRealPadster?

**Comment by CharlieS1103** [comment]
@afonsojramos Nope, probably dribblish

**Comment by CharlieS1103** [comment]
Dribblish dynamic for clarification

**Comment by VincentH06** [comment]
> 

yes that is what theme i am using and where the popup came up from 
![image](https://user-images.githubusercontent.com/99091162/152691862-d1075fac-e896-4b74-9558-8c72e52bd447.png)

**Comment by afonsojramos** [comment]
This is cool, but it does seem to know that it is already in 2.9.0 @VincentH06 🤔

**Comment by afonsojramos** [comment]
Well, I think that is expected. Either way, that is something for the dribblish dynamic project, so I will close the issue.
