### ISSUE TITLE
[ 1 / 35 ] aboutfatal zip: not a valid zip file

### ISSUE THREAD

**Issue by swoopae** [khanhas/spicetify-cli#146]
windows 10 x64 1903
used prebuilt binary from here
full log: 
`
PS C:\WINDOWS\system32> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/mast
er/install.ps1" | Invoke-Expression
DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest > OK
DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v0.9.7/spicetify-0.9.7-windows-x64.zip > OK
EXTRACTING     C:\Users\senpa\spicetify-cli\spicetify-0.9.7-windows-x64.zip into C:\Users\senpa\spicetify-cli > OK
REMOVING       C:\Users\senpa\spicetify-cli\spicetify-0.9.7-windows-x64.zip > OK
 > OK
Run spicetify --help to get started.

PS C:\WINDOWS\system32> spicetify
success Config is updated.
info Run "spicetify -h" for commands list.
PS C:\WINDOWS\system32> spicetify backup apply enable-devtool
spicetify v0.9.7
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
[ 1 / 35 ] aboutfatal zip: not a valid zip file
PS C:\WINDOWS\system32>`

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply`
