### ISSUE TITLE
Last.fm external app

### ISSUE THREAD

**Issue by Utsav-Murudi** [khanhas/spicetify-cli#1462]
## 📝 Provide a description of the new feature
An external app for Last.fm similar to reddit.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_
Many users use Last.fm for tracking and getting recommendations. The main purpose of this external app would be the recommendations from Last.fm which can be checked at a glance and played.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by TheMayhem6328** [comment]
To add to this, somehow adding scrobble count would be fun too. Ideally, it should be integrated directly into tracklist - maybe beside or in place of `plays`?

**Comment by afonsojramos** [comment]
> To add to this, somehow adding scrobble count would be fun too.

This does not make sense since Last.fm already implements Spotify scrobble.

**Comment by afonsojramos** [comment]
Will close this issue as the core team will not work on this, however, the community is more than open to do it :eyes:
