### ISSUE TITLE
Can't use custom apps

### ISSUE THREAD

**Issue by Ergoprett** [khanhas/spicetify-cli#1464]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: I don't know newest
- Spicetify version:version = 1.1.65.643.g2d707698
                    with    = 2.9.0
```

### 📝 Description

I can apply themes in Spicetify, but no custom apps.
I would love to use the custom apps, but it doesn't work. 
I already tried everything in this thread but nothing works. 
https://github.com/khanhas/spicetify-cli/issues/845

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/87259731/152825982-9e339343-25fd-4314-87da-0b220b6b24ec.png)

**Comment by itsmeow** [comment]
1.1.65 is not newest. Please update your Spotify, that version is over 10 versions old.

**Comment by Ergoprett** [comment]
I just downloaded the newest version earlier, I don't know why it didn't work.
But now everything works, again.
Thanks a lot.
