### ISSUE TITLE
Don't know how to apply changes to Spotify at different storage drive.

### ISSUE THREAD

**Issue by KhoaVu8** [khanhas/spicetify-cli#1467]
My main SSD is almost full so I copied and pasted the AppData folder of the Original Spotify on SSD. But when I try to apply the modification to my Spotify on my Windows PowerShell, it showed the backup applied successfully but nothing changed to my Audio Visualiser at Desktop. Is there any way to apply the modification to my Spotify located at other drives?
![Screenshot 2022-02-07 160129](https://user-images.githubusercontent.com/73670357/152871725-141c37f0-2d0c-4769-afac-d27d04a3bf6b.png)
.

**Comment by KhoaVu8** [comment]
> So the issue is that the Monstercat audio visualizer(rainmeter skin) doesn't display song info and album art?
> Have you tried using other extensions with Spicetify, like fullAppDisplay.js, popupLyrics.js etc.. Do they work?

Yes, the Monstercat Visualizer doesn’t show the song name, Artist and Album Art from Spotify run on F: external HDD.

**Comment by sagars007** [comment]
Hope this fixes it: https://github.com/marcopixel/monstercat-visualizer/issues/374#issuecomment-1025501756

**Comment by afonsojramos** [comment]
Okay, so it seems that this issue does not belong here, therefore, I will close it.

**Comment by KhoaVu8** [comment]
> So the issue is that the Monstercat audio visualizer(rainmeter skin) doesn't display song info and album art?
> Have you tried using other extensions with Spicetify, like fullAppDisplay.js, popupLyrics.js etc.. Do they work?

I just tried those extensions and it worked. Thanks for help.

**Comment by sagars007** [comment]
> > So the issue is that the Monstercat audio visualizer(rainmeter skin) doesn't display song info and album art?
> > Have you tried using other extensions with Spicetify, like fullAppDisplay.js, popupLyrics.js etc.. Do they work?
> 
> I just tried those extensions and it worked. Thanks for help.

Welcome!
