### ISSUE TITLE
Odd formatting error

### ISSUE THREAD

**Issue by derekagraham78** [khanhas/spicetify-cli#147]
![spicetify-problem](https://user-images.githubusercontent.com/54497759/75788232-ef708500-5d35-11ea-93ee-10a5d41d17d7.png)
this happens no matter the theme, running the AUR on Manjaro

**Comment by D33pfield** [comment]
Getting the same thing on Pop_OS running xfce. It seems to be a font problem maybe?

**Comment by khanhas** [comment]
Please reinstall Spotify and run `spicetify backup apply` again.
Every time Spotify is upgraded to new version, run `spicetify backup apply`
