### ISSUE TITLE
Install script misphrases $PATH note

### ISSUE THREAD

**Issue by jorisw** [khanhas/spicetify-cli#1473]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- macOS 12.2.1
- Spicetify version: 2.9
```

### 📝 Description

```
spicetify was installed successfully to /Users/jorisw/.spicetify/spicetify

Please restart your Terminal to have spicetify in your PATH.
Then you can run:
'/Users/jorisw/.spicetify/spicetify --help' to get started
```

I believe this means to say:

`Until then you can run:`

or:

```
Then you can run:
'spicetify --help' to get started
```

**Comment by afonsojramos** [comment]
I think the latter is the one that makes the most sense, thanks for the issue!
