### ISSUE TITLE
Is it possible to change the popularity meter to a number with spicetify?

### ISSUE THREAD

**Issue by zjeffer** [khanhas/spicetify-cli#148]
When looking at a list of songs in an album, there's a meter showing how popular a song is. When you mouse over the meter, it shows the amount of plays. When looking at the top 5 songs of an artist, it shows the number of plays instead of a meter. 

I was wondering if it was possible to always show the number instead of a meter when looking at an album. 

I'm guessing it isn't possible but I'd love to be proven wrong :)

**Comment by mackarelfish** [comment]
It's definitely possible, just add this style to your theme css file.
`
.TableCellPopularity__popularity-meter::before {
    content: attr(data-tooltip-text);
}

.TableCellPopularity__popularity-meter-background,
 .TableCellPopularity__popularity-meter-overlay {
    display: none;
}
`
![pic-selected-200327-0442-28](https://user-images.githubusercontent.com/55378008/77699678-67ecfd80-6fe5-11ea-8a80-1b80118a994e.png)

**Comment by zjeffer** [comment]
Thanks! Is there any way to remove the 'plays' string?

**Comment by zjeffer** [comment]
Closing in favour of #162
