### ISSUE TITLE
Home screen appears blank.

### ISSUE THREAD

**Issue by Adithya-Kalany** [khanhas/spicetify-cli#1482]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.79.763.gc2965cdf
- Spicetify version: 2.9.1
```

### 📝 Description

I installed the new update and re-installed multiple times, yet this issue occurs. Attaching logs and please do give me a resolve on this.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/69103102/154729594-72a223f6-897b-4832-bfc5-fd79c3369707.png)
![image](https://user-images.githubusercontent.com/69103102/154729624-a972f434-aedc-4aff-bb69-eecadc38a748.png)

**Comment by CharlieS1103** [comment]
Yeah if you check Spotify on down detector it looks like they're having some issues

**Comment by Adithya-Kalany** [comment]
Ah okay that explains it, thanks!
