### ISSUE TITLE
Spotify DevTools language preference not saved

### ISSUE THREAD

**Issue by xerta555** [khanhas/spicetify-cli#1487]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.79.763
- Spicetify version: 2.9.1
```

### 📝 Description

- Run Spotify
- Open DevTools of Spotify (Ctrl+Alt+I)
- Set DevTools language to Spanish (for exemple, it happen for any language)
- Close DevTools
- Open DevTools again, the language set isn't saved

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/20888017/154810558-065dbf1b-90f9-4c1f-9379-8facefa91dac.png)

**Comment by afonsojramos** [comment]
This is something part of CEF that the Spotify app is built on, so not something we can change.

**Comment by xerta555** [comment]
> 

CEF?
Any idea for a temporary fix?

**Comment by afonsojramos** [comment]
Temporary/long-term fix is to either learn english or change language every time 😅

**Comment by xerta555** [comment]
> Temporary/long-term fix is to either learn english or change language every time 😅

Ok and what is CEF?

**Comment by afonsojramos** [comment]
CEF = [Chromium Embedded Framework](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework)
