### ISSUE TITLE
Allow a custom folder for the spicetify files

### ISSUE THREAD

**Issue by SophieAu** [khanhas/spicetify-cli#15]
On Mac, spicetify creates a non-hidden folder in my home folder (`spicetify_data`) which I would love to be able to customize.

So maybe allow reading from a env var and use that location as fallback? I'm happy to create a PR if this is a feature you'd consider.

**Comment by khanhas** [comment]
Yeah I think using an environment variable for 3 platforms to customize config directory is the best solution. 
Thank you!

**Comment by SophieAu** [comment]
Awesome! I'll create a PR next week 👍

**Comment by khanhas** [comment]
Ah. Don't worry, I will do it this weekend

**Comment by khanhas** [comment]
I added this feature in v0.8
Please check it out and tell me if it works correctly.

**Comment by SophieDonut** [comment]
works great, thank you!

**Comment by SophieAu** [comment]
works great, thank you!
