### ISSUE TITLE
Can't open dev tools panel

### ISSUE THREAD

**Issue by liquid600pgm** [khanhas/spicetify-cli#150]
After using `spicetify enable-devtool`, I cannot use Ctrl+Shift+I to enable the dev tools panel. Using the command simply logs me out of Spotify for some reason (probably has something to do with the client locking my access to the dev tools, but honestly I have no idea).

**Comment by khanhas** [comment]
Can you access it from this menu?
![image](https://user-images.githubusercontent.com/26436809/76209882-aa28e780-624e-11ea-8177-30fb45186377.png)

**Comment by liquid600pgm** [comment]
I don't have this menu at all. I wouldn't be surprised if it was Windows-specific.

**Comment by liquid600pgm** [comment]
I just right-clicked on a blank area accidentally, the Show Dev Tools button was available here.
