### ISSUE TITLE
Custom Apps "Lyrics" on Synced tab is way to high up to see the Synced Lyrics

### ISSUE THREAD

**Issue by Lainasan** [khanhas/spicetify-cli#1500]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v1.1.79.763
- Spicetify version: v2.9.1
- Windows 11
```

### 📝 Description

I just updated my spotify and spicetify but the Custom app "Lyrics" on synced tab is so high up to see the Synced Lyrics.

Edit: I typed v2.9.3 instead of v2.9.1 on spicetify version.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/90865965/155245110-721ee5c9-319a-4f2c-90ab-44f407ee2ee9.png)

**Comment by huhridge** [comment]
> ```gfm
> - Spotify version: v1.1.79.763
> - Spicetify version: v2.9.3
> ```
you must live in the future, because last I checked the latest version was 2.9.1.

seems like a problem with your theme maybe? check if the lyrics are even present by inspect element

**Comment by Lainasan** [comment]
Oh, sorry I mistyped it It's v2.9.1

I check it and it's present and the lyrics is showing on full app display extension but on the Synced tab It's on the top you can't see it.

**Comment by Lainasan** [comment]
Update: The themes has the problem am going change it and report an issue to the creator thanks.

The Theme that I use is DribbblishDynamic by JulienMaille.
