### ISSUE TITLE
?

### ISSUE THREAD

**Issue by itssonny** [khanhas/spicetify-cli#151]
It says C://Users/Owner/Appdata/Roaming/Spotify/prefs file isn't found, and I tried reinstalling Spotify and Spicetify but it still says it
![image](https://user-images.githubusercontent.com/61924574/76155186-680c7400-609d-11ea-88c0-3a23fd85d96a.png)
.

**Comment by khanhas** [comment]
This is Spicetify for Rainmeter. It is no longer supported.
Please reinstall Spotify and follow this guide https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user
