### ISSUE TITLE
Can't install Spicetify on Windows 8

### ISSUE THREAD

**Issue by AidenR449** [khanhas/spicetify-cli#152]
Whenever I run `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression` in PowerShell I get [this error](https://imgur.com/a/fJhPDwd). Any help?

**Comment by khanhas** [comment]
Upgrade Powershell to v5 for Windows 8
