### ISSUE TITLE
Can't add extentions

### ISSUE THREAD

**Issue by Mermyx** [khanhas/spicetify-cli#153]
Whenever you add extensions the file downloads and says "success Config changed: extensions = (installed extension)" but it doesn't work and doesn't shop up on spotify

**Comment by khanhas** [comment]
Run `spicetify apply`

**Comment by Mermyx** [comment]
i have tried with trashbin and webnowplaying so far, but neither of them are working

**Comment by khanhas** [comment]
How do you know they not working?
Did you check Console?

**Comment by Mermyx** [comment]
it doesn't show on spotify

**Comment by mgoszcz2** [comment]
I'm having the same issue, I tried enabling `keyboardShortcut.js`. The file definitely exists and I have

```
extensions = keyboardShortcut.js
```

set in my config file. I've ran `spicetify update` and restarted Spotify. Nothing of intrest shows up in the console.

**Comment by khanhas** [comment]
You need to run `spicetify apply`

**Comment by mgoszcz2** [comment]
Thanks, that did it. Might make sense to mention `spicetify apply` in the Extensions wiki page. Great project.

**Comment by Mermyx** [comment]
even after running `spicetify apply` extentions such as trashbin and webnowplaying don't work although shuffle+ is working, does this have something to do with the spotify version.

**Comment by khanhas** [comment]
They still works fine at my end. Trashbin should be found in right click menu of track links and artist links. I believe Webnowplaying is still working fine else I would receive a lot of complaint from Rainmeter community.
