### ISSUE TITLE
No more css file ? (flatpak install)

### ISSUE THREAD

**Issue by papey** [khanhas/spicetify-cli#155]
I'm currently facing issues using spicetify-cli on my flatpak install.

Since the last update, I can't find css files anymore. There is only `.spa` files, eg :

```
file /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/zlink.spa
/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/zlink.spa: Zip archive data, at least v2.0 to extract
```

It looks like something change in the way Spotify client is bundled, do you have any advice ?

Thanks for help and thanks for this awesome tool.

**Comment by khanhas** [comment]
Run `spicetify backup apply`

**Comment by papey** [comment]
It works, thanks a lot.
