### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by yuvyuvyuv** [khanhas/spicetify-cli#156]
I wasn't able to uninstall spicetify, tried to but there were still files of it.
how can I uninstall it?
(the software itself is great it just wasnt exectly what I thought it was).

**Comment by PoorPocketsMcNewHold** [comment]
This depends on where you’ve installed spicetify obviously.
Via homebrew, It’s `brew uninstall khanhas/tap/spicetify-cli`.
Via the AUR, It’s `yay -R spicetify`.
From the prebuilt linux or darwin packages, I suppose deleting the ~/.spicetify folder after reinstalling a clean installation of Spotify will work, but they’re surely a better way to uninstall it.
