### ISSUE TITLE
Cover images are MASSIVE in certain views

### ISSUE THREAD

**Issue by InternetOscar** [khanhas/spicetify-cli#157]
I'm setting up spicetify on a new windows account for school and no matter which theme I choose all of the cover images are massive.

here is an example:
![image](https://user-images.githubusercontent.com/29482772/77422929-3fa8a780-6e09-11ea-92aa-e19853909488.png)

It only happens when spotify is maximised too. When I have it set to half-width the sizes of everything is perfect.

I haven't included the right side of spotify because my friends names are there and don't want to dox them.

**Comment by khanhas** [comment]
I could not reproduce.
Can you give me specific steps so I can examine this?

**Comment by InternetOscar** [comment]
1. start spotify windowed
2. select and apply a theme
3. make spotify fullscreen

now you have large cover images

**Comment by InternetOscar** [comment]
I uninstalled spotify and spicetify then reinstalled both and it seems to have fixed it after a restart
