### ISSUE TITLE
all black window on ubuntu 18.04

### ISSUE THREAD

**Issue by littleredryanhood** [khanhas/spicetify-cli#158]
I've installed the latest version of spicetify CLI and spotify (downloaded and installed, not via snap), whenever I apply a theme the spotify window goes completely black.  I've reinstalled spotify a few times.  The only thing that I have seen is an error about jshelper not found when I run a spiceftify backup apply.

Please let me know what details I can provide to help troubleshoot.  
![Screenshot_20200315_113529](https://user-images.githubusercontent.com/47164393/77448368-f0815900-6dad-11ea-8bd4-a322207bd09e.png)

**Comment by khanhas** [comment]
Try reinstalling Spotify then run: `spicetify backup apply`

**Comment by littleredryanhood** [comment]
I think I found my problem, it looks like I had two installs of spicetify, one was in ~/ and the other was in /usr/bin when I would run spicetify backup apply and spicetify update it would run from /usr/bin and was all wonky.  Closing as user error.  Thanks for helping.  Your tool looks great.
