### ISSUE TITLE
Prefs file error

### ISSUE THREAD

**Issue by AlphaBlue7** [khanhas/spicetify-cli#159]
I get this error when i run `spicetify backup apply enable-devtool`
`Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini`
Even though i've correctly nentioned the location of the prefs file 

prefs_path       = .var/app/com.spotify.Client/config/spotify/prefs
Please help T_T 
OS is Fedora 31

**Comment by mackarelfish** [comment]
Maybe try adding the full path? `/home/<username>/.var/app/com.spotify.Client/config/spotify/prefs`

**Comment by AlphaBlue7** [comment]
> Maybe try adding the full path? `/home/<username>/.var/app/com.spotify.Client/config/spotify/prefs`

Just tried that, it still isn't working unfortunately.

**Comment by AlphaBlue7** [comment]
> Maybe try adding the full path? `/home/<username>/.var/app/com.spotify.Client/config/spotify/prefs`

added a forward slash(/) just before home and it worked tyvm
