### ISSUE TITLE
user.css error

### ISSUE THREAD

**Issue by AlphaBlue7** [khanhas/spicetify-cli#161]
I get this error when i run `spicetify update`

`fatal open /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/zlink/css/user.css: no such file or directory`

and I can't add files to zlink.spa because i'm apparently not the owner .
My OS is Fedora 31
Also i'm new to linux.

Please help

**Comment by mackarelfish** [comment]
Maybe try giving your user permission on the folder?
`sudo chmod 777 /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/`

**Comment by AlphaBlue7** [comment]
> Maybe try giving your user permission on the folder?
> 
> ```
> sudo chmod 777 -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
> ```

Ii ran the command you gave me , but it returns me the same error

**Comment by khanhas** [comment]
After giving permission, run `spicetify restore backup apply`.
If it doesn't change anything, reinstall Spotify and run `spicetify backup apply`.

**Comment by AlphaBlue7** [comment]
> spicetify restore backup apply

How do i give permission exactly?

**Comment by jessebett** [comment]
I am also getting this error on manjaro.

`fatal open /opt/spotify/Apps/zlink/css/user.css: no such file or directory` 

It's not an isue of permissions, it seems there is no `zlink` directory in `Apps`.

**Comment by khanhas** [comment]
@jessebett please reinstall spotify and run `spicetify backup apply`
Whenever Spotify has new update, always run `spicetify backup apply`
