### ISSUE TITLE
Extension KeyboardShortcuts: Play button shortcut

### ISSUE THREAD

**Issue by jzbor** [khanhas/spicetify-cli#163]
There are many options on pressing <f>, but I am missing one that enables me to play songs with the keyboard shortcuts. It would be great if you could add shortcuts for the play buttons on the beginning of each line.

Btw you are doing a great job - with both the program itself and the extensions! :)

**Comment by Piehthyte** [comment]
Sorry, but why not get a keyboard with media controls?

**Comment by Piehthyte** [comment]
I'm rocking a sidewinder x4 from 2012 xD 20 bucks gets you a long way

**Comment by jzbor** [comment]
I did not mean a general play/pause button. The goal would be selecting a specific song to play.

**Comment by Piehthyte** [comment]
Ohhhhhh alright I understand now apologies

**Comment by jzbor** [comment]
Ok, so I think as of [this](https://github.com/khanhas/spicetify-cli/commit/b58178ec97b14d45bcb83c2a94fde1c657e71377) commit there is now a shortcut to play songs. It works great! Thanks for your great job making this @khanhas :)
