### ISSUE TITLE
Pywal Variables

### ISSUE THREAD

**Issue by heyyzoeyy** [khanhas/spicetify-cli#17]
There is a tool called Pywal which generates colors from the current wallpaper. [https://github.com/dylanaraps/pywal](url) Color variables are stored in the .Xresources file, so would you know a way to use those variables in the colors.ini file?
I have tried to use  `${xrdb:color0:#fff}` and an enivornment variable.

**Comment by khanhas** [comment]
This is brilliant!
Yeah I will add it in next weekend.

**Comment by heyyzoeyy** [comment]
Thanks!

**Comment by khanhas** [comment]
@heyyzoeyy Added in v0.8.1
Check it out!

**Comment by heyyzoeyy** [comment]
This is awesome, it's working great!
