### ISSUE TITLE
spicetify update command doesn't work when run in a script with cronjob

### ISSUE THREAD

**Issue by Ninja73737** [khanhas/spicetify-cli#170]
Hello!
I have a script that changes settings from various programs between light and dark mode and I was adding Spicetify to this by making it edit the config.ini file's theme then running `spicetify update`. I run this script as a cronjob. The editing of the config.ini file works whether I run the script as a cronjob or manually, but the `spicetify update` command does not work when the script is run as a cronjob. Any idea what might be causing this?

**Comment by khanhas** [comment]
After run `spicetify update`, did you refresh Spotify (hit Ctrl Shift R) or restart Spotify?

**Comment by Ninja73737** [comment]
Yes, I refreshed it with the same keyboard shortcut that successfully refreshes it when the script is not run from the cronjob. It does show that it’s refreshing but when it refreshes it’s still on the old theme.

**Comment by khanhas** [comment]
I'm sorry, I don't quite understand what you just said. Can you phrase it again?

**Comment by Ninja73737** [comment]
No worries, sure! Yes, I did refresh it with the keyboard shortcut. I know I'm using the right shortcut because it does update the theme successfully normally. The only time it doesn’t work is when the spicetify update command is run as part of a cronjob. Does that make sense?
I’m thinking it might be a permissions error, but I’m not sure how to go about debugging it. Do you have any suggestions?

**Comment by khanhas** [comment]
OK I can understand now.
But I don't see any reason why it shouldn't work in your "cronjob" (I assume it's just a script, correct me if I'm wrong) as long as you use same commands when you do it manually.

**Comment by Ninja73737** [comment]
I don't either, but I'm sure that's what's happening, I've tested it plenty
of times. Actually I just had an idea that I probably should've had
earlier, but I'll modify the script so that all its output is dumped into a
file and see if the command is throwing any errors.
