### ISSUE TITLE
How do i change to DARK theme located in the color.ini

### ISSUE THREAD

**Issue by Blackrucat** [khanhas/spicetify-cli#173]
[base]
; Pink on White background
main_fg                               = FE6F61
secondary_fg                          = 3D3D3D
main_bg                               = FAFAFA
sidebar_and_player_bg                 = FAFAFA
cover_overlay_and_shadow              = 000000
indicator_fg_and_button_bg            = FE6F61
pressing_fg                           = FF5C86
slider_bg                             = FAFAFA
sidebar_indicator_and_hover_button_bg = FF6F61
scrollbar_fg_and_selected_row_bg      = EBEBEB
pressing_button_fg                    = DEDEDE
pressing_button_bg                    = 383145
selected_button                       = FE6F61
miscellaneous_bg                      = 3F3C45
miscellaneous_hover_bg                = 383145
preserve_1                            = FFFFFF

[dark]
; Light green on Dark Blue background
main_fg                               = 00FF9C
secondary_fg                          = DEDEDE
main_bg                               = 2E2837
sidebar_and_player_bg                 = 2E2837
cover_overlay_and_shadow              = 000000
indicator_fg_and_button_bg            = 00FF9C
pressing_fg                           = FF5C861
slider_bg                             = 3F3C45
sidebar_indicator_and_hover_button_bg = 00BF76
scrollbar_fg_and_selected_row_bg      = 615670
pressing_button_fg                    = DEDEDE
pressing_button_bg                    = 383145
selected_button                       = 00BF76
miscellaneous_bg                      = 3F3C45
miscellaneous_hover_bg                = 383145
preserve_1                            = FFFFFF

There are thoses 2 themes how do i get the dark?

**Comment by Drgabi18** [comment]
It exists in the [code](https://github.com/khanhas/spicetify-cli/blob/38947253dd6fdfecfb677dd6079ade835c2b78ad/src/cmd/color.go#L86-L96), wait for Khan to update the the [spicetify.go](https://github.com/khanhas/spicetify-cli/blob/master/spicetify.go) file with instructions

**Comment by Halloyo** [comment]
You can just remove everything before [DARK]
