### ISSUE TITLE
spotify keeps migrating to Store version

### ISSUE THREAD

**Issue by hhhal** [khanhas/spicetify-cli#174]
so i've actually looked around the issues here and got very close to having an install but had no luck, still.

i keep uninstalling every spotify installation, yet every installer constantly changes itself back to the store version. i've tried safe mode, deleting registry keys, but it's completely unavoidable. does anyone have any way to fix this shit?

by the way, i'm using windows 10 home 64 bits, if that helps.

**Comment by khanhas** [comment]
So you have tried everything. I honestly don't know any solution to suggest.
But, have you ever considered remove Windows Store?

**Comment by userhas404d** [comment]
@hhhal what are you seeing specifically? I just got spicetify-cli up and running on windows 10 after uninstalling the spotify windows store app and installing the standalone app from here: https://www.spotify.com/download/windows/ and thus far no issues - haven't rebooted yet though..

This is what I have in my spicetify-cli `[settings]` block
```
spotify_path     = C:\Users\<username>\AppData\Roaming\Spotify\
prefs_path       = C:\Users\<username>\AppData\Roaming\Spotify\prefs
```

**Comment by Drgabi18** [comment]
I was in the same boat and disabling Windows Store from registry did the job for me. Uninstall the Windows Store version of spotify, make a .reg file containing
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsStore]
"DisableStoreApps"=dword:00000001
```
, run it, restart your pc and download the installer from userhas404d link, after that, everything should be automated when you run `spicetify` or run the download link again

(to enable back the Windows Store, just change the second line to `"DisableStoreApps"=-`)

**Comment by userhas404d** [comment]
Quick update, I'v rebooted a few times since installing the non-windows store version of spotify and it hasn't tried to migrate to the windows store version. @Drgabi18 that might be helpful for others, but I didn't want to risk breaking wsl by disabling the windows store so didn't try it.

**Comment by Drgabi18** [comment]
[Based on this](https://github.com/microsoft/WSL/issues/2323), the distros install in the WindowsApps folder, which doesn't disappear when you turn off the store, so I don't think it may be a problem, but at least you got it working without that so gg!
