### ISSUE TITLE
Change CSS color from album colour

### ISSUE THREAD

**Issue by Halloyo** [khanhas/spicetify-cli#176]
Hello. I know this was an issue which khanhas already replied to, but I don't know how to code so I can't really use the answer (if that makes sense?). It would be appreciated if someone could at least explain what to write in the JS script.

The answer from khanhas:
0. You need an extension (JS script) to do that.
1. Use method `Spicetify.getAblumArtColors` from Spicetify API to get colors.
For example, get colors of this currently playing album
```
Spicetify.getAblumArtColors(Spicetify.Player.data.track.metadata.album_uri)
    .then((colors) => {
        console.log(colors)
    })
```
`colors` object received from the method contains all colors from dark to bright and vibrant ones.

3. From there, you can change spicetify CSS variables with color you want, also with JS.

_Originally posted by @khanhas in https://github.com/khanhas/spicetify-cli/issues/122#issuecomment-565857732_

**Comment by khanhas** [comment]
Please ask for help on Spectrum.
