### ISSUE TITLE
Reload specific div on track change

### ISSUE THREAD

**Issue by Halloyo** [khanhas/spicetify-cli#177]
Hello. The theme I have created centers the track+artist playing. However, it sometimes lands on half-pixels and the text becomes blurry. The only way I have found to fix it is to reload the page, however I dont want to have to manually load the page everytime a new track plays. 

I know it is possible to reload only the text container, but how would I make it do so automatically whenever the track changes?

**Comment by khanhas** [comment]
Can I have some screenshots of this blurry text? With them, I might have other solution since reloading page adds memory usage up really quickly. 

Anyway, here the code for auto-reloading on track change:
```js
Spicetify.Player.addEventListener("songchange", () => window.location.reload(false));
```

**Comment by Halloyo** [comment]
The difference doesn't show as well in screenshots, but it is noticable enough that it annoyed me.
Here is the blurry text:
![Capture d’écran (50)](https://user-images.githubusercontent.com/62628491/79759992-66191000-82ed-11ea-990d-f9995d9995ee.png)
Here is after reloading:
![Capture d’écran (51)](https://user-images.githubusercontent.com/62628491/79759994-66b1a680-82ed-11ea-80a1-5b1b191e84bd.png)

**Comment by khanhas** [comment]
https://stackoverflow.com/questions/8840580/force-dom-redraw-refresh-on-chrome-mac
I guess you could try some of these solutions, excluding those with JQuery.

**Comment by Halloyo** [comment]
Ended up not centering it.
