### ISSUE TITLE
Custom color.ini variables?

### ISSUE THREAD

**Issue by Fuhrmann** [khanhas/spicetify-cli#178]
First of all everything works fine! Thanks!

I want to specify a new `colors.ini` variable like:

`footer_background = ${xrdb:color1}`

And use it inside my `user.css` like so:

```
.view-player {
  background: var(--modspotify_footer_background)
}
```

Is this possible right now or there it is another solution? I couldn't find anything related to this in the docs.

Thanks.

**Comment by Fuhrmann** [comment]
I guess this is related to #57.

**Comment by khanhas** [comment]
Spicetify doesn't support custom variable right now. But I think it would be a nice addition.
Thank you!

**Comment by Fuhrmann** [comment]
I've made a patch to get it working, but I want to post here so you can take a look and see if it follows your idea to this change:

```
diff --git a/src/apply/apply.go b/src/apply/apply.go
index a852fe3..59f1a81 100644
--- a/src/apply/apply.go
+++ b/src/apply/apply.go
@@ -204,11 +204,12 @@ func getColorCSS(scheme *ini.Section) string {
 
 	var variableList string
 
-	for k, v := range utils.BaseColorList {
-		parsed := utils.ParseColor(scheme.Key(k).MustString(v))
+	for _, k := range scheme.KeyStrings() {
+		base_value := utils.BaseColorList[k];
+		parsed := utils.ParseColor(scheme.Key(k).MustString(base_value))
 		variableList += fmt.Sprintf(`
-    --modspotify_%s: #%s;
-    --modspotify_rgb_%s: %s;`,
+	--modspotify_%s: #%s;
+	--modspotify_rgb_%s: %s;`,
 			k, parsed.Hex(),
 			k, parsed.RGB())
 	}

``` 

Instead of loading only the `BaseColorList` we iterate over every key defined in `color.ini` and parse the color. We keep loading the default value for the key, but if the key is a custom one it has not any custom value. 

Maybe we should check if the value exists in this line?

`base_value := utils.BaseColorList[k];`

This is my first time messing with go.

I've tested locally and its working fine as you can see here:

![image](https://user-images.githubusercontent.com/1160365/79931006-e8055800-8417-11ea-9b2e-aee2f5fcf5e0.png)

**Comment by khanhas** [comment]
Add in v0.9.9
