### ISSUE TITLE
"Unsupported fetching URI type: playlist-v2" error

### ISSUE THREAD

**Issue by Halloyo** [khanhas/spicetify-cli#179]
Hello,

As the name implies, I sometimes get the error "Unsupported fetching URI type: playlist-v2" when trying to shuffle context. It only happens when I double-click on a playlist name in the left sidebar. 
![Capture d’écran (52)](https://user-images.githubusercontent.com/62628491/80157104-7b16cd00-8593-11ea-8672-e7cad12eab54.png)

**Comment by khanhas** [comment]
Fixed in v0.9.9
