### ISSUE TITLE
I can't find the buttons in the queue for shuffle+

### ISSUE THREAD

**Issue by mohitgarg** [khanhas/spicetify-cli#18]
> After injecting this extension, go to Queue and you can find 2 new buttons at page header: - Shuffle Context: detect current context and shuffle all its item.

This is what I changed in my config file:
`extensions= shuffle+.js|queueAll.js`

Here's what the queue looks like:

<img width="989" alt="Screen Shot 2019-05-20 at 14 58 29" src="https://user-images.githubusercontent.com/14136405/58011455-e6e4f000-7b0f-11e9-8223-8895a7ae4df0.png">

I am using Spotify on Mac with version is 1.1.7.13766.gf9dc3904 with Spicetify v0.8.0

**Comment by khanhas** [comment]
Fixed in v0.8.1
Check it out!

**Comment by mohitgarg** [comment]
Hi @khanhas . Thank you for the update but it seems like there's an issue with homebrew. First I was getting a 404 error but then I guess it got fixed somehow and now I am getting a *checksum error*
<img width="1010" alt="Screen Shot 2019-05-28 at 10 09 21" src="https://user-images.githubusercontent.com/14136405/58451338-af3dff80-8130-11e9-90cf-b07017eb65f0.png">
I have tried cleaning up as mentioned in the instructions as well `brew cleanup` and `brew doctor` but somehow it still exists.

**Comment by khanhas** [comment]
Fixed. Please try again

**Comment by mohitgarg** [comment]
It's working. Thank you so much.
