### ISSUE TITLE
Double-clicking on left sidebar playlists is weird?

### ISSUE THREAD

**Issue by Halloyo** [khanhas/spicetify-cli#180]
Hello, 

This issue I believe is related to the problem I described [here](https://github.com/khanhas/spicetify-cli/issues/179#issue-605924634). 

When you double-click on a playlist on the left sidebar, it displays a "playing" icon next to it. When I go on the playlist's page, the play/pause button shows "Pause", indicating the playlist is playing. However, when I go to click the "Pause" button, it acts as if I was playing another playlist and it reshuffles the playlist.

Here is a gif showing it:
https://gfycat.com/flimsyvigilantharrierhawk

(Also, I'm sorry for creating so many issues)

**Comment by khanhas** [comment]
My take on this is Spotify is testing new URI scheme for playlist. So contexts URIs are different when playlist is played from sidebar and when it is played from Playlist app.
I don't think anything I can do with this problem.
