### ISSUE TITLE
Clicked a button bottom right now its not looking good

### ISSUE THREAD

**Issue by xXMedRedXx** [khanhas/spicetify-cli#181]
![image](https://user-images.githubusercontent.com/63717981/80667343-47cbc500-8ae2-11ea-8977-f2736bdeeef8.png)
![image](https://user-images.githubusercontent.com/63717981/80667385-60d47600-8ae2-11ea-89c7-0d5b09ba122a.png)

**Comment by khanhas** [comment]
You're using WebPlayer.

**Comment by khanhas** [comment]
It's impossible to customise Web Player UI so I closed this issue.
