### ISSUE TITLE
Powershell Version Lesser than 3

### ISSUE THREAD

**Issue by Tutuforver** [khanhas/spicetify-cli#182]
My power shell's version is 3.0 But when I use the invoke command in power shell, it responds with "your powershell version is lesser than 3"

I have tried installing 4.5 and up, but the install wizard says I already have a higher version installed fro .net framework? 

Any advice?

**Comment by khanhas** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by Tutuforver** [comment]
Thanks, I will give it a go and update if it works. I am updating to windows 8.1 since 8 can’t use newer versions.
