### ISSUE TITLE
Stuck in minimal UI

### ISSUE THREAD

**Issue by Clinqk** [khanhas/spicetify-cli#184]
Why can't I switch back to the regular UI? (Or how do I?)

**Comment by khanhas** [comment]
1. Have you tried restart Spotify?
2. If you still stuck, open `%APPDATA%\Spotify\prefs` file, remove line `ui.experience_override`

**Comment by Clinqk** [comment]
Ah, thank you! Restarting didn't work but I deleted the line and everything is back to normal. I'm definitely not messing with that again.
