### ISSUE TITLE
Icons are squares from a flatpak installation

### ISSUE THREAD

**Issue by fourstepper** [khanhas/spicetify-cli#185]
![image](https://user-images.githubusercontent.com/49439044/81500127-45325200-92d0-11ea-8f91-921e4d879145.png)

Hello, after successfully applying my desired spicetify theme it appears that the icons that are supposed to be present are actually missing.

What could this be caused by? How can I debug this? Thanks

**Comment by khanhas** [comment]
Can you try with `SpicetifyDefault` theme to see if icon is missing in that theme? Because I don't want to debug someone else theme problem.

**Comment by fourstepper** [comment]
It's been a temporary issue. Sorry and thanks for the help
