### ISSUE TITLE
/usr/bin/jsHelper: not a file or directory???

### ISSUE THREAD

**Issue by katdanieltabs** [khanhas/spicetify-cli#186]
Hello! When I run `spicetify backup apply` I get this error:
```spicetify v0.9.9
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK                            
Preprocessing:
[ 29 / 30 ] stations         fatal open /usr/bin/jsHelper: no such file or directory
```

I've reinstalled Spotify and Spicetify multiple times but this error persists. 
I am on Ubuntu 18.04 LTS.

**Comment by khanhas** [comment]
I'm sorry for late reply.
Can you run `spicetify` with direct path to where it is?
I don't know how you could have spicetify binary file placed in `/usr/bin/`. It doesn't work that way because spicetify requires extra files locating in same `spicetify` executable place.
