### ISSUE TITLE
Issues with importing node_modules because of its dependencies

### ISSUE THREAD

**Issue by jonasthiesen** [khanhas/spicetify-cli#187]
It's nice to see that one of the new releases introduced the ability to use node_modules!

I'm experiencing some issues with *sub-dependencies* though. NPM packages without any dependencies work great, but the packages that themselves require packages seem to cause some issues.

An example of this could be the package "match-sorter", which is imported in the following way:
```js
import './node_modules/match-sorter/dist/match-sorter.esm.js'
```

Which causes this error from one of its dependencies:
```
Uncaught TypeError: Failed to resolve module specifier "@babel/runtime/helpers/esm/extends".
Relative references must start with either "/", "./", or "../".
```

The error message sounds like it doesn't appreciate that the package itself uses the "normal" way of importing node_modules (absolute instead of relative) 🤔 

Maybe I'm doing something completely wrong, in which case I'd be happy to contribute "pitfalls" to the docs, that might be of help to someone else.

I don't really have any experience with Go, so I'm not sure I can be of much help in that department, but I'd be happy to give it a go (hehe).

**Comment by khanhas** [comment]
I guess ESM distribution still need dependency link, in this case `@babel` package. And browser doesn't want to look into `node_modules` unless the dev prefixed `./` in front of dependency link.
Have you try `.umd.js` distribution? They are usually compiled with all dependencies and good to go in browser. Also use `.min.` version of distribution so browser load the package faster.
