### ISSUE TITLE
[macOS] Issue after recent Spotify client update

### ISSUE THREAD

**Issue by ciehanski** [khanhas/spicetify-cli#189]
After the most recent Spotify client update (1.1.32.618.gda5638a6) the client reverted back to the default styling. I attempted to rerun `spicetify update` but ran into this error:
```
spicetify v0.9.9
fatal open /Applications/Spotify.app/Contents/Resources/Apps/zlink/css/user.css: no such file or directory
```

**Comment by khanhas** [comment]
Reinstall and run `spicetify backup apply`
After any Spotify update, always run `spicetify backup apply`.
Optionally, make Spotify shortcut to run `spicetify auto` (instead of direct path to spotify executable), so that Spicetify can backup, apply when it needs to, automatically.

**Comment by ciehanski** [comment]
Wonderful, that did it! This might be useful to add to the documentation. Thanks!

**Comment by bbpoizon** [comment]
I'm having this exact issue. I reinstalled both spotify and Spicetify but I keep getting the same message after running spicetify apply

> Reinstall and run `spicetify backup apply`
> After any Spotify update, always run `spicetify backup apply`.
> Optionally, make Spotify shortcut to run `spicetify auto` (instead of direct path to spotify executable), so that Spicetify can backup, apply when it needs to, automatically.
