### ISSUE TITLE
Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini

### ISSUE THREAD

**Issue by TallGorilla** [khanhas/spicetify-cli#190]
The program returns this in windows 10... spotify installed from microsoft store
What should i do?

**Comment by khanhas** [comment]
Remove Windows Store, I guess. It will keep mirgrating for whatever you do if Windows Store is still up.

**Comment by TallGorilla** [comment]
Ok, Microsoft store spotify isnt supported, just migrate to the non microsoft store spotify.
