### ISSUE TITLE
Spotify is all black [Manjaro KDE; via flatpak]

### ISSUE THREAD

**Issue by Juniokoi** [khanhas/spicetify-cli#191]
![image](https://user-images.githubusercontent.com/53125029/82496455-23508080-9ac3-11ea-9df4-eb63aca412df.png)
Apparently there is no error when execute the commands to apply the theme.
I've just have deleted part of colors.ini to make the theme go black {it worked perfectly on windows}, not sure if this is what is causing the error.

**Comment by khanhas** [comment]
Can you not use `sudo` to run `spicetify`?

**Comment by quentincaffeino** [comment]
Same here, tried running `sudo spicetify apply`. After apply it runs immediately with no problems, but if I try running `spotify` or `spacetify restart` I get the same behavior with black screen.
My Spotify version is also coming from flatpak, version 1.1.26.501.
I don't think this is platform dependent then.

**Comment by khanhas** [comment]
1. Reinstall Spotify
2. Run these commands:
```bash
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
```

3. Then run:
```bash
spicetify backup apply
``` 
**Without `sudo`**

**Comment by quentincaffeino** [comment]
Ok, now it doesn't return black screen anymore. Thanks
