### ISSUE TITLE
Themes don't work

### ISSUE THREAD

**Issue by Project-Magenta** [khanhas/spicetify-cli#192]
I am getting this error:
Failed to load resource: net::ERR_FAILED
for zlink.app.spotify.com/css/user.css

**Comment by UnlimitedCookies** [comment]
I think it would be helpful if you would supply some more information.
What version are you using? Which theme did you try to load? (Maybe attach the theme for troubleshooting) What did you do to evoke these issues? (the commands you typed in beforehand) etc.

**Comment by Project-Magenta** [comment]
I tried to load Elementary theme from https://github.com/morpheusthewhite/spicetify-themes. I am using spicetify 0.9.9 and spotify 1.1.33

**Comment by Project-Magenta** [comment]
I used
`spicetify config current_theme Elementary`
`spicetify backup apply`

**Comment by khanhas** [comment]
Nothing is wrong with them theme
Can you just reinstall Spotify and run `spicetify backup apply`?
