### ISSUE TITLE
BOM: read C:\Users\jack\spicetify-cli: The handle is invalid.

### ISSUE THREAD

**Issue by jacc** [khanhas/spicetify-cli#193]
Tried running `spicetify backup apply`, and looking at a previous issue `C:\Users\jack\AppData\Roaming\Spotify` does exist. I'm using the Spotify from the website, not the Microsoft Store.

**Comment by jacc** [comment]
Alright, so after a few attempts, here's what I did (for anyone that might have the same issue)

I uninstalled spicetify-cli from my home folder, opened an admin PowerShell terminal, installed Chocolatey, installed spicetify-cli using Chocolatey, then set my prefs_path to `C:\Users\jack\AppData\Roaming\Spotify\prefs` and now it's working all good.

**Comment by Pukimaa** [comment]
Do you need to add it to Path?
