### ISSUE TITLE
Song cover images not appearing on WebNowPlaying

### ISSUE THREAD

**Issue by InterFelix** [khanhas/spicetify-cli#195]
The cover images of playing songs are sometimes not displayed in Rainmeter skins using WebNowPlaying. This happens with all the ones I tested and simultaneously, so when one doesn't show the cover image, all others also do not show it and vice versa.
This leads me to believe it's a problem on the Spicetify side of things.
Everything else works though, Song Progress, Title and Artist continue working, even over a song switch.
This started with some songs some times (but not in any recognizable pattern) and became more prevalent, to the point where I haven't seen a song cover in the last five hours. This also happens on two machines.

**Comment by khanhas** [comment]
I haven't experienced any of this problem. All of track information is fetched successfully.
Can you reinstall Spotify then run `spicetify backup apply`?

**Comment by InterFelix** [comment]
I will try this. But since the problems occur on two machines at once, I don't think it will solve the problem.

**Comment by InterFelix** [comment]
No effect. Covers are not shown. I have multiple skins that use WebNowPlaying with Spotify running at the same time.

**Comment by khanhas** [comment]
Nothing is wrong on my side, Spotify got metadata correctly and Webnowplaying still downloaded cover succesfully. Sorry, couldn't help you.

**Comment by stevehoek** [comment]
@InterFelix what version of Spotify?  I'm seeing issues as of 1.1.34

**Comment by InterFelix** [comment]
I'm on 1.1.34.694, so yes. Not seen a song cover in days, btw.
I updated Spotify on both my laptop and desktop when I installed spicetify, I think.

**Comment by InterFelix** [comment]
@khanhas did you try on the latest version of Spotify?

**Comment by khanhas** [comment]
I did. I'm always on the latest

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/83707118-9548ce00-a65c-11ea-9ec4-bad02a1b3455.png)

**Comment by khanhas** [comment]
Can you guys do re-install Spotify and run `spicetify backup apply`?
Then if problem still persists, open up devtool, navigate to Console and run `Spicetify.Player.data.track.metadata` to see if it returns any track metadata.

**Comment by stevehoek** [comment]
@khanhas  what Rainmeter skin are you using as a player?

**Comment by stevehoek** [comment]
> `Spicetify.Player.data.track.metadata` to see if it returns any track metadata.

That API returns a valid object, but I am seeing errors in the console about the webnowplaying socket connection refused.

```
webnowplaying.js:106 WebSocket connection to 'ws://127.0.0.1:8974/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
init @ webnowplaying.js:106
Spicetify.Player.data.track.metadata
{album_artist_name: "Pearl Jam", album_disc_count: "1", album_disc_number: "1", album_title: "No Code", album_track_count: "13", …}
webnowplaying.js:106 WebSocket connection to 'ws://127.0.0.1:8974/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

```

**Comment by khanhas** [comment]
@stevehoek Do you use WebNowPlaying Companion extension in any of your browser?

**Comment by stevehoek** [comment]
@khanhas yes I do... I just disabled it, and things are working again!
