### ISSUE TITLE
Themes aren't working as they should!

### ISSUE THREAD

**Issue by RevzIsClean** [khanhas/spicetify-cli#196]
So, when I restore to the default spotify theme, the text on the left shows up as normal. When I put a theme on, the text disappears. Idk if this is due to the transparent thing I needed to add to the .exe for one of the themes I was trying, but this is an annoying problem. If I missed something, please dont ridicule me, I have a minuscule amount of understanding for the computer sciences, Thank You! - RevzIsClean

My Screenshot:

![unknown](https://user-images.githubusercontent.com/65987096/82962978-b2600b80-9f8f-11ea-9f11-fb53c30b7d5e.png)

Desired Outcome:

![68747470733a2f2f692e696d6775722e636f6d2f3058426f6a76382e6a7067](https://user-images.githubusercontent.com/65987096/82962988-b7bd5600-9f8f-11ea-8bd0-9825d0021855.png)

**Comment by khanhas** [comment]
I believed you have tried Dribbblish theme at some point. Dribbblish theme requires an extension called dribbbish.js and you didn't turn it off when you switched to another theme.
Now run:
```
spicetify config extensions dribbblish.js-
spicetify apply
```

**Comment by RevzIsClean** [comment]
Thank you so much! Yes that's exactly what happened.
