### ISSUE TITLE
Spicetify doesn't launch at all

### ISSUE THREAD

**Issue by maaaryo** [khanhas/spicetify-cli#197]
As the title says, when I type 'spicetify' into my terminal, it just spurs out "bash: spicetify: command not found"

**Comment by khanhas** [comment]
How do you install Spicetify?

**Comment by maaaryo** [comment]
git clone https://github.com/khanhas/spicetify-cli.git

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-and-macos
