### ISSUE TITLE
./spicetify apply has no effect (still vanilla spotify)

### ISSUE THREAD

**Issue by Eddi2015** [khanhas/spicetify-cli#2]
I followed the instructions and first ran just ./spicetify to generate the config and then ./spicetify backup, which successfully created a backup. Then I ran ./spicetify apply, which just launched Spotify and said something like 'successfull' in the terminal. Sadly the Spotify client still looks the same. Am I missing something? I am using the latest version (0.3) on Linux (Manjaro).

**Comment by khanhas** [comment]
Thanks you for your issue report,
I just pinned down that the problem might come from "prefs" file location isn't found.
So I added a field in config file for user to manually find and set it. 
But before doing manually, please
- Download v0.4.0
- Run `spicetify` one time to see if it throws any error
- If it shows `success Config is updated` then you are good to go.
- Run `spicetify clear backup apply` and enjoy.

If it throws
`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini`
- Run this command in your home directory:
```bash
find | grep "spotify/prefs$"
```
to find then add its full path to `prefs_path` field in config.

**Comment by Eddi2015** [comment]
I followed your instructions, but still potify wasn't changed. Spotify version: 1.0.94.262
Also your command `spicetify clear backup apply` gave me this error: ```
Before clearing backup, make sure you have restored or re-installed Spotify to original state. Continue? [y/N]: y
open /home/eddi-g/.spicetify/Backup: no such file or directory
```
So I ran every command (clear, backup, apply) one by one and that worked without errors. Sadly Spotify is still vanilla. It said the config was updated successfully.

**Comment by Eddi2015** [comment]
`find | grep "spotify/prefs$"` returns nothing. A bit strange.

**Comment by khanhas** [comment]
How did you install Spotify? Via Snap right?

**Comment by Eddi2015** [comment]
As I am running Manjaro I installed it via the pacman gui. I assume it was installed through an AUR, but I'm not sure. Maybe it's already in the official repos.

**Comment by khanhas** [comment]
Ok, the problem is not `prefs` file
It could be lack of write permission in Spotify location.
Can you run this version both normally and with `sudo`? See what error it will throw:

https://github.com/khanhas/spicetify-cli/releases/download/untagged-21ea468361464941cc0d/spicetify-0.4.1-linux-amd64.tar.gz

**Comment by Eddi2015** [comment]
Link to the Spotify AUR I use: https://aur.archlinux.org/packages/spotify

Your link to v0.4.1 is dead btw.

running sudo ./spicetify clear returns this:

```
error Could not detect "prefs" file location.
success Default config.ini generated.
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini
```

The thing is I can't find out my prefs location. As I wrote above:

> `find | grep "spotify/prefs$"` returns nothing. A bit strange.

**Comment by khanhas** [comment]
[spicetify_0.4.1_linux.zip](https://github.com/khanhas/spicetify-cli/files/2717132/spicetify_0.4.1_linux.zip)

Can you search prefs file with command above in wider range, outside of your home directory?

I'm installing Majaro right now so I will have better solution later

**Comment by Eddi2015** [comment]
Actually v0.4.1 also gives the same error. And I was searching the pref outside of my home dir. Now I've searched it in my home dir and it returns `./.config/spotify/prefs`
I didn't know that I had to search in my home dir.
Well actually /home/eddi-g/.config/spotify/prefs is already in my config. And it should be the same as what the command returned.

**Comment by khanhas** [comment]
Ah!
Originally, Spotify's Apps files aren't owned by user so just simple run:
```bash
sudo chown $USER /usr/share/spotify/Apps -R
```
to take ownership  and then you can run `spicetify apply` normally.

**Comment by Eddi2015** [comment]
So I ran your command without any issues. The funny thing is if I run ./spicetify apply (without sudo) it says 

```
spicetify v0.4.1
fatal remove /usr/share/spotify/Apps: permission denied

```

So I ran it with sudo which results in: 

`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini
`

But I already explained that my config already has /home/eddi-g/.config/spotify/prefs in it.
Any ideas?

**Comment by khanhas** [comment]
Yeah you don't need to run `spicetify` with `sudo` anymore. I will investigate its behaviour with sudo later.
chown was last command I tried and got it working so I thought it was enough.
Actually, only this one is enough:
```bash
sudo chmod 777 /usr/share/spotify/ -R
```

**Comment by Eddi2015** [comment]
Sadly that doesn't help me. I still get this problem: 

> So I ran your command without any issues. The funny thing is if I run ./spicetify apply (without sudo) it says
> 
> ```
> spicetify v0.4.1
> fatal remove /usr/share/spotify/Apps: permission denied
> ```

Also my Spotify interface is now blank and has no ui at all. I might need to reinstall it.

**Comment by khanhas** [comment]
- reinstall
- `sudo chmod 777 /usr/share/spotify/ -R`
- `spicetify backup apply`

**Comment by Eddi2015** [comment]
It worked! Thank you so much! The next thing would be to port over the 'normal' Spicetify theme to here.

**Comment by Eddi2015** [comment]
closed as fixed :)

**Comment by oubaycodes** [comment]
I've been having this issue after try to use spicetify on aur spotify client on arch linux, and how i fixed it was by changing the config-xpui.ini file's spotify app field to /opt/spotify
