### ISSUE TITLE
Weird now-playing cover art behavior

### ISSUE THREAD

**Issue by shuhu3** [khanhas/spicetify-cli#20]
I recorded the behavior here.
https://gfycat.com/fairpopularimago

There is a horizontal section in the middle of the cover image that:

- doesn't show the menu when right clicked
- confines the enlarge button (only shows if I hover on the top or bottom part of the cover image) into the section

Clicking the top/bottom part of the section does not do anything. 

I'm pretty sure the issue is within user.css but I'm not familiar with the code. Thanks for your time.

**Comment by khanhas** [comment]
I made some changes in css file to fix this bug.
The changes are insignificant so I will update it in spicetify-cli package later.
Right now, you can:
1. Copy fixed css file content: https://raw.githubusercontent.com/khanhas/spicetify-cli/master/Themes/SpicetifyDefault/user.css
2. Run `spicetify path css` to get theme's css file path and Open that file in your text editor.
3. Replace your css file content with just copied css.
4. Save and run `spicetify update`. Restart your Spotify client.

**Comment by shuhu3** [comment]
> I made some changes in css file to fix this bug.
> The changes are insignificant so I will update it in spicetify-cli package later.
> Right now, you can:
> 
> 1. Copy fixed css file content: https://raw.githubusercontent.com/khanhas/spicetify-cli/master/Themes/SpicetifyDefault/user.css
> 2. Run `spicetify path css` to get theme's css file path and Open that file in your text editor.
> 3. Replace your css file content with just copied css.
> 4. Save and run `spicetify update`. Restart your Spotify client.

Everything works perfectly now. Thank you!
