### ISSUE TITLE
webNowPlaying not working as of Spotify Desktop 1.1.34.694

### ISSUE THREAD

**Issue by stevehoek** [khanhas/spicetify-cli#201]
Updated to latest Spotify desktop app on Windows
Ran 'spicetify backup apply;
No longer see my Rainmeter gadget "Spotify Control" on the desktop, and see errors in the Rainmeter log "Web Side Error:Error updating ALBUM for Spotify Desktop" (and many others for other metadata fields).  Errors keep filing the log.

I've opened the Chrome dev tools on Spotify and see the webNowPlaying.js is integrated

**Comment by khanhas** [comment]
Do you install WebNowPlaying Companion extension/plugin in any browser?
