### ISSUE TITLE
Spotify latest update no longer installing under roaming 

### ISSUE THREAD

**Issue by Vmite1** [khanhas/spicetify-cli#202]
Basically I just installed spicetify on my laptop and now doing it for my main PC when I ran into a problem involving the directory which Spotify is now installing its self under.`spicetify backup apply enable-devtool`  When I put this in windows Powershell  it comes up with 

> \AppData\Roaming\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.

When I checked the file location there was completely noting in the Spotify folder in roaming like my laptop has.

**Comment by khanhas** [comment]
Your spotify just migrated to Windows Store Spotify. Please uninstall current Spotify completely and go to Spotify website to download proper installer.

**Comment by Vmite1** [comment]
Didn't work there is a folder in roaming with the name Spotify put nothing is inside it.

**Comment by khanhas** [comment]
Did you uninstall Windows Store Spotify?

**Comment by Vmite1** [comment]
I fully uninstalled the app and checked Microsoft store and it's not installed and signed out and it still didn't appear in roaming.

**Comment by khanhas** [comment]
I have no idea. Normal spotify always be installed in that location so I doubt you just, some how, installed Windows Store Spotify again.
Not spicetify problem.
