### ISSUE TITLE
like #181 - no colors, only images visible after applying

### ISSUE THREAD

**Issue by Pawiczekk** [khanhas/spicetify-cli#203]
Please explain what do you mean by Web Player UI and how is this supposed to work on windows, what to do to disable web ui(?), anything. I am using a cleanly installed client from https://www.spotify.com/us/download/windows/ version 1.1.34.694.gac68a2b3-a, spicetify v. 0.9.9.
Devtools console shows that https://zlink.app.spotify.com/css/user.css (referenced in almost all extracted .html files) is failing to load, and css variable definitions are nowhere to be seen, but for example html has a background-color of `var(--modspotify_sidebar_and_player_bg);`.
Setting replace_colors in config to 0 makes the window render properly, but also blocks customization, error about user.css persists.
It also seems that colors.ini css isn't injected - default theme has a `--bar-height: 120px;` definition in the `:root` pseudo-class which isn't there in devtools.

**Comment by khanhas** [comment]
If you can provide some screenshot, that would be better for me to see what's going on.

**Comment by Pawiczekk** [comment]
![image](https://user-images.githubusercontent.com/13506050/83974349-06061980-a8ed-11ea-8cb5-3eab92bfc058.png)

**Comment by Pawiczekk** [comment]
I should also mention that this isn't happening only in the home screen but in every tab (search, settings, etc) in the app

**Comment by khanhas** [comment]
Can I see your Spicetify config file?

**Comment by Pawiczekk** [comment]
[https://pastebin.com/5mwxsa6Q](url)

**Comment by khanhas** [comment]
Oh you are forced by Spotify to use new UI. Sorry I didn't notice that earlier. Open
`%appdata%\Spotify\prefs` file and remove `ui.experience_override` line.

If it still doesn't work: 
1. Run `spicetify restore`
2. Go to `%appdata%\Spotify\Apps` and delete `xpui.spa` file
3. Run `spicetify backup apply` then you should be fine.

**Comment by Pawiczekk** [comment]
That line doesn't exist in this file, and without xpui spotify is entirely blank, in devtools the html has empty `<head>` and `<body>`. I also found out that manually adding all variables from colors.ini of a theme to Apps/xpui/xpui.css at the top in a `body` selector actually makes spotify use the theme's colors, but this doesn't work for css since spotify has obfuscated class names (which I guess confirms that this is the new UI). Are there any other options to change to the old UI?

**Comment by khanhas** [comment]
How about in prefs file, add `ui.experience_override=false`.

**Comment by Pawiczekk** [comment]
I tried, the line gets automatically deleted when spotify starts.

**Comment by khanhas** [comment]
Try sign out, delete `prefs` file and `Users` folder. Log in again.

**Comment by Pawiczekk** [comment]
Custom colors and css are injected on the login screen, but after logging in it's still the new ui, `ui.experience_override` doesn't exist in the new prefs, it's still getting removed when I add it.

**Comment by Poopooracoocoo** [comment]
Spotify updated itself today and now I'm getting the same issues as @Pawiczekk :((((((

**Comment by khanhas** [comment]
Will be fixed in next version.
