### ISSUE TITLE
Spotify still has a default look yet has no errors installing spicetify

### ISSUE THREAD

**Issue by Midnyte13** [khanhas/spicetify-cli#204]
As said in the title I get the message "success Spotify is spiced up!" and Spotify restarts to no avail and still has a vanilla look.

**Comment by khanhas** [comment]
`spicetify --help`
`spicetify --help config`

**Comment by Midnyte13** [comment]
Do you want me to post the config?

**Comment by khanhas** [comment]
If you read the help text and change config yourself, that would be great.

**Comment by Midnyte13** [comment]
Thanks so much! it seems inject_css and replace_colors were both set to 0
