### ISSUE TITLE
Changing Spicetify Config Folder MacOS

### ISSUE THREAD

**Issue by jakebox** [khanhas/spicetify-cli#205]
It would be a nice feature to be able to relocate the config folder, currently it sits visible in the home folder. Or, alternatively, maybe making the folder still there but hidden by default? Seems like few other similar projects leave such folders visible and in the home folder.

**Comment by khanhas** [comment]
Set environment variable `SPICETIFY_CONFIG` to location you want

**Comment by jakebox** [comment]
That worked perfectly, thank you.
