### ISSUE TITLE
Issue: Can't find ini file

### ISSUE THREAD

**Issue by Glazzy12** [khanhas/spicetify-cli#206]
hello i was trying to download Spicetify and i can't find the config.ini file but its not here is there any tips that i can use to get it 
![Capture](https://user-images.githubusercontent.com/53692198/83935522-3d4ebc00-a76f-11ea-92dd-3158d700e847.PNG)

**Comment by khanhas** [comment]
`spicetify -c` to find out where your config file is.

**Comment by Glazzy12** [comment]
i don't understand

**Comment by khanhas** [comment]
You know this is a commandline program right?
You run that command in terminal of your choice. Since you on Windows, run it with Powershell.
