### ISSUE TITLE
scroll lag only on home tab

### ISSUE THREAD

**Issue by bibedice** [khanhas/spicetify-cli#207]
ok, so after using spicetify, when i'm scrolling on the home tab it feels laggy, but when i'm on another tab it's smooth like normal. I've tried enabling and disabling the hardware acceleration but nothing changed, what should i do? or is it normal?

**Comment by khanhas** [comment]
Depends on what theme do you use. If it heavily uses drop shadow effect, custom fonts or unoptimized CSS rules, it might slows rendering process down.
Not a problem/issue.

**Comment by kk-spartans** [comment]
I have the exact same problem, only on the home tab, but it happens even when I'm not using any extensions. Sorry if i posted this 4 and a half years late.
