### ISSUE TITLE
Spicetify doesnt works on my Pc

### ISSUE THREAD

**Issue by Timbreaken** [khanhas/spicetify-cli#208]
Today I have install Spicetify and Spotiplayer.
Spotiplayer doesnt show my the cover of every song and I can only use the playbutton.
A Discord user tell me, that I shoud look in the Spicetify settings, but I cant open it...
I had re-install it and it doesnt works to
can someone help me?
btw sorry for my bad english

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user
Follow all these steps

**Comment by Timbreaken** [comment]
It still doesn't work :(

**Comment by khanhas** [comment]
Do you use WebNowPlaying Companion extension in any of your browser?
