### ISSUE TITLE
PowerShell error locating Spotify "prefs file"

### ISSUE THREAD

**Issue by Earth-kun** [khanhas/spicetify-cli#210]
When I'm trying to write the PowerShell commands after writing "spicetify backup apply", I will get an error message saying... Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini. Kinda new to this and I couldn't find a solution to this.

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/FAQ#1-cannot-find-pref_file

**Comment by Earth-kun** [comment]
completely missed that. Thank you so much for the help :)

**Comment by AbhayAysola** [comment]
I used scoop to install spotify and the prefs file is still gone. I can't even find the Spotify App directory.
