### ISSUE TITLE
I reinstalled several times and couldn't fix this and i don't know css.

### ISSUE THREAD

**Issue by melihapaydin** [khanhas/spicetify-cli#213]
![spicetifymyissue](https://user-images.githubusercontent.com/54594800/84571960-8a4e1600-ad9f-11ea-9aaf-56df82f29bd4.JPG)

Rainmeter version 4.3.1 spicetify version 1.7.7

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user
