### ISSUE TITLE
Problem with Flatpak

### ISSUE THREAD

**Issue by CramMK** [khanhas/spicetify-cli#214]
Installed it according to https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-flatpak, but after setting I still get an error: 

`aincrad ➜ ~  ls ~/.var/app/com.spotify.Client/config/spotify/prefs
/home/marc/.var/app/com.spotify.Client/config/spotify/prefs`
`aincrad ➜ ~  ./spicetify-cli/spicetify apply                      
spicetify v0.9.9
error ~/.var/app/com.spotify.Client/config/spotify/prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.`

/home/marc/.config/spicetify/config.ini:
` 27 prefs_path       = ~/.var/app/com.spotify.Client/config/spotify/prefs `

The pref_path is the corrent one.

**Comment by CramMK** [comment]
aincrad ➜ ~  find | grep "spotify/prefs$" 
./.var/app/com.spotify.Client/config/spotify/prefs

**Comment by khanhas** [comment]
Can you expand the `~` in prefs_path`

**Comment by CramMK** [comment]
Okay I tried it with `.`, rather with `~` and that seems to work for some reason. I'm closing the issue, thank you

**Comment by khanhas** [comment]
No, please expand it to your home directory
