### ISSUE TITLE
Separate Color Scheme and themes

### ISSUE THREAD

**Issue by morpheusthewhite** [khanhas/spicetify-cli#215]
I think it would be much powerful to have the possibility to choose indipendently between color schemes and theme.
What I mean is this: currently, once selected a Theme, you can later choose one of its color schemes, but that is somehow limiting because if there is another colorscheme which I want to put on a certain theme I cannot do it in an automated way, and this is also somehow redundant (you can also see it on the `spicetify-themes` repository, spefically in your Dribbblish theme, where some of the previous pr were just meant to introduce color scheme which are already present in other themes (and this may probably go on forever)).
So what about separating them?

Thanks as always for you work

**Comment by khanhas** [comment]
I honestly don't know how to deal with that case. I don't expect colors from one theme to fit perfectly on another theme. Even if they do, copying and pasting from file to file isn't that difficult and complicated.
