### ISSUE TITLE
New interface disables spicetify integration

### ISSUE THREAD

**Issue by ToasterDEV** [khanhas/spicetify-cli#216]
Hey there!
I'm not sure how far has this new interface has spreaded out, but it seems it has changed the way in which hooks are handled within Electron.

Trying to apply spicetify again appears as successful, but no changes are applied to the app so far. The only solution I've found is to reinstall Spotify and then reapply the patch.

I'll attach a screenshot of how this new UI looks, just tell me if there's anything I can do to help debug. ;)
![image](https://user-images.githubusercontent.com/5206262/85253927-c2e79280-b424-11ea-82c8-6d5307ae674d.png)

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/issues/203
Try these ways here.
If they don't help, I dont know.

**Comment by ToasterDEV** [comment]
> Oh you are forced by Spotify to use new UI. Sorry I didn't notice that earlier. Open
> `%appdata%\Spotify\prefs` file and remove `ui.experience_override` line.


This solution worked for me, and it seems that I get an option to voluntarily opt in with a button in the lower pane consistently.

I'll attach a screen snip of the icon (Highlighted in yellow) as it appears on my copy.

![image](https://user-images.githubusercontent.com/5206262/85366306-b169bd80-b4ec-11ea-8139-546c84ff08ad.png)

Given this is a known issue, is there any way I could help to fix it?

**Comment by Poopooracoocoo** [comment]
Should we follow BlockTheSpot and install an older version and block updates or something?

**Comment by khanhas** [comment]
Up to you. If you do use BlockTheSpot, you don't have to upgrade Spicetify from now on.
Personally, I would never recommend that on this project and I don't to associate with BlockTheSpot or any Spotify ads blocker in any form. It's completely against TOS and it hurts Spotify's and artists' revenue.

**Comment by Poopooracoocoo** [comment]
@khanhas What I meant was did you want to do what BlockTheSpot is doing in terms of using an old version? I wasn't trying to suggest using BlockTheSpot.

**Comment by khanhas** [comment]
Will be fixed in next version.
