### ISSUE TITLE
New Spicetify version changes color template of custom themes

### ISSUE THREAD

**Issue by ZacheryMcLaughlin** [khanhas/spicetify-cli#217]
Hello, I updated from version 0.9.5 to 0.9.9 of Spicetify and noticed that the new version causes the custom themes that were linked to have reversed color schemes instead of what is intended. Is there any way to fix this?

For example, here is what the theme Vaporwave (color scheme: NewRetro) is supposed to look like and what it looks like for me.

![image](https://user-images.githubusercontent.com/44444169/85440211-ae99b780-b542-11ea-81c0-34e9128eaa22.png)

![image](https://user-images.githubusercontent.com/44444169/85440383-d2f59400-b542-11ea-8651-1f3652bdc4f4.png)

**Comment by khanhas** [comment]
What is your spotify version?

**Comment by ZacheryMcLaughlin** [comment]
Version: 1.1.35.458.g891674f3

**Comment by khanhas** [comment]
Can you reinstall Spotify and run 
```
spicetify backup apply
```

**Comment by ZacheryMcLaughlin** [comment]
I just tried that and it still has the inverted colors.

**Comment by ThaUnknown** [comment]
Same issue, spicetify-cli ver 0.9.9, spotify ver 1.1.35.458.g891674f3

**Comment by ThaUnknown** [comment]
this isn't an issue introduced by the latest version of spicetify-cli but by a recent spotify update, either the theme creator needs to fix the theme or spicetify-cli needs to change which color variables are assigned to what

**Comment by ThaUnknown** [comment]
Here is the theme and config that I'm currently using, I haven't seen many other people have this issue, so I really hope this helps

[files.zip](https://github.com/khanhas/spicetify-cli/files/4848465/files.zip)

**Comment by ThaUnknown** [comment]
![Untitled](https://user-images.githubusercontent.com/6506529/86065300-8690e380-ba6f-11ea-9ab3-e5903a1dd9b9.png)
dont really have a full screenshot of my old spotify, but this is the best i could get, old and new[bugged] side by side

**Comment by ZacheryMcLaughlin** [comment]
Yeah it doesn't seem like there's a fix for it. Something with spotify switching up the variables most likely

**Comment by ThaUnknown** [comment]
> Yeah it doesn't seem like there's a fix for it. Something with spotify switching up the variables most likely

i mean, it was a 7 second fix for me, replaced color a with "temp", color b with a and "temp" with b, but its more about solving this issue so it doesnt happen to other people/break old themes that are more complex and arent updated anymore

**Comment by khanhas** [comment]
@ZacheryMcLaughlin did you manage to fix it? I honestly don't know what could cause this.

**Comment by ZacheryMcLaughlin** [comment]
@khanhas Yeah I was able to figure it out. I followed the process that @ThaUnknown  posted earlier. You have to swap the main_bg and sidebar_and_player_bg color codes to get it correct. I posted a picture below to visualize. I don't know why they're swapped in the first place tho. 
![image](https://user-images.githubusercontent.com/44444169/86819867-1836bd00-c03d-11ea-9e11-338072f5911d.png)
