### ISSUE TITLE
This is not about the Spicetify issues that have been currently going on. Its a different issue i cant explain.

### ISSUE THREAD

**Issue by loganpman** [khanhas/spicetify-cli#218]
![image](https://user-images.githubusercontent.com/50798817/85671000-5a651380-b6b9-11ea-8b80-0164ff6b7cdd.png)

**Comment by khanhas** [comment]
1. Reinstall Spotify
2. https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user
