### ISSUE TITLE
config.ini was not created

### ISSUE THREAD

**Issue by Chaosflori25** [khanhas/spicetify-cli#22]
I tried installing it 3 times but every time it just did not create the config file, in normal mode as well as an Administrator.
![image](https://user-images.githubusercontent.com/44469989/58834008-906ccb00-8652-11e9-88be-7d6eeebdbfa8.png)

**Comment by khanhas** [comment]
Open `%appdata%\Spotify`, do you see a file named `prefs` in there?

**Comment by gordonthompson** [comment]
I had this because I had downloaded the Windows Store version of Spotify rather than the manual installer. Removing the windows store one and installing the one from the spotify website fixed the issue for me.

**Comment by khanhas** [comment]
Close due to inactivity.

**Comment by JiminBang** [comment]
The file named prefs is there, but what do we do with it?

**Comment by hobhobuk** [comment]
I have this issue but the reverse.. using offline installer but did once have the old app one on there.. cant get this working at all..
