### ISSUE TITLE
Running spicetify apply installs the windows version of spotify

### ISSUE THREAD

**Issue by AbhayAysola** [khanhas/spicetify-cli#221]
When I run ``spicetify apply`` there are no errors and the Spotify client starts up. But when I login, it's the default Spotify theme.

 So I decided to investigate and found that when I run ``spicetify apply`` and the Spotify client starts, there is only one Spotify app.
 But after logging in, I find the windows store version. 

I can't find a fix anywhere. I've tried uninstalling and reinstalling and my windows store app is disabled.

**Comment by khanhas** [comment]
None of what you just said makes sense or is possible. Either your Spotify is windows store version the whole time or it automatically migrate itself.

**Comment by AbhayAysola** [comment]
I don't think my Spotify is the windows store version because I installed it using scoop. I also deleted the migrator.exe in the scoop spotify folder.

**Comment by khanhas** [comment]
After you install it from Scoop, where does Spotify stay then?

**Comment by AbhayAysola** [comment]
It works after uninstalling and reinstalling and running the normal spotify as admin. Thanks for the help though.
