### ISSUE TITLE
Volume controls and fullscreen positioning issue with dribblish

### ISSUE THREAD

**Issue by matthaigh27** [khanhas/spicetify-cli#222]
![spicetify](https://user-images.githubusercontent.com/44395485/85921873-c1094d80-b8c2-11ea-9956-2b241fb560a5.png)
![spicetify2](https://user-images.githubusercontent.com/44395485/85921894-e39b6680-b8c2-11ea-81ab-5677adbc1234.png)
The first image is on my 1680x1050 screen and the second is on my 1080p screen. Not a huge issue but just thought I'd raise it to you. Theme is dribblish dracula.

**Comment by khanhas** [comment]
I wish I know how to fix that.
If any web dev has experience with flexbox and their properties, could you help me out on this?

**Comment by khanhas** [comment]
By the way, why you post the issue here? This is not Spicetify issue.
