### ISSUE TITLE
Unavailable track text not readable on default theme

### ISSUE THREAD

**Issue by 39digits** [khanhas/spicetify-cli#223]
**Versions**

- Spotify: 1.1.36.734.g8731c306
- Spicetify: 0.9.9
- Operating System:  MacOS and Windows 10

**The Issue**
The text colour for unavailable tracks is the same as the background on the default Spicetify theme making it look like there is no text.

This is true for most items on the row:

- Track number
- Track name
- Track length

It seems (according to the web interface) that it adds a new class to the track row to show it is unplayable `tracklist-row-unplayable`  

I've attached 2 images to better show what I mean.

**Spicetify Default Theme with unavailable track**
<img width="762" alt="spicetify_song_not_available" src="https://user-images.githubusercontent.com/719731/86132301-9bf12680-bade-11ea-9270-f380890cd46d.png">

**Spicetify Default Theme with unavailable track and row selected**
<img width="738" alt="spicetify_song_not_available_selected" src="https://user-images.githubusercontent.com/719731/86132317-a01d4400-bade-11ea-8592-7689194cc05b.png">

**Comment by khanhas** [comment]
Fixed, thank you. It will be available in next version.
