### ISSUE TITLE
Bookmark Not Working

### ISSUE THREAD

**Issue by marcocanto** [khanhas/spicetify-cli#224]
I have the bookmark and reddit custom apps enabled and while reddit works without a hitch I am not able to add anything to the bookmarks tab.

**Comment by khanhas** [comment]
There's new version of Bookmark extension in up coming Spicetify version. I will ping you when it's out.

**Comment by khanhas** [comment]
Please try spicetify v1.0.0

**Comment by carlocastoldi** [comment]
I may be a little too stupid, but I don't get where the bookmarks are now. Since it's no longer a custom_app there is no page associated to them, is there? :\

**Comment by khanhas** [comment]
It's in the top bar
![image](https://user-images.githubusercontent.com/26436809/86593757-2b17a600-bfd9-11ea-9c61-f61edcb48be9.png)

**Comment by carlocastoldi** [comment]
Yeah sorry, i forgot to mention that, even if i click on either "Current page", "This track" or "This trak with time", the drop down menu will be empty:
![](https://user-images.githubusercontent.com/34198340/86594275-069ada00-bf97-11ea-8948-3e7e24a0de8e.png)

Spotify versione: 1.1.26.501.gbe11e53b
OS: Linux Manjaro KDE

**Comment by khanhas** [comment]
Did you update new version?
This new menu is only available in spicetify v1.0.0

**Comment by carlocastoldi** [comment]
Mmmh nop, I did not

**Comment by ooeygooeypotato** [comment]
2026 and still not working sadly
