### ISSUE TITLE
Add "--transparent-window-controls" flag when using "spicetify auto" to launch Spotify

### ISSUE THREAD

**Issue by MaxJW** [khanhas/spicetify-cli#227]
If possible, could there be an option to add the flag `--transparent-window-controls` to the `spicetify auto` command, as I don't believe this is currently possible to enable when using the auto command.

Cheers

**Comment by khanhas** [comment]
Thank you. I will add an option in config file for users to specify additional flags to launch Spotify.

**Comment by khanhas** [comment]
Added in v1.0.0
