### ISSUE TITLE
Vertical mode option breaks FullAppDisplay extension

### ISSUE THREAD

**Issue by AbsurdUsername** [khanhas/spicetify-cli#228]
Turning on the vertical mode option with the new extension FullAppDisplay breaks all the settings menu. I can't go back to horizontal and the other options are unrensponsive/don't work. Playing around it a bit it seems when vertical mode is on the options are not aligned with what are you pointing with the mouse cursor.

**Comment by AbsurdUsername** [comment]
Oh and when turning off an option the tick stays there

**Comment by khanhas** [comment]
Can you provide your Spotify version?
Also please open DevTool, navigate to Console. Follow your steps to produce this problem again, then capture any error log in console window.

**Comment by AbsurdUsername** [comment]
Spotify version: 1.1.36.734.g8731c306
and this is what the console says when I click on vertical mode
![](https://user-images.githubusercontent.com/64277577/86602911-9f375700-bfa3-11ea-9c79-d39ee2b45541.png)

**Comment by khanhas** [comment]
Oh, please run `spicetify restore backup apply`

**Comment by AbsurdUsername** [comment]
Thanks! It works perfectly fine now. Thank you so much!
