### ISSUE TITLE
Spicetify rejects URI in getAblumArtColors if URI is valid track

### ISSUE THREAD

**Issue by camtheman256** [khanhas/spicetify-cli#229]
https://github.com/khanhas/spicetify-cli/blob/6907c82dfc114dde1e623eb6ff39b70e37c65650/jsHelper/spicetifyWrapper.js#L1381-L1384
I believe there should be a `!` in the if statement, in order for this method to work.

You can work around this bug by modifying the spicetifyWrapper.js file in the spicetify-cli/jsHelper folder prior to running `spicetify backup apply`.

**Comment by khanhas** [comment]
Good catch! Thank you.
Actually, I just discovered that color-extractor API can accept any URI (track, album, playlist, artist).

**Comment by khanhas** [comment]
Fixed in v1.0.2. Please run `spicetify restore backup apply` to apply the change.
