### ISSUE TITLE
how to uninstall spicetify itself on MacOS ? 

### ISSUE THREAD

**Issue by kanhangliew** [khanhas/spicetify-cli#23]
I need to arrange files in my computer and for that I have to uninstall spicetify first. But I can not find the match command to do that. 
Is there any way to uninstall spicetify on MacOS? 
Thank you.

**Comment by khanhas** [comment]
How did you install spicetify? Brew or manually extracting binary package?
brew has remove command:
```
brew remove spicetify-cli
brew cleanup
```

If you manually extracted it, just delete its folder and `~/spicetify_data` folder.

**Comment by kanhangliew** [comment]
Thank you.
And here occurs the second issue after I reinstalled spicetify. 
There is no such a folder named `Themes` in home directory, where it lies `color.ini` file by which I would use to adjust theme option in earlier version. 
That is to say, how to change theme in this version?

**Comment by kanhangliew** [comment]
Folders in home directory listed below
[https://i.loli.net/2019/06/04/5cf60e47060f114420.jpg](url)

**Comment by khanhas** [comment]
Run `spicetify path color` to know where the color file is
Same with css file: `spicetify path css`

**Comment by kanhangliew** [comment]
I followed your instruction but it seems it didn't work 
[terminal](https://i.loli.net/2019/06/04/5cf6715c99b4021365.png)

**Comment by khanhas** [comment]
Spicetify is at v0.8.1 currently. Update spicetify first.

**Comment by kanhangliew** [comment]
Well it's weird, I remember I did update it otherwise I would not know there is a latest version. 
Anyway, I tried to reinstall spicetify again. 
I used this command you told to uninstall spicetify:
```
brew remove spicetify-cli
brew cleanup
```
After that , I run:
```
brew install khanhas/tap/spicetify-cli
```
It appears that it has failed somehow?  
[what terminal shows](https://i.loli.net/2019/06/05/5cf71d333484556702.png)

**Comment by khanhas** [comment]
Try `brew upgrade khanhas/tap/spicetify-cli`
