### ISSUE TITLE
Right click menu in fullAppDisplay extension not working

### ISSUE THREAD

**Issue by damiponce** [khanhas/spicetify-cli#230]
When right clicking in the `fullAppDisplay.js` extension, the settings can **only be toggled once**, and clicking them again does nothing. They only register a click again seemingly at random, but I assume that's because of a triggered `EventListener`.

**Comment by khanhas** [comment]
Please run `spicetify restore backup apply`

**Comment by damiponce** [comment]
Now the whole extension is broken, clicking the upper icon doesn't open the screen. Not really sure why, because I even removed and loaded the extension twice.

**Comment by khanhas** [comment]
Can you reinstall Spotify and run `spicetify backup apply`? Back-upped data might not reliable to be applied again.
