### ISSUE TITLE
High CPU usage(70+) on 1.0.1 with no music playing

### ISSUE THREAD

**Issue by exadeci** [khanhas/spicetify-cli#231]
I did a restore and then applied:

```
[Setting]
current_theme        = google-spicetify
color_scheme         = gow
inject_css           = 1
replace_colors       = 1
overwrite_assets     = 0
spotify_path         = /Applications/Spotify.app/Contents/Resources
prefs_path           = /Users/gaetan/Library/Application Support/Spotify/prefs
spotify_launch_flags = 

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features        = 1
search_in_sidebar            = 0
extensions                   = shuffle+.js|trashbin.js|newRelease.js
custom_apps                  = 
home                         = 0
minimal_ui                   = 0
new_feedback_ui              = 0
fastUser_switching           = 0
lyric_force_no_sync          = 1
radio                        = 0
song_page                    = 0
tastebuds                    = 0
visualization_high_framerate = 0
lyric_always_show            = 1
made_for_you_hub             = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.36.734.g8731c306
```

This is on OSX: (CMD + Option + J)
![Screen Shot 2020-07-07 at 3 14 55 pm](https://user-images.githubusercontent.com/1394130/86717171-43350700-c065-11ea-8057-ff97d84e8d9c.png)

Disabling everything in the config doesn't fix the issue, only a `restore` actually fixes the issue and Spotify only uses 2% of CPU while playing music.

**Comment by khanhas** [comment]
Judging by error log, nothing stands out:
1. Failed to load resources: I guess you are either using Dribbblish or Google theme but didn't turn `overwrite_assets` config on. Please run:
```bash
spicetify config overwrite_assets 1
spicetify apply
```

2. Invalid Dns: I just changed Spotify telemetry domain to something useless. It not used to throw error like this before. I should take care of that later.

Can you try running `spicetify restore backup apply` once and see if it fixes?
If you can't restore, reinstall Spotify and run `spicetify backup apply`.

**Comment by exadeci** [comment]
Tried it all nothing fixed it.

**Comment by khanhas** [comment]
Problem identified. I will upload new version soon. Thank you!

**Comment by Zyrophr** [comment]
> Problem identified. I will upload new version soon. Thank you!

Good to know, I was going to make an issue too, it makes a MacBook Pro overheat to 98 degrees celsius, which is unusable 👍

**Comment by khanhas** [comment]
Please upgrade to spicetify v1.0.2. It should be fine now!

**Comment by Zyrophr** [comment]
> Please upgrade to spicetify v1.0.2 and run `spicetify restore backup apply` to apply the change. It should be fine now!

Fixed! Well done, that was pretty fast 👍

**Comment by exadeci** [comment]
Sweet! Thanks for the quick fixing!
