### ISSUE TITLE
open C:\Users\Name\.spicetify\AppX:

### ISSUE THREAD

**Issue by Archibold2** [khanhas/spicetify-cli#232]
I am using powershell and ran the command required to install spicetify. Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

When I ran the backup it came up with this. open C:\Users\Name.spicetify\AppX:
I played around a bit then found this fatal open C:\Users\Name\.spicetify\AppX\zlink\css\user.css: The system cannot find the path specified.
Can I have any help on this please?
![spicetify](https://user-images.githubusercontent.com/67985687/86858430-89678600-c0b8-11ea-8571-1ce5859c64d0.PNG)

**Comment by vorichardjohn** [comment]
Had the same issue -- quick and dirty fix I did was to add a folder named "AppX" in at path C:\Users\Name.spicetify\
After that everything seems fine. Looks like a simple fix from the development side?

**Comment by khanhas** [comment]
Did you ever run
```
spicetify backup
```
?

**Comment by Archibold2** [comment]
I did this first but it came up with the error at the bottom C:\Users\Jacob\.spicetify\AppX 
I've just tried to do this again the backup is now working for some reason but it still cant find the path 
![fatalk](https://user-images.githubusercontent.com/67985687/86922538-b782af80-c124-11ea-922e-4fcf2ba47d6c.PNG)

**Comment by khanhas** [comment]
Backup then `spicetify apply`

**Comment by Archibold2** [comment]
![apply](https://user-images.githubusercontent.com/67985687/86943352-43550580-c13e-11ea-86cc-69d7f10de909.PNG)
Same thing cant find the AppX file

**Comment by khanhas** [comment]
Can you create AppX folder as in the path then try again

**Comment by khanhas** [comment]
Also, uninstall Windows Store Spotify and install normal Spotify from installer if you can.

**Comment by Archibold2** [comment]
Ok I created the AppX file myself and it fixed the whole thing!
Thank you for being patient with me I appreicate it <3

**Comment by khanhas** [comment]
It's actually my fault though. I forgot to create `AppX` folder for user.

**Comment by paapoh** [comment]
I had the same issue. I ran "spicetify restore clear" and then ran "spicetify backup" and "spicetify apply" by themselves. That seemed to fix the problem and didn't say anything about AppX. 
Installed to windows store version with ease.
