### ISSUE TITLE
error Theme "=" not found

### ISSUE THREAD

**Issue by ledleledle** [khanhas/spicetify-cli#236]
I'm running in Ubuntu 18.04. After installing spicetify, i run <code> spicetify backup apply enable-devtool</code> then return error <code>error Theme "=" not found</code>. Same error appear when i try to change the theme too.
Here the <code>config.ini</code> file :
```
[Setting]  
spotify_launch_flags =

spotify_path         = /usr/share/spotify/

prefs_path           = /home/sweet/.config/spotify/prefs
current_theme        = =
color_scheme         =
inject_css           = 1
replace_colors       = 1
overwrite_assets     = 0
...
```

I tried to change <code>current_theme</code> value and apply theme, its worked.

**Comment by khanhas** [comment]
So what's the issue?
