### ISSUE TITLE
spicetify not working when closing out of spotify

### ISSUE THREAD

**Issue by AkumiAQ** [khanhas/spicetify-cli#237]
Whenever I close out of spotify or restart my computer. my spicetify theme is not applied anymore. is there a fix for this?

**Comment by khanhas** [comment]
Are you using Windows Store Spotify?

**Comment by AkumiAQ** [comment]
> Are you using Windows Store Spotify?

Yeah I am. Is that a part of the issue?

**Comment by khanhas** [comment]
I would highly recommend to uninstall Windows Store Spotify and install normal Spotify with installer from its website.
But you still can make it work by making a Spicetify shortcut and let it run `auto` command:
```
%appdata%\spicetify-cli\spicetify.exe auto
```

![image](https://user-images.githubusercontent.com/26436809/87251774-88b46280-c4b1-11ea-84db-3ce12e0f4340.png)

**Comment by AkumiAQ** [comment]
If I download the non windows store version spotify should my theme still be applied after I close it out?

**Comment by khanhas** [comment]
It will because normal Spotify modification is written directly.

It doesn't on Windows Store version because Microsoft doesn't allow to modify app assets. So I have to redirect modded app assets to somewhere else and make Spotify to launch with it. Run `spicetify auto` to correctly launch spotify with redirected location.

Also, delete the config file before you apply Spicetify on normal Spotify.
```powershell
rm $(spicetify -c)
spicetify
spicetify clear backup apply
```

**Comment by koidex** [comment]
am pretty sure i downloaded mine from the website itself not the windows store spotify, still having this issue

**Comment by errEstiak** [comment]
> I would highly recommend to uninstall Windows Store Spotify and install normal Spotify with installer from its website. But you still can make it work by making a Spicetify shortcut and let it run `auto` command:
> 
> ```
> %appdata%\spicetify-cli\spicetify.exe auto
> ```
> 
> ![image](https://user-images.githubusercontent.com/26436809/87251774-88b46280-c4b1-11ea-84db-3ce12e0f4340.png)

cna u tell the process how to enable this auto function for spotify

**Comment by alexcop73** [comment]
It didn't even work for me with the one on the website and I fixed it this way:
1.Uninstall Spotify from Windows as well as from the web.
2.Go to this link: https://spicetify.app/docs/getting-started/.
3.Open Power Shell as administrator and copy the first one and press enter, the same with the second one and wait for the process to finish.
4.Spotify will automatically open with Warketplace.
5.Point to the taskbar icon, left click and pin to taskbar.
