### ISSUE TITLE
Add update check whenever we use the cli.

### ISSUE THREAD

**Issue by AmrBinBashir** [khanhas/spicetify-cli#238]
I had a problem with one of themes not applying correctly because I was not on the latest version of the cli. 
It would be nice to have a notification to update the cli and maybe add a flag to update it self. `spicetify upgrade` 

Something like this.
![image](https://user-images.githubusercontent.com/48618675/87509085-1ab69980-c671-11ea-864d-8746a3774275.png)

**Comment by khanhas** [comment]
Thank you! I added `upgrade` command, it will be available in next version. However, I don't like the idea of checking version every spicetify run.

**Comment by Bluscream** [comment]
Thanks

**Comment by AmrBinBashir** [comment]
Thanks for the upgrade command. 
How about automatic version check as an option which is disabled by default ?

**Comment by khanhas** [comment]
That's great idea, thank you again!
