### ISSUE TITLE
[Enhancement] Global hotkeys

### ISSUE THREAD

**Issue by treacherousfiend** [khanhas/spicetify-cli#239]
Hi, I recently installed Spicetify, and was curious if maybe it would be possible (in app or in extension) to make Spotify's hotkeys global (i.e. have them work even if minimized)

I'm not too much of a programmer, so I'm not sure of the possibility of this working, but I do know there have been other attempts in the past with both Toastify (interesting but annoying as well as having large delays on hotkeys) as well as with AutoHotkey scripts (also having large delays)

I attempted to read the documentation for extensions, but didn't see anything relating to window focus, only adding buttons and so forth.

**Comment by khanhas** [comment]
Sorry, it's not possible.

**Comment by khanhas** [comment]
You could try PowerToys' Keyboard Manager. It has ability to globally remap shortcuts/keys to media keys (Play/Pause/Next)

**Comment by treacherousfiend** [comment]
Thats a shame, I assume its just that no matter what, in its current state spotify just doesn't support it aside from the default media keys.
I'll look into it, but i'm afraid its either going to force spotify into being focused or only work if its focused.

Thanks for the quick response. Aside from this inconvenience, I've really been enjoying Spicetify

**Comment by khanhas** [comment]
Remapped keys are global, I can change music while I'm in game.
  
![image](https://user-images.githubusercontent.com/26436809/87620590-4d8c8a80-c762-11ea-8bbc-7784095d8c34.png)

**Comment by treacherousfiend** [comment]
I guess I forgot to mention in my original issue, I have media keys, I was just hoping there was a way for me to change specifically spotify's volume without focusing the window

**Comment by Bluscream** [comment]
It's probably possible with AutoHotKey
