### ISSUE TITLE
Make more clear in documentation, that it needs to be run as root on Linux

### ISSUE THREAD

**Issue by dj-bauer** [khanhas/spicetify-cli#240]
I didn't find anywhere, that I need to run it as root with sudo.
I use Arch Linux.
Spicetify and spotify are installed via the AUR

**Comment by khanhas** [comment]
Simply because you don't need sudo to run spicetify!
If you don't have read/write permission on Spotify file (fatal error probably spitted it out loud in your commnad line), just give permission it to them.
https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur

**Comment by dj-bauer** [comment]
Ah, thanks. I didn't see that :)
