### ISSUE TITLE
config.ini not appearing

### ISSUE THREAD

**Issue by BlazeBurnBlade** [khanhas/spicetify-cli#242]
When I try to install spicetify it works fine, but when I run the command 'spicetify' try to get the config.ini to appear, all I get is "info Run "spicetify -h" for commands list." I've tried deleting Spicetify, uninstalling Spottily, I'm not sure what to do next.

**Comment by BlazeBurnBlade** [comment]
Nevermind I'm an idiot

**Comment by Bluscream** [comment]
same
