### ISSUE TITLE
Playlists are always empty.

### ISSUE THREAD

**Issue by devomaa** [khanhas/spicetify-cli#244]
Screenshot:
![image](https://user-images.githubusercontent.com/25231103/88190230-b4b6ad00-cc42-11ea-8fd3-75e0fd7a65cf.png)
Version:
uname -a: Linux no 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux
spicetify: 1.0.2
spotify: 1.1.10.546.ge08ef575

**Comment by MaxJW** [comment]
Can you view playlists without spicetify? Or in the web version of spotify? (https://open.spotify.com/)
As far as I'm aware, Spicetify should not affect the loading of playlists.

**Comment by khanhas** [comment]
Your spotify client is ancient. Can you upgrade to newer one using `spotify-dev` package?

**Comment by devomaa** [comment]
ok i'll try

**Comment by devomaa** [comment]
rip, now im getting "A firewall may be blocking Spotify ... (error code 30)"

**Comment by khanhas** [comment]
Are you using any system-wide adblocker or hosts file?

**Comment by devomaa** [comment]
nope :P

**Comment by mockingcode** [comment]
> Can you view playlists without spicetify? Or in the web version of spotify? (https://open.spotify.com/)
> As far as I'm aware, Spicetify should not affect the loading of playlists.
> How about albums as well? Can you not view songs anywhere?

Have you tried this suggestion yet?

**Comment by devomaa** [comment]
web/non-dev version works fine

**Comment by khanhas** [comment]
Is this still a problem, @devomaa ?

**Comment by devomaa** [comment]
lemme test.. yup, still a problem
