### ISSUE TITLE
The handle is invalid

### ISSUE THREAD

**Issue by LemonsareBad** [khanhas/spicetify-cli#245]
Whenever I run spicetify backup or apply I get the message
'BOM: read C:\User\MyUser\AppData\Roaming\Spotify\prefs: The handle is invalid'
Changing the file path and name don't seem to be a valid fix

**Comment by khanhas** [comment]
Can you check that path above to see if the file is actually there?

**Comment by aaaaaa1232131** [comment]
I checked the files, and even went as far as to removing and reinstalling spotify, even checked if it was caused by file corruptions as some handle errors are but nothing seems to be out of the ordinary

**Comment by khanhas** [comment]
1. Delete the prefs file
2. Restart Spotify, login, close Spotify
3. Try spicetify again

**Comment by LemonsareBad** [comment]
Alr, I'll try
