### ISSUE TITLE
Full App Display can't show song name starts with -

### ISSUE THREAD

**Issue by pnthach95** [khanhas/spicetify-cli#246]
Try to play these song in Full App Display, only show artist name and cover.

[- Star Divine - Finale](https://open.spotify.com/track/4KUT6tFek5IcxrD8TzUe7a?si=kBLV3ISpRCW6of7pzODOcg)
![Annotation 2020-07-24 143243](https://user-images.githubusercontent.com/31266357/88369987-64af2600-cdbb-11ea-8187-f3a8b67a37cd.png)

[-HEROIC ADVENT-](https://open.spotify.com/track/1wUsBNR7p92LWE8sTj6gTA?si=hWNuS6hOTVy7u0nVTKGbMw)
![image](https://user-images.githubusercontent.com/31266357/88370399-26663680-cdbc-11ea-87a7-2626b54d9c42.png)

Spotify version 1.1.37.690.g8f3b16fc
Spicetify version 1.0.2

**Comment by khanhas** [comment]
You probably turned "Trim title" option on.

**Comment by pnthach95** [comment]
You're right. Problem solved.

**Comment by khanhas** [comment]
Actually, current trimming text by hyphen is a bit greedy. I will fix it in next patch.
