### ISSUE TITLE
Powershell dont find spicetify 

### ISSUE THREAD

**Issue by Goran277** [khanhas/spicetify-cli#248]
I do all ways on powershell and gave every command but there is an error message that spicetify cant be find. 
plssss help

**Comment by givonwash** [comment]
Check your anti-virus software if you have some installed. I ran into the same issue and had to whitelist `spicetify.exe`. I did not have any problems after that.

**Comment by khanhas** [comment]
Before every command
1. Change directory to spicetify-cli
```
cd ~\spicetify-cli
```

2. Execute spicetify by calling `.\spicetify.exe` instead of `spicetify`. For example:
```
.\spicetify.exe backup apply
```

**Comment by Goran277** [comment]
OMG Thxxxxxxx
