### ISSUE TITLE
Full App Display: Right Click Menu check boxes cannot be unchecked

### ISSUE THREAD

**Issue by Akasiek** [khanhas/spicetify-cli#249]
So I recently started to use Dribbblish theme and my favorite use of it is with Full App Display Extension. There is only one issue. While checking all the options for the extension I check all the boxes in the right click menu. I didn't really liked the "vertical mode" so I wanted to change it back. Then I realized that I couldn't uncheck the box. Is there any way to change it in .js file? Or any other way?

I would like to suggest one thing for the Full App Display. There should be a "Like Song" (Heart) button. There also should be a full square artwork mode, because sometimes the artwork just looks weird with the rounded corners.

Edit: There also one thing that bugs me about the Full App Display. You cannot changed the volume without exiting the app. I was thinking about adding volume control with scroll on Full App Display. Just a suggestion

**Comment by khanhas** [comment]
1. Thank you for testing out Full App Display extension and I'm really glad that you like it.
2. You probably have old version Spicetify API file. Run `spicetify restore backup apply` to update then try deactivating it again.
3. Your ideas are valid but I just don't want to cluster it with things both visually and in code, I had to code mechanism behind every button. Alternatively, you can use `keyboaradShortcut.js` to do those things:
- <kbd>M</kbd> to Like/Unlike track
- <kbd>Ctrl</kbd><kbd>Up/Down</kbd> to control volume

**Comment by Akasiek** [comment]
Thank you for fast replay. Your solution helped with my problem without any problems.And about the keyboard shortcuts. I added the shortcut app and I works perfectly just like you said.

I really love your app. It makes Spotify 10 times better! Keep up the good work!
