### ISSUE TITLE
Windows Powershell issues - the term 'iwr' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Bradley-Webster** [khanhas/spicetify-cli#25]
Hi there!

I am attempting to install on Windows 7 with Powershell (Admin mode), what am I missing?

![iwrproblem](https://user-images.githubusercontent.com/39505775/59086047-e9cf4580-8943-11e9-8e74-82cf0071c340.PNG)

Is there an alternate way to install?

**Comment by khanhas** [comment]
Sorry, I shouldn't use alias for command
Try this:
```powershell
Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
```

**Comment by Bradley-Webster** [comment]
That was a quick response thanks!

Yep, installing without the Alias works as expected  ( I also had to download the latest powershell ).

I'll let you know if I run into any other issues.

Cheers,
Bradley.

**Comment by adidas1212** [comment]
I have the same problem but this soloution didn't work

**Comment by muhBilal** [comment]
i work using 

Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

**Comment by Ahmed3457** [comment]
> I have the same problem but this soloution didn't work

i don't remember commenting this, i don't even use Spotify

**Comment by KANEKIOP11** [comment]
> Sorry, I shouldn't use alias for command Try this:
> 
> ```powershell
> Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
> ```

i am trying this and it's not working this pops up 
![image](https://user-images.githubusercontent.com/75243661/235584499-3fe54658-9330-40d5-967e-9205ce295cf4.png)
