### ISSUE TITLE
[Windows 10] Window control color customization

### ISSUE THREAD

**Issue by softtama** [khanhas/spicetify-cli#250]
Is it possible to customize the window control (minimize, maximize, close) color?

So I can change from this:
![image](https://user-images.githubusercontent.com/7237624/89106027-9f1a6200-d450-11ea-974b-c8e00aa8527c.png)

to this:
![image](https://user-images.githubusercontent.com/7237624/89106035-b3f6f580-d450-11ea-9c1a-5e61767da7f0.png)

**Comment by khanhas** [comment]
Sorry, it's not possible.

**Comment by khanhas** [comment]
Alternatively, you try these:
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#hide-window-controls

**Comment by softtama** [comment]
> Sorry, it's not possible.

Care to explain, is it not possible because the feature currently doesn't exist, or is it not possible to implement the code?

**Comment by khanhas** [comment]
They're native window created by Spotify process and attached to browser window. They're not web component so modification is impossible.

**Comment by softtama** [comment]
> Alternatively, you try these:
> https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#hide-window-controls

Alright, but is it possible for you to implement the 'hide window controls' from this and add custom web component control to do window control job? Or is it really impossible at all?

Anyway I'm keeping this active in my Spotify app because I love it much! Just a few days ago I was thinking about light-themed Spotify and I'm glad I found yours!

**Comment by khanhas** [comment]
You're correct, I don't believe there is any way to close, maximize window from browser javascript.
