### ISSUE TITLE
Covers randomly change sizes? (Manjaro)

### ISSUE THREAD

**Issue by kittydragoness** [khanhas/spicetify-cli#251]
I have no idea why this happens but my install of spicetify made it so cover art gets bigger for no apparent reason. Is there a way to permanently make the covers smaller and make it so they don't get bigger?

Spicetify version: 1.0.2
Spotify version: 1.1.26.501.gbe11e53b

**Comment by kittydragoness** [comment]
![image](https://user-images.githubusercontent.com/62865881/89110868-382f8580-d41d-11ea-85f5-8409c60f700f.png)
![image](https://user-images.githubusercontent.com/62865881/89110884-775dd680-d41d-11ea-863f-21bfe080f828.png)
that's what it looks like

**Comment by khanhas** [comment]
Does it happen in unmodded Spotify?

**Comment by kittydragoness** [comment]
I reinstalled spotify through the AUR and it seems to be working now.
