### ISSUE TITLE
Spotify client doesn't open anymore after creating the backup

### ISSUE THREAD

**Issue by los2pollos** [khanhas/spicetify-cli#252]
I'm on Linux Mint and I've set permissions for all necessary directories. After launching "spicetify backup", the Backup files are not accessible and the directory "/usr/share/spotify" is not accessible anymore (padlocks icons appeared).

I can launch normal spotify only with sudo mode enabled.

What can I do?

**Comment by khanhas** [comment]
Can I see permissions of your Spotify folder?

**Comment by los2pollos** [comment]
Here they are: https://imgur.com/a/4ePnh4b

**Comment by los2pollos** [comment]
> Can I see permissions of your Spotify folder?

Nevermind, I adjusted all the necessary permissions. Thank you for your time
