### ISSUE TITLE
Buttons not working properly when windowed instead of full screen

### ISSUE THREAD

**Issue by Epic420Alex6911** [khanhas/spicetify-cli#254]
I noticed yesterday I could not pause/unpause music when I was running spicetify in windowed mode instead of full screen. 
![error](https://user-images.githubusercontent.com/62729521/90039402-6ca40c80-dc7b-11ea-834a-3cd863aedf64.PNG)
Also, when the window is shrunk labels can overlap each other. In this screenshot the song and favorite button work, but the play button does not. 

Oh I'm using the most recent version of spicetify, got everything running yesterday. The color palette Im using is ShadowCustom.

**Comment by khanhas** [comment]
This is problem of badly made theme, not Spicetify issue.
Please contact theme author to fix it or learn to use DevTool and CSS to fix it yourself.
