### ISSUE TITLE
Remove "UPGRADE" button on the top right of the UI

### ISSUE THREAD

**Issue by Titaniumtown** [khanhas/spicetify-cli#257]
So I have spotify free, and was wondering if there was some way to remove that pesky button telling you to upgrade, I already block ads, and I want it to be as clean-looking as possible.

**Comment by khanhas** [comment]
Sorry, please post customising question on Spectrum.

**Comment by Titaniumtown** [comment]
Oh ok. sorry

**Comment by ClemGlacee** [comment]
How do you block ads please?

**Comment by khanhas** [comment]
YOu cant'

**Comment by ClemGlacee** [comment]
I know that you can't with spicetify as it's not intended to do that
