### ISSUE TITLE
color.ini: colors don't apply

### ISSUE THREAD

**Issue by zjeffer** [khanhas/spicetify-cli#26]
This is my color.ini:

https://gist.githubusercontent.com/zjeffer/87bac260c1bf85d4d76d5d0589dc75b4/raw/dbd89794e6da76c5d64b9d9fe84370922959897b/gistfile1.txt

This is my user.css:

https://gist.githubusercontent.com/zjeffer/6858a48a200d237fc6d8b60c247306ac/raw/3c2b747466d208f45e906ee61cde03d4c5d86d0b/gistfile1.txt

For some reason it doesn't apply the color.ini colors, as if the file wasn't even there. Do I have to do something special to apply those colors?

**Comment by khanhas** [comment]
In color.inc, the section name should be `[Base]`

**Comment by zjeffer** [comment]
Thanks! But isn't it `color.ini`, not `color.inc`?
