### ISSUE TITLE
Freeing up space

### ISSUE THREAD

**Issue by mockingcode** [khanhas/spicetify-cli#267]
Recently installed `spicetify-cli` and I was wondering if it's okay to remove Go (I didn't had a Go installed). Correct me if I'm wrong but the only time Go was used was to compile the code or is there something else it is used for?

**Comment by khanhas** [comment]
Yup, you can remove Go. From version 1.1, if you don't want to break sweat compiling spicetify from source, just use ` spicetify upgrade` command to update using pre-built package.
