### ISSUE TITLE
Shuffle+ throws error and only adds one song to queue

### ISSUE THREAD

**Issue by jneplokh** [khanhas/spicetify-cli#269]
Today I tried using the Shuffle+ feature but it threw an error about a PUT request:

`Error: PUT request to sp://player/v2/main/queue failed with status code 409`

and only adds one song to the queue.

**Comment by khanhas** [comment]
What did you try to play?

**Comment by jneplokh** [comment]
I tried with a playlist of mine at first, but also tried with some Spotify-curated ones. Same error for all.

**Comment by khanhas** [comment]
No idea what happens in your client. What is your OS and is your spotify on latest version?
If you can provide more error info, that would be great. Just open Console, right click at a playlist, choose Play With Shuffle+and screenshot me all error it splits out.

**Comment by jneplokh** [comment]
Huh, strangely it started working again today. Not sure what happened. I'll update here with logs should the error occur again.

Closing the issue as it got resolved.

**Comment by Akyshnik** [comment]
Just had the exact same issue on Arch. Setting "Auto Schuffle" setting on is what fixed it.
