### ISSUE TITLE
WebNowPlaying extension didn't work

### ISSUE THREAD

**Issue by SaberAkiyama** [khanhas/spicetify-cli#270]
I've try install WebNowPlaying extension on Spicetify CLI using PowerShell like this:
```
spicetify config extensions webnowplaying.js 
```
I've found that extension didn't exist.
I don't know how users aren't work properly.

OS: Windows 10 Home 1909
Spotify version: 1.1.40
Spicetify CLI version: 1.1.0

**Comment by khanhas** [comment]
Save this file to your Extensions folder.
To know where the extensions folder is, run this in powershell:
```
explorer.exe ~\.spicetify\Extensions
```

**Comment by SaberAkiyama** [comment]
> Save this file to your Extensions folder.
> To know where the extensions folder is, run this in powershell:
> 
> ```
> explorer.exe ~\.spicetify\Extensions
> ```

Or this one is work
```
C:\Users\(Your user name)\.spicetify\Extensions
```
