### ISSUE TITLE
How to install manually

### ISSUE THREAD

**Issue by Bluscream** [khanhas/spicetify-cli#273]
Where do i get the files to update my chocolatey installation to 1.1.0? (win10)

**Comment by khanhas** [comment]
Uninstall spicetify package of chocolatey. Use powershell script in Installation wiki page

**Comment by Bluscream** [comment]
Why do you offer that if you dont keep it up to date or use it?

**Comment by khanhas** [comment]
I'm not maintainer of the package, I already sent out-of-date report but they didn't do anything.
From version 1.1, you just need to use commadn `upgrade` to upgrade, so you don't need package manager anymore.

**Comment by Bluscream** [comment]
Why is it in your wiki without any notice then? :(

**Comment by khanhas** [comment]
Do you still have a problem or not?
