### ISSUE TITLE
Where are bookmarks stored?

### ISSUE THREAD

**Issue by grastraa** [khanhas/spicetify-cli#274]
I'm suddenly having an issue similar to prior ones I've seen where the bookmark icon is no longer appearing. 
I'm also using the custom app as I find that view a useful function. It has previously worked along side the extension, but now only the custom app is showing up.

I've tried the recommendations in the other issue threads such as restoring backup and reapply, ensuring I'm on the latest release...

At this point I am about to try a full delete and reinstall of spotify and spicetify. 
Unsure where the current list of bookmarks is stored, but looking to make sure I can retain this list through this process.

**Comment by khanhas** [comment]
Oh no, if you already uninstall Spotify and reinstall it, bookmark list might has gone.

1. After a recent version, Bookmark extension is no long needed custom app to access bookmarks list. It just shows a popup with the list on its own. So make sure you are on latest Spicetify and remove bookmark from config file `custom_apps` field.

![image](https://user-images.githubusercontent.com/26436809/91709435-1cf39980-ebc6-11ea-8057-0505541448b1.png)


2. Bookmark list is stored in `localStorage`. It's a feature of browsers to store data locally, easy to write and access if webpage needs to store cookie, user info, state,... `localStorage` binded with other browser data and they were encrypted (or hashed or whatever, I do not know for sure). So you couldn't access it outside of browser. As I said, if you uninstalled the browser, the data is gone.

**Comment by grastraa** [comment]
I haven't uninstalled spotify yet as I was afraid exactly that would happen.

1. I actually prefer the custom app view with it's dedicated page instead always relying on on a small menu that requires a lot of scrolling. 

I'd actually love to see the New Releases extension custom app so I could easily browse it without feeling like I'm on a small mobile phone.

2. When you say `localStorage`, in my ignorance, I can only assume this means (for windows 10) somewhere within `appdata/local/google/chrome` perhaps? 

Can I locate the specific browser data and back it up usefully?

**Comment by khanhas** [comment]
1. I can't help you with that.
2. It might works like that but I'm not sure that data is still there.

**Comment by khanhas** [comment]
1. I can't help you with that.
2. It might works like that but I'm not sure that data is still there.
