### ISSUE TITLE
Playlist Icons Not Changing?

### ISSUE THREAD

**Issue by ByronLi8565** [khanhas/spicetify-cli#275]
I am using Spicetify with Dribblish theme. I changed one of my playlist's pictures, but it didn't update on the sidebar where the icons are displayed. When I relaunch, it gets even worse and doesn't even display the icon on the playlist page. When I check the web client, it is fine. Any idea what is the problem/how to fix?

**Comment by khanhas** [comment]
Open DevTool and screenshot error in Console

**Comment by ByronLi8565** [comment]
I'm so sorry, I don't know how to do that. This is a screenshot of how it looks right now. If you can tell me how to access DevTool, I can get that to you.
![image](https://user-images.githubusercontent.com/54540092/91789281-f50b3280-ebd3-11ea-92e6-f647df36005d.png)

**Comment by khanhas** [comment]
Can you try add a picture for pizza box playlist and see problem still persists?

**Comment by ByronLi8565** [comment]
Restarted computer and the icon shows up now. Thank you for your help.
