### ISSUE TITLE
I cant download it

### ISSUE THREAD

**Issue by hullololo** [khanhas/spicetify-cli#276]
when i download it,it fucks up spotifys UI then someone said to use spicetify-cli instead of the rmskin but then i messed that up too and when i retry by deleting all the fukes i get this error
![2020-09-02 (1)](https://user-images.githubusercontent.com/70656761/92014495-9c60a480-ed4f-11ea-83ea-f88b5e73a7e5.png)

**Comment by khanhas** [comment]
Try:
```
spicetify config spotify_path " "
spicetify backup apply enable-devtool
```

**Comment by hullololo** [comment]
I need the prefs path im assuming i do the same thing but where is the prefs path?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hullololo** [comment]
BOM: read C:\Users\maxbr\AppData\Roaming\Spotify: The handle is invalid.
PS C:\Users\maxbr>
i found the prefs path but now it gives me this

**Comment by hullololo** [comment]
i fixed the pref and spotify path but it says this :
open C:\Users\maxbr\AppData\Roaming\Spotify\Spotify.exe\Apps: The system cannot find the path specified.

**Comment by hullololo** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by hullololo** [comment]
THANK YOU SO FUCKING MUCH I LOVE YOU
