### ISSUE TITLE
Full App Display

### ISSUE THREAD

**Issue by schnensch0** [khanhas/spicetify-cli#277]
**A few things to improve the Full App Display extension:**

* Add an option to show the album the song is from
* Add an option to hide the artist
* Add an option to hide the song name
* Add an option to hide the album art

I love this extension and I think these things would make it even better. It'd look awesome with just the album art.

Thanks

**Comment by JulienMaille** [comment]
option to show album is already there (from my PR #260)
Not sure why you would hide stuff, can you elaborate?

**Comment by schnensch0** [comment]
Just to make it look cleaner, I use it as a kinda screensaver thingy when I'm listening to spotify

**Comment by khanhas** [comment]
Show album was already implemented and will be available in next version.
I don't use any use case for hiding title, artist or album art, and I don't want to overcrowd setting menu.
Extension code is open source and was written in extreme clarity that anyone can hack and add personal touch to it with ease. I'm happy to assist if you want to do so.
