### ISSUE TITLE
Themes apply but nothing changes

### ISSUE THREAD

**Issue by lkeya** [khanhas/spicetify-cli#278]
Hi,

I'm using spicetify on windows, not on the microsoft app, when I set it up everything seems to go fine but when I apply themes, it shows no error, yet nothing changes in the spotify UI.

![image](https://user-images.githubusercontent.com/61351254/92175207-be842080-ee3c-11ea-8173-dd16486ab028.png)

As you can see the theme is still "applied". I tried reinstalling spotify and spicetify, but it's still the same.

**Comment by khanhas** [comment]
Try again:
```
spicetify restore backup apply
```

**Comment by lkeya** [comment]
Still no success

![image](https://user-images.githubusercontent.com/61351254/92310650-b3520180-efb0-11ea-9df0-9979289313dd.png)

**Comment by Hedlosa** [comment]
I am also having this problem, any success?

**Comment by khanhas** [comment]
Did spicetify restart your Spotify after it finished apply command?

**Comment by Hedlosa** [comment]
no luck, I noticed that neither mine nor Ikeya's spotify has the spicetify default skin, as if it did not latch at all. In the config file the directory to the spotify.exe is correct, and it says in the powershell that it has connected and applyed, but nothing is being affected.

**Comment by khanhas** [comment]
Can I see your config file?

**Comment by Hedlosa** [comment]
[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
lyric_always_show            = 0
made_for_you_hub             = 0
search_in_sidebar            = 0
song_page                    = 0
visualization_high_framerate = 0
extensions                   = 
custom_apps                  = 
experimental_features        = 0
fastUser_switching           = 0
home                         = 0
lyric_force_no_sync          = 0
new_feedback_ui              = 0
radio                        = 0

[Setting]
inject_css              = 0
replace_colors          = 0
overwrite_assets        = 0
spotify_path            = C:\Users\Owner\AppData\Roaming\Spotify
prefs_path              = C:\Users\Owner\AppData\Roaming\Spotify\prefs
current_theme           = Aritim-Dark
color_scheme            = Base
spotify_launch_flags    = 
check_spicetify_upgrade = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.41.634.gc2c73ca7

**Comment by khanhas** [comment]
Are you sure that you have that theme "Aritim-Dark" in your `Themes` folder?

**Comment by khanhas** [comment]
Also you didn't enable `inject_css` or `change_colors`, of course you have original theme.

**Comment by khanhas** [comment]
Please read `spicetify -h` and `spicetify -h config`.

**Comment by Hedlosa** [comment]
I changed both inject_css and change_colors to 1 in the ini, and that worked, don't know how I did not spot that even as I was copy and pastig the code, but thank you for helping me, and hopefully this is OP's solution aswell

**Comment by lkeya** [comment]
Yep this was it ! I don't know why the values of inject_css and replace_colors were 0 though, anyways thank you !
