### ISSUE TITLE
Access is denied [install process on windows]

### ISSUE THREAD

**Issue by stefanvqm** [khanhas/spicetify-cli#279]
After downloading spicetify through powershell, every command about spicetify is getting the same "error"

![6c8b29125505e8195055d0d25ab1e8fc](https://user-images.githubusercontent.com/49335343/92304589-a537bd00-ef7f-11ea-8e32-789a4f2a2956.png)

**Comment by khanhas** [comment]
Try running powershell as Administrator

**Comment by stefanvqm** [comment]
Doesnt work

**Comment by comtecnocel** [comment]
> Después de descargar spicetify a través de powershell, cada comando sobre spicetify recibe el mismo "error"
> 
> ![6c8b29125505e8195055d0d25ab1e8fc](https://user-images.githubusercontent.com/49335343/92304589-a537bd00-ef7f-11ea-8e32-789a4f2a2956.png)

Quizás quisiste decir: Mismo problema, intento instalar incluso como administrador, y me bota ese error.
80/5000
Same problem, I try to install even as administrator, and it throws me that error.

**Comment by stefanvqm** [comment]
even if i run powershell as administrator, it says the same message. anything else?

**Comment by khanhas** [comment]
Eh, I actually have no idea what could prevent you from accessing `spicetify.exe`.
Can you try it in cmd?

**Comment by stefanvqm** [comment]
great, running cmd as administrator worked. ty a lot
