### ISSUE TITLE
Enabling the search bar

### ISSUE THREAD

**Issue by noir-Z** [khanhas/spicetify-cli#28]
Since I installed spicetify the search has moved to the sidebar. However, i would like to have the little search bar near the top of the window. 
search_in_sidebar is already set to 0 in ~/.config/spicetify/config.ini

I'm on Manjaro using the latest AUR spotify and spicetify package.

**Comment by khanhas** [comment]
So you are belong to an A/B group that are used to test that feature.
`spicetify` just exposes it to everyone to try, it didn't force it to your client, Spotify did.

I should give option (toggle value `-1`, maybe) to shut off A/B testing features. 
I will add it this weekend.

**Comment by noir-Z** [comment]
Ah, that explains it.

> I should give option (toggle value -1, maybe) to shut off A/B testing features.
I will add it this weekend.
Cool! Thanks for the quick and productive reply :)

**Comment by khanhas** [comment]
Added in v0.9.1!
After upgrade, run
```bash
spicetify config search_in_sidebar -1
spicetify apply
```
