### ISSUE TITLE
keyboardShortcut.js: opening links with Link Follow(f) triggers other hotkeys

### ISSUE THREAD

**Issue by artofvs** [khanhas/spicetify-cli#280]
Entering combinations for Link Follow(default bind: f) will trigger other shortcuts.
For example, entering `qm` combination will trigger M hotkey defined in the same extension and toggle heart on the song.

**Comment by khanhas** [comment]
Thank you for your report!
I fixed it, rewrote some parts and added some improvement. If you don't mind, could you help me test it out and find any bug I missed?
Just save this js file to your `Extensions` folder and run `spicetify apply`:
https://raw.githubusercontent.com/khanhas/spicetify-cli/8bed80647643ff34ef56a2abaf3a0f5e038bad80/Extensions/keyboardShortcut.js

**Comment by artofvs** [comment]
Works great for me! Thank you very much for such a quick fix.

**Comment by khanhas** [comment]
Great!
I would leave this open for a few more days in case weird bug comes up
