### ISSUE TITLE
Can't see spotify icon on TouchBar for Macbook Pro

### ISSUE THREAD

**Issue by stephanoparaskeva** [khanhas/spicetify-cli#284]
After installing Spicetify and using it with Spotify on my mac, I no longer get the TouchBar slider, previous/next buttons on my touchbar. For example this image shows the functionality I have *lost*:

![](https://media.idownloadblog.com/wp-content/uploads/2016/12/Spotify-Touch-Bar-image-001.jpg)

**Comment by khanhas** [comment]
Can you run `spicetify restore` and see if it comes back to normal?
