### ISSUE TITLE
error Cannot backup app files. Reinstall Spotify and try again.

### ISSUE THREAD

**Issue by 1mg2** [khanhas/spicetify-cli#285]
I keep getting this line after inputting "spicetify backup apply enable-devtool"
ive tried re installing from the web page and im compl.etely new to coding so i really ahve no idea what to do.

**Comment by khanhas** [comment]
Can you uninstall Spotify, run `spicetify clear`, install Spotify and try again?

**Comment by khanhas** [comment]
Sorry, I don't know what's wrong with your Powershell.
Please manually extract spicetify package and run it terminal by its path.
