### ISSUE TITLE
unlinkat /opt/spotify/Apps/full-screen-modal.spa: permission denied

### ISSUE THREAD

**Issue by salteax** [khanhas/spicetify-cli#286]
Hey i'm running Arch Linux and when trying to change my Spicetify theme i always get this message after trying to apply it trought the terminal. Does any one know why it happens all the time?

**Comment by khanhas** [comment]
Did you give Spotify folder write permission?
https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur

**Comment by salteax** [comment]
Nevermind, just had to change permission of the path.

**Comment by salteax** [comment]
> Did you give Spotify folder write permission?
> https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur

Ye, while testing i found out that this have to be the problem :) Thanks for the help!
