### ISSUE TITLE
Can't find prefs file on linux spotify.

### ISSUE THREAD

**Issue by samm-sepi0l** [khanhas/spicetify-cli#287]
I have looked in root/.config and there is no .var in root. What do I do? In-fact, there is no spotify folder in .config. I installed from debian

**Comment by khanhas** [comment]
You have to find it yourself then. It must be in spotify config folder, just find where spotify stores their files.

**Comment by samm-sepi0l** [comment]
spotify stores the files in /usr/share/spotify but there is no config folder there.

**Comment by khanhas** [comment]
Can you find else where? Use tool search or something?

**Comment by samm-sepi0l** [comment]
I used a different file browser and the folders showed up. Thanks
