### ISSUE TITLE
after install this:

### ISSUE THREAD

**Issue by Nandil** [khanhas/spicetify-cli#289]
i have backup, i have all step by step from wiki side and now is this: https://prnt.sc/ui72o4

i have 3x reinstall, but again this.

**Comment by khanhas** [comment]
Which wiki were you reading from?
Please reinstall Spotify and follow this wiki: https://github.com/khanhas/spicetify-cli/wiki/Installation

**Comment by Nandil** [comment]
ah, thx for this.
I try this next day´s
*automatische Signatur*



Am Mi., 16. Sept. 2020 um 12:18 Uhr schrieb khanhas <
notifications@github.com>:
