### ISSUE TITLE
Bring back Spicetify

### ISSUE THREAD

**Issue by Bluscream** [khanhas/spicetify-cli#29]
as a UI wrapper for the CLI

**Comment by khanhas** [comment]
Sorry. I don't use Windows anymore.

**Comment by Bluscream** [comment]
There are cross platform ui's

**Comment by rhysperry111** [comment]
I might have a go at developing one via electron myself. Don't expect much (or anything)

**Comment by rhysperry111** [comment]
Here is a link to the repo if you wanted to watch it. It is currently nowhere near a functional release as I am just learning how to build electron apps

**Comment by Bluscream** [comment]
Thanks

**Comment by Bluscream** [comment]
I am working on a C# GUI Wrapper now https://github.com/Bluscream/Spicetify-GUI-Wrapper

**Comment by rhysperry111** [comment]
Sorry I have not been developing my app. I had a lot of time over the holidays when I decided to start it but went to school a week after I had decided that. Turns out I don’t have as much time as I thought
