### ISSUE TITLE
left sidebar issue

### ISSUE THREAD

**Issue by UnderMan4** [khanhas/spicetify-cli#295]
![image](https://user-images.githubusercontent.com/56913469/93712468-5fb9e900-fb56-11ea-9449-fbd2e2d2ef51.png)
As you can see in ss left sidebar looks very weird. It happens with any theme or even without it when I try to turn of spicetify only for extensions. I already reinstalled spotify and spicetify and it didn't help. Any ideas how to repair it?

PS Sorry for my English in advance but its not my native language

**Comment by khanhas** [comment]
```
spicetify config extensions dribbblish.js-
spicetify apply
```
