### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by amanavinash007** [khanhas/spicetify-cli#297]
I am currently using a dribblish theme and I see ads although I am on a spotify premium account

**Comment by khanhas** [comment]
I don't think that's possible.

**Comment by StefanAvra** [comment]
Spotify does show _announcements_ for new releases on Home. Once turned off by clicking "hide announcement" it won't show them anymore until turned back on in settings. This is expected behaviour for Spotify Premium. Maybe this is what @amanavinash007 saw?

**Comment by amanavinash007** [comment]
> Spotify does show _announcements_ for new releases on Home. Once turned off by clicking "hide announcement" it won't show them anymore until turned back on in settings. This is expected behaviour for Spotify Premium. Maybe this is what @amanavinash007 saw?

yupp realized that a day ago, what occurred that one time is the hide announcement button did not appear.. Thank You!
