### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by notusknot0** [khanhas/spicetify-cli#298]
I keep getting this error while installing:

 ~/.var/app/com.spotify.Client/config/spotify/prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.

I've double checked and confirmed that that is the correct directory for the prefs file and that I set it correctly in the config.ini. Why do I keep getting this issue when running spicetify apply or spicetify update?

**Comment by khanhas** [comment]
Please expand your "~"

**Comment by notusknot0** [comment]
That works, thank you
