### ISSUE TITLE
custom fonts dont seem to work 

### ISSUE THREAD

**Issue by joe23rep** [khanhas/spicetify-cli#299]
hi. im somehow not able to choose a different font for the .glue-page-header__title selector. 

tried it first with google fonts (imported the font on top of the user.css file and declared the font underneath).

didnt work. then i downloaded a font and added the font to the themes directory. added it via:

```
@fontface {
  font-family: myFirstFont;
  src: url("/home/joe/.config/spicetify/Themes/Bitter/almond.otf");
}

```
and declared it underneath with:

 `font-family: myFirstFont;
`

didnt work either. using "local" insteadt of "url" in the link didnt work as well. any ideas what else i can try?

the linter doesnt throw out any errors.

**Comment by khanhas** [comment]
You are using direct path to font file. Spotify browser cannot access files outside of its apps directories.
Please take a look at google-spicetify theme or Dribbblish to know where to put font files and CSS font declarations.  Also remember to enable `overwrite_assets` option in config file.

**Comment by joe23rep** [comment]
thanks. will do that

**Comment by joe23rep** [comment]
hmm. i must be missing something. i set overwrite assests to 1 in the config file. then i basically copied the assests folder from dribblish. i then copied the css code of dribblish at the top and put it into my user.css file at the top. 

set the font family where it needed to be set (i know its at the right place cuz when i change the color it works). 

do i have to declare the path anywhere? or is spicetify programmed to know what the local resource host is?

right now i basically have a folder called assets- in it a folder called glue-recsources, another folder called fonts and then the font files in the fonts folder. 

at the top of my user.css i have:

```
@font-face {
	font-family: "Roboto";
	src: url("https://local_resource_host/fonts/Roboto.woff2") format("woff2");
	font-style: normal;
	font-weight: 400;
}

```

and its declared underneath it with:
`
font-family: Roboto;
`


do i have to do anything different?

**Comment by khanhas** [comment]
Please try running `spicetify apply`

**Comment by joe23rep** [comment]
spicetify said it worked (overwriting theme assets, overwriting custom assets, transfering user css and applying custom modifications but the outcome is still the same. still serif font insteadt of the applied font. 

tried it with a variable like it is done in dribbblish as well. no success either. 

so theres nothing u see i do wrong?

**Comment by joe23rep** [comment]
hmm. i start to think the issue is with the fonts i use. i set up dribblish to test it and added my font to the assests folder in dribbblish. then just changed the font name and format in one of the links. 

doesnt get applied. 

so i thought maybe its the format- found an online formater which changes otf to woff2. did that- same issue. still not showing the fonts. 

do u have a link where i can get woff2 fonts?

**Comment by khanhas** [comment]
https://fonts.google.com/specimen/Roboto?query=roboto
