### ISSUE TITLE
Reload style without having to go to the app and press Cmd+Shift+R

### ISSUE THREAD

**Issue by shuhu3** [khanhas/spicetify-cli#30]
I wrote a script that lets me switch between dark mode on spicetify by changing the color file(swap them) by pressing a hotkey, which functions also as dark mode switching in other apps. But in order to update the style, I will have to bring up the app active and press the Cmd+Shift+R. My current workaround is to make the script switch to the Spotify window and send keystrokes and then switch it back. It works but I was wondering if there is a more efficient way this can be done.

**Comment by khanhas** [comment]
I did try to find how to reload Spotify on command, but no solution is good enough.  
In the past (Spicetify for Rainmeter), to have Live Update feature, I opened a Websocket client in Spotify that was able to receive command `reload` from a websocket server:
```
function InitWS() {
    const ws = new WebSocket("ws://127.0.0.1:58932/")
    ws.onclose = () => setTimeout(InitWS, 1000)
    ws.onmessage = (event) => {
        var command = event.data.toLowerCase().trim()
        if (command == "reload") {
            location.reload()
        }
    };
}
InitWS();
```

But I don't think opening Websocket behind users' back is a good idea, despise the intention is pure or not.

You can use this code above for yourself. Use tool like [wscat](https://www.npmjs.com/package/wscat2) to listen to that port and echo command in:
```bash
echo "reload" | wscat -l 58932
```

**Comment by khanhas** [comment]
Another solution with no Websocket involved and no error spam in console:  
Using `fetch` to read a file content, act as "socket" to receive command. This file has to be in `zlink` app folder.
JS code for Spotify:
```javascript
function InitFetch() {
    fetch("https://zlink.app.spotify.com/socket.json")
        .then(a => a.json())
        .then(command => {
            setTimeout(InitFetch, 1000)
            const commandString = JSON.stringify(command);

            if (commandString == localStorage.getItem("socket")) {
                return
            }   

            localStorage.setItem("socket", commandString)

            if (command.name == "reload") {
                location.reload()
            }
        })
        .catch(() => setTimeout(InitFetch, 1000))
}
InitFetch();
```
Then to command `reload`, in terminal, run:
- **Bash**:
```bash
echo "{\"name\":\"reload\", \"time\": $(date +%s)}" > /opt/spotify/Apps/zlink/socket.json
```

- **Powershell**
```powershell
echo "{`"name`":`"reload`", `"time`": $(Get-Date -UFormat %s)}" > $env:APPDATA\Spotify\Apps\zlink\socket.json
```

**Comment by shuhu3** [comment]
sf

**Comment by shuhu3** [comment]
> Another solution with no Websocket involved and no error spam in console:
> Using `fetch` to read a file content, act as "socket" to receive command. This file has to be in `zlink` app folder.
> JS code for Spotify:
> 
> ```js
> function InitFetch() {
>     fetch("https://zlink.app.spotify.com/socket.json")
>         .then(a => a.json())
>         .then(command => {
>             setTimeout(InitFetch, 1000)
>             const commandString = JSON.stringify(command);
> 
>             if (commandString == localStorage.getItem("socket")) {
>                 return
>             }   
> 
>             localStorage.setItem("socket", commandString)
> 
>             if (command.name == "reload") {
>                 location.reload()
>             }
>         })
>         .catch(() => setTimeout(InitFetch, 1000))
> }
> InitFetch();
> ```
> 
> Then to command `reload`, in terminal, run:
> 
> * **Bash**:
> 
> ```shell
> echo "{\"name\":\"reload\", \"time\": $(date +%s)}" > /opt/spotify/Apps/zlink/socket.json
> ```
> 
> **Note:** Your Spotify client location might be different.
> 
> * **Powershell**
> 
> ```powershell
> echo "{`"name`":`"reload`", `"time`": $(Get-Date -UFormat %s)}" > $env:APPDATA\Spotify\Apps\zlink\socket.json
> ```

This looks like awesome. I will give it a try in a bit.

**Comment by shuhu3** [comment]
Sorry about the late response.

So if I am guessing correctly, for macOS the file should be placed under `/Applications/Spotify.app/Contents/Resources/Apps/zlink/somename.js` and the command would be

``` shell
echo "{\"name\":\"reload\", \"time\": $(date +%s)}" > /Applications/Spotify.app/Contents/Resources/Apps/zlink/socket.js
```

Did I get this right?

**Comment by khanhas** [comment]
Yeah. It looks right.  
To be sure and cross-platform, you could use: 
`$(spicetiffy config spotify_path)/Apps/zlink/socket.json`
But it's unnecessary if you already know what the path is.

**Comment by shuhu3** [comment]
![image](https://user-images.githubusercontent.com/10255571/59897287-d939b900-93a0-11e9-947e-da3d298a12cf.png)

I can't seem to call InitFetch in Console and socket.json is not listed under Sources

![image](https://user-images.githubusercontent.com/10255571/59897316-fbcbd200-93a0-11e9-9892-2c7426d5cc76.png)

I must be doing something wrong.

**Comment by khanhas** [comment]
did you put the JS function I gave above anywhere?
Like an extension maybe?

**Comment by shuhu3** [comment]
Never mind. I forgot to run the `spicetify apply` command. I just tested it and it works now. Thank you so much for your time!
