### ISSUE TITLE
Spotify breaks on Linux apply.

### ISSUE THREAD

**Issue by samm-sepi0l** [khanhas/spicetify-cli#301]
When I run `spicetify backup apply` the Spotify autostart (as in the automatic launch of spotify after spicetify is applied) doesn't let me play anything, just gives me an error message saying **"Spotify can't play this right now. If you have the file on your computer, import it"**. When I try restarting spotify, it's just broken, blank screen and all. `restore backup` doesn't help. It's stuck in the blank screen stage until I reinstall spotify itself.

**Comment by khanhas** [comment]
1. What is your distro?
2. Spotify version and how did you install Spotify?

**Comment by Vinhocent** [comment]
Same issue occurs with Windows.

**Comment by samm-sepi0l** [comment]
Tried it on Ubuntu 20.04 and Linux Mint 20

I have tried flatpak, apt, manually dpkging it, and snap when I was on Ubuntu. No luck, I even tried the featured .deb's on this here repository. My spotify version is currently the latest. But I have tried older versions such as the ones you had here.

**Comment by 3raxton** [comment]
Dealing with this on Mac as well. Mine came from Spotify's newest update, which is 1.1.43.700. I reinstalled from the website and was fortunate to end up with 1.42 again, which works with spicetify-cli, but it seems like the problem comes from 1.43

**Comment by tikeyike** [comment]
I had a similar issue — What I ended up doing was to download Spotify again from the Spotify website (for windows) - version `1.1.43.700.g20acee0f`

Then I ran the `spicetify backup apply` command again, and that seemed to fix the issue for me.

**Comment by Pushkin31** [comment]
I support the problem. Some control buttons are also gone and the design cannot be used on any themes.
spotify-1: 1.1.42.622-1
spicetify v1.1.0
arch linux kernel: 5.8.12-arch1-1
qt 5.15.1-1
gtk engine murrine 0.98.2-4

<details>
<summary>Screenshot</summary>

> ![photo_2020-10-01_16-32-57](https://user-images.githubusercontent.com/35974828/94817665-ed72bf80-0405-11eb-8db0-d064496a07b8.jpg)

</details>

**Comment by samm-sepi0l** [comment]
Still doesn't work guys. I tried using an older version (1.26) and I'm getting the same blank screen unless I open from the terminal. And once that happens it does not let me play anything. I still get the banner saying "Spotify can't play this right now. If you have the file on your computer you can import ti".

**Comment by 3raxton** [comment]
I have spicetify-cli installed via Homebrew and still deal with this issue. I wouldn't say this issue is completely resolved.

**Comment by samm-sepi0l** [comment]
Well, my bad, I'll keep it open again until you Mac and Windows users get something from Khan.

**Comment by 3raxton** [comment]
All good! I appreciate that you’re opening it again for us. Thank you!

**Comment by 3raxton** [comment]
Just took a look at #304, and it looks like what I ran into was that I applied an old back up to a new version of Spotify. Hoping to hear from @khanhas on this, but it looks like we should back up after each update. Do I understand this correctly?

**Comment by khanhas** [comment]
It supposes to show a warning when you try to apply old backup on new version. I wonder if any of you guys saw that warning.

**Comment by samm-sepi0l** [comment]
I saw no warning, and I've tried it with so many different distributions of Spotify, it'd be odd if all of them had "mismatched version" warnings no?
