### ISSUE TITLE
Spicetify Attached to Static Version of Spotify After First Run

### ISSUE THREAD

**Issue by rhaokiel** [khanhas/spicetify-cli#302]
When running Spicetify for the first time, it will create all the config files, etc. It will automatically populate config.ini > spotify_path with the path to the current version of Spotify. But the path to Spotify contains the version number of Spotify, so if Spotify ever updates like it did today, then Spicetify will be lost until I either delete config.ini and rebuild it or manually update the path.

My recommendation would be to put "Shell:AppsFolder\SpotifyAB.SpotifyMusic_zpdnekdrzrea0" as the spotify_path, and then dynamically resolve it to the current path of Spotify each run. That way it keeps Spicetify from overriding a user's customization, but also allows users to leave it set as auto-customized.

I tried this, but unfortunately Spicetify is not expecting a Shell command there, only a real directory.

**Comment by khanhas** [comment]
Fixed. Will be available in next version
