### ISSUE TITLE
New Spotify update completely breaks the UI 

### ISSUE THREAD

**Issue by rhynero** [khanhas/spicetify-cli#303]
The new Spotify update rolled out a few days ago and when installing it, it reverts back to the original Spotify theme.

However, when I go to apply the spicetify theme, it shows a blank interface, with only the three dots in the top left and the minimise functions on the top right. I can only seem to turn it back to normal by reinstalling Spotify. All the playback options work and I can still listen to music.

It may be something to do with the user file or something.

https://imgur.com/a/NL8dfla

**Comment by zjeffer** [comment]
I didn't have a completely blank interface, but I did have the default UI after installing today's Spotify update. 

I just had to run `spicetify backup apply` to reapply spicetify. Does that work for you?

**Comment by rhynero** [comment]
Nah, it doesn't. But I will reinstall Spotify and try it again.

**Comment by zjeffer** [comment]
Does `spicetify restore` turn it back to normal?

**Comment by rhynero** [comment]
Ok, doing backup apply worked which is weird because I tried it before, but it said things like:

`[ 26 / 32 ] genre            error Cannot find symbol for playerUI
[ 29 / 32 ] collection       error Cannot find symbol for EventDispatcher and Event Creator
error Cannot find symbol for player and cosmos in PlayerHelper
[ 30 / 32 ] playlist         error Cannot find symbol for Profile Menu and Item React
error Cannot find symbol for Profile Sub Menu React`

Should I just ignore these?

**Comment by zjeffer** [comment]
I don't get these warnings. 

Do you have any extensions?

**Comment by rhynero** [comment]
Alright, I've sorted it out. I was supposed to have the `webnowplaying.js` extension but apparently, it wasn't in the extensions folder so I fixed that easily.

Anyway, thanks very much for your help :)

**Comment by zjeffer** [comment]
No problem :)

**Comment by imwaveyyy** [comment]
I've tried the fixes in this thread. Still gives me a blank UI. I also get "[ 30 / 32 ] search           error Cannot find symbol for Profile Sub Menu React" during the preprocessing stage of backing up files.
