### ISSUE TITLE
Spotify Crashing on Launch on Linux, and all icons missing once theme applied.

### ISSUE THREAD

**Issue by VandanUbuntu** [khanhas/spicetify-cli#304]
First of all, let me present the exact steps I am taking.
1. Install Spotify
curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update && sudo apt-get install spotify-client
sudo chmod a+wr /usr/share/spotify
sudo chmod a+wr /usr/share/spotify/Apps -R

2. Install Spicetify
sudo curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh

3. Set an alias for Spicetify
sudo nano ~/.bashrc
alias spicetify = '/home/[user[/spicetify-cli/spicetify'
source ~/.bashrc

4. Download Spicetify themes
cd Downloads
git clone https://github.com/morpheusthewhite/spicetify-themes
cd spicetify-themes
cp -r * ~/.config/spicetify/Themes

5. Set themes
cd ~/.config/spicetify/Themes
spicetify config current_theme THEME_NAME
spicetify apply
____
Now that I have shown the steps - here are the issues: 
1. Spotify keeps crashing, [I don't know why]
when I run it through the terminal this is what it shows - 
[1003/103506.826242:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

Spotify seems to start working once I spam "Spotify" in the terminal. [but it crashing again & again is really annoying, how can I fix this?]

2. Icons are missing, it looks terrible.
![image](https://user-images.githubusercontent.com/60042992/94971849-7e5fad00-0564-11eb-9386-04813efad756.png)

Those are the two issues I have encountered.
System info - Ubuntu 20.04, CPU - intel celeron, memory - 4 GB.

**Comment by mbednarek360** [comment]
Can confirm on Arch Linux with Spicetify 1.1.0. Config was lost and after reapplying icons are missing. 
![image](https://user-images.githubusercontent.com/25366750/95025805-7a15bb80-065a-11eb-8539-50fb7907bb62.png)

**Comment by khanhas** [comment]
Can you guys reinstall Spotify then run
```
spicetify backup apply
```

**Comment by mbednarek360** [comment]
> Can you guys reinstall Spotify then run
> 
> ```
> spicetify backup apply
> ```

This worked perfectly for me. Not sure the cause but this fixed everything.

**Comment by khanhas** [comment]
You probably applied old backup on new Spotify version

**Comment by OlegWock** [comment]
I got this error with gpu process with fresh installation of spotify and spicetify. In rare cases when it launches it shows blank window (like here #94)
