### ISSUE TITLE
Flatten theme not completely flat :)

### ISSUE THREAD

**Issue by ref** [khanhas/spicetify-cli#306]
Search page have gradient (look at my screenshot).

I fix it by css style:
`
.GlueHeader__background-color {
    background-color: #1b1b1b !important;
}
`

But maybe I can disable this bg color by color.ini file?

<img width="1199" alt="Screenshot 2020-10-08 at 16 37 26" src="https://user-images.githubusercontent.com/505388/95441769-bdd33280-0984-11eb-95ae-eef46927b6de.png">

**Comment by khanhas** [comment]
Sorry, this is not Spicetify issue. Please ask for help on Spectrum.
