### ISSUE TITLE
problems using the webnowplaying.js

### ISSUE THREAD

**Issue by fleixi** [khanhas/spicetify-cli#31]
I have problems using the webnowplaying.js
I like to use it for a custom plugin in a python programm but im not able to connect to the ws-port and im not sure if your extensions is registerted correctly.

I have tried to connect with wscat via commandline without success:
```

[fleixi@daisy ~]$ wscat -c ws://127.0.0.1:8974/
error: connect ECONNREFUSED 127.0.0.1:8974


```
Is there a way to check if a extensions is loaded correctly in spotify?

My config:

```
[fleixi@daisy ~]$ cat /home/fleixi/.config/spicetify/config.ini 
[Setting]
color_scheme     = Base
inject_css       = 0
replace_colors   = 0
overwrite_assets = 0
spotify_path     = /opt/spotify
prefs_path       = /home/fleixi/.config/spotify/prefs
current_theme    = 

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
visualization_high_framerate = 0
custom_apps                  = 
experimental_features        = 0
fastUser_switching           = 0
lyric_always_show            = 0
lyric_force_no_sync          = 0
radio                        = 0
song_page                    = 0
home                         = 0
made_for_you_hub             = 0
new_feedback_ui              = 0
search_in_sidebar            = 0
extensions                   = autoSkipVideo.js|queueAll.js|trashbin.js|webnowplaying.js

; DO NOT CHANGE!
[Backup]
version = 1.1.5.153.gf614956d

```

**Comment by khanhas** [comment]
1. To check if extensions are injected correctly, in Spotify, open Devtool by right click at bottom bar and choose `Show Devtools. (Note: You need to run `spicetify enable-devtool` first if you haven't).
Switch to `Source` tab and you can see list of javascript files that are loaded successfully:
![image](https://user-images.githubusercontent.com/26436809/59726941-fc684980-9276-11e9-9167-81c4c0bffb1e.png)

2. To establish a WebSocket (ws) connection, you need a server and client(s). Ws in `webnowplaying.js` or any ws in browsers are always clients, never a server.
To open a ws server with wscat, use flag `--listen` (`-l`):
```bash
wscat -l 8974
```
Correspondingly, you need to find a ws server package for Python to programmatically gather/scrap player info.

**Comment by fleixi** [comment]
Thanks i miss interpreted the js as a server. Everything working fine now.
