### ISSUE TITLE
Themes removed after update

### ISSUE THREAD

**Issue by TOXX1C** [khanhas/spicetify-cli#310]
My Spotify app updated today but when the app was opened the themes were removed. I checked the **Spicetify cli** folder and checked the **Spotify_path**, everything was proper and even the theme that I used was there in the folder. I restarted my computer and the theme was back but when I reopen the app the themes are gone. Any idea on why this is happening?

**Comment by khanhas** [comment]
Try run: `spicetify restart` in terminal

**Comment by TOXX1C** [comment]
I ran `spicetify restart` in terminal and the spotify app opened and the themes were there. I reopened the app and the themes are gone.

**Comment by khanhas** [comment]
You are using Windows Store Spotify, please uninstall it and install Spotify from installer. Then run `spicetify backup apply`.

**Comment by TOXX1C** [comment]
No, I am not using the Windows store version. I had the windows store version before, I uninstalled it and reinstalled spotify from the web installer.

**Comment by khanhas** [comment]
If you said you had normal Spotify distribution, opening Spotify via `spicetify restart` or directly via its shortcut should make no difference.
If it's not too troublesome, please make a new shortcut and let it execute `spicetify restart`

**Comment by khanhas** [comment]
Also try reinstall Spotify, remove config file, then run `spicetify backup apply` to see if it resolves.

**Comment by TOXX1C** [comment]
Sorry for the late reply. You can run `spicetify restart` in command prompt in the directory of the application shortcut or the spotify application _(the directory that you use to open the app)_. This fixes the issue.
