### ISSUE TITLE
newRelease.js Extension Broken

### ISSUE THREAD

**Issue by senhan07** [khanhas/spicetify-cli#311]
I guess after update from version v1.1.43.700 the extension not working anymore, i already clean reinstall everything including spotify and spicetify but still not result.

Spotify Version: 1.1.43.700.g20acee0f
Spicetify Version: 1.1.0
Log file: [zlink.app.spotify.com-1602828437832.log](https://github.com/khanhas/spicetify-cli/files/5389530/zlink.app.spotify.com-1602828437832.log)

![image](https://user-images.githubusercontent.com/34976706/96212424-11ef9f80-0fa1-11eb-9ee1-d6e9b1a0d5fd.png)
![image](https://user-images.githubusercontent.com/34976706/96212443-1c119e00-0fa1-11eb-9741-3bb8522e143a.png)
![image](https://user-images.githubusercontent.com/34976706/96219496-276cc580-0fb1-11eb-869a-01045ab3abd2.png)

**Comment by JoMa25** [comment]
The whole mod doesnt load for me anymore, didnt change anything the last few weeks. Hope this gets solved

**Comment by khanhas** [comment]
Zero problem on my end.
Can you open your Followed Artists page and see if it loads alright? Since the extension and Artist app use same API endpoint.

**Comment by JoMa25** [comment]
![image](https://user-images.githubusercontent.com/47923682/96576536-9a887b80-12d2-11eb-9a38-2a97c6bcc20c.png)

seems like its working alright

**Comment by khanhas** [comment]
Is this still a problem @senhan07 ?
Can you try right clicking at bell icon and choose Refresh?
