### ISSUE TITLE
Unable to get spicetify working

### ISSUE THREAD

**Issue by Bookadic** [khanhas/spicetify-cli#313]
[IMPORTANT: Please remove or replace everything between two square brackets ( [ ] ) before posting your issue.]

Description
[When I try to enter " spicetify backup apply ", I always get this error C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0 does not exist or is not a valid path. Please manually set "spotify_path" in config.ini to correct directory of Spotify.
When I try to get to Windowsapps folder, I get a message that I do not have the permission to enter. I am the administrator.

Is there anyway I can fix it or can I uninstall spicetify.cli and reinstall ?

Thanks in advance

Versions

Rainmeter Version: [4.4 Beta Release r3404 ]
OS Version: [Windows 10 Pro 2004 64-bit (build 19041) French (3084)]
Spotify Version: [Spotify is not showing in the plugins Tab but I have version 1.1.44.538 installed]

Additional notes/images

Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.
Testez le nouveau système multiplateforme PowerShell https://aka.ms/pscore6 PS 

C:\Users\HP600G2> Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression DOWNLOADING https://api.github.com/repos/khanhas/spicetify-cli/releases/latest > OK DOWNLOADING https://github.com/khanhas/spicetify-cli/releases/download/v1.1.0/spicetify-1.1.0-windows-x64.zip > OK
EXTRACTING C:\Users\HP600G2\spicetify-cli\spicetify-1.1.0-windows-x64.zip into C:\Users\HP600G2\spicetify-cli > OK
REMOVING C:\Users\HP600G2\spicetify-cli\spicetify-1.1.0-windows-x64.zip > OK

OK
Run spicetify --help to get started.

PS C:\Users\HP600G2> spicetify
info Run "spicetify -h" for commands list.

PS C:\Users\HP600G2> spicetify config extensions webnowplaying.js
warning Config "extensions" unchanged: webnowplaying.js is already in the list.

PS C:\Users\HP600G2> spicetify backup apply
spicetify v1.1.0
error C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0 does not exist or is not a valid path. Please manually set "spotify_path" in config.ini to correct directory of Spotify.

**Comment by khanhas** [comment]
```
spicetify config spotify_path " "
spicetify backup apply
```

**Comment by Bookadic** [comment]
This is what I get in powershell

C:\Users\HP600G2> spicetify config spotify_path "C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0"
success Config changed: spotify_path = C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0
info Run "spicetify apply" to apply new config

PS C:\Users\HP600G2> spicetify apply
spicetify v1.1.0
error C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0 does not exist or is not a valid path. Please manually set "spotify_path" in config.ini to correct directory of Spotify.
PS C:\Users\HP600G2> spicetify backup apply
spicetify v1.1.0
error C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.143.700.0_x86__zpdnekdrzrea0 does not exist or is not a valid path. Please manually set "spotify_path" in config.ini to correct directory of Spotify.
PS C:\Users\HP600G2>

**Comment by Bookadic** [comment]
I ended up removing Spotify app and spicetify. I reinstall Spotify and spicetify. Everything is working fine like before. I wonder if a Windows update could have caused the problem as it was working fine before.
