### ISSUE TITLE
fatal zip: not a valid zip file

### ISSUE THREAD

**Issue by RCYLA** [khanhas/spicetify-cli#318]
I reinstalled Spicetify and now when I try to install WebNowPlaying I always get the same error
fatal zip: not a valid zip file
I tried to reinstall it, install it via Choco, restart everything but I keep getting the same error.
![image](https://user-images.githubusercontent.com/60105842/97593172-69453500-19cf-11eb-9a29-dbfb4e483e7a.png)

When trying to make a backup I get

![image](https://user-images.githubusercontent.com/60105842/97593259-8417a980-19cf-11eb-9915-da0287c18dfd.png)
*The system can not find the specified path *

**Comment by khanhas** [comment]
Please uninstall your current SPotify and install it again with installer.
Then run:
```
spicetify clear backup apply
```
