### ISSUE TITLE
x86 os support?

### ISSUE THREAD

**Issue by metsukou** [khanhas/spicetify-cli#319]
Just wondering if there's a 32-bit ver for this? The description is too vague so I thought it would work on all windows os and tried it on my netbook but unfortunately it doesn't run.

**Comment by khanhas** [comment]
Sorry, I don't even think there is 32-bit Windows user.
If you really want to use Spicetify, please build binary file using these instructions:
https://github.com/khanhas/spicetify-cli/wiki/Development
