### ISSUE TITLE
Playlists not loading

### ISSUE THREAD

**Issue by PixeLInc** [khanhas/spicetify-cli#32]
Hello - My playlists don't seem to be loading whilst using spicetify.
Meaning, when clicking a playlist, it loads forever and ever and ever.

If I restore to the original spotify, it works.
There are 2 errors in console:
![alt text](https://i.imgur.com/YEEO8U6.png, "Console errors")
but I don't really know if those are related and seem to happen upon client launch.

I am using the latest release, v0.9.2 on Arch Linux.

**Comment by khanhas** [comment]
What version is your Spotify?

**Comment by PixeLInc** [comment]
Right, of course I forget that...

Using spotify v1.0.80.480.g51b03ac3

**Comment by PixeLInc** [comment]
You know - you'd think a person would be smart enough to figure out that they should check if their spotify is out of date before making an issue.. 

Fixed by updating to v1.1.5
*sigh*
