### ISSUE TITLE
"Liked Songs" playlist cleared and cannot add any to it

### ISSUE THREAD

**Issue by iceman42** [khanhas/spicetify-cli#320]
Hi there, thanks for creating this amazing software!
I'm using linux mint 20 xfce, and I've been able to install and use the different colour schemes and extensions fine, with one problem. For some of the themes (for example, SolarizedDark) my "Liked Songs" playlist is empty, and when I try to like a song I get the an error saying that I have too many songs in the playlist. However other themes are fine, e.g. Otto. 
I've tried to look in the css files and I couldn't see what could be causing it (but I'm not really experienced enough to understand what's going on there). I've also had a search around online and can't find a solution. 
Thanks

**Comment by quantumfate** [comment]
I actually have the same issue. As well as all my albums

**Comment by quantumfate** [comment]
I actually just fixed mine by simply logging off and on

**Comment by iceman42** [comment]
Hi quantumfate. Logging out and in again has fixed it for me also. Thanks!
