### ISSUE TITLE
Equalify Add-in

### ISSUE THREAD

**Issue by Glo0mY** [khanhas/spicetify-cli#321]
Hello 

I installed Spicetify today, but now I can't use my Equalify Equalizer.
https://www.equalify.me/
Can I get that to work somehow ?
Thanks a lot

Best regards

Jan

**Comment by PseudonymPatel** [comment]
You could try installing Equalify _after_ installing Spicetify, that way Equalify overwrites anything it needs to from Spicetify, or at least in theory

**Comment by Bluscream** [comment]
i use both without problems
