### ISSUE TITLE
Reddit-Adding Problem

### ISSUE THREAD

**Issue by urdaddyVlex** [khanhas/spicetify-cli#325]
When I typed the command 
spicetify config custom_apps reddit
spicetify apply

Powershell showed 
success Config changed: custom_apps = genius|reddit
info Run "spicetify apply" to apply new config
spicetify v1.1.0
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
error Extension "bundle.js" not found.
OK
Creating custom apps symlinks:
OK
success Spotify is spiced up!

but I've already dragged the folder "reddit" from C:\Users\Username\spicetify-cli\CustomApps to C:\Users\Username\.spicetify\CustomApps

and when I opened spotify to check out the results, reddit was here but there's a "Nothing Here Yet" in the Subreddit column

**Comment by khanhas** [comment]
Sorry for late response.
Can you open DevTool console and check if there is any error relating to reddit app?
