### ISSUE TITLE
Pywal on MacOS

### ISSUE THREAD

**Issue by Ninja73737** [khanhas/spicetify-cli#327]
Hello! So the current implementation of pywal support uses XResources, but I'm using pywal on Mac, so I don't have XResources. I'm not sure how difficult this would be to implement, but is there a way that I can "source" a pywal colorscheme `.json` file and use it's contents in the color.ini theme file?
If it's a complicated issue then don't worry about it, but I suspect from the way the syntax works for the XResources variables that it might not be too difficult to do, I'm just not sure how I would go about it...

**Comment by khanhas** [comment]
You can use environment variables. I don't know whether pywal can automatically do it for you, but  just write a script that sources colors from json file to environment variables. Then use the same environment to execute `spicetify` commands (`apply`, `update`).
![image](https://user-images.githubusercontent.com/26436809/98454450-4590a480-21b0-11eb-856e-52fc40ba0843.png)

**Comment by Ninja73737** [comment]
Ok thanks! Sorry, missed the environment variables part of the docs mb.

**Comment by khanhas** [comment]
All good. Hope you have fun with Spicetify!
