### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Lavender-Breeze** [khanhas/spicetify-cli#328]
when I try to do the whole
`spicetify backup apply` 
bit. I get an error saying that the path doesn't exist. when I do to look for the file it's trying to write which should be on this path here...
`C:\Users\---------\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs`
everything up to the file `SpotifyAB.SpotifyMusic_zpdnekdrzrea0` and therefore everything after doesn't exist

what would I need to do to get these files to, you know, exist? is there anything? I'm not too sure...
I did some light research and this appears to be the file that houses the cache for classic Spotify, but after I did a reinstall after being told to by CMD after attempt #1. this is my 5th attempt at this, I've restarted the app, computer, logged in and out, and reinstalling all over again.

any help to getting on the path to fixing this would be greatly appreciated. thanks to any help you can provide.

**Comment by khanhas** [comment]
If you successfully installed normal Spotify (non-Windows Store), please just delete config file and run `spicetify backup apply`.

**Comment by Lavender-Breeze** [comment]
alright, were talking about the one in the `.spicetify` right?

**Comment by khanhas** [comment]
Yes, the ".ini" file.

**Comment by Lavender-Breeze** [comment]
alright, thanks so much, I appreciate it so much. it was a great help and looks great in the end!

it's huge on how great this is!
