### ISSUE TITLE
The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by whydiors** [khanhas/spicetify-cli#329]
I've been trying to install spicetify for the whole afternoon lol and after it downloads, I type in spicetify like the instructions say but Win Powershell says ''The specified executable is not a valid application for this OS platform.'' 
I use Windows 10 32bit, does that have anything to do with Spicetify?

**Comment by JulienMaille** [comment]
Duplicate of #319

**Comment by khanhas** [comment]
Spicetify only supports 64bit Windows.
