### ISSUE TITLE
Spotify update doesn't work if -cli and spicetify patches installed

### ISSUE THREAD

**Issue by charmarkk** [khanhas/spicetify-cli#33]
I mentioned this over on the monstercat vis issue tracker, but if I patch Spotify, it won't update until I reboot, and then I have to patch over with the -cli again. IS this expected?

**Comment by khanhas** [comment]
I really don't understand what is the issue.  
Anyway, I will give some info from my guesses:
- After applied `spicetify`, Spotify auto-update still works normally in Windows and MacOS (Linux users have to update via package manager, obviously).
- You don't have to reboot your computer after applying `spicetify`. You only need to restart Spotify client. `spicetify` also automatically restart it after applying successfully.
- When Spotify is auto-updated, you have to run `spicetify backup apply` again.

**Comment by charmarkk** [comment]
That's what I'm saying - none of that goes as expected with spicetify installed/applied. 

When I atrempt to update Spotify, if Spicetify applied:
Spotify will restart, then say it can't update because the files are being used. At this point, I also can't open the client without cleaning up the appdata folder. I'll then have to restart the PC, where then everything will go as expected. This only started occuring after Spicetify, so I'm thinking it's that.

**Comment by khanhas** [comment]
Sorry then. I have no idea what could cause this.

**Comment by charmarkk** [comment]
Unfortunate.

Very well then.

**Comment by sslesar** [comment]
I believe Charmarkk using Spotify from Windows Store Apps. There two different Spotify clients and different store in C disk.

**Comment by charmarkk** [comment]
@sslesar No, just the downloadable from Spotify's own website.

**Comment by charmarkk** [comment]
Since there will likely be no resolution, I'll close the issue.
