### ISSUE TITLE
Spicetify cant apply backup or anything

### ISSUE THREAD

**Issue by MarcoIanne** [khanhas/spicetify-cli#331]
![image](https://user-images.githubusercontent.com/26443313/98557321-59b5ce00-22a4-11eb-8b1e-859ea263b137.png)
image attached, PS C:\Users\Marco> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest > OK
DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v1.1.0/spicetify-1.1.0-windows-x64.zip > OK
EXTRACTING     C:\Users\Marco\spicetify-cli\spicetify-1.1.0-windows-x64.zip into C:\Users\Marco\spicetify-cli > OK
REMOVING       C:\Users\Marco\spicetify-cli\spicetify-1.1.0-windows-x64.zip > OK
 > OK
Run spicetify --help to get started.

PS C:\Users\Marco> spicetify
info Run "spicetify -h" for commands list.
PS C:\Users\Marco> spicetify backup apply
spicetify v1.1.0
BOM: read C:\Users\Marco\AppData\Roaming\Spotify\prefs: Handle non valido.
PS C:\Users\Marco> spicetify backup apply
spicetify v1.1.0
BOM: read C:\Users\Marco\AppData\Roaming\Spotify\prefs: Handle non valido.
PS C:\Users\Marco> spicetify backup apply
spicetify v1.1.0
BOM: read C:\Users\Marco\AppData\Roaming\Spotify\prefs: Handle non valido.
PS C:\Users\Marco> spicetify prefs_path C:\Users\Marco\AppData\Roaming\Spotify\prefs
spicetify v1.1.0
error Command "prefs_path" not found.
info Run "spicetify -h" for list of valid commands.
PS C:\Users\Marco> spicetify config prefs_path C:\Users\Marco\AppData\Roaming\Spotify\prefs
success Config changed: prefs_path = C:\Users\Marco\AppData\Roaming\Spotify\prefs
info Run "spicetify apply" to apply new config
PS C:\Users\Marco> spicetify apply
spicetify v1.1.0
BOM: read C:\Users\Marco\AppData\Roaming\Spotify\prefs: Handle non valido.
PS C:\Users\Marco>

**Comment by manohar9600** [comment]
Same issue for me too.

**Comment by khanhas** [comment]
Sorry for very late response.
Can you check if that prefs file exists?

**Comment by GDWingWangWong** [comment]
> Sorry for very late response.
> Can you check if that prefs file exists?

I have the same issue, there is no 'prefs' file in the spicetify-cli folder

**Comment by GDWingWangWong** [comment]
Sorry for bothering you, I had this issue but a config file was generated.

**Comment by khanhas** [comment]
@GDWingWangWong what do you mean? spicetify config file or prefs file?

**Comment by boehs** [comment]
This issue just started happening to me. spicetify's `config.ini'`s file has the correct spotify path. issue seems to be that `\login\` is missing.

![](https://e.reeee.ee/4QvhX0.png)

**Comment by khanhas** [comment]
What are you doing?
After you reinstall, just run `spicetify backup apply`. I repeat this multiple times in every single Issues.

**Comment by boehs** [comment]
> What are you doing?
> After you reinstall, just run `spicetify backup apply`. I repeat this multiple times in every single Issues.

I did not grab a screenshot, but unfortunately the backup was also causing issues, so I purged it. 

I resolved it now, but its quite a interesting issue
