### ISSUE TITLE
Spotify Issue

### ISSUE THREAD

**Issue by Odsodium** [khanhas/spicetify-cli#333]
Hey, I have an issue where when I have the program installed (correctly, Its functioning) 
Spotify crashes every second time I open it up, It says "The Spotify application is not responding".
Any permanent fix for this?
Thanks

**Comment by khanhas** [comment]
Can you reinstall and try spicetify again?

**Comment by Odsodium** [comment]
I Have tried that. The problem still persists.

**Comment by khanhas** [comment]
I mean reinstall Spotify.
