### ISSUE TITLE
Adblock no longer working after applying backup after spotify update

### ISSUE THREAD

**Issue by Jackaroo05** [khanhas/spicetify-cli#335]
Hello. The main reason I got spicetify was for the adblock functionality but spotify had an update so i applied the backup spicetify had and the ads are showing up again. I really need this fixed... Thanks!

**Comment by khanhas** [comment]
Excuse me, ad-blocking was never a functionality of spicetify. And I won't give support or affiliate with anyone who intent to take advantage of my software to hurt Spotify revenue. Please don't mistaken spicetify to other Spotify ad-blockers.
