### ISSUE TITLE
Lyrics not working after installing spicetify.

### ISSUE THREAD

**Issue by yatsukiko** [khanhas/spicetify-cli#336]
Hi, after I installed spiectify lyrics breaks with a message "humming is fun", without spicetify or even using spotify on mobile/open.spotify it works fine. I'm on japanese region and windows 10 if that matters. 
In console I can see "Connection error: net::ERR_NAME_NOT_RESOLVED" for "https://lyrics.app.spotify.com/css/lyrics.css.map", but also whenever I click lyrics buttons this error pops up
 ![spice](https://yatsukiko.me/u/K7yAIztCWs.png)

I've tried to track down where is open.spotify.com taking lyrics from and it's "https://spclient.wg.spotify.com/lyrics/v1/track/", I haven't seen that at all in spiectify. 

This also happens with fresh spicetify/spotify install.

**Comment by andrizmitnick** [comment]
Confirmed, fresh spotify and spicetify install, it breaks built-in lyrics function

**Comment by khanhas** [comment]
I'm really sorry, it's impossible for me to find the problem because the lyric feature is not enabled on my country.

**Comment by yatsukiko** [comment]
I'm willing to temporarily share my spotify logins, if you don't mind

**Comment by khanhas** [comment]
We can try. Please send it to xuankhanh96a at gmail dot com

**Comment by yatsukiko** [comment]
just making sure, it's xuankhanh96a not xuankhanh963? latter is on your github page

**Comment by khanhas** [comment]
Yeah, you can send to either.

**Comment by yatsukiko** [comment]
I've send it to xuankhanh96a at gmail com

**Comment by dimasmiftah** [comment]
Maybe consider using [this ](https://github.com/khanhas/genius-spicetify) spicetify custom app while wait the author fixes the built-in error.

**Comment by vrevolverrr** [comment]
Found a solution. Run `spicetify restore` and navigate to the Apps directory in your Spotify installation folder (%APPDATA%/Spotify/Apps) and backup `lyrics.spa` file. Then run `spicetify apply` and close Spotify. Open `lyrics.spa` with a file archiver (7-zip). Replace everything in the lyrics folder of the modded Apps directory with the contents of `lyrics.spa` file.

**Comment by irfanfadilah** [comment]
Can confirm. Instead of showing the lyrics, it will just showing us this error message:

![image](https://user-images.githubusercontent.com/6077598/106889368-7f733780-671a-11eb-8367-50998b2ef97a.png)

**Comment by complex-hub** [comment]
> 
> 
> Found a solution. Run `spicetify restore` and navigate to the Apps directory in your Spotify installation folder (%APPDATA%/Spotify/Apps) and backup `lyrics.spa` file. Then run `spicetify apply` and close Spotify. Open `lyrics.spa` with a file archiver (7-zip). Replace everything in the lyrics folder of the modded Apps directory with the contents of `lyrics.spa` file.
> ![SharedScreenshot](https://user-images.githubusercontent.com/32459351/106860449-5ee9b400-66ff-11eb-9060-84403cd9aa3f.jpg)

Worked here as well.

![image](https://user-images.githubusercontent.com/53913349/106890463-1bc01e80-66c8-11eb-9ccc-4d0fe7c5ba7d.png)

**Comment by khanhas** [comment]
Well, if restoring stock lyric app solve the issue, it's definitely my fault then. One of the modification breaks the app.

**Comment by yatsukiko** [comment]
I have pointed down what change breaks it, if u js pretty print it, look for "if (0 === this.propertySet.size) return Promise.resolve();" and remove "return;" just before that it will fix the lyrics
![image](https://user-images.githubusercontent.com/40772846/106991913-297caf00-676f-11eb-834a-49a379377880.png)

proof: 
![image](https://user-images.githubusercontent.com/40772846/106992003-60eb5b80-676f-11eb-9cb7-ed449955f6b3.png)

**Comment by khanhas** [comment]
Thank you @yatsukiko for narrowing down what is the problem!
I just made a quick fix, can you test it out this version:
[spicetify-1.2.1-windows-x64.zip](https://github.com/khanhas/spicetify-cli/files/5930824/spicetify-1.2.1-windows-x64.zip)

Just unzip `spicetify.exe` to `%userprofile%\spicetify-cli\` and run:
```
spicetify restore backup apply
```

**Comment by irfanfadilah** [comment]
@khanhas @yatsukiko just tried that zip and it works on my end.

**Comment by yatsukiko** [comment]
@khanhas works for me

**Comment by khanhas** [comment]
Thank you all!

**Comment by sortedcord** [comment]
Works for me as well!

**Comment by akhiljerald** [comment]
thank you @khanhas and @yatsukiko. I wanted a fix for this for a while now!

**Comment by ishaan-kapoor** [comment]
The issue is still there in 2024, with the latest version of spicetify.
and there is no `lyrics.spa` file this time.

**Comment by yatsukiko** [comment]
> The issue is still there in 2024, with the latest version of spicetify. and there is no `lyrics.spa` file this time.

cannot confirm, check your extensions. Works fully ok for me.

If u can confirm that this still happens with all extensions/themes off then better to write a new issue rather than necro this.
