### ISSUE TITLE
[SOLVED] Monstercat Visualicer & Sound info. stopped working after yesterday's Spotify 1.1.46.916.g416cacf1 update …

### ISSUE THREAD

**Issue by just4t** [khanhas/spicetify-cli#337]
Yesterday @ ±201118-20:00 (UTC+1) right after **Spotify 1.1.46.916.g416cacf1** automatic update sudently made the visualizer + song info. to stop working through **Web NowPlaying + Spicetify CLI** combo, as correctly did it before. Hope you will consider to fix It soon! Thanks in advance ;))

**Comment by khanhas** [comment]
They still works fine on mine.
Please reinstall Spotify and run `spicetify backup apply`.
If there is any Spotify update in the future, you need to run `spicetify backup apply`.
