### ISSUE TITLE
How to uninstall Spicetify completely?

### ISSUE THREAD

**Issue by in-atus** [khanhas/spicetify-cli#338]
I installed Spicetify with my Microsoft Store version of Spotify, but uninstalled that version of Spotify since I wanted more customization. Now that I installed the Windows version of the app, Spicetify won't recognize the file path of the new version. What's the line to uninstall Spicetify on PowerShell, or what file path do I use on the config file?

**Comment by in-atus** [comment]
Update: I am not the brightest lightbulb out there. I deleted the folders .spicetify and spicetify-cli, and trying to reinstall it through PowerShell gives an error I am too dumb to understand. Please help.

**Comment by in-atus** [comment]
![image](https://user-images.githubusercontent.com/74826989/99882169-774a4680-2c59-11eb-862d-fb7810e843e7.png)

**Comment by khanhas** [comment]
In powershell, run:
```
cd ~
rm -r spicetify-cli
rm -r .spicetify
```
Then reinstall Spotify.

**Comment by in-atus** [comment]
![image](https://user-images.githubusercontent.com/74826989/99907739-74168f80-2d19-11eb-8ff6-753bcd3ad4bc.png)

**Comment by in-atus** [comment]
> I deleted the folders .spicetify and spicetify-cli
I'm not hoping that there'll be a way to remove it completely, but by leaving it as is there shouldn't be a problem, right?

**Comment by khanhas** [comment]
What do you mean?
If you already deleted those 2 folders, you successfully uninstalled spicetify.

**Comment by in-atus** [comment]
When I try to reinstall spicetify through PowerShell using this:
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`
What I get is a result shown in my third reply. I've already reinstalled the Windows version of Spotify, so I just need to reinstall spicetify. Is there another way to reinstall spicetify without going through PowerShell?

**Comment by in-atus** [comment]
Wait, sorry, forgot to run PowerShell in administrator. Looks like I got it reinstalled. Thanks @khanhas!

**Comment by ajhawkings** [comment]
Really sorry - am having the same issue - just where do I need to run PowerShell in administrator. If it is run in administrator for the installing, won't it put the folders in system32 directory? Thanks (and sorry if i am not supposed to reopen issues)

**Comment by 9dl** [comment]
Omg Ty it worked i deleted the file "Spotify" and it worked thank you so much!

**Comment by phuid** [comment]
[on spicetifys website](https://spicetify.app/docs/advanced-usage/uninstallation) you can find the official way to uninstall
```
spicetify restore
rmdir -r -fo $env:APPDATA\spicetify
rmdir -r -fo $env:LOCALAPPDATA\spicetify
```
