### ISSUE TITLE
Feature request: warn about a snap installation of spotify

### ISSUE THREAD

**Issue by KiranWells** [khanhas/spicetify-cli#339]
I recently installed this on my device and I immediately ran into errors, including a failed backup and inability to find the Spotify installation.

After nearly two hours of troubleshooting, I noticed under "A note for Linux users" it said that snap installations were not supported. This could have easily been avoided if the application had tested for a "~/snap/spotify/" directory when it failed to find Spotify. As Snap is the preferred installation according to Spotify, it is highly likely that this issue will happen again.

As a side note: your instructions for installing Spotify without Snap are out of date. Currently, the Spotify website says this:

### Debian / Ubuntu

Spotify for Linux is also released as a Debian package. Our aim is that it should work with the latest Long Term Support release of Ubuntu, but we will try to make it work for other releases of Ubuntu and Debian as well.

You will first need to configure our debian repository:

```sh
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
```

Then you can install the Spotify client:

```sh
sudo apt-get update && sudo apt-get install spotify-client
```

**Comment by khanhas** [comment]
Thanks

**Comment by MainManu** [comment]
Thanks for saving me a lot of time. Apparently this feature would have been really useful for me :sweat_smile:
