### ISSUE TITLE
Buttons are out of their places

### ISSUE THREAD

**Issue by LeooHollow** [khanhas/spicetify-cli#340]
Hey, I'm using Spicetify in Windows 10 and it was working alright, but when I tried to change to another theme than Dribblish, all of the icons were out of their places, as seen in the screenshot. I have no idea of what to do.

![image](https://user-images.githubusercontent.com/74525293/100525695-87a27a00-31a1-11eb-91fb-17294e86611a.png)

**Comment by khanhas** [comment]
```
spicetify config extensions dribbblish.js-
spicetify apply
```

**Comment by jojoharry16** [comment]
I have the same error, I think it only appeared after using Dribbblish-dynamic, and using ```spicetify config extensions dribbblish.js-``` and ```spicetify config extensions dribbblish-dynamic.js-``` don't fix the error

![2020-12-13 22_55_29-Spotify Premium](https://user-images.githubusercontent.com/39400627/102025177-8d4db180-3d96-11eb-8641-03fcb89eb97d.png)

**Comment by jojoharry16** [comment]
After reinstalling Spotify the SpicetifyDefault theme works, but then applying the Onepunch theme messes it up again, and reverting to SpicetifyDefault leaves it messed up

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply` again. Be consensus on what theme you installed, what were the steps to install it and invert those steps if you don't want it anymore.
