### ISSUE TITLE
Add to queue is weird

### ISSUE THREAD

**Issue by GreyHunter21** [khanhas/spicetify-cli#341]
Hi,

When I press the 3 dots of a song I can't add it to the queue. The button in the context menu is not responding and also not adding anything. It does nothing. The rest of the buttons in the context menu work fine, but the 'add to queue' button doesn't.

Anyone else have this problem?

Thanks

**Comment by khanhas** [comment]
Still works normally on my side.
Please reinstall Spotify and run `spicetify backup apply`.
