### ISSUE TITLE
Network Connectivity Status Indicator (NCSI) Problem

### ISSUE THREAD

**Issue by surya27895** [khanhas/spicetify-cli#342]
I have an internet connection and can use normally but windows say that i have not internet connection, cause of that spotify also say that "No internet connection".

is there any chance to spicetify to force spotify run without NCSI checking or spoof that status check?
Thanks.

**Comment by khanhas** [comment]
No idea what you're talking about. Why that has anything to do with Spicetify?
Have you tried reinstall Spotify?

**Comment by surya27895** [comment]
i mean this problem
![image](https://user-images.githubusercontent.com/22859567/100709072-0684f600-33e0-11eb-8afd-ab1c7bf04c9e.png)

sometimes that network indicator say "No Internet Access" although you have a normal connection and can use the internet normally but the indicator still say so.

Spotify by default use this indicator to check if there any internet connection or not, if the indicator still say that "No Internet Access" spotify app will followed it and cannot used,  thats the problem.

thats why i ask is there any possibility to spicetify force the spotify app start without that internet indicator check of atleast spoof it ?

**Comment by khanhas** [comment]
I don't think so, at least it's out of my skill scope. It is very likely that connection checking function was implemented in binary layer, not Chrominium/browser layer. And spicetify has no control over that.
Have you consider reinstall your Windows to fix that bug?

**Comment by surya27895** [comment]
i did, but it always come if i use dnscrypt, so i think i will look for another solution.

Thanks for the answer!!

**Comment by rojnwa** [comment]
> i did, but it always come if i use dnscrypt, so i think i will look for another solution.
> 
> Thanks for the answer!!

Did you find any solution to that? I have the exact same problem.

**Comment by surya27895** [comment]
> > i did, but it always come if i use dnscrypt, so i think i will look for another solution.
> > Thanks for the answer!!
> 
> Did you find any solution to that? I have the exact same problem.

the only way to fix this is solve it on the windows side
nothing can do with spicetify
