### ISSUE TITLE
Cannot install Spicetify

### ISSUE THREAD

**Issue by zx111lol** [khanhas/spicetify-cli#344]
Fresh install of windows. After uninstalling the Microsoft store edition of Spotify, I tried to install the website one along with Spicetify. Giving me this error constantly. I'm 100% sure it's not the Microsoft store edition.

PS C:\Users\teodo> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest > OK
DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v1.1.0/spicetify-1.1.0-windows-x64.zip > OK
EXTRACTING     C:\Users\teodo\spicetify-cli\spicetify-1.1.0-windows-x64.zip into C:\Users\teodo\spicetify-cli > OK
REMOVING       C:\Users\teodo\spicetify-cli\spicetify-1.1.0-windows-x64.zip > OK
 > OK
Run spicetify --help to get started.

PS C:\Users\teodo> spicetify
info Run "spicetify -h" for commands list.
PS C:\Users\teodo> spicetify backup apply enable-devtool
>>
spicetify v1.1.0
error C:\Users\teodo\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.
PS C:\Users\teodo>

![image](https://user-images.githubusercontent.com/60603374/100809373-e2500600-342d-11eb-9ff1-d75a905eca25.png)

![image](https://user-images.githubusercontent.com/60603374/100809590-5a1e3080-342e-11eb-917c-930669d5a0f8.png)

**Comment by khanhas** [comment]
Delete config file and try again.
Run `spicetify -c` to print config file path.
