### ISSUE TITLE
Bookmark icon has once again disappeared

### ISSUE THREAD

**Issue by grastraa** [khanhas/spicetify-cli#345]
This has happened a few times for me now. I haven't changed anything, one day I open Spotify and the icon is gone from that point onwards.

I'm on the latest Spotify and Spicetify.

Removing and re-adding Bookmark.js from config does not work.

Restoring backup and re-appplying Spicetify does not work. 

Installing the latest Spotify set up over the top of everything and re-injecting Spicetify does not work.

(Loading the old bookmark custom app (who's layout I miss dearly) shows that my bookmarks are still present)

The only way I can remedy this extension not loading is by completely removing Spotify and reinstalling it, then injecting Spicetify and it's extensions again from scratch.

Doing this destroys my entire collection of bookmarks. 

Any solution or hacky work around allowing me to get bookmark.js running again without losing my actual bookmark collection every time would be much appreciated.

**Comment by khanhas** [comment]
Can you open Console (hit Ctrl + Shift + i), then hit Ctrl + Shift + R to refresh, check if there is any error from bookmark.js

**Comment by grastraa** [comment]
Yep that looks to be the case. 
[zlink.app.spotify.com-1607100702786.log](https://github.com/khanhas/spicetify-cli/files/5644126/zlink.app.spotify.com-1607100702786.log)

**Comment by khanhas** [comment]
Thank you, I found the bug. Please download this bookmark.js and replace the one in `~\spicetify-cli\Extensions` folder:
https://raw.githubusercontent.com/khanhas/spicetify-cli/master/Extensions/bookmark.js

**Comment by grastraa** [comment]
Yus! That did the job. You're a legend, thank you~
