### ISSUE TITLE
Does Not Work With WebNowPlaying When Region Is Set To Turkey.

### ISSUE THREAD

**Issue by JordansplaceYT** [khanhas/spicetify-cli#346]
When windows is set to turkey as a region spicetify fails to work properly. when it is set to America it works fine.
Im not quite sure what may be causing this issue but it seems to be a problem.

**Comment by khanhas** [comment]
Can you be more specific on how it doesn't work properly?

**Comment by KyoSenpaiX** [comment]
when i change country and regional format to english in windows settnings it is working. i change country to turkey and still working. but when I change the regional format from turkish to english its not working

**Comment by khanhas** [comment]
Can you open Console in Devtool, then hit Ctrl R to reload Spotify and check if there is any error in Console.
