### ISSUE TITLE
No idea what happened.

### ISSUE THREAD

**Issue by xawes0m3** [khanhas/spicetify-cli#347]
I followed the installation instructions and ended with this. Can someone please provide insight or guide me through this? My guess is I might've closed PowerShell before it fully finished. I have run the installation command twice, nothing changed. I also do not know how to uninstall Spicetify to reinstall. I added what my Spotify looks like.
Thanks.
![problem](https://user-images.githubusercontent.com/62813535/101271774-cd7bb700-373a-11eb-8fa7-e7fb94a84580.PNG)

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#windows
