### ISSUE TITLE
"Cannot Detect spotify prefs location" But the location is correct

### ISSUE THREAD

**Issue by AnshulKanwar** [khanhas/spicetify-cli#348]
As written in FAQ I ran, `cd ~` and then `find | grep "spotify/prefs$"`.
It returns `./.config/spotify/prefs`.

And in my **config.ini** I have, `refs_path = /home/user/.config/spotify/prefs`.

Running `spicetify backup apply enable-devtool` or `spicetify update` gives this error: 
`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini`.

##
- **Os**: Arch linux 5.4.80-lts
- **Spotfiy Version**: 1.1.42.622.gbd112320
- **Spicetify Version**: 1.1.0-1
- **Spicetify installed with**: yay -S spicetify-cli

**Comment by khanhas** [comment]
Can I see your whole config file?

**Comment by AnshulKanwar** [comment]
> Can I see your whole config file?

Here: https://hastebin.com/noqiyajelo.ini

**Comment by khanhas** [comment]
Is that prefs file a valid file, can you check its content, just check it out, don't post it here.
I can see you already successfully backupped, how could you not apply?

**Comment by AnshulKanwar** [comment]
Ok I feel dumb.
I did not run chmod on my spotify files.
Thanks :)
