### ISSUE TITLE
WebNowPlaying

### ISSUE THREAD

**Issue by bBSempai** [khanhas/spicetify-cli#349]
How do I enable WebNowPlaying extension for Spicetify to enable its compatibility for rainmeter skins??

**Comment by bBSempai** [comment]
I cant figure out doing that in the CLI

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user

**Comment by bBSempai** [comment]
Ahh figured it out thankyouu!
