### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by phoenix277yt** [khanhas/spicetify-cli#351]
I've run chmod on my files fyi. When I try to find the path of the prefs file the terminal returns this. I use the FlatPak version.
`[daksh_s@R53600X ~]$ cd ~`
`[daksh_s@R53600X ~]$ find | grep "spotify/prefs$"`
`./.var/app/com.spotify.Client/config/spotify/prefs`
`find: ‘./~’: Permission denied`

**Comment by phoenix277yt** [comment]
config.ini - 
`[Setting]
inject_css              = 1
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0
color_scheme            = 
prefs_path              = ~/.var/app/com.spotify.Client/config/spotify/prefs
current_theme           = SpicetifyDefault
replace_colors          = 1
spotify_path            = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
radio                        = 0
visualization_high_framerate = 0
custom_apps                  = 
experimental_features        = 0
fastUser_switching           = 0
home                         = 0
lyric_always_show            = 0
lyric_force_no_sync          = 0
song_page                    = 0
extensions                   = 

; DO NOT CHANGE!
[Backup]
version = 
`

**Comment by phoenix277yt** [comment]
this is the same issue as issue #348 but the thing is that i've run chmod, im running kernel 5.9 in manjaro

**Comment by khanhas** [comment]
Replace `~` with actual path.

**Comment by phoenix277yt** [comment]
ok thanks will check now

**Comment by phoenix277yt** [comment]
tysm
