### ISSUE TITLE
Spotify has a new UI design

### ISSUE THREAD

**Issue by SaberAkiyama** [khanhas/spicetify-cli#352]
I've saw on Spotify has been updated, the UI design has different, right now.

![Screenshot (21)](https://user-images.githubusercontent.com/48464326/102001645-6d36d780-3d2f-11eb-8ab4-eb996be7b90a.png)

By the way, this is the original without using Spicetify.

**Comment by khanhas** [comment]
And your issue is?

**Comment by SaberAkiyama** [comment]
None. I just wonder that app was updated a couple of weeks ago.

**Comment by goldfinches** [comment]
Still not an issue, but spicetify does not adapt to the new layout (album artwork in playlists and the organization of the artist page being the two big ones). I didn't particularly like Spotify's update (and this was partially how I discovered spicetify in the first place), but you might get complaints in the coming months of people expecting album artwork in playlists etc. Just a warning.
