### ISSUE TITLE
Custom fonts always missing

### ISSUE THREAD

**Issue by jojoharry16** [khanhas/spicetify-cli#354]
First of all, thank you for making Spicetify, it makes everything better

Any theme which uses a custom font always shows up without any font, just the default Times New Roman-looking one.

![2020-12-15 20_45_58-Spotify Premium](https://user-images.githubusercontent.com/39400627/102264972-ad0be380-3f16-11eb-8b3e-9573eebb2ec0.png)

This happens on every Windows boot and the only way to fix it is by reinstalling the custom fonts, even if they were already installed. Is this a Windows issue? Is there a known fix?

Thanks in advance

**Comment by khanhas** [comment]
Did you enable `overwrite_assets` option in config?
