### ISSUE TITLE
Applying a theme doesn't work with the new UI

### ISSUE THREAD

**Issue by Momoske** [khanhas/spicetify-cli#355]
Actually quite enjoying the new UI personally, I found out today that forcing it in the prefs file finally works - so having used the web player for months with Stylus to have custom CSS, I decided to try Spicetify again to apply my CSS inside the desktop app.

After applying my own theme, it automatically reverted to the old UI, with a completely messed up UI (but that's probably because of my CSS, though it was almost all black and I haven't forced black anywhere in my CSS) - so checking the prefs file, the line to enable the new UI was indeed gone, but adding it back didn't change a thing, it's stuck to the old UI. Here's the line to add in the prefs file:
> ui.experience_override="xpui"

Is the new UI disabled on purpose, or is it purely some incompatibility making it not work?

**Comment by khanhas** [comment]
Sorry, there is no way to customising new UI. And yes, spicetify deletes xpui on purpose.
