### ISSUE TITLE
Connectivity 

### ISSUE THREAD

**Issue by Tealfully** [khanhas/spicetify-cli#359]
I cant run the installation for spicetify.cli on PS, I did it once but I accidentally had the windows version of spotify. What do I do to undo the installation?

**Comment by khanhas** [comment]
1. Title about "Connectivity". What do you mean by Connectivity?
2. Not able to run spicetify has anything to do with accidentally having Spotify Windows Store version?

Please rephrase your question.

**Comment by Tealfully** [comment]
So what I mean is that I had the windows version of spotify when I didn't notice. I did the spicetify stuff in powershell and I realised I had the windows version. I installed the spotify executable and it didn't work. I did Powershell again and it's coming with errors.

I hope that makes sense.

**Comment by khanhas** [comment]
Remove config file and try again

**Comment by Tealfully** [comment]
How do I do that? I'm bad with this sorta stuff.

**Comment by Tealfully** [comment]
Oh the audio works. But the song info and music logo isn't working, what do I do about that?

**Comment by Tealfully** [comment]
Sorted! Thank you so much for your help!
