### ISSUE TITLE
Better Api-Documentation -- Questions

### ISSUE THREAD

**Issue by fleixi** [khanhas/spicetify-cli#36]
I know this is a issues-tracker no helpdesk but i struggle to understand the exposed api and i dont find a place for questions

Im working on a kodi-addon to control/sync the playback from both using ur example in webnowplaying.js. Basic playback (syncing time,play,pause,next,prev, show playlist in kodi) are working already but now i like to allow the user to select a spotify-track inside kodis current playlist to jump to this track in spotify.

I think i need to use "PlaybackControl" but i dont understand what parameter i need to pass to it. Or is there a better way to jump to a track in the current playlist.

**Comment by khanhas** [comment]
1. I am really glad that people starts building stuff with Spicetify. I hope you will publish your work after you finish so everyone can use it as example usage.

2. Exposed APIs beside those in `spicetifyWrapper.js` are leaked via variables. I have no access to the pre-minified source code so I do not know fully their documentation and potential. 

3. To jump to a track in a certain context (playlist, album), add:
```javascript
function playUriFromQueue(uri) {
    Spicetify.PlaybackControl.playFromResolver(
        Spicetify.Player.data.context_uri, 
        { trackUri: uri }, 
        () => { }
    );
}
```
then, simply run `playUriFromQueue` with track uri you want to jump to as argument.  
**Note:** Beware, it simply create a new session for your player, play that track in same context and it will go on play next tracks normally. If you are previously in shuffle mode, new session will be no longer in shuffled order.

**Comment by fleixi** [comment]
1. i will try to publish my code but since i am only writing code as a hobby and only learning with tryanderror my code will not be the best example. The most is happening on kodi/python side too.

2. i totally understand this, but i have to clue how you find functions like PlaybackControl.playFromResolver(). In your code there is nothing exposed below PlaybackControl

3.
I seem to miss something. I have add the funktion to my js file and added a event for it to:

```
function fireEvent(event) {
        const m = event.data;
        const n = m.indexOf(" ");
        let type = n === -1 ? m : m.substring(0, n);
        type = type.toUpperCase();
        const info = m.substring(n + 1);

        switch (type) {
            case "PLAYSONG":
                playUriFromQueue(info);
                break;
            case "PLAYPAUSE":
                Spicetify.Player.togglePlay();
                break;

```
but if i send "PLAYSONG:spotify:track:3KQ8BI3qEGlze3ToDNIfJ9" to the websocketclient i get no reaction. Im complete new to javascript. Is the string splitted incorrectly since there a more than one ":" or must i convert the string to something other?

Is there a good way to debug this by output the content of info to some console or similar?

If there some questions to generic to javascript please say it and i will search on my own. I dont want to annoying you with generic questions.

**Comment by khanhas** [comment]
1. You haven't enable devtool? Run:
```js
spicetify enable-devtool
```
After Spotify restarts, right click at player bar, choose Show Devtools and open tab Console.

2. You should send `PLAYSONG spotify:track:3KQ8BI3qEGlze3ToDNIfJ9`, because command and param divider is a space (`const n = m.indexOf(" ");`)

**Comment by fleixi** [comment]
silly me! :-D
devtools are enabled, i havend seen the console. Thank you.

Everything works fine now.

Should this issue be closed or keep open for more api-questions?

**Comment by khanhas** [comment]
They can make a new one. I'm actually Ok with questions
