### ISSUE TITLE
Spicetify.getAudioData doesn't wok

### ISSUE THREAD

**Issue by vokinpirks** [khanhas/spicetify-cli#360]
Hi!
I'm trying to develop my own extension which shows track's audio metadata from the context menu.
I made js file and added it in the Spicetify config. 
In the extension I've defined a context menu item and registered it. 
To this point everything works just fine - the context menu item shows up in Spotify and it's handler method is being invoked with a URI list but I have no success with getting a track's metadata.
I've tried to use the Spicetify.getAudioData method as follows:

`function get_metadata(uris) {
        const uri = uris[0];
        Spicetify.getAudioData(uri)
            .then(metadata => {
                Spicetify.showNotification(metadata);
            })
            .catch(console.log);
    }`

Which seemed not to work as nothing happens and in the dev tools console it says:
Error: GET request to hm://audio-attributes/v1/audio-analysis/2esJ6s6tXJNpmEtBJFvMiP failed with status code 503
    at t.Resolver._parseResponse (zlink.bundle.js:78)
    at t.Resolver._createRequestAsync (zlink.bundle.js:78)

Have tried a few tracks with the exact same result.

Also, where I can find the description of all that hm:// and sp:// protocol calls to be able to fix such things myself whenever possible? Or is there a way I can reverse engineer/capture/intercept them to sort things out myself?

**Comment by khanhas** [comment]
1. What kind of metadata you are looking for? Track metadata or **Analyzed Audio** metadata? Because Pre-analyzed audio are audio track being analyzed by Spotify, not audio track that are currently playing on your machine.
2. `Spicetify.getAudioData` still works fine on my end. 503 means server has problem so I think you should try in another time.

**Comment by vokinpirks** [comment]
Oh, thank you, I now realise that what I was looking for is actuially called audio features not audio analysis. Is it possible to fetch audio features somehow? I know I can do so though a Spotify API call but that requires authorization and complicates things a bit.

**Comment by vokinpirks** [comment]
Have decided to code this myself and thus rewritten code like this looking at your implementation of the getAudioData:

```
Spicetify.CosmosAPI.resolver.get(
            `hm://audio-attributes/v1/audio-features/${uriObj.getBase62Id()}`,
            (error, payload) => {
                if (error) {
                    console.log(error);
                    return;
                }

                Spicetify.showNotification(payload.getJSONBody());
            });

```
Still got the same error:
`Error: GET request to hm://audio-attributes/v1/audio-features/6fTxRAW44D6UKHkdaxkDTB failed with status code 503
    at t.Resolver._parseResponse (zlink.bundle.js:78)
    at t.Resolver._createRequestAsync (zlink.bundle.js:78)`

It looks strange to me that the same functionality works for you and doesn't for me.

**Comment by khanhas** [comment]
Sorry, I don't really know why.
Also what is "audio feature" that you are looking for?

**Comment by vokinpirks** [comment]
https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/
Sadly it's not possible to access them inside Spotify application. I'm trying to fix that. For example sort queue by criteria like valence, danceability, acousticness and so on. Would be really helpful I think...

**Comment by khanhas** [comment]
Wow, that API link you made up actually works:
![image](https://user-images.githubusercontent.com/26436809/102896890-da2a3a00-44b2-11eb-9d13-ed5f16630aef.png)

**Comment by vokinpirks** [comment]
Indeed, finally now it's working for me too at least ~25% of attempts.
I solved the issue with recursive retry mechanism limited to max 5 unsuccessful tries.
Thank you for assistance. I'm closing this.
