### ISSUE TITLE
Can't install spicetify with Brew

### ISSUE THREAD

**Issue by PaulVerhoeven1** [khanhas/spicetify-cli#361]
when i want to install the spicetify cli with `brew install khanhas/tap/spicetify-cli`

i got the following error:
`Error: Your CLT does not support macOS 11.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.`

I think there is something wrong with the brew package.

**Comment by khanhas** [comment]
Sorry I don't really know.
https://github.com/Homebrew/brew/issues/9128
Try this I think

**Comment by PaulVerhoeven1** [comment]
Thanks, that solved the problem!
