### ISSUE TITLE
WebNowPlaying not working at all

### ISSUE THREAD

**Issue by nursemorrigan** [khanhas/spicetify-cli#362]
Ever since the (I believe) Spotify 1.1.46.916.g416cacf1 update, my Rainmeter skins refuses to work with Spicetify. I've tried reinstalling Spotify and WebNowPlaying is the only enabled extension. This isn't a problem with Rainmeter itself since it works with the browser WebNowPlaying extension just fine.

Spotify Version: 1.1.48.625.g1c87c7f7
Spicetify Version: 1.1.0

**Comment by khanhas** [comment]
Open DevTool Console and see if there is any error from webnowplaying.js
Also check if `<script>webnowplaying.js</script>` is in Elements page

**Comment by nursemorrigan** [comment]
I checked the Console and there is an error

webnowplaying.js:47 Uncaught ReferenceError: Spicetify is not defined
    at updateInfo (VM533 webnowplaying.js:47)

Only line 47 is giving any errors, there's also something about a SourceMap, but I don't know if it's a part of my problem

![image](https://user-images.githubusercontent.com/46274809/103200257-b8112d00-48a1-11eb-9227-c3bf580387c8.png)

**Comment by khanhas** [comment]
Can you copy your config file content here?

**Comment by nursemorrigan** [comment]
[Setting]
color_scheme            = 
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
spotify_path            = C:\Users\melis\AppData\Roaming\Spotify
prefs_path              = C:\Users\melis\AppData\Roaming\Spotify\prefs
current_theme           = Night
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 0
disable_upgrade_check = 1

[AdditionalOptions]
lyric_always_show            = 0
lyric_force_no_sync          = 0
made_for_you_hub             = 0
visualization_high_framerate = 0
custom_apps                  = 
experimental_features        = 1
fastUser_switching           = 0
home                         = 0
song_page                    = 0
extensions                   = webnowplaying.js
new_feedback_ui              = 0
radio                        = 0
search_in_sidebar            = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.48.625.g1c87c7f7

**Comment by khanhas** [comment]
Yeah, your `exposed_api` is turned off somehow.
Set it to 1 and run `spicetify restore back apply`
