### ISSUE TITLE
Unable to Install via Homebrew on M1 MacBook

### ISSUE THREAD

**Issue by CookieCoder15** [khanhas/spicetify-cli#363]
I am trying to install Spicetify via brew on OS X 11.1 (M1 MacBook Pro) and it always fails to build as shown in the logs below:

```
Last 15 lines from /Users/user/Library/Logs/Homebrew/spicetify-cli/01.go:
2020-12-30 17:14:50 +1100

go
build
-o
spicetify

go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/go-ini/ini v1.55.0
go: downloading golang.org/x/net v0.0.0-20200506145744-7e3656a0809f
go: downloading github.com/mattn/go-isatty v0.0.12
dep/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:6:8: missing go.sum entry for module providing package golang.org/x/sys/unix; try 'go mod tidy' to add it
```

If this issue should be directed at the developer of a module you use rather than you, please tell me and I can make an issue on the corresponding repo. Thanks!

**Comment by khanhas** [comment]
Can you install go (if you haven't had it yet) via homebrew and run:
```
go get github.com/mattn/go-isatty
```
then try again.

**Comment by CookieCoder15** [comment]
Thanks for the quick response! I just tried that now, unfortunately I got the same error as above. Heres the output when I ran the command you sent:
```
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
```

**Comment by khanhas** [comment]
Oh hey, is your MacBook the lastest model with ARM chip?
Anyway, if it's not too troublesome, can you use pre-built package? Either with install bash script or do it manually.

**Comment by CookieCoder15** [comment]
Just tried that and it worked with a little extra effort.

For anyone else with An M1 Mac you need to run terminal in rosetta mode just for the install otherwise you see: `Unsupported architecture arm64. Only x64 binaries are available.` Once you install and add to path you can use from terminal in ARM mode just fine.

**Comment by khanhas** [comment]
Thank you!
I think I will add ARM support build for MacOS in next version.

**Comment by chang2000** [comment]
> Just tried that and it worked with a little extra effort.
> 
> For anyone else with An M1 Mac you need to run terminal in rosetta mode just for the install otherwise you see: `Unsupported architecture arm64. Only x64 binaries are available.` Once you install and add to path you can use from terminal in ARM mode just fine.

Just tried and succeed! 
- Use `env /usr/bin/arch -x86_64 /bin/zsh --login` to switch terminal into Rosetta2 mode
- Use the manually installation approach 
- Add path as the post-install text
