### ISSUE TITLE
Spicetify not working after installing.

### ISSUE THREAD

**Issue by vigneshkannan522** [khanhas/spicetify-cli#365]
I'm using POP_OS 20.04 and I did as per the instructions and it worked without any problem till I installed it. It showed it is running and even suggested that I try spicetify -h for more commands and it showed the info of it.
But when I ran the command you mentioned to make sure that it is correctly installed, it showed everything was okay but in the end/last line it showed (some name) theme is not found (It didn't show the first time I installed it, but showed the second and third time) but didn't show any other error.
Then when I close the terminal and reopen it. and type spicetify/spicetify -h it shows:

`kannan@pop-os:~$ spicetify --help
spicetify: command not found
kannan@pop-os:~$ 
`
When I run the `curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh` code you mentioned, and run the command "spicetify" again, I just shows all the things it showed the first time I installed ran it, but it again after I close terminal and reopen it and run it, It shows the same "spicetify: command not found" error.

**Comment by khanhas** [comment]
spicetify was installed in your home folder, either launch it directly with its path:
```
~/spicetify-cli/spicetify --help
```
or add its folder to `$PATH` then launch it normally as you did before.

**Comment by vigneshkannan522** [comment]
Yeah, I'm able to run it when I install it, but then suddenly it shows some error about a __ theme not found and when I try to update it(like you said on the github page, I followed the whole step), it shows the same error.
```
kannan@pop-os:~$ curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest
DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v1.1.0/spicetify-1.1.0-linux-amd64.tar.gz
######################################################################## 100.0%-=#=#   #   #                                           ######################################################################## 100.0%
EXTRACTING     /home/kannan/spicetify-cli/spicetify.tar.gz
REMOVING       /home/kannan/spicetify-cli/spicetify.tar.gz

spicetify was installed successfully to /home/kannan/spicetify-cli/spicetify

Manually add the directory to your $HOME/.bash_profile (or similar)
  export SPICETIFY_INSTALL="/home/kannan/spicetify-cli"
  export PATH="$SPICETIFY_INSTALL:$PATH"

Run '/home/kannan/spicetify-cli/spicetify --help' to get started
kannan@pop-os:~$ export PATH=/home/kannan/spicetify-cli:$PATH
kannan@pop-os:~$ spicetify
info Run "spicetify -h" for commands list.
kannan@pop-os:~$ spicetify backup apply enable-devtool
spicetify v1.1.0
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK                            
Preprocessing:
OK                            
OK                            
success Everything is ready, you can start applying now!
error Theme "DribbblishDynamic" not found
kannan@pop-os:~$ 
kannan@pop-os:~$ spicetify update
spicetify v1.1.0
error Theme "DribbblishDynamic" not found
kannan@pop-os:~$ 
```
And this only happend when I install it. But when I close the terminal and reopen it and type "spicetify", it shows this:
`kannan@pop-os:~$ spicetify
spicetify: command not found
kannan@pop-os:~$ 
`
And about the PATH you mentioned, I think I did that when spicetify installed and prompted me to manually define it, and I did it again after you said it. And I even reinstalled spotify client. Should I reinstall spicetify? (Would you mind sharing how to do it, if so!!! (Sorry, new to linux).

**Comment by vigneshkannan522** [comment]
Thanks for the reply :)
But Its shows that (some) theme is not found when I run the command you mentioned on your "Basic Usage" page to make sure there is no error. 
And when I run the update command, It shows the same error. 
```
kannan@pop-os:~$ /home/kannan/spicetify-cli/spicetify
info Run "spicetify -h" for commands list.
kannan@pop-os:~$ /home/kannan/spicetify-cli/spicetify backup apply enable-devtool
spicetify v1.1.0
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK                            
Preprocessing:
OK                            
OK                            
success Everything is ready, you can start applying now!
error Theme "DribbblishDynamic" not found
kannan@pop-os:~$ /home/kannan/spicetify-cli/spicetify update
spicetify v1.1.0
error Theme "DribbblishDynamic" not found
```
Why is it? Did I miss any theme package that is default or needed when I installed it?

**Comment by vigneshkannan522** [comment]
Thank you for your help. Since I'm new to Linux, I didn't know about the path stuff, after reading your reply, I did a little research and found out about it. I had to change the .profile file to get it to read it every time :)

**Comment by ClemGlacee** [comment]
You can close the issue if it got resolved :)

**Comment by Firefox2892** [comment]
> spicetify was installed in your home folder, either launch it directly with its path:
> 
> ```
> ~/spicetify-cli/spicetify --help
> ```
> 
> or manually add its folder (`~/spicetify-cli`, please expand it) to `$PATH` then launch it normally as you did before.

wdym $PATH folder?
