### ISSUE TITLE
Some mistakes in the description of the path to the Linux config file on the wiki

### ISSUE THREAD

**Issue by skmatz** [khanhas/spicetify-cli#370]
Hi @khanhas, I found some mistakes on the wiki, but I don't know how to send a pull request about the wiki, so I report it to the issue.

- https://github.com/khanhas/spicetify-cli/wiki/Custom-Apps
- https://github.com/khanhas/spicetify-cli/wiki/Customization
- https://github.com/khanhas/spicetify-cli/wiki/Extensions

In these links, the path to the configuration file for Linux is written as `~/.config/spicetify/config.ini` or `$XDG_CONFIG_HOME/.config/spicetify/config.ini`.

But in general, and also from the source code, the latter path should be `$XDG_CONFIG_HOME/spicetify/config.ini`.

**Comment by khanhas** [comment]
Thank you!
