### ISSUE TITLE
Spotify update broke spicetify.

### ISSUE THREAD

**Issue by phoenix277yt** [khanhas/spicetify-cli#372]
as It says in the title, I still have the ownership of spotify files. 
terminal - 
`[daksh_s@R53600X ~]$ spicetify backup `
`spicetify v1.1.0`
`info There is available backup.`
`info Clear current backup:`
`success Backup is cleared.`
`Backing up app files:`
`OK`
`Extracting:`
`OK`                            
`Preprocessing:`
`OK`                            
`OK    `                        
`success Everything is ready, you can start applying now!`
`[daksh_s@R53600X ~]$ spicetify backup apply`
`spicetify v1.1.0`
`info There is available backup.`
`info Clear current backup:`
`success Backup is cleared.`
`Backing up app files:`
`OK`
`Extracting:`
`OK`                         
`Preprocessing:`
`OK  `                          
`OK`                            
`success Everything is ready, you can start applying now!`
`Copying raw assets:`
`fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/stations.spa: permission denied`
`[daksh_s@R53600X ~]$ spicetify apply`
`spicetify v1.1.0`
`Copying raw assets:`
`fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/stations.spa: permission denied`

**Comment by khanhas** [comment]
can you check that path with `ls -l`

**Comment by phoenix277yt** [comment]
@khanhas it is indeed there.
![image](https://user-images.githubusercontent.com/73348506/104310006-09075f00-54f9-11eb-9872-219d91887cc9.png)

**Comment by khanhas** [comment]
1. Don't use `sudo` with any of spicetify command.
2. Make prefs_path a absolute path.
2. Try these commands:
```
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
```

**Comment by phoenix277yt** [comment]
> 1. Don't use `sudo` with any of spicetify command.
> 2. Make prefs_path a absolute path.
> 3. Try these commands:
> 
> ```
> sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
> sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
> ```

step 3 didn't work but the second step fixed it :D thank you @khanhas
