### ISSUE TITLE
Perfs path error

### ISSUE THREAD

**Issue by YTisRuler2006** [khanhas/spicetify-cli#373]
So when i type the spicetify backup apply enable-devtool or spicetify backup apply devtool it gives this : "\AppData\Local\Packages\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file." so i saw someone say type "find | grep "spotify/prefs$" and i did and it gave "grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:8
+ find | grep "spotify/prefs$"
+        ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException"

i am not sure as to what to do.

I am using a windows 10 computer and i downloaded spotify from there website and on the windows store it says i havent installed it and i can install it by clicking install.

Please help.

**Comment by khanhas** [comment]
Delete config file and try `spicetify backup apply` again

**Comment by MKrabs** [comment]
IF this isnt working for you, after:

- reinstalling sportify
- deleting config file
- searching with `find | grep "spotify/prefs$"`

Did you launch Spotify after reinstalling ? AND logging in?
This helped me !
