### ISSUE TITLE
Mine doesnt look like the picture....

### ISSUE THREAD

**Issue by Harry825** [khanhas/spicetify-cli#374]
![Capture](https://user-images.githubusercontent.com/64845629/104576505-2bf85700-5650-11eb-9722-301d750b4b41.PNG)

**Comment by phoenix277yt** [comment]
what was it like in the picture?

**Comment by khanhas** [comment]
Reinstall Spotify and follow this instruction: https://github.com/khanhas/spicetify-cli/wiki/Customization
