### ISSUE TITLE
[bug] latest version check crashes spicetify if it failed for some reason

### ISSUE THREAD

**Issue by amrbashir** [khanhas/spicetify-cli#375]
Right now if for some reason the latest-version check fails, maybe because there is no internet or something, spicetify will just crash. 

![image](https://user-images.githubusercontent.com/48618675/104743102-f89ef080-5753-11eb-9c12-9a6d5e9ce720.png)

**Comment by khanhas** [comment]
Fixed. Will be available in next version.
