### ISSUE TITLE
Spotify won't open after restarting pc

### ISSUE THREAD

**Issue by Rawerooo** [khanhas/spicetify-cli#376]
When i'm installing spotify and spicetify, everything works perfectly fine, but if i close, and then open my pc, spotify won't open. I checked my task manager and i seen that spotify process going up for a few seconds and then it closes. There's no error massages. Only way to repair it, is reinstalling spotify but then this issue comeback after next pc shutdown.

**Comment by khanhas** [comment]
What is your spotify version and is it Windows Store version?

**Comment by Rawerooo** [comment]
No, it's not Windows Store version. Just regular app from spotify website. Version 1.1.48.625.g1c87c7f7

**Comment by khanhas** [comment]
Can you run `spicetify restart` see if it launches normally?
And how do you start Spotify after close it?

**Comment by Bluscream** [comment]
Funnily enough i have the same problem on my cloud pc but not on my local pc

**Comment by Rawerooo** [comment]
`spicetify restart` and `spicetify restore` doesn't work. I've tried starting spotify in normal way, as administrator and in compatibility mode but nothing changes. Only reinstalling worked.

**Comment by khanhas** [comment]
Try run this in powershell and see if there is any error:
```
& "$env:APPDATA\Spotify\spotify.exe"
```
