### ISSUE TITLE
Spicetify Error

### ISSUE THREAD

**Issue by Breadleaf** [khanhas/spicetify-cli#377]
'BOM: read /home/<user_name>/.var/app/com.spotify.Client/config/spotify: is a directory'
I tried searching for a solution to what this means on google but couldn't find a answer. Am I doing something wrong?

**Comment by khanhas** [comment]
Can I see your config file?

**Comment by Breadleaf** [comment]
Hi khanhas, I am sorry for taking so long with this reply. I messed up while dual booting windows with the machine I was having the issue on and destroyed it in the process. I am currently in the process of reinstalling all of my old apps and files. If I run into any other issues I will be sure to comment here again. Sorry for taking up room on your Issues tab.
