### ISSUE TITLE
Modifying Spotify's CEF build

### ISSUE THREAD

**Issue by itsmeow** [khanhas/spicetify-cli#379]
Spotify runs on CEF, of course, but it's also a really garbage stripped-down CEF. I specifically need H.264 support, which is disabled by default on their build, because it's proprietary. Would it somehow be possible to add functionality that allows a different version of CEF to be applied to Spotify in a manageable way? I'm currently working on bringing Canvas to the Spotify desktop client with an extension, and I've got everything working except for the fact that it can't play the Canvases because they're H.264. Theoretically, one could just drag and drop replace Spotify's CEF paks and DLLs with a new version and so long as it has whatever features the client uses, it should just *work*. If Spicetify added a somewhat more sustainable way to do this that also included backups, it would be pretty useful.

I do admit however that the idea is a bit crazy for something so small, but it could have other uses for things like Flash (RIP) or other plugins that have to be compiled into CEF?

**Comment by itsmeow** [comment]
Update: The word "Theoretically" does not apply anymore. You can absolutely drag-and-replace Spotify's CEF build. For more info check the README of https://github.com/itsmeow/Spicetify-Canvas

**Comment by khanhas** [comment]
Very fascinating result! Good work.
But I can't see any application for theme community, I don't think this should be included in spicetify-cli. Debugging problems with binary modification and provide support on all three platforms are a bit out my league.
Also isn't this simply drag-and-replace CEF DLL files? I think making scripts (`powershell` for Windows, `sh` for Linux and MacOS) to apply these new DLL is sufficient for your purpose.
