### ISSUE TITLE
The location of Spotify Prefs has changed

### ISSUE THREAD

**Issue by ndv99** [khanhas/spicetify-cli#380]
### Describe the bug
The prefs path is no longer the one defined in the program and causes issues.

### To Reproduce
Run the program on a fresh installation of Spotify Desktop (obviously not Windows Store) and try to backup or apply something. You will see that the path is not found

### Error report
`error C:\Users\<username>\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist`

### System information
* **Rainmeter Version:** 4.3.1
* **OS Version:** Windows 10 Pro 2009 64-bit (build 19042) - English (2057)

# Suggested Solution

**The new path is "C:\Users\<username>\AppData\Roaming\Spotify\prefs", I have confirmed this to work.**

**Comment by khanhas** [comment]
It's because you switched from Spotify Windows Store version to normal Spotify version.
Just delete config file and it should auto recognise new location.

**Comment by Ridfoo** [comment]
how to delete it

**Comment by Ridfoo** [comment]
> It's because you switched from Spotify Windows Store version to normal Spotify version.
> Just delete config file and it should auto recognise new location.

where to delete it

**Comment by khanhas** [comment]
Run `spicetify --help` to know everything
