### ISSUE TITLE
Unable to apply after Spotify update

### ISSUE THREAD

**Issue by dmattera** [khanhas/spicetify-cli#382]
Spotify updated to version 1.1.51.380.ga06fdc8d last night.

When trying to run `spicetify backup apply` to re-apply my config, I get the following:

    spicetify v0.9.9
    info There is available backup.
    info Clear current backup:
    success Backup is cleared.
    Backing up app files:
    OK
    Extracting:
    [ 30 / 32 ] stations         fatal open /users/dmattera/.config/spicetify/Extracted/Raw/xpui/xpui-routes-collection-local-files.js: too many open files

**Comment by khanhas** [comment]
Please upgrade your spicetify. Reinstall Spotify and try again.

**Comment by dmattera** [comment]
Shoot, sorry about that didn't realize I wasn't on the lastest release. Confirmed that following these steps resolved the issue. Thank you!
