### ISSUE TITLE
Cant install extensions

### ISSUE THREAD

**Issue by OhItsTom** [khanhas/spicetify-cli#384]
after a bunch of crashing issues i thought i'd reinstall only to find literally 0 extensions will load
![image](https://user-images.githubusercontent.com/22730962/105559385-eea75f80-5d08-11eb-8a49-2c0bbfc39641.png)

**Comment by khanhas** [comment]
Run this and see if extensions files are available:
```
ls ~/spicetify-cli/Extensions
```

**Comment by daksh2k** [comment]
Add the full name of extension with file format at the end which is ".js"
`spicetify config extensions keyboardShortcut.js` Like this
`spicetify config extensions shuffle+.js`
`spicetify apply`
