### ISSUE TITLE
Spicetify doesn't run on my Spotify fro some reason

### ISSUE THREAD

**Issue by DeadTec9s** [khanhas/spicetify-cli#389]
![Issue](https://user-images.githubusercontent.com/77972339/105710154-9fcb1700-5f0e-11eb-85c9-e8701a6137df.jpg)

I redownloaded and downloaded Spotify a few times and it still replies with this message
"Backing up app files:
error Cannot backup app files. Reinstall Spotify and try again."

Any ideas?
Thanks.

**Comment by DeadTec9s** [comment]
(EDIT) now it says
\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.

**Comment by Bluscream** [comment]
You need the normal version of spotify, not the Windows Store version

**Comment by DeadTec9s** [comment]
I have now but it still says
\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.

**Comment by rhaokiel** [comment]
Either update config.ini (located at %userprofile%\.spicetify ) with the new spotify path or delete it and rebuild spicetify.

**Comment by khanhas** [comment]
Delete config file and try `spicetify backup apply` again.

**Comment by DeadTec9s** [comment]
how do i delete it?

**Comment by rhaokiel** [comment]
The file exists at `%userprofile%\.spicetify\config.ini`. You can find it by choosing 'Run...' from the start menu (or pressing WinKey + R) and typing in `%userprofile%\.spicetify\`

**Comment by DeadTec9s** [comment]
thanks so much everyone,
one last thing before i end the discussion,  how do i select which thee i want to put on use, so ive put them all in the themes file, but how do i seect which one to enable. Thanks

**Comment by DeadTec9s** [comment]
and where do i install the fullappdisplay.js extension file from

**Comment by khanhas** [comment]
Please read Wiki page.
