### ISSUE TITLE
detecting Spotify-Connect

### ISSUE THREAD

**Issue by fleixi** [khanhas/spicetify-cli#39]
Spotify-Connect is driving me crasy. Is there any way to detect if a song is played on the device itself or the client is only used as an remove via spotify-connect.

With that information i could try to add some workarounds in my code or disable my functions wile a other device is playing.

**Comment by khanhas** [comment]
Sorry. I don't quite understand what is the problem you have.

**Comment by Bluscream** [comment]
@khanhas you know the function where you can remote control spotify on your pc with your phone for example. he means that. He wants to know if its a remote control or local session

**Comment by khanhas** [comment]
```javascript
Spicetify.Player.origin.remotePlaybackBar._activeDevice()
```
should have what you are looking for.

**Comment by khanhas** [comment]
```javascript
Spicetify.Player.origin.remotePlaybackBar._activeDeviceIsLocal()
```
is even better

**Comment by fleixi** [comment]
Thanks thats what im looking for
