### ISSUE TITLE
My DribbbilsihDynamic looks slightly different

### ISSUE THREAD

**Issue by DeadTec9s** [khanhas/spicetify-cli#393]
![image](https://user-images.githubusercontent.com/77972339/105996801-bb672680-60a2-11eb-96ff-56286eae6d6c.png)
above is mine, with album art on the right, and below is the preview with the album art on the left
![image](https://user-images.githubusercontent.com/77972339/105996911-e18cc680-60a2-11eb-9f32-b60938082818.png)
how do i move it there?

**Comment by Mozartuss** [comment]
It's look like you use the "normal" Dribbblish theme and not the Dynamic one
The first picture shows the DynamicDribbblish theme
The second picture shows the normal Dribbblish theme
