### ISSUE TITLE
How to add text to the left side panel with DribbbilsihDynamic Theme.

### ISSUE THREAD

**Issue by dalcop** [khanhas/spicetify-cli#397]
Is it possible to add text to the left side panel and time stamp on the seek with DribbbilsihDynamic theme? I tried to tweak user.css (C:\Users\%userprofile%\.spicetify\Themes\DribbblishDynamic\user.css) of DribbbilsihDynamic theme but it didn't work.
![Spotify_EkpHjMGKP3](https://user-images.githubusercontent.com/74777981/106219720-fdf24580-61ff-11eb-95cf-c27e89c8476d.png)

**Comment by khanhas** [comment]
It's possible. Learn CSS, use devtool to try it out and edit `user.css` to make it permanent.
