### ISSUE TITLE
Spotify issues

### ISSUE THREAD

**Issue by 1R0SE** [khanhas/spicetify-cli#398]
Sorry to bother you guys, but whenever I try and enter the last line of code "spicetify backup apply". It gives me an error. This is my first time trying any kind of visualizer, so it's probably just me messing it up. If u can tell how to fix it, it would be appreciated.  

 "error C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.151.380.0_x86__zpdnekdrzrea0 does not exist or is not a valid path. Please manually set "spotify_path" in config.ini to correct directory of Spotify.
PS C:\Users\annar> spicetify backup apply"

**Comment by khanhas** [comment]
Please remove config file:
```
Remove-Item $(spicetify -c)
```
then run:
```
spicetify backup apply
```

**Comment by winaalkerchief** [comment]
@khanhas Thank you so much for this; I've been struggling for hours and just seen your solution. It helps me a lot. Thank you.
