### ISSUE TITLE
How cna i take this and add it to another theme

### ISSUE THREAD

**Issue by Hamish123456** [khanhas/spicetify-cli#399]
hi,

want to add this to another theme. Can't find what code to copy over from the user.css
<img width="383" alt="This" src="https://user-images.githubusercontent.com/78527187/106855100-81d09400-6710-11eb-8180-bdee273b8a4c.png">

**Comment by Hamish123456** [comment]
The theme is called Dracula

**Comment by khanhas** [comment]
Sorry, please ask customising question on Discussion page or Spectrum forum.

**Comment by Hamish123456** [comment]
ok thanks
