### ISSUE TITLE
Issue with Backup

### ISSUE THREAD

**Issue by blackheron** [khanhas/spicetify-cli#4]
I'm having an issue in MacOS that is preventing a proper backup. 
`Backing up app files:
OK
Extracting:
[31 / 31] OK
Preprocessing:
[30 / 31] stations            fatal open /usr/local/bin/jsHelper: no such file or directory`

Any commands there on out fail to work as well. For example, update, which says that it cannot find the default theme.

**Comment by khanhas** [comment]
Thank for your report. I remember I well tested it many times and it worked perfectly.
Maybe new version of Homebrew doesn't allow me to copy `spicetify` assets to `bin` folder anymore.
Right now, please follow this instruction to install and run `spicetify` manually without using Homebrew: https://github.com/khanhas/spicetify-cli#linux-or-macos-prebuilt 
Remember to remove/uninstall `spicetify-cli` in Homebrew first

**Comment by blackheron** [comment]
Thanks, got it to work!

**Comment by khanhas** [comment]
Fixed.
Try install it with brew again.
