### ISSUE TITLE
Cannot get to detect path though provided

### ISSUE THREAD

**Issue by poplipopatpotty** [khanhas/spicetify-cli#40]
Hi, 
I have installed Spotify from Ubuntu App Store 
Spicetify via your manual guide of downloading zip file then placing it etc. etc.

Spotify works normally
Spicetify is installed properly

but it can't find spotify's path

These I guess are my Spotify's paths:

/home/<username>/snap/spotify
/home/<username>/snap/spotify/35/.config/spotify
/home/<username>/snap/spotify/common/.cache/spotify

This is the spicetify config file (which I'm editing):
/home/<username>/.config/spicetify/config.ini

AND THIS IS THE CONFIG FILE THAT IS EDITED:

[Setting]
overwrite_assets = 0
spotify_path     = 
prefs_path       = /home/<username>/snap/spotify
current_theme    = ShadowStyle
color_scheme     = 
inject_css       = 1
replace_colors   = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
experimental_features        = 0
lyric_always_show            = 0
lyric_force_no_sync          = 0
made_for_you_hub             = 0
extensions                   = 
fastUser_switching           = 0
home                         = 0
new_feedback_ui              = 0
radio                        = 0
search_in_sidebar            = 0
song_page                    = 0
visualization_high_framerate = 0
custom_apps                  = 

; DO NOT CHANGE!
[Backup]
version = 

the output of  **find | grep "spotify/prefs$"** command:

find: ‘./.config/Thunar’: Permission denied
find: ‘./.config/xfce4/xfconf/xfce-perchannel-xml’: Permission denied
find: ‘./.dbus’: Permission denied
find: ‘./.gvfs’: Permission denied
find: ‘./.cache/dconf’: Permission denied
./snap/spotify/35/.config/spotify/prefs

**Comment by khanhas** [comment]
As I mentioned in Installation wiki page. There is no way to change/edit/replace Snap's app files, hence spicetify cannot apply modification on it. 
Follow these steps if you still want to mod Spotify:
https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-snap

**Comment by poplipopatpotty** [comment]
Thanks, Problem is resolved
