### ISSUE TITLE
Fonts missing after system restart 

### ISSUE THREAD

**Issue by LeoLTM** [khanhas/spicetify-cli#404]
I applied the "Elementary" theme but everytime I restart my PC and open Spotify again, the fonts are missing again (Raleway and Google sans (I changed Google sans to open Sans in the CSS but the issue existed before), which I both had to install manually). They show up as "installed" in the system settings and I can use them in other applications like MS Word. 
Can someone help me out?

**Comment by khanhas** [comment]
Can you provide which platform are you on? and what is your Spotify version?

**Comment by LeoLTM** [comment]
> 
> 
> Can you provide which platform are you on? and what is your Spotify version?

I'm on Windows 10 Pro 64bit and my Spotify version is 1.1.52.687.gf5565fe5

**Comment by khanhas** [comment]
I'm sorry, I can't think of anything could be the problem. If you already installed the font locally, it technically should work. I think this is more theme problem or chrominium bug than spicetify problem.
