### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by underscore-bama** [khanhas/spicetify-cli#407]
FYI: Spicetify was unable to run using the prebuilt binary or homebrew method. However, downloading the source, installing go via homebrew and self building allowed the application to build correctly for amd64. After that the application works perfectly with no modifications to the source.

**Comment by khanhas** [comment]
Huh, aren't you suppose to build with `GOARCH=arm64` for M1?

**Comment by underscore-bama** [comment]
Nah. Just installed homebrew, installed go, and then ran `go build -o spicetify` and it's all running perfectly. Didn't need any flags of any sort. Just thought any other M1 owners might want to know this.

**Comment by khanhas** [comment]
Well, if you don't know how it works behind, don't be so sure about `amd64` you mentioned in your original post.
Can you check your `go` version and all build variables of `go`, like GOOS, GOARCH? I can't build for arm64-darwin with current stable version of go.

**Comment by underscore-bama** [comment]
So no offense but you're kind of coming off as a dick. I simply submitted my experience for people who have a similar chip. The prebuilt/and your homebrew installs also did not work on my Mac Mini M1, so I did exactly what I posted above there as well and now Spicetify runs perfectly on it as well. I didn't do anything special, set any build flags, or anything. Anyways, here is the information you requested: 

```
$ go version
go1.16rc1 darwin/arm64

$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/bama/Library/Caches/go-build"
GOENV="/Users/bama/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bama/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bama/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.15.7_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.15.7_1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z7/zs1jnjn1465bl7lxb26nrp180000gn/T/go-build1218328064=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by khanhas** [comment]
Your Go info clearly said your platform is `arm64` while you told other users to compile as `amd64`, which is completely different thing. `amd64` binary could be run normally on M1 but Rosetta has to be on. Go only supports `arm64` for MacOS recently in version 1.16 and it hadn't been released as stable version yet. I called you out to double check and you told me I'm a dick.

**Comment by underscore-bama** [comment]
I told you the manner in which you were coming off was being a dick dude. All you had to say was you're compiling arm not amd or something to that gist instead you chose to throw in the extra "if you don't know how it works" bullshit which was unnecessary. I never stated I had anything other than the steps that I went through to get the application to build in a usable manner for M1. Did I miss amd/arm, sure, but there wasn't a reason to be insulting.

**Comment by adolphnov** [comment]
> FYI: Spicetify was unable to run using the prebuilt binary or homebrew method. However, downloading the source, installing go via homebrew and self building allowed the application to build correctly for amd64. After that the application works perfectly with no modifications to the source.

Hi, friend, I've never used go to compile software, can I take the liberty to ask how to use go to compile this project?

**Comment by afonsojramos** [comment]
@adolphnov check out our [Docs](https://spicetify.app/docs/development/compiling)! 😃
