### ISSUE TITLE
Spotify is glitching

### ISSUE THREAD

**Issue by Digginghole** [khanhas/spicetify-cli#409]
![Screenshot (545)](https://user-images.githubusercontent.com/78884859/107585386-1007b700-6bf6-11eb-8412-6a82c918a44c.png)

Just installed the skin and backed up and applied but Spotify looks like this.

I've redownloaded spotify and tried backed up again and I Unchecked inject CSS but still no luck.

**Comment by khanhas** [comment]
Reinstall Spotify and follow this guide: https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user
