### ISSUE TITLE
link to profile inserted in menu

### ISSUE THREAD

**Issue by JulienMaille** [khanhas/spicetify-cli#411]
From what I understand the following code is responsible for inserting items into the profile drowdown menu.
One of those items (the only one?) being the profile name which is shown with an ugly id
Is there a way to make it optional, or detect it and change text on the fly with maybe "profile"
What's the reason for that code? It seems to only insert that item.
![image](https://user-images.githubusercontent.com/182520/107847900-a652fd00-6def-11eb-9ea6-0d320502aa87.png)

https://github.com/khanhas/spicetify-cli/blob/f9ebab819516e1c71be7e8cc6c9a6ac694253680/jsHelper/spicetifyWrapper.js#L1411-L1434

**Comment by JulienMaille** [comment]
Right now I'm using a dirty css trick to hide it
```css
.Menu__root-items button:first-child {  
    display: none;
}
```

**Comment by khanhas** [comment]
Not a spicetify-cli problem. That's Dribbblish feature, check dribbblish.js and remove it.

**Comment by JulienMaille** [comment]
@khanhas is there a trick to insert an item at the end of the menu?
```js
// Add "About" item in profile menu
new Spicetify.Menu.Item("About", false, () => window.open("spotify:app:about")).register();
```

**Comment by khanhas** [comment]
No, sorry, it was hard-coded to prepend.
