### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by sheeepdev** [khanhas/spicetify-cli#413]
How do I update spicetify-cli without reinstalling it? I don't want my config to be deleted and I don't want to download all themes and extensions again.. is there a command that upgrades spicetify-cli

I'm using 1.1.0 and 1.2.0 is available from releases

**Comment by khanhas** [comment]
```
spicetify upgrade
```
Everything spicetify can do lies in `--help`, please run `spicetify --help` and read before open any issue.
If you upgrade it using method you used to install it, none of them delete your "personal" directories or config file.
Your personal directories location can be found in wiki, please read them too.

**Comment by sheeepdev** [comment]
> 
> 
> ```
> spicetify upgrade
> ```
> 
> Everything spicetify can do lies in `--help`, please run `spicetify --help` and read before open any issue.
> If you upgrade it using method you used to install it, none of them delete your "personal" directories or config file.
> Your personal directories location can be found in wiki, please read them too.

Oh, thanks!
