### ISSUE TITLE
Missing file %appdata%\Spotify\Apps\login\css\user.css 

### ISSUE THREAD

**Issue by Robzyy** [khanhas/spicetify-cli#416]
Hey Khan, Robz here! 👋 

I have a slight issue: 
```
$ spicetify apply
spicetify v1.2.0
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
fatal open C:\Users\cclip\AppData\Roaming\Spotify\Apps\login\css\user.css: The system cannot find the path specified.
```

I have tried `spicetify restore` and `spicetify backup` but it doesn't solve the problem...

**Comment by Robzyy** [comment]
My bad it looks like I wasn't running latest Spotify **fuck me**

**Comment by Robzyy** [comment]
It happened again.

**Comment by khanhas** [comment]
1.Reinstall spotify
2.Delete config file (Run `spicetify -c` to know where it is)
3. Run `spicetify backup apply`

**Comment by Robzyy** [comment]
Thank u! ♥
