### ISSUE TITLE
Unable to use F and `/` vim bindings

### ISSUE THREAD

**Issue by matildeopbravo** [khanhas/spicetify-cli#417]
I'm glad you like it!
Your suggestions are reasonable, I should comply with keyboard-driven softwares out there instead of inventing my own keybinds.

I did make a few changes here: https://github.com/khanhas/spicetify-cli/blob/7f8205a50d69166bf865547e7a4ccbb277766f5a/Extensions/keyboardShortcut.js

If you have time, please test it out. 

I added `G/Shift+G` scroll top/bottom, `/` to search, changed navigating forward/backward to `shift+H/L`, activate follow link function to `F` and added some documentation for users who want to change or add their own keybinds.

If you think of any more feature that are suitable for Spotify client, please do tell me.

_Originally posted by @khanhas in https://github.com/khanhas/spicetify-cli/issues/27#issuecomment-500331931_

According to khanhas, that feature has been implemented. However, despite having vim extension installed and being able to use every other feature, I can't seem to be able to use these two.

**Comment by khanhas** [comment]
Which two you can't use? 
I just checked and seems `G/Shift+G`, `/`, `shift+H/L` and `f` work fine on my end.

**Comment by matildeopbravo** [comment]
I can't use `/` and `F` @khanhas

**Comment by khanhas** [comment]
Oh sorry, I missed the title 😆 
Do you have a custom keyboardShortcut.js? Can you run `spicetify path -e` so I can check its path.
Just to be sure, here what to expect when you hit these buttons:
- `/` will give focus on search input field, type something Spotify will switch to search view immediately.
- `f` (don't hold shift) will pop up small link followers at near all visible links:
![image](https://user-images.githubusercontent.com/26436809/108301872-96bc2580-71ee-11eb-97dd-37d4f01ae894.png)

**Comment by matildeopbravo** [comment]
I ran the command you asked me to. 
![image](https://user-images.githubusercontent.com/56790511/108447213-678dce80-7257-11eb-842a-3d5e2e56e351.png)
Btw, the f works fine. In your comment I saw capital f and I thought it was another binding(f  + shift) but it was my mistake, it has worked all along. As for the search, sadly it does not work at all and it's a very important feature for me.

**Comment by khanhas** [comment]
I saw you put `keyboardShortcut.js` in your personal Extensions folder. `keyboardShortcut.js` comes with spicetify-cli package by default so I don't know if your keyboardShortcut.js misses feature or contains old code.
Just delete it, make sure your spicetify is up-to-date and run `spicetify apply`.

**Comment by matildeopbravo** [comment]
I deleted it as you said but the problem remains.

**Comment by khanhas** [comment]
I have no idea what could cause just that specific key to stop working. Can you check console (hit Ctrl + Shift + i) and hit the `/` on Spotify client to see if there is any error on function the key bound to.

**Comment by khanhas** [comment]
I don't know if you know javascript. You might want to try run this function manually line by line in Console and see where the problem's at:
https://github.com/khanhas/spicetify-cli/blob/master/Extensions/keyboardShortcut.js#L160

**Comment by matildeopbravo** [comment]
Ctrl + shift +i doesn't work either

**Comment by khanhas** [comment]
It's because you didn't enable devtool to access Console. Run this and try what I suggested again:
```
spicetify enable-devtool
```

**Comment by matildeopbravo** [comment]
I ran the command you told me to and I still couldn't access the console.

**Comment by khanhas** [comment]
😟 
Right click at player bar and see if there is any context menu pop up. 
![image](https://user-images.githubusercontent.com/26436809/108944891-5f92bc00-76a7-11eb-9763-3e988f1193ab.png)

**Comment by matildeopbravo** [comment]
![image](https://user-images.githubusercontent.com/56790511/108997834-01121180-7698-11eb-8a75-22a0ddb33f3a.png)
That does work. I was able to open the devtools. I saw these issues

**Comment by khanhas** [comment]
Okay you got into Console, phew.
Now focus on Spotify client and hit `/`, look at Console and see if there is any new error pop up.
If not, run the code I pointed earlier, line by line and see where it goes wrong.
