### ISSUE TITLE
Preprocessing error

### ISSUE THREAD

**Issue by Tomishpolo** [khanhas/spicetify-cli#419]
Hi,

When I run the command "spicetify backup apply enable-devtool", I have an error in the "Preprocessing" step. It wrote: "Cannot find symbol for Profile Sub Menu React".
The process ends and when I launch Spotify, I can connect but after the application remains on an empty solid background and even if I restart. I am on Windows 10 and I want to clarify that I am under version 1.0.8 of the Spotify client ... to block ads :)
Thank you for your help 

![image](https://user-images.githubusercontent.com/73855569/108394603-2b397e80-7215-11eb-83b5-4e4a09c97e26.png)

**Comment by khanhas** [comment]
Yeah sorry. I can't support ancient version of Spotify since its structure is very different from current one.
