### ISSUE TITLE
Dosen't work for me

### ISSUE THREAD

**Issue by shyvesCCD** [khanhas/spicetify-cli#421]
I'm don't know what i doing wrong but after the install command spicetify dosen't work.
![Screenshot_20210219_185910](https://user-images.githubusercontent.com/54871907/108566070-8dad8000-72e4-11eb-819b-fd2cceb49a19.png)
I'm on Linux Kubuntu 20.04

**Comment by khanhas** [comment]
What command doesn't work? Did you read wiki or help file?

**Comment by shyvesCCD** [comment]
The spicetify command is not recognized when I try to type it into the konsole.

**Comment by khanhas** [comment]
spicetify is a program of multiple command
I can see in your Konsole that help text display just fine, that means spicetify can be run.  Try `spicetify backup apply` and see if spotify changes.

**Comment by shyvesCCD** [comment]
i try to do that... i don't know what i doing wrong. 
![Screenshot_20210220_001144](https://user-images.githubusercontent.com/54871907/108582182-489f4300-7310-11eb-9ed6-0fc17a650b6f.png)

**Comment by khanhas** [comment]
Do you know where spicetify is installed?
How did you install spicetify?

**Comment by shyvesCCD** [comment]
i just copy and past the tutorial.

**Comment by khanhas** [comment]
Just run it again. It will tell what to do at the end.
