### ISSUE TITLE
--transparent-window-controls seems to have no effect

### ISSUE THREAD

**Issue by linuswillner** [khanhas/spicetify-cli#425]
Hi, I'm encountering an issue where passing `--transparent-window-controls` to the Spotify executable seems to have no effect at all.

Screenshot of client after running `Spotify.exe --transparent-window-controls`:
![Sample](https://i.linuswillner.me/We8iKSj.png)

As can be noted, the controls are still present. Could it be that Spotify changed something and this flag no longer works, or is this an issue with Spicetify?

**Comment by khanhas** [comment]
That's how it supposes to work. Plus, that's Spotify client feature, not mine, so nothing I can do to improve it.
