### ISSUE TITLE
Custom App: Reddit Unable to use

### ISSUE THREAD

**Issue by Xanaxus** [khanhas/spicetify-cli#428]
So I followed the steps in the wiki but i am unable to use it as it always a blank screen

OS:Linux
Latest build of spicetify

**Comment by khanhas** [comment]
What is your Spotify version?
Still works fine on 1.1.52

**Comment by Xanaxus** [comment]
I am using the latest spotify from flathub

**Comment by khanhas** [comment]
No idea flathub is and what version of Spotify it distrubutes.

**Comment by Xanaxus** [comment]
Its flatpak. and the version is 1.1.46.916.g416cacf1

**Comment by khanhas** [comment]
I only have access to version 1.1.42 on Linux and 1.1.52 on Windows. They both works fine so I don't think there will be any different on 1.1.46
Can you run this: 
```
ls -l $(spicetify config spotify_path)/Apps/
```
and check if reddit symlink is there and if it actually leads to reddit app directory:
![image](https://user-images.githubusercontent.com/26436809/109734385-a7b46000-7c0c-11eb-8d93-45adbaa343c3.png)
**Note**: Your reddit app directory is not necessary to be exactly like mine.

**Comment by Xanaxus** [comment]
```
[ivan@Fiona ~]$ ls -l $(spicetify config spotify_path)/Apps/
total 128
drwx------ 4 ivan ivan 4096 Feb 24 10:21 about
drwx------ 4 ivan ivan 4096 Feb 24 10:21 artist
drwx------ 4 ivan ivan 4096 Feb 24 10:21 browse
drwx------ 4 ivan ivan 4096 Feb 24 10:21 buddy-list
drwx------ 3 ivan ivan 4096 Feb 24 10:21 chart
drwx------ 3 ivan ivan 4096 Feb 24 10:21 collection
drwx------ 3 ivan ivan 4096 Feb 24 10:21 collection-album
drwx------ 3 ivan ivan 4096 Feb 24 10:21 collection-artist
drwx------ 3 ivan ivan 4096 Feb 24 10:21 collection-songs
drwx------ 3 ivan ivan 4096 Feb 24 10:21 concert
drwx------ 3 ivan ivan 4096 Feb 24 10:21 concerts
drwx------ 3 ivan ivan 4096 Feb 24 10:21 error
drwx------ 4 ivan ivan 4096 Feb 24 10:21 findfriends
drwx------ 4 ivan ivan 4096 Feb 24 10:21 full-screen-modal
drwx------ 3 ivan ivan 4096 Feb 24 10:21 genre
drwx------ 5 ivan ivan 4096 Feb 24 10:21 glue-resources
drwx------ 3 ivan ivan 4096 Feb 24 10:21 hub
drwx------ 3 ivan ivan 4096 Feb 24 10:21 legacy-lyrics
drwx------ 3 ivan ivan 4096 Feb 24 10:21 licenses
drwx------ 4 ivan ivan 4096 Feb 24 10:21 login
drwx------ 3 ivan ivan 4096 Feb 24 10:21 lyrics
drwx------ 3 ivan ivan 4096 Feb 24 10:21 playlist
drwx------ 3 ivan ivan 4096 Feb 24 10:21 playlist-folder
drwx------ 3 ivan ivan 4096 Feb 24 10:21 profile
drwx------ 3 ivan ivan 4096 Feb 24 10:21 queue
lrwxrwxrwx 1 ivan ivan   46 Feb 26 14:46 reddit -> /home/ivan/.config/spicetify/CustomApps/reddit
drwx------ 3 ivan ivan 4096 Feb 24 10:21 search
drwx------ 3 ivan ivan 4096 Feb 24 10:21 settings
drwx------ 3 ivan ivan 4096 Feb 24 10:21 show
drwx------ 3 ivan ivan 4096 Feb 24 10:21 station
drwx------ 4 ivan ivan 4096 Feb 24 10:21 stations
drwx------ 2 ivan ivan 4096 Feb 24 10:21 xpui
drwx------ 5 ivan ivan 4096 Feb 24 10:41 zlink
```

**Comment by khanhas** [comment]
reddit app is distributed with spicetify package, you don't have to put it in your personal CustomApps folder if you don't do any modification on it.
1. Delete `/home/ivan/.config/spicetify/CustomApps/reddit`
2. `spicetify restore backup apply`

**Comment by Xanaxus** [comment]
Did that now its trying to get the custom app from the following:
`/usr/share/spicetify-cli/CustomApps/reddit`

**Comment by khanhas** [comment]
Yes, that's right path. Does reddit work now?

**Comment by Xanaxus** [comment]
Nope, still blank
![image](https://user-images.githubusercontent.com/53279068/110202562-7bf4dc80-7e8f-11eb-86da-6f2c7cfb3bb4.png)
Should i try to reinstall it?

**Comment by khanhas** [comment]
You could try, I don't know any more. I'm out of idea

**Comment by Xanaxus** [comment]
ok i tried to do that i did a clean install of every thing but it was in vain :cry:

**Comment by Xanaxus** [comment]
I found the issue for some reason the spicetify-cli file from the AUR got deleted that's why it was not working well
