### ISSUE TITLE
Fullscreen Issue

### ISSUE THREAD

**Issue by lynchzival** [khanhas/spicetify-cli#429]
Fullscreen mode exit automatically on song end, skip, or next song is playing.

os windows 10
spicetify latest version
issue first found on latest spotify client, downgraded to 1.1.34.694.gac68a2b3 and is still occurring.

**Comment by khanhas** [comment]
Does not occur to me.
Does it happen only with spicetify applied?
Stick to latest Spotify and just small reminder that Full Screen is premium-only feature.

**Comment by lynchzival** [comment]
I have a free account and I completely unaware of that, It used to be available for free users back then and I haven't used the desktop client for quite some time now, actually come to think of it, installing spicetify must has had unlocked that feature back to me and everything would be perfect if only there isn't an issue as described above. I found an extension calls "spicetify-enable-fullscreen" but people are still report to have the same problem and the guy seems to no longer maintenance it, so ain't there any solutions around this?

**Comment by khanhas** [comment]
Sorry, I can't. It's premium-only, Spotify's making money off it, I can't hurt their livelihood.
