### ISSUE TITLE
[macOS] Error when installing

### ISSUE THREAD

**Issue by A1exInamin** [khanhas/spicetify-cli#43]
When I was installing spicetify with `brew install khanhas/tap/spicetify-cli`, I got following error log:

```==> go build -o spicetify
Last 15 lines from /Users/alex/Library/Logs/Homebrew/spicetify-cli/01.go:
2019-08-02 11:06:35 +0900

go
build
-o
spicetify

go: finding github.com/go-ini/ini v1.42.0
go: finding github.com/mattn/go-colorable v0.1.1
go: finding github.com/mattn/go-isatty v0.0.5
go: golang.org/x/sys@v0.0.0-20190222072716-a9d3bda3a223: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: error loading module requirements

Do not report this issue to Homebrew/brew or Homebrew/core!
```

And I tried to manually access the address `golang.org/x/sys@v0.0.0-20190222072716-a9d3bda3a223`, but just got a 404 not found. Seems like this tag of release has been deleted?

**Comment by graveszhang** [comment]
same problem

**Comment by xasxcy** [comment]
I have this problem too.

**Comment by khanhas** [comment]
I'm currently extremely tight with time on uni assignments so I can't spend too much time setting up macOS right now.
@graveszhang , @xasxcy , @A1exInamin If you don't mind, please use pre-built package by following this instruction: 
https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-or-macos-prebuilt

**Comment by freeqimmy** [comment]
@khanhas I tried the pre-built package and here comes 'fatal open /usr/bin/Users/freeqimmy/spicetify/jsHelper: not a directory' while preprocessing, do you have any idea👀 btw your work is amazing❤︎❤︎

**Comment by khanhas** [comment]
@freeqimmy Can you open that directory to see if it's actually not there?
If it isn't, please download and extract prebuilt package again.

**Comment by freeqimmy** [comment]
@khanhas the directory is already there and I can open it manually, I tried to extract prebuilt package again but it aint work

**Comment by khanhas** [comment]
I really don't know. If you extracted successfully and the file is there, I don't see any reason why it throws that error.

**Comment by khanhas** [comment]
@A1exInamin @xasxcy @graveszhang 
Can you try install again? I believe it's just golang host temporary problem.

**Comment by A1exInamin** [comment]
> @A1exInamin @xasxcy @graveszhang
> Can you try install again? I believe it's just golang host temporary problem.

Tried, but still got the same error.

I'd better keep using the pre-built package LOL

**Comment by nicehiro** [comment]
Maybe you are in China, I had the same problem here. And I fix it just by trying another go repo mirror. You can give it a try [here](https://github.com/goproxy/goproxy.cn). @A1exInamin @graveszhang @khanhas 

![image](https://user-images.githubusercontent.com/17773634/66044473-358da680-e554-11e9-8647-41865f80f2bf.png)

**Comment by tin-the-element** [comment]
Has there been a fix for the fatal open /usr/bin/Users/tintheelement/spicetify/jsHelper: not a directory error?

**Comment by luis815** [comment]
I didn't get any errors while installing it.  My guess would be to use the brew method.  If the China restriction is the problem, then definitely try the proxy method above.  From the original issue, it does seem like a connection issue with go requirements.
