### ISSUE TITLE
Powershell...

### ISSUE THREAD

**Issue by Sakooooo** [khanhas/spicetify-cli#430]
Powershell doesnt recognize command spicetify after adding python to path. Any fix?

**Comment by khanhas** [comment]
Why you added "python" to path, python has nothing to do with spicetify.

**Comment by khanhas** [comment]
Check your environment path if there is spicetify location in it. If not, reinstall spicetify using the script and restart your Windows.

**Comment by Sakooooo** [comment]
ok ty

> 
> 
> Why you added "python" to path, python has nothing to do with spicetify.

I installed it to path for something else
