### ISSUE TITLE
How do I contribute to the documentation?

### ISSUE THREAD

**Issue by UNlDAN** [khanhas/spicetify-cli#431]
I had a great deal of trouble on how to actually _use_ this program. There was so much about _how it works_ that I got lost trying to find out _how to use it_. I have figured it out now, but I would love to contribute so future users don't have to go through this agonizing process again. 

Thanks!!

**Comment by khanhas** [comment]
What processes you went through exactly? Help text is not enough?

**Comment by UNlDAN** [comment]
> What processes you went through exactly? Help text is not enough?

I was referring to the actual usage process of it. How to download spicetify on powershell, apply the initial command, pasting the theme to the folders, selecting the theme, then applying it. It was not easy to find this info in the docs, I used an online tutorial.

**Comment by khanhas** [comment]
1. https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage
2. On how to use community themes, there is usage instruction on its own repo.

**Comment by UNlDAN** [comment]
> 1. https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage
> 2. On how to use community themes, there is usage instruction on its own repo.

Personally, I feel that all that info should be in one common place, but to each their own :)
