### ISSUE TITLE
What are these keys used for?

### ISSUE THREAD

**Issue by patri9ck** [khanhas/spicetify-cli#432]
```
pressing_fg = d42121
pressing_button_bg = d42121
selected_button = d42121
miscellaneous_bg = d42121
preserve_1 = d42121
```
I created a theme and set the color of those elements to red (#d42121) to find out where they are used. Unfortunately, I cannot find anything that is red in my current Spotify theme. So what are those values used for? What do they change?

**Comment by khanhas** [comment]
If they're not visible, ignore them.
