### ISSUE TITLE
currently playing on disappeared

### ISSUE THREAD

**Issue by handrei** [khanhas/spicetify-cli#439]
hello everyone!

firstly I wanna thank you for this project, it's amazing. good job.

secondly, after I installed the app on macOS, the currently playing on disappeared.(when I'm playing on Spotify connect)  it's not possible to have it back? it was a cool feature.

**Comment by khanhas** [comment]
1. You are still able to access list of devices via icon on player bar
2. Learn how to use devtool and edit user.css to enable it back.
