### ISSUE TITLE
[Windows] Update command wont run because user.css file not found.

### ISSUE THREAD

**Issue by damianpetroff** [khanhas/spicetify-cli#44]
Hi,

After having installed the pre-built package with PowerShell :
```
Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
```
I specified the Spotify folder in `config.ini`, which is `C:\Users\me\AppData\Roaming\Spotify`, and then when running :
```
spicetify update
```
The following error appears :
```
fatal open C:\Users\me\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The specified path does not exist.
```
In fact, there is no sub-folder in `\Apps\`, only a couple (30 actually) `.spa` files. Among them is `zlink.spa` by the way.

The question is : Did I do something wrong or is the current installation guideline deprecated ?
Thanks for your time, keep up with this project.

**Comment by khanhas** [comment]
You havent run `spicetify apply`

**Comment by damianpetroff** [comment]
Oh ok, probably my mistake I didn't notice that was mentioned anywhere...

Now it ran a sort of scan Spotify files, but then I got this error :
```
BOM: read C:\Users\me\AppData\Roaming\Spotify: Descripteur non valide
```
"Descripteur non valide" is french for "Invalid descriptor" I suppose

**Comment by khanhas** [comment]
Can you reinstall Spotify and follow this instruction
https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage

**Comment by damianpetroff** [comment]
Sure,

Here's what I get :

![](https://i.imgur.com/HDUKh3Z.png)

**Comment by khanhas** [comment]
Can you double check that you are **not** using Spotify Windows Store version?

**Comment by SirEssGee** [comment]
@damianpetroff I was having a similar issue and then managed to figure it out. Is your prefs_path defined in your config.ini?

Make sure it is defined as the actual prefs file, which can be found in the same spot as your Spotify application as long as it was downloaded through a web browser and not the Microsoft Store.

![prefs_path file location](https://user-images.githubusercontent.com/54054536/62918032-6fb8a400-bd6c-11e9-90a6-8ee38586af8d.png)

**Comment by khanhas** [comment]
Close due to inactivity.

**Comment by MeDemon0** [comment]
you need to go to your user folder and delete .spictefy folder. reinstall everything and you'll be good to go
