### ISSUE TITLE
Unable to access settings while using a spicetify theme.

### ISSUE THREAD

**Issue by SetuCoder** [khanhas/spicetify-cli#441]
### As shown below in the demonstration, I cannot open the settings page of the Spotify app when I'm using a spicetify theme. I really want to get into it because I wanna disable 'open at startup'. Note that I'm using macOS 11.2.1 Big Sur. Please respond to this asap. 

https://user-images.githubusercontent.com/58362876/110238150-f4c66800-7f65-11eb-8927-413bcb318f34.mov

**Comment by khanhas** [comment]
Duplicate
