### ISSUE TITLE
Cannot get trash icon to show up

### ISSUE THREAD

**Issue by will5757** [khanhas/spicetify-cli#45]
I'm not sure this is the right spot to be asking for help, but my google skills have failed me.

I have Spicetify installed, and the skins work, but I cannot figure out how to get the trash plugin to work.

Config file line was edited to this "extensions                   = trashbin.js|", also tried without the | symbol.

The .Js file is in both the .spicetify folder and the spicetify cli folder

**Comment by khanhas** [comment]
Did you run `spicetify apply` after that?

**Comment by will5757** [comment]
well....that was easy.
Thanks,  did try several commands but i guess i missed that one
