### ISSUE TITLE
New releases needs a little improvement

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#450]
Check this site https://spotifyreleaselist.netlify.app/
Unlike extension, it shows not only albums and singles of your favorite artists, but also guest releases (you can configure it). That is, now, in the extension, if my favorite artist appears on someone else's album , I will not know about it, although it is strange that this isn't displayed, cause the check mark is removed from "Followed artists only". Maybe it's a bug? Because no difference with this check mark, and without it.

**Comment by khanhas** [comment]
1. I'm content with the extension right now, it does exactly what it needs to, no more no less. If there is any improvement you think that suits your need, please do look through the code of both project, make change, add new context menu option and pull request. I will assist and improve your code if it is necessary. 
2. "Get artists" API provided by Spotify client will give all artists that you liked at least one of their tracks. If "Followed artist only" option is on, the extension will filter only artists you follows. I don't know whether there is any better API, I just pulled the code out of original "Artists" app of Spotify client.
3. How long does https://spotifyreleaselist.netlify.app/ take to refresh new releases list on your machine? Mine is 12s.

**Comment by FiftyFour7250** [comment]
Less than two seconds for me. Maybe it's taking so long for you cause it's your first time...

Yea, you're right Spicetify extension works well, and does no more, no less. It's just that there are artists who don't release albums and singles for several years or more, but every few months they appear on other artists releases. And it's pity that there is no opportunity to learn about this in Spotify, much remains unheard, so I still have to use https://spotifyreleaselist.netlify.app/ . Unfortunately, I'm so stupid I don't understand programming, hope someone will be interested in this idea, and will be able to implement it.
