### ISSUE TITLE
Button for Genius App

### ISSUE THREAD

**Issue by livepo88** [khanhas/spicetify-cli#454]
Hi. Is it possible somehow add a button to the player bar, so that when I click it, I would be thrown into the Genius custom app tab? I have a lot of playlists, and if I listen to something from the bottom of the list, then when I want to read lyrics - it's not very convenient to go back up, it would be cool if it was pinned

**Comment by FiftyFour7250** [comment]
I want it too. I'm not a programmer, and I have absolutely no experience in this, but I found a similar extension, took a part from there, in general it adds a button, but... it doesn't work. Probably something in this part:

```
b.onclick = () => {
            if (document.getElementById("spotify:app:genius").style.display === "block") {
                closeNav();
            } else {
                openNav();
            }
        };
        return b;
    }

```


All code:

```
(function spotifyLyrics() {
    if (!Spicetify.LocalStorage) {
        setTimeout(spotifyLyrics, 1000);
        return;
    }

    // Setup the mode 
    let isEnabled = Spicetify.LocalStorage.get("lyrics") === "1";

    new Spicetify.Menu.Item("Lyrics Button", isEnabled, (self) => {
        isEnabled = !isEnabled;
        Spicetify.LocalStorage.set("lyrics", isEnabled ? "1" : "0");
        self.setState(isEnabled);
    }).register();


    function createLyricsButton() {
        const b = document.createElement("button");
        b.classList.add("button");
        b.innerText = "LYRICS";
        b.id = "lyricsButton"
        b.onclick = () => {
            if (document.getElementById("spotify:app:genius").style.display === "block") {
                closeNav();
            } else {
                openNav();
            }
        };
        return b;
    }

    // Create the lyrics buton
    const extraControlsContainer = document.getElementsByClassName("extra-controls-container");
    extraControlsContainer[0].prepend(createLyricsButton()); // prepend = append before all

})();
```

**Comment by FiftyFour7250** [comment]
Still not understanding anything, I managed to make a little progress. I added **href="spotify:app:genius"** to this inactive button in HTML source code, and the button worked. But it doesn't do much good. After all, when the page is updated, it disappears. How can I add it to the js extension? Or maybe it's possible to make a js extension that just always changes the HTML code to the right one? By the way, after digging into the HTML code of the page, I managed to find an even better button. And here's how it all looks now in HTML source code

![222222222222](https://user-images.githubusercontent.com/78786088/111422485-d39d0e80-86ff-11eb-991a-188ce2030199.JPG)

Fuck. My mom told me to study to be a programmer.

**Comment by livepo88** [comment]
Really appreciate your efforts. Although it looks like you need it a lot more than I :D

**Comment by FiftyFour7250** [comment]
DONE! 

Guy from stackoverflow told me about b. setAttribute('href', 'spotify: app:genius').

I also refused to use the Spotify Lyrics icon. Since the word is longer, it is easier to click.
```


(function spotifyLyrics() {
    if (!Spicetify.LocalStorage) {
        setTimeout(spotifyLyrics, 1000);
        return;
    }

    function createLyricsButton() {
        const b = document.createElement("a");
        b.classList.add("button");
        b.innerText = "LYRICS  ";
        b.id = "lyricsButton"
        b.setAttribute('href','spotify:app:genius')
        b.draggable = false
        b.onclick = () => {
            if (document.getElementById("spotify:app:genius").style.display === "block") {
                closeNav();
            } else {
                openNav();
            }
        };
        return b;
    }

    const extraControlsContainer = document.getElementsByClassName("extra-controls-container");
    extraControlsContainer[0].prepend(createLyricsButton()); // prepend = append before all

})();


```
