### ISSUE TITLE
no command

### ISSUE THREAD

**Issue by PIndividual** [khanhas/spicetify-cli#455]
the command spicetify does not work on macos after the install on terminal
reported:no such command

**Comment by TheAirGotCold** [comment]
I also don't have a command I'm on Linux mint. But I run it with /home/(username)/spicetify-cli/spicetify.

so maybe try typing its directory as the command.

**Comment by TheAirGotCold** [comment]
sudo ln /home/(username)/spicetify-cli/spicetify /bin/spicetify

this worked for me

**Comment by AlexanderEDavis** [comment]
You might need to go into the directory where the spicetify file is and run ./spicetify
