### ISSUE TITLE
File location not changing after uninstalling windows store version

### ISSUE THREAD

**Issue by ham-q** [khanhas/spicetify-cli#458]
Sorry if this is the wrong place to ask, but after realising that specitify needed the desktop app, I switched to it but the file location spicetify loops for when applying wasn't created on Spotify install, even after fully deleting all the files from my PC and doing a fresh desktop install. Any help with getting the proper file location installed or how to specify the new file location?

**Comment by khanhas** [comment]
Delete config file and try again.

**Comment by ham-q** [comment]
yep, works now, thanks! sorry for the basic question.
