### ISSUE TITLE
[question] Set default spotify theme

### ISSUE THREAD

**Issue by jkmpariab** [khanhas/spicetify-cli#463]
Sorry for this question on issue list. didn't found any discussion communication.
What i want to do is to not touch the default spotify theme (as if spicetify-cli never applied).
Thanks in advance.

**Comment by khanhas** [comment]
1. https://github.com/khanhas/spicetify-cli/discussions
2. Run:
```
spicetify config inject_css 0 replace_colors 0 overwrite_assets 0
spicetify apply
```
