### ISSUE TITLE
The GPL does not cover modifications to closed source projects

### ISSUE THREAD

**Issue by Cr3atable** [khanhas/spicetify-cli#465]
See http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF for more information.

**Comment by khanhas** [comment]
What License do you think I should change to?

**Comment by EwanLyon** [comment]
Seems like a pretty easy fix. Even says in the link what to do

>However, you can resolve that legal problem by adding an exception to your plug-in's license, giving permission to link it with the nonfree main program.

Just add something in the license saying the user is allowed to link it to Spotify

**Comment by Tread-2036** [comment]
Perhaps LGPL? https://github.com/khanhas/spicetify-cli/blob/master/LICENSE Line 669-674 suggests this.

**Comment by khanhas** [comment]
@Tread-2036 Thank you

**Comment by Tread-2036** [comment]
Hmm, it seems it's GPL again?
