### ISSUE TITLE
Error with prefs

### ISSUE THREAD

**Issue by kimlulz** [khanhas/spicetify-cli#468]
"error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini"

![screen](https://user-images.githubusercontent.com/42508318/112097666-c5f5f600-8be3-11eb-9752-c8f48c03f528.png)

The configuration is accurate, but it is still an error.

**Comment by kimlulz** [comment]
Solved

config.ini located in /root/.config/spicetify

**Comment by khanhas** [comment]
You don't have to use sudo with spicetify. Anyway, does not matter tho.
