### ISSUE TITLE
Extensions no longer work

### ISSUE THREAD

**Issue by levoothan** [khanhas/spicetify-cli#469]
I have alot of extensions including DJmode, Lyrics, History shortcut etc that have stopped appearing in the drop down list. Is this an issue with the extensions or the client itself? I lost my backup of the older spotify version so cant revert.

**Comment by khanhas** [comment]
1. Reinstall Spotify
2. Run: `spicetify backup apply`

**Comment by levoothan** [comment]
> 1. Reinstall Spotify
> 2. Run: `spicetify backup apply`

Didnt solve the issue.

**Comment by khanhas** [comment]
What is your platform and what is your Spotify client version

**Comment by levoothan** [comment]
> What is your platform and what is your Spotify client version

Windows 10 Spotify version 1.1.55.498.gf9a83c60-a

**Comment by levoothan** [comment]
correction 1.1.55.498.gf9a83c60

**Comment by Gaw18** [comment]
Also don't work on Debian bullseye

**Comment by khanhas** [comment]
Can you check your config file and see if those extensions were not accidentally removed?

**Comment by levoothan** [comment]
`extensions                   = bookmark.js|djMode.js|shuffle+.js|trashbin.js|queueAll.js|keyboardShortcut.js|loopyLoop.js|newRelease.js|webnowplaying.js|historyshortcut.js|spotifyLyrics.js|getcanvas.js|hidePodcasts.js|copyPlaylist.js|fullAppDisplay.js` Thats what Ive got. theyre all there but alot stopped working. some still work others dont. mainly those which need the dropdown menu with settings.

**Comment by khanhas** [comment]
I'm sorry. I don't know what happens on yours. They still works on mine:
![image](https://user-images.githubusercontent.com/26436809/113381168-a1f39b00-93c1-11eb-9370-d80d8937d5db.png)
![image](https://user-images.githubusercontent.com/26436809/113381192-b5066b00-93c1-11eb-9188-08bf93a964d5.png)

**Comment by khanhas** [comment]
What is your spicetify version? Can you make sure you are on latest?
If you're not already, please resinstall Spotify, upgrade Spicetify and run `spicetify backup apply`

**Comment by levoothan** [comment]
1.2.1 latest. I dont get why its not working it was before updating spotify. even when reinstalling it doesnt fix em.

**Comment by channer72** [comment]
Also having the same problem, I'm getting these errors when applying:

```
Transferring extensions:
error Extension "webnowplaying.js, newRelease.js, shuffle+.js, bookmark.js" not found.
OK
Creating custom apps symlinks:
error Custom app "genius" not found.
```

I've checked my files and they're all there.

**Comment by khanhas** [comment]
@channer72 Please read Extensions wiki page
Extensions names are separated by `|`
