### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ChocoTonic** [khanhas/spicetify-cli#472]
How do you uninstall this?

**Comment by khanhas** [comment]
Run `spicetify restore`

**Comment by NoName95x** [comment]
@khanhas 
That command does not work for me.

`error C:\Users\NAME\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.`

**Comment by khanhas** [comment]
Delete config file and try again. Or just reinstall if you don't want spicetify anymore.
