### ISSUE TITLE
BOM: read C:\Users\NAME\AppData\Roaming\Spotify\prefs: The handle is invalid.

### ISSUE THREAD

**Issue by Pukimaa** [khanhas/spicetify-cli#473]
If I run every command it gives me the error mentioned in the title. Already tried reinstalling both Spicetify and Spotify. Also if I run `spicetify` it just says `Run "spicetify -h" for commands list.`

**Comment by Pukimaa** [comment]
Alright, so after a few attempts, here's what I did (for anyone that might have the same issue)

I uninstalled spicetify-cli from my home folder, opened an admin PowerShell terminal, installed Chocolatey, installed spicetify-cli using Chocolatey, then set my prefs_path to C:\Users\jack\AppData\Roaming\Spotify\prefs and now it's working all good.

**Comment by Pukimaa** [comment]
Ok tried it out but still same error

**Comment by feedmes1eep** [comment]
Same thing happened to me. 
Don't know if this can fix for you but here ya go.

Removed both of the spicetify-cli folders from home directory.
Installed [https://github.com/powershell/powershell](PowerShell Core) (Forgot to install this after clean windows reinstall)
And then installed spicetify.

Also don't know if this is a thing with default installed powershell's repos or not (barely know much of these things at the moment), the config file that came with the install had the Windows Store Spotify's prefs_path in it.

**Comment by McStecca** [comment]
With PowerShell Core or with Chocolatey or with both of them it doesn't work. On another pc with only one account it works flawlessly, and same on linux with only one account

**Comment by Pukimaa** [comment]
> Same thing happened to me.
> Don't know if this can fix for you but here ya go.
> 
> Removed both of the spicetify-cli folders from home directory.
> Installed [PowerShell Core](https://github.com/powershell/powershel) (Forgot to install this after clean windows reinstall)
> And then installed spicetify.
> 
> Also don't know if this is a thing with default installed powershell's repos or not (barely know much of these things at the moment), the config file that came with the spicetify-cli install had the Windows Store Spotify's prefs_path in it.

That worked...thx
