### ISSUE TITLE
Spotify has received a major facelift causing fatal errors.

### ISSUE THREAD

**Issue by Hexlicious** [khanhas/spicetify-cli#474]
The update for Spotify that completely redesigns the desktop client to be more like the browser version just got pushed, this makes it so applying Spicetify causes a fatal error to display, the exact reasoning behind why is unknown to me but I would assume it has to do with Spicetify trying to alter a portion of the client that is no longer present with the new base design.

I would assume a fix would be to either update this program, or for me to somehow downgrade to an older version of Spotify, hoping for a solution though.

**Comment by CyberGen49** [comment]
This just happened to me as well.

After reinstalling Spicetify using the same Powershell commands used initially, everything works, but the app's appearance is reverted to the way it was before the update.

As someone who only uses Spicetify as a framework for WebNowPlaying (and Rainmeter), I'd like to keep the original, updated design. With that said, hopefully, we can get an update to Spicetify soon so we can keep the best of both worlds.

**Comment by khanhas** [comment]
Did you backup new version before apply?
If you didn't, please reinstall Spotify and run `spicetify backup apply`

**Comment by Hexlicious** [comment]
Did you read the report? Spotify has been completely redesigned so this program wont work till that is taken into account.

**Comment by afonsojramos** [comment]
@khanhas Supposedly there are a lot of changes that, to me, sound like they might break a few things. 
Once I get the update I'll try to provide more info here.

**Comment by khanhas** [comment]
I did. I just forced Spotify to updat to latest 1.1.56 and spicetify still works fine on mine.

**Comment by Hexlicious** [comment]
This is what I get now and started getting yesterday after the update was pushed https://prnt.sc/110nlcd

I've tried clearing the custom UI, backing up the new UI and applying again and that is the result.

According to my powershell I am running v0.9.6

**Comment by khanhas** [comment]
Can you reinstall Spotify, upgrade Spicetify to **v1.2.1** and run `spicetify backup apply`

**Comment by Hexlicious** [comment]
How exactly do I update? When I downloaded it the first time I just popped a line into powershell and it did the rest, now if I try to download the 1.2.1 version and run the .exe nothing happens.

**Comment by khanhas** [comment]
Just do the installing instruction again

**Comment by Hexlicious** [comment]
Got Spicetify updated to 1.2.1 but I had to pretty much wipe the whole thing from my system including spotify.

Anyways, I got it working again now but now the WebNowPlaying is blank, is there something I am missing?

**Comment by khanhas** [comment]
Check your spicetify config file to see if WebNowPlaying extension is added

**Comment by Hexlicious** [comment]
Figured it out with a bit of googling, sadly it seems I backed up the wrong theme though so I need to redesign my stuff from scratch, but I'll figure that out eventually.

Appreciate the help and program, spotify should have hired you to be their designer.

**Comment by afonsojramos** [comment]
I suppose you can close the issue then @Hexlicious 🤓

**Comment by Hexlicious** [comment]
Suppose I could, don't really use GitHub so assumed the repository owner had to do it.
