### ISSUE TITLE
[Windows 10] Custome titlebar / close minimize maximize buttons for Spicetify

### ISSUE THREAD

**Issue by momiji-oroshi** [khanhas/spicetify-cli#477]
I installed a custom theme for windows 10 and change the titlebar on the top-right corner.
For Chrome I disabled the original one by "--disable-windows10-custom-titlebar" (Reference: https://www.deviantart.com/poulnyrup/journal/Enabling-your-visual-styled-titlebar-in-Chrome-823160283), but this does not work for spotify / spicetify.

I know I can do a transparent titlebar by putting -transparent windows control thingy and that's what I'm using rn, but would be nicer if I can use my theme. Does anyone know how to enable?

**Comment by khanhas** [comment]
Not possible, sorry.
