### ISSUE TITLE
Needs to use new Spotify UI

### ISSUE THREAD

**Issue by 1N7R1N51C** [khanhas/spicetify-cli#478]
They've changed the Spotify UI, and now I look like a boomer. Please update Spicetify to match.

**Comment by afonsojramos** [comment]
@1N7R1N51C If you followed instructions and backedup before the update running `spicetify backup apply` should fix it!
Also, take a look at the exact same issue in #474

**Comment by khanhas** [comment]
@afonsojramos He wants new UI with spicetify
@1N7R1N51C Not gonna happen, sorry.

**Comment by afonsojramos** [comment]
Oh, in that case @1N7R1N51C , you can always create a new community theme 👀
