### ISSUE TITLE
Spotify just flat out doesn't look right

### ISSUE THREAD

**Issue by Liam2979** [khanhas/spicetify-cli#479]
I'm not sure how to describe it, it changes the font to times new roman, there's what looks like a black screen over my main window so I can't play songs. Happens with every CSS I try 
![image](https://user-images.githubusercontent.com/81754326/113290117-1575a980-92e9-11eb-9a48-9226d5e41707.png)

**Comment by Liam2979** [comment]
I'm on windows 10 btw, would love any help recommended

**Comment by khanhas** [comment]
Reinstall Spotify and follow this instruction https://github.com/khanhas/spicetify-cli/wiki/Installation
