### ISSUE TITLE
How do I properly inject an extension?

### ISSUE THREAD

**Issue by melangue** [khanhas/spicetify-cli#48]
Hey,

Sorry but I can't find any information on this.

Wrote a simple extension which allows to hide/show the sidebar when clicked on a button.
It works properly if I just inject and invoke the function via DevTools but I can't figure out how to inject it on when Spotify loads.

I have placed  my script in `./config/spicetify/Extensions` and added it to `config.ini` like so:
`extensions                   = menuToggle.js`

Tried just executing it, attaching it to window.onload, executing with a timeout etc - no luck. It seems like the extension is not loaded (tested with leaving in some console.log() ).

Simplified version:

	(function toggleMenu() {

		function toggle() {  };

		function addBtn() {	};
	
		window.onload = () => { addBtn(); };

	})();

Could you please point me in the right direction?

**Comment by khanhas** [comment]
Did you run `spicetify apply` after you add extension in config?

**Comment by melangue** [comment]
Oh wow, that was a dumb mistake on my part. This solved it, thank you :) 
Just to clarify, as I see it does not matter how I call the function in the script - extensions are injected when everything has loaded, right?
