### ISSUE TITLE
Wallet/PGP dialog before reboot

### ISSUE THREAD

**Issue by ckolodjski** [khanhas/spicetify-cli#489]
I'm currently on the latest version of Arch on both computers that had this issue. This computer (desktop) is on kernel 5.11.11-arch1-1 and running KDE Plasma, and the other computer (laptop) is running i3wm.

I just installed Spotify and spicetify-cli from the AUR.

I occasionally received a KDE Wallet Service dialog: see picture below. Initially, it would pop up immediately after closing Spotify. However, it soon became less consistent, appearing after clicking various things in Spotify itself. After a reboot, it no longer seems to appear.

![dialog](https://user-images.githubusercontent.com/43521811/113556905-c5d1ff00-95c2-11eb-9a2c-3f67a4b59864.png)

On my laptop (on which I had Spotify installed for months), I had the same issue after installing spicetify-cli, though the dialog was different; it specified the PGP key that it wanted me to unlock. This seemed strange to me, since I don't use that key for anything except encrypting individual files. Again, after a reboot the dialog ceased to appear.

**Comment by khanhas** [comment]
Sorry, I have no idea what could cause this and I'm certain that Spicetify has nothing to with it. Spicetify does not modify Spotify binary file, hence these requests made no sense.
Maybe it's chrominum/kdewallet weird interaction bug, try some of these suggestions at your own risk: https://superuser.com/questions/994551/disable-kwallet-popups-from-chrome#995367

**Comment by ckolodjski** [comment]
Since the problem goes away after the first reboot after installing spicetify-cli, it's not a persistent nuisance. I just wanted to log it since it's happened on two systems now. 

While my laptop only has chromium, my desktop only has qt5-webengine, though I'm not sure if that's useful at all.

```
~  paru -Qs chromium      
local/qt5-webengine 5.15.3-3 (qt qt5)
    Provides support for web applications using the Chromium browser project
~

**Comment by khanhas** [comment]
By chromium, I means the Spotify binary itself. Spotify is chromium.
