### ISSUE TITLE
Is it normal for Spicetify-cli to be really slow?

### ISSUE THREAD

**Issue by eliasbenb** [khanhas/spicetify-cli#49]
When I pause/play/skip track it takes a while to respond to my action (upwards of 20 seconds). Is this normal?

**Comment by khanhas** [comment]
Yeah, it's not normal. But I do not interfere with play/pause function in app code for its button to delay that much.
What extensions you are using? The delay might comes from one of them.
If you can, enable devtool (run `spicetify enable-devtool`). Whenever it doesn't work normally, open Console and see if there is any error, screenshot and post it here.

**Comment by eliasbenb** [comment]
I don't use any extensions (unless there are extensions which come preinstalled with Spicetify). Also how do I see the errors? I ran 'spicetify enable-devtool' in windows powershell but I can't figure out how to  "open Console". Sorry for my stupidity, and thanks for the reply!

**Comment by eliasbenb** [comment]
I just found out why it's being so slow. It has something to do with AdGaurd (a full system adblocker) I don't know why but when I turn AdGaurd off Spicetify is quick like with the normal Spotify, but when I turn it off it is slow. Any idea why this only happens on Spicetify? Are there ads?

**Comment by khanhas** [comment]
Could you open AdGuard log to see what does it block from Spotify?

**Comment by eliasbenb** [comment]
Thanks for all the help! But I reached out to AdGaurd aswell to see if it was a problem on their side. As it turned out it was on their side, they resolved the issue by updating their ad blocking filter. So rest assured that your code is not fualty! Thanks again!

**Comment by khanhas** [comment]
Le gasp

**Comment by eliasbenb** [comment]
https://bit.ly/2zYrMWi
