### ISSUE TITLE
Getting blank white Spotify (Linux)

### ISSUE THREAD

**Issue by LoLei** [khanhas/spicetify-cli#490]
![2021-04-05_16-36](https://user-images.githubusercontent.com/9076894/113585825-08302600-962d-11eb-902e-2608c488bdc1.png)

This happened when I first wanted to use spicetify-cli, after following the basic usage from the wiki, and installing the themes package.

[This](https://github.com/khanhas/spicetify-cli/wiki/FAQ#2-spotify-got-an-update-i-ran-spicetify-apply-or-spicetify-update-now-my-spotify-is-totally-messed-up) from the FAQ did not work.

At this point I just wanna get my normal Spotify back.

I've uninstalled both Spotify and spicetify-cli. That didn't restore my original Spotify after reinstalling it.
I reinstalled spicetify-cli and ran `spicetify restore` according to this: https://github.com/khanhas/spicetify-cli/issues/472#issuecomment-808836353
Didn't work either.

Are there any additional directories I need to remove?

```
$ spicetify --version
1.2.1

$ spotify --version
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Spotify version 1.1.55.498.gf9a83c60, Copyright (c) 2021, Spotify Ltd
```

**Comment by khanhas** [comment]
Please reinstall Spotify, give read write permission to `/opt/spotify` folder and try spicetify again.

**Comment by LoLei** [comment]
That worked, thanks.
