### ISSUE TITLE
Can't access devtools

### ISSUE THREAD

**Issue by twigit** [khanhas/spicetify-cli#491]
I'd like to enable dev tools to modify a theme, but I'm not able to get them to work. Might be me doing something wrong, though.

Here is the command I use and its result
```
$ spicetify apply enable-devtool
spicetify v1.2.1
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
success Spotify is spiced up!
success DevTool enabled!
```

Sounds like everything is fine. Spotify starts and the theme I picked is applied.
I read on Spectrum [here](https://spectrum.chat/spicetify/general/chrome-developer-tools~31aa3625-b747-4139-b105-add27af1cb73) that you need to press Ctrl+Shift+I to access devtools in Spotify, but nothing happens when I do.

I'vo got the same problem on two computers, one running MX Linux (Debian based), the other running Manjaro (Arch based). Both use XFCE as a desktop environment, so I checked, just in case : there is no action associated to the shortcut Ctrl+Shift+I by default in XFCE that would interfere.

Based on what's said on Spectrum, it seems that these dev tools are actually Google Chrome's dev tools, so I tried to install Chromium (via APT so that it's not self-contained) to make sure these tools are present on my system, but that does not change anything.

**Comment by khanhas** [comment]
Right click at any blank space in player and see if context menu popping up
![image](https://user-images.githubusercontent.com/26436809/113685602-c45f1e80-9709-11eb-916f-417eb7ea0792.png)

**Comment by twigit** [comment]
I tried to right click on a empty spaces in various screen, but I never get any context menu. The only ones I get are regular Spotify menus when right clicking on non-empty spaces, such as an artist name.

**Comment by twigit** [comment]
I installed the actual Google Chrome, instead of its open-source alternative Chromium, and not it's working.

The documentation does not tell that Chrome is required (I only accidentally guessed that information from a question on Spectrum), I think it's an important information that's worth mentionning.
