### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by pecdo12** [khanhas/spicetify-cli#494]
So yes, i have installed the desktop version of spotify, i then installed spicetify-cli with powershell: no problems installing. Then i run spicetify (to generate the config) but it gives me error _Access Denied_. This is my computer so i have admin powers (and i tried using also administrator cmd but it still gave me the same error.

I looked everywhere on google but didnt find anybody with a similar issue, so help ig?
btw im on windows 10

![image](https://user-images.githubusercontent.com/48889043/113804404-77407400-972c-11eb-8cb0-d16083138b20.png)
![image](https://user-images.githubusercontent.com/48889043/113804560-c5557780-972c-11eb-925d-d892cc24f593.png)

**Comment by khanhas** [comment]
Can you try with CMD, not powershell?

**Comment by khanhas** [comment]
Do you use any antivirus anti malware that potentially block program from executing?

**Comment by pecdo12** [comment]
Thx a lot, turns out it was because of a firewall/antivirus i installed (Comodo FIrewall) that even when turned off, the process stayed on, so it blocked it. So yeah, cant thank you enough for the quick response. 

Ciao ;)
