### ISSUE TITLE
skin completely broken..

### ISSUE THREAD

**Issue by MichaelKroon** [khanhas/spicetify-cli#498]
started my pc today and launched spotify with the skin active but now it's broken for some reason :( [Screenshot](https://imgur.com/a/aJuz7CU)

**Comment by DoubleJarvis** [comment]
Spotify updated their desktop client changing things around. `spicetify restore backup` brings the client back to life, without the skin, unfortunately. But at least you have music :)

**Comment by khanhas** [comment]
Reinstall and run `spicetify backup apply`
After every update, run that command again

**Comment by ZacheryMcLaughlin** [comment]
I Reinstalled Spotify and ran spicetify backup apply, but it just brings me back to the original screenshot that OP posted.

**Comment by MichaelKroon** [comment]
I tried it and it fixed it. However using the rainmeter way that I used to use makes it go broken again.

**Comment by khanhas** [comment]
Of course, didn't you see that project was abandoned? Right in its front page, huge text.

**Comment by MichaelKroon** [comment]
Never checked out the github page, only noticed it when I was looking for my problem
