### ISSUE TITLE
Taskbar controls not showing post-Spicetify install

### ISSUE THREAD

**Issue by EmSixTeen** [khanhas/spicetify-cli#499]
Is this a side-effect of using Spicetify that's unavoidable? Or is there a setting/workaround to get them back?

Windows 10x64 1909 fwiw.

**Comment by pWoLiAn** [comment]
works just fine over here on Windows 10x64 21h1

**Comment by Dinxton** [comment]
I can reproduce immediately after applying Spicetify - no taskbar controls showing at all. After a single restart of Spotify, the taskbar controls appear as normal.

Win 10 Pro x64, 2004 (19041.928)
Spotify 1.1.58.820.g2ae50076
Spicetify-cli 1.2.1
