### ISSUE TITLE
Thumbnail is sized incorrectly

### ISSUE THREAD

**Issue by steebchen** [khanhas/spicetify-cli#5]
The image is not display correctly, as well as the image in the view when you expand the image (though I can't click on the expand-icon now):

![selection_999 1073](https://user-images.githubusercontent.com/5013932/53843239-0a34e000-3fa2-11e9-9849-6afc0b41d7d3.jpg)

Sadly `enable-devtool` does not work for me, so I can't seem to investigate further.

running latest spicetify-cli on Linux Mint 18.1

**Comment by khanhas** [comment]
What is your Spotify version?

**Comment by steebchen** [comment]
oops, spotify version is 1.0.98.78.gb45d2a6b

**Comment by khanhas** [comment]
Sorry, newest version is 1.1 and everything works correctly.
I cannot rollback to 1.0.98 in any platform. So I don't think I can help you find out what is wrong.
Try upgrade to 1.1 and tell me if this problem still persist.

**Comment by steebchen** [comment]
Currently can't manage to upgrade, so I'll close for now and re-open later if needed
