### ISSUE TITLE
Trashbin.js gets in the way of new(-ish) Release Radar feature

### ISSUE THREAD

**Issue by raiscan** [khanhas/spicetify-cli#50]
Hi! Love the project!

The Trashbin.js extension is great but it interferes with the button that appears on Release Radar for blocking certain songs/artists. Because both buttons are in the same place, yours takes precedence due to the other first opening a context menu.

Could you please add a presence check for the existing button and if so offset the trash button, or optionally remove it altogether when it's present since this feature is similar in functionality?

Thanks!

**Comment by khanhas** [comment]
I'm certain that they do not have same functionality. Trashbin detects and skips songs at app-wide, at any context. While Blocking feature in Release Radar just stops track from getting into your next Release radar or Radio. If theses tracks are in a playlist, it's still played normally.

Anyway, I will take a look at this weekend to see if I can come up with any solution.

**Comment by khanhas** [comment]
I think it's best to use Spicetify new Context menu API. I don't have to deal with buttons states and positions. We also can block track and artist everywhere, no need to play that track or open artist page.

![image](https://user-images.githubusercontent.com/26436809/63650214-a8ed0d00-c78b-11e9-91aa-52c118144917.png)
![image](https://user-images.githubusercontent.com/26436809/63650241-d76ae800-c78b-11e9-850d-ac8c47f9c805.png)

**Comment by khanhas** [comment]
Changed in v0.9.3.
