### ISSUE TITLE
C:\Users\ACER\AppData\Roaming\Spotify\Apps\zlink\css\user.css

### ISSUE THREAD

**Issue by xmariconiex** [khanhas/spicetify-cli#503]
I can not find this file, how do i solve it? It says fatal error C:\Users\ACER\AppData\Roaming\Spotify\Apps\zlink\css\user.css not found

**Comment by rickvandijck** [comment]
Try reinstalling/repairing Spotify, make sure you're using the one from Spotify.com, not the MS Store version

**Comment by khanhas** [comment]
And run `spicetify backup apply`

**Comment by elias-carlson** [comment]
I had the same issue and can confirm reinstalling Spotify and running `spicetify backup apply` fixed it

**Comment by kane090** [comment]
I had the same issue `spicetify backup apply` does not fix it.

![image](https://user-images.githubusercontent.com/40439371/118115920-3d7d2000-b3f2-11eb-9bde-f7206387676f.png)

**Comment by muril0-0** [comment]
I had the same problem on Windows 10 and solved with these steps:

- Uninstalling both (Spicetify and Spotify), I was using Chocolatey version, so I just ran 'choco uninstall spicetify-cli';
- Removing 'spicetify-cli' and '.spicetify' folders;
- Installing spicetify-cli by Powershell (don't use Choco or Scoop, only Powershell version worked for me);
- Installing Spotify (not the MS version);
- Run 'spicetify' command and after 'spicetify backup apply enable-devtool';
- Change themes and colors;
- Run 'spicetify update';

Now it's works fine.

PS.: Sorry about my English errors, I'm Brazilian, and I'm learning the idiom yet.
