### ISSUE TITLE
fullAppDisplay not showing up

### ISSUE THREAD

**Issue by rickvandijck** [khanhas/spicetify-cli#504]
Hi there,
I just discovered Spicetify and tried installing the fullAppDisplay extension, but it's not showing the button to activate it. 
It's in my config file, so it is loaded in... any help would be appreciated

**Comment by khanhas** [comment]
Did you run `spicetify apply` after changing your config?

**Comment by rickvandijck** [comment]
I did, but guess something went wrong without me noticing. It's working now, thanks
