### ISSUE TITLE
prefs_path; weird behaviour

### ISSUE THREAD

**Issue by xLazar07** [khanhas/spicetify-cli#506]
I'm on Windows and installed the latest version of spicetify (11.04.21). Today my Spotify was broken | some Microsoft store error | and because its recommended to have the 'original' spotify I deinstalled and downloaded the installer from their website. I changed the path but now I can't find the correct pref file. I found two of them:
C:\Users\xxx\AppData\Roaming\Spotify\prefs and C:\Users\xxx\AppData\Roaming\Spotify\Users\xxx\prefs

I don't get an error but Spicetify won't start. If I start spotify normally it starts.

I tried: Reinstalling, Checking the prefs files, if they have scuffed settings in them.
Happy with every answer.

**Comment by khanhas** [comment]
Delete spicetify config file and try again
