### ISSUE TITLE
New Spotify app design

### ISSUE THREAD

**Issue by guttitto** [khanhas/spicetify-cli#507]
Hello, so I noticed that Spotify changed the design of its application to look more like the web version. At first I thought it was weird, but one thing I liked about it was that it shows the track number on playlists, like an album, which is something that can be useful sometimes. I tried to use Spicetify with no theme, to have the new design and be able to use some extensions and custom apps and still have those numbers, but it changes back to the old Spotify theme. is there a way to keep this new design and use spicetify apps?

**Comment by khanhas** [comment]
It's not possible sorry. At the moment, new UI is not theme-able and Spicetify API cannot be exposed using same way as in old version.

**Comment by guttitto** [comment]
Do you think it's possible for someone to make an add-on to show the track numbers on playlists?

**Comment by fzslm** [comment]
well, the new Spotify is still based on CEF and I still have access to the dev tools. so it should be possible for devs to whip up relatively simple extensions for the new Spotify - but we wouldn't have the Spicetify API, and a new framework would likely need to be developed to make management of these new plugins easier.

FWIW, i seem to have track numbers on my playlists already...

**Comment by guttitto** [comment]
I mean having the track numbers on the old theme
