### ISSUE TITLE
Theme doesn't apply - Ubuntu 18.04

### ISSUE THREAD

**Issue by andreasmpoulsen** [khanhas/spicetify-cli#508]
My installation seems to be fine but when i apply a theme nothing happens.

My config file:
`[Setting]
spotify_path            = /usr/share/spotify/
prefs_path              = /home/andr/.config/spotify/
current_theme           = Dribbblish
color_scheme            = nord-dark
inject_css              = 1
overwrite_assets        = 1
spotify_launch_flags    = 
replace_colors          = 1
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
fastUser_switching           = 0
lyric_always_show            = 0
radio                        = 0
extensions                   = dribbblish.js
custom_apps                  = 
experimental_features        = 0
home                         = 0
lyric_force_no_sync          = 0
song_page                    = 0
visualization_high_framerate = 0

; DO NOT CHANGE!
[Backup]
version = 
`

And my themes are situated in /home/andr/.config/spicetify/Themes/

**Comment by khanhas** [comment]
Have you read the wiki on Basic Usage and followew those steps?
Which step it threw error and what was the error?

**Comment by andreasmpoulsen** [comment]
Yes i followed the installation guide and then the basic usage page. What's strange is that i don't get errors. As far as I can tell everything works as it should. There's just no changes when i open spotify

**Comment by andreasmpoulsen** [comment]
Okay so it turns out i had two prefs files and the correct one was in "/home/andr/.var/app/com.spotify.Client/config/spotify/User Data".
After adding that as the path, the themes were finally applied
