### ISSUE TITLE
Save backup version seperately 

### ISSUE THREAD

**Issue by jzbor** [khanhas/spicetify-cli#509]
Currently spicetify saves the `[Backup]` section in `.config/spicetify/config.ini` with a *Do Not Change* disclaimer. This is a problem for the portability of the config, for example when syncing dotfiles between multiple machines (for example with git). Would it be possible to put those automatically generated attributes in a seperate file?

**Comment by khanhas** [comment]
Yeah it's possible but a lot of code need to be fix. But this use case is quite niche and I don't think it's necessary to force that to everyone.
