### ISSUE TITLE
AdditionalOptions

### ISSUE THREAD

**Issue by akeslo** [khanhas/spicetify-cli#51]
made_for_you_hub             = 0
radio                        = 0

With the above in place, radio and made for you options still displayed in sidebar.  Any way to also remove Podcast from sidebar?

Thanks.

**Comment by khanhas** [comment]
They should be `-1` if you want to remove it. But `made_for_you_hub` is no longer customizable since v0.9.1. 
Easier, you can use CSS to hide them.
