### ISSUE TITLE
Restore spotify default theme

### ISSUE THREAD

**Issue by KonstantMan** [khanhas/spicetify-cli#516]
I love the customizability of spicetify-cli but some times i just want to return to default  spotify theme ,is there any way to do it without breaking the ability to change themes again ?

**Comment by khanhas** [comment]
Read help text, run `spicetify --help`

**Comment by spinalgr1990** [comment]
Open Powershell and hit

------------------------------------------------------------

spicetify restore
rmdir -r -fo $env:APPDATA\spicetify
rmdir -r -fo $env:LOCALAPPDATA\spicetify

------------------------------------------------------------


and then 



------------------------------------------------------------

spicetify enable-devtools

------------------------------------------------------------


After that open Spotify 



Open up DevTools by right clicking anywhere on Spotify, and then click on Inspect Element.
Click the Console tab in the DevTools window, paste the following command inside then execute Marketplace.reset()



https://github.com/spicetify/spicetify-marketplace/wiki/Development

**Comment by nox-4O4** [comment]
You can use 

```
spicetify config current_theme reset-
```
Mind the `-` at the end, that's the key! It leads to spicetify removing the configured custom theme. (You can actually use any other value instead of `reset` as well, it does not matter as long as a `-` is at the end.)

Run `spicetify apply` afterwards.
