### ISSUE TITLE
Spicetify undoing latest UI update

### ISSUE THREAD

**Issue by Darzee2244** [khanhas/spicetify-cli#517]
When I have Spicetify applied, it is reverting to the previous UI layout even when I have "config inject_css 0 replace_colors 0". Once I restore it, Spotify loads the latest UI layout (thumbnails in playlists etc.). Is this a problem on my end or does Spicetify load the older layout and doesn't work with the latest Spotify update?

Spotify Version: 1.1.56.595.g2d2da0de-a
Spicetify Version: 1.2.1

Thanks

**Comment by khanhas** [comment]
Yes it discards new UI as it supposes to do.
