### ISSUE TITLE
Themes don't work

### ISSUE THREAD

**Issue by alexroumi** [khanhas/spicetify-cli#519]
I have done everything correctly but except the default theme no other of the installed work just defaults to spotify

**Comment by khanhas** [comment]
What have you done exactly? Which guide you followed?
Also, show you me your config file.

**Comment by blasterpistol** [comment]
Same thing, it stopped working, but I saw that Spotify released a new version, this could be the root of the problem, something changed under the hood.

**Comment by alexroumi** [comment]
I wans't;t using the right command apparently
