### ISSUE TITLE
Add command to choose theme

### ISSUE THREAD

**Issue by morpheusthewhite** [khanhas/spicetify-cli#52]
A good improvement could be to add a command (for example select) to apply an installed theme, such that running `spicetify select _THEME_NAME_` will update `config.ini` with `_THEME_NAME_`

**Comment by khanhas** [comment]
Use `spicetify config current_theme  _THEME_NAME_`

**Comment by morpheusthewhite** [comment]
Ok, thank you, I didn't notice it
