### ISSUE TITLE
Feature request - Disable ContextMenu Item

### ISSUE THREAD

**Issue by elijaholmos** [khanhas/spicetify-cli#520]
As a developer, I would like the ability to toggle the enabled/disabled status of a custom ContextMenu Item. For example, the "Report" item in the below screenshot is disabled because it is grayed out and unable to be clicked.
![image](https://user-images.githubusercontent.com/35435704/115177128-67595600-a083-11eb-908f-20afbbeaba67.png)

**Comment by khanhas** [comment]
`shouldAdd` function parameter is already for returning the condition whether API should append your context menu item in the list. Is there any other use case that `disabled` status would be useful for?

**Comment by elijaholmos** [comment]
I know it's a little niche, but the specific situation I wanted it for was an extension that fetched the user's entire library upon initialization and cannot function properly until that is complete. I've already incorporated this into the `shouldAdd` method so that the button will not appear until the entire user library has been fetched- I was just thinking it would be better on the user-side if they saw the button grayed out rather than completely absent, so that they know the extension is there, just not available to use yet.

**Comment by elijaholmos** [comment]
I'm not sure how much work it would be to add the ability to toggle button enabled/disabled status from the code... if it's not something you think can be done easily, don't worry about it.

**Comment by khanhas** [comment]
Nah I think it's reasonable enough. I will add it in next version.

**Comment by elijaholmos** [comment]
Ok sweet! Thanks for chatting with me.

**Comment by khanhas** [comment]
I made the change but I won't draft a new spicetify version any time soon. So if you want to try it out, just download this file and replace with the original one in `<spicetify directory>/jsHelper/`:
https://raw.githubusercontent.com/khanhas/spicetify-cli/master/jsHelper/spicetifyWrapper.js
"disabled" prop should be the last parameter of `Item` or `SubMenu` constructor:
```js
const test = new Spicetify.ContextMenu.Item("Test", () => {}, () => true, "album", true);
test.register();
```
You can set "disabled" prop explicitly and it will be updated visually immediately:
```
test.disabled = false;
```

**Comment by elijaholmos** [comment]
Awesome! I will test this out later today when I get home from work

**Comment by elijaholmos** [comment]
I replaced my previous `spicetifyWrapper.js` file with the one you linked, but when I run `spicetify apply` it is loading in the source code from the old file. Is the old javascript being cached, or could there be something else that I didn't do right?

**Comment by khanhas** [comment]
Ah no spicetifyWrapper.js is copied in preprocess, you gotta run `spicetify restore backup apply`.

**Comment by elijaholmos** [comment]
That worked perfectly, thanks for the help. The new feature functioned as intended and I encountered zero problems. Thank you!
