### ISSUE TITLE
Spicetify Lyrics

### ISSUE THREAD

**Issue by RiichKT** [khanhas/spicetify-cli#521]
How does the Spicetify lyrics work? Every time I click on the little mic it keeps sayinig "humming is fun" how do I enable it?
![lyrcs'](https://user-images.githubusercontent.com/82802753/115200618-a43c4180-a0b1-11eb-99af-428b42c7e63f.jpg)

**Comment by khanhas** [comment]
If you're not in right region, it's never going work.
