### ISSUE TITLE
Shuffle+ Shuffle Context

### ISSUE THREAD

**Issue by badwolf292** [khanhas/spicetify-cli#525]
Whenever i try to use the "Shuffle Context" button, it always returns an error code. I tried reinstalling, i tried removing and adding again but it still does not work.

The error reads: "Unsupported fetching URI type: track

The Shuffle Queue button works fine though.

**Comment by khanhas** [comment]
As it said in the error: the context you were playing is a track. How do you expect it to shuffle one track?
Supported contexts are playlist, album, podcast, playlist folder, personal collection and artists.

**Comment by badwolf292** [comment]
Wow. Now I feel stupid. Thanks.
