### ISSUE TITLE
Spicetify cannot detect spotify location.

### ISSUE THREAD

**Issue by brymer-meneses** [khanhas/spicetify-cli#528]
I have manually put the spotify location on `config.ini` but it still doesn't work 

![Screenshot from 2021-04-21 20-42-50](https://user-images.githubusercontent.com/68867487/115555592-42165300-a2e2-11eb-975e-d6421dc221cc.png)

I can confirm that the path I provided is valid and true. Where did I screw up and how can I fix this?

**Comment by khanhas** [comment]
Please expand `~`

**Comment by brymer-meneses** [comment]
I have expanded the path, but it’s still not working.

**Comment by khanhas** [comment]
Did you follow Wiki instruction for Flatpak user?

**Comment by brymer-meneses** [comment]
Yes, I did.

**Comment by khanhas** [comment]
![Uploading image.png…]()

**Comment by brymer-meneses** [comment]
I see, thank you! Sorry for the triviality of the problem.
