### ISSUE TITLE
Popularity Meter Extension?

### ISSUE THREAD

**Issue by clu7ch3r** [khanhas/spicetify-cli#529]
As you have may noticed... on the recent spotify update the popularity meter got replaced with total plays. This issue was recently brought up on the spotify community site a couple of times but so far there's no idea on when spotify will bring that feature back. Each bar represents a range of songs played last month which I would assume could be implemented using spotify's API. Could this be something that could be added as an extension on spicetify?

### **Previous Spotify**

![image](https://user-images.githubusercontent.com/36937310/115687213-f5ee0180-a327-11eb-8374-5203b2534f94.png)
![image](https://user-images.githubusercontent.com/36937310/115687306-0a31fe80-a328-11eb-87c9-79bb0f70dffa.png)

### **Current Spotify**
![image](https://user-images.githubusercontent.com/36937310/115687966-b1af3100-a328-11eb-8341-551059f58223.png)

**Comment by khanhas** [comment]
spicetify does not work on new UI at the moment so it's not possible to do any modification and add extension.
