### ISSUE TITLE
Possibility to backup recent searchs ?

### ISSUE THREAD

**Issue by xerta555** [khanhas/spicetify-cli#533]
Hi

I would like to know where the recents searchs are saved in the Spotify install folder, bcz at each time i do the `spicetify backup apply enable-devtool` command, my recents searchs are removed.

Is it possible ?

**Comment by khanhas** [comment]
Don't run `enable-devtool` every single time, you only need to run it once. Then running spicetify won't reset your stuff.

**Comment by xerta555** [comment]
> Don't run enable-devtool every single time, you only need to run it once. Then running spicetify won't reset your stuff.

Ok thanks for this info, so if i understand correctly, when we do the `enable-devtool` command to enabling the devtool mode, it remove the recent searchs history right ?

So do we know where are they located ?

**Comment by khanhas** [comment]
I really don't know what happens when we changes enable/disable devtool. Spicetify simply edits "prefs" file (Spotify config file) and Spotify doesn't not like that. It forces user to log in again to generate new credential. And that's probably the reason why your data is wiped out.

**Comment by xerta555** [comment]
> I really don't know what happens when we changes enable/disable devtool. Spicetify simply edits "prefs" file (Spotify config file) and Spotify doesn't not like that. It forces user to log in again to generate new credential. And that's probably the reason why your data is wiped out.

Ok, and where this config file is located ?

**Comment by khanhas** [comment]
It's in your config file, in field `prefs_path`. It does not contain anything about recent search though.
Scratch what I said earlier. I just did a test and seem like re-login does not wipe my recent search. Honestly, I don't know what happens to yours. Can you tell me more what happens to Spotify that you need to execute `spicetify backup apply`?
Anyway, if you really want to access recent search data, just hit Ctrl Shift i , then follow this:
![image](https://user-images.githubusercontent.com/26436809/115856558-fe515400-a46f-11eb-8be3-844e69f16913.png)

**Comment by xerta555** [comment]
> It's in your config file, in field prefs_path. It does not contain anything about recent search though.

Scratch what I said earlier. I just did a test and seem like re-login does not wipe my recent search. Honestly, I don't know what happens to yours. Can you tell me more what happens to Spotify that you need to execute spicetify backup apply?

I used an other old version of this tool on another repo.
When i have found your one (wich is regulary updated), i did a full clean setup of Spotify client, Spicetify-cli and other MOD for other things in Spotify.
Now that i have found your repo and that it's works fine, i don't have to do the command again.

> Anyway, if you really want to access recent search data, just hit Ctrl Shift i , then follow this:

Effectivly i have found it and it contain the recent searchs witch appear when i click in the search field area.
I will look at it and try to backup/restore to check if the Spotify app accept that or not.

Thanks.

**Comment by xerta555** [comment]
I just tested by make backup of the whold line you indicated to me to a simple notepad, use the clear all recent search button in spotify recent search at bottom, replace the new content in the devtool with my backup and restart my Spotify client, my recent searchs works.

I don't have test after an Sotify client update, i will check it.
But we can't be sure that it will necessarily work with all future versions of the Spotify client, if Spotify devs change the format of saved recent searchs in future, i will have to do again all my recent searchs and backup it again.
