### ISSUE TITLE
Installing spicetify

### ISSUE THREAD

**Issue by Gnarly-Barnacle** [khanhas/spicetify-cli#534]
I'm having trouble with installing and implementing this and changing the theme. Could anyone perhaps create a more detailed walkthrough on how to do all this?

**Comment by Mobmaker55** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation
DO THAT FIRST

https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage
DO THAT SECOND

https://github.com/khanhas/spicetify-cli/wiki/Customization
DO THAT THIRD

If these three docs don't help you enough, I don't quite know what to tell you...

**Comment by Pixouls** [comment]
i followed an installation video on yt, i think that's the most detail you can get (someone talking for 30 minutes guiding you step by step)
