### ISSUE TITLE
Error with prefs_path, even though the file exists

### ISSUE THREAD

**Issue by TheCultLeader666** [khanhas/spicetify-cli#536]
Whenever I run `spicetify apply`, I get `~/.var/app/com.spotify.Client/config/spotify/prefs does not exist or is not a valid path.`, even though this is the location of the prefs file
![Screenshot from 2021-04-23 09-36-30](https://user-images.githubusercontent.com/65368815/115879210-67f14400-a417-11eb-958f-3c2a258c8741.png)

**Comment by khanhas** [comment]
Expand `~`
and follow instructions on wiki for Flatpak user if you still encounter problems.

**Comment by PolGZ** [comment]
Same error. Instructions for flatpak followed.

Only `prefs` file in `~` is:

```
find | grep "spotify/prefs$"
`.var/app/com.spotify.Client/config/spotify/prefs`
```

Content of 

`~/.config/spicetify/config-xpui.ini` is:

```
[Setting]
spotify_path           = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
current_theme          = 
inject_theme_js        = 1
inject_css             = 1
spotify_launch_flags   = 
always_enable_devtools = 0
prefs_path             = ~/.var/app/com.spotify.Client/config/spotify/prefs
```

Flatpak installed directoy is indeed `/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/`

Permissions have been applied:

```
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
```

`Prefs` file is with these default permissions (but documentation doesn't say to change them):

```
drwxr-xr-x@    - polgz 27 ene 17:17  Users
.rw-r--r--@ 1,0k polgz 11 mar 12:18  prefs
```
