### ISSUE TITLE
Static (and completely inaccurate) timebar

### ISSUE THREAD

**Issue by Mobmaker55** [khanhas/spicetify-cli#540]
With any theme designed this way, and with any song playing, this is what always shows for the bar... I don't know why the left and right won't move, that's all I really want anyway, I don't care about the text under it as much...

Edit: The timestamps are ALWAYS set to "1:26" and "4:03", the time ON the bar does move with the song's time, but it's stuck in that weird spot
![image](https://user-images.githubusercontent.com/45888585/115974244-526c3f00-a529-11eb-99ef-fc16089ed3e7.png)

**Comment by khanhas** [comment]
Remove extension dribbblish.js in config file and run apply.

**Comment by Mobmaker55** [comment]
That did not work, applying it just changed the start and stop time ;-;

**Comment by khanhas** [comment]
Did you remove the dribbblish.js extension?

**Comment by Mobmaker55** [comment]
[config.txt](https://github.com/khanhas/spicetify-cli/files/6371091/config.txt)
It wouldn't let me upload it as an ini, but yes I understand that it *should* be .ini

**Comment by khanhas** [comment]
Try `spicetify restore backup apply`?

**Comment by Mobmaker55** [comment]
That worked! thank you so much!
