### ISSUE TITLE
Reoccurring pease reinstall Spotify and try again

### ISSUE THREAD

**Issue by sdey02** [khanhas/spicetify-cli#541]
Every time I try to back up or apply a theme, it hits me with a reinstall Spotify and try again error, i have tried this abot 10+ times of reinstalling Spotify but it doesn't seem to work?

**Comment by khanhas** [comment]
At which stage it threw that error?

**Comment by sdey02** [comment]
After I download it, and try to back up Spotify.

**Comment by dannyibishev** [comment]
Getting the same. my state somehow got corrupted when I ran spicetify clear. Now I'm getting the same error.

**Comment by sdey02** [comment]
My issue got fixed by adding, /Spotify.app/Contents/Resources, in the config.ini file in the line spotify_path  = /Users/sdey02/Applications/Spotify.app/Contents/Resources
