### ISSUE TITLE
Minor Bug: Issue displaying preview in Gnome (3.38) when minimizing

### ISSUE THREAD

**Issue by protodrew** [khanhas/spicetify-cli#544]
Screenshot
![](https://i.imgur.com/mmPfucO.png)

Process to create bug:

Open spicetify and split the window with another application, minimize spicetify

Press the key that opens activities view (default is super key) 

You can see that the content of spotify hasn't been resized to fit the full view in the preview window or cropped to the aspect ratio it was at when minimized like shown below

![](https://i.imgur.com/XMTf1px.png)

**Comment by khanhas** [comment]
Sorry, I have no clue. Spicetify has nothing to do with how desktop manager renders preview of a window.
