### ISSUE TITLE
XResources is not Available

### ISSUE THREAD

**Issue by adhinath01** [khanhas/spicetify-cli#545]
I keep getting this Error when i try to update my theme a ss for context
![image](https://user-images.githubusercontent.com/82806081/116584814-5cc97700-a935-11eb-95ab-d6f9d70325db.png)

**Comment by khanhas** [comment]
Can you try running `xrdb` and see if it's working in your terminal session?

**Comment by adhinath01** [comment]
what exactly should i run, is it just xrdb or something else accompanying it? Sorry i'm new to this

**Comment by khanhas** [comment]
XRDB is where pywal store generated colorscheme. Are you using Pywal or not?

**Comment by adhinath01** [comment]
i dont think i am haven't installed pywal

**Comment by khanhas** [comment]
So don't set color_scheme to "wal" because it's for pywal user.
