### ISSUE TITLE
Lyrics supported on any theme anybody?

### ISSUE THREAD

**Issue by saDimpartuSuseR** [khanhas/spicetify-cli#547]
I just checked all the themes in the community themes collection, but none of them display lyrics. Anyone else had luck getting them on any theme? Can somebody guide through on how to add them in any theme? All the user.css I saw mentioned .nolyricsmessage wherever lyrics box was mentioned.

**Comment by Pixouls** [comment]
@saDimpartuSuseR you can check out this repo https://github.com/khanhas/genius-spicetify/
it's developed separately

**Comment by khanhas** [comment]
Theme consists of color and CSS, it has nothing to do with client functionality.
