### ISSUE TITLE
Progress bar for Star Wars easter egg

### ISSUE THREAD

**Issue by cubetastic33** [khanhas/spicetify-cli#55]
The star wars lightsaber easter egg has a different progress bar. If you play star wars songs, the progress bar becomes a lightsaber. This lightsaber is out of position with the DefaultTheme. Also, the DefaultTheme seems to try to hide the new playlist creation button, but it ends up showing anyway.

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/commit/d8574718998069029e16a0d8cf35c030d258fcc3

Thanks!

**Comment by khanhas** [comment]
Fixed in v0.9.3.

**Comment by cubetastic33** [comment]
So now it hides the saber's hilt, right? Is there a way you could incorporate the lightsaber feature into the theme?

**Comment by khanhas** [comment]
I could but I don't think I will
