### ISSUE TITLE
Disable all things podcast

### ISSUE THREAD

**Issue by KevinBongart** [khanhas/spicetify-cli#550]
Hi there, Spicetify looks great! I see a few features around podcasts. Could this tool be used to hide all podcast features and recommendations from Spotify? If so, I'm happy to take a stab at an implementation, and any pointers would be appreciated.

**Comment by yougotwill** [comment]
@KevinBongart I haven't used this extension myself but might help you out. https://github.com/3raxton/spicetify-custom-apps-and-extensions/tree/main/spicetify-hide-podcasts
