### ISSUE TITLE
Spicetify not working in latest version of Spotify

### ISSUE THREAD

**Issue by D0J1n** [khanhas/spicetify-cli#551]
Hi all,

Latest version of Spotify (1.1.58.820.g2ae50076-a) released today and below screenshot shows the error when I use Spicetify. Everything worked fine before today. Is this just me or did the Spotify update break Spicetify?

![image](https://user-images.githubusercontent.com/75489905/116989382-f300f280-acd1-11eb-801a-9b9a8b30cd65.png)

**Comment by D0J1n** [comment]
Nevermind, my bad, haven't updated Spicetify in ages. Everything works.

**Comment by Aedoenoert** [comment]
i had the same issue. I updated my spicetify from version 0.9.6 (or so) to the newest 1.2.1. Spicetify is working fine again but setting up the colors is kinda bugged, because it only applys some of the colors, some stay default.
