### ISSUE TITLE
Spicetify 0.9.9 error

### ISSUE THREAD

**Issue by 72Tysiak** [khanhas/spicetify-cli#552]
Since the new update for spotify got released (2nd or 3rd May) I can't use the spicetify due to an error. 
![Zrzut ekranu (1274)](https://user-images.githubusercontent.com/62675898/117058979-975d5600-ad1f-11eb-8156-a63ca1a2b643.png)
When I use 'spicetify restore backup' in cmd then Spotify run normally but in vanilla so without themes. Once I tried to reinstall Spotify and I used 'spicetify backup apply'. Everything was good, spicetify lunched, spotify launched, no fatal error, however I restarted PC and the error showed again. When I use 'spicetify restore backup' I can restart PC, restart Spotify and  Spotify run commonly vanilla. 
Therefore, can somebody help me? Btw, I thought about install newer version but it is from 28th Feb. Problem and Spotify update was 2nd or 3rd May as I wrote.

**Comment by khanhas** [comment]
Upgrade Spicetify.
