### ISSUE TITLE
Old Default Spotify Theme

### ISSUE THREAD

**Issue by Akasiek** [khanhas/spicetify-cli#553]
Without Spicetify on PC you can see new look of Spotify which I really like. But I don't want to give up stuff that Spicetify can offer (WebNowPlaying).
After disabling "inject_css" and "replace_colors" in config Spotify has the Old Default look. The new design is gone and I need to disable Spicetify to see it.
Can you help?

**Comment by khanhas** [comment]
Sorry, you can't switch to new UI when using spicetify at the moment. The reason is New UI is entire different infrastructure to old UI and obviously Spicetify cannot support that. And I think I will find time to reverse engineer the new one.
