### ISSUE TITLE
Dark Theme?

### ISSUE THREAD

**Issue by mortenanakin** [khanhas/spicetify-cli#556]
Not a issue, but i have all my windows dark, and today i've installed Spicetify (its GREAT), and i want a dark theme for that. Any way to get it without messing up things that i dont know? xD Thanks!

**Comment by khanhas** [comment]
https://github.com/morpheusthewhite/spicetify-themes

**Comment by grasonchan** [comment]
Maybe you can try this theme - [spotify-spice](https://github.com/grasonchan/spotify-spice). It's based on Spotify original theme.

![spotify_spice](https://user-images.githubusercontent.com/19476925/117441133-89017b00-af67-11eb-98b9-231de1953b2d.png)

![full_app_display](https://user-images.githubusercontent.com/19476925/117441193-9880c400-af67-11eb-9c4a-0854c7fd81dc.png)
