### ISSUE TITLE
Spotify Update 1.1.59.697.g3af4df50-a removes old UI

### ISSUE THREAD

**Issue by Sparoney** [khanhas/spicetify-cli#557]
Hi,

The latest Spotify update (1.1.59.697.g3af4df50-a) removes the old UI from the files. Going in to Spotify/Apps folder there are only 4 .spa files, compared to 1.1.58 and below where there are around 30.

Not sure what can be done about this other than downgrading to 1.1.58, but I just thought I'd let you know this happens.

**Comment by Sparoney** [comment]
Update: On my laptop, the files are still there, but ``spicetify backup apply`` works but causes Spotify to be a black screen, however on my desktop, the files are completely removed, and ``spicetify backup apply`` fails

**Comment by khanhas** [comment]
Oh lawd. It's happening.

**Comment by khanhas** [comment]
At the moment, can you download old version: https://spotify.en.uptodown.com/windows/download/3642581 or anywhere else you could find.
Then, follow this guide to stop auto-update: 

Open Admin Command Prompt and type
```
rm %localappdata%\Spotify\Update
mkdir %localappdata%\Spotify\Update
icacls %localappdata%\Spotify\Update /deny "%username%":D
icacls %localappdata%\Spotify\Update /deny "%username%":R
```

**Comment by FinleyGomez** [comment]
> At the moment, can you download old version: https://spotify.en.uptodown.com/windows/download/3642581 or anywhere else you could find.
> Then, follow this guide to stop auto-update:
> 
> Open Admin Command Prompt and type
> 
> ```
> rm %localappdata%\Spotify\Update
> mkdir %localappdata%\Spotify\Update
> icacls %localappdata%\Spotify\Update /deny "%username%":D
> icacls %localappdata%\Spotify\Update /deny "%username%":R
> ```
> 
> After that, running `spicetify backup apply`

Could you let us Mac users know how to do this please?

**Comment by billxsand** [comment]
I do like the new version and unfortunately the only real solution i can see is ppl developing new / porting old themes 😓

**Comment by Theblockbuster1** [comment]
I'm waiting for Spicetify to support the new Spotify UI so I can port my theme.

**Comment by khanhas** [comment]
Hi guys, I just published a new version with initial support for new Spotify. You can build your new theme and update your extensions with it now. Please checkout [release note](https://github.com/khanhas/spicetify-cli/releases/tag/v2.0.0) for critical changes and new features.
To install, please use the same install script but annotate version parameter:
**Windows:**
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -OutFile $env:TEMP\install.ps1
Invoke-Expression "$env:TEMP\install.ps1 2.0.0"
```
**Linux/MacOS:**
```bash
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh -o /tmp/install.sh
sh /tmp/install.sh 2.0.0
```

**Comment by Sparoney** [comment]
For anyone on Windows getting the error with ``File C:\Users\[User]\AppData\Local\Temp\install.ps1 cannot be loaded
because running scripts is disabled on this system. For more information, see about_Execution_Policies``, do the following:

Open PowerShell as Administrator and type the following commands, pressing A when prompted:
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -OutFile $env:TEMP\install.ps1
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
Invoke-Expression "$env:TEMP\install.ps1 2.0.0"
Set-ExecutionPolicy Restricted
```

**Comment by benpashiro** [comment]
Some of the extensions aren't working yet. Will it be good the next update or? is there a workaround?

**Comment by Theblockbuster1** [comment]
@benpashiro I think that most extensions will have to be ported/re-coded.

**Comment by dominikpflegerl** [comment]
> At the moment, can you download old version: https://spotify.en.uptodown.com/windows/download/3642581 or anywhere else you could find.
> Then, follow this guide to stop auto-update:
> 
> Open Admin Command Prompt and type
> 
> ```
> rm %localappdata%\Spotify\Update
> mkdir %localappdata%\Spotify\Update
> icacls %localappdata%\Spotify\Update /deny "%username%":D
> icacls %localappdata%\Spotify\Update /deny "%username%":R
> ```
> 
> After that, running `spicetify backup apply`

Your link downloads a .dmg for mac. 

I used choco

`choco install spotify --version "1.1.58.820" --ignore-checksums`

Works fine so far 👍🏼
