### ISSUE TITLE
having trouble backing up app files

### ISSUE THREAD

**Issue by Salutiferous** [khanhas/spicetify-cli#559]
It keeps on saying "Cannot backup app files. Reinstall Spotify and try again." and i dont know what im meant to do
I downloaded spicetify v1.2.1 on windows and when i typed "spicetify backup apply enable-devtool" onto powershell it comes with "Cannot backup app files. Reinstall Spotify and try again." and although i reinstalled spotify and deleted all of its files it still happens.
![image](https://user-images.githubusercontent.com/83878084/117568857-51c0d480-b0f5-11eb-8ca5-ec5d111eae46.png)

**Comment by Tread-2036** [comment]
It might be worth checking out these threads: https://github.com/khanhas/spicetify-cli/issues/389
