### ISSUE TITLE
Background Opacity

### ISSUE THREAD

**Issue by jakobkukla** [khanhas/spicetify-cli#56]
Is there a way to make the background of the app partly transparent to see the wallpaper shine through? Like in a transparent terminal window? I tried to change all the background-color values to be transparent but I'm left with a brown color that I can't change anymore.

Thanks!

**Comment by khanhas** [comment]
Sorry you can't. There still is an chromium background that is not customisable.

**Comment by jakobkukla** [comment]
Oh, I'm sad to hear that. Thanks anyway for the quick answer! :)
