### ISSUE TITLE
Spotify black screen when running spicetify

### ISSUE THREAD

**Issue by nick51953** [khanhas/spicetify-cli#564]
Spicetify was running fine until the new update.  I tried running the 2.0.1 version but I'm having issues. I tried entering the script with the new code, but I get a message saying "a file cannot be loaded because running scripts on this system is disabled" even though I ran it through administrator mode. However, it still goes through and says it is installed. But it'll still say I'm using spicetify 1.2.1. Do I need to uninstall it and reinstall with the new version?

**Comment by fIextify** [comment]
I'm running into the exact same problem :)

**Comment by nick51953** [comment]
Update: to fix the message: "a file cannot be loaded because running scripts on this system is disabled" , you need to run in powershell: Set-ExecutionPolicy RemoteSigned 

So, I can install 2.0.0 fine, but I still get the black screen after applying a theme.

**Comment by 0Inspiration0** [comment]
i get a black screen also

i also get this error too

fatal open C:\Users\x\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

**Comment by khanhas** [comment]
Please reinstall Spotify with installer then run `spicetify backup apply`.

**Comment by nick51953** [comment]
Okay, I got it running. However, it's stuck on BIB-Green. I cannot change it. I try using spicetify restore and then spicetify config color_scheme (theme I want) and spicetify apply, but it stays on BIB-Green. 

This is the theme I was using before the update. I had edited it to change the colors and it was working fine.

**Comment by khanhas** [comment]
I don't quite understand what do you mean by "stuck on BIB-Green"

**Comment by nick51953** [comment]
Sorry, I mean it's stuck on one theme and I can't change it. When I try to change the theme, nothing happens, it just stays on one theme. I've tried capitalizing the name of the themes but that doesn't work either.

**Comment by Umbrozium** [comment]
when i entered spicetify backup apply it said i already have a backup, but restoring it just gave me the same black screen.

**Comment by khanhas** [comment]
> 
> 
> Sorry, I mean it's stuck on one theme and I can't change it. When I try to change the theme, nothing happens, it just stays on one theme. I've tried capitalizing the name of the themes but that doesn't work either.

Theme of legacy Spotify is not compatible with new one because CSS names completely different. But color scheme can be changed so you might want to do that



> 
> 
> when i entered spicetify backup apply it said i already have a backup, but restoring it just gave me a black themeless spotify.

Reinstall and run `spicetify backup apply`

**Comment by nick51953** [comment]
Okay, thank you so much!

**Comment by umurkarakas** [comment]
> i get a black screen also
> 
> i also get this error too
> 
> fatal open C:\Users\x\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

I got the same error. I downloaded the spotify using its launcher and I ran spicetify backup apply and it worked. But Spotify keeps getting updated after I run spotify a few hours later than I run spicetify backup apply and theme is gone. Then I get the same error when I try to run spicetify backup apply so I need to redownload spotify multiple times everyday.

**Comment by MatiPlayzzYT** [comment]
> > Sorry, I mean it's stuck on one theme and I can't change it. When I try to change the theme, nothing happens, it just stays on one theme. I've tried capitalizing the name of the themes but that doesn't work either.
> 
> Theme of legacy Spotify is not compatible with new one because CSS names completely different. But color scheme can be changed so you might want to do that
> 
> > when i entered spicetify backup apply it said i already have a backup, but restoring it just gave me a black themeless spotify.
> 
> Reinstall and run `spicetify backup apply`

i did it and i worked while i had spotify opened, whenever i turn off the pc and turn it on again it just stops working and show the "can't find the css" error again when applying

**Comment by gordon-z** [comment]
> 
> 
> > i get a black screen also
> > i also get this error too
> > fatal open C:\Users\x\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.
> 
> I got the same error. I downloaded the spotify using its launcher and I ran spicetify backup apply and it worked. But Spotify keeps getting updated after I run spotify a few hours later than I run spicetify backup apply and theme is gone. Then I get the same error when I try to run spicetify backup apply so I need to redownload spotify multiple times everyday.

I've been getting the same thing and also had to reinstall spotify multiple times a day.

**Comment by 0Inspiration0** [comment]
> Please reinstall Spotify with installer then run `spicetify backup apply`.

this worked for me thanks :) <3

**Comment by khanhas** [comment]
If your Spotify version is 1.1.59, you have 2 choices:
1. Download Spotify 1.1.58 installer from other source and continue to use spicetify v1.2.1. But beware that Spotify will auto update anyway so run this in Powershell to stop autoupdating:
```powershell
rm "$env:localappdata\Spotify\Update"
mkdir "$env:localappdata\Spotify\Update"
icacls "$env:localappdata\Spotify\Update" /deny "$env:username":D
icacls "$env:localappdata\Spotify\Update" /deny "$env:username":R
```

2. Try out spicetify v2.0.1. Run this to install:
**Windows:**
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -OutFile $env:TEMP\install.ps1
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
Invoke-Expression "$env:TEMP\install.ps1 2.0.1"
Set-ExecutionPolicy Restricted
```

**Linux/MacOS:**
```bash
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh -o /tmp/install.sh
sh /tmp/install.sh 2.0.1
```

**Comment by collips** [comment]
> If your Spotify version is 1.1.59, you have 2 choices:
> 
> 1. Download Spotify 1.1.58 installer from other source and continue to use spicetify v1.2.1. But beware that Spotify will auto update anyway so run this in Powershell to stop autoupdating:
> 
> ```powershell
> rm "$env:localappdata\Spotify\Update"
> mkdir "$env:localappdata\Spotify\Update"
> icacls "$env:localappdata\Spotify\Update" /deny "$env:username":D
> icacls "$env:localappdata\Spotify\Update" /deny "$env:username":R
> ```
> 
> 1. Try out spicetify v2.0.1. Run this to install:
>    **Windows:**
> 
> ```powershell
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -OutFile $env:TEMP\install.ps1
> Set-ExecutionPolicy -ExecutionPolicy Unrestricted
> Invoke-Expression "$env:TEMP\install.ps1 2.0.1"
> Set-ExecutionPolicy Restricted
> ```
> 
> **Linux/MacOS:**
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh -o /tmp/install.sh
> sh /tmp/install.sh 2.0.1
> ```

i tried to do 2nd way but when i try to run spicetify command on powershell defender says its ransomware, its very strange.

**Comment by physcrowley** [comment]
https://github.com/khanhas/spicetify-cli/issues/564#issuecomment-841028101

I tried the v2.0.1 spicetify version on a fresh install of Spotify from the official source and still get the black screen.

**Comment by physcrowley** [comment]
> [#564 (comment)](https://github.com/khanhas/spicetify-cli/issues/564#issuecomment-841028101)
> 
> I tried the v2.0.1 spicetify version on a fresh install of Spotify from the official source and still get the black screen.

* So I rebooted. --> no change.
* Then I tried `spicetify backup apply`. --> after a warning I got `Please restore first then backup, run "spicetify restore backup" or re-install Spotify then run "spicetify backup".`
* So I ran `spicetify restore backup` --> got another warning `Spotify version and backup version are mismatched.` but clicked continue anyway. Things ran along, more verbose that the spicetify v1.2, without errors.
* Finally ran `spicetify backup apply`--> everything ran again with the glorious message:
    ![image](https://user-images.githubusercontent.com/53307335/118300628-28ff5d00-b4b0-11eb-9f11-22bbd4a64ef1.png)

Spotify's looking good again!

**Comment by Ku-Tadao** [comment]
> 
> 
> If your Spotify version is 1.1.59, you have 2 choices:
> 
>     1. Download Spotify 1.1.58 installer from other source and continue to use spicetify v1.2.1. But beware that Spotify will auto update anyway so run this in Powershell to stop autoupdating:
> 
> 
> ```powershell
> rm "$env:localappdata\Spotify\Update"
> mkdir "$env:localappdata\Spotify\Update"
> icacls "$env:localappdata\Spotify\Update" /deny "$env:username":D
> icacls "$env:localappdata\Spotify\Update" /deny "$env:username":R
> ```
> 
>     1. Try out spicetify v2.0.1. Run this to install:
>        **Windows:**
> 
> 
> ```powershell
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -OutFile $env:TEMP\install.ps1
> Set-ExecutionPolicy -ExecutionPolicy Unrestricted
> Invoke-Expression "$env:TEMP\install.ps1 2.0.1"
> Set-ExecutionPolicy Restricted
> ```
> 
> **Linux/MacOS:**
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh -o /tmp/install.sh
> sh /tmp/install.sh 2.0.1
> ```

Second method worked like a charm, sadly this does break every theme being applied (if there is a fix for this, be sure to let us know >_<)
