### ISSUE TITLE
New release radar?

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#565]
Hey. I saw that you did something with the release radar after all https://github.com/khanhas/spotify-release-list
Cool. I see it says "add: spicetify compability", but how to install it in Spicetify? I'm asking about legacy Spotify and Spicetify. Or is the work still in progress?

**Comment by khanhas** [comment]
Yeah, it works now. I was busy with spicetify v2 so I kinda forgot about it. And it only works on legacy Spotify at the moment.
- Download https://github.com/khanhas/spotify-release-list/releases/download/v1.7.12/release.zip
- Extract to CustomApps folder
- Add "release" to `custom_apps` field in config file
- Run `spicetify apply`

**Comment by FiftyFour7250** [comment]
@khanhas 

It doesn't work on 1.1.58.820. Just a blank screen when I click on "Release". I even thought that it's problem with compatibility with other extensions and applications, so I deleted everything, and it still doesn't work :c

**Comment by khanhas** [comment]
I can't find legacy spotify installer anywhere so I cant debug this.
Can you try renaming "release" to "releases"?

**Comment by FiftyFour7250** [comment]
Yea, it helped. Thanks.

By the way, is it possible to make it open in the window of the old release extension? Or at least to have a redirect to it?

**Comment by khanhas** [comment]
No it can't sorry. App is an app and it has to be displayed in main view.

**Comment by FiftyFour7250** [comment]
@khanhas 

Hey, I tried to make it so that the resfresh button was pressed automatically every time the application was launched. I've tried this

```
document.addEventListener("DOMContentLoaded", () => {
    document.getElementsByClassName('SyncButton')[0].click();
});
```

And this

```
window.onload = function() {
     document.getElementsByClassName('SyncButton')[0].click();
}; 
```

And this

```
document.getElementsByClassName('SyncButton')[0].addEventListener('click', clickFunction, false);

function clickFunction() {
}


document.addEventListener("DOMContentLoaded", () => {
    document.getElementsByClassName('SyncButton')[0].click();
});
```

But it all doesn't work. I tried to write this in all the js files, and still nothing, can you tell me what I'm doing wrong?

![21](https://user-images.githubusercontent.com/78786088/118405756-dfff0280-b681-11eb-925e-0157b1e84151.PNG)
