### ISSUE TITLE
Not longer able to add theme

### ISSUE THREAD

**Issue by Dan33185** [khanhas/spicetify-cli#567]
I'm following the instructions here: https://www.makeuseof.com/tag/customize-spotify-with-spicetify-themes/

When I input [Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression](url) into powershell, it runs like normal, but it doesn't finish the install process, it ends at "removing", and never gets to "adding", which I assume applies the theme. I just updated Spotify, so I'm assuming this new updated broke something.

![Untitled](https://user-images.githubusercontent.com/5460711/118155248-a1e1b480-b3dd-11eb-9698-c3d3ca20564e.png)

**Comment by khanhas** [comment]
Please read all instructions one more time
That script only installs Spicetify, it does not install themes from community
