### ISSUE TITLE
Bookmark app for v2.x

### ISSUE THREAD

**Issue by JulienMaille** [khanhas/spicetify-cli#568]
I'm working on fixing the bookmark app for v2.x, my progress is slow and I know @khanhas as high standard for code quality. Is it worth spending some time or will you rewrite the whole thing anytime soon anyway?

PS; thanks again for supporting the new UI

**Comment by khanhas** [comment]
Yeah you could have a try. It's not my top priority right now.

**Comment by JaysonBayson** [comment]
@khanhas Do you know where the bookmarks are stored, so I can look at the items I had bookmarked before?

**Comment by khanhas** [comment]
@JaysonBayson Try spicetify v2.2.5, Bookmark extension was ported.
And it should be compatible with old bookmark storage. If you see no item in bookmark pop over, it's very likely that your local storage was wiped at some point and nothing I can do about it.
