### ISSUE TITLE
Dribbblish not working in v2.0.1

### ISSUE THREAD

**Issue by umurkarakas** [khanhas/spicetify-cli#569]
Hello,

I was using spicetify v1.2.1 but after Spotify started to upload itself in each reboot, I decided to switch to spicetify v2.0.1. I was using DribbblishDynamic theme but I couldn't make it work in v2.0.1. Colors are changing as expected but UI does not change at all when I try Dribbblish & DribbblishDynamic.

Thanks in advance,

**Comment by khanhas** [comment]
I already said in realest note: Legacy Spotify theme are incompatible with new Spotify.
