### ISSUE TITLE
How to change hover over colour of a song, without changing most of the background colour?

### ISSUE THREAD

**Issue by kittenparry** [khanhas/spicetify-cli#57]
After many tries, I've finally found out that mouse hover over colour of a song in an album/playlist is controlled by `main_bg` variable in `color.ini`. But if you change that anything that isn't controlled by `sidebar_and_player_bg` variable gets changed as well, that is sidebars, bottom pane and shadow of header.

I tried pinpointing the CSS block that controlled the mouse hover of songs, looking for `main_bg` in `user.css`, but couldn't find it. Could anyone point me in the direction of the CSS block that controls the mouse hover behaviour? Thanks in advance.

**Comment by khanhas** [comment]
1. In terminal, run `spicetify enable-devtool`.
2. Right click at bottom bar, choose Open Devtool.
3. Use it to find element class/id name and add rules to user.css

If you still get stuck, find help on Spectrum. More people with CSS knowledge can help you.
