### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by vmuun** [khanhas/spicetify-cli#571]
Every time I launch my PC back up, it launches regular Spotify. If I type "spicetify backup apply", into PowerShell, it says, "fatal open C:\Users\tyler\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified." I found a temporary fix for this, which is to delete and reinstall Spotify, but it is very annoying to do it each system boot up.

**Comment by rickvandijck** [comment]
Same here, issue started with the ugly ass web-interface looking update Spotify recently got

**Comment by Silverthorn1111** [comment]
Same here too. Spotify then becomes plain black for me, until I restore the backup.
This doesn't look good 😞

**Comment by Blu-Bit** [comment]
I'm running into the exact same issue.

**Comment by Silverthorn1111** [comment]
You can use this Pre-release https://github.com/khanhas/spicetify-cli/releases/tag/v2.0.1
It will fix the color scheme but not the UI, at least no for me atm.

**Comment by Silverthorn1111** [comment]
This can also help https://spectrum.chat/spicetify/general/spicetify-not-working~ec36b939-36b8-4fb2-b803-aceceadc132b

**Comment by khanhas** [comment]
Upgrade to spicetify v2.1.0, reinstall Spotify and try again.
