### ISSUE TITLE
can somebody help me with this.......

### ISSUE THREAD

**Issue by Vismay23** [khanhas/spicetify-cli#572]
![image](https://user-images.githubusercontent.com/84200709/118311130-1f581280-b50d-11eb-9f8c-17cc0a83ebd0.png)

idk how to solve this...pls help me

**Comment by Silverthorn1111** [comment]
Type : Set-ExecutionPolicy -ExecutionPolicy **Unrestricted** -Scope CurrentUser
then accept with O 
Then run the spicetify command.
then type Set-ExecutionPolicy -ExecutionPolicy **Default** -Scope CurrentUser
and accept with O

**Comment by Ku-Tadao** [comment]
> 
> 
> In the same Powershell window:
> Type : Set-ExecutionPolicy -ExecutionPolicy **Unrestricted** -Scope CurrentUser
> then accept with O
> Then run the spicetify command.
> then type Set-ExecutionPolicy -ExecutionPolicy **Default** -Scope CurrentUser
> and accept with O

^ if that doesn't solve it, try running PS as admin, that should do it.

**Comment by khanhas** [comment]
spicetify v2.1.0 is released. Please use normal install instruction from [wiki](https://github.com/khanhas/spicetify-cli/wiki/Installation) to install.
Reinstall Spotify and run `spicetify backup apply`.
