### ISSUE TITLE
User css problem

### ISSUE THREAD

**Issue by Mersz** [khanhas/spicetify-cli#575]
Hi guys this problem exist 3 4 days. Always i got this problem i need to reinstall spotify
whats the permanent solution?  
![123](https://user-images.githubusercontent.com/84226837/118355755-68927b80-b57a-11eb-8be3-c7e7e82f7c25.PNG)

**Comment by khanhas** [comment]
Upgrade to spicetify v2, reinstall Spotify and try `spicetify backup apply` again.
Read newest release note to know what's going on.
