### ISSUE TITLE
spicetify update doesn't work

### ISSUE THREAD

**Issue by Haberkamp** [khanhas/spicetify-cli#58]
I followed the [instructions](https://github.com/khanhas/spicetify-cli/wiki/Installation). I tried to install spicetify-cli from the AUR and prebuilt. But i alway get this error message: 
`spicetify v0.9.2 fatal open /opt/spotify/Apps/zlink/css/user.css: no such file or directory`

**Comment by khanhas** [comment]
Did you run these: https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage

**Comment by Haberkamp** [comment]
Yes I did.

**Comment by khanhas** [comment]
When you run `spicetify apply`, does it success?

**Comment by Haberkamp** [comment]
No. It says
`spicetify v0.9.2
BOM: read /home/nils/.var/app/com.spotify.Client/config/spotify: is a directory`

**Comment by khanhas** [comment]
Did you install spotify from AUR or elsewhere?

**Comment by Haberkamp** [comment]
I installed spotify & spicetify from the AUR.

**Comment by khanhas** [comment]
Can you do a spotify clean install (not from cache) and try again?

**Comment by khanhas** [comment]
And remember to set spotify files permissions before applying.

**Comment by Haberkamp** [comment]
I now reinstalled spotify trough flatpak and spicetify-cli via prebuilt. Exactly like in the github wiki. Still same error.

**Comment by MAMAdzwoni** [comment]
How is this closed if issue wasn't resolved?

**Comment by FrenzyExists** [comment]
I have a similar issue, however, in my case spicetify can't find the prefs file, I tried searching it manually at /opt/spotify/, but no luck. Any suggestions?

**Comment by khanhas** [comment]
@FrenzyExists it's probably in your `~/.config/spotify`

**Comment by roozbehzarei** [comment]
> No. It says `spicetify v0.9.2 BOM: read /home/nils/.var/app/com.spotify.Client/config/spotify: is a directory`

Go to `home/nils/.config/spicetify` and edit the `config-xpui.ini`'. It has a `prefs_path` field that should point to: `/home/nils/.var/app/com.spotify.Client/config/spotify/prefs`.

**Comment by haseebabid72** [comment]
What is the sollution to this issue?
