### ISSUE TITLE
dont know how to change colour in spicetifydefault

### ISSUE THREAD

**Issue by Vismay23** [khanhas/spicetify-cli#580]
can somebody help me....i dont know how to change the coulour in spicetify default theme....i dont want this white and orange theme....pls help me change the colour....

**Comment by maycarlos** [comment]
The default theme has these color schemes in the color.ini file
 `pink-white, green-dark, nord-light, nord-dark, purple and dracula`
You can change between these color schemes like this
`spicetify config color_scheme [insert_color_scheme]`
And then apply the changes
`spicetify apply`
