### ISSUE TITLE
popup lyrics wont show settings

### ISSUE THREAD

**Issue by bakzkndd** [khanhas/spicetify-cli#581]
when i try to right click the lil mic icon nothing happens

in console i get this error
![image](https://user-images.githubusercontent.com/50497725/118375066-99e16a80-b5bf-11eb-9805-1d22f741372c.png)

which leads to
![image](https://user-images.githubusercontent.com/50497725/118375072-a4036900-b5bf-11eb-8772-e3aff4ec8c6c.png)

**Comment by khanhas** [comment]
Try run `spicetify restore backup aplply`

**Comment by bakzkndd** [comment]
that worked, thanks
