### ISSUE TITLE
Pink & White

### ISSUE THREAD

**Issue by vmuun** [khanhas/spicetify-cli#582]
Every time I try to reinstall Spicetify into Spotify, it turns the default Spotify theme into an ugly pink and white theme. It also does not add the extensions that I wrote into the config. I've been trying to do this for around 3 hours now. I tried to do the Spicetify Default Nord-Dark theme. 
![Spotify Premium 5_15_2021 2_56_57 PM_LI](https://user-images.githubusercontent.com/84197893/118375186-0e031a80-b58e-11eb-99de-63ac1e4f853d.jpg)

**Comment by khanhas** [comment]
Run `spicetify -c` to know exactly where config is
Change color scheme if you don't like white. 
And please read the release note and help text (`spicetify -h`) before asking.
