### ISSUE TITLE
DJ mode button missing

### ISSUE THREAD

**Issue by soopfox** [khanhas/spicetify-cli#583]
Hello Khanhas
I'm having some issues getting DJ-Mode to work. The button to toggle it on and off does not appear in the menu. As the screenshot below shows, it has been added to the extensions list and appears correctly in the CLI. Any suggestions? 

![image](https://user-images.githubusercontent.com/84250165/118378100-9ce55680-b5d1-11eb-83a0-b834de35be1c.png)

**Comment by khanhas** [comment]
Porting DJ mode on new version requires a lot of work and I don't think it's worth it at the moment.

**Comment by soopfox** [comment]
My guess was that it was due to the newer Spotify layout, but I was hoping it was just something I did wrong that I could fix. Thank you for the response though.
