### ISSUE TITLE
Download spicetify 1.2.1

### ISSUE THREAD

**Issue by kieran0377** [khanhas/spicetify-cli#584]
I downgraded Spotify to the Dec 2020 version because of the new UI, how do I keep using spicetify v1.2.1?

**Comment by itsmeow** [comment]
You can download it from the releases page. https://github.com/khanhas/spicetify-cli/releases/tag/v1.2.1

**Comment by khanhas** [comment]
Specifiy version variable before executing installing script
```powershell
$v="1.2.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
```

**Comment by kieran0377** [comment]
Thanks, I tried but I keep getting this error. error Cannot backup app files. Reinstall Spotify and try again.

**Comment by khanhas** [comment]
Did you try reinstalling Spotify and try `spicetify backup apply` as it suggested?

**Comment by kieran0377** [comment]
Yup a few times, I must've messed something up before but it worked after a restart. Cheers man, appreciate the help!
