### ISSUE TITLE
Extensions and themes not working, but colours are.

### ISSUE THREAD

**Issue by Achachak** [khanhas/spicetify-cli#585]
I just installed spotify using spotify's official method for "[Debian / Ubuntu](https://www.spotify.com/se/download/linux/)", and i installed spicetify using the [Spotify installed from Snap instructions](https://github.com/khanhas/spicetify-cli/wiki/Installation). The command line gives me good results, for example inputting `spicetify config extensions` gives me the list of all supposedly installed extensions. And changing colors with `spicetify color` works fine too. Yet for some reason extensions arent showing up in spotify, and i tried installing dribbblish dynamic, and the theme seems to be installed according to the spicetify command line, but its not showing anything in client. Im able to start dev tools, as i do have the white context menu with a "Show DevTools" option.

Im at a total loss. Did i miss a step somewhere? If there is any sort of log i can upload i will gladly do so.

**Comment by lukethacoder** [comment]
Most likely has something to do with the latest release of Spicetify (v2 - https://github.com/khanhas/spicetify-cli/issues/557), built to support the new Spotify update.

checkout the release notes (https://github.com/khanhas/spicetify-cli/discussions/578) which outline the need to re-build extensions from the ground up.
