### ISSUE TITLE
Wait for Spotify to load (extension)

### ISSUE THREAD

**Issue by Theblockbuster1** [khanhas/spicetify-cli#586]
Is there a function for checking when Spotify has completely loaded? I've tried using:
```js
window.load = function() { ... };
document.addEventListener("DOMContentLoaded", function() { ... });
window.addEventListener("load", function() { ... });
```
But none of them have been successful, as after immediately calling `Spicetify.Player.isPlaying()`, it outputs `Cannot read property '_state' of undefined`, meaning that the `Spicetify.Player.origin` has not yet been initialised (`undefined`). Additionally, the page hasn't been loaded and accessing elements returns `null`.

**Comment by khanhas** [comment]
Wrap your code inside a function like this, check `origin` availability and other API if you need them. If they're not there at the moment of checking, function will be called again after 500ms.
```js
(function YourExtension(){
	if (!Spicetify.Player.origin) {
		setTimeout(YourExtension, 500);
		return;
	}
	// Do stuff
})();
```

**Comment by Theblockbuster1** [comment]
@khanhas Thanks! I just added 
```js
if (!Spicetify.Player.origin || !document.querySelector(selector)) {
```
and it worked great.
