### ISSUE TITLE
Releases v2.0.0, v2.0.1 and v2.1.0 are incorrectly tagged and dont include the mentioned changes in release notes and prebuild binaries arent built from the code at that point

### ISSUE THREAD

**Issue by parona-source** [khanhas/spicetify-cli#587]
Notable differences in behavior:
1. `spicetify -v`
Prebuilt binary outputs 2.1.0, but its set to 1.2.1 in source code.
https://github.com/khanhas/spicetify-cli/blob/294ba116300ad317ea7e91ae1169efb9ac554a5c/spicetify.go#L16
2. `spicetify -h config`
Prebuilt binary doesnt output this:
https://github.com/khanhas/spicetify-cli/blob/294ba116300ad317ea7e91ae1169efb9ac554a5c/spicetify.go#L398-L423
3. `spicetify -c` 
Points to `config-xpui.ini` in prebuilt binary and not `config.ini` like source code says:
https://github.com/khanhas/spicetify-cli/blob/294ba116300ad317ea7e91ae1169efb9ac554a5c/spicetify.go#L58-L59
https://github.com/khanhas/spicetify-cli/blob/294ba116300ad317ea7e91ae1169efb9ac554a5c/src/cmd/cmd.go#L185-L186

I can reproduce behaviour the source code with a self built binary.

Otherwise the major change touted in 2.0.0 of moving from `config.ini` to `config-xpui.ini` is completely missing from released source code and as of 294ba116300ad317ea7e91ae1169efb9ac554a5c `config.ini` is still used.

There is also discrepancies with reddit being removed from CustomApps according to release notes and in the prebuild release but source code still includes it. Also source code includes extra extensions that shouldn't be there according to release notes and in the prebuild releases like `bookmark.js`, `djMode.js` and `queueAll.js`.

For all intents and purposes released source code is missing most changes included in the binaries and release notes. These are only the differences that I could be bothered to look into, there are probably more differences and discrepancies.

Currently the simplest explanation to me at least is that @khanhas builds the binaries on his personal copy of the repository and forgot to commit/push changes.

**Comment by elsandosgrande** [comment]
@parona-source All of the changes seem to be in the `xpui` branch. For example: https://github.com/khanhas/spicetify-cli/blob/4faf82fe7f9d31a051f77fcbcc5ea77a55b03954/spicetify.go#L16

**Comment by parona-source** [comment]
So it seems like a mishap with forgetting to update master branch with the major changes and then tagging it.

**Comment by khanhas** [comment]
Yeah it's my bad, totally forgot that release tar ball only contains master.
I had some work in progress at moment, when I'm done I will swap branch name and draft new release.
