### ISSUE TITLE
High GPU usage when in full app display mode

### ISSUE THREAD

**Issue by skarfie123** [khanhas/spicetify-cli#588]
When turning on "full app display" (from built-in `fullAppDisplay.js`), GPU usage is very high, with noticeable lag.

![image](https://user-images.githubusercontent.com/50425728/118403181-1f6b2600-b665-11eb-889c-76bc09fdd539.png)

**Comment by khanhas** [comment]
It updates continuously and re-blurs background, that's just how browser render stuff.
Turn off progress bar might help.

**Comment by skarfie123** [comment]
thanks, that does help.
