### ISSUE TITLE
Error with "prefs"

### ISSUE THREAD

**Issue by Digitalworldkamikaze** [khanhas/spicetify-cli#59]
`spicetify apply`
`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini`
What can I do with that?

**Comment by khanhas** [comment]
OS?

**Comment by Digitalworldkamikaze** [comment]
> OS?

Debian Buster

**Comment by ParaIdioma** [comment]
same error Manjaro, KDE, spotify installed with AUR

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/FAQ#1-cannot-find-pref_file
This is a generic solution. It might not work on your distro because Spotify might place user files in different place.
But I think you will get the basic idea and try to use it in places corresponding to your system.

**Comment by ParaIdioma** [comment]
.config.ini had correct location, but i was running: sudo spicetify backup apply enable-devtool
i had to chown /opt/spotify/ and then everything worked.

**Comment by khanhas** [comment]
You shouldn't run `spicetify` with `sudo` though.
If you get write permission related error, just `chmod 777 /opt/spotify`.

**Comment by Digitalworldkamikaze** [comment]
> https://github.com/khanhas/spicetify-cli/wiki/FAQ#1-cannot-find-pref_file
> This is a generic solution. It might not work on your distro because Spotify might place user files in different place.
> But I think you will get the basic idea and try to use it in places corresponding to your system.


Ok, that fixed error with "prefs" location, thanks.
But then I tried to run
`spicetify backup apply enable-devtool`
I got this error message:
`fatal unlinkat /usr/share/spotify/Apps/collection-songs.spa: permission denied`
Since it's permission related error, I tried to run
`sudo chmod 777 /usr/share/spotify/Apps/collection-songs.spa`
But that doesn't work. What can I do with it?

**Comment by khanhas** [comment]
Try `chmod 777 /usr/share/spotify/`

**Comment by Androide7461** [comment]
I have the exact same problem as Digitalworldkamikaze. But when I tried `spicetify backup apply enable-devtool` I got this error message: `fatal unlinkat /opt/spotify/Apps/collection-artist.spa: permission denied`. But I already did `chmod 777 /opt/spotify` like you said. What should I do?

**Comment by jzatarain** [comment]
I have this issue with windows 10 enterprise
I had the spotify app from windows store, I uninstalled it, and got the one from the spotify site, but I still get this error :/

**Comment by khanhas** [comment]
@jzatarain Actually I have no idea how to stop Spotify from migrating to Windows Store version.
If you can, please do remove Windows Store.

**Comment by jzatarain** [comment]
So after uninstalling the app twice, the app finally installed away from the windows store folders.
And after digging around, I set this as my path for the prefs_path: C:\Users\myUser\AppData\Roaming\Spotify\prefs

**Comment by Jayonics** [comment]
> So after uninstalling the app twice, the app finally installed away from the windows store folders.
> And after digging around, I set this as my path for the prefs_path: C:\Users\myUser\AppData\Roaming\Spotify\prefs

The UWP version of Spotify, or any UWP program for that matter, will be a huge pain in the ass to manually change because of the permissions system that denies the user access to UWP appdata folders and corrupts if you take ownership to go inside. If you're someone that likes to dig inside program folders I'd recommend using native Windows Programs over UWP apps whenever possible.

**Comment by PascalDutch** [comment]
If you just installed Spotify, make sure to actually open the app and login, I think that generates the `prefs` file. That fixed it for me.

**Comment by Jayonics** [comment]
> If you just installed Spotify, make sure to actually open the app and login, I think that generates the `prefs` file. That fixed it for me.

Yeah, I think you're right. Unless you are logged in or have logged in there will be no `%APPDATA%\Spotify\Users\YOURUSERID` directory and hence no **prefs** file. I set up UE-V to sync my Spotify settings (The stuff that doesn't save in the cloud like Audio Quality, Volume Normalisation setting, e.c.t.) and can confirm that once you:
1. Login with the same Spotify User on multiple devices.
2. Roam/Sync the prefs file under %APPDATA%\Spotify\YOURUSERID. 
3. All my settings roam correctly.

This is my UE-V template if anyone is interested 👍
[https://github.com/Jayonics/UE-V-Hub/blob/master/Templates/Spotify.xml](url)
