### ISSUE TITLE
Cannot open the config menu of new popupLyrics extension (+ Apostrophe in lyrics of some songs)

### ISSUE THREAD

**Issue by momiji-oroshi** [khanhas/spicetify-cli#594]
I like this new extension very much but just cannot open the config when I tried right-clicking the icon as explained in the official release note. Does anyone else have the same problem?

Also I got a problem of some song's lyrics not showing apostrophe properly (it says "&apos;") but I guess this is the problem of source and not the extension itself?

**Comment by khanhas** [comment]
What is your spotify version?
It works fine on mine but some others have problem opening it too.
Also what song are you mentioning, I can have a look.

**Comment by nils-kt** [comment]
Hi, I have the same problem with open the options.
Spotify: 1.1.59.712.g54f36e5d-a

**Comment by khanhas** [comment]
Can you open console, clear console, try right click at popup lyric icon and see if there is any new log/error appears

**Comment by nils-kt** [comment]
Sure, here:

```
popupLyrics.js:986 Uncaught TypeError: Cannot read property 'check' of undefined
    at createSlider (popupLyrics.js:986)
    at HTMLButtonElement.openConfig (popupLyrics.js:854)
createSlider @ popupLyrics.js:986
openConfig @ popupLyrics.js:854
```

**Comment by khanhas** [comment]
Please make sure you're using spicetify v2.1
Then run `spicetify restore backup apply`

**Comment by nils-kt** [comment]
Its fixed with `spicetify restore backup apply`, thank you!

**Comment by gdude2002** [comment]
I'm now running into this problem myself. I made sure I was up-to-date, and ran `spicetify restore backup apply` as well, but I'm not getting anywhere.

[Here's my config](https://gist.github.com/gdude2002/4cf4a766fc5442ea80285e00fe1b7032), and here's the error in my console:

```
spicetifyWrapper.js:920 
Uncaught TypeError: Cannot read property 'isValidElement' of undefined
    at HTMLElement.display (spicetifyWrapper.js:920)
    at HTMLButtonElement.openConfig (popupLyrics.js:1085)
display @ spicetifyWrapper.js:920
openConfig @ popupLyrics.js:1085
```

I'm using Spotify for Windows, version `1.1.67.586.gbb5ef64e`.

**Comment by hollowshiroyuki** [comment]
Having a similar error on fresh Spicetify 2.6.2 install with `choco`
```
spicetifyWrapper.js:920 Uncaught TypeError: Cannot read property 'isValidElement' of undefined
    at HTMLElement.display (spicetifyWrapper.js:920)
    at HTMLButtonElement.openConfig (popupLyrics.js:1085)
```
