### ISSUE TITLE
Spicetify stuck on default

### ISSUE THREAD

**Issue by x2831** [khanhas/spicetify-cli#595]
I've installed the themes correctly and everything seems correct in my config but the theme won't change, no errors in PowerShell when I run the spicetify config color_scheme command either, I have no idea what's going on but its probably just a stupid mistake on my end

**Comment by kamimema** [comment]
I had the same mistake and yes its a dumb mistake. You were probably working in unzipped folder, but you have to go to this directory "C:\Users\user_name\.spicetify"

**Comment by khanhas** [comment]
Read the release note to know the situation.
