### ISSUE TITLE
Spicetify themes no longer updating visuals on spotify. 

### ISSUE THREAD

**Issue by ThePlixel01** [khanhas/spicetify-cli#597]
Today when I booted up Spotify, my Spicetify settings were gone, as is normal. I went through the motions of reinstalling spotify, restoring by Spicetify backup and then changing my theme to Dribbblish, as normal. But instead of updating everything as it normally should, the client did not update. My client looks like a recolored version of the Web Player, as opposed to how it should look. Any fixes are appreciated. Below is how my client looks, vs how it should. Also included is my Config list in powershell. 
![base](https://user-images.githubusercontent.com/71137112/118517149-f7330400-b704-11eb-9dff-06c6e7ea50c7.png)
![jacoblee](https://user-images.githubusercontent.com/71137112/118517173-fd28e500-b704-11eb-8b56-ee83e1dacc1b.jpg)
![config](https://user-images.githubusercontent.com/71137112/118517342-1df13a80-b705-11eb-9b3c-28e474c0badd.jpg)

Thanks for the help.

**Comment by qwersteve07** [comment]
Im facing the similar problem.
I tried to overwrite the default theme with my custom theme, and after that I can't open spotify anymore

**Comment by terry182** [comment]
Dribbblish does not work with this version of spotify. Check the theme repo

**Comment by OhItsTom** [comment]
how would you go down a version in spotify though? because dribbblish is the only theme i like and now its suddenly broken

**Comment by Shinyhero36** [comment]
That's because there is a new Spotify update. We have to wait for theme creators to update their themes if they are willing to update their themes once more.
