### ISSUE TITLE
Any solution to the ongoing issues?

### ISSUE THREAD

**Issue by Hexlicious** [khanhas/spicetify-cli#598]
I've seen plenty of ways to make spicetify work, but none of them seem to stick, as soon as you restart your computer spotify will auto update and make it not function.

Is there any method that actually works?

**Comment by snjyr123** [comment]
https://www.youtube.com/watch?v=ucFVg9jnXbw&list=LL&index=5&ab_channel=GaneshH 
This seemed to work for me but instead downloading the .zip I used the powershell method, although I have problems with the new spicetify update as you can see on my latest issue :).
