### ISSUE TITLE
Offer dark theme default

### ISSUE THREAD

**Issue by NuroDev** [khanhas/spicetify-cli#6]
> Currently the default theme provided is a light there. There is a dark theme example given in the README:

![](https://i.imgur.com/e4CWeRC.png)

> Would it be possible to also ship this with the current default theme? That way we have both a custom light theme and a custom dark theme.

**Comment by khanhas** [comment]
Themes folder location is same folder of `spicetify` executable.  
`SpicetifyDefault` theme folder can be found in there.  
1. In `SpicetifyDefault`, open `color.inc` file.
2. I included both color scheme but dark scheme colours are commented out. So comment out light scheme colours and uncomment dark ones.
3. Save
4. Run `spicetify update`
5. Restart Spotify (or hit Ctrl + Shift + R if DevTool is enabled)

**Comment by NuroDev** [comment]
Ah okay, perfect! 👍

**Comment by DragoCubed** [comment]
if anyone else came here from google:
https://github.com/khanhas/spicetify-cli/releases/tag/v0.9.3

> Theme SpicetifyDefault: Move dark colorscheme to its own section. Now user can just run these commands to switch to default Dark theme:
```
spicetify config color_scheme Dark
spicetify apply
```
