### ISSUE TITLE
Fatal unlinkat on any action

### ISSUE THREAD

**Issue by megaturbo** [khanhas/spicetify-cli#60]
When I'm trying to do anything with spicetify I got this error
```bash
fatal unlinkat /opt/spotify/Apps/lyrics.spa: permission denied
```

Any idea why? I tried to modify this file permission but it doesnt change anything apparently.

**Comment by khanhas** [comment]
Did you use the command I put in Linux user note in Installation page?

**Comment by megaturbo** [comment]
It appears that I'm definitely unable to read. Sorry for wasting your time.
