### ISSUE TITLE
Transferring user.css

### ISSUE THREAD

**Issue by OhItsTom** [khanhas/spicetify-cli#600]
fatal open C:\Users\tomfi\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

Opened up spotify and noticed spicetify had uninstalled itself again, i tried running spicetify apply and spicetify update to no evail, so i ran spicetify clear, reinstalled spotify and tried to create a backup using spicetify backup apply and now this is showing up i dont know what to do

**Comment by OhItsTom** [comment]
![Uploading image.png…]()

**Comment by mortenanakin** [comment]
Same here, started today :(

**Comment by OhItsTom** [comment]
Uninstall Spotify, backup your themes, plugins, and extensions. Then delete both spicetify folders (the hidden one too) in your user folder (C:/users/name) restart your pc, reinstall spotify, then reinstall spicetify, then move your plugins and themes back into the appropriate folders.

Then follow the image below:
![image](https://user-images.githubusercontent.com/22730962/118553595-6ab23100-b758-11eb-8f6b-3403dd73f692.png)
