### ISSUE TITLE
Spicetify not working anymore?

### ISSUE THREAD

**Issue by mortenanakin** [khanhas/spicetify-cli#601]
Hi, everything was OK until this morning, i has the dark theme installed. Now, I power on my PC and Spotify is stuck its own default theme. I run the powershell and got this:

fatal open C:\Users\juani\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.
PS C:\Users\juani>

**Comment by OhItsTom** [comment]
Uninstall Spotify, backup your themes, plugins, and extensions. Then delete both spicetify folders (the hidden one too) in your user folder (C:/users/name) restart your pc, reinstall spotify, then reinstall spicetify, then move your plugins and themes back into the appropriate folders.

Then follow the image below:
![image](https://user-images.githubusercontent.com/22730962/118553595-6ab23100-b758-11eb-8f6b-3403dd73f692.png)

**Comment by OhItsTom** [comment]
However some themes no longer work in this latest version of spotify and you'll have to wait for the creators of said themes to update, if they ever will.

**Comment by khanhas** [comment]
Read release note.
