### ISSUE TITLE
Spicetify wont run after shutting down

### ISSUE THREAD

**Issue by bbpoizon** [khanhas/spicetify-cli#602]
I installed this successfully a few days ago and spicetify wouldn't run after rebooting my computer.

I uninstalled both spicetify and spotify
downloaded spotify
ran: brew install khanhas/tap/spicetify-cli

came back as:
`NCG-IMAC-01:~ cbrown$ spicetify
success Default config.ini generated.
info Run "spicetify -h" for commands list.
NCG-IMAC-01:~ cbrown$ spicetify backup apply enable-devtool
spicetify v1.2.1
Backing up app files:
OK
Extracting:
OK                       
Preprocessing:
OK                       
OK                       
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
fatal open /Applications/Spotify.app/Contents/Resources/Apps/zlink/css/user.css: no such file or directory`

Why am I now getting this error when I never received it the first time? All of the suggestions that I've been able to find online just have me running in circles, ultimately receiving the same error message.

**Comment by Frai7ty** [comment]
I am also getting this error.

**Comment by Pmanen** [comment]
Spotify recently replaced their desktop app with a completely different version that has a codebase largely based on the web app. Likely this also means that the configuration files are stored differently, if they are accessible at all, and that the Spicetify add-on will need to be rewritten :(
Source: https://pr-newsroom-wp.appspot.com/2021-03-25/introducing-a-new-spotify-experience-across-desktop-app-and-web-player/
