### ISSUE TITLE
And now Spicetify upgrades to the new UI instead of reverting

### ISSUE THREAD

**Issue by Mavoy** [khanhas/spicetify-cli#605]
I know it's been reported by the others already but I'm going to report my exact situation. As you all know, Spotify update forces stupid UI on everyone. I got back to the old UI using this method https://old.reddit.com/r/spotify/comments/mpxwz3/reverting_to_the_classic_desktop_ui/ - deleting everything, downloading old Spotify and modifying prefs file  Then, I reinstalled Spicetify. I had backup before, but I decided to start clean. Unfortunately, as soon as I used "apply", Spicetify reverted to the new UI and stopped working altogether. At least I got back to the old UI via "restore" but I still wanna use Spicetify which I really love. What am I missing?

**Comment by khanhas** [comment]
Read the release note.
