### ISSUE TITLE
WebNowPlaying does not return Artist value on 2.x

### ISSUE THREAD

**Issue by BaconDamage** [khanhas/spicetify-cli#607]
As title says - previous to new spotify and spicetify 2.x WebNowPlaying.js worked flawlessy, but now it does not return Artists value for some reason.
Not sure if this belongs here...

(Also thanks for updates spicetify working with new spotify 👍 )

![image](https://user-images.githubusercontent.com/30985091/118643534-f9689180-b7dc-11eb-9f07-e93d5f62db98.png)

**Comment by aakyol** [comment]
Can confirm this happens on my PC too. I temporarily fixed it by editing webnowplaying.js Line:15 as following:

`ARTIST: () => document.evaluate("//a[contains(@href, '/artist')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML,`

Instead of the if-block there.

**Comment by aakyol** [comment]
Can confirm this happens on my PC too. I temporarily fixed it by editing webnowplaying.js Line:15 as following:

`ARTIST: () => document.evaluate("//a[contains(@href, '/artist')]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML,`

Instead of the if-block there.

**Comment by khanhas** [comment]
@BaconDamage Can you run `spicetify path -e` and paste the output here?

**Comment by khanhas** [comment]
@aakyol I'm 100% sure that you're using old webnowplaying.js
Can you run the command above to find out its path, delete that file and try `spicetify apply` again

**Comment by aakyol** [comment]
@khanhas will do.

**Comment by khanhas** [comment]
Correct file should look like this: https://github.com/khanhas/spicetify-cli/blob/xpui/Extensions/webnowplaying.js

**Comment by aakyol** [comment]
@khanhas yeah I probably downloaded the old zip from old github 🤦‍♂️ Doesn't look like that AT ALL. Thanks a lot.

**Comment by BaconDamage** [comment]
That was it, somehow during transition to 2.01 it deleted this .js and I've copied it from my old download folder.
Deleting old file + running `spicetify apply` fixed the issue.
Thanks for fast reply!

**Comment by aakyol** [comment]
@BaconDamage exact same scenario as mine.
