### ISSUE TITLE
spotify's UI remains same, can only change color schemes after reinstall.

### ISSUE THREAD

**Issue by Jarsay** [khanhas/spicetify-cli#609]
I reinstalled spotify and spicetify as well and it isn't working as it was before. It only changes the color scheme of the app and the UI remains same as default vanilla. 
previously I had dribbblish installed and it worked fine. 
Please help. :-/
This is how it is supposed to look;
![WhatsApp Image 2021-05-18 at 5 49 22 PM](https://user-images.githubusercontent.com/84388290/118650735-66425280-b802-11eb-88bc-368fe57a4e48.jpeg)
This is how it looks right now;
![WhatsApp Image 2021-05-18 at 5 48 42 PM](https://user-images.githubusercontent.com/84388290/118650741-67737f80-b802-11eb-9501-3e57b659f6e7.jpeg)

**Comment by khanhas** [comment]
Read release note.
