### ISSUE TITLE
Permissions error with `apply`?

### ISSUE THREAD

**Issue by Jont828** [khanhas/spicetify-cli#61]
I ran `spicetify` followed by `spicetify backup apply` and got the following error:
```
Copying raw assets:
fatal unlinkat /opt/spotify/Apps/artist.spa: permission denied
```
My Spicetify version is 0.9.3 and I'm running Arch Linux.

**Comment by TornaxO7** [comment]
Did you fix this? I'm confronting the same error

**Comment by TornaxO7** [comment]
Nvm, just found this post: https://github.com/khanhas/spicetify-cli/issues/63
