### ISSUE TITLE
Spotify prefs file is there but Spicetify isn't seeing it. 

### ISSUE THREAD

**Issue by thespyboss** [khanhas/spicetify-cli#610]
My prefs file is at `/home/cazd561/.config/spotify/prefs` but Spicetify doesn't seem to see it. I don't know if this is a chmod thing that I have to do and I don't know the chmod command to use. I have tried deleting my config.ini file multiple times and that didn't work either. The picture below is my config file. I am on Manjaro and installed spicetify-cli-git with `yay spicetify`
![Screenshot_20210518_094946](https://user-images.githubusercontent.com/42257053/118662936-6456a000-b7be-11eb-9063-8d0effaa047d.png)

**Comment by khanhas** [comment]
1. Check its read permission
2. Check its content if it's a valid ini file, sometimes wrong syntax cause it to fail to read

**Comment by thespyboss** [comment]
I think the whole install has a read/write permission problem
![Screenshot_20210518_101321](https://user-images.githubusercontent.com/42257053/118667085-b0571400-b7c1-11eb-8da4-c5ea794937d7.png)

**Comment by thespyboss** [comment]
I can't through the file viewer, change the read and write permissions. They seem to change back whenever I get done setting them.

**Comment by thespyboss** [comment]
If I run `spicetify backup apply` through `sudo` I get this
![Screenshot_20210518_101655](https://user-images.githubusercontent.com/42257053/118667647-2e1b1f80-b7c2-11eb-855f-a3d55d9410a6.png)

**Comment by thespyboss** [comment]
I didnt read the Installation process. I just had to follow the chmod steps there, Sorry about that!
