### ISSUE TITLE
Can't find color schemes mentioned in Release Notes 

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#611]
In the release notes for v2, it's mentioned that there are some new color schemes along with SpicetifyDefault theme.  In my `~/.spicetify/Themes` I cannot find a folder for SpicetifyDefault and therefore don't really know what the names of these color schemes are. Any pointers on where I can find the folder or what the names of the color schemes are would be appreciated.

**Comment by khanhas** [comment]
Run `spicetify path` to know where color.ini file path is.
Open that file and you can see color schemes in different section.
But I recommend you hold on to modify color scheme at the moment because I just did a rework on colors and there are major changes on colors key name.

**Comment by lemonnuggets** [comment]
Ah thanks. Got it now.
