### ISSUE TITLE
Themes dont work though the colors from them apply

### ISSUE THREAD

**Issue by Dwezzle** [khanhas/spicetify-cli#614]
I've tried uninstalling and reinstalling though nothing seems to work. Spicetify is just set to the default theme and when I change it all it does is change the colours. I cant even uninstall the program to set it to the default spotify theme as it doesn't change.

**Comment by maverickvignette** [comment]
You could change the theme name in the **config-xpui.ini** file.

**Comment by Dwezzle** [comment]
> You could change the theme name in the **config-xpui.ini** file.
What I mean is when I change the theme in the config file it only changes the colors and the actual layout. I also cant remove it as I tried uninstalling spicetify and it was still there.

**Comment by khanhas** [comment]
Read the release note.
