### ISSUE TITLE
Option doesn't get highlighted if it's enabled or disabled in the "Popup Lyrics" and "Full Screen Display" menus.

### ISSUE THREAD

**Issue by maverickvignette** [khanhas/spicetify-cli#616]
As seen in the images, I can't figure out if the option is enabled or disabled. 
I just upgraded to 2.2.0 from 1.2.1 and hour ago, and it was working then. The issue arised on upgrading to 2.2.1.

![image](https://user-images.githubusercontent.com/83518932/118698111-a79c2780-b82d-11eb-96e4-79705c4a9728.png)
![image](https://user-images.githubusercontent.com/83518932/118698152-b1be2600-b82d-11eb-9c84-9e0ccb0126a2.png)

**Comment by khanhas** [comment]
Oh crap I forgot about extensions css names

**Comment by khanhas** [comment]
Fixed in v2.2.2
