### ISSUE TITLE
Theme won't apply

### ISSUE THREAD

**Issue by mathvaib** [khanhas/spicetify-cli#617]
I have tried 2 methods, one using the spicetify config current_theme command and by opening the config file and manually changing and then running spicetify apply. I have put all the files in the themes folder as well

**Comment by jacob-gomez** [comment]
I have this same issue. Came to spotify this morning and the window only showed an empty frame due to missing zlink folder within the app's resources.

**Comment by badkidcen** [comment]
Same, most themes won't apply even after redoing everything with the new spicetify update.

**Comment by danivm1** [comment]
Same here, actually it only changes the font of the playlist name, every thing else still the same.

**Comment by nintendork07** [comment]
same issue here, even with the newest v2.2.1 version. 

spotify updated to 1.1.59.712 today automatically and broke spicetify theming

**Comment by khanhas** [comment]
Read release note.
