### ISSUE TITLE
themes are not working

### ISSUE THREAD

**Issue by anvlcan** [khanhas/spicetify-cli#619]
i wanted to use dribbblishdynamic dark scheme i did the config thing and writed the codes on powershell 
first i write spicetify update then spicetify apply after i write spicetify apply it restarts spotify but nothing changes

**Comment by Dblxy** [comment]
I am facing the same issue

**Comment by anvlcan** [comment]
i tried to install older versions of spotify but nothing changed. i gave up

**Comment by FSV-Venom** [comment]
same issue, been using dribbblish forever, but today when I tried to apply it, it didn't work. I've tried applying it and reinstalling spicetify a few times, still nothing. Please fix <3

**Comment by ZenghaoWang** [comment]
same here

**Comment by nintendork07** [comment]
same issue here, even with the newest v2.2.1 version. 

spotify updated to 1.1.59.712 today automatically and broke spicetify theming

**Comment by anvlcan** [comment]
i tried to insatll older version of spotify but nothing changed

**Comment by khanhas** [comment]
Read release note.

**Comment by anvlcan** [comment]
i already read it i installed older version of spotify but nothing changed

**Comment by anvlcan** [comment]
@khanhas
