### ISSUE TITLE
characters not displayed

### ISSUE THREAD

**Issue by Bruhsini** [khanhas/spicetify-cli#62]
hey everybody,

I am using Spicetify for a few months now and I am very pleased with it.
Since last week most of the charaters don´t get properly displayed. There are just a bunch of 
 rectangles which probably means that there´s something wrong with the Unicode, right?

Attached are a bunch of examples:

Bottom row where the play button used to be...

![spotify_playbutton](https://user-images.githubusercontent.com/54752058/64068343-18a14300-cc37-11e9-8259-6e12525fddbf.png)

another examples
![spotify_toprow](https://user-images.githubusercontent.com/54752058/64068365-76358f80-cc37-11e9-945f-26f2b09b17ea.PNG)

I tried using Spotify without Spicetify and it worked perfectly fine.
Reinstalling Spotify doesn´t work either.
Neither does turning off all of the extensions.

Thanks in advance

**Comment by khanhas** [comment]
This problem is still a mystery to me.  Some ppl met it but I never know why. 
But reinstalling Spotify then running `spicetify clear backup apply` always fix
