### ISSUE TITLE
What error is this and how do I fix it?

### ISSUE THREAD

**Issue by Aeget** [khanhas/spicetify-cli#621]
I keep getting this error message, but I don't really know what it means or how to fix it. Can anyone help?
`C:\Users\neaeb\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file.`

**Comment by khanhas** [comment]
Uninstall windows store Spotify and install it via Spotify installer. Delete config file and try again.

**Comment by dylpickles** [comment]
Do you know how to find the config-xpui.ini file? If you open that file up, the 5th line should be labelled "prefs_path" and you can change the file location to the real one where the prefs file is located. I can try to help you more if you're not sure about how to write the correct file path.
