### ISSUE TITLE
After update, theme, extensions, and custom apps aren't working

### ISSUE THREAD

**Issue by snjyr123** [khanhas/spicetify-cli#622]
After I got the new update, it said the "spotify/apps/zlink/css/user.css was not found, then I saw it got updated 15 minutes ago, so I reinstalled spotify and spicetify, uploaded my theme, extension, and custom apps apps back in the appropriate folders, edited the config file, and applied the backup, but the app's theme is not changing.

**Comment by snjyr123** [comment]
Sorry, I am not that good with tech so I'm not sure if my theme is a legacy theme, it is Material Ocean. https://github.com/morpheusthewhite/spicetify-themes/tree/master/Material-Ocean

**Comment by pnthach95** [comment]
Your theme is legacy based on commit history, 29 days ago. Spicetify v2 was released 8 days ago.

**Comment by snjyr123** [comment]
I'm sorry about that. I also tried dribblishdynamic and it was updated 2 days ago and it didn't work, and my apps and extensions also didn't work.

**Comment by snjyr123** [comment]
Sorry for wasting your guy's time. :(
