### ISSUE TITLE
Cant remove default theme from spicetify

### ISSUE THREAD

**Issue by Dwezzle** [khanhas/spicetify-cli#623]
I have been trying to uninstall spicetify though everything I've tried I cannot seem to be able to remove the default theme no matter what. I cant remove the theme and I was wondering if anyone could help as I would like to go back to the default original spotify theme.

**Comment by khanhas** [comment]
Why don't you just reinstall Spotify?

**Comment by Dwezzle** [comment]
> Why don't you just reinstall Spotify?

I've tried it keeps applying the default theme

**Comment by khanhas** [comment]
How can it have spicetify default theme after you reinstalled Spotify to stock?
Try uninstall first then.

**Comment by Dwezzle** [comment]
its very strange, I have uninstalled spotify through windows apps and features and reinstalled it from the website multiple times and it keep opening with the spicetify default theme.
