### ISSUE TITLE
idea: Adding DIY help for custom theming

### ISSUE THREAD

**Issue by RootBurner** [khanhas/spicetify-cli#625]
Can this piece of info be given in the color.ini files for custom themers to easily understand

:DIY HELP
; text                            = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext                      = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; main                          = main field or main bg
; sidebar                      = sidebar bg
; player                        = player bg
; card                           = card bg
; shadow                     = bg of buttons like account, pop-up lyrics, full app display in main field
; selected row             = color of the song selected, scrollbar, caption and details of playlist, download and options button
; button                       = playlist buttons bg in sidebar, drop-down menus, now playing song, play button bg, like button
; button-active             = hover on song selected
; button-disabled         = seekbar bg, volume bar bg
; tab-active                   = button bg in library main field (playlists,podcasts,artists,albums)
; notification                = notification
; notification-error       = error
; misc                           = misc

**Comment by McStecca** [comment]
make a pull request
