### ISSUE TITLE
Theme is not applied

### ISSUE THREAD

**Issue by Mohammadreza99A** [khanhas/spicetify-cli#629]
I have arch linux with spotify installed from aur. I changed permissions on `/opt/spotify` and `/opt/spotify/Apps` and when I apply Nord theme found [here](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Nord), I receive this output but the spotify theme stays in the default theme.

Here is the output:
```
spicetify v2.2.2
Err
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
```

and here is the output of `spicetify color`:
```
text (*)                                        | ffffff | 255,255,255
subtext (*)                                     | b3b3b3 | 179,179,179
main (*)                                        | 121212 | 18,18,18
sidebar (*)                                     | 000000 | 0,0,0
player (*)                                      | 181818 | 24,24,24
card (*)                                        | 282828 | 40,40,40
shadow (*)                                      | 000000 | 0,0,0
selected-row (*)                                | ffffff | 255,255,255
button (*)                                      | 1db954 | 29,185,84
button-active (*)                               | 1ed760 | 30,215,96
button-disabled (*)                             | 535353 | 83,83,83
tab-active (*)                                  | 333333 | 51,51,51
notification (*)                                | 4687d6 | 70,135,214
notification-error (*)                          | e22134 | 226,33,52
misc (*)                                        | 7f7f7f | 127,127,127
main_fg                                         | d8dee9 | 216,222,233
secondary_fg                                    | e5e9f0 | 229,233,240
main_bg                                         | 2e3440 | 46,52,64
sidebar_and_player_bg                           | 2e3440 | 46,52,64
cover_overlay_and_shadow                        | 000000 | 0,0,0
indicator_fg_and_button_bg                      | 81a1c1 | 129,161,193
pressing_fg                                     | 4c566a | 76,86,106
slider_bg                                       | 434c5e | 67,76,94
sidebar_indicator_and_hover_button_bg           | 81a1c1 | 129,161,193
scrollbar_fg_and_selected_row_bg                | 4c566a | 76,86,106
pressing_button_fg                              | 5e81ac | 94,129,172
pressing_button_bg                              | 3b4252 | 59,66,82
selected_button                                 | 81a1c1 | 129,161,193
miscellaneous_bg                                | 434c5e | 67,76,94
miscellaneous_hover_bg                          | 81a1c1 | 129,161,193
preserve_1                                      | ffffff | 255,255,255

(*): Default color is used
```

Here is my `config-spui.ini`:
```
[Setting]
spotify_launch_flags    = 
prefs_path              = /home/mohammadreza/.config/spotify/prefs
current_theme           = Nord
replace_colors          = 1
overwrite_assets        = 0
check_spicetify_upgrade = 0
spotify_path            = /opt/spotify
color_scheme            = Nord
inject_css              = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions  = 
custom_apps = 

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.56.595.g2d2da0de

```
I am using Arch linux with AwesomeWM with spotify installed from aur. I already tested this with other themes but the situation is the same.

**Comment by umurkarakas** [comment]
Same here, it started to happen after I updated Spicetify to v2.2.2.

**Comment by TyphoonTeaser** [comment]
I think there was an update to the color schemes and some css. SpicetifyDefault theme do is working, was updated today.     
Tested it with the different color schemes, including Nord. You can transfer that color scheme to the Nord theme and should work but has a couple broken gradients

**Comment by TyphoonTeaser** [comment]
[Spicetify-cli v2.1.0](https://github.com/khanhas/spicetify-cli/releases/tag/v2.1.0)

Yes, since 2.0 update all the legacy themes are incompatible so they will need to be updated. If you still wanna use the legacy Spotify themes and apps you can rollback by unistalling and installing an older version (previous to v1.1.56)

**Comment by HighSaint** [comment]
Is there a way to change the colorscheme of the default theme? I am pretty sure most people who get themes for spotify aren't all that fond of a white theme, I installed it today and wanted to use Gradianto for example, can I get that color scheme to the default which is working somehow?

**Comment by TyphoonTeaser** [comment]
Use the command `spicetify config color-scheme COLORSCHEMENAME`  
SpicetifyDefault theme has pink-white, green-dark, nord-light, nord-dark, purple and dracula.  

You can add color schemes to the theme by editing the `color.ini` file inside the theme folder.  
 
All the previous themes won't work with the newer Spicetify, They need to be updated to the new Spotify CSS and Spicetify color scheme system. You can see on the library how recently they were updated.
