### ISSUE TITLE
Permission denied when applying

### ISSUE THREAD

**Issue by p3rsephone** [khanhas/spicetify-cli#63]
When I do `spicetify apply enable-devtool` I get the following error
`fatal unlinkat /opt/spotify/Apps/playlist.spa: permission denied`

The backup step went fine, but I keep having this error when trying to apply.

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#note-for-linux-users

**Comment by prateekamana** [comment]
the wiki link seems to be down?

**Comment by afonsojramos** [comment]
@prateekamana Yep, the wiki has been moved to the site! Edited the comment for future visibility.

**Comment by ajmeese7** [comment]
@afonsojramos can you update [this comment](https://github.com/spicetify/spicetify-cli/issues/70#issuecomment-531533504) as well? That's the link I found first and it is also pointing to the old page

**Comment by afonsojramos** [comment]
Thank you for bringing that issue to my attention @ajmeese7! Edited, and will also take the comment in it into account!
