### ISSUE TITLE
idea: Stop the communication of Spotify with Discord

### ISSUE THREAD

**Issue by LotharieSlayer** [khanhas/spicetify-cli#631]
Hi,

It would be cool with an extension to forbid Discord to manage the pause or not of the music on Spotify, but while keeping the "Presence mode" and the "Listen together mode" which is cool.

Because except if we disconnect Spotify from Discord, as soon as we want to share music or even talk with music in our ears, it's impossible because the Discord robot is stupid and does not understand that it's our voice the broadcast and not the music...

Thanks a lot ! :)

**Comment by khanhas** [comment]
It's not possible. Discord controls Spotify via Web API on its own. Spotify client has nothing to do with it.
