### ISSUE TITLE
idea: Add Genius to the Popup Lyrics Extension

### ISSUE THREAD

**Issue by LotharieSlayer** [khanhas/spicetify-cli#632]
Hi,

I don't know if it's already planned but add Genius on Popup Lyrics.js would be great, mostly 50% of my music has lyrics on Genius unlike Musixmatch...

Thanks!

**Comment by khanhas** [comment]
It's under way

**Comment by khanhas** [comment]
Popup Lyrics is not interactable, using Genius lyrics in there would not make sense.
Please try out Lyrics Plus custom app.

**Comment by LotharieSlayer** [comment]
Ok I will try this soon, thanks a lot!
