### ISSUE TITLE
Spicetify Broke need help

### ISSUE THREAD

**Issue by Vroother** [khanhas/spicetify-cli#633]
My spicetify just broke so I uninstalled it and reisntalled it and it's still broken. My dribbblishdynamic, which is what I leave for spicetify is now:

 fatal open C:\Users\jgdmv\AppData\Roaming\Spotify\Apps\xpui\user.css: The system cannot find the path specified.

How do I fix this?

**Comment by T-Raptor** [comment]
bump.
Same problem here.

**Comment by orta** [comment]
Double check you're on v2 of spicetify

**Comment by skim-milk** [comment]
I can apply the default Spicetify theme, but I can't apply custom themes.

Spicetify 2.2.2 
Spotify 1.1.59.712.g54f36e5d-a


```
brew remove spicetify-cli
rm -rf ~/spicetify_data

brew install spicetify-cli #v2.2.2
brew install spotify #v1.1.59.712.g54f36e5d-a
spicetify
spicetify backup apply enable-devtool # this works fine and gives the default spicetify theme
cd ~/spicetify_data
git clone https://github.com/morpheusthewhite/spicetify-themes Themes
spicetify config current_theme Cherry
spicetify apply # this reverts to no theme (normal Spotify)
```

**Comment by chwba** [comment]
I have the same on v2.2.2
```
spicetify config color_scheme Dark
> success Config changed: color_scheme = Dark
> info Run "spicetify apply" to apply new config
spicetify update
> spicetify v2.2.2
> Err
> success Custom CSS is updated
spicetify apply
>spicetify v2.2.2
>Err
>Overwriting themed assets:
>OK
>Transferring user.css:
>OK
>Applying additional modifications:
>OK
>success Spotify is spiced up!
```

**Comment by slowstab** [comment]
legacy custom themes are meant to work on spicetify v1.2.1, so it is normal that they do not work on v2.2.2
that being said i did install spicetify v1.2.1 via the command provided in the readme and i still face the same problem in the OP. currently it seems like i can only use spicetify by upgrading to v2.2.2 and using the new UI.
