### ISSUE TITLE
dribbblish.js not found even though i have it

### ISSUE THREAD

**Issue by XTRZR0** [khanhas/spicetify-cli#635]
Hello, I am having a problem. I have tried installing and uninstalling both spicetify and spotify various times and wanted to apply a theme, but it keeps saying that the extension "dribbblish.js" isn't found even though there is one in the Extensions folder on my .spicetify folder. It would apply the theme, but I still see the default theme over and over. 
![Screenshot (180)](https://user-images.githubusercontent.com/84496289/118933969-04095f00-b974-11eb-8d8e-82e43ee8d524.png)
![Screenshot (181)_LI](https://user-images.githubusercontent.com/84496289/118933983-08ce1300-b974-11eb-8b49-8a3af6cc65e4.jpg)

**Comment by khanhas** [comment]
Dribbblish is not supported new Spotify UI and spicetify v2

**Comment by Firefox2892** [comment]
> Dribbblish does not supported new Spotify UI and spicetify v2

then how do we downgrade down to v1?

**Comment by ajhawkings** [comment]
@Firefox2892 https://github.com/khanhas/spicetify-cli#legacy-spotify
