### ISSUE TITLE
Cannot Install Apps

### ISSUE THREAD

**Issue by porrige51122** [khanhas/spicetify-cli#64]
I have successfully installed spicetify css and a custom theme but I have followed the steps in the wiki to install the custom apps and I am unable to see the bar on the left which shows the installed apps

**Comment by JakeStevenson** [comment]
I wonder if a Spotify client update broke this.  I had the Reddit app in my sidebar before, but it's not there now, and re-applying spicetify does not seem to help.

**Comment by khanhas** [comment]
I will take a look in this weekends

**Comment by porrige51122** [comment]
Thanks, I can send any diagnostic info if you need. I'm on spotify version 1.1.14.475.g566c8beb

**Comment by joshc133** [comment]
Same issue here. Custom app does not load in Spotify.

Spotify Windows Version: 1.1.14.475.g566c8beb

**Comment by khanhas** [comment]
Fixed in v0.9.4
