### ISSUE TITLE
Spicetify v2 - new reddit app doesn't work

### ISSUE THREAD

**Issue by GitGangGuy** [khanhas/spicetify-cli#640]
Hi, I just noticed my scripts broke because of the recent major spicetify overhaul and went through the upgrade process (I believe adding a hint about the recent changes to error messages would significantly reduce the unnecessary issues and frustration here).
I noticed the reddit app, which was announced in version 2.2.1, doesn't work and causes my spotify client to show the 'something went wrong' error message. Without the reddit client as the value for custom_apps, everything works. Here's my `config-xpui.ini`:
```ini
[Setting]
spotify_path            = /opt/spotify
color_scheme            = nord-dark
check_spicetify_upgrade = 1
prefs_path              = /home/<user>/.config/spotify/prefs
current_theme           = SpicetifyDefault
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
spotify_launch_flags    = 

[Preprocesses]
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1

[AdditionalOptions]
extensions  = fullAppDisplay.js|autoSkipVideo.js|loopyLoop.js|shuffle+.js|popupLyrics.js
custom_apps = reddit <---- causes error

[Patch]

; DO NOT CHANGE!
[Backup]
version = <version>
```
I followed the steps in the release notes. What am I doing wrong?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/issues/637

**Comment by GitGangGuy** [comment]
@khanhas So this has to do with me running Arch Linux? Is it possible for you to add full GNU/Linux support? :smile:

**Comment by KsaRedFx** [comment]
I have this issue on Windows 10

**Comment by khanhas** [comment]
should be fixed now in spicetify v2.2.3

**Comment by GitGangGuy** [comment]
@khanhas Thanks for working so tirelessly on getting this to work for the apparently outdated Linux spotify version! :100:

**Comment by khanhas** [comment]
Thank you very much! Glad you have fun with spicetify.
