### ISSUE TITLE
Can't find user.css file

### ISSUE THREAD

**Issue by guo0O0o** [khanhas/spicetify-cli#641]
I use Spicetify so I don't have to use the new Spotify UI but every once in a while it still reverts back. The last few times I've been able to fix it by following the basic usage instructions and just doing it again but now it's not working because I can't find the user.css file when I try to do `spicetify backup apply enable-devtool`. Before this, I might have installed another copy of Spicetify by installing the older release? I'm not sure if that has something to do with it so I uninstalled Spotify and deleted all files of Spicetify and reinstalled each. It's still giving me the same error.

**Comment by khanhas** [comment]
`spicetify path color`

Run `spicetify -h` for other commands

**Comment by chwba** [comment]
I have the same problem, fresh install of spotify followed by `spicetify backup apply enable-devtool`
