### ISSUE TITLE
Apply breaks UI

### ISSUE THREAD

**Issue by tomasrudh** [khanhas/spicetify-cli#643]
Spotify version: 1.1.59.712.g54f36e5d-a
Spicetify version: 2.2.2

When I run Spicetify Apply do I get this:
spicetify v2.2.2
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!

And after that is the Spotify UI blank. Running Spicetify Restore makes Spotify work properly again.

Any idea what is going on? Have I missed something?
I did have Spicetify working with an earlier version of both Spotify and Spicetify. I am primarily using Spicetify for the webnowplaying extension.

Btw, thanks for a great utility!

**Comment by khanhas** [comment]
Reinstall Spotify, run `spicetfy backup apply`.

**Comment by callum-dixon** [comment]
I'm also having this issue, I've tried rolling back Spotify to an earlier version and it's still blank after applying any changes

**Comment by tomasrudh** [comment]
I have tried to uninstall Spotify, reboot, and installed again. Same problem. I have not installed Spotify from Microsoft Store.

**Comment by khanhas** [comment]
Try spicetify v2.2.3

**Comment by tomasrudh** [comment]
That works! I had to reinstall Spotify again, but it works. Thanks for your quick support!
