### ISSUE TITLE
Sudden Update Causes "Something Went Wrong" Error

### ISSUE THREAD

**Issue by OriginSaint** [khanhas/spicetify-cli#644]
Launched spicetify.exe and got a very fast update. Once it was finished, I did the "spicetify backup apply" command, but once it launches, I get an error "Something went wrong".

I have already tried uninstalling Spotify and re-installing and then re-running "spicetify backup apply", and get the exact same result.

I also tried running "spicetify apply", and when it launched, same error. Attached is an image.

![image](https://user-images.githubusercontent.com/16825705/119176274-e18d4980-ba38-11eb-936d-5bf797b0d908.png)

**Comment by LotharieSlayer** [comment]
yup, I have the same exact problem too, it seems to be the last Spotify update. :(

**Comment by BluTree** [comment]
This seems to appear when a custom app is enabled, I had this only when the reddit app was enabled. Sadly, the extensions disappeared too with the latest update

**Comment by OriginSaint** [comment]
> **This seems to appear when a custom app is enabled, I had this only when the reddit app was enabled.** Sadly, the extensions disappeared too with the latest update

That was it. Removing the reddit custom app in the config-xpui.ini file and then running "spicetify backup apply" seemed to alleviate the issue. Obviously that means custom apps are not working any longer (or at least the reddit one), which is still something to look into, but at the very least, I get a _slightly_ better UI and some useful features back again.

**Comment by khanhas** [comment]
What is your Spotify version?
Let me investigate this

**Comment by BluTree** [comment]
I had the issue with the 1.1.59.714.g7e040462-a

**Comment by khanhas** [comment]
Should be fixed now on v2.2.3
