### ISSUE TITLE
popupLyrics doesn't actually show up

### ISSUE THREAD

**Issue by KsaRedFx** [khanhas/spicetify-cli#645]
I've applied popupLyrics as part of my config file, and despite that the microphone icon never shows up

```
[AdditionalOptions]
custom_apps = 
extensions  = webnowplaying.js|trashbin.js|popupLyrics.js|loopyLoop.js
```

Currently on Windows 10, using the latest Spicetify (2.2.2) and the latest Spotify (1.1.59.714.g7e040462-a) available to me via the auto-updater. 
All other extensions are working fine so far, it seems to just be popupLyrics.js that isn't working 

The other ticket (#637) seemed to be noted as being related to Linux, so I created one specifically about Windows environments

**Comment by 144hertzmonitor** [comment]
same here, all the other extensions work except for popupLyrics - the microphone icon doesn't show up

**Comment by OuterWild** [comment]
this happens for me too, on the popupLyrics, fullAppDisplay and one from a third party theme with an extension wich also is listed as compatible with the newest version.

**Comment by khanhas** [comment]
Should fixed now in spicetify v2.2.3

**Comment by skarfie123** [comment]
working again for me in v2.2.3

**Comment by KsaRedFx** [comment]
Works great for me!
