### ISSUE TITLE
spicetify wont start

### ISSUE THREAD

**Issue by teachann** [khanhas/spicetify-cli#646]
i restarted my computer a few times to do some installations for other things and when i try to open spicetify it gave me an error, i reinstalled it because it wouldn't work, when i do spicetify backup apply it gives me the same thing as before;

```
fatal open C:\Users\(my name)\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.
PS C:\Users\(my name)>
```

**Comment by SonGorLick** [comment]
You have to update spicetify

**Comment by teachann** [comment]
> You have to update spicetify

i did though i reinstalled it and stuff as i said

**Comment by khanhas** [comment]
Make sure you're on Spicetify v2.2.3
Reinstall spotify and run `spicetify backup apply`

**Comment by AustrAlienGH** [comment]
I've tried that as well and I'm still getting the issue, I've reinstalled spotify and spicetify multiple times at this point

**Comment by khanhas** [comment]
Can you post command output?
Provide your spotify version and spicetify version.

**Comment by AustrAlienGH** [comment]
spicetify v1.1.0
Overwriting themed assets:
OK
Transferring user.css:
fatal open C:\Users\[User]\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

**Comment by khanhas** [comment]
Dude, please upgrade to spicetify v2.2.3
It was announced all over the site

**Comment by khanhas** [comment]
It was said 2 times in this post alone

**Comment by AustrAlienGH** [comment]
I've tried upgrading to 2.2.3 and it won't. I've removed the old spicetify, reinstalled spotify, reinstalled spicetify and it's still on 1.1

**Comment by Akkuya** [comment]
Maybe try uninstalling then pasting this line of code instead of the one shown on the home page?
`$v="2.2.3"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`

All I did was change the version name, and it worked for me.

**Comment by AustrAlienGH** [comment]
Turns out when I uninstall spicetify it doesn't *fully* remove it. The spicetify-cli and .spicetify folders get removed but when I run the `spicetify` command it generates a new config and acts as if it was never uninstalled. Is there any way to fix that?

**Comment by 9hax** [comment]
If the spicetify-cli and .spicetify folders from your user directory really have been deleted, you will have to check other places that your computer looks in to find programs which are ran on the command line.
Those Places are defined in your PATH variables on windows.
Check all folders in your PATH variables (user and system) for a spicetify.exe file, then delete it. 
After that, check if you can still run spicetify in your command line.

You can also just put in spicetify into your windows search, then right click in the "Run command" entry and open the file location.
![image](https://user-images.githubusercontent.com/23525377/120923549-7649a580-c6cf-11eb-812a-2979f78a8492.png)

If both those things still lead to you being able to run spicetify from the command line, install git-scm and use the "which" command as seen here:
![image](https://user-images.githubusercontent.com/23525377/120923586-b6108d00-c6cf-11eb-91b8-1062adc15628.png)

**Comment by AustrAlienGH** [comment]
Works perfectly, thanks!

**Comment by 9hax** [comment]
@khanhas We can close this now :)
