### ISSUE TITLE
extensions do not work with macOS

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#648]
tried with FullAppDisplay, lyrics extension.
theming works

**Comment by applekillerbyjames** [comment]
loop extension works

**Comment by applekillerbyjames** [comment]
on latest version of spotify & spicetify

**Comment by khanhas** [comment]
Please upgrade Spicetify to v2.2.3

**Comment by applekillerbyjames** [comment]
same issues, custom apps do not work, spotify error message says reload page

**Comment by khanhas** [comment]
Run `spicetify restore` and find out what is your spotify version is

**Comment by applekillerbyjames** [comment]
1.1.59.714.g7e040462-a

**Comment by applekillerbyjames** [comment]
[Setting]
overwrite_assets        = 1
check_spicetify_upgrade = 1
spotify_path            = /Applications/Spotify.app/Contents/Resources
current_theme           = SpicetifyDefault
inject_css              = 1
replace_colors          = 1
prefs_path              = /Users/jamesfan/Library/Application Support/Spotify/prefs
color_scheme            = 
spotify_launch_flags    = experimental_features|

[Preprocesses]
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 0
disable_sentry        = 1

[AdditionalOptions]
extensions  = loopyLoop.js|FullAppDisplay.js|autoSkipVideo.js|popupLyrics.js
custom_apps = 

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.59.714.g7e040462

**Comment by applekillerbyjames** [comment]
macOS Big Sur 11.5, mid-2015 Macbook Pro

**Comment by khanhas** [comment]
It should work on 1.1.59.714
Can you run `spicetify restore backup apply`

**Comment by applekillerbyjames** [comment]
yes!!!! thank you
