### ISSUE TITLE
WebNowPlaying results are delayed when playing through another device

### ISSUE THREAD

**Issue by Fosmos** [khanhas/spicetify-cli#649]
So I'm fairly certain this is an issue with the extension and not my use of it in a Rainmeter skin, but it could maybe even be an issue with Spotify itself or the Rainmeter plugin. It's a bit of a tricky bug so let me break down how to recreate it. I've made a skin that shows which song is playing (_https://github.com/Fosmos/Simply check the MeasureMediaWeb.inc in Resources\Include if you want to proof read my usage of the plugin_) and it works great so long as you are viewing the skin on the same device that is playing Spotify. As you know, Spotify allows you to select which device to play the audio through and so what I've noticed is everything will work fine on that device but on other devices that have Spotify+Spicetify+MySkin running the skin will show the track title correctly but the artist and album cover will always be one song behind. It doesn't matter which device you try this on either. Additionally if you open the window to change devices in Spotify it updates and it looks good until either the song finishes or you skip songs using any method (e.g., via the skin, Spotify, and Window's media functions). 

**Example**
Let's say I'm listening to _Track1_ by _Artist1_ through my Desktop and for the sake of the example both my laptop and desktop have just booted up Spotify cleanly (so there's no lingering track history on either). Initially the skin will report correctly on both devices but as soon as _Track1_ completes or I skip it from any device (even my phone) and by any means (that I know of) the laptop will show _Track2_, _Artist1_, and the album art from the first track whereas the desktop will show the correct _Track2_, _Artist2_, and the album art for _Track2_.

**A few side notes**
- Spotify always reports the correct data
- The media controls using the extension work as expected
- Song duration and current time is correct

Like I said I'm fairly certain it's an extension problem but it could very well be a Spotify issue (like some async or power saving thing), however seeing as the app shows the correct data and the Windows' media overlay show the data I'm leaning towards the extension being the culprit. Additionally the song name and a few others are **always** reported correctly so somethings are working it would just be nice if more things worked, haha. In the end it's not a huuuge problem, just thought it was curious. If there's someway to debug the extension I can do some investigating on my own, as well.

**Comment by Tread-2036** [comment]
I have the same issue, but the issue can be replicated even when playing from another client that does not have Spicetify and only Spotify (ie. my iPad).
