### ISSUE TITLE
Glue Resources don't load since latest update

### ISSUE THREAD

**Issue by Chrissi2812** [khanhas/spicetify-cli#65]
Seems the glue resources won't load anymore.
![image](https://user-images.githubusercontent.com/6141652/64422848-57a31e80-d0a5-11e9-9d79-8e8a2d94caf1.png)

![image](https://user-images.githubusercontent.com/6141652/64422824-49550280-d0a5-11e9-910e-b5ed32c4a847.png)

Tried new install and different themes.
Everything in glue-resources folder won't load.

**Comment by khanhas** [comment]
I just tested and spicetify still works alright.
Can you reinstall **Spotify** then run:
```
spicetify clear backup apply
```

**Comment by Chrissi2812** [comment]
Reinstalling and running `spicetify clear backup apply` solved it, thanks 👍🏽
