### ISSUE TITLE
Spicetify not applying any themes.

### ISSUE THREAD

**Issue by Jakethebest1238** [khanhas/spicetify-cli#652]
I usually reinstall spicetify on each Spotify update. Spotify updated itself today meaning I had to reinstall the latest version of Spicetify I usually download the zip file and the themes zip. I then use the Dracula theme. But the theme isn't applying. I tried other themes but non worked. The only theme it applied was the default Spicetify theme. Is this just me or are other people experiencing this.

**Comment by khanhas** [comment]
Said it why multiple times. Read release notes.  Read README page.
