### ISSUE TITLE
The command "Invoke-WebRequest" is either spelled incorrectly or could not be found.

### ISSUE THREAD

**Issue by JoMa25** [khanhas/spicetify-cli#655]
Spicetify didnt work and after reinstalling spotify I only got a blackscreen in the app. Deinstalled spicetify and downloaded spotify again. Now the app works but when trying to install spicetify trough cmd with
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`
on windows 10 I get the error 
`The command "Invoke-WebRequest" is either spelled incorrectly or could not be found.`
I have up to date windows software and wonder how I can fix this.
I also tried
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install_curl.ps1" | Invoke-Expression`
but the same error appears

**Comment by BluTree** [comment]
This is a PowerShell command, you need to open a PowerShell window instead of cmd

**Comment by JoMa25** [comment]
> This is a PowerShell command, you need to open a PowerShell window instead of cmd

Oh wow, there you think you have atleast some coding knowledge and then you dont even know the difference beween cmd and powershell lol. Ty
