### ISSUE TITLE
How to create extra-controls buttons?

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#656]
![image](https://user-images.githubusercontent.com/78786088/119234561-4929be80-bb37-11eb-9e95-bf0ead12f939.png)

Does anyone have an extension with a custom button here? I need example, just seems that something has changed since Legacy

**Comment by khanhas** [comment]
Use devtool to find its class name.
```
const extras = document.querySelector(".ExtraControls");
```
then append or prepend your button to it.
Check its availability first before using it.
