### ISSUE TITLE
Lyrics-plus app doesn't show artists notes on Genius.

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#659]
It's only shows community notes, but not artist's.

A few examples with artist notes:
https://genius.com/Pop-smoke-welcome-to-the-party-lyrics
https://genius.com/Eminem-the-way-i-am-lyrics
https://genius.com/Nas-represent-lyrics

Interestingly, these lines displayed as active.

By the way, it would be cool if the notes from "About this song" displays too

**Comment by khanhas** [comment]
Found the problem. I forgot to get response object of the request result and verified annotation parser reading from wrong object the whole time.
Just overwrite the original one this file:
https://raw.githubusercontent.com/khanhas/spicetify-cli/master/CustomApps/lyrics-plus/ProviderGenius.js
Run this to know where the app located
``
spicetify path -a lyrics-plus
```
After overwriting, run spicetify apply.

**Comment by FiftyFour7250** [comment]
@khanhas 

Now I don't have any annotations at all ¯\\_(ツ)_/¯

**Comment by FiftyFour7250** [comment]
Yea, its fixed. thanks.

**Comment by FiftyFour7250** [comment]
Now one annotation shows for all lines :c

**Comment by FiftyFour7250** [comment]
https://disk.yandex.ru/i/k8jvsztcb7fvWg
