### ISSUE TITLE
Not updating theme or anything

### ISSUE THREAD

**Issue by DarkGhost7** [khanhas/spicetify-cli#66]
When using the cli it seems nothing I do has any effect on the spotify client like changing themes or adding extensions, but I can restart it via the cli... Not sure why this is. Theming used to work for me just fine. I have all the themes in the theme folder and I can use config current_theme theme_name for my different themes and its successfull then I apply it and I have no errors. It restarts spotify, but it always looks the same... not sure why this is.

**Comment by DarkGhost7** [comment]
I reinstalled both and ran the enable dev-tools and I think that was the cause.

**Comment by khanhas** [comment]
What is your OS?
Try reinstalling Spotify first then run `spicetify backup apply`

**Comment by soraino** [comment]
Hi, I am having the same issue as well.
Reinstalled spicetify-cli and Spotify and the themes did not change.
I am using windows 10.

**Comment by khanhas** [comment]
Can you post your config file here?
