### ISSUE TITLE
Prioritize Musixmatch instead of Netease in Lyrics-plus

### ISSUE THREAD

**Issue by Thiagoedlp151** [khanhas/spicetify-cli#661]
I would like to prioritize musixmatch instead o Netease on the synced and unsynced section. I don't know much about coding but I would like some help.

**Comment by khanhas** [comment]
open devtool console and run
```js
localStorage.setItem("lyrics-plus:services-order", `["musixmatch","netease","spotify","genius"]`)
```
Remember to get and set your musixmatch token

**Comment by Thiagoedlp151** [comment]
Thank you!
