### ISSUE TITLE
no config.ini

### ISSUE THREAD

**Issue by jezzae** [khanhas/spicetify-cli#662]
I reinstalled Spotify (from the browser) quite a few times and updated/reinstalled spicetify quite a few times as well.
Nevertheless, I still cannot find any `config.ini` -- It does not exist.
Therefore, my themes and extensions do not work at all.

Edit: I tried the `spicetify -c` and the files (config-x[ui.ini and config.ini) exist in another folder `.spicetify` instead of `.spicetify-cli`
Is this normal ? Because my spicetify does not work on spotify at all.

When i search `C:\Users\MyUser\AppData\Roaming` there is indeed a `prefs` (to answer your question from another issue now closed ). I did have to config the spotify and prefs paths.

What can i do ? Thank you :)

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/discussions/578
