### ISSUE TITLE
Musixmatch lyrics and Karaoke lyrics don't work at all

### ISSUE THREAD

**Issue by gamiing** [khanhas/spicetify-cli#663]
I don't know why but the karaoke feature just does not work at all.

The synced lyrics work but they always use Netease instead of prioritizing Musixmatch, and Popup lyrics looks fine and works properly as is. 

![Screen Shot 2021-05-23 at 1 14 30 AM](https://user-images.githubusercontent.com/34428225/119253072-485b5180-bb64-11eb-9602-f285ad3de12c.png)
![Screen Shot 2021-05-23 at 1 14 13 AM](https://user-images.githubusercontent.com/34428225/119253075-4abdab80-bb64-11eb-8c33-681a6db380d4.png)

Any idea how to fix it?

**Comment by Chikorit** [comment]
I have the same problem, but for me doesn't mind because netease have more lyrics than musixmatch. 

What version of spotify do you have? I see in your screenshots the block button near favorite icon, how?

**Comment by ashzw** [comment]
The issue for me is that Netease censors explicit lyrics, so I prefer using Musixmatch. I've been having the same issue, I wish we could prioritize the order of the lyric providers like with the popup lyrics

**Comment by gamiing** [comment]
> I have the same problem, but for me doesn't mind because netease have more lyrics than musixmatch.
> 
> What version of spotify do you have? I see in your screenshots the block button near favorite icon, how?

It's the autoplay feature on Spotify if I have it correctly, if you dislike a song that plays next you can choose the block button and such

**Comment by gamiing** [comment]
> The issue for me is that Netease censors explicit lyrics, so I prefer using Musixmatch. I've been having the same issue, I wish we could prioritize the order of the lyric providers like with the popup lyrics

From khanhas, I have seen him provide a line of code that you put into your developer console but I see no difference unfortunately, and I've tried turning off Popup lyrics and seeing if it would work that way but it sucks that it doesn't work

**Comment by Thiagoedlp151** [comment]
> > The issue for me is that Netease censors explicit lyrics, so I prefer using Musixmatch. I've been having the same issue, I wish we could prioritize the order of the lyric providers like with the popup lyrics
> 
> From khanhas, I have seen him provide a line of code that you put into your developer console to change the lyrics providers' priority but I see no difference unfortunately, and I've tried turning off Popup lyrics and seeing if it would work that way but it sucks that it doesn't work

I try another method to change the lyrics providers priority, you have to go to spicetify-cli folder and then to Custom Apps and Lyrics plus once you there you have to edit the file index. I have it like this:

 providers: {
	musixmatch: {
            on: getConfig("lyrics-plus:provider:musixmatch:on"),
            desc: `Fully compatible with Spotify. Require a token that can be retrieved from Musixmatch offical app. Follow instructions on <a href="https://github.com/khanhas/spicetify-cli/wiki/Musixmatch-Token">spicetify Wiki</a>.`,
            token: localStorage.getItem("popup-lyrics:services:musixmatch:token") || "21051986b9886beabe1ce01c3ce94c96319411f8f2c122676365e3",
            modes: [SYNCED, UNSYNCED],
        },
        netease: {
            on: getConfig("lyrics-plus:provider:netease:on"),
            desc: `Crowd sourced lyrics provider running by Chinese developers and users.`,
            modes: [KARAOKE, SYNCED, UNSYNCED],
        },
        spotify: {
            on: getConfig("lyrics-plus:provider:spotify:on"),
            desc: `Lyrics are offically provided by Spotify. Only available for some regions/countries' users (e.g Japan, Vietnam, Thailand).`,
            modes: [SYNCED, UNSYNCED],
        },
        genius: {
            on: getConfig("lyrics-plus:provider:genius:on"),
            desc: `Brilliant`,
            modes: [GENIUS],
        }

**Comment by gamiing** [comment]
> > > The issue for me is that Netease censors explicit lyrics, so I prefer using Musixmatch. I've been having the same issue, I wish we could prioritize the order of the lyric providers like with the popup lyrics
> > 
> > 
> > From khanhas, I have seen him provide a line of code that you put into your developer console to change the lyrics providers' priority but I see no difference unfortunately, and I've tried turning off Popup lyrics and seeing if it would work that way but it sucks that it doesn't work
> 
> I try another method to change the lyrics providers priority, you have to go to spicetify-cli folder and then to Custom Apps and Lyrics plus once you there you have to edit the file index, and change the order of the providers. I have it like this:
> 
> providers: {
> musixmatch: {
> on: getConfig("lyrics-plus:provider:musixmatch:on"),
> desc: `Fully compatible with Spotify. Require a token that can be retrieved from Musixmatch offical app. Follow instructions on <a href="https://github.com/khanhas/spicetify-cli/wiki/Musixmatch-Token">spicetify Wiki</a>.`,
> token: localStorage.getItem("popup-lyrics:services:musixmatch:token") || "21051986b9886beabe1ce01c3ce94c96319411f8f2c122676365e3",
> modes: [SYNCED, UNSYNCED],
> },
> netease: {
> on: getConfig("lyrics-plus:provider:netease:on"),
> desc: `Crowd sourced lyrics provider running by Chinese developers and users.`,
> modes: [KARAOKE, SYNCED, UNSYNCED],
> },
> spotify: {
> on: getConfig("lyrics-plus:provider:spotify:on"),
> desc: `Lyrics are offically provided by Spotify. Only available for some regions/countries' users (e.g Japan, Vietnam, Thailand).`,
> modes: [SYNCED, UNSYNCED],
> },
> genius: {
> on: getConfig("lyrics-plus:provider:genius:on"),
> desc: `Brilliant`,
> modes: [GENIUS],
> }
> },
> providersOrder: ["musixmatch","netease","spotify","genius"],
> modes: ["karaoke", "synced", "unsynced", "genius"],
> locked: localStorage.getItem("lyrics-plus:lock-mode") || "-1",

For me, I've just completely removed the Netease part. It works fine, but I recommend getting a backup file just in case something screws up.

**Comment by gamiing** [comment]
While I have the first half of my problem solved, I still want to get the Karaoke feature working.

**Comment by khanhas** [comment]
Musixmatch does not provide karaoke-able lyrics, at least not with with API of Desktop App. I noticed they have something called "richsync" but it requires API key and probably is behind a paywall so I never try.

**Comment by Chikorit** [comment]
I have tried musixmatch priority to compare but it does not work for me. I have put the token in Popup Lyrics and in the index. Should we put it somewhere else?

Popup Lyrics works fine for me with the token.

**Comment by ashzw** [comment]
Yep, same here. Tried all sorts of combinations of ordering the different providers and changing `CONFIG.providersOrder` in index.js but as soon as I touch `netease` or place it below `musixmatch` everything stops working, even when the popup lyrics still do.

**Comment by ashzw** [comment]
> From khanhas, I have seen him provide a line of code that you put into your developer console to change the lyrics providers' priority but I see no difference unfortunately, and I've tried turning off Popup lyrics and seeing if it would work that way but it sucks that it doesn't work

I saw the command they provided in the other issue but it also doesn't work for me :( Tried reloading, reapplying Spicetify, not sure what else I can try

**Comment by gamiing** [comment]
> Musixmatch does not provide karaoke-able lyrics, at least not with with API of Desktop App. I noticed they have something called "richsync" but it requires API key and probably is behind a paywall so I never try.

If it's possible, could you be able to experiment with it? I currently have Musixmatch Premium so I can probably (at least) try to make it work if possible

**Comment by ctctk9** [comment]
My Musixmatch lyrics doesn't display lyrics also, I added the user token already.
