### ISSUE TITLE
umm, Arch Linux not working?

### ISSUE THREAD

**Issue by OkaVatti** [khanhas/spicetify-cli#668]
I'm actually stumped rn, I swear I have the file locations right, I'm using the AUR version (grabbing directly from spotify) because it actually had the prefs file (unlike flatpak for some reason). Now I'm getting the the error
`_fatal unlinkat /opt/spotify/Apps/about.spa: permission denied_`

when giving it root privs i get the following
`_error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini_`
but i checked that file already and its an exact copy of what I already did, the file location is correct and it's the exact same as my previous one, it's just not detecting it for some reason.
Here's both of my config files for more info.
**--------------------------------------------------**
**--------------------------------------------------**
**config-xpui.ini**
`[Preprocesses]
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1

[AdditionalOptions]
extensions  =
custom_apps =

[Patch]

[Setting]
color_scheme            =
inject_css              = 1
overwrite_assets        = 0
check_spicetify_upgrade = 0
spotify_path            = /opt/spotify/
prefs_path              = /home/black/.config/spotify/prefs
current_theme           = SpicetifyDefault
replace_colors          = 1
spotify_launch_flags    =

; DO NOT CHANGE!
[Backup]
version = 1.1.56.595.g2d2da0de`
**--------------------------------------------------**
**--------------------------------------------------**

**config.ini**
`
[Setting]
inject_css              = 1
overwrite_assets        = 0
prefs_path              = /home/black/.config/spotify/prefs
color_scheme            =
replace_colors          = 1
spotify_launch_flags    =
check_spicetify_upgrade = 0
spotify_path            = /opt/spotify
current_theme           = SpicetifyDefault

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
lyric_force_no_sync          = 0
song_page                    = 0
custom_apps                  =
experimental_features        = 0
lyric_always_show            = 0
radio                        = 0
visualization_high_framerate = 0
extensions                   =
fastUser_switching           = 0
home                         = 0

; DO NOT CHANGE!
[Backup]
version =
`
**--------------------------------------------------**
**--------------------------------------------------**

I'm kinda just worried that there's just no Arch support for this plugin. Not just that but there's barely any documentation available for these types of problems.

**Comment by wiktor-waj** [comment]
Have you updated access mode for spotify after insalation? If I am not mistaken I think yay or any other aur helper can't set them so you have to do it manually. If you haven't done that already try:
```
sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R
```

**Comment by wiktor-waj** [comment]
Have you updated access mode for spotify after instalation? I think yay can't do it for you, if not try : 
```
sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R
```

**Comment by OkaVatti** [comment]
thank you so much, it's working now.

**Comment by OkaVatti** [comment]
thank you so much, it's working now.
