### ISSUE TITLE
Could not find Config ini file, Linux Ubuntu Budgie

### ISSUE THREAD

**Issue by riskirills66** [khanhas/spicetify-cli#669]
I used Spicetify on Windows 7/10, to make the config INI with the folder, I ran the spicetify.exe in the Spicetify-Cli folder in the user folder. But I couldn't run the Spicetify Executable in here to generate the Spicetify folder and config INI for Linux, and I couldn't locate them either if they're already generated.
I want to make the preferred Spotify location folder, but I couldn't since I can't locate them.

**Comment by khanhas** [comment]
Run `spicetify -c`
