### ISSUE TITLE
When Spotify updates and I backup and apply, the theme is messed up

### ISSUE THREAD

**Issue by cubeslice** [khanhas/spicetify-cli#67]
Title. Whenever Spotify updates and I reapply the theme, this happens:
![image](https://user-images.githubusercontent.com/35668016/64653643-f0fb6900-d3f4-11e9-95d1-701f91d3b0a6.png)
I have no idea what is happening. The only way to reapply the theme properly is to run the Spotify installer again and then apply the theme.

**Comment by khanhas** [comment]
Fixed in v0.9.4
