### ISSUE TITLE
hey why am i not able to apply spicetify default theme.....

### ISSUE THREAD

**Issue by Vismay23** [khanhas/spicetify-cli#670]
spicetify default theme worked perfectly fine before the update i received yesterday......all the plugins are back but the theme doesnt show up......
![image](https://user-images.githubusercontent.com/84200709/119337111-135a1680-bcac-11eb-9ad3-21f8c7e37452.png)
![image](https://user-images.githubusercontent.com/84200709/119337179-253bb980-bcac-11eb-96e8-0dd2d86f5638.png)

**Comment by khanhas** [comment]
Try running `spicetify restore backup apply`

**Comment by khanhas** [comment]
Also upgrade spicetify to v2.2.3 first

**Comment by Vismay23** [comment]
> Also upgrade spicetify to v2.2.3 first

i did....thats when it started to give this problem.....

**Comment by TradeMark17** [comment]
i'm having the exact same issue - i completely reinstalled Spotify, spicetify, and Dribbblish and the base spicetify light theme showed up fine. then as soon as i tried using Dribbblish it's straight back to default Spotify

**Comment by timescam** [comment]
> i'm having the exact same issue - i completely reinstalled Spotify, spicetify, and Dribbblish and the base spicetify light theme showed up fine. then as soon as i tried using Dribbblish it's straight back to default Spotify

Dribblish theme does not support v2 at the moment

**Comment by TradeMark17** [comment]
> > i'm having the exact same issue - i completely reinstalled Spotify, spicetify, and Dribbblish and the base spicetify light theme showed up fine. then as soon as i tried using Dribbblish it's straight back to default Spotify
> 
> Dribblish theme does not support v2 at the moment

Should I revert to an old version of spicetify, or just wait for them to update dribbblish?
