### ISSUE TITLE
Lyrics Page not extending all the way to the bottom.

### ISSUE THREAD

**Issue by snjyr123** [khanhas/spicetify-cli#671]
Is there any way I could change the CSS to make the lyrics extend all the way to the bottom, because there is a huge lip and I would like to make it extend to the bottom. The theme I am using currently is Material-Ocean 
![image](https://user-images.githubusercontent.com/83570596/119382281-6ec5dd80-bc87-11eb-83c4-beaf89724333.png)

**Comment by khanhas** [comment]
Sorry, that's where ads is placed and I can't help you remove ads.
