### ISSUE TITLE
Spotify Showing Blank Screen

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#673]
![image](https://user-images.githubusercontent.com/81705406/119504167-b7d66a00-bd39-11eb-88bf-ee715c6470e4.png)
After updating to latest Spicetify and reinstalling Spotify, I added the lyrics-plus and Reddit apps, but after I opened Spotify, a blank screen appeared. I closed it, killed the task in task manager and reopened it, but it does not work

**Comment by Copimox** [comment]
Already fixed it nvm

**Comment by kelukelol** [comment]
> Already fixed it nvm

how did you fix it?
having the same issue rn

**Comment by Copimox** [comment]
> > Already fixed it nvm
> 
> how did you fix it?
> having the same issue rn

I just closed Spotify from task manager, used command **spicetify restore** then used command **spicetify backup apply** again
