### ISSUE TITLE
Lyrics-plus not displaying lyrics but popupLyrics worked fine with musixmatch

### ISSUE THREAD

**Issue by apple171017** [khanhas/spicetify-cli#674]
So you see the popupLyrics worked better than lyrics-plus for some reason
it just displays a loading screen for most of the songs

![image](https://user-images.githubusercontent.com/64765950/119505031-1e41a380-bd9f-11eb-894b-d335c2a39102.png)

I modified the `index.js` a bit to change the priority from 
`netease` > `musixmatch` > `spotify` > `genius`
to
`musixmatch` > `spotify` > `netease` > `genius`

since some of the lyrics from Netease are wrong and the timings for it is a little delayed for some reason

Is it because I changed the order of the providers? 
If yes, is there any way else to not corrupt it and change the priority? 

```js
// Modes enum
const KARAOKE = 0, SYNCED = 1, UNSYNCED = 2, GENIUS = 3;

const CONFIG = {
    visual: {
        colorful: getConfig("lyrics-plus:colorful"),
    },
    providers: {
		musixmatch: {
            on: getConfig("lyrics-plus:provider:musixmatch:on"),
            desc: `Fully compatible with Spotify. Require a token that can be retrieved from Musixmatch offical app. Follow instructions on <a href="https://github.com/khanhas/spicetify-cli/wiki/Musixmatch-Token">spicetify Wiki</a>.`,
            token: localStorage.getItem("popup-lyrics:services:musixmatch:token") || "usertoken",
            modes: [SYNCED, UNSYNCED],
        },
		spotify: {
            on: getConfig("lyrics-plus:provider:spotify:on"),
            desc: `Lyrics are offically provided by Spotify. Only available for some regions/countries' users (e.g Japan, Vietnam, Thailand).`,
            modes: [SYNCED, UNSYNCED],
        },
        netease: {
            on: getConfig("lyrics-plus:provider:netease:on"),
            desc: `Crowd sourced lyrics provider running by Chinese developers and users.`,
            modes: [KARAOKE, SYNCED, UNSYNCED],
        },
        genius: {
            on: getConfig("lyrics-plus:provider:genius:on"),
            desc: `Song Lyrics & Knowledge By Genius`,
            modes: [GENIUS],
        }
    },
    providersOrder: [],
    modes: ["karaoke", "synced", "unsynced", "genius"],
    locked: localStorage.getItem("lyrics-plus:lock-mode") || "-1",
};
```
Above is the code I modified 

any help will be appreciated.

**Comment by timescam** [comment]
Have u setup [Musixmatch Token](https://github.com/khanhas/spicetify-cli/wiki/Musixmatch-Token)?
or you can change `usertoken` to your token string
```
token: localStorage.getItem("popup-lyrics:services:musixmatch:token") || "usertoken",
```

**Comment by apple171017** [comment]
> Have u setup Musixmatch Token?

Yep I did thats why I replaced it

**Comment by apple171017** [comment]
Still not working tho

**Comment by Meikiv** [comment]
![image](https://user-images.githubusercontent.com/84654332/169228012-08fb1792-2fdc-460e-abbd-cade385e819f.png)

to

![image](https://user-images.githubusercontent.com/84654332/169228071-6b054f0a-cb8d-4e00-92ba-78de2bdd9043.png)
