### ISSUE TITLE
Can't update spicetify

### ISSUE THREAD

**Issue by Blu3Razr1** [khanhas/spicetify-cli#676]
fatal open C:\Users\[MYNAME]\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

been using spicetify for a while, normally I just type "spicetify backup apply" into PowerShell and everything is fine, but with this most recent update I am getting this error. Any solutions?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/issues?q=is%3Aissue+is%3Aclosed
https://github.com/khanhas/spicetify-cli/releases
