### ISSUE TITLE
can you solve this reddit glitch......

### ISSUE THREAD

**Issue by Vismay23** [khanhas/spicetify-cli#677]
the text just gets masked by the upgrade and account options . 

![image](https://user-images.githubusercontent.com/84200709/119607890-bdec4980-be12-11eb-89a9-77db13d3d15b.png)

**Comment by khanhas** [comment]
Try resize the window

**Comment by Vismay23** [comment]
> Try resize the window

Didn't work by resizing.....when I turned on what your friends are playing an arrow toggle button appeared bug as soon as I turned it off the problem reappeared.....any fix?

**Comment by khanhas** [comment]
Maybe the upgrade button is the problem. It was never taken into account when recalculating elements size.

**Comment by Vismay23** [comment]
> Maybe the upgrade button is the problem. It was never taken into account when recalculating elements size.

ok np....

**Comment by khanhas** [comment]
I made a new account to test this, it does not occur to me in any Spotify version.
