### ISSUE TITLE
how to get the karaoke lyrics working......

### ISSUE THREAD

**Issue by Vismay23** [khanhas/spicetify-cli#678]
it always show this face...
![image](https://user-images.githubusercontent.com/84200709/119609563-6dc2b680-be15-11eb-8435-8aedc0ec59f6.png)

**Comment by khanhas** [comment]
Not all tracks has karaoke lyrics
Try popular ones from 90s, 00s
https://open.spotify.com/playlist/08ZBip1gxb97iNoHjFEBYh

**Comment by Vismay23** [comment]
> Not all tracks has karaoke lyrics
> Try popular ones from 90s, 00s
> https://open.spotify.com/playlist/08ZBip1gxb97iNoHjFEBYh

Thanks.....btw i saw your face...
