### ISSUE TITLE
pls answer and help thx

### ISSUE THREAD

**Issue by ThatLink** [khanhas/spicetify-cli#680]
so I tried to install spicetify today and it got a little hard but I did it and in powershell it said reinstall spotify  so I did..... after installing again it told me to sign in so I did too but I noticed that in the log in background it had my theme on which was "Blade Runner" then when i logged in it  gave me this
![image](https://user-images.githubusercontent.com/84858302/119678876-33224380-be40-11eb-8b24-73506a2abcc2.png)  i reloaded the page couple of times and it didn't work 
pls help

**Comment by apple171017** [comment]
I had this issue on making my own discord theme for spotify before, it might be issue on your `color.ini` file of your current theme. Try using `SpicetifyDefault` For now

**Comment by apple171017** [comment]
But still, I don't know the reason sorry.

**Comment by khanhas** [comment]
Reinstall Spotify, run `spicetify backup apply`

**Comment by ThatLink** [comment]
![image](https://user-images.githubusercontent.com/84858302/121238806-c889f280-c898-11eb-8932-3fea68bf0606.png)
this is what it displayed it didn't help i just want to use my spotify again

**Comment by lockieluke** [comment]
You have to run `spicetify.exe` in the directory of the repo(the thing yo downloaded from the release page)

**Comment by afonsojramos** [comment]
Closed for inactivity.
