### ISSUE TITLE
[macOS] Spicetify installs properly but breaks Spotify.app (see screenshots)

### ISSUE THREAD

**Issue by jonathanlaniado** [khanhas/spicetify-cli#681]
I am able to confirm Spicetify installs properly on the latest version:

![119712075-38769280-be2e-11eb-9a6f-38173d870fcf](https://user-images.githubusercontent.com/8929491/119712604-c05c9c80-be2e-11eb-8dac-38ab1ec06d46.png)

But then when I try to open Spotify.app, it redirects me here (notice the URL parameters):
```https://www.spotify.com/us/download/mac/?step=launch-updated-client&error-domain=NSCocoaErrorDomain&error-code=259&description=The+application+%E2%80%9CSpotify.app%E2%80%9D+could+not+be+launched+because+it+is+corrupt.&failure-reason=The+file+isn%E2%80%99t+in+the+correct+format.&recovery-suggestion=The+file+might+be+corrupted%2C+truncated%2C+or+in+an+unexpected+format.&internal-error-description=Error+Domain%3DNSCocoaErrorDomain+Code%3D259+%22The+application+%E2%80%9CSpotify.app%E2%80%9D+could+not+be+launched+because+it+is+corrupt.%22+UserInfo%3D%7BNSURL%3Dfile%3A%2F%2F%2FApplications%2FSpotify.app%2F%2C+NSLocalizedDescription%3DThe+application+%E2%80%9CSpotify.app%E2%80%9D+could+not+be+launched+because+it+is+corrupt.%2C+NSUnderlyingError%3D0x7fcc6051cc00+%7BError+Domain%3DNSOSStatusErrorDomain+Code%3D-10827+%22kLSNoExecutableErr%3A+The+executable+is+missing%22+UserInfo%3D%7BNSURL%3Dfile%3A%2F%2F%2FApplications%2FSpotify.app%2F%7D%7D%7D&old-app-version=1.1.60.668.gff09d345&new-app-version=1.1.59.714.g7e040462```

And then shows me this error message:

<img width="260" alt="CleanShot 2021-05-26 at 14 24 38@2x" src="https://user-images.githubusercontent.com/8929491/119712183-57752480-be2e-11eb-9e0a-b32a6d6a364d.png">

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply`.

**Comment by afonsojramos** [comment]
@jonathanlaniado do you have any updates on this?
