### ISSUE TITLE
A little improvement for fullAppDisplay extension?

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#682]
I really don't know what they think in Spotify. Do you want sometimes take a look at the cover album cover? This usually assumes full-screen mode, but...

![1](https://user-images.githubusercontent.com/78786088/119716614-f4a37d80-be6d-11eb-89a7-ca00680f200f.PNG)

OK, we have our own fullAppDisplay extension in Spicetify, but even there cover is not big enough.

![2](https://user-images.githubusercontent.com/78786088/119716736-1dc40e00-be6e-11eb-80ca-c72e4a137c0c.PNG)

Maybe try looking in the lower-left corner?

![3](https://user-images.githubusercontent.com/78786088/119716805-2d435700-be6e-11eb-8d7e-175097ff291b.PNG)

Terribly. But what if we try to stretch this sidebar as much as possible?

![4](https://user-images.githubusercontent.com/78786088/119716870-48ae6200-be6e-11eb-8dd8-9be69f78a489.PNG)

That's better. In general. if possible, please make the cover in fullAppDisplay at least the same size as when the left side bar is stretched 🙏

**Comment by khanhas** [comment]
Fix it yourself in the code, it was made to be customisable on different certain degree, I can't just support every single need.
