### ISSUE TITLE
Themes not work on Windows 7

### ISSUE THREAD

**Issue by Mehmetali345Dev** [khanhas/spicetify-cli#686]
I configured themes and applied but doesn't works.
All things works like Extensions and Custom Apps but Themes doesn't works on Windows 7 but when i change to Windows 10 it works.
This bug needs to be solve.

**Comment by Mehmetali345Dev** [comment]
> Are you using spicetify v2.2.3 and latest Spotify?
My spicetify version v2.3.3 and Spotify version 1.1.60.668.gff09d345-a.

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply` and see if problem persists

**Comment by Mehmetali345Dev** [comment]
> Reinstall Spotify and run `spicetify backup apply` and see if problem persists

I tried it but not works.

**Comment by kamimema** [comment]
same here, extensions and apps work, but it doesn't apply theme

**Comment by Inzomania** [comment]
Windows 10, latest Spicetify and Spotify (1.1.60.672.g6ad9c215-a). Spicetify themes does not work.

**Comment by khanhas** [comment]
Windows 10: Please reinstall Spotify and run `spicetify backup apply`. I'm 100% it's still wokring.
Windows 7: I have no idea, sorry. I can't support that far back. But I'm certain that OS does not matter, only Spicetify version and Spotify version matter. Make sure you have everything on the latest and run `spicetify backup apply`.

**Comment by erest0r** [comment]
third time trying still doesnt work on windows 10

**Comment by Mehmetali345Dev** [comment]
![It like this](https://user-images.githubusercontent.com/65217390/120073182-fa80a500-c09f-11eb-8a96-1afc8a36d856.png)
I reinstalled Spotify and run `spicetify backup apply` but nothing changed.

**Comment by khanhas** [comment]
Oh god, I thought you said spicetify does not working
Where did you get your theme? Did you read previous release note said that themes for legacy Spotify won't be compatible with new Spotify?

**Comment by khanhas** [comment]
Also you turned off all `replace_color`, `inject_css`. Theme won't work without those.

**Comment by Mehmetali345Dev** [comment]
> Also you turned off all `replace_color`, `inject_css`. Theme won't work without those.

Also you need to fix these because this is the default value.

**Comment by khanhas** [comment]
No it isn't. Try delete the config file, run spicetify again and see what are their default values
