### ISSUE TITLE
Theming seems to be broken

### ISSUE THREAD

**Issue by abiramen** [khanhas/spicetify-cli#687]
Trying to use the SpicetifyDefault theme on the latest version of Spotify (1.1.59.714.g7e040462-a, Windows 10 19041) with the latest version of Spicetify and theming seems to no longer work, even if I change the colour scheme.

![image](https://user-images.githubusercontent.com/7523422/119809447-7a83ff00-bf28-11eb-81df-19db0f01326d.png)

I attempted a fresh install of both Spotify, and reinstalled Spicetify (v2.2.3).

**Comment by khanhas** [comment]
Did you run `spicetify backup apply` after reinstalled Spotify or you ran something else?

**Comment by abiramen** [comment]
Whoops, looks like I used `spicetify apply`.
