### ISSUE TITLE
Hope the lyrics with the function of translation

### ISSUE THREAD

**Issue by RebirthEgo** [khanhas/spicetify-cli#689]
Hope the lyrics with the function of translation

<img width="976" alt="Snipaste_2021-05-28_00-30-07" src="https://user-images.githubusercontent.com/54738173/119863231-ef1c6500-bf4b-11eb-9dfb-769fbfd4b4f9.png">

**Comment by khanhas** [comment]
Not gonna happen. I'm not lyric provider and I can make lyrics translations out of thin air
