### ISSUE TITLE
Since Spotify Update SpicetifyDefault broken

### ISSUE THREAD

**Issue by Pukimaa** [khanhas/spicetify-cli#690]
Since the new Spotify update a few things are not themed that well. Here some screenshots:

![graphic](https://user-images.githubusercontent.com/58347116/119865542-0e9b9980-bf1c-11eb-839b-4f589b8d0576.png)
(first button)

![Facebook Button](https://user-images.githubusercontent.com/58347116/119865608-23782d00-bf1c-11eb-8a29-d7dc368d6d3d.png)
Facebook Button

And in general Button colors doesnt look too good (green variant)

**Comment by corfeur12** [comment]
Please check the [latest release notes](https://github.com/khanhas/spicetify-cli/releases/tag/v2.2.3). You probably need to reinstall Spotify and run `spicetify backup apply`.
