### ISSUE TITLE
Black screen?

### ISSUE THREAD

**Issue by luximus-hunter** [khanhas/spicetify-cli#693]
I'm trying to install Spicetify, but after applying i get a black screen which is unresponsive.

![image](https://user-images.githubusercontent.com/49814847/119974184-ad73d480-bfb4-11eb-9fc4-bca248477140.png)

Spicetify version: v2.3.3
Spotify version: 1.1.60.672.g6ad9c215-a
OS: Windows 10 Pro 21H1 19043.985

**Comment by khanhas** [comment]
reinstall Spotify, run `spicetify backup apply

**Comment by luximus-hunter** [comment]
♥
