### ISSUE TITLE
Sudo required

### ISSUE THREAD

**Issue by lapega** [khanhas/spicetify-cli#694]
I'm using ubuntu 20.04, spotify version 1.55 and spietify 2.23

When trying to use some command:
`./spicetify clear`
I get
`open /usr/share/spotify/Apps: permission denied`

But when
`sudo ./spicetify clear`
there no error but the spotify client get a blank page:
![imagen](https://user-images.githubusercontent.com/572502/119987845-d9cf2700-bf9b-11eb-985e-c5d8af56303d.png)

**Comment by khanhas** [comment]
spicetify doesn't require sudo.
Read wiki installation page: https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-and-macos

**Comment by khanhas** [comment]
Also spicetify v2 supports v1.1.56 or later. I'm not sure if anything will break on v1.1.55

**Comment by lapega** [comment]
Indeed. Tried version 1.2.1 and works like a charm!

Thanks!!!
