### ISSUE TITLE
[Bug may be] custom CSS not injected to the login screen

### ISSUE THREAD

**Issue by okarin001** [khanhas/spicetify-cli#697]
It seems spicetify is not injecting custom CSS unless I login to the app. 

![image](https://user-images.githubusercontent.com/63984668/120079067-e9e82300-c0cf-11eb-908f-7b794c633995.png)

It might be reading the variables but not applying it.
![image](https://user-images.githubusercontent.com/63984668/120079157-464b4280-c0d0-11eb-8aad-ee697f8390c9.png)

tried changing it to certain colors but it seems custom css is not working.
![image](https://user-images.githubusercontent.com/63984668/120079177-5fec8a00-c0d0-11eb-8a0d-cbc21078f722.png)

**Comment by khanhas** [comment]
From v2.2.5, Login app asset won't be touched by spicetify. Don't spend effort on it.

**Comment by okarin001** [comment]
> From v2.2.5, Login app asset won't be touched by spicetify. Don't spend effort on it.

ohh okay, thanks.  (＠＾◡＾)
