### ISSUE TITLE
Transferring user.css

### ISSUE THREAD

**Issue by nils-kt** [khanhas/spicetify-cli#698]
Hello, I have reinstalled Spotify and since then I get this error.

```
C:\Windows\system32>spicetify backup apply
spicetify v2.2.4
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Transferring user.css:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x90 pc=0xdf0b71]

goroutine 1 [running]:
github.com/go-ini/ini.(*File).Sections(0x0, 0x0, 0x0, 0x0)
        C:/Users/xuank/go/pkg/mod/github.com/go-ini/ini@v1.62.0/file.go:194 +0x51
github.com/khanhas/spicetify-cli/src/cmd.updateCSS()
        D:/Code/spicetify-cli/src/cmd/apply.go:148 +0x196
github.com/khanhas/spicetify-cli/src/cmd.Apply()
        D:/Code/spicetify-cli/src/cmd/apply.go:54 +0x150
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x4a5
```

Spotify version: 1.1.60.672.g6ad9c215-a

**Comment by fosam** [comment]
Can you try to delete the old config file and generate a new one?

**Comment by nils-kt** [comment]
I have tested a bit. The error occurs as soon as I set replace_colors to 0.

**Comment by fosam** [comment]
I just tested now, even with `replace_colors=1` it still happens

**Comment by nils-kt** [comment]
I get the error when I change one of the following entries:

- current_theme
- replace_colors

**Comment by fosam** [comment]
I got this issue as soon as i updated to v2.2.4, can you switch back to v2.2.2 and try with that? i had no problem with v2.2.2, must be something with the new version.

**Comment by nils-kt** [comment]
v2.2.3 also works without problems. Let's wait for @khanhas :)

**Comment by khanhas** [comment]
Sorry my bad. I forgot to check ini file  availability

**Comment by fosam** [comment]
Should we wait for a release?

**Comment by fosam** [comment]
.
