### ISSUE TITLE
Community Themes

### ISSUE THREAD

**Issue by gregjw** [khanhas/spicetify-cli#7]
Where do people list themes they've built?

**Comment by khanhas** [comment]
I did make a Spectrum chat where people can share themes and extensions.
https://spectrum.chat/spicetify
But there is not so much of them and they were made for "Spicetify for Rainmeter" which is not really compatible with spicetify-cli. Just need some manual work.
Hope that helps and thing will be better in future.

**Comment by gregjw** [comment]
Thanks for the prompt reply, that does help, I'll keep an eye out for spicetify-cli's community themes.

**Comment by Zazerr** [comment]
Hi, quick question, I love your application but it is way too bright! I can't stand the bright colours, how do I change the colours to something similar to [this](https://camo.githubusercontent.com/c64e4d07d7c515f4c606c846dcc2ebb50f1525e1/68747470733a2f2f692e696d6775722e636f6d2f653443576552432e706e67) example you gave? That looks awesome! Would greatly appreciate the help. Just by the way, I'm on Mac, and tried to follow the instructions to change main_fg and stuff from [here](https://github.com/khanhas/spicetify-cli/blob/master/Themes/SpicetifyDefault/color.ini), but I couldn't get it to work. I love the look of Spicetify, again, but it's just too bright at the default! Thanks for the help :)

**Comment by khanhas** [comment]
1. Default themes folder can be found in `/usr/local/Cellar/spicetify-cli/x.x.x/bin/Themes` (with `x.x.x` are version numbers).
2. In that folder you can find "SpicetifyDefault" folder which is default theme. You can copy it to user Themes folder if you want or just edit directly on it.
3. In `SpicetifyDefault`, you can find `color.inc`.
4. Open that file and comment out white theme and uncomment dark theme
5. Save
6. Run `spicetify update restart`

**Comment by Zazerr** [comment]
Thank you so much! Looks awesome now, I really appreciate it! :D

**Comment by morpheusthewhite** [comment]
> 1. Default themes folder can be found in `/usr/local/Cellar/spicetify-cli/x.x.x/bin/Themes` (with `x.x.x` are version numbers).
> 2. In that folder you can find "SpicetifyDefault" folder which is default theme. You can copy it to user Themes folder if you want or just edit directly on it.
> 3. In `SpicetifyDefault`, you can find `color.inc`.
> 4. Open that file and comment out white theme and uncomment dark theme
> 5. Save
> 6. Run `spicetify update restart`

For me the path is `/usr/share/spicetify-cli/Themes`

**Comment by morpheusthewhite** [comment]
I started a community-driven repository to collect Spicetify themes, be free to contribute to it!

Here it is https://github.com/morpheusthewhite/spicetify-themes

**Comment by ahmetb** [comment]
It would be much better if this repository hosted a link to themes, extensions etc in the wiki. It's really hard to discover at the moment.

**Comment by rien333** [comment]
@khanhas The https://github.com/morpheusthewhite/spicetify-themes repo is coming along nicely, maybe link it somewhere easy to find in the spicetify  wiki/docs so that this issue can be closed? You could list it as a repo of community themes.
