### ISSUE TITLE
fatal: unlinkat /opt/spotify/Apps/collection.spa: permission denied

### ISSUE THREAD

**Issue by MEXdave1997** [khanhas/spicetify-cli#70]
I get this error after running `spicetify apply` (and this is after a successful backup of the default config). Any ideas?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#note-for-linux-users

**Comment by BramVer** [comment]
While that was an easy fix, it should be included (or at least referenced to) in the AUR section under install.  
There's no other signs that tell you to read the rest of the documentation.

**Comment by R-L-T-Y** [comment]
Might be worth putting it in FAQ.

**Comment by tarun-varier** [comment]
I did the steps mentioned in the 'note for linux users' section (installed from AUR) ...but now this error appears
`lstat /opt/spotify/Apps/hub: permission denied`

Being a total noob...I tried doing this too...
`sudo chmod a+wr /opt/spotify/Apps/hub`

Still didn't work...

So now...I need help from you guys (the experts)

Altho, I applied the theme in the root user and it works but can't play no songs

Thnx a lot

**Comment by diorcula** [comment]
I get this error, but the method referenced here to solve it does not apply as I installed it with the recommended pre-built library?

Any ideas?

**Comment by RenaudAlly** [comment]
> I get this error, but the method referenced here to solve it does not apply as I installed it with the recommended Shell (pre-built binary)?
> 
> Any ideas?

I used the same method and it worked for me. Have you ensured that your prefs_path has been set correctly? You can do `spicetify config prefs_path ~/.config/spotify/prefs` to do that

**Comment by AnmolHatua** [comment]
still getting the same error. 
after: 
spicetify config prefs_path ~/.config/spotify/prefs

~$ spicetify config prefs_path ~/.config/spotify/prefs
success Config changed: prefs_path = /home/anmol/.config/spotify/prefs
info Run "spicetify apply" to apply new config
~$ spicetify apply
spicetify v2.36.15
info Spicetify up-to-date
Copying raw assets:
fatal unlinkat /usr/share/spotify/Apps/login.spa: permission denied

**Comment by rotkiv1205** [comment]
> https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users

Worked for me by looking at the SNAP section (I installed spotify as a debian package)

**Comment by ShadowComes** [comment]
For anyone wondering.. it was a permission error.. If some one installed it from spotify website (adding the spotify library to apt-get list) then you will need to execute thease commands:
```
sudo chmod a+wr /usr/share/spotify
sudo chmod a+wr /usr/share/spotify/Apps -R
```

After that u can retry to apply it or make a backup.. :)

**Comment by yigitsalar** [comment]
> https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users

This page is down since then, this is the most recent reference: https://spicetify.app/docs/getting-started#linux-specific-setup
