### ISSUE TITLE
Spotify is blank

### ISSUE THREAD

**Issue by d4rks0n1c** [khanhas/spicetify-cli#702]
When using Spicetify, I have the issue that my Spotify window is blank after logging in, even though it's still working.
It looks like this with the Spicetify standard:
![grafik](https://user-images.githubusercontent.com/39404370/120110431-bb208a00-c16d-11eb-9eaa-a096df952ed6.png)
Sometimes it's dark gray.

With the original version/after restoring I also need to create the css-folder.
Does anyone have a solution for this?

I am on Windows 10

**Comment by khanhas** [comment]
Spotify version 
Spicetify version

**Comment by d4rks0n1c** [comment]
Spotify: v1.1.60.672.g6ad9c215-a
Spicetify: v1.2.1

**Comment by Dinxton** [comment]
Use Spicetify-cli v2.0.0 or newer if you're using Spotify 1.1.58 or newer - v1.2.1 is only for versions before 1.1.56 using the old UI.

**Comment by d4rks0n1c** [comment]
It works now, thank you!
Is the UI also affected by changing the themes? I tried out some of them and there are only colors changing

**Comment by khanhas** [comment]
Old themes are not compatible
