### ISSUE TITLE
I can't get Spicetify to work 

### ISSUE THREAD

**Issue by AbdullahKhan25** [khanhas/spicetify-cli#709]
_I'm sorry but I'm very new to this, so forgive me for my lack of knowledge._

I followed all instructions as written in some online tutorials, but I just couldn't get any community themes to work. I tried it on 2.2.4.
I installed using the Powershell method, managed to get the default white-pink theme (Spicetify-Default?) but I couldn't get even one of the many community themes to work.
Do all the themes work? Can anyone help me with a tutorial on how to use Dribbblish? 
Please, any help would be appreciated. 

_I'm using the latest Spotify build with BlockTheSpot and a change to xpui.spa in Appdata>Spotify>Apps to remove the ad banner (Though I tried installing Spicetify without these and it didn't work either)_

**Comment by EmstallZ** [comment]
The spicetify community themes currently don't work with version 2 of spicetify. If you would like to use community themes, use the legacy version of spicetify instead. The legacy version can be found here: https://github.com/khanhas/spicetify-cli/tree/legacy

**Comment by AbdullahKhan25** [comment]
Thanks! Does the legacy one work with Spotify's new UI?

**Comment by josephyooo** [comment]
Guy ain't answer your question before closing, but no. You gotta download the latest version before they added the new UI. (1.1.56 according to #702 in Dinxton's comment). I downloaded it from [here](https://spotify.en.uptodown.com/windows/versions). Basically, you need to have a legacy version of both spicetify and Spotify to work with community themes for the time being. Hope this helps, wanted to pull my hair out tryna figuring out how to fix it.

**Comment by AbdullahKhan25** [comment]
Yup I was disappointed that he closed it before I got the answer. I stayed up last night figuring everything out and got everything to work. Literally me wanting to pull my hair out too lol. I did all the same except I used Spotify 1.1.55. Anyways, thanks for responding.
