### ISSUE TITLE
Unable to use/change themes, only able to use and change to spicetifydefault

### ISSUE THREAD

**Issue by sadddrr** [khanhas/spicetify-cli#710]
i just installed the new update but i cant seem to change the theme. if i do change the theme it will go back to the normal spotify, when i change it back to spicetiftdefault it works. so only spicetifydefault works for me, someone help me :(

**Comment by khanhas** [comment]
Legacy themes are not compatible with new Spotify.

**Comment by sadddrr** [comment]
okay thank you!
