### ISSUE TITLE
Lyrics-Plus custom app breaks the whole App

### ISSUE THREAD

**Issue by Adrnzz** [khanhas/spicetify-cli#713]
Upon enabling the Lyrics-Plus custom app, the Spotify client just displays an error and there's no way to access anything
![image](https://user-images.githubusercontent.com/46679188/120225377-6bad8d00-c245-11eb-9cb9-ef6e173b85a4.png)

**Comment by Adrnzz** [comment]
Update: Installing New-releases custom app results in the same error

**Comment by AustrAlienGH** [comment]
Are you on the latest build of spicetify? Not sure if custom apps still support the old UI or not but that might be the problem?

**Comment by Adrnzz** [comment]
I'm on the latest build, yes! Also new UI, and the latest build just added lyrics plus back, that's why I wanted to check it!

**Comment by ensyvz** [comment]
Same here. Wrote this so devs can know this is not a one-time issue.

**Comment by khanhas** [comment]
Did anyone still has this problem with latest spicetify?

**Comment by st-den** [comment]
> 
> 
> Did anyone still has this problem with latest spicetify?


The update fixed it for me

**Comment by Adrnzz** [comment]
The update fixed it for me too, closing the issue!

Thank you for the fix!
