### ISSUE TITLE
how do I uninstall this? 

### ISSUE THREAD

**Issue by hunkypucky111** [khanhas/spicetify-cli#715]
don't need it anymore and I don't rly want it installed on my computer..

**Comment by kotobuki09** [comment]
Try Google with the keyword "uninstall spicetify" and go to the top link in this issues category. There you go, the solution there

**Comment by Pixouls** [comment]
in your /user folder, there should be a spicetify folder and a .spicetify folder, those contain all the files associated with the app and should be all you need to remove it.
