### ISSUE TITLE
After using brew upgrade on spicetify, extensions and custom apps no longer appear at all, despite being enabled in the config.

### ISSUE THREAD

**Issue by SaltNuggets** [khanhas/spicetify-cli#719]
Machine is mac, there are two config files generated config-xpui and the normal one. I used a mitm proxy to get around ads, however even after disabling nothing changed.

**Comment by GitGangGuy** [comment]
Do you have the old Spotify client (v1.1.56 and older) installed or the new one (v1.1.58 or later)? Depending on the Spotify version, you'll need to install a different spicetify version (Also see the [README](https://github.com/khanhas/spicetify-cli#legacy-spotify)) with different config files. There has been a major rewrite to Spotify and, by extension, spicetify. Check the [release notes](https://github.com/khanhas/spicetify-cli/releases) for every new spicetify version and also see the several already closed issues about this (#557, #564, #566, #578, #569, #572, #595, #597, #601, #602, #614, #615, #617, #619, #622, #629, #633, #635, #644, #652, #662, #680, #670, #676, #685, #690, #702, #709, #710).

**Comment by SaltNuggets** [comment]
@GitGangGuy I don't believe that that's the issue here, since the theme works the same as it did previously, Extensions and apps don't however.

**Comment by GitGangGuy** [comment]
Oh ok, I guess I was too quick to judge :smile:

**Comment by SaltNuggets** [comment]
@GitGangGuy Just ran it, spotify no longer works as a whole now. i am on the newest spotify client version

**Comment by SaltNuggets** [comment]
I'm kind of exhausted from all of this, I'm thinking of just wiping all files relevant to spotify and spicetify and starting from scratch

**Comment by SaltNuggets** [comment]
@GitGangGuy I just did a full reinstall of spicetify and spotify, it doesn't work at all.

**Comment by SaltNuggets** [comment]
Well, it actually works slightly, except the theme which sucks but the extensions and apps do. Can't have it all I guess.

**Comment by GitGangGuy** [comment]
As I already said, your theme of choice not working probably has to do with the recent major spicetify update

**Comment by SaltNuggets** [comment]
Ah alright, any clue how I can fix it? What exactly changed?

**Comment by GitGangGuy** [comment]
https://github.com/khanhas/spicetify-cli/releases

**Comment by GitGangGuy** [comment]
Your theme will not work until it gets updated. If its from [spicetify-themes](https://github.com/morpheusthewhite/spicetify-themes/), the repo maintainers are working on it (in that case, also see morpheusthewhite/spicetify-themes#368 and [their v2 branch](https://github.com/morpheusthewhite/spicetify-themes/tree/v2))

**Comment by GitGangGuy** [comment]
But again, this has already been commented on in several previous issues

**Comment by SaltNuggets** [comment]
Ah yeah, i made my own theme so this is probably going to be quite a painful experience but oh well, thanks for all the help @GitGangGuy
