### ISSUE TITLE
Spotify devtools don't show up anymore (Linux 1.1.56.595/latest + v2.2.5/latest)

### ISSUE THREAD

**Issue by GitGangGuy** [khanhas/spicetify-cli#721]
Since the v2 update (yes, I'm running the newest Spotify for Linux and spicetify versions (1.1.56.595 with 2.2.5) xD) `spicetify enable-devtool apply` won't change that I can't open the devtools anymore. I tried right-clicking, `Control+Shift+I`, `Control+Shift+J`, `Control+Shift+C` and F12. I can live with it, but it is a bummer. Is this because Spotify for Linux still stuck on 1.1.56 (which apparently lags behind the Spotify for Windows/macOS versions)?

**Comment by Arthur1236** [comment]
Yes, Spicetify currently runs better on 1.59/1.60. I think there are some files or new elements missing that were introduced.

But you can enable it by using SpicetifyDefault-Theme right click on the album cover or artis name then click on the empty space next to it. Then the options like on the screenshot
![gwgegwgg-rgrgwggg01-12](https://user-images.githubusercontent.com/37155796/120400615-7a2b9f80-c33e-11eb-8a21-04313b150890.png)

**Comment by GitGangGuy** [comment]
@Arthur1236 I don't understand what you mean with 'the empty space next to it'. When I right-click the artist name, I get the regular Spotify context menu. If I click around the box, it closes.

**Comment by khanhas** [comment]
The empty space are the space that doesn't has anything on it. No link, no text, no image.

**Comment by GitGangGuy** [comment]
![Screenshot](https://user-images.githubusercontent.com/50679178/120483719-ac76e480-c3b2-11eb-986c-4ee557ba50db.png)
I'm feeling a little stupid right now, but I tried clicking everywhere with no success

**Comment by khanhas** [comment]
Click at empty space! Not the one that has text in!

**Comment by Arthur1236** [comment]
Oh sorry, first you have to right-click on the artist name or album cover and then **right-click** on the empty space (red area in the screenshot). This is how it shows up on my Arch Linux.

![Screenshot 2021-06-02 164705](https://user-images.githubusercontent.com/37155796/120502813-08e20000-c3c3-11eb-83e9-b490fec2b926.jpg)
