### ISSUE TITLE
pls help, i'm new to this

### ISSUE THREAD

**Issue by ubitbits** [khanhas/spicetify-cli#724]
Hello, I am new to this spicetify and I'm stupid and slow so I don't know what to do. 

I not really familiar with codings so I don't know what to click and type here. I followed online instructions for installing spicetify with powershell. After I type the spicetify backup apply enable-devtool, its says that \Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file.  

What should I do? I don't know where and what to set. 
I've been trying for hours but I don't get a thing on what I should do. 
![spicee](https://user-images.githubusercontent.com/85213965/120429833-ab40ba00-c3a8-11eb-9676-dedb52908b60.jpg)

**Comment by khanhas** [comment]
1. Uninstall Spotify from Windows Store and install Spotify with installer downloaded from its website
2.Run
```
spicetify config prefs_path " "
spicetify config spotify_path " "
spicetify backup apply
```

**Comment by ubitbits** [comment]
![Screenshot (1256)_LI](https://user-images.githubusercontent.com/85213965/120583608-22d22000-c461-11eb-88fb-aec884594733.jpg)

**Comment by khanhas** [comment]
Run `spicetify -c` to know where config file is. Delete  it and try `spicetify backup apply`

**Comment by ubitbits** [comment]
it finally worked! Thank you so muchh!!
