### ISSUE TITLE
Can not apply themes or or it has a problem with gnome40

### ISSUE THREAD

**Issue by eralocal** [khanhas/spicetify-cli#725]
I've installed spotify from aur not from flatpak but even though spotify is working fine i can not apply spicetify themes to it. I checked spotify pref files locaition and everything. They look correct and spicetify apply, backup and every command is working without any error but theme is still same default spotify theme. 

I am using gnome 40 with arch, i installed user themes to gnome but i don't think it has anything to do with this issue 'cause spoitfy was already using its own default theme. So it is not affected by gtk themes.

Is there any suggestions? (also i am new to github if my questions are in wrong format please excuse me)

**Comment by khanhas** [comment]
Legacy themes are not compatible with new Spotify.
Revert to old Spotify, use spicetify v1 if you wish
