### ISSUE TITLE
SpotifyNoControl.exe doesn't work

### ISSUE THREAD

**Issue by Piglen** [khanhas/spicetify-cli#728]
Is the SpotifyNoControl.exe supposed to work? I couldn't find the .exe in Dribbblish v2 so I used the .exe from Dribbblish v1. When I open it, nothing happens.

**Comment by khanhas** [comment]
https://github.com/morpheusthewhite/spicetify-themes/blob/master/DribbblishDynamic/SpotifyNoControl.exe
download this one.
