### ISSUE TITLE
pls help "fatal error"

### ISSUE THREAD

**Issue by ryanstickley** [khanhas/spicetify-cli#729]
every time I try to run the spicetify apply command, it always runs into the error 
"fatal open C:\Users\*****\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified."
I've tried creating the css folder, but that didn't work. and the only way it worked is by installing a 2 year old version of spotify
please help

**Comment by khanhas** [comment]
Read the readme page
https://github.com/khanhas/spicetify-cli#legacy-spotify
