### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by juliankomatsu** [khanhas/spicetify-cli#73]
![image](https://user-images.githubusercontent.com/55417941/65002098-936d8d80-d8c8-11e9-877e-510bcff873f7.png)

basically, i cant use spotify like this. i did the correct steps to link spicetify with the monstercat visualizer, and this happened. this is very unpleasing...
how can i return spotify to normal with the both plugins working correctly?

**Comment by dindin56** [comment]
Having the same issue. Spotify just updated. They must've changed something.

**Comment by Maleando** [comment]
This started for me yesterday and Spotify was force updating upon restart now it's just completely broken.

**Comment by MEXdave1997** [comment]
Also same issue. Seems like Spotify caught on and messed with the CSS values.

**Comment by khanhas** [comment]
Fixed in v0.9.4
