### ISSUE TITLE
Feature Request: bookmark.js Add songs to bookmarks from right click context menu?

### ISSUE THREAD

**Issue by Tread-2036** [khanhas/spicetify-cli#731]
While I'm not sure if extensions can change the right click context menus, I think it would be nice to be able to add tracks/pages to the bookmark.js extension without needing to visit the page or play the song (more seamless I guess?).

**Comment by AustrAlienGH** [comment]
extensions can change context menus (see shuffle+.js). Although wouldn't this just be the same thing as your liked songs?

**Comment by Tread-2036** [comment]
I think the idea of the bookmark extension is to have a separate list from your likes as a listen later?
