### ISSUE TITLE
extension trashbin not working 

### ISSUE THREAD

**Issue by KyungbokLee** [khanhas/spicetify-cli#732]
I'm currently using the latest version for both Spotify and Spicetify on Windows 10,
and there is no trashbin button even after I applied on powershell.

Other extensions like shuffle+ and bookmark are working.

**Comment by khanhas** [comment]
Trashbin button are in right click context menu.
Right click at track title or artist

**Comment by KyungbokLee** [comment]
![image](https://user-images.githubusercontent.com/43272511/120590002-c24cde00-c474-11eb-90fc-3b6d0268a7a3.png)

I've right-clicked a track but no trash button. Same for artist.
