### ISSUE TITLE
Spicetify not changing anything 

### ISSUE THREAD

**Issue by Pauzovzki** [khanhas/spicetify-cli#734]
Please help me really love the idea of changing spootify colors, but i cant
![image](https://user-images.githubusercontent.com/64266119/120676323-ce916500-c48d-11eb-98f3-dffb3c862877.png)
![image](https://user-images.githubusercontent.com/64266119/120676417-e7017f80-c48d-11eb-9ee2-2a0304856cd0.png)

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply`

**Comment by devExcale** [comment]
Got the same problem, I tried applying themes for the first time but it didn't work.
I tried on my desktop and my laptop, both running the latest version of Spotify and spicetify. At first, I tried on my desktop with a (slight) older version of spicetify, it didn't work so I tried updating but still nothing.

I guess something broke with the latest Spotify update.

**Comment by khanhas** [comment]
Maybe read the front page of the repo might give you some insight.

**Comment by khanhas** [comment]
and this: https://github.com/khanhas/spicetify-cli/discussions/578

**Comment by Pauzovzki** [comment]
@khanhas i have to install it trough microsoft store else it doesnt work, is it related?

**Comment by khanhas** [comment]
Yes. Please uninstall it from Microsoft Store, download installer from Spotify website, install it and try `spicetify backup apply`

**Comment by Alyetama** [comment]
If you have a recent version of Spotify (which I assume is the case since you reinstalled it), then use the themes [here](https://github.com/morpheusthewhite/spicetify-themes/tree/v2) instead. These are compatible with the new UI.

**Comment by talpay** [comment]
Can we get an official confirmation as to whether the new UI supports the old themes?

**Comment by HuangLinBao** [comment]
I've had the same issue here....I'm using manjaro linux and tried installing spicetify from AUR and using curl...installed spotify using AUR and flatpak...no use....extensions apply with no issues but themes don't

**Comment by talpay** [comment]
It's easy to miss that the spicetify-themes repository has a v2 branch and that the master is outdated. Switching these or mentioning this at the start of the README might prevent further misunderstandings.

**Comment by HuangLinBao** [comment]
> It's easy to miss that the spicetify-themes repository has a v2 branch and that the master is outdated.



I figured that out and my problem was solved...waiting for other themes to be added the v2 branch

**Comment by lockieluke** [comment]
https://github.com/lockieluke/SpotifyDesktopMod
care to take a look at this?
