### ISSUE TITLE
Spicetify messes up my Spotify

### ISSUE THREAD

**Issue by waltermelan** [khanhas/spicetify-cli#74]
![Screenshot (65)](https://user-images.githubusercontent.com/55470738/65098954-3206f680-d97c-11e9-940b-459923be9bef.png)
I tried reinstalling Spotify, reverting Spotify, or reinstalling Spicetify. I run out of options, and I don't know what to do.

**Comment by khanhas** [comment]
Please update Spicetify to 0.9.4
