### ISSUE TITLE
[Request] fullAppDisplay Add Collection (heart) button.

### ISSUE THREAD

**Issue by RebirthEgo** [khanhas/spicetify-cli#742]
[Request] fullAppDisplay Add Collection (heart) butt
<img width="914" alt="heart" src="https://user-images.githubusercontent.com/54738173/120929953-c0597800-c71d-11eb-9d6c-1ce3704dccc5.png">
on.

**Comment by khanhas** [comment]
Nah

**Comment by khanhas** [comment]
Use `keyboardShortcut.js`

**Comment by RebirthEgo** [comment]
> Nah
Well! Then I'll just have to figure it out for myself.
