### ISSUE TITLE
Lyrics Plus bug. One annotation for all lines.

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#746]
There is a bug in lyrics app (genius) when one annotation is shown for all lines. It doesn't happen always, but really often. If you try to change the song - then the first annotation that you click on new song - will be for all lines on this song. Reload page doesn't help. Only Spotify restarting helps. 

Interestingly, during the bug, in HTML code, all lines have the correct annotations in href.

**Comment by khanhas** [comment]
Have you double checked with genius site on real browser to confirm they are not originally like that?

**Comment by FiftyFour7250** [comment]
> Have you double checked with genius site on real browser to confirm they are not originally like that?

Yea, of course. I'm sure everyone has this bug, but no one notices it, because you need to know which annotations belong to which lines. 

[Here's the video](https://disk.yandex.ru/i/lGZoamtJKL6zhw)

**Comment by FiftyFour7250** [comment]
And yes, I also have this bug without any my extensions or css. I first noticed it on May 23.
I have the latest versions of Spotify and Spicetify
