### ISSUE TITLE
Shuffle+ buttons not showing up on the queue menu

### ISSUE THREAD

**Issue by Player72** [khanhas/spicetify-cli#747]
I'm used to pressing the queue button then the queue pops up and right above that would be two buttons that say Shuffle Context and Shuffle Queue.

![image](https://user-images.githubusercontent.com/17227845/121091830-9dc86d00-c7b8-11eb-98f0-91b29ba4ca98.png)

The black rectangle is where these two buttons would normally show up, but I don't see them. I know shuffle+ is installed because I see it in the context menu when i right-click a playlist and it says "Play with shuffle+". 

What do?

**Comment by khanhas** [comment]
That's v1 Shuffle+ extension. It has been updated to v2 and doesn't have that feature anymore. I don't have time to update Wiki.
They're useless anyway imo, just right click at stuff and choose `Play with Shuffle+`.
