### ISSUE TITLE
Lyrics Plus colourful background bug

### ISSUE THREAD

**Issue by Sparoney** [khanhas/spicetify-cli#748]
Hey,

I found a bug with the Lyrics Plus colourful background, which might have to do with this commit? https://github.com/khanhas/spicetify-cli/commit/8692c461e11cbf2c4294c07fb72489ccfece5d70

Basically, the coloured background based on album art doesn't work, until it is toggled off and back on. Then, when the song changes, it doesn't update until it is once again toggled off and back on. It was working fine about a week ago.

It defaults to the colour specified as "Background colour" in the config if the album art coloured background is turned off.

I'm using Spicetify v2.2.6 and Spotify v1.1.61.583.gad060c66-a

I can test previous commits of lyrics plus if you'd like

Edit: Also, what does the noise overlay option do? I never noticed any change with it being on or off

**Comment by Thiagoedlp151** [comment]
I have the same problem. Could you fin any solution?

**Comment by Sparoney** [comment]
> I have the same problem. Could you fin any solution?

Yes, khanhas has fixed it in this commit: https://github.com/khanhas/spicetify-cli/commit/3c4469fd688c73d7da2c4894bda7515de7be1a90. I downloaded the updated index.js and Settings.js from it.
