### ISSUE TITLE
All themes are messed up

### ISSUE THREAD

**Issue by rxckstar** [khanhas/spicetify-cli#75]
No matter what theme i choose the font and css are all messed up and not working, 

I'm on windows 10 (not using windows store app), I've tried reinstalling both spotify and spicetify

ss below

![gPTidTu](https://user-images.githubusercontent.com/34636878/65158920-2fafa580-da2b-11e9-8b98-6498e02e2dcf.png)

**Comment by in1tiate** [comment]
Fixed in Spicetify v0.9.4 per [Spectrum thread](https://spectrum.chat/spicetify/general/spotify-layout-breaks-after-recent-spotify-update~98abae96-aecc-4b9b-8541-4945712d1f39?m=MTU2ODUyMzMyNTc2NA==)
