### ISSUE TITLE
lyrics app for legacy version?

### ISSUE THREAD

**Issue by cristianmtr** [khanhas/spicetify-cli#750]
Is there a way to make it work there? I can't seem to be able to update Spotify to a version newer than 55, so I'm stuck trying to get lyrics app to work in legacy spicetify. Any input?

Thanks

**Comment by khanhas** [comment]
You can update to Spotify v1.1.56 with deb file provided by Spotify in their website

Anyway, this is lyrics app predecessor
https://github.com/khanhas/genius-spicetify

**Comment by cristianmtr** [comment]
Thanks for the quick reply!
