### ISSUE TITLE
AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Haven-Lau** [khanhas/spicetify-cli#751]
### version: 
spotify version: **1.1.60.672.g6ad9c215-a**
spicetify installation cmd: 
```
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
```

### problem:

I tried to reinstall spotify and spicetify from scratch, stock config without any theme or extensions applied, as soon as I run `spicetify apply` I get the following error:

``` \> spicetify apply
spicetify v1.2.1
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
fatal open C:\Users\haven\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.
```
my AppData\Roaming\Spotify\Apps\ directory:
![image](https://user-images.githubusercontent.com/12973227/121271479-9f596a00-c878-11eb-9804-c0d0348d436e.png)

config.ini:
```[Setting]
prefs_path              = C:\Users\haven\AppData\Roaming\Spotify\prefs
current_theme           = SpicetifyDefault
inject_css              = 1
overwrite_assets        = 0
spotify_path            = C:\Users\haven\AppData\Roaming\Spotify
color_scheme            = 
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features        = 0
fastUser_switching           = 0
extensions                   = 
custom_apps                  = 
home                         = 0
lyric_always_show            = 0
lyric_force_no_sync          = 0
radio                        = 0
song_page                    = 0
visualization_high_framerate = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.60.672.g6ad9c215
```

am I missing some installation steps?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation

**Comment by Haven-Lau** [comment]
I used the powershell command linked there, is that up to date?

**Comment by khanhas** [comment]
When did you do it? Did you notice that latest release is completely different than what you had?

**Comment by Haven-Lau** [comment]
I did a clean install today - both my spotify installation and spicetify-cli

**Comment by khanhas** [comment]
Please remove any spicetify version you had.
Run install script again, make sure it installs version 2.2.6 and try again.
