### ISSUE TITLE
Everything is working previously and after spotify and spicetify update it didnt work

### ISSUE THREAD

**Issue by brenmadeit** [khanhas/spicetify-cli#755]
I checked inject_css and replace_colors all is set to 1 and still didn't work

**Comment by brenmadeit** [comment]
and all then extensions work as well just the theme, I tried with Nosleep theme and also dribbblish as well

**Comment by khanhas** [comment]
Provide Spicetify version, Spotify version and what OS are you using. Also try phrase your sentences probably. I have no idea what works what doesn't

**Comment by Thiago-LM** [comment]
Currently on `Windows 10 Pro v20H2 OS build 19042.1052` and `Spicetify v2.2.6` and experiencing similar problem. I was using [DribbblishDynamic](https://github.com/morpheusthewhite/spicetify-themes/tree/master/DribbblishDynamic) theme and after Spotify updated (right now it's on v1.1.60.672, according to the Control Panel) it's back to the default Spotify theme and I can't re-apply either, as it'll just don't appear on Spotify, but nothing wrong shows in the PowerShell.

**Comment by afonsojramos** [comment]
@Thiago-LM the new version has a new set of themes on the [v2 themes branch](https://github.com/morpheusthewhite/spicetify-themes). Unfortunately old themes are not supported by the new version.

**Comment by Thiago-LM** [comment]
> 
> 
> @Thiago-LM the new version has a new set of themes on the [v2 themes branch](https://github.com/morpheusthewhite/spicetify-themes). Unfortunately old themes are not supported by the new version.

Oh, thanks. I didn't pay attention to this. It's working now with the v2 branch themes.
