### ISSUE TITLE
Lyrics Plus issues with colorful background

### ISSUE THREAD

**Issue by Aerozolic** [khanhas/spicetify-cli#761]
Just installed Spicetify and Lyrics Plus.

The issue is that every time I launch the app lyrics have the black background. Even though I have colorful background enabled. If I disable that setting and re-enable it then a new background color is set but it never changes until I disable and re-enable the setting. And then again if I close the app an re-open it, it's back to black background.

Spotify 1.1.61.583.gad060c66-a
Windows 10 21H1
Spicetify 2.2.6

**Comment by afonsojramos** [comment]
What lyrics sources do you have activated?

**Comment by Aerozolic** [comment]
Genius.

**Comment by khanhas** [comment]
The problem was identified and will be fixed in next spicetify version.
