### ISSUE TITLE
Ubuntu 20.04 Internal error

### ISSUE THREAD

**Issue by sn4dy** [khanhas/spicetify-cli#762]
![image](https://user-images.githubusercontent.com/16862833/121775141-7bef3180-cb8e-11eb-9a04-a4e17c73d42a.png)

**Comment by sn4dy** [comment]
Please let me know if I need to give any other details.

**Comment by afonsojramos** [comment]
What's the spotify and spicetify version?

**Comment by sn4dy** [comment]
spicetify 2.2.6
---
The problem was caused by the lyrics-plus plugin, it was fixed when I removed the plugin and tested it. thanks..
