### ISSUE TITLE
Chocolatey package outdated  and legacy versions on windows no longer working with current spotify

### ISSUE THREAD

**Issue by bennolor** [khanhas/spicetify-cli#763]
The spicetify package available on [chocolatey](https://community.chocolatey.org/packages/spicetify-cli) is heavily outdated (currently v1.1.0) and as of now no longer seems to be compatible with spotify

**Comment by bennolor** [comment]
note:
v1.2.1 also seems to no longer work with a fresh spotify installation
the directory 
```
C:\Users\me\AppData\Roaming\Spotify\Apps\zlink\css\
```
no longer gets created, resulting in the error of spicetify being unable to copy `user.css`.
When manually creating the directory `user.css` gets placed in there correctly, however either doesnt change spotify at all or results in a blank black window upon startup.

**Comment by bennolor** [comment]
Testing on Windows:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎23/‎12/‎2020
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
```

Spotify version(fresh reinstall)
```
1.1.61.583.gad060c66-a
```

Tested Spicetify versions:
```
1.1.0(chocolatey)
1.2.1
2.2.6
```

**Comment by khanhas** [comment]
Sorry I don't have govern over choco or scoop package.
You might want to give its maintainer a notice.
Or you can try `spicetify upgrade` command to upgrade spicetify.
