### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Eliqui** [khanhas/spicetify-cli#764]
Hey there,

I'm using the spicetify version v2.2.6 and Spotify version 1.1.61.583.gad060c66-a. 
The preview screenshots of the One Punch theme show the old playlist layout with the standard title/artist/album layout. Since i think the new layout where the artist is combined with the title is way more confusing and pretty shitty i would like the old one back. Are these just old screenshots of the themes and it's not possible to go back to the old layout? Or am i doing sth wrong?

**Comment by afonsojramos** [comment]
You now have to use the [v2 themes](https://github.com/morpheusthewhite/spicetify-themes/tree/v2), however, for a customization such as the one you are referring to, changes need to be made to the theme you choose to display as you wish.
