### ISSUE TITLE
"spicetify v2.2.6 err"

### ISSUE THREAD

**Issue by apolitoo** [khanhas/spicetify-cli#766]
Hi! I recently downloaded spicetify but, everytime i try to apply a theme, however i try, i keep getting the message on the picture below, and it only resets to the original Spotify layout. Anyone having the same problem? How can i fix it?
![problema](https://user-images.githubusercontent.com/81381322/121793944-98f52600-cbc9-11eb-8065-0ac9a2ceff41.png)

**Comment by Tread-2036** [comment]
Hi! @apolitoo https://github.com/khanhas/spicetify-cli/issues/629 might be worth checking out! Are you using a legacy theme?
