### ISSUE TITLE
Issues with Musixmatch lyrics

### ISSUE THREAD

**Issue by Aerozolic** [khanhas/spicetify-cli#767]
Genius lyrics work really well but Musixmatch (synced and unsynced) not that well.
I sometimes get lyrics working for multiple songs in a row but after that it just shows the (•_• ) for every song. If that happens I have to close Spotify and re-open it. Then Musixmatch lyrics work for a bit again and then stop working.
I added my own user token as per guide.

Spotify 1.1.61.583.gad060c66-a
Windows 10 21H1
Spicetify 2.2.6

**Comment by khanhas** [comment]
Did you get and replace token with your own as instructed?

**Comment by Aerozolic** [comment]
> Did you get and replace token with your own as instructed?

Yes, that’s exactly what I did.

**Comment by khanhas** [comment]
Well. Don't skip songs too fast. Musixmatch has rate limiting.

**Comment by Aerozolic** [comment]
> Well. Don't skip songs too fast. Musixmatch has rate limiting.

Would having Musixmatch Premium affect this limit in any way?

**Comment by khanhas** [comment]
I don't know, sorry.
