### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by nicolasbaggio** [khanhas/spicetify-cli#768]
![image](https://user-images.githubusercontent.com/6036714/121916997-09f02700-cd0b-11eb-81b3-2e9520fc8cb7.png)
I did everything and when I try to apply it gives this error.

**Comment by khanhas** [comment]
1. Uninstall Spotify from Windows Store
2. Install Spotify using installer from its website.
3. Run `spicetify -c` to know where config file
4. Delete config file and try `spicetify backup apply` again.

**Comment by afonsojramos** [comment]
Closed due to inactivity.
