### ISSUE TITLE
Themes are not working except the default

### ISSUE THREAD

**Issue by EricThunder** [khanhas/spicetify-cli#769]
https://user-images.githubusercontent.com/67475344/121934022-c7334c80-cd14-11eb-9bc7-ca8b2ba7f996.mp4

**Comment by afonsojramos** [comment]
@EricThunder the new version has a new set of themes on the v2 themes branch. Unfortunately old themes are not supported by the new version.

**Comment by EricThunder** [comment]
> @EricThunder the new version has a new set of themes on the v2 themes branch. Unfortunately old themes are not supported by the new version.

so how can I revert to the old one?

**Comment by afonsojramos** [comment]
> so how can I revert to the old one?

You would need to install a Spotify version prior to these changes and then install the legacy Spicetify, but my recommendation is to use v2 themes.

**Comment by GangsterFox** [comment]
And how does one install an older spotify version or how does one find v2 working themes

**Comment by elijaholmos** [comment]
@GangsterFox working v2 themes can be found in the v2 branch of [this](https://github.com/morpheusthewhite/spicetify-themes/tree/v2) repository. reverting to an older version of spotify is a bit more complicated, but there are several guides on the topic. [here](https://www.reddit.com/r/spotify/comments/jyp947/you_can_revert_back_to_previous_desktop_versions/) is one for an example.

**Comment by GangsterFox** [comment]
Much thank you for the reply, I went the hard way and reverted to 1.1.53 which gave me a small headache to get why it didnt work at first, but as I can see I might be switching to a newer version then since the Themes do look way more promising.
Thank you for giving me a way to get v2 Themes tho

**Comment by elijaholmos** [comment]
No problem, glad you were able to get it working eventually 👍
