### ISSUE TITLE
Reddit app not using proper CSS

### ISSUE THREAD

**Issue by porrige51122** [khanhas/spicetify-cli#77]
![image](https://user-images.githubusercontent.com/26583011/65247691-c1c9b380-dae8-11e9-802e-30fdcb1e3f20.png)
When using Reddit, none of the custom images are showing up. Is this a me error or an everyone error?

**Comment by accik** [comment]
Also having issues with new Spotify version, themes are looking way off. Version 1.1.15.448.g00fba0e3. I can attach pictures later

**Comment by porrige51122** [comment]
^^ I was only having problems with the reddit app since the newest update. Try redownloading the files from github and reapply. He has updated the repo since this problem

**Comment by khanhas** [comment]
Can you post your reddit app `index.html`?
It should be in `%appdata%\Apps\reddit\`

**Comment by porrige51122** [comment]
`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://zlink.app.spotify.com/css/glue.css">
  <link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" class="spicetify-userCSS" href="https://zlink.app.spotify.com/css/user.css"></head>
<body>
  <div id="reddit-setting-popover">
    <div class="modal-backdrop" data-interaction-intent="reddit-cancel"></div>
    <div class="popover modal" data-bind="css: modalClasses" data-interaction-context="modal-dialog">
      <h3 class="popover-title" data-bind="settingTitle">Setting</h3>
      <div class="popover-content">
        <div class="row">
          <div class="form-group col-sm-8 col-md-8 col-lg-8">
            <h4 data-bind="reddit-option-title">Options</h4>
            <div id="reddit-option"></div>
          </div>
          <div class="form-group col-sm-4 col-md-4 col-lg-4" id="reddit-subreddit">
            <h4 data-bind="reddit-form-title">Add subreddit</h4>
            <form id="subreddit-input-form">
              <input class="form-control" type="text" id="subreddit-input" maxlength="100" placeholder="Subreddit name" data-bind="reddit-form-placeholder"></input>
            </form>
            <div id="autocomplete"></div>
            <div id="reddit-subreddit-list"></div>
          </div>
        </div>
      </div>
      <div class="popover-footer" data-bind="visible: footerVisible" tabindex="-1">
        <button
          class="button button-with-stroke"
          data-interaction-intent="reddit-cancel"
        >
          <span data-bind="cancelButtonLabel">Cancle</span>
        </button>
        <button
          class="button button-green"
          data-interaction-intent="reddit-confirm"
        >
          <span data-bind="okButtonLabel">Apply</span>
        </button>
      </div>
    </div>
  </div>
  <div id="render-target"></div>
  <div id="reddit-youtube">
    <div class="modal-backdrop" data-interaction-intent="youtube-close"></div>
    <div id="youtube-container" class="popover"></div>
  </div>
  <div id="reddit-sortby-context-menu" class="context-menu-container" style="display: none;">
    <div class="context-menu" style="z-index:2; opacity: 1; display: inline-block; height: auto; width: auto;">
        <div class="item" data-bind="hot">
          <span class="text">Hot</span>
        </div>
        <div class="item" data-bind="new">
          <span class="text">New</span>
        </div>
        <div class="item" data-bind="top">
          <span class="text">Top</span>
        </div>
        <div class="item" data-bind="rising">
          <span class="text">Rising</span>
        </div>
        <div class="item" data-bind="controversial">
          <span class="text">Controversial</span>
        </div>
    </div>
  </div>
  <div id="reddit-sorttime-context-menu" class="context-menu-container" style="display: none;">
    <div class="context-menu" style="z-index:2; opacity: 1; display: inline-block; height: auto; width: auto;">
        <div class="item" data-bind="hour">
          <span class="text">Past Hour</span>
        </div>
        <div class="item" data-bind="day">
          <span class="text">Past Day</span>
        </div>
        <div class="item" data-bind="week">
          <span class="text">Past Week</span>
        </div>
        <div class="item" data-bind="month">
          <span class="text">Past Month</span>
        </div>
        <div class="item" data-bind="year">
          <span class="text">Past Year</span>
        </div>
        <div class="item" data-bind="all">
          <span class="text">Of All time</span>
      </div>
    </div>
  </div>
  
  <script src="init.js"></script>
  <script src="bundle.js"></script>
</body>
</html>
`
Here is index.html

**Comment by khanhas** [comment]
You are using the old reddit app. In spicetify v0.9.4, I had a small modification in index.html to comply with new glue.css url.  
In case:
1. You did your own modification in your reddit app and don't want to lose it:
- In `index.html` please change: 
```
  <link rel="stylesheet" href="https://zlink.app.spotify.com/css/glue.css">
```
to
```
  <link rel="stylesheet" href="https://local_resource_host/css/glue.css">
```

2. You changed nothing:
- Please remove `%userprofile%\.spicetify\CustomApps\reddit`

3. `%userprofile%\.spicetify\CustomApps\reddit` doesn't even exist:
- Remove spicetify and reinstall it with PS script again. 100% works every single time.

**Comment by porrige51122** [comment]
Thanks, All working now :)

**Comment by TheLastZombie** [comment]
I'm having the same issue, even after following the instructions above, with both the Reddit and Bookmark apps.

![image](https://user-images.githubusercontent.com/8181990/66109250-89d06f00-e5c4-11e9-8fdd-46338199a9c3.png)

The network tab shows a failed request, may be intended behavior though.

![image](https://user-images.githubusercontent.com/8181990/66108883-d10a3000-e5c3-11e9-99cb-42de48178fc7.png)
![image](https://user-images.githubusercontent.com/8181990/66109082-352cf400-e5c4-11e9-97ce-73477ff24220.png)

Reinstalling Spicetify does nothing. Any ideas?

**Comment by porrige51122** [comment]
I assume to do the same as me and paste your `index.html` see if there are any discrepancies

**Comment by khanhas** [comment]
Oops! Sorry all, I made a mistake. I forgot to re-package updated apps assets before I uploaded to Github.
I will publish v0.9.5 in a few minutes.

**Comment by khanhas** [comment]
Uploaded.
Please upgrade to v0.9.5
