### ISSUE TITLE
missing path fatal open C:\Users\Maximiliano\AppData\Roaming\Spotify\Apps\zlink\css\user.css: El sistema no puede encontrar la ruta especificada.

### ISSUE THREAD

**Issue by maxii126** [khanhas/spicetify-cli#771]
I tried everything and nothing works

I tried to create the path by myself, and it doesn't work either
![image](https://user-images.githubusercontent.com/85974568/122145616-93931800-ce23-11eb-857e-b2e3f467b156.png)

I tried reinstalling spicetify and Spotify from zero and nothing works. I installed the latest version of Spotify. Any idea? :(

**Comment by Aerozolic** [comment]
Seems to me that your Spicetify is out of date.

**Comment by afonsojramos** [comment]
@maxii126 What version of Spotify are you running? 
Most likely it is an up to date one, and in that case you need to update Spicetify to 2.X. Refer to [instalation](https://github.com/khanhas/spicetify-cli/wiki/Installation) for help!

**Comment by afonsojramos** [comment]
This is the problem of having an installation link for the legacy version in the readme 😅
Go to https://github.com/khanhas/spicetify-cli/wiki/Installation @maxii126

**Comment by maxii126** [comment]
Look at this

> 
![image](https://user-images.githubusercontent.com/85974568/122239764-35038380-ce8f-11eb-9c96-738adcf3b157.png)


When I use that link it installs an old version of spicetify. I think you misunderstood my answer.
