### ISSUE TITLE
newRelease.js extension not working

### ISSUE THREAD

**Issue by jraxxo** [khanhas/spicetify-cli#772]
I have noticed that recently, the newRelease.js extension stopped working completely.
I could successfully activate it (only after manually downloading it from GitHub for some reason though, not sure what's going on here as newReleases.js should be a default extension, no?), but the button just doesn't show up. 
It doesn't matter whether I have activated a theme or not. I also tried manually copying the .js file to .config/spicetify/Extensions in addition to it residing under spicetify_data/Extensions. 
What gives? 
Spotify Ver. 1.1.61.583.gad060c66-a
macOS Big Sur 11.4
![image](https://user-images.githubusercontent.com/2436494/122170295-b272c800-ce7e-11eb-99be-6f357414e330.png)

![image](https://user-images.githubusercontent.com/2436494/122170220-9a02ad80-ce7e-11eb-928d-4b7d6a6c4b9e.png)

**Comment by Aerozolic** [comment]
Try:
`spicetify config custom_apps new-releases
spicetify apply`

instead

**Comment by jraxxo** [comment]
Sadly, that doesn't work either.

**Comment by Aerozolic** [comment]
> Sadly, that doesn't work either.

In that case I'd start from scratch. Remove everything related to Spicetify and Spotify and reinstall. Both lyrics and new releases work for me.

**Comment by afonsojramos** [comment]
@jraxxo on the Spicetify 2.X `new-releases` started being a custom app, which, as the link @Aerozolic provided, now shows as a tab on the left.

Can you elaborate on what happens when you run this command?

```
spicetify config custom_apps new-releases

spicetify apply
```

**Comment by jraxxo** [comment]
@afonsojramos Ohh sorry, I'm an idiot. 
I was looking for the old button.
The tab is working, thank you 👍
