### ISSUE TITLE
Improvements to Genius lyrics

### ISSUE THREAD

**Issue by Aerozolic** [khanhas/spicetify-cli#773]
Some songs have lyrics in multiple languages or translations. It seems that the lyrics feature is not sure which one to  show and in some cases it doesn't show the lyrics in the original language at all.
For example Godzilla - Eminem. It shows those options:
![image](https://user-images.githubusercontent.com/25500346/122184341-cc1f0a00-ce94-11eb-8284-672d0c2ca040.png)
There isn't an English version even shown.
And in some other cases the English version is available but not shown by default.

I'm not sure what to do in the first case where lyrics in English aren't shown as an option at all. But for other cases maybe it could be possible to set a default language for Genius lyrics to be shown?

**Comment by khanhas** [comment]
Is this really a problem? Like does it happen to many songs or just this one particularly?
Either way, I don't know how. Lyrics plus scraps whatever Genius search page gives, it doesn't have language information and certainly doesn't know what song's original language is.
