### ISSUE TITLE
Spotify is completely mangled

### ISSUE THREAD

**Issue by pcktm** [khanhas/spicetify-cli#78]
![Spotify_2019-09-22_20-29-00](https://user-images.githubusercontent.com/13273420/65392694-c1931780-dd77-11e9-86c8-ee44fb461aef.png)
After updating spotify not a single theme works correctly (see attached image). I'm using the latest spicetify version, tried clean reinstalling - didn't help.

**Comment by nesperida911** [comment]
i experience that also. my workaround there is to reinstall both again :3

**Comment by khanhas** [comment]
Fixed in v0.9.4
