### ISSUE TITLE
Can't play any songs at all and cant see the songs on my playlists

### ISSUE THREAD

**Issue by Lochie123** [khanhas/spicetify-cli#783]
## ℹ Computer information

- Spotify version: 1.1.39.612
- Spicetify version: 1.2.1

Basically I watched https://www.youtube.com/watch?v=RdbN1ig3BNY&t=318s called [UPDATED] Make Spotify Look Better Using Themes! followed those instructions untill I realised that I couldnt play any songs or see the songs in my playlist. According to this video u have to use an old spicetify because the new version doesnt work or something. help me my friends, I am desperate.

**Comment by Lochie123** [comment]
also when it is restored it also doesnt work, so i guess it isnt the themes that are an issue

**Comment by khanhas** [comment]
Your spotify version is ancient. I can't help you.

**Comment by Lochie123** [comment]
@khanhas but doesnt the new version not work

**Comment by Lochie123** [comment]
with the themes

**Comment by afonsojramos** [comment]
It works, you just have to use the v2 themes
