### ISSUE TITLE
Something went wrong, please reload the page and try again

### ISSUE THREAD

**Issue by Lochie123** [khanhas/spicetify-cli#784]
Downloaded the newest version of Spotify and Spicetify, however when I open spotify it says "something went wrong, please reload the page. THis also happens on the web player.

**Comment by Lochie123** [comment]
i literally uninstalled spotify and the web player doesn't work still

**Comment by khanhas** [comment]
Sorry. I have no idea. Probably bug on Spotify server side.
Try play something on your phone and open web player again.

**Comment by afonsojramos** [comment]
Try running `spicetify restore backup apply` to see if it helps!

**Comment by CharlieS1103** [comment]
Did you check your proxy settings? Might have messed something up.

**Comment by jrmain** [comment]
I'm seeing something similar, but only on the home page: 'Something went wrong. Try reloading the page.' Clicking the big reload button does nothing. Running 'spicetify restore' returns home page to normal crappy Spotify default page.

Possibly related: none of the new sidebar and home page config features work: I don't see any of the options described.

Using latest Spotify and Spicetify 2.3.0

**Comment by CharlieS1103** [comment]
@jrmain Can you show the console errors when you attempt to start spotify?

**Comment by jrmain** [comment]
[xpui.app.spotify.com-1624397660680.log](https://github.com/khanhas/spicetify-cli/files/6697540/xpui.app.spotify.com-1624397660680.log)

**Comment by CharlieS1103** [comment]
@jrmain At least for me that didn't work, mind just sending a screenshot?

**Comment by CharlieS1103** [comment]
@jrmain Scratch that, it says SpiceitfyHome is not configured, mind ending your config file as well?

**Comment by shreyamtaneja** [comment]
I had the same problem and turning off the new home_config feature off fixed it
` spicetify config home_config 0`

**Comment by Lochie123** [comment]
!. uninstall spotify and all the associated files
2. go to C:\Windows\System32\drivers\etc and move the file to the desktop
3. open the host file
3. delete anything with Spotify in it and save it
4. move the file back in and reinstall spotify

**Comment by CharlieS1103** [comment]
@Lochie123 I don't think a full reinstall would help here, ans they said they already tried. Also please leave the issue open until it's resolved.

**Comment by jrmain** [comment]
@Lochie123 - I'm not sure why you think this problem has anything to do with my local HOSTS file. Or why I would use the process you describe to change it. But I checked anyway, and sure enough, there's nothing about Spotify in my HOSTS file.

**Comment by jrmain** [comment]
@CharlieS1103 - here you go:
[Preprocesses]
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1

[AdditionalOptions]
custom_apps    = 
extensions     = 
sidebar_config = 1
home_config    = 1

[Patch]

[Setting]
spotify_path            = C:\Users\me\AppData\Roaming\Spotify
prefs_path              = C:\Users\me\AppData\Roaming\Spotify\prefs
current_theme           = SpicetifyDefaultJR
color_scheme            = nord-light
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.61.583.gad060c66
with    = 2.3.0

**Comment by Lochie123** [comment]
It had a problem with spotify itself. I couldn't login and thst fixed it
for me

**Comment by jrmain** [comment]
@Lochie123 But I'm able to log in just fine. That's not the problem.

**Comment by jrmain** [comment]
Sorry, I seem to have hijacked this issue. My bad.

**Comment by jrmain** [comment]
> I had the same problem and turning off the new home_config feature off fixed it
> ` spicetify config home_config 0`

Yup, that fixed it for me too.

**Comment by CharlieS1103** [comment]
@jrmain set home config to 0 and see if that works

**Comment by khanhas** [comment]
@CharlieS1103 @jrmain If you have problem with home_config:
1. Turn it on
2. Run `spicetify restore backup apply`
If problem still persist, Console screenshot would help me debugging. Thank you

**Comment by jrmain** [comment]
As requested, used these commands:
`spicetify config home_config 1`
`spicetify restore backup apply`
I still get 'Something went wrong. Try reloading the page.' when I navigate to the Home screen.
Console screenshot attached.
![SpicetifyHomeProblemsConsole](https://user-images.githubusercontent.com/1110694/123105021-4a773100-d3ec-11eb-8b80-e71fe12333fc.png)

**Comment by CharlieS1103** [comment]
Seems like a code error in homeConfig.js.I'll check it out later

**Comment by DimitriDaSilva** [comment]
I'm having the same issue on Arch Linux (5.12.12). The "Something went wrong" pops up every time I try to set a different theme

**Comment by popebene** [comment]
Anyone found a fix for this or know when it might be fixed?

**Comment by CharlieS1103** [comment]
@popebene @DimitriDaSilva It was fixed just now, update your spicetify and try setting homeconfig to 1.

**Comment by CharlieS1103** [comment]
@Lochie123 Mind closing your issue?

**Comment by okarin001** [comment]
> @popebene @DimitriDaSilva It was fixed just now, update your spicetify and try setting homeconfig to 1.
i still have this one.. with the latest spicetify.

**Comment by Aerozolic** [comment]
Same here.

**Comment by DimitriDaSilva** [comment]
I no longer have the error message but I don't have the updated theme either. To be noted that it never worked for me so it might come from something else. Very likely my own fault, although I did RTFM. 

I tried several themes (including Dribbblish with the extension). The closest I came from a theme change was the font being off (like when you apply a font that you don't have so it sets a ugly default one)

I tried with both `home_config = 0` and `home_config = 1`

![image](https://user-images.githubusercontent.com/66511903/123505702-84e50600-d658-11eb-9c74-cd2f9777a8b3.png)

**Comment by popebene** [comment]
> @popebene @DimitriDaSilva It was fixed just now, update your spicetify and try setting homeconfig to 1.

not sure if I'm being an idiot or not, but;

updated spicetify, redownloaded spotify, followed all the right steps.

homeconfig 1 gives me the error, homeconfig 0 launches spotify but without the theme applied. :(

**Comment by khanhas** [comment]
If you're using Dribbblish, please also update it. There are some changes recently.

**Comment by popebene** [comment]
Dribbblish not the issue, I'm trying to use Onepunch.

**Comment by okarin001** [comment]
> > @popebene @DimitriDaSilva It was fixed just now, update your spicetify and try setting homeconfig to 1.
> 
> i still have this one.. with the latest spicetify.
> 
> with `home_config = 0` it works

this is the console log.. 
![console_log](https://user-images.githubusercontent.com/63984668/123509249-ed040e00-d691-11eb-8f13-665e56dabe05.png)

**Comment by Aerozolic** [comment]
> > > @popebene @DimitriDaSilva It was fixed just now, update your spicetify and try setting homeconfig to 1.
> > 
> > 
> > i still have this one.. with the latest spicetify.
> > with `home_config = 0` it works
> 
> this is the console log..
> ![console_log](https://user-images.githubusercontent.com/63984668/123509249-ed040e00-d691-11eb-8f13-665e56dabe05.png)
> 
> Edit1: so far only dribbblish is working. does that mean we need to fix our theme or something?
> Edit2: spotify version 1.1.61.583.gad060c66-a
> 
> Edit3: wait... with `home_config=0` my theme is working fine. i mean the changes i made is applied in the home page.
> what's the `home_config` for actually can anyone explain please??

https://github.com/khanhas/spicetify-cli/releases/tag/v2.3.0

**Comment by jeff2957** [comment]
Mac user here with the latest Dribbblish, spicetify and spotify version 1.1.60, also having the same problem after installing dribbbblish, my spotify shows "something went wrong" and couldn't show the theme. Tried home_config = 0 and restore backup but it's still not working.

**Comment by jrmain** [comment]
I updated Spicetify to 2.5.0 and now Home config and Sidebar config work perfectly. Home page no longer shows an error.

**Comment by isXander** [comment]
Still experiencing issue on spicetify 2.10.1-1

**Comment by G1sbi** [comment]
Bump, same problem

**Comment by acezx-programer** [comment]
my way to fix this is when you get the popup, reinstall spicetify, then when you get the popup again, turn on airplane mode, do spicetify restore backup, then spicetify apply, then turn on airplane mode off

**Comment by IsAvaible** [comment]
I managed to resolve the issue by disabling offline mode via the three dot menu and restarting Spotify.

**Comment by AboodeDaBOSS** [comment]
guys I got this issue around two months ago
<img width="577" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/68856095/daa86aa5-d713-4907-ab48-a46ad90771a2">
