### ISSUE TITLE
Application does nothing to spotify

### ISSUE THREAD

**Issue by ithsmis** [khanhas/spicetify-cli#785]
## ℹ Computer information

- Spotify version: 1.1.61.583.gad060c66-a
- Spicetify version: 2.2.7

## 📝 Provide detailed reproduction steps (if any)

1. … run "spicetify backup apply" in powershell
2. … "success Spotify is spiced up"
3. … Spotify opens to original version

### ✔️ Expected result

Spicetify is applied to spotify 
 
### ❌ Actual result

Nothing changes. Same applies to anything else I try to change in powershell (colors, extensions, etc.). No errors are shown in powershell, which seems to think it's working just fine. This never happened before, but I'm not great with this kind of stuff, so I could be doing something wrong and not noticing it.

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by invakid404** [comment]
Linux user here, Spotify 1.1.56.595, Spicetify used to work, but themes simply don't apply on my new install.

**Comment by afonsojramos** [comment]
@ithsmis Can you specify which themes you are using?

**Comment by ithsmis** [comment]
> @ithsmis Can you specify which theme you are using?

Just the default, I was going to apply it as it comes then mess with themes later

**Comment by khanhas** [comment]
Can you post your config file here?

**Comment by ithsmis** [comment]
![Capture](https://user-images.githubusercontent.com/86202188/122824150-447b3600-d2ae-11eb-8582-eee40baadc73.PNG)

**Comment by khanhas** [comment]
You didn't set any theme, of course Spotify doesn't change.
Set `current_theme` to `SpicetifyDefault` and `color_scheme` to `pink-white`, `green-dark`, `nord-light`, `nord-dark`, `purple` or `dracula`

**Comment by Envious7777** [comment]
Same here . i use windows 11 btw, but if use default themes its working normally
![image](https://user-images.githubusercontent.com/35870230/122994586-d1b7ab00-d3d2-11eb-9bd3-1f2b4e8db90d.png)

**Comment by CharlieS1103** [comment]
@Envious7777 Mind showing the custom color scheme so we can see if its an error with that?

**Comment by Envious7777** [comment]
> @Envious7777 Mind showing the custom color scheme so we can see if its an error with that?

![image](https://user-images.githubusercontent.com/35870230/123086851-1a607a00-d44e-11eb-9bb2-75b712de4430.png)

**Comment by khanhas** [comment]
You're using legacy theme, it no longer works
Check these out: https://github.com/morpheusthewhite/spicetify-themes/tree/v2
Also don't insert your own issue in other ppl issue.
