### ISSUE TITLE
[Question] command to empty color_scheme.

### ISSUE THREAD

**Issue by fosam** [khanhas/spicetify-cli#786]
Hello!

This is just a question:

What is the command in Windows to "empty" the **`color_scheme`** field in the **`config-xpui.ini`** file? 

I'm aware that i can achieve this by editing the config file but I'm also looking for the way to do it via CLI.

**Comment by khanhas** [comment]
Second parameter should be a space
`spicetify config color_scheme " "`

**Comment by fosam** [comment]
It doesn't completely wipe the field but it assigns a `" "`

Is that a problem?

**Comment by khanhas** [comment]
No it isn't. INI format does not recognize a space as valid value, it would be trimmed to empty value. Hence default color scheme is used instead.
If your `colors.ini` file has multiple color scheme sections, first section is default color scheme.
If you want original Spotify color scheme, set `replace_colors` to 0.
