### ISSUE TITLE
Cannot apply new spicetify update

### ISSUE THREAD

**Issue by Inovvia** [khanhas/spicetify-cli#788]
## ℹ Computer information

- Spotify version: 1.1.62.575.gca12c808-a
- Spicetify version: 2.2.7 

## 📝 Provide detailed reproduction steps (if any)

1. Install Spicetify
2 Update Spotify
3. Run spicetify backup restore apply

### ✔️ Expected result

Spicetify is applied

### ❌ Actual result
[ 2 / 2 ] loginfatal open C:\Users\Jm\.spicetify\Backup\settings.spa: The system cannot find the file specified.
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/70137651/122711924-a11e2700-d295-11eb-99c3-40d8127d802b.png)

**Comment by khanhas** [comment]
Thank you

**Comment by khanhas** [comment]
At the moment you can copy and paste login or xpui.spa and rename it to `settings.spa` then try the command again.
Just a temporary solution. I will fix it later when the update comes in my machine.

**Comment by Inovvia** [comment]
It showed a new issue.
![image](https://user-images.githubusercontent.com/70137651/122721208-f876c400-d2a2-11eb-91d9-9c99690e365c.png)

**Comment by khanhas** [comment]
well, do the same thing for `glue-resources.spa`

**Comment by Inovvia** [comment]
Yep that's what fixed it.
