### ISSUE TITLE
Genius lyrics for lyrics-plus is not working

### ISSUE THREAD

**Issue by WildCatIan** [khanhas/spicetify-cli#792]
Whenever I check the genius tab in lyrics-plus I get the (._.) error face. This happens for every song I play. Please fix this. I love this feature and it sucks to be without it.

- Spotify version: latest version
- Spicetify version: v2

**Comment by afonsojramos** [comment]
Try running `spicetify restore backup apply`.

**Comment by WildCatIan** [comment]
Unfortunately, that didn't work. Thanks for the suggestion though.

**Comment by afonsojramos** [comment]
You'll have to provide more info. Did you upgrade Spicetify? If not, it's a good opportunity to do it.

**Comment by WildCatIan** [comment]
I'm currently on the latest version of Spicetify (2.2.7), Spotify's latest version (downloaded two days ago), and have lyrics-plus installed. Karaoke, Synced, and Unsynced lyrics work, but when I go to the Genius tab, nothing shows up except the error face.

**Comment by afonsojramos** [comment]
Oh, I see, it's only Genius that is not working. Sorry, can confirm the same on my end.

**Comment by khanhas** [comment]
Yeah, they rolled new page layout again.

**Comment by WildCatIan** [comment]
That's a bummer. Hope it'll be an easy fix! Thanks for all the help.
