### ISSUE TITLE
Fast-Switching Flag not working in New Spicetify Version

### ISSUE THREAD

**Issue by aaryanpednekarr** [khanhas/spicetify-cli#793]
## ℹ Computer information

- Spotify version: 1.1.61
- Spicetify version: 2.2.7

### ✔️ Expected result
Switch to new user option should be enabled

### ❌ Actual result
Switch to new user option is not enabled

**Comment by khanhas** [comment]
Spotify removed it.

**Comment by Poopooracoocoo** [comment]
oh i had no idea it was spotify who had this feature and not spicetify. could you please add this to your wiki or something? i looked all over for info on it.
