### ISSUE TITLE
Page content not always loaded when appchange event fires

### ISSUE THREAD

**Issue by theRealPadster** [khanhas/spicetify-cli#794]
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2da0de,
- Spicetify version: 2.3.0

## 📝 Provide detailed reproduction steps (if any)

1. Make and enable an extension that listens to and logs the appchange event
2. Start Spotify and open dev tools + console
3. Click on the Search page in the sidebar

### ✔️ Expected result

I'd expect the content of the search page to be fully loaded, or at least have all the DOM elements

### ❌ Actual result

There is a div with a child on the page, but that child is empty and the actual categories are not there. 

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/1565883/123021405-0eb77980-d3a2-11eb-83ac-490940ace561.png)

### Other notes

I had implemented the MutationObserver technique manually in my [spiceify-hide-podcasts](https://github.com/theRealPadster/spicetify-hide-podcasts) extension for Spicetify v2, and I'm currently getting around this issue by including the subtree with the MutationObserver and looking for a specific item for the Search, which you can see [here](https://github.com/theRealPadster/spicetify-hide-podcasts/blob/8f4ca3d253209dafeb237eadede0a3592afdc250/hidePodcasts.js#L38-L62). I thought it would be cleaner to just use the `appchange` event, so I tried swapping over. 

Side note: I'm also noticing that sometimes content loads in randomly after the page has been idle for a while (issue reported [here](https://github.com/theRealPadster/spicetify-hide-podcasts/issues/17), which I am not able to detect without leaving the MutationObserver running. Do you have any idea if it's possible to detect these?

**Comment by khanhas** [comment]
Sorry, there is no way to detect when app is fully loaded or not. Each app has their own way to fetch content, some fast some slow. And their component constructs are different from each other. This is the best I can give.
You can always use MutatationObserver and setTimeout to wait till app is "fully" loaded. 
And as you said, their content could be dynamic and change. Sorry, no way to detect that.
