### ISSUE TITLE
Global Shorcuts ?

### ISSUE THREAD

**Issue by keplerk** [khanhas/spicetify-cli#8]
Hi, i would like to know if there is a way to make the shorcuts works globally, even when spotify isn't in focus. i have no multimedia keys so this would be very helpful.

Regards.

**Comment by khanhas** [comment]
Sorry, there is no internal API providing that functionality. I checked.
But you can write a simple native program (a daemon) to connect with Spotify via websocket. Send messages back and forth to control player.
