### ISSUE TITLE
Developer mode remember credentials

### ISSUE THREAD

**Issue by sinankizar** [khanhas/spicetify-cli#80]
I want to start spotify in developer mode by default and spotify doesn't remember when I start in developer mode:
`spicetify enable-devtool`
 Is it possible to force remember the password in developer mode?

**Comment by khanhas** [comment]
You just need to run `enable-devtool` once.
You might need to login again after running that command. And that's all you need to do.

**Comment by sinankizar** [comment]
Thank you so much again. Now my spotify looks and SOUNDS great!!!
Thanks again for correcting the spotify client :)

**Comment by khanhas** [comment]
You were the second person talking about sound quality improvement. Although it is a good thing, I have to admit that it wasn't implemented or "upgraded" by me. I have no idea how enabling DevTool could enhance audio output.

**Comment by sinankizar** [comment]
I think spotify dev-tool disables the forcing stereo of spotify and then windows' speaker fill kicks in.  That might be the magic ;)
