### ISSUE TITLE
"fatal open C:\Users\USER\.spicetify\Backup\settings.spa: The system cannot find the file specified." Error after update 1.1.62.583.gdac868ed-a

### ISSUE THREAD

**Issue by jojoharry16** [khanhas/spicetify-cli#802]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: v2.2.5

## 📝 Provide detailed reproduction steps (if any)

1. Run `spicetify backup`

### ✔️ Expected result

A backup is taken

### ❌ Actual result

``` 
spicetify v2.2.5
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
[ 2 / 2 ] loginfatal open C:\Users\USER\.spicetify\Backup\settings.spa: The system cannot find the file specified.
```

**Comment by daksh2k** [comment]
Upgrade to Spicetify Version v2.30. It was fixed in that release.
To upgrade run:
```bash
spicetify upgrade
```
then
```bash
spicetify backup restore apply
```
If issue still exists reinstall spotify.

**Comment by jojoharry16** [comment]
Oh...


<sub>oopsie</sub>

**Comment by DinnoZurg** [comment]
> Upgrade to Spicetify Version v2.3.0. It was fixed in that release.
> To upgrade run:
> 
> ```shell
> spicetify upgrade
> ```
> 
> then
> 
> ```shell
> spicetify restore backup apply
> ```
> 
> If the issue still exists reinstall spotify.

okok i am going to try it

**Comment by DinnoZurg** [comment]
i triend but nothing 
![image](https://user-images.githubusercontent.com/86431655/123341686-041cf180-d514-11eb-8fc6-cb6db2cd447c.png)

still the same error

**Comment by CharlieS1103** [comment]
I've had this before, I think that a full reinstall of spotify and spicetify fixed it for me. @DinnoZurg. I think the issue was with spotify updating and spicetify not being able to apply because of it or something.

**Comment by DinnoZurg** [comment]
> I've had this before, I think that a full reinstall of spotify and spicetify fixed it for me. @DinnoZurg. I think the issue was with spotify updating and spicetify not being able to apply because of it or something.

okok i just tried that but only one at time i am going to try thanks

**Comment by DinnoZurg** [comment]
no, doesn´t work

**Comment by andre-paulo98** [comment]
Had the same issue and version 2.5.0 (released 2 days ago) seems to have this issue fixed

**Comment by DinnoZurg** [comment]
> Had the same issue and version 2.5.0 (released 2 days ago) seems to have this issue fixed

interesting i am going to try that
