### ISSUE TITLE
no fad button and some class value not normal

### ISSUE THREAD

**Issue by grasonchan** [khanhas/spicetify-cli#803]
## Information

* Spotify version: 1.1.62.583.gdac868ed-a
* Spicetify version: 2.3.0

## Bugs report
1. no fad button, same as #799
1. some class value not normal, since Spotify 1.1.61.583

**Comment by grasonchan** [comment]
### no fad button

![image](https://user-images.githubusercontent.com/19476925/123292575-c042e000-d545-11eb-92dd-1ffa6a012c2d.png)

![image](https://user-images.githubusercontent.com/19476925/123292523-b3be8780-d545-11eb-839a-b4f7e363b82f.png)

**I can add the fad button from the Console**

![image](https://user-images.githubusercontent.com/19476925/123296914-a5726a80-d549-11eb-808b-0bfee3b12071.png)

**And i think there is lost the class attribute.**

![image](https://user-images.githubusercontent.com/19476925/123289516-1f532580-d543-11eb-86ac-1b56aebf81ef.png)

![image](https://user-images.githubusercontent.com/19476925/123289614-32fe8c00-d543-11eb-8865-e8e3c85fddad.png)

![image](https://user-images.githubusercontent.com/19476925/123289873-67724800-d543-11eb-9b72-842af68575e1.png)

**Comment by grasonchan** [comment]
### class value not normal

![image](https://user-images.githubusercontent.com/19476925/123290558-f717f680-d543-11eb-821a-c5b201157ce7.png)

**Comment by FiftyFour7250** [comment]
Same
