### ISSUE TITLE
Spicetify Backup error 

### ISSUE THREAD

**Issue by DinnoZurg** [khanhas/spicetify-cli#804]
## ℹ Computer information
sorry but my computer is in spanish i am going to translate all 
- Spotify version: 1.86
- Spicetify version: 2

## 📝 Provide detailed reproduction steps (if any)

1. …Well i try to use spicetify but 
2. … When i try yo use the comand Backup 
3. …That appears

### ✔️ Expected result
That i can use the Backup succesfully 

_What is the expected result of the above steps?_

### ❌ Actual result
I cannot use the backup in specitify
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/86431655/123312384-e177e200-d4ed-11eb-8106-eec9f06aab1a.png)
(The system cannot find the specified file.)
_Are there any useful screenshots?_
Not but i previusly i can use specitify normaly whitout errors

**Comment by DinnoZurg** [comment]
I fortgot to say that is the normal spotify not the windows one

**Comment by Fosmos** [comment]
I'm having the same issue

**Comment by DinnoZurg** [comment]
> I'm having the same issue

can we compare information?

**Comment by daksh2k** [comment]
See  this issue #802!
And follow the steps in the [comment](https://github.com/khanhas/spicetify-cli/issues/802#issuecomment-867461257) to resolve it.

**Comment by Fosmos** [comment]
Oh I didn't see there was newer version. I was still on 2.2.7. This fixed it, thanks

**Comment by DinnoZurg** [comment]
> Oh I didn't see there was newer version. I was still on 2.2.7. This fixed it, thanks

where can you send me the link?

**Comment by Fosmos** [comment]
> > Oh I didn't see there was newer version. I was still on 2.2.7. This fixed it, thanks
> 
> where can you send me the link?

If you update your spicetify it should be fine. Check this link https://github.com/khanhas/spicetify-cli/issues/802#issuecomment-867461257
