### ISSUE TITLE
Broken Theme

### ISSUE THREAD

**Issue by XenottaBit** [khanhas/spicetify-cli#81]
Whenever i use the devtool or try to modify the theme, this keeps happening and i have no idea why. Can i have some help please?
![image](https://user-images.githubusercontent.com/39027165/65701917-d37ffd80-e08a-11e9-96be-6d62043a7a3c.png)

**Comment by XenottaBit** [comment]
Update: I reinstalled Spicetify, now it just isn't working

**Comment by khanhas** [comment]
1. Reinstall Spotify
2. Install spicetify v0.9.4
3. Run
```
spicetify backup apply
```

**Comment by XenottaBit** [comment]
Now it's just the regular theme, nothing changed
