### ISSUE TITLE
Synced lyrics tabs not working sometimes

### ISSUE THREAD

**Issue by Teun-Bergsma** [khanhas/spicetify-cli#810]
Latest version of spotify and spicetify, downloaded today

When using the lyrics feature the synced lyrics only function some of the time but most of the time the (∘_∘) emoji is the only thing showing up in the synced lyrics tab when it functions completely fine other times.  Attached below is the page of the same song one time with the working synced lyrics and the other one with the (∘_∘) emoji, any idea what is causing it to not work periodically?

![image](https://user-images.githubusercontent.com/78822623/123486692-d071c280-d60c-11eb-9723-2b89f7f76bba.png)
![image](https://user-images.githubusercontent.com/78822623/123487027-71607d80-d60d-11eb-85d6-b28dabf121c0.png)

**Comment by khanhas** [comment]
1. Did you get your personal Musixmatch token as instructed? Get into Lyrics Plus config and follow its link in Musixmatch section
2. Musixmatch has rate limit, it will stop responding if you send too many request in short period of time. In our case, you probably skip song too often. If you don't want to be annoyed by that, enable Netease provider to back up Musixmatch when it's down.

**Comment by Teun-Bergsma** [comment]
Sorry, where are the instructions for getting the musixmatch token, I could only find the commands to install the lyrics tab being.

spicetify config custom_apps lyrics-plus
spicetify apply

I did that but I can't find these extra steps you are referencing, thanks in advance for your response

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/123512880-48072680-d6cd-11eb-92e2-f4c56faf1443.png)

![image](https://user-images.githubusercontent.com/26436809/123512888-4fc6cb00-d6cd-11eb-9f58-31c74b2d4bed.png)

https://github.com/khanhas/spicetify-cli/wiki/Musixmatch-Token

**Comment by Teun-Bergsma** [comment]
Worked like a charm, thank you very much!
