### ISSUE TITLE
lyrics-plus not working

### ISSUE THREAD

**Issue by rickvandijck** [khanhas/spicetify-cli#812]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.3.0

## 📝 Provide detailed reproduction steps (if any)

1. Play a song
2. Click "Lyrics"

### ✔️ Expected result

Actually show the lyrics =]

### ❌ Actual result

Only shows the emoji thingy

**Comment by khanhas** [comment]
Read the Wiki.
