### ISSUE TITLE
Ability to add different types of variables

### ISSUE THREAD

**Issue by CharlieS1103** [khanhas/spicetify-cli#813]
## Idea
Currently, you are only able to add rgb and hex values to color.ini, however, Spotify has certain elements which don't accept these values, such as .main-trackList-playingIcon in sleek theme.

## Scenarios
As mentioned beforehand, the  .main-trackList-playingIcon is an example of where this could be used. This would be immensely useful to theme creators as it would allow us to change elements between schemes, and add a multitude of different elements to our themes.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by khanhas** [comment]
Use custom assets feature. Read v.2.5.0 release note, there is a basic tutorial there.

**Comment by CharlieS1103** [comment]
@khanhas I don't really see how that helps? I'm able to change the color of .main-trackList-playingIcon, however, I can't set different colors per each theme because hue-rotate requires a degree unit, and color.ini parses everything to either hex or rgb.

**Comment by khanhas** [comment]
.main-trackList-playingIcon is a GIF file. Because it's a image, there are very limited options to customized it. So, you replace that file with something else using custom assets I mentioned.
