### ISSUE TITLE
Home page broken

### ISSUE THREAD

**Issue by Deniied** [khanhas/spicetify-cli#816]
## ℹ Computer information

- Spotify version: latest as of date
- Spicetify version: latest as of date

## 📝 Provide detailed reproduction steps (if any)

1. … open spotify

### ✔️ Expected result

_should show home_

### ❌ Actual result

_something went wrong_

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/24880594/123526970-c3021a00-d698-11eb-9186-29aa0f490f4f.png)

**Comment by CharlieS1103** [comment]
@Deniied Yeah it's pretty messed up for a majority of people right now(not me I'm special lol.) Just go into your config and set ``home_config`` to ``0``

**Comment by khanhas** [comment]
Should be fixed now.
