### ISSUE TITLE
Themes dont get applied properly and sidebar_config doesnt get applied yet is set to 1

### ISSUE THREAD

**Issue by GangsterFox** [khanhas/spicetify-cli#818]
## ℹ Computer information

- Spotify version: 1.1.61.583.gad060c66
- Spicetify version: 2.4.0

## 📝 Provide detailed reproduction steps (if any)

Just trying to apply a theme doesnt work in an intended way, Let's say I try to apply Ziro theme, it gets applied but seems to be broken, sidebar doesnt get changed and home(as other people pointed out) displays an "Something went wrong" Page. The timer thing is also missplaced. I have tried with another theme dev to get things working (reinstall, generate new config, change up the config, use a different theme which also changes the home page and sidebar) came to no avail.
### ✔️ Expected result

_What is the expected result of the above steps?_
It should change the sidebar and home properly

### ❌ Actual result

_What is the actual result of the above steps?_
The sidebar doesnt change yet is turned on, the home page displays "Something went wrong" when enabling and Themes sometimes dont work as expected

## 📷 Screenshots
How ziro looks for me with sidebar on but not home(please take a close look at the bottom right too as you can see next to the play line on the right is the song lenght but next to the queue button is the other timer how far into the song we are in): https://cdn.discordapp.com/attachments/842818946243887134/858432509050224671/unknown.png
Trying out a different Theme called Dreary(Deeper) also shows sidebar not working yet being turned on: https://cdn.discordapp.com/attachments/842818946243887134/858435039212470272/unknown.png
A picture of my config file: https://cdn.discordapp.com/attachments/852196550222020651/858688798124408892/unknown.png

**Comment by GangsterFox** [comment]
New update came out and it seems to fix the sidebar and home config not working but Ziro still seems looks to be broken. Nonetheless nice that sidebar and home got fixed

**Comment by khanhas** [comment]
Good to hear. But sorry, I can't help you with other people theme. You might want to contact its author to update it.
