### ISSUE TITLE
Themes not getting applied

### ISSUE THREAD

**Issue by Nickdv9** [khanhas/spicetify-cli#819]
## ℹ Computer information

- Spotify version: 1:1.1.56.595-1 (Latest)
- Spicetify version: v2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Fresh Install 2.5.0
2. Get updated themes from community repo (Just pulled with [this](https://github.com/morpheusthewhite/spicetify-themes/commit/7740b3b14d9f53e3da29f7ce04a98dccc13d2a67) as head)
3. copy themes and follow instructions as mentioned in **[Installation](https://github.com/khanhas/spicetify-cli/wiki/Installation)** and **[Basic Usage](https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage)**
4. Testing with `spicetify config current_theme Gruvbox-Gold`
(All above steps mentioned in SS below)

### ✔️ Expected result

Theme gets applied

### ❌ Actual result

No modifications whatsoever. Sometimes on reapplying getting the "Something went wrong" dialogue. No effect on changing home_config to 0/1, getting the same "Something went wrong" OR no theming on launch.

## 📷 Screenshots
Installation:
![image](https://user-images.githubusercontent.com/17958198/123557970-d3ca9280-d761-11eb-857b-15a7aabd2c69.png)

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/17958198/123558001-fbb9f600-d761-11eb-909d-58173aa7ae01.png)

**Comment by schnensch0** [comment]
AFAIK you pulled the themes for "the old Spotify UI (<v1.1.56) and Spicetify <v2", as written in the 4th line of the README. themes for spicetify  >v2 are kept in the v2 branch

**Comment by luckless8** [comment]
I've been having the exact same issue. I had spicetify running a month ago but had to reinstall my manjaro fresh, now I'm unable to get any themes working other than the default.  I'm certain I have the current theme files as well.

**Comment by khanhas** [comment]
Themes for legacy version are not compatible. Use these from v2 branch:
https://github.com/morpheusthewhite/spicetify-themes/tree/v2
