### ISSUE TITLE
Clicking on genres takes you to home page.

### ISSUE THREAD

**Issue by lemonnuggets** [khanhas/spicetify-cli#820]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Go to search tab.
2. Click on one of the recommended genres.

### ✔️ Expected result

Takes you to a page with playlists and music from that genre.

### ❌ Actual result

Shows the home page.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/63046776/123799607-04e3c800-d906-11eb-94cb-0614a7ef207c.png)
Clicking here ^
![image](https://user-images.githubusercontent.com/63046776/123799709-1cbb4c00-d906-11eb-874d-fb6bf5a98188.png)
Takes me here ^

**Comment by RhapsodySL** [comment]
Confirming this issue.

**Comment by KorayUlusan** [comment]
I confirm this, too.

**Comment by Vismay23** [comment]
confirming this

**Comment by RhapsodySL** [comment]
@khanhas Pinging because this is a relatively major issue that blocks certain functionality of the Spotify app while Spicetify is installed.

**Comment by lor1x** [comment]
Same thing happening in 3 of the PCs where I have Spotify installed, all different OSes and Spotify accounts.

**Comment by luckybuzz** [comment]
Just to add to this thread, I tried disabling all my spicetify Custom Apps and Extensions, and the behaviour described above still happens... so the bug is in spicetify itself, not any of the add-ons.  Thanks!

**Comment by casungo** [comment]
This seems to be resolved I think (at least for me)

**Comment by Fauzaan** [comment]
> This seems to be resolved I think (at least for me)

how do u fix it ?
i still have the problem with spotify version : 1.1.65.643.g2d707698-a spicetify : 2.5.0 (patch 4 from itsmeow)

**Comment by casungo** [comment]
> > This seems to be resolved I think (at least for me)
> 
> how do u fix it ?
> i still have the problem with spotify version : 1.1.65.643.g2d707698-a spicetify : 2.5.0 (patch 4 from itsmeow)

I dont know, it just works 🤔

**Comment by afonsojramos** [comment]
Will close this issue as this has been now completely fixed.
