### ISSUE TITLE
Uneven spacing above [PLAYLISTS] in sidebar since v2.3.0(sidebar config) update

### ISSUE THREAD

**Issue by senntore** [khanhas/spicetify-cli#822]
## ℹ Computer information

- Spotify version: 1.1.55.498.gf9a83c60(flatpak)
- Spicetify version: v2.5.0

## 📝 Provide detailed reproduction steps (if any)

1.Install spicetify-cli v2.30+ for flatpak Spotify
2.Open Spotify
3.Try using sidebar config & restart Spotify

### ✔️ Expected result
Even vertical spacing in sidebar like in default Spotify

### ❌ Actual result
There is little to no vertical space between [PLAYLISTS] (not actual song playlists but the non clickable header)& buttons which are stick to the top(Home, Search, Library, etc)

## 📷 Screenshots
Spotify with spicetify v2.5.0
![Screenshot-2021-07-01](https://user-images.githubusercontent.com/58325574/124063456-8ba4bc00-da50-11eb-968e-83f7e14f6997.png)
Default Spotify
![Screenshot-2021-07-01,09-17-03](https://user-images.githubusercontent.com/58325574/124063482-99f2d800-da50-11eb-86ef-2855e9124104.png)

## Note
Extensions used with the setup: fullAppDisplay.js|keyboardShortcut.js|loopyLoop.js|popupLyrics.js

**Comment by khanhas** [comment]
If you're on Linux, upgrade Spotify to v1.1.56.
