### ISSUE TITLE
Lyrics shows "Something went wrong" page

### ISSUE THREAD

**Issue by syphernl** [khanhas/spicetify-cli#823]
## ℹ Computer information

- Spotify version: 1:1.1.55.498.gf9a83c60
- Spicetify version:  v2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Enable & apply `lyrics-plus`
2. Go to Lyrics in Spotify

### ✔️ Expected result

Lyrics showing up

### ❌ Actual result

A page with
```
Something went wrong, try reloading the page`
```

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/639906/124086315-387f3900-da51-11eb-9b2f-6e4cd4b0d52a.png)

## Background info
When visiting the lyrics page the error console shows this error twice:

```

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at zs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at ra (vendor~xpui.js:29)
    at la (vendor~xpui.js:29)
    at aa (vendor~xpui.js:29)
    at oa (vendor~xpui.js:29)
    at Ds (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at Ts (vendor~xpui.js:29)
    at gs (vendor~xpui.js:29)

```

According to the decoder this is because of:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**Comment by khanhas** [comment]
If you're on Linux, upgrade to v1.1.56

**Comment by syphernl** [comment]
> If you're on Linux, upgrade Spotify to v1.1.56

I am, but unfortunately the latest version in their Debian/Ubuntu repository seems to be 1.1.55. I guess I'll have wait until they publish the new version there then..

**Comment by khanhas** [comment]
Use deb package from Spotify website.

**Comment by syphernl** [comment]
I upgraded to `1:1.1.56.595.g2d2da0de` but it is still failing.

**Comment by XYQuadrat** [comment]
I too have updated to version `1:1.1.56.595.g2d2da0de` but Lyrics still is just a "Something went wrong. Please reload" page for me. I can gather additional debug information if required.

**Comment by r4pid2000** [comment]
Hi, I'm on Windows 10 and just installed spicetify with dribbblish and also getting the "Something went wrong" error with lyrics-plus and reddit.
