### ISSUE TITLE
Settings.spa file missing after Spotify update

### ISSUE THREAD

**Issue by AustrAlienGH** [khanhas/spicetify-cli#824]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.2.7

After updating Spotify to the above version and attempting to inject Spicetify, the settings.spa file gets removed from the Backup folder in the .spicetify directory. Trying to create a new settings.spa file gets that removed too. I'm unable to get the original settings file as it gets permanently deleted on running the `spicetify backup apply` command

## 📷 Screenshots

![error](https://user-images.githubusercontent.com/61350071/124230149-fc7fcd00-db51-11eb-8576-9f2ad9c2e6b1.png)

![image](https://user-images.githubusercontent.com/61350071/124230781-d149ad80-db52-11eb-8ea3-956125d0ad10.png)

**Comment by Stoned-stoner** [comment]
how did you resolve this issue?
