### ISSUE TITLE
Linux KDE Neon; Spicetify not applying "Play with Shuffle+" button but profile still has "Auto Shuffle+" button

### ISSUE THREAD

**Issue by samm-sepi0l** [khanhas/spicetify-cli#825]
## ℹ Computer information

- Spotify version: 1.1.55.498.gf9a83c60 (flatpak install
- Spicetify version:  2.5.0 (linuxbrew install)

## 📝 Provide detailed reproduction steps (if any)

1. … Installed spicetify with linuxbrew
2. Installed spotify with flatpak
3. Added shuffle+.js and fullAppDisplay.js to config
4. Ran `spicetify backup apply`

### ✔️ Expected result

_Full App Display button in top left, Shuffle+ button on right-click, Auto Shuffle+ at profile menu._

### ❌ Actual result

_Full App Display button working, Auto Shuffle+ working, yet right-click "Play with Shuffle+" button is missing_

## 📷 Screenshots

![Screenshot_20210702_153318](https://user-images.githubusercontent.com/48124040/124262085-1ead2700-db21-11eb-98eb-d4adcc21a53d.png)
![Screenshot_20210702_153601](https://user-images.githubusercontent.com/48124040/124262258-574d0080-db21-11eb-9fb1-1929e5f49114.png)

**Comment by khanhas** [comment]
Upgrade Spotify to v1.1.56.
