### ISSUE TITLE
Transferring issue

### ISSUE THREAD

**Issue by kwokke** [khanhas/spicetify-cli#826]
Hi, whenever I kept facing this issue of Transferring user.css whenever I apply backup. it states fatal open c:\User\Kwokk\AppData\Roaming\Spotify\App\zlink\css\user.css :This system cannot find the path

For the multiple times i have reinstalled both spicetify and spotify it stated that the User.css file is missing (i checked on spotify folder) and is wondering how to go about this.

**Comment by khanhas** [comment]
Upgrade spicetify.
