### ISSUE TITLE
Error in Windows 11?

### ISSUE THREAD

**Issue by FKCrew** [khanhas/spicetify-cli#827]
- Spotify version: 1.1.4
- Spicetify version: 2.5.0

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x5909d6]

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/preprocess.Start.func1(0xc0000894d0, 0x2d, 0x0, 0x0, 0x69b3c0, 0xc00022c000, 0xc00008e240, 0x0)
        D:/Code/spicetify-cli/src/preprocess/preprocess.go:64 +0x56
path/filepath.Walk(0xc0000894d0, 0x2d, 0xc000507d10, 0x0, 0x0)
        D:/Program Files/Go/src/path/filepath/path.go:499 +0x8a
github.com/khanhas/spicetify-cli/src/preprocess.Start(0xc00000a450, 0x28, 0x101010101)
        D:/Code/spicetify-cli/src/preprocess/preprocess.go:63 +0x416
github.com/khanhas/spicetify-cli/src/cmd.Backup(0x6952d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/backup.go:61 +0x826
main.main()
        D:/Code/spicetify-cli/spicetify.go:183 +0x5b2

![image](https://user-images.githubusercontent.com/84207879/124355391-25b36280-dc11-11eb-9e81-c35851321c93.png)

**Comment by khanhas** [comment]
1. Minimum Spotify version support is v1.1.56
2. Can't help you with Windows 11.
