### ISSUE TITLE
lyrics-plus: Change font size, [-|+] buttons

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#828]
## 📝 Provide a description of the new feature

It would be nice if you can add a + -  button to change the font size. 
Something like the Firefox [reader view](https://i.imgur.com/HkhBWHg.png) would be nice. Though a simple +- would do the job, too. 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by ririxidev** [comment]
Has been added,
https://github.com/khanhas/spicetify-cli/commit/b83de296b1a42fa250e04c92a1d366dd87558cef,
can be closed.
