### ISSUE TITLE
Cannot open file color.ini

### ISSUE THREAD

**Issue by ten-typek** [khanhas/spicetify-cli#829]
hi, 
I am having this problem. However, color.ini is present in Themes\SpicetifyDefault and I open PowerShell as administrator. Any ideas how to fix this? 
Thanks in advance :) 

![image](https://user-images.githubusercontent.com/80646702/124377807-39f96d00-dcae-11eb-9f75-5836c3764a21.png)

**Comment by CharlieS1103** [comment]
Yeah, that probably means it doesn't exist most of the time, check to see if it does.

**Comment by khanhas** [comment]
Wrong syntax in INI file could lead to that error.

**Comment by Dounial** [comment]
Just open the directory where the color.ini is missing and create a empty color.ini -file,  then it should work again :)
