### ISSUE TITLE
[Windows 10] Cannot locate .exe

### ISSUE THREAD

**Issue by urmilshroff** [khanhas/spicetify-cli#83]
I installed Spotify regularly from their website, but then it auto-updated from the Windows Store. So now it's a Windows Store app and doesn't have a proper .exe which I can link to in `config.ini`, and thus Spicetify doesn't work at all.

What can be done if I use the Windows Store version of Spotify? I tried looking for solutions online but couldn't find any. Thanks in advance.

**Comment by khanhas** [comment]
1. Completely uninstall Spotify.
2. Go to `C:\Program Files\WindowsApps` or `C:\Program Files (x86)\WindowsApps`, find any folder with Spotify in its name and manually delete them.
You might need to change folder permission to have the right to access them.
3. Then use Spotify installer from the website to install non-Windows Store version.
