### ISSUE TITLE
New Releases Tab Loads Continuously

### ISSUE THREAD

**Issue by mrreal100** [khanhas/spicetify-cli#832]
## ℹ Computer information
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.20 GHz
Installed RAM	16.0 GB
Edition	Windows 10 Pro
Version	21H1
Installed on	‎5/‎22/‎2021
OS build	19043.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. … Reinstalled new-releases folder.
2. … Re-ran spicetify config new-releases and spicetify apply
3. … Made sure it was applied in config-xpui

### ✔️ Expected result
Being able to see new releases load.
_What is the expected result of the above steps?_
new-release to load new apps
### ❌ Actual result
Custom app spins and does not do anything.

_What is the actual result of the above steps?_

## 📷 Screenshots
![0704 21 - 11 39 31 AM](https://user-images.githubusercontent.com/86922699/124391123-112ca400-dcbd-11eb-9472-7ee978644c62.png)
_Are there any useful screenshots?_

**Comment by Gobbr** [comment]
Same here
![Spotify_2021-07-08_22-42-40](https://user-images.githubusercontent.com/28529132/124981121-dbc9e280-e03d-11eb-8601-680742cbc4ec.png)

**Comment by ScriptKiddieTutorials** [comment]
been like that since v2 release for me
![image](https://user-images.githubusercontent.com/60780745/125163824-8d455100-e1c1-11eb-9b7c-9d3bb3de917e.png)

**Comment by Gobbr** [comment]
Oh, I get it! 
There is nothing to show if you did not follow any artist. 
I think it would be better to see some kind of message like "Follow artist to see their new releases here".

**Comment by ScriptKiddieTutorials** [comment]
I followed some artists but get the same result.
![image](https://user-images.githubusercontent.com/60780745/126247929-68104aec-263c-4c8c-a5cd-044b51b245ec.png)
![image](https://user-images.githubusercontent.com/60780745/126247970-5ac04f0f-48dd-4056-aaa2-48afeeaa9314.png)

**Comment by marcusrbrown** [comment]
Could this issue be reopened? I have the same issue. When I select New Releases the page loads indefinitely.
