### ISSUE TITLE
Spicetify Wont Apply

### ISSUE THREAD

**Issue by leeprky** [khanhas/spicetify-cli#833]
## ℹ Computer information

- Spotify version:  v1.1.62.583.gdac878ed
- Spicetify version:  v1.1.0
- Windows 11 Insider Build

## 📝 Provide detailed reproduction steps (if any)

1. spicetify config color_scheme SpicetifyDefault
2. spicetify backup
3. spicetify restore backup
3. spicetify apply

### ✔️ Expected result

_What is the expected result of the above steps?_

Restart & Apply Theme

### ❌ Actual result

_What is the actual result of the above steps?_

fatal open C:\Users\leepa\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

## 📷 Screenshots

_Are there any useful screenshots?_

https://imgur.com/a/w1m3Frz

**Comment by khanhas** [comment]
Upgrade spicetify.

**Comment by sufiyaanEX** [comment]
![image](https://user-images.githubusercontent.com/87233670/169637923-39ba5bd3-5c22-4ac4-b1c7-480241f8b3e9.png)
what do i do

**Comment by Psycho-Fan** [comment]
> ![image](https://user-images.githubusercontent.com/87233670/169637923-39ba5bd3-5c22-4ac4-b1c7-480241f8b3e9.png) what do i do

buy premium
