### ISSUE TITLE
FullAppDisplay not working properly on Portrait monitors

### ISSUE THREAD

**Issue by Silverarmor** [khanhas/spicetify-cli#835]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)
Use extension `fullAppDisplay.js`

### ✔️ Expected result
fullAppDisplay works as per a landscape monitor (
![image](https://user-images.githubusercontent.com/23619946/124437278-052f0800-ddcb-11eb-83e5-0012590a5aaa.png)

### ❌ Actual result

Issues at top of screen. See below screenshot.

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/23619946/124437539-47584980-ddcb-11eb-97f2-c3c09433a641.png)

![image](https://user-images.githubusercontent.com/23619946/124437574-4f17ee00-ddcb-11eb-8fdd-7c586f0269b4.png)
![image](https://user-images.githubusercontent.com/23619946/124437590-52ab7500-ddcb-11eb-91fb-cee4fedb2064.png)

**Comment by afonsojramos** [comment]
Still active 👌 But thanks bot! 👀

**Comment by am586390** [comment]
I think I figured out a solution: changing `const blur = 30` to a higher number. `100` was enough on my tablet.

**Comment by TheGeeKing** [comment]
@afonsojramos is it fixed?

**Comment by nodgear** [comment]
> @afonsojramos is it fixed?

Yes: https://i.wisp.run/f/AWQCxY.png

**Comment by TheGeeKing** [comment]
So can be closed, @itsmeow @khanhas
