### ISSUE TITLE
spicetify backup fails

### ISSUE THREAD

**Issue by CryoRenegade** [khanhas/spicetify-cli#837]
## ℹ Computer information

- Spotify version: Latest
- Spicetify version: spicetify v2.2.6

## 📝 Provide detailed reproduction steps (if any)

1. spicetify backup

### ✔️ Expected result
_What is the expected result of the above steps?_
`❯ spicetify backup
spicetify v2.2.6
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting: OK`

### ❌ Actual result
_What is the actual result of the above steps?_
`❯ spicetify backup
spicetify v2.2.6
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
[ 2 / 2 ] loginfatal open C:\Users\jledb\.spicetify\Backup\settings.spa: The system cannot find the file specified.`

## 📷 Screenshots
_Are there any useful screenshots?_
![WindowsTerminal_vwTXmUwAnk](https://user-images.githubusercontent.com/23038070/124490691-a7210700-dd6f-11eb-8286-d6cd03755160.png)

**Comment by khanhas** [comment]
Upgrade spicetify.
