### ISSUE TITLE
Only Discord working everything else Default

### ISSUE THREAD

**Issue by zgast** [khanhas/spicetify-cli#838]
- Spotify version: idk
- Spicetify version: 2.5.0
- OS: Ubuntu 21.04

## Themes
Only Discord theme is working every other theme is the Default theme

## Lyrics:
![](https://i.imgur.com/r1EdSis.png)

**Comment by bustatu** [comment]
Happens to me on Kubuntu 21.04 too.

**Comment by khanhas** [comment]
You can't even bother to find out most essential information that what is your Spotify version. I don't think I want to help you further.
Anyway, upgrade your Spotify to v1.1.56 is only advice I can give with this limited detail.

**Comment by zgast** [comment]
So is there a way to find out the spotify version, there is nothing in the internet, it is the newest version in the apt repository, but there is no way to see the version in the app or I cant find it, there is no help...
