### ISSUE TITLE
Problems with installing in Windows 10

### ISSUE THREAD

**Issue by lionnesquaer** [khanhas/spicetify-cli#84]
Hi everyone!
Im trying to install Spicetify on Windows 10 Last Update 1903
Im run Powershell with Admin rights and try to run command: 
Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
And get error something with link to Internet Explorer install. But.., Windows 1903 doent have internet explorer and i can't install it becouse of IE installation error.
How i can install Spicetify now?

**Comment by khanhas** [comment]
You can just download the script manually and run
```
cat "C:\Link\to\the\script\install.ps1" | Invoke-Expression
```

**Comment by QuantumParadox13** [comment]
when I try to install it that way, this error comes up

Invoke-Expression : At line:1 char:8
+ param (
+        ~
Missing ')' in function parameter list.
At line:1 char:76
+ ... tify-cli-master\spicetify-cli-master\install.ps1" | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingEndParenthesisInFunctionParameterList,Microsoft.PowerShell.Commands.InvokeExpress
   ionCommand

**Comment by khanhas** [comment]
I'm sorry.
It should be
```
Invoke-Expression "C:\Link\to\the\script\install.ps1"
```

**Comment by QuantumParadox13** [comment]
that prompted me on weather to run the script and then this error came up 
```
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At A:\Downloads\spicetify-cli-master\spicetify-cli-master\install.ps1:31 char:26
+   $latest_release_json = Invoke-WebRequest -Uri $latest_release_uri
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

**Comment by Ridham-haru** [comment]
im trying to install the Spicetify in windows 11 
**### **Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:1
+ Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetif ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
   HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
   Shell.Commands.InvokeWebRequestCommand****

**Comment by Cskthegr8** [comment]
Just found out that it is windows defender or your antivirus causing this issue, go there and allow it to download or just disable it for some time while you update! It is quite a common thing to be caught by your antivirus, happens to steam and other applications as well
![image](https://user-images.githubusercontent.com/70256305/212145613-3f8dd9ec-0ae1-4101-8cd4-7204732d171c.png)
