### ISSUE TITLE
Lyrics App

### ISSUE THREAD

**Issue by OhItsTom** [khanhas/spicetify-cli#848]
## ℹ Computer information

- Spotify version: Latest
- Spicetify version: Latest

## 📝 Provide detailed reproduction steps (if any)

1. install application
2. input own token
3. play songs (with shuffle+?)

### ✔️ Expected result

Musix synced lyrics playing consistently on supported songs

### ❌ Actual result

When the lyrics load, they work perfectly, however sometimes they do not show despite having lyrics for the song.

What im thinking is happening, is its taking musix a while to load the token or something, as it only stops working when you go back to library, another playlist ect and then back to lyrics were they dont show for ages. And sometimes songs that should support the lyrics apparently have none. Despite the official musix app recognizing the songs and showing lyrics itself.

## 📷 Screenshots
Working example:
![image](https://user-images.githubusercontent.com/22730962/124845071-d4e39700-df8d-11eb-854e-fb060371bfa1.png)

2 minutes later after going to playlist and back to lyrics:
![image](https://user-images.githubusercontent.com/22730962/124845107-ed53b180-df8d-11eb-9b30-377fa3a9a359.png)

**Comment by OhItsTom** [comment]
Genius works consistently well, so im wondering if its just api issues. Its extremely tempermental...

**Comment by OhItsTom** [comment]
![image](https://user-images.githubusercontent.com/22730962/124922285-41dc4880-dff1-11eb-8413-e321428beb31.png)

**Comment by saxobroko** [comment]
I've found that sometimes 
![image](https://user-images.githubusercontent.com/18757374/125186603-a3f5b180-e26e-11eb-9041-849e29248554.png)
isn't set unless you switch to genius, and back.

**Comment by afonsojramos** [comment]
Closed due to moved topic to #980.
