### ISSUE TITLE
Issue running spicetify backup apply

### ISSUE THREAD

**Issue by RiotDrummer** [khanhas/spicetify-cli#85]
when i run spicetify backup apply i get 
"success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!"

then i get the error 
"fatal remove C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.116.522.0_x86__zpdnekdrzrea0\Apps\about.spa: Access is denied."

**Comment by khanhas** [comment]
Uninstall Spotify Windows store version and use normal version installer downloaded from Spotify website.
