### ISSUE TITLE
 No strip in the player (Dribblish)

### ISSUE THREAD

**Issue by tarmichal** [khanhas/spicetify-cli#852]
## ℹ Computer information

- Spotify version: Latest
- Spicetify version: Latest

## 📝 Provide detailed reproduction steps (if any)

1. Changed the theme to dribblish after installation
2. Runned Spotify
3. Runned the music

### ✔️ Expected result

idk

### ❌ Actual result

The dribblish theme does not show the scroll function to the selected minute, only the song name, album picture, band / artist name, pause / play button, next / previous track button and volume level. Is this a normal problem?

## 📷 Screenshots
![github 2](https://user-images.githubusercontent.com/87128340/124950631-e327c680-e012-11eb-9770-aa9a5b25f925.PNG)

**Comment by OhItsTom** [comment]
https://github.com/morpheusthewhite/spicetify-themes/issues/440#issuecomment-875498498
Possible fix? Similar issue but where his was moved due to scaling yours is seemingly invisible or just offscreen.

Is there any errors by pressing ctrl+shift+I and running spotify from powershell using spicetify apply enable-devtool

**Comment by tarmichal** [comment]
> [morpheusthewhite/spicetify-themes#440 (comment)](https://github.com/morpheusthewhite/spicetify-themes/issues/440#issuecomment-875498498)
> Possible fix? Similar issue but where his was moved due to scaling yours is seemingly invisible or just offscreen.
> 
> Is there any errors by pressing ctrl+shift+I and running spotify from powershell using spicetify apply enable-devtool

Nope

**Comment by LikhithRajT** [comment]
![image](https://user-images.githubusercontent.com/47000780/125593661-6637bc9b-852b-4ff9-9a23-a5b452c6ce61.png)
It works in mine. In the image you sent I'm unable to see the top of the player bar.

**Comment by afonsojramos** [comment]
Either way, this is a bug on a specific theme, not with the cli.
