### ISSUE TITLE
Custom themes not working

### ISSUE THREAD

**Issue by Crylia** [khanhas/spicetify-cli#853]
## ℹ Computer information

- Spotify version: 1.1.55.498.gf9a83c60
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

When ever I set a theme in the config other than SpicetifyDefault it wont load the theme. I installed themes from the spicetify-themes repo inside ~/.config/spicetify/Themes but spicetify wont load them after i hit spicetify apply

```
spicetify v2.5.0
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
success Spotify is spiced up!
```

This is the output, so i dont see any error there.

Inside the Themes folder i have themes as Folders with following structure:

`Themes/BIB-Green/color.ini README.md user.css`

I installed spotify via flatpak and set both paths according to the guide as:

```
spotify_path                  /home/crylia/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/

prefs_path                    /home/crylia/.var/app/com.spotify.Client/config/spotify/prefs

```
I also added write permissions as written in the guide with:

```
sudo chmod a+wr -R ~/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps

sudo chmod a+wr ~/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
```

I'm pretty much out of options by now and i cant find anything on the web regarding my issue.

### ✔️ Expected result

That i see the theme i selected

### ❌ Actual result

The themes wont load

**Comment by paulhersch** [comment]
Issue continues in Spotify 1.1.56.595-1

**Comment by OhItsTom** [comment]
you need to make sure you have a v2 version of the theme, you can get the supported themes here: https://github.com/morpheusthewhite/spicetify-themes/tree/v2

If you already have a v2 theme then feel free to drop my details here

**Comment by Crylia** [comment]
Allright thanks it works now, may i suggest to put a disclaimer in the install section.
