### ISSUE TITLE
Allow sidebar customization

### ISSUE THREAD

**Issue by rien333** [khanhas/spicetify-cli#86]
Not sure if this is within scope, but my spotify use is pretty limited/specific. I don't use playlist basically, and I have no idea what all the rows beneath "YOUR LIBRARY" even mean. I occasionally use the "Home" tab to search for new albums, but I don't know what the "Browse" and "Radio" tabs beneath it do (nor do I want to find out).

Can spicetify remove some of the UI elements/sections of the sidebar? Or better yet (for me at least) hide the whole side bar? I suspect a theme might allow me to do this, but a global setting you can use together with a theme of your liking might be preferable.

**Comment by rien333** [comment]
To hide the sidebar, adding this to `user.css` worked okay (not sure whether this is the best solution):

```
.sidebar {
	width: 0px !important;
	min-width: 0px !important;
	max-width: 0px !important;
	opacity: 0;
}
```

**Comment by khanhas** [comment]
Sorry. I checked the sidebar render code. It's extremely difficult to make all of them customisable.
