### ISSUE TITLE
Audio visualiser option (On fullsappdisplay)

### ISSUE THREAD

**Issue by ohitstom** [khanhas/spicetify-cli#860]
## 📝 Provide a description of the new feature
![image](https://user-images.githubusercontent.com/22730962/125092918-b8e51000-e0c9-11eb-8131-072401c71af8.png)

An option for an audio visualizer which is white, some possible positions for vertical are above.

Could just make the progress bar a visualizer! Would be a real neat feature and i would use fullapp more, because currently i just use a wallpaper engine background just for the visualizer...

And for horizontal below.

![image](https://user-images.githubusercontent.com/22730962/125093210-019cc900-e0ca-11eb-9153-481d03b7964d.png)

**Comment by tacosontitan** [comment]
@OhItsTom when you say "visualizer", do you mean in the *simplistic* <sub>[1]</sub> sense:

![image](https://user-images.githubusercontent.com/65432314/132603889-28fddf8d-07e6-48f7-aace-193b8f3f49ea.png)

Or perhaps the more complex sense:

![image](https://user-images.githubusercontent.com/65432314/132604159-e7f0cfde-cee8-44d9-b71b-f8ca25b9bbff.png)

<sub>1: Simplistic is a relative term in this case, the screenshot provided does add *some* complexity.</sub>

**Comment by ffernn-dev** [comment]
I would say simplistic

**Comment by ffernn-dev** [comment]
Or heck possibly both
