### ISSUE TITLE
Please tell me how will the program update.

### ISSUE THREAD

**Issue by WelkinBunbury** [khanhas/spicetify-cli#862]
I have few questions 
1. What will happen when Spotify is updated to a new version.
2. how will spicetify and its custom theme, extensions and custom apps get updated and what effects they will have.

**Comment by OhItsTom** [comment]
For the most part spotify updates will not effect spicetify, sometimes you will need to re-apply spicetify by going into cmd and typing spicetify apply, however its rare for spicetify to completely stop working. 

After a lot of updates you may need to update spicetify by doing spicetify upgrade in console, and if that doesnt fix it, then you will need to upgrade, however if you google how to stop spotify updating im pretty sure there are way around all your questions.

**Comment by afonsojramos** [comment]
Next time, open this questions in Discussions.
