### ISSUE TITLE
"The system cannot find the path specified" when trying to apply spicetify

### ISSUE THREAD

**Issue by PyDeQ** [khanhas/spicetify-cli#866]
When I try to install spicetify with Powershell on Windows 10 I end up running into the same error again. When applying a theme it only says "fatal open C:\Users\*User*\AppData\Roaming\Spotify\Apps\login\css\user.css: The system cannot find the path specified." 
I reinstalled Spotify (not the Microsoft Store version) and Spicetify multiple times but there's always this error message. I have no idea how to fix this.

**Comment by Rachniotov** [comment]
I had the same error, what I did was:

1. I went to `C:\Users\*User*\AppData\Roaming\Spotify\Apps\login`
2. Created a folder named `css`
3. Run `spicetify apply`

I was facing the same `path not found` error with the zlink folder and I did the same and it is working until now.

**Comment by VolkanKorki** [comment]
I believe you need to use the update command last, so you'd want to use it like this: `spicetify.exe backup apply update`

I noticed I had the same error when I tried to use `spicetify.exe backup update apply`

**Comment by Syridia** [comment]
Exactly the same error here. None of the fixes I've found have worked, and I'm having the issue on 2 computers also.

**Comment by rgarcia7** [comment]
https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-887073051

**Comment by rgarcia7** [comment]
FYI: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-887073051
