### ISSUE TITLE
Not working in Manjaro

### ISSUE THREAD

**Issue by sicr0** [khanhas/spicetify-cli#868]
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2da0de
- Spicetify version: Not printing

## 📝 Provide detailed reproduction steps (if any)

1. Installed spicetify-cli from AUR
2. Run spicetify with -v or --version option
3. Just showing a blank line
4. Also installed a couple themes from morpheus/spicetify-themes, none work when setted

### ✔️ Expected result

First of all, I should see the version number, also the themes should be setted

### ❌ Actual result

No version number nor theme applied

## 📷 Screenshots

![Screenshot_20210710_131227](https://user-images.githubusercontent.com/49662650/125169434-834f2e00-e180-11eb-9e2d-fbc31b3c0489.png)

**Comment by OhItsTom** [comment]
To start with are you using v2 spicetify, the latest spotify, and a v2 theme? Do plugins work at all?

**Comment by sicr0** [comment]
I installed `spotify 1.1.56.595.g2d2da0de` and `spicetify-cli 2.5.0-1` from the AUR, so I guess they are the latest. No theme work at all, also I `chmod`ed Spotify to allow Spicetify to modify it. What do you mean by "plugins"?

**Comment by thedjdoorn** [comment]
Mind you that spicetify v2 only works with spotify v1.1.58 and up, which isn't available for Linux yet. You're also trying to use a v1 theme (Elementary) on >v2 spicetify. So you can try:

- Downgrading spicetify by cd'ing into the `spicetify-cli` directory in your AUR helper's cache and running the follwing:
```bash
git checkout c8b576b6e106cafce49df6f5fe7125da2b4da45e # checks out v 1.2.1
makepkg
sudo pacman -U spicetify-cli-1.2.1-1-x86_64.pkg.tar.zst
```

- Using a v2 theme (check out the v2 branch from morpheusthewhite/spicetify-themes), although I don't think that's going to work

**Comment by sicr0** [comment]
Thanks for the advice, will try it tonight

Il giorno lun 12 lug 2021 alle ore 06:20 David Doorn <
***@***.***> ha scritto:

**Comment by afonsojramos** [comment]
@sicr0 were you able to install Spicetify v1?
