### ISSUE TITLE
bug: adding to queue leads to staying in the old playlist

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#871]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: [prints a blank line idk, fresh installed a week ago or so.]

## 📝 Provide detailed reproduction steps (if any)

1. search for a playlist
2. open a playlist  _(p1)_ 
2. click a song to play
3. go to another playlist _(p2)_ in the same search and add to queue
4. skip current playing song (now playing the song in the queue)
5. click on the album icon bottom left to go to _p2_

### ✔️ Expected result

The second playlist (p2) should open 

### ❌ Actual result

The first playlist (p1) opens

**Comment by afonsojramos** [comment]
This is expected behavior from spotify, not really understanding the problem here.
