### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Luke-99870** [khanhas/spicetify-cli#874]
## ℹ Computer information

- Spotify version:  Latest
- Spicetify version: Latest 

## 📝 Provide detailed reproduction steps (if any)

1. Installed latest versions of spicetify & spotify
2. Ran commands stated in basic guide
3. Upon running any command the error generated is `Transferring user.css:
fatal open C:\Users\houst\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.`

### ✔️ Expected result

Spicetify should work as intended allowing me to apply themes.

### ❌ Actual result

Transferring user.css:
fatal open C:\Users\houst\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

This prevents any commands being ran and/or themes being applied.

**Comment by palerski** [comment]
same issue

**Comment by lbibass** [comment]
same issue.

**Comment by mertgoksel** [comment]
same here

**Comment by quinnsweeney11** [comment]
Me too :(

**Comment by rgarcia7** [comment]
FYI: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-887073051

**Comment by TheGeeKing** [comment]
Hi @Luke-99870,

Do you still encounter this issue?
If so, please provide more information like the version of Spotify and Spicetify that you are using and not just "Latest" as it doesn't help. Also provide more info on the command that you ran by posting them and don't hesitate to add some screenshots it can always help. Your config file will also be needed to understand more precisely the problem.

**Comment by Luke-99870** [comment]
Hi!

Yeah still getting the error.

Spotify version: 1.1.66.580.gbd43cbc9
Spicetify Version: 2.6.0

[config.txt](https://github.com/khanhas/spicetify-cli/files/7086496/config.txt)

**Comment by TheGeeKing** [comment]
Hi,

Two points :

1. Your Spotify version is not supported by Spicetify for the moment
2. Spicetify isn't correctly installed

i will list you what you need to do

to fix 1. :

  If on you are on Windows :
  
  Block updates :
  del %localappdata%\Spotify\Update
  
  mkdir %localappdata%\Spotify\Update
  
  icacls %localappdata%\Spotify\Update /deny "%username%":D
  
  icacls %localappdata%\Spotify\Update /deny "%username%":R
  
  Rollback to 1.1.65.643 :
  https://www.filepuma.com/download/spotify_1.1.65.643-29529/
  For Mac users :
  
  Block updates :
  
  In the Application folder, right-click on the Spotify app and choose 'Get Info'
    
  in the 'Get info' window, make sure you check 'Locked', right at the top.
    
  Rollback to 1.1.59.714 (maybe newer versions work but I don't know so say it if you can try it) :
  https://www.filepuma.com/download/spotify_1.1.59.714-28782/

to fix 2. :

uninstall completely Spicetify by deleting spicetify-cli and .spicetify folders

install spicetify using `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`

I hope I have helped

**Comment by Luke-99870** [comment]
> Hi,
> 
> Two points :
> 
> 1. Your Spotify version is not supported by Spicetify for the moment
> 2. Spicetify isn't correctly installed
> 
> i will list you what you need to do
> 
> to fix 1. :
> 
> If on you are on Windows :
> 
> Block updates :
> del %localappdata%\Spotify\Update
> 
> mkdir %localappdata%\Spotify\Update
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":D
> 
> icacls %localappdata%\Spotify\Update /deny "%username%":R
> 
> Rollback to 1.1.65.643 :
> https://www.filepuma.com/download/spotify_1.1.65.643-29529/
> For Mac users :
> 
> Block updates :
> 
> In the Application folder, right-click on the Spotify app and choose 'Get Info'
> 
> in the 'Get info' window, make sure you check 'Locked', right at the top.
> 
> Rollback to 1.1.59.714 (maybe newer versions work but I don't know so say it if you can try it) :
> https://www.filepuma.com/download/spotify_1.1.59.714-28782/
> 
> to fix 2. :
> 
> uninstall completely Spicetify by deleting spicetify-cli and .spicetify folders
> 
> install spicetify using `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`
> 
> I hope I have helped

Thank you, very detailed :)

Should i uninstall my current build of spotify first?

**Comment by TheGeeKing** [comment]
Normally, no need for that, Spotify is installed over.

**Comment by Luke-99870** [comment]
Brilliant.

**Comment by Luke-99870** [comment]
![image](https://user-images.githubusercontent.com/17953963/131571253-c7741e93-6bf0-494c-a269-53c35ddfe20b.png)
Does this look right for fix 1

**Comment by Luke-99870** [comment]
![image](https://user-images.githubusercontent.com/17953963/131571426-67918e03-6ed6-41ec-8682-c500a9abb7a5.png)
How does this look for fix 1?

**Comment by TheGeeKing** [comment]
Good! You have locked the Spotify "Update" folder so it doesn't update at restart

**Comment by Luke-99870** [comment]
Awesome! Reran the commands using "%username%" and also rolled back spotify. Also installed the command via powershell. Shoud i now follow the basic installation guide?

**Comment by TheGeeKing** [comment]
You should know be able to follow those steps : https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage

Let me know how it is working out :)

**Comment by Luke-99870** [comment]
Ran those commands and got this error

`Transferring user.css:
fatal open C:\Users\houst\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.`

:(

**Comment by TheGeeKing** [comment]
Which command and config file please

**Comment by Luke-99870** [comment]
[config.txt](https://github.com/khanhas/spicetify-cli/files/7086718/config.txt)

Command: "spicetify"

**Comment by TheGeeKing** [comment]
Can you send me screenshots of your :

1. Spotify folder
2. Spotify\Apps
3. Spotify\Apps\zlink
4. Spotify\Apps\zlink\css

**Comment by Luke-99870** [comment]
![image](https://user-images.githubusercontent.com/17953963/131582902-79bbf4f5-1fd5-4a9a-ab31-d42c7c2ec44a.png)
![image](https://user-images.githubusercontent.com/17953963/131582909-de6d32b7-8b12-40ed-b40c-f95512fdab0f.png)
![image](https://user-images.githubusercontent.com/17953963/131582914-6678d23f-197a-4d1b-918c-ba1839b61723.png)
Sadly i have no CSS folder

**Comment by Luke-99870** [comment]
Hi @TheGeeKing I have tried to reinstall but still no joy!

**Comment by TheGeeKing** [comment]
Sorry to hear that. Your issue has been highlighted and will be followed up shortly.

**Comment by Luke-99870** [comment]
Thank you :)

**Comment by afonsojramos** [comment]
@Luke-99870 Can you upgrade and try again?

**Comment by Luke-99870** [comment]
Hi @afonsojramos

I've reinstalled spotify and spicetify and get the folllowing error `fatal open C:\Users\houst\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.
PS C:\Users\houst>`

**Comment by TheGeeKing** [comment]
Did you completely removed spicetify? There is a .spicetify folder and a spicetify-cli folder. https://github.com/khanhas/spicetify-cli/issues/751#issuecomment-859785621

**Comment by Luke-99870** [comment]
Yep, removed both. I can try again if worthy?

**Comment by TheGeeKing** [comment]
Yeah maybe. If it doesn't work, as I said this issue is being monitored closely and we will do our best to solve it. Afonso, itsmeow or Charlie can maybe help you more than me.

**Comment by Luke-99870** [comment]
Yeah I hope so. Been trying to fix it for a few months but it sadly never happened. Spicetify looks amazing too! Real bummer.

**Comment by Luke-99870** [comment]
Hi @TheGeeKing @afonsojramos @itsmeow @CharlieS1103 (Hope i have tagged all relevant parties)

I have reinstalled spotify & spicetify and can confirm this is as far as i get.

![image](https://user-images.githubusercontent.com/17953963/132106737-db40eea7-8231-4705-a017-f2c65a63d9d9.png)

**Comment by CharlieS1103** [comment]
> Hi @TheGeeKing @afonsojramos @itsmeow @CharlieS1103 (Hope i have tagged all relevant parties)
> 
> 
> 
> I have reinstalled spotify & spicetify and can confirm this is as far as i get.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/17953963/132106737-db40eea7-8231-4705-a017-f2c65a63d9d9.png)
> 
> 

You installed the oldest version of spicetify somehow.

**Comment by Luke-99870** [comment]
I'm actually mildly impressed! Could you copy paste the correct command please.

**Comment by CharlieS1103** [comment]
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh

**Comment by Luke-99870** [comment]
On Windows so its not working mate. I was using the invoke commands. Is there a workaround to use curl? PS C:\Users\houst> curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
sh : The term 'sh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Luke-99870** [comment]
> curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh

![image](https://user-images.githubusercontent.com/17953963/132108755-57900d06-7f1b-409b-8bfd-882947ce1df5.png)
heres a better screenshot if useful

**Comment by CharlieS1103** [comment]
Oh thought you were on linux mb, just use the windows install command in the installation section of the wiki

**Comment by CharlieS1103** [comment]
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

**Comment by Luke-99870** [comment]
Hiya mate @CharlieS1103 

Got hit with this once again haha. (Complete log)

![image](https://user-images.githubusercontent.com/17953963/132140226-2656b2ff-2401-412e-ad8b-f76ee840273e.png)

**Comment by TheGeeKing** [comment]
Hi,

Found some past issues similar to you:

https://github.com/khanhas/spicetify-cli/issues/503

https://github.com/khanhas/spicetify-cli/issues/44

Try: `spicetify backup apply` maybe it will works or follow the links I posted.

**Comment by Luke-99870** [comment]
> Hi,
> 
> Found some past issues similar to you:
> 
> #503
> 
> #44
> 
> Try: `spicetify backup apply` maybe it will works or follow the links I posted.
> 
> https://spectrum.chat/spicetify/general/fatal-error-github-issue-repost~95a8ca62-95a6-494c-9811-530991a2b2a1

Hiya,

Yeah Tried it all. Sadly i cannot escape this (below). Something is stopped these app things getting installed and its really doing my heading haha :( 

![image](https://user-images.githubusercontent.com/17953963/132140645-f62bba2d-cdb8-4bce-9a36-38e310edc842.png)

**Comment by CharlieS1103** [comment]
> Hiya mate @CharlieS1103 
> 
> 
> 
> Got hit with this once again haha. (Complete log)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/17953963/132140226-2656b2ff-2401-412e-ad8b-f76ee840273e.png)
> 
> 
Still on wrong version somehow, try fully deleting and reinstalling

**Comment by TheGeeKing** [comment]
@Luke-99870,

In PowerShell:

`cd ~`
`rm -r spicetify-cli`
`rm -r .spicetify`

Should work.

**Comment by itsmeow** [comment]
What is the output of `where.exe spicetify`?

**Comment by Luke-99870** [comment]
@TheGeeKing @itsmeow @CharlieS1103 Hi Guys, These are all the commands you listed. I can confirm I've removed .spicetify and Spicetify-CLI

![image](https://user-images.githubusercontent.com/17953963/132198725-70cb3355-cfaa-402e-b882-41352e82ec87.png)

**Comment by TheGeeKing** [comment]
What is the bin folder?

**Comment by Luke-99870** [comment]
![image](https://user-images.githubusercontent.com/17953963/132200057-24b764b5-aa72-4bf0-ae8f-cae7c37fbdad.png)

Not too sure. It seems to be remnants of an old copy maybe? Do you think its worth deleting and reinstalling spicetify?

**Comment by TheGeeKing** [comment]
Yep because your spicetify always run an older version of it and it seems that the Spicetify that you are running was hidden in this folder and the one running when making your commands

**Comment by Luke-99870** [comment]
Holy Shit mate! I'm at a complete loss for words. Its worked!

![image](https://user-images.githubusercontent.com/17953963/132202168-162db857-7693-4465-a3f1-c87616de4f70.png)

Absolutely awesome! Thank you so much

**Comment by TheGeeKing** [comment]
Thanks @itsmeow will remember this command for next users that has similar problems.

Glad we finally helped.

**Comment by Luke-99870** [comment]
Massive thanks to everyone that's helped! Yall are awesome!
