### ISSUE TITLE
Package version not same as the one I installed

### ISSUE THREAD

**Issue by Rachniotov** [khanhas/spicetify-cli#875]
## 📝 Provide detailed reproduction steps (if any)

1. If you have spicetify installed, delete .spicetify dir from your User's folder.
2.  Run `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`
3. Notice that it says `DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v2.5.0/spicetify-2.5.0-windows-x64.zip > OK` (notice the version)
4. Run `spicetify -v` for checking version

### ✔️ Expected result

The installed package version should match the version i'm trying to install.

### ❌ Actual result

It shows that it is downloading **v2.5.0** but the installed version is **1.1.0**

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/71971848/125233119-92a6b680-e2fb-11eb-8afc-3b249ad3500a.png)

**Comment by afonsojramos** [comment]
I'd suggest deleting the folder where Spicetify is installed and retrying!
