### ISSUE TITLE
ERROR cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#881]
## ℹ Computer information

- Spotify version: latest
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. let Spotify download the newest version itself
2. close Spotify
3. open PowerShell
4. run `spicetify backup apply`

### ✔️ Expected result

_Backup file, apply, and open spiced up Spotify as usual_

### ❌ Actual result

_Error (Included in screenshot)_

### Screenshots
![image](https://user-images.githubusercontent.com/81705406/125326741-5b8ed000-e310-11eb-9393-f9ef57d9b67b.png)

**Comment by afonsojramos** [comment]
Duplicate of #845
