### ISSUE TITLE
Blank Spotify UI shown after applying Spicetify commands

### ISSUE THREAD

**Issue by theman122** [khanhas/spicetify-cli#882]
Every time I apply the Spicetify code in Powershell, it just turns Spotify into a blank slate. It makes Spotify an obsolete void and I have reinstalled Spotify numerous times and redone the line of code, which has worked fine before, but now it just shows up blank.
![image](https://user-images.githubusercontent.com/73348655/125349344-11631a00-e323-11eb-87bb-14179c4757fb.png)

**Comment by complex-hub** [comment]
This is happening due to a new Spotify update. You can downgrade your app version so that spicetify works again, https://github.com/khanhas/spicetify-cli/issues/845 has links for older (and compatible) Spotify versions.

**Comment by MarHelmer** [comment]
If it helps, the CLI spits out an error message:

> Applying additional modifications:
> error Cannot find symbol for Custom app React symbols

I assume that this will be fixed by a hotfix from you, but until then I'll downgrade.  Thanks.
