### ISSUE TITLE
Can't set any theme

### ISSUE THREAD

**Issue by marbinuwusito** [khanhas/spicetify-cli#883]
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2a0de
- Spicetify version: I can't get the version with the command spicetify -v or spicetify --version

## 📝 Provide detailed reproduction steps (if any)

1.I made the steps to get the default spicetify theme (white with red)
2. when i set the pywal theme for example and set spicetify apply the results is the default spotify theme

### ✔️ Expected result
get any theme or pywal theme working

### ❌ Actual result

get the default spotify theme

## 📷 Screenshots

![Screenshot_2021-07-12_16-29-19](https://user-images.githubusercontent.com/72583007/125363741-6a847b00-e32e-11eb-94d6-9b45fd177e0a.png)
![Screenshot_2021-07-12_16-29-55](https://user-images.githubusercontent.com/72583007/125363745-6e180200-e32e-11eb-92bc-642484cecf9d.png)

**Comment by uzair-ali10** [comment]
I'm facing the same issue initially Spotify launches with spicetify default theme which is that orange and white and when I close the window and reopen it Spotify launches with its default theme and I cant set any theme 
I'm Also on Linux :)

**Comment by marbinuwusito** [comment]
> I'm facing the same issue initially Spotify launches with spicetify default theme which is that orange and white and when I close the window and reopen it Spotify launches with its default theme and I cant set any theme
> I'm Also on Linux :)

oh man idk what to do :( before i was using manjaro and worked fine, now im with arch linux in a fresh installation and i have this inssue :(

**Comment by uzair-ali10** [comment]
@marbinuwusito 
It seems that spicetify is broke now coz there are lots of issues opening on this same topic

**Comment by TyphoonTeaser** [comment]
@marbinuwusito 
#868 Same issue
Spicetify only works with spotify v1.1.58+ Also the theming file format and variables changed for spicetify v2

Please downgrade your spicetify until Spotify on linux get's updated and pick of the new themes when you do
For pywall you will have to update the way color schemes variables are used, you can find reference on [Customization](https://github.com/khanhas/spicetify-cli/wiki/Customization) and spicetify v2 [themes as examples](https://github.com/morpheusthewhite/spicetify-themes/tree/v2)

**Comment by marbinuwusito** [comment]
> @marbinuwusito
> #868 Same issue
> Spicetify only works with spotify v1.1.58+ Also the theming file format and variables changed for spicetify v2
> 
> Please downgrade your spicetify until Spotify on linux get's updated and pick of the new themes when you do
> For pywall you will have to update the way color schemes variables are used, you can find reference on [Customization](https://github.com/khanhas/spicetify-cli/wiki/Customization) and spicetify v2 [themes as examples](https://github.com/morpheusthewhite/spicetify-themes/tree/v2)

Thanks my man, I installed spicetify legacy and now works c:

**Comment by uzair-ali10** [comment]
@marbinuwusito 
Can U tell me your spotify and spicetify version and also the theme ur using currently
And did u  have to reinstall both spotify and spicetify ?

**Comment by marbinuwusito** [comment]
> @marbinuwusito
> Can U tell me your spotify and spicetify version and also the theme ur using currently
> And did u have to reinstall both spotify and spicetify ?

I use spotify ver 1.1.56 from AUR and now spicetify legacy and pywal theme
