### ISSUE TITLE
Spotify doesn't function with spicetify on

### ISSUE THREAD

**Issue by 6K6666** [khanhas/spicetify-cli#885]
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. install spicetify
2. backup
3. apply theme

tried so far: 

reinstalling spotify and doing the 2nd thing in faq

### ✔️ Expected result

Spicetify themes spotify properly

### ❌ Actual result

Blank spotify window with spicetify on, but when spicetify is removed spotify works again

## 📷 Screenshots

https://voided.dev/cdn/POWA6/garUDOYE21.png

**Comment by Rachniotov** [comment]
Can you show what is in the console and the elements tab?

**Comment by R4ver** [comment]
Experiencing the same issue here.
Nothing is printed to the console, let alone the elements tab, just completely blank.

Simple restore makes everything working again

**Comment by AntServiceApps** [comment]
Same issue as #845, it's due to the last update.
