### ISSUE TITLE
Themes aren't being apply

### ISSUE THREAD

**Issue by uzair-ali10** [khanhas/spicetify-cli#888]
- Spotify version: 1.1.55.498.gf9a83c60,
- Spicetify version: v2.5.0

Spicetify is installed properly but themes aren't being applied 
But however, when  I initially ran `spicetify backup apply enable-devtool`  during installation Spotify launched with the default theme of spicetify 
and then when I closed the window and reopened it spotify launches with its default theme.

 I reinstalled both Spotify and spicetify and still the same issue. I'm attaching few useful screenshots below

OS: Elementry OS (Based On Ubuntu 18.04)
Spotify-client is installed from the official site, not from snap or flappattak
![Screenshot from 2021-07-13 17-16-24](https://user-images.githubusercontent.com/72073401/125447368-68721fab-60e4-4f27-9273-d8009fff1238.png)
---
![Screenshot from 2021-07-13 17-15-52](https://user-images.githubusercontent.com/72073401/125447384-bd97790d-7c62-460b-b53e-bce2b1ad0f2b.png)
---
![Screenshot from 2021-07-13 17-15-27](https://user-images.githubusercontent.com/72073401/125447427-5f618aaa-21e8-47cb-b36d-df95ebb0e3ab.png)

---
![Screenshot from 2021-07-13 17-35-05](https://user-images.githubusercontent.com/72073401/125448733-0f4f5e43-b559-4b9e-a05e-a45068448241.png)

Even after all these themes aren't being applied :/

**Comment by uzair-ali10** [comment]
@khanhas
Can u please help me out :(

**Comment by TyphoonTeaser** [comment]
#868 Same issue
Spicetify only works with spotify v1.1.58+ Also the theme you are applying isn't compatible with spicetify v2+
Please downgrade your spicetify until Spotify on linux get's updated and pick of the new themes when you do

**Comment by uzair-ali10** [comment]
@TyphoonTeaser 
So Should I Downgrade my spicetify to spicetify V1?

**Comment by afonsojramos** [comment]
@uzair-ali10 you can find it here: https://github.com/khanhas/spicetify-cli/wiki/Installation#legacy-spotify

**Comment by uzair-ali10** [comment]
@TyphoonTeaser 
![Screenshot from 2021-07-15 23-24-22](https://user-images.githubusercontent.com/72073401/125834720-b21bcb56-6812-41c5-b353-c33170eaacc3.png)
All in vain Still spotify have its default theme

**Comment by TyphoonTeaser** [comment]
@uzair-ali10 Sorry, I miss phrased that last part.（；^ω^）
I meant, update to one of the new themes when you are able to update spotify and spicetify v2. You should keep using the theme you were using (Otto) until then.

**Comment by uzair-ali10** [comment]
@TyphoonTeaser 
`You should keep using the theme you were using (Otto) until then` ??
Even if I apply otto spotify still remains in its default theme

**Comment by uzair-ali10** [comment]
Thanks, It worked 
I've used `Spotify version 1.1.55.498.gf9a83c60`  and `spicetify v1.2.1` along with [legacy](https://github.com/morpheusthewhite/spicetify-themes/tree/legacy) themes
