### ISSUE TITLE
Why does my spotify look like this after installing?

### ISSUE THREAD

**Issue by Makzwell** [khanhas/spicetify-cli#89]
This issue is with the rain meter installation. Sorry, I’m a very casual github user and I haven’t looked into the issue too too much, just wondering if anyone knows why my spotify looks very basic? https://gyazo.com/d42d708c9eaf8354da3e7b7f159743fc

**Comment by khanhas** [comment]
Rainmeter Spicetify is no longer supported. Please reinstall spotify and try:
https://github.com/khanhas/spicetify-cli/wiki/Installation#windows-pre-built
