### ISSUE TITLE
Screen turns to grey after applying backup, and now it won't start up. [I used Powershell for this]

### ISSUE THREAD

**Issue by heyimnikolai** [khanhas/spicetify-cli#891]
## ℹ Computer information

- Spotify version: 1.1.63.568 (I think.)
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Tried restoring backup
2. Reapplied 
3. It still won't launch.

### ✔️ Expected result

_Would launch with no issues at all so that I can use WebNowPlaying for Rainmeter skins._

### ❌ Actual result

_After applying, nothing happened. It says that it's finished applying, but not anymore. Only thing it got me was an error for not finding symbol for custom app React symbols. And then, boom. Grey screen._

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/40872848/125472863-d8ddc018-9cd4-4f9c-8fa1-a334ae7067ec.png)

![image](https://user-images.githubusercontent.com/40872848/125473543-81cf0b24-8203-4e23-ab36-fa5de954a3ee.png)

**Comment by Terrain2** [comment]
I'm getting a similar issue, although my Spotify works, i'm getting the same error in the console when running ``spicetify apply`` and a similar result (but colored differently) when running ``spicetify auto``. Strangely enough, your screenshot has no stack trace, but my output has one:

```
goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc000834000, 0x1aaa1f, 0x1aaa1f, 0xc000834000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0000c6fc0, 0x3a, 0xc0006879d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0000c6fc0, 0x3a, 0xc000104280, 0x3, 0x4, 0xc0000a6780, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000c2660, 0x2d, 0xc000104280, 0x3, 0x4, 0xc0000a6780, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0xe652d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
```
I don't have a ``D:\`` drive, so i can only assume these paths are from the original environment my version of spicetify was built in.

Here's the full output as shows up in my terminal:

![WindowsTerminal_0LtfSdNHG6](https://user-images.githubusercontent.com/37938646/125486295-b818501c-eeba-4b60-b126-44f7d739245c.png)

I also got the same error when running ``spicetify restore backup`` or ``spicetify restore``. ``spicetify auto`` did run a couple times with no errors but leaves Spotify as an empty window, but just as i was writing this and made sure to double-check that, it also encountered the same error.

I also have spotify version ``1.1.63.568`` and spicetify ``v2.5.0``

**Comment by Rachniotov** [comment]
#845 you might want to check this out.

**Comment by cykopvth** [comment]
I have the same problem and versions of spotify and spicetify, really hope this issue is sorted
