### ISSUE TITLE
Themes not applying

### ISSUE THREAD

**Issue by Miyazono1** [khanhas/spicetify-cli#894]
## ℹ Computer information

- Spotify version: 1.1.59.714
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. apply spicetify
2. change current theme
3. reapply spicetify

### ✔️ Expected result

the selected theme will be applied

### ❌ Actual result

spotify default theme is what shows

i've seen multiple other people with this issue, so i'm just adding mine in to show it's a real issue, not a fluke.

**Comment by uzair-ali10** [comment]
Looks like spicetify is now broke, I'm also facing this very same issue
