### ISSUE TITLE
error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini

### ISSUE THREAD

**Issue by Papol56** [khanhas/spicetify-cli#898]
## ℹ Computer information

- Spotify version: Latest version
- Spicetify version: V2.5

When I paste the pastebin code into the PowerShell while using administrative permissions, it gives me this error code at the end once I am finished. I have uninstalled and reinstalled the browser version of spotify several times to make sure that it was not the issue. If I try and skip the step and load dribbblish it will still give me the error code "error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini" in PowerShell. I am not sure how to manually set the path in PowerShell. Any help would be much appreciated

**Comment by CharlieS1103** [comment]
Yeah just open the config-xpui.ini file and change it there, or use "spicetify config spotify-path [path]"

**Comment by PAI5REECHO** [comment]
> or use "spicetify config spotify_path [path]"

That doesn't work though, in order to use `spicetify config` you must have `spotify_path` already set

**Comment by AmeLooksSus** [comment]
I found my config-xpui.ini file in %APPDATA%\spicetify

**Comment by xvolare** [comment]
~AppData\Roaming\spicetify 
you can find the ini file and add path to it

**Comment by SayanMondal01** [comment]
can anyone please improvise in details ?

**Comment by filintodelgado** [comment]
This issue happened to be but it was because I installed Spotify from Microsoft Store and because of this Spicetify couldn't detect Spotify path.

Download the [package](https://download.scdn.co/SpotifySetup.exe) from Spotify's website and install manually.

**Comment by YatherGamms** [comment]
> This issue happened to be but it was because I installed Spotify from Microsoft Store and because of this Spicetify couldn't detect Spotify path.
> 
> Download the [package](https://download.scdn.co/SpotifySetup.exe) from Spotify's website and install manually.

Yes, it worked, thanks !

**Comment by amiralishoja** [comment]
> This issue happened to be but it was because I installed Spotify from Microsoft Store and because of this Spicetify couldn't detect Spotify path.
> 
> Download the [package](https://download.scdn.co/SpotifySetup.exe) from Spotify's website and install manually.

it worked for me too, thanks !
