### ISSUE TITLE
Spotify wont start after last update

### ISSUE THREAD

**Issue by Eden333** [khanhas/spicetify-cli#899]
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0 

## 📝 Provide detailed reproduction steps (if any)

1. I see my Rainmeter doesn't show my current song anymore
2. I reinstall Spictify
3. Spotify only gives black window

### ✔️ Expected result

_What is the expected result of the above steps?_
It should work normally

### ❌ Actual result

_What is the actual result of the above steps?_
It doesn't work anymore

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by TyphoonTeaser** [comment]
@Eden333  Could you give more information like:
Rainmeter skin settings (in the case it has settings you input)
Spicetify settings
Console output when installing/applying spicetify

**Comment by Ankidote1422** [comment]
I believe his console output would look something similar to this
![image](https://user-images.githubusercontent.com/55636005/125719053-4e4dee4b-62a0-4674-9d84-b67d60880ccd.png)

**Comment by Ankidote1422** [comment]
I believe his console output looked something like this
![image](https://user-images.githubusercontent.com/55636005/125719160-1f5affed-c11b-404b-a09c-893c869a2911.png)

**Comment by TyphoonTeaser** [comment]
@Ankidote1422 
The issue "Cannot find symbol for Custom app React symbols" is being discussed on issue #845 
Will probably be worked out on the next spicetify update, there's a possible fix on a pull request.
You can downgrade spotify to version `1.1.62.583.gdac868ed-a` to solve it for now

**Comment by afonsojramos** [comment]
@Eden333 if this issue is unrelated to #845 please create a new issue with more information, thanks!
