### ISSUE TITLE
Won't load after reboot

### ISSUE THREAD

**Issue by Funeoz** [khanhas/spicetify-cli#90]
So I installed Spicetify with Google Theme without any problems then I turned off my computer. Next day, I turned it on and when I launch Spotify, I just see the default grey background and the title bar. Nothing is loading. When I launch spotify from the command line, I get :

> [1013/195925.058405:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

OS: Kubuntu 19.04
Kernel : 5.0.0

**Comment by khanhas** [comment]
That error has nothing to do with Spicetify.
Try reinstall Spotify and try `spicetify backup apply` again.

**Comment by Funeoz** [comment]
Ok, I will try that.
