### ISSUE TITLE
Lyrics+ margins change

### ISSUE THREAD

**Issue by Horse-5-333** [khanhas/spicetify-cli#901]
## ℹ Computer information

- Spotify version: 1.1.62.583
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Play a song with synced lyrics uploaded

### ✔️ Expected result

The lyrics play centered or aligned

### ❌ Actual result

As the song plays, the lyrics jump around from left to right, for seemingly no reason

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/69611823/125903966-39b1c5d2-c86f-49af-8e7b-02c37054ebd2.png)

![image](https://user-images.githubusercontent.com/69611823/125904017-ff98161e-76a7-4771-9f25-c2b7a3c78d87.png)

**Comment by afonsojramos** [comment]
This is not exactly a bug, but it is easily fixable.
Would you guys prefer centered or fixed to the left?

### Centered
![centered](https://user-images.githubusercontent.com/19473034/134664272-bbdd5102-9ff0-4257-aa49-93afff023a3c.png)
### Left aligned
![left aligned](https://user-images.githubusercontent.com/19473034/134664419-1e1e2be9-f953-4ad5-b05d-efa068432a4e.png)

**Comment by itsmeow** [comment]
@afonsojramos Add it to the lyrics plus configuration. Popup has a similar option.

**Comment by afonsojramos** [comment]
@itsmeow yep, that's what I said in Discord! On it!
