### ISSUE TITLE
'Installing Spotify...' after PC restart

### ISSUE THREAD

**Issue by theman122** [khanhas/spicetify-cli#902]
I recently got Spicetify and it has been great. Love everything about it because I really hated the way Spotify normally looked. I have a problem, though. Everytime my PC shuts down or restarts... when I load up Spotify I believe it automatically updates and goes back to how it was before. I constantly have to change it back everytime I start up my PC and I was wondering how to fix this. I did some things I saw online but none really provided an actual fix. Is there something I can do?

**Comment by afonsojramos** [comment]
Everytime Spotify updates you need to run `spicetify backup apply`. But Spotify shouldn't be updating that frequently, but I suppose they have been launching a lot of updates recently.
