### ISSUE TITLE
Error on Installing

### ISSUE THREAD

**Issue by BarisBayraktar** [khanhas/spicetify-cli#906]
Can anyone help with this?
![Screenshot 2021-07-17 151235](https://user-images.githubusercontent.com/14079839/126036559-699a7599-f186-46f3-bdf4-845bb4fab9a3.png)

**Comment by gazzover67** [comment]
Write in the specified file the path to the prefs file.
Example: https://fpic.in/E8SqaXO

**Comment by BarisBayraktar** [comment]
Now says this:  
```
PS C:\Users\sbayr> spicetify apply
spicetify v2.5.0
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!
PS C:\Users\sbayr>
```

**Comment by gazzover67** [comment]
Error spotify update, downgrade

**Comment by itay10000** [comment]
> Error spotify update, downgrade

how do I downgrade?

**Comment by ScottyHoover** [comment]
> how do I downgrade?

use this link to downgrade
https://spotify.en.uptodown.com/windows/download/3764443
#845 for more info
