### ISSUE TITLE
[Lyrics+] Something went wrong; Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by VottusCode** [khanhas/spicetify-cli#907]
## ℹ Computer information

- Spotify version: 1:1.1.55.498.gf9a83c60 (according to apt)
- Spicetify version: 2.5.0
- OS: Ubuntu 20.04

## 📝 Provide detailed reproduction steps (if any)

1. Click the lyrics tab
2. "Something went wrong"

### ✔️ Expected result

I can see the lyrics of the currently playing song.

### ❌ Actual result
```js
xpui.js:10 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at zs (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at ra (vendor~xpui.js:29)
    at la (vendor~xpui.js:29)
    at aa (vendor~xpui.js:29)
    at oa (vendor~xpui.js:29)
    at Ds (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at Ts (vendor~xpui.js:29)
    at gs (vendor~xpui.js:29)
```

## 📷 Screenshots
![obrazek](https://user-images.githubusercontent.com/53915302/126036105-36cedc13-70de-4fdd-9996-f9989fffc180.png)

**Comment by afonsojramos** [comment]
Linux is still not using Spotify's updated API, therefore you must use Spicetify v1. Let me know if you have any trouble!

**Comment by VottusCode** [comment]
Okay, I'll try. God damnit Spotify :sweat:

**Comment by VottusCode** [comment]
Why close this? The issue still stands for Linux users, there should be some workaround for the old API except for downgrading spicetify, right?

**Comment by afonsojramos** [comment]
@VottusCode unfortunately, Spicetify v2 will only support the new Spotify API, if you are using an old version due to Linux or some other reason, please use Spicetify v1.

**Comment by VottusCode** [comment]
Then why even support Spicetify on Linux? Why not just let the CLI give you a warning. Why not just write this in the README?
