### ISSUE TITLE
Applying themes results in a blank window

### ISSUE THREAD

**Issue by FawazTakhji** [khanhas/spicetify-cli#908]
## ℹ Computer information

- Spotify version: 1.1.63.568
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. … copy theme to theme folder
2. … type spicetify config current_theme "theme name" into powershell
3. … type spicetify apply

### ✔️ Expected result
theme is installed and shows up properly 

### ❌ Actual result
some colors changed but the window is empty

## 📷 Screenshots
https://i.imgur.com/dU3Agcl.png

**Comment by YuukiRondo** [comment]
Hello, I have the same problem, and i can't fix it.

**Comment by CharlieS1103** [comment]
@FawazTakhji @YuukiRondo  You need to downgrade your spotify, 1.62 should work

**Comment by ricozyx** [comment]
Also having this issue, all themes I tested end up just in a blank color.

**Comment by luigirinaldi** [comment]
> Also having this issue, all themes I tested end up just in a blank color.

I am also having the same issue

**Comment by luigirinaldi** [comment]
> @FawazTakhji @YuukiRondo You need to downgrade your spotify, 1.62 should work

for anyone looking I found this website to download the old version, now it's working, thank you
https://spotify.en.uptodown.com/windows/download/3764443

**Comment by prism2001** [comment]
alternatively just use the "spicetify restore" command rather than going to shady download websites. that command exists for a reason.

**Comment by ScottyHoover** [comment]
> for anyone looking I found this website to download the old version, now it's working, thank you

Make sure you also create an update folder within spotify and change the security settings so you can't access it. If you don't, spotify will try and update to a newer version. This [video](https://www.youtube.com/watch?v=lPUFzDes_Eg&t=20s) explains it pretty well.

**Comment by IoPossoIo** [comment]
Had the same problem , pushing the theme resulted in black window when opening Spotify.
Tried to fix with an older version of Spotify , but didn't work.

I restored everything with 
`spicetify restore`
now the theme is vanilla , but at least everything works.

**Comment by baris-inandi** [comment]
Same problem here

**Comment by kulaid** [comment]
> Had the same problem , pushing the theme resulted in black window when opening Spotify.
> Tried to fix with an older version of Spotify , but didn't work.
> 
> I restored everything with
> `spicetify restore`
> now the theme is vanilla , but at least everything works.

this happened to me too

**Comment by maybecitrus** [comment]
I have a similar problem with Spicetify, when I go to Spotify, I see the interface for a second and immediately I get an blank white screen. https://imgur.com/a/DcRJK1b

**Comment by HybridRaven** [comment]
All works fine on spotihfy v1.62.... On v1.63 we have blank gui etc. 
I restore spotify to 1.62 version but **HOW can I stop spotify** for the automatic updates?

**Comment by KR2206** [comment]
> All works fine on spotihfy v1.62.... On v1.63 we have blank gui etc.
> I restore spotify to 1.62 version but **HOW can I stop spotify** for the automatic updates?

Check out this vid https://www.youtube.com/watch?v=lPUFzDes_Eg

**Comment by afonsojramos** [comment]
Related to #845
