### ISSUE TITLE
Spicetify is broking my spotify

### ISSUE THREAD

**Issue by Bildeniz** [khanhas/spicetify-cli#909]
# My spotify is broking when i add new theme
 
wihout any theme or settings in spicetify
![resim](https://user-images.githubusercontent.com/57387002/126043836-2a2fd705-f449-4f93-8f43-1ba769cd2505.png)

when i runing just this code `spicetify apply enable-devtools`

![resim](https://user-images.githubusercontent.com/57387002/126043930-ef77464d-db48-45f3-b808-d6f391faebfe.png)
![resim](https://user-images.githubusercontent.com/57387002/126044076-9af9b2b8-4c99-4032-8bd4-572abedf91dc.png)
![resim](https://user-images.githubusercontent.com/57387002/126044084-96bbc618-faf6-4c36-9865-fc0865f94a3b.png)
![resim](https://user-images.githubusercontent.com/57387002/126044088-48480f18-1099-49b6-8d5a-9f71709ebef3.png)

and i runing `spicetify restore backup`

![resim](https://user-images.githubusercontent.com/57387002/126043966-0ce351df-4acc-4e4d-974e-073e8fa5f0d4.png)

returns to its original state

my operating system is windows 10
and my config file:
```
Settings
prefs_path                    C:\Users\bilde\AppData\Roaming\Spotify\prefs
current_theme                 Dribbblish
color_scheme                  Purple
replace_colors                1
overwrite_assets              0
spotify_launch_flags
spotify_path                  C:\Users\bilde\AppData\Roaming\Spotify
inject_css                    1
check_spicetify_upgrade       0

Preprocesses
disable_sentry                1
disable_ui_logging            1
remove_rtl_rule               1
expose_apis                   1
disable_upgrade_check         1

AdditionFeatures
sidebar_config                1
home_config                   1
extensions
custom_apps
```

**Comment by ricozyx** [comment]
Also having this issue, all themes I tested end up just in a blank color.

**Comment by eetle** [comment]
Same issue here, it seems the latest update of Spotify is not working with spicetify, I had to roll back the Spotify version

**Comment by eetle** [comment]
#845 has all the info you need to roll back the update

**Comment by TngySt** [comment]
Hey! I have the same issue and I saw many people having the same issue

**Comment by jboutin** [comment]
Kinda messy, but I posted a workaround to this on [Spectrum](https://spectrum.chat/spicetify/general/for-anybody-having-trouble-installing-spicetify-guide-in-getting-it-to-work~816b2083-a01f-49b7-b61a-4c128df82bb5).

Lemme know if it works for you 👍🏻

**Comment by Bildeniz** [comment]
yes it's working successfully
