### ISSUE TITLE
keyboardShortcut.js problems

### ISSUE THREAD

**Issue by Herewegoagainn** [khanhas/spicetify-cli#91]
Multiple errors when just doing a copy and paste of the code. Multiple errors of "Property 'click' does not exist on type 'Element'"

Does this for 'click', 'focus', and 'style'.

**Comment by khanhas** [comment]
You mean the error on the IDE or in Chrome console?
Errors with type and properties of type on the IDE do not actually cause any problem. Script could still work normally. You can just cast the type of object to the correct type if you feel like you need totally type-safe script.

**Comment by IzzyDLP** [comment]
In the IDE. I'll try it again tomorrow as none of the shortcuts were working when I was using it earlier.
