### ISSUE TITLE
Dribbblish

### ISSUE THREAD

**Issue by vigneshkannan522** [khanhas/spicetify-cli#910]
- Spicetify version: 2.5.0

I installed spicetify on my POP_OS and when I changed the theme to Dribbblish, the left bar is too large and almost takes up half of the window.

But other themes work fine.

## 📷 Screenshots
Full Screen
![Screenshot-20210718174857-1922x1082](https://user-images.githubusercontent.com/64825629/126067035-41bf5560-2efe-40a2-a2cc-0486eeec0d43.png)

When not in Full Screen
![Screenshot-20210718175932-1371x945](https://user-images.githubusercontent.com/64825629/126067189-16226646-916b-40b9-8b13-7c3af614afce.png)

**Comment by LooLzzz** [comment]
Did you add the `dribbblish.js` extension?

from the dribbbilish readme:
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish
![image](https://user-images.githubusercontent.com/8081213/126072225-8b248248-0335-4f2a-8a88-e72812cf79c8.png)

**Comment by afonsojramos** [comment]
This is not an issue with Spicetify, but with a specific theme.

**Comment by vigneshkannan522** [comment]
@LooLzzz  Thanks for your reply. I didn't know that I had to put the dribbblish.js file in the extensions folder. When I ran the commands from the readme file, it said that the dribbblish extension was not found. Then after I manually copied the Dribbblish.js file to the extensions folder, it works. 
Again Thanks.
