### ISSUE TITLE
glue-resources.spa file missing but copy and renaming method didnt work

### ISSUE THREAD

**Issue by brenmadeit** [khanhas/spicetify-cli#913]
## ℹ Computer information

- Spotify version:  1.1.64.561.g71bd09eb-a 
- Spicetify version: v2.2.6

## 📝 Provide detailed reproduction steps (if any)

1. at first it was settings.spa not founded then I went on to copy login.spa and rename it to settings.spa and it fixed it but now glue-resources.spa is not founded. 
2. tried the same copy and rename method but it didnt work.
3. tried on older spotify versions but it didnt work too.

### ✔️ Expected result

spotify is spiced up!

### ❌ Actual result

 settingsfatal open C:\Users\Brenda\.spicetify\Backup\glue-resources.spa: The system cannot find the file specified.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/83563626/126346752-89964f26-2241-498f-83ef-4313919899fd.png)

**Comment by afonsojramos** [comment]
Please update to the latest version and try again, thanks!
