### ISSUE TITLE
Does not work with latest Spotify Release

### ISSUE THREAD

**Issue by ajaxburger** [khanhas/spicetify-cli#914]
As of writing this does not function with the latest Spotify release and attempting to apply breaks the program entirely, forcing a reinstall.

**Comment by DrPleaseRespect** [comment]
Can confirm. on version 1.1.63.568.gda8cb5ac-a my Spotify client does not load and is stuck in a empty screen

Spotify Version: 1.1.63.568.gda8cb5ac-a
Config Settings:
- Theme: Turntable
- Color Scheme: Purple
- Extensions: fullAppDisplay.js | rotateTurntable.js | popupLyrics.js

**Comment by oTalDoNexus** [comment]
True, when i tried to install a extension it gave me a blank screen, i just restored it to default and it works, but can't install anything else or it stops working

**Comment by BinToss** [comment]
#845

**Comment by SonGorLick** [comment]
> Duplicate of #845

Its kinda a dup but the versions of spotify are different

**Comment by rgarcia7** [comment]
FYI: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-887073051
