### ISSUE TITLE
Spotify time bar is missing, when using Dribbblish

### ISSUE THREAD

**Issue by niuprofile** [khanhas/spicetify-cli#915]
## ℹ Computer information

- Spotify version: 1.1.63.568
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

Applied the Dribbblish theme, everything works fine, but the timebar is missing.

### ✔️ Expected result

Having the time bar.

### ❌ Actual result

Not having the time bar.

## 📷 Screenshots
I think the screenshot shows pretty good what I am missing here.
![a](https://user-images.githubusercontent.com/87776973/126533517-9144569c-fd9e-4216-8187-ef7ea5d33d6c.jpg)

**Comment by ScriptKiddieTutorials** [comment]
Confirm this.

**Comment by Guiguim255** [comment]
Same goes for me
![image](https://user-images.githubusercontent.com/47949573/127719615-d5b803c4-440d-4688-93e9-cba9b4cfb10c.png)

**Comment by Zerss** [comment]
Hey! I believe this issue would better belong in the [spicetify-themes](https://github.com/morpheusthewhite/spicetify-themes) repository, but it's alright.

Have you applied the `dribbblish.js` script in spicetify? I've had this specific issue before enabling it properly when installing it yesterday. I also could resize the sidebar.

You can check that by typing `spicetify config` in the CLI and checking if `dribbblish.js` appears in the extensions.

Make sure you also have your script placed in the Extensions folder of your spicetify configuration folder. You can find the folder by typing `spicetify -c` and going to the directory the file `config-xpui.ini` is in, there's your Extensions directory in here.

Everything is mostly explained in the README.md file of the Dribbblish theme [here](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#manual-install).

Hope that helps! :)

**Comment by Guiguim255** [comment]
You're right, I missed those steps, my bad.
I commented here because I couldn't find any similar issue in the [spicetify-themes](https://github.com/morpheusthewhite/spicetify-themes) repository (and it seems obvious since this is not an issue, but just a human fault).

Thanks for helping :)

**Comment by Zerss** [comment]
@niuprofile @ScriptKiddieTutorials Does this fix the issue for you? If so, please close the issue. Thanks!
