### ISSUE TITLE
Error 'Cannot find symbol for Custom app React symbols'

### ISSUE THREAD

**Issue by Dblxy** [khanhas/spicetify-cli#916]
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: v2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Apply theme
2. Error in powershell

### ✔️ Expected result

Theme should be applying

### ❌ Actual result

Error in powershell

## 📷 Screenshots

![Desktop Screenshot 2021 07 22 - 08 55 40 08](https://user-images.githubusercontent.com/61641687/126600388-92775d54-58a4-4132-b080-f37c3befd291.png)
![Desktop Screenshot 2021 07 22 - 08 53 42 39](https://user-images.githubusercontent.com/61641687/126600393-73bbfd2d-33c4-4cbe-ab1b-5ed8c691bb38.png)

**Comment by meteorsquare** [comment]
https://github.com/khanhas/spicetify-cli/issues/845
