### ISSUE TITLE
Stuff is breaking

### ISSUE THREAD

**Issue by pjalsGit** [khanhas/spicetify-cli#922]
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2da0de
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

I have no idea how I made it like this

### ✔️ Expected result

Able to search, custom apps work, songs don't randomly not play.

### ❌ Actual result

Can't search ("Ooops! something went wrong!") Custom apps don't work (Infinite Load) Songs don't play (progress bar doesn't move) Playlists randomly dissapear

## 📷 Screenshots

I use Fedora 34 (Linux) and also I have just updated. Here are the screenshots of the bugs:

https://imgur.com/a/vNBGdnB

**Comment by afonsojramos** [comment]
@pjalsGit for Spotify versions of 1.1.56 or older please use v1 of Spicetify which can be found [here](https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-legacy-spotify). If you have any trouble let me know!
