### ISSUE TITLE
error Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by Dr-DaNk** [khanhas/spicetify-cli#924]
## ℹ Computer information

- Spotify version: Latest I guess?
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

apply spicetify, any theme.

### ✔️ Expected result

Spicetify works

### ❌ Actual result

Blank screen with background color. Dev console completely empty. no HTML, no sources, nothing.
error in title provided from powershell.

## 📷 Screenshots

https://imgur.com/a/O6OD2m6

**Comment by a1sop0s** [comment]
Duplicate of #845
