### ISSUE TITLE
How to Reinstall Spicetify and Get It Working Again?

### ISSUE THREAD

**Issue by chipswdips** [khanhas/spicetify-cli#925]
![Untitled](https://user-images.githubusercontent.com/87925769/126890286-11592a34-f2a2-4f2c-95ab-363363eb0d8e.png)
I have this error and I don't know what I did wrong, please help me fix it. Thank you!

**Comment by KorayUlusan** [comment]
are you sure that you installed spicetify correctly?

**Comment by nils-kt** [comment]
Follow this guide: https://github.com/khanhas/spicetify-cli/wiki/Installation#with-powershell-pre-built-binary
You don't seem to have installed it correctly.

**Comment by chipswdips** [comment]
Hello I've successfully installed it, but when I apply backup now, my spotify just has a black screen. What do I do here?

**Comment by chipswdips** [comment]
![Untitled](https://user-images.githubusercontent.com/87925769/126914176-bbbb8ff8-ef4b-4841-9e7c-99ca208b5b4e.png)
My WebNowPlaying still isn't displaying spotify information, please help me with this issue. Thank you!

**Comment by nils-kt** [comment]
> Hello I've successfully installed it, but when I apply backup now, my spotify just has a black screen. What do I do here?

#845

**Comment by chipswdips** [comment]
Hello! I've restored it to an older version but it still doesn't work >.< sorry but could you help me again?

**Comment by SaberAkiyama** [comment]
@chipswdips 
https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-880459337

**Comment by chipswdips** [comment]
Hello! I've followed the comment but it still doesn't work, is there something I am doing wrong?

**Comment by SaberAkiyama** [comment]
> Hello! I've followed the comment but it still doesn't work, is there something I am doing wrong?

What doesn't work?

**Comment by rgarcia7** [comment]
FYI: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-887073051

**Comment by chipswdips** [comment]
My WebNowPlaying still isn't displaying Spotify information like a song or album covers, am I missing something?

**Comment by afonsojramos** [comment]
@chipswdips what versions are you now using on both Spicetify and Spotify?

**Comment by saxobroko** [comment]
For anyone wondering this is a duplicate of #845 and the only workaround as of now is to downgrade the Spotify version. Instructions on how to downgrade are in #845
