### ISSUE TITLE
Sort by 💚 heart (in playlists)

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#926]
## 📝 Provide a description of the new feature

Currently there are ways to sort by title, artist, album etc. However we cannot sort by liked songs (the green heart, 💚). With the new "blend for two" feature this will be more useful than ever. 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Poopooracoocoo** [comment]
or filter?
