### ISSUE TITLE
Dragging to "Create Playlist" or "Liked Songs" makes the buttons look odd 

### ISSUE THREAD

**Issue by shivins** [khanhas/spicetify-cli#928]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.5.0

The only css changes I have is to remove the upgrade button and the ad banner.  
Apps : lyrics-plus
Extensions : loopyLoop and popupLyrics

## 📝 Provide detailed reproduction steps (if any)

1. Have either "Create Playlist" or "Liked Songs" stuck in the sidebar
2. Go to any album/playlist page and attempt to drag a song to one of the two buttons
3. The button css gets cleared (my guess at least), and the button(s) no longer looks normal until Spotify is reloaded

### ✔️ Expected result

The button doesn't change appearance after the operation 

### ❌ Actual result

The padding for the button gets cleared and looks weird

## 📷 Screenshots

Before:

![image](https://user-images.githubusercontent.com/54951938/126917377-fea83147-7d04-4cbe-a618-93833b819ec8.png)

After:

![image](https://user-images.githubusercontent.com/54951938/126917407-7238b502-a25f-4402-9120-d656940fc901.png)

**Comment by meteorsquare** [comment]
Happens to mine as well. Might be a bug in the sidebar config extension but I could be wrong.

**Comment by KorayUlusan** [comment]
This also happened to me. I just quit and reopen spotify. Kinda works... :shrug:

**Comment by CharlieS1103** [comment]
Yeah i just fixed this in my theme Dreary, making a pull request rn.

**Comment by shivins** [comment]
@CharlieS1103 This fix didn't seem to work for me. Maybe it's because I'm on the default theme

So I think I figured out why this happens for me. The problem is that the "create playlist" button goes from class="GlueDropTarget GlueDropTarget--tracks personal-library" to class = "GlueDropTarget GlueDropTarget--tracks".  The same thing happens with the liked songs button in that the "personal-library" part gets removed as well. 

The css checks for GlueDropTarget.personal-library, so when you drag something over the buttons, the css doesn't apply anymore to the button without the personal-library class. This is probably some js related problem, but to fix this temporarily just add the following to your css file. This should fix the create playlist and liked songs button

`ul.main-navBar-entryPoints > div.GlueDropTarget{
    padding: 0 8px;
}
ul.main-navBar-entryPoints > div.GlueDropTarget >* {
    padding: 0 16px;
    height: 40px;
    border-radius: 4px;
}
ul.main-navBar-entryPoints > div.GlueDropTarget >*.active {
    background: var(--spice-card);
}`

This just uses the sticky menu to specify which gluedroptargets to apply the css to. There may be problems to this approach, but it seems to work for me on the default theme

**Comment by CharlieS1103** [comment]
Yeah i guess all the themes that haven't implemented it yet will have to in the future, I'll try to share it to the theme makers ik lol.
