### ISSUE TITLE
Nothings loading.

### ISSUE THREAD

**Issue by berryes** [khanhas/spicetify-cli#929]
## ℹ Computer information

- Spotify version: 1.1.64.561.g71bd09eb
- Spicetify version:  2.5.0

This has been like this for a week. No idea why
![image](https://user-images.githubusercontent.com/73071529/127147682-aca1e676-e345-4729-998c-528004603bcd.png)

**Comment by ricozyx** [comment]
Duplicate of: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-880459337

**Comment by itsmeow** [comment]
Patch available: #945 https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

**Comment by afonsojramos** [comment]
Please update to v2.6.0 and retry, thanks!
