### ISSUE TITLE
Playlist Scrollbar Non-Existent and Home Page Non-Functional When Using Spicetify

### ISSUE THREAD

**Issue by gemma350mb** [khanhas/spicetify-cli#93]
I use Spicetify simply so I can use the Monstercat Now Playing information on my desktop, so don't use any form of other customisation.
As soon as I run Spicetify, the scroll bar on the playlist section disappears completely and I'm totally unable to scroll down my list of playlists.
Also, the Home Page in Spotify just stops working entirely, with a "Please Try Again" message from Spotify.

**Comment by khanhas** [comment]
If you just need WebNowPlaying, run:
```
spicetify config inject_css 0 replace_colors 0
spicetify apply
```

**Comment by gemma350mb** [comment]
> If you just need WebNowPlaying, run:
> 
> ```
> spicetify config inject_css 0 replace_colors 0
> spicetify apply
> ```

Hey, thanks for the speedy reply!
I did this and that's exactly what makes my scrollbar and Home Page disappear :(

**Comment by khanhas** [comment]
Whaa... How could it?
When inject_css and replace_colors are 0, spicetify doesn't touch css files and everything should be in pristine state.

**Comment by gemma350mb** [comment]
> Whaa... How could it?
> When inject_css and replace_colors are 0, spicetify doesn't touch css files and everything should be in pristine state.

That's exactly what I expected also, but that doesn't seem to be the case! Even after a clean install of Spotify, as soon as I follow the steps you've said, the problem occurs.

**Comment by eerwwe** [comment]
same for me

**Comment by theRealPadster** [comment]
I have this issue as well, on MacOS Catalina. Everything works fine with normal Spotify, but when I apply my Spicetify theme to it, I can't scroll the playlists anymore and the homepage shows "Please try again".

**Comment by khanhas** [comment]
@theRealPadster Always run `spicetify backup apply` whenever there is new Spotify update.
