### ISSUE TITLE
Can't find trashbin icon...

### ISSUE THREAD

**Issue by ShivaPrakash-006** [khanhas/spicetify-cli#932]
## ℹ Computer information

- Spotify version: 1.1.59.714.g7e040462-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Apply trashbin extension and open spotify
2. …
3. …

### ✔️ Expected result

The trashbin icon should appear

### ❌ Actual result

The trashbin icon did not appear

## 📷 Screenshots

![2021-07-28 12_41_45-Spotify Free](https://user-images.githubusercontent.com/87466383/127280687-c6e53660-b4ba-4e95-8f77-36bb832883cf.png)

**Comment by CharlieS1103** [comment]
You right-click the song title and a button appears in the context menu.

**Comment by ShivaPrakash-006** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhh........ Doesn't it appear in the song menu?
