### ISSUE TITLE
Cant get this thing to say "ok" in all steps

### ISSUE THREAD

**Issue by Vannywasnotavailable** [khanhas/spicetify-cli#938]
Buddy, am pretty new to all of this terminal stuff, but i did follow the guide and i still get this everytime i try to get this thing to work
![aaaa](https://user-images.githubusercontent.com/88246277/127746391-4d4afc3b-3eb8-48ef-a4ab-6b5443841ba8.PNG)

**Comment by afonsojramos** [comment]
Try to create that file in that folder, might fix it!

**Comment by thatNexus** [comment]
Perhaps a permission issue?

To take ownership of the file from the PowerShell use this
`takeown /a /r /d Y /f <PATH TO FOLDER>`

    

-     /a – Gives ownership to the Administrators Group.
-     /r – Makes the operation recursive, it will apply to all subfolders and files.
-     /d Y – Suppresses confirmation with the option of Y. It will answer any ‘Are you sure?’ dialog with Y for Yes.
-     /f – This will specify the file or folder name.

**Comment by cherche** [comment]
What version of Spotify are you using? Note that spicetify 1.x (which you have installed) is incompatible with the new Spotify UI, which many users now have installed. If you have the newer Spotify, uninstall spicetify and install the latest 2.x version. (Check out #751, which seems to be the same issue.)
