### ISSUE TITLE
[Ubuntu 18.04] Blank application until reapplied

### ISSUE THREAD

**Issue by TheLastZombie** [khanhas/spicetify-cli#94]
When launching Spotify, I just get a blank, black application window and the HTML only consists of opening and closing `head` and `body` tags, but when I run `spicetify apply`, Spotify works as normal (until I exit Spotify and try to start it again).

Is this a bug or am I missing something?

**Comment by khanhas** [comment]
How did you install Spotify? Is there any chance that your package manager modify/revert app content before running it?

**Comment by c4tzz** [comment]
> How did you install Spotify? Is there any chance that your package manager modify/revert app content before running it?

Hi. 18.04.03
https://www.spotify.com/us/download/linux/
(from spotify repository)

black screen ( dev tool enable and css update)

**Comment by khanhas** [comment]
I'm not sure it will change anything but can you try this method:
https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-snap
You can skip the first step.
