### ISSUE TITLE
Where is the bookmarks data stored?

### ISSUE THREAD

**Issue by FiftyFour7250** [khanhas/spicetify-cli#940]
Not the bookmark extension itself, but data. I think somewhere in AppData\Roaming\Spotify, but where...

**Comment by Woosy** [comment]
It's stored in the localstorage.

You can access it by running `spicetify enable-devtool` and then hitting ctrl+shift+i
The localstorage key is `bookmark_spicetify`, and here's an example of what this data looks like:
```
[{"uri":"spotify:artist:2kCcBybjl3SAtIcwdWpUe3","title":"Lil Peep","description":"Artist","imageUrl":"https://i.scdn.co/image/ab67618600006fbadc4504191bbb5f26521271ea","id":"spotify:artist:2kCcBybjl3SAtIcwdWpUe3-1628168254073"}]
```
