### ISSUE TITLE
fullappdisplay.js not showing progress bar like in photo

### ISSUE THREAD

**Issue by Ast3r0ids** [khanhas/spicetify-cli#944]
## ℹ Computer information

- Spotify version: 1-1-59-714
- Spicetify version:  2.50

## 📝 Provide detailed reproduction steps (if any)

I wanted to install the theme called "turntable" which required fullappdisplay, so I applied it. In the turntable screenshot, 
it showed fullappdisplay with progress controls and a bar.

### ✔️ Expected result

For fullappdisplay to work properly

### ❌ Actual result

fullappdisplay shows album art, artist and song but not progress or controls

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/85231847/127886784-42548dea-8293-4a10-b66e-b0827b35fd6d.png)

**Comment by philipch07** [comment]
Right click to change the options and the layout. For example, I use these settings, and it appears as follows:
![image](https://user-images.githubusercontent.com/59272129/127907571-8372e44b-38ad-4ece-b061-468974f1a71a.png)
![image](https://user-images.githubusercontent.com/59272129/127907590-3978efcd-9dfd-43de-8e62-8dbf321cafab.png)

**Comment by Ast3r0ids** [comment]
Many thanks.

**Comment by Adithya-Kalany** [comment]
Hey, Thanks a lot @philipch07
