### ISSUE TITLE
popupLyrics stops updating lyrics if spotify is minimized

### ISSUE THREAD

**Issue by saurabhcodes25** [khanhas/spicetify-cli#946]
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2da0de
- Spicetify version: Latest

## 📝 Provide detailed reproduction steps (if any)

1.Click on popupLyrics.
2. It shows lyrics and keeps updating it.
3. Minimize Spotify app.
4. Lyrics pauses.

### ✔️ Expected result

popupLyrics should work as usual and keep the lyrics going.

### ❌ Actual result

popupLyrics stops updating lyrics and pauses there.Have to maximize Spotify and restart popupLyrics to make it normal again. Stops again if Spotify is minimized. (OS- Arch Linux)

**Comment by afonsojramos** [comment]
I believe this has now been fixed.
