### ISSUE TITLE
every thing is fucked

### ISSUE THREAD

**Issue by eerwwe** [khanhas/spicetify-cli#95]
ive been useing this for a year but i had to reseet my laptop beacause it got a little buggy. after i reinstalled everything and didnt chnage any settings this happend. how can i fix it.

![image](https://user-images.githubusercontent.com/28791625/67529375-94d96500-f681-11e9-8c5f-28c0adbf0df4.png)

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#windows-pre-built

**Comment by eerwwe** [comment]
bruh

**Comment by eerwwe** [comment]
i was using that and than i tried the other version that didn't work either they're both broke for me .

**Comment by khanhas** [comment]
Reinstall Spotify to original state and try commands in the link I gave
