### ISSUE TITLE
error C:\Users\me\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file.

### ISSUE THREAD

**Issue by ryawann** [khanhas/spicetify-cli#950]
when installing i got this error :(

i used this code i found from a youtube video:
Add-Type -AssemblyName PresentationFramework
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
spicetify
spicetify backup apply enable-devtool
[System.Windows.MessageBox]::Show('Please drag the themes into the themes folder located at | C:\Users\YourUserName\.spicetify\Themes |')
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply
pause

## ℹ Computer information

- Spotify version: the latest
- Spicetify version: the latest

thamk you !!

**Comment by Penetrosity** [comment]
Followed the wiki, but started with it before I read about not using Windows Store version. I've got the same error and this is how I got it.

1)Install spicetify while having Windows Store version
2)Realize and uninstall windows store version
3)Install regular version
4)Try to run spicetify backup apply

My main issue now is that I can't find this config-xpui.ini file, where is it stored normally?

Found the answer in one of the previous responses
```
spicetify config prefs_path " "
spicetify config spotify_path " "
spicetify backup apply
```
Fixed my error, although it did load spotify all white, but that's another issue that I can work on my own and doesn't have to do with the above user.

**Comment by casungo** [comment]
config-xpui.ini is located at `C:\Users\yourUsername\.spicetify`
If you are still experiencing issues even after tweaking config-xpui.ini I suggest you do a complete reinstall of Spotify & Spicetify (To uninstall spicetify just delete `C:\Users\yourUsername\.spicetify` & `C:\Users\yourUsername\spicetify-cli`)

**Comment by josh-codes** [comment]
It worked for me when I had both versions.

**Comment by afonsojramos** [comment]
Closed for lack of response from issue opener.
