### ISSUE TITLE
lyrics-plus: Show previous line

### ISSUE THREAD

**Issue by Flash08YT** [khanhas/spicetify-cli#954]
As some lyrics are not very synchronous with the song, you could put the current line in the middle and the previous line above it, so when it goes too fast, you could still read the last line.
It then could look something like this:

![synced](https://user-images.githubusercontent.com/34920726/128432177-028cedfa-3234-4eba-87ec-b3e8b560dcb3.png)

**Comment by khanhas** [comment]
Added customizable lines to show before and after, they would be available next patch:

![image](https://user-images.githubusercontent.com/26436809/141606596-10078444-122a-4484-97a9-67a0d2ddcf98.png)
![image](https://user-images.githubusercontent.com/26436809/141606612-364eb118-9245-4130-a1eb-ac39493d6880.png)
