### ISSUE TITLE
lyrics plus app stuck says "something went wrong; try reloading the page"

### ISSUE THREAD

**Issue by justnewt** [khanhas/spicetify-cli#963]
title says it all.
![image](https://user-images.githubusercontent.com/23704936/129425137-63e9daa7-336c-470f-b6a1-9f698bc78d88.png)

**Comment by NITRONewt0n** [comment]
this is on a fresh install for both spotify and spicetify on v2.5.0-itsmeow-patch2. lmk if anyone has any fixes.

**Comment by itsmeow** [comment]
Patch 4 is out which fixes this! https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch4
You probably shouldn't make repo issues on changes that aren't official yet, just comment on the PR or previous issue if you find something wrong with the patch, that's the best way to get it to my eyes.

**Comment by justnewt** [comment]
> You probably shouldn't make repo issues on changes that aren't official yet, just comment on the PR or previous issue if you find something wrong with the patch, that's the best way to get it to my eyes.
ah, sorry. i dont use git much. thanks for the update!
