### ISSUE TITLE
[Help] No Render On spotify After Running sudo -E spicetify backup apply enable-devtool

### ISSUE THREAD

**Issue by AiryPP** [khanhas/spicetify-cli#964]
Hey there I was just trying to use a spicetify theme for my new Arch rice and ran into a problem after running the command sudo -E spicetify backup apply enable-devtool, nothing will render regardless of the theme.

Any help is appreciated

**Comment by Shayshon** [comment]
Can Reproduce- Windows 11 build 22000.132 on newest Spotify build

**Comment by itsmeow** [comment]
Duplicate of #845, patch available (see #945)

**Comment by AiryPP** [comment]
Patch not working for me

Spotify Run Logs
```
(spotify:37153): Gtk-WARNING **: 20:31:52.975: Theme parsing error: gtk-dark.css:6342:10: 'height' is not a valid property name
Gtk-Message: 20:31:52.994: Failed to load module "appmenu-gtk-module"
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

**Comment by itsmeow** [comment]
@AiryPP Can you tell me your OS and CPU architecture?

**Comment by AiryPP** [comment]
@itsmeow ArchLinux cpu Architecture is x86 64 bit
