### ISSUE TITLE
Open developer tools

### ISSUE THREAD

**Issue by dftd** [khanhas/spicetify-cli#965]
## ℹ Computer information

- Spicetify version: 2.5.0
Running the Linux version of Spotify from flatpak.

## 📝 Provide detailed reproduction steps (if any)

`spicetify enable-devtool`
`success DevTool! enabled`

Ctrl + Shift + I not working
Right-click on blank areas doesn't show a context menu at all.

**Comment by itsmeow** [comment]
You need to run `spicetify enable-devtool apply`

**Comment by dftd** [comment]
> You need to run `spicetify enable-devtool apply`

Sorry for the late reply but that ain't working either.

**Comment by casungo** [comment]
🤔 try to use the command used [here](https://github.com/khanhas/spicetify-cli/wiki/Basic-Usage)

**Comment by dftd** [comment]
Yeah none of that works with Flatpak version from me.

Now I installed Spotify from their debian repo and everything works fine there.
