### ISSUE TITLE
Conventional user data locations for macOS

### ISSUE THREAD

**Issue by cafca** [khanhas/spicetify-cli#967]
## 📝 Provide a description of the new feature

User data for spicetify-cli on macOS is stored in `~/spicetify_data`. Have you considered storing user data in locations which are conventionally used by macOS applications such as `~/Library/Application Support` and `~/Library/Preferences`? 

I prefer applications that use these folders because it lets me structure my user folder `~/` how I like it. 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by okarin001** [comment]
> conventionally used by macOS applications such as `~/Library/Application Support` and `~/Library/Preferences`?

Since **spicetify** is not a normal application rather a command-line interface (CLI - everything happens in the terminal), I think, those places will not be "convenient places". 
My assumption behind @khanhas using `~/spiceity_data` (in the home directory) to keep things simple for most of the users. Yes, it would be better if we shift the `spicetify_data` from `~` (the home directory) to someplace like 
- `~/.config/spicetify_data/` or
- make it a hidden folder like `~/.spicetify_data`

**Comment by KorayUlusan** [comment]
@okarin001 what is your spicetify version. Mine still is in `~/spiceity_data`

```
$ spicetify -c path
/Users/thisuser/spicetify_data/config-xpui.ini
```

**Comment by ririxidev** [comment]
`~/Library/Application Support` and `~/Library/Preferences` directories are reserved for Applications that are in `/Applications` dir.
We could use `~/.spicetify_data` or `~/.config/spicetify_data/` like @okarin001 suggested - I guess it will be easier to even access config files etc for end-users. Will see 👀

**Comment by cafca** [comment]
> `~/Library/Application Support` and `~/Library/Preferences` directories are reserved for Applications that are in `/Applications` dir.

Is this an actual guideline? I wasn't able to find documentation on this, only [this page](https://support.apple.com/guide/mac-help/folders-that-come-with-your-mac-mchlp1143/mac) which says that this folder contains data for applications in general. 

My vote goes to `~/.config/spicetify_data` because that doesn't dump another folder in the home directory and `~/.config` seems to have gained momentum as a convention for application data.

**Comment by ririxidev** [comment]
> Is this an actual guideline? I wasn't able to find documentation on this, only this page which says that this folder contains data for applications in general.

There is not, but it's really better to keep stuff like spicetify in basically different dirs than these. 😄

**Comment by cafca** [comment]
Why is that? On the contrary, it's a very good idea to keep *all* application data in the same place unless there are good reasons not to do so.

**Comment by ririxidev** [comment]
> Why is that? On the contrary, it's a very good idea to keep all application data in the same place unless there are good reasons not to do so.

This folder is used for Applications that are under /Applications dir because only these that in theory have access to it, we can just keep data in ~/.configs/ and it will be fine too.
