### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Tyde** [khanhas/spicetify-cli#968]
I installed spicetify-cli with the Powershell method on Windows. Installation had no issues and also running `spicetify` did not result in errors, but when I executed `spicetify backup apply enable-devtool`as in the Basic Usage page, I got the following output 

    spicetify v2.5.0
    Backing up app files:
    OK
    Extracting:
    OK
    Preprocessing:
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x30 pc=0xa909d6]
    
    goroutine 1 [running]:
    github.com/khanhas/spicetify-cli/src/preprocess.Start.func1(0xc00000d8f0, 0x2c, 0x0, 0x0, 0xb9b3c0, 0xc000020030, 0xc0000060e8, 0x0)
            D:/Code/spicetify-cli/src/preprocess/preprocess.go:64 +0x56
    path/filepath.Walk(0xc00000d8f0, 0x2c, 0xc00047dd10, 0x0, 0x0)
            D:/Program Files/Go/src/path/filepath/path.go:499 +0x8a
    github.com/khanhas/spicetify-cli/src/preprocess.Start(0xc0000c21b0, 0x27, 0x101010101)
            D:/Code/spicetify-cli/src/preprocess/preprocess.go:63 +0x416
    github.com/khanhas/spicetify-cli/src/cmd.Backup(0xb952d4, 0x5)
            D:/Code/spicetify-cli/src/cmd/backup.go:61 +0x826
    main.main()
            D:/Code/spicetify-cli/spicetify.go:183 +0x5b2

The paths in the config file seem to be correct.

**Comment by casungo** [comment]
This is new 🤔
Try [this community patch](https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch4) maybe it fixes something.
Also it's a good thing to restart your PC just in case (good old power off power on)

**Comment by Tyde** [comment]
Sadly both the community patch and restarting the PC did not help

**Comment by casungo** [comment]
Ok so, I just realized that the error is basically the same as the popular #845 error, minus the _Cannot find symbol for Custom app React symbols_ part, strange that the community patch did nothing. I'm out of ideas, might as well wait for someone with more knowledge than me to help you :D

**Comment by afonsojramos** [comment]
@Tyde can you retry using the `spicetify upgrade` method?

**Comment by Tyde** [comment]
I tried.

I still get the error:

    Fetch latest release info:
    OK
    info Current version: 2.5.0-itsmeow-patch4
    info Latest release: 2.6.0
    Downloading:
    OK
    Extracting:
    OK                                                                                                                      
    success spicetify is up-to-date.                                                                                       
    info Please run "spicetify restore backup apply" to receive new features and bug fixes                                  
    PS C:\Users\thiem> spicetify backup apply enable-devtool                                                                
    spicetify v2.5.0-itsmeow-patch4                                                                                         
        info There is available backup.                                                                                         
        info Clear current backup:                                                                                              
    success Backup is cleared.
    Backing up app files:
    OK
    Extracting:
    OK
    Preprocessing:
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x30 pc=0x1170bd6]
    
    goroutine 1 [running]:
    github.com/khanhas/spicetify-cli/src/preprocess.Start.func1(0xc000302510, 0x2c, 0x0, 0x0, 0x127b540, 0xc0002da090, 0xc000006350, 0x0)
            C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/preprocess/preprocess.go:65 +0x56
    path/filepath.Walk(0xc000302510, 0x2c, 0xc0003edd10, 0x0, 0x0)
            C:/Program Files/Go/src/path/filepath/path.go:499 +0x8a
    github.com/khanhas/spicetify-cli/src/preprocess.Start(0xc00000c4e0, 0x27, 0x101010101)
            C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/preprocess/preprocess.go:64 +0x416
    github.com/khanhas/spicetify-cli/src/cmd.Backup(0x12769e0, 0x14)
            C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/cmd/backup.go:61 +0x826
    main.main()
            C:/Users/itsmeow/spicetify-cli/spicetify-cli/spicetify.go:183 +0x5b2


Weirdly the version at the beginning did not change.

**Comment by TheGeeKing** [comment]
Hi @Tyde,

Do you still encounter this issue?
If so, please provide more information like the version of Spotify and Spicetify that you are using. Can you also please provide your config file. Did you try to completely uninstall Spicetify (spicetify-cli and .spicetify folders) and run `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
` to install Spicetify.

**Comment by itsmeow** [comment]
This appears to be a filesystem read/write error. Can you show a screenshot of your `%appdata%/Spotify/Apps` folder? What's inside the `xpui` folder there?

**Comment by Tyde** [comment]
To add on that. I've searched through both my drives and there actually no `xpui` folder anywhere to be found.

**Comment by TheGeeKing** [comment]
Hi, 

> It seems like I did install Spotify via the Microsoft Store. Maybe that causes the issue?

Yep, that's the issue. 

https://www.spotify.com/us/download/

If the problem is fixed after the installation of Spotify, please close the issue.

**Comment by Tyde** [comment]
Yep that solved it. Thanks!
