### ISSUE TITLE
New releases tab not loading

### ISSUE THREAD

**Issue by Copimox** [khanhas/spicetify-cli#970]
## ℹ Computer information

- Spotify version: Latest idk
- Spicetify version: 2.6.0

## 📝 Provide detailed reproduction steps (if any)

1. Download the latest version of Spicetify
2. Run `spicetify restore backup apply`
3. Go to New Releases tab

### ✔️ Expected result

_What is the expected result of the above steps?_
Me getting info on new releases

### ❌ Actual result

_What is the actual result of the above steps?_
See Video
## 📷 Screenshots

_Are there any useful screenshots?_

https://user-images.githubusercontent.com/81705406/129784794-d4eeb9ca-392c-4213-882b-d7a3bacd95c1.mp4

**Comment by afonsojramos** [comment]
Can confirm that this bug is happening, currently investigating a fix!
