### ISSUE TITLE
Changes after Spotifyupdate

### ISSUE THREAD

**Issue by SigmaGrindYK** [khanhas/spicetify-cli#971]
- Spotify version: 1.1.66.578.gc54d0f69-a
- Spicetify version: Latest

Hello,

I'm using Spicetify for quite a while now and I'm sick of all the problems that spotify cause with their updates. 
I really enjoyed the changes I ran through with Spicetify V2 and now (again) after the latest Spotifyupdate, my Theme went from 1. to the 2. as you can see in the Screenshots below. I know that theres only a little difference but I just like the initial version.

1.
![2021-08-17](https://user-images.githubusercontent.com/89106146/129801730-4cd33a97-d9f6-48f7-bb7a-d6dc4d668da2.png)

2.
![2021-08-17 (1)](https://user-images.githubusercontent.com/89106146/129801729-ade421d5-182a-462a-a5a7-6fe2e519de09.png)

My question is, if there is any way to reset this or if I'm forced to wait for a new update that hopefully fixes this issue. 
Sincerly, Lukas

**Comment by afonsojramos** [comment]
I would suggest that you play around and edit the theme yourself. Unfortunately, there is no better option.

**Comment by kxm613** [comment]
I had the same issue; I was able to fix it by [downgrading Spotify to 1.1.65](https://spotify.en.uptodown.com/windows/download/3835861). Also make sure you disable auto-updating for Spotify.
