### ISSUE TITLE
Spicetify 2.6.0 causes fatal error

### ISSUE THREAD

**Issue by 3raxton** [khanhas/spicetify-cli#972]
## ℹ Computer information

- Spotify version: 1.1.66.578
- Spicetify version: 2.6.0
- macOS

## 📝 Provide detailed reproduction steps (if any)

1. Install Spicetify 2.6.0
2. Run ```spicetify upgrade``` then run ```spicetify restore backup apply```
3. Launch Spotify 

### ✔️ Expected result

Spotify will load and be themed from spicetify-cli.

### ❌ Actual results

This results in a fatal error and Spotify launches wit the theme but does not load any content

### 📸 Screenshots

<img width="1706" alt="Xnip2021-08-17_14-18-04@2x" src="https://user-images.githubusercontent.com/20716142/129803560-71b93701-54e9-4b82-a478-293cf79d0f28.png">

**Comment by nils-kt** [comment]
Download the latest Spotify client.

**Comment by casungo** [comment]
This version is pretty messed up, the only solution is to wait for a fix
[This](https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-900560880) is the first time someone has reported it fyi
