### ISSUE TITLE
Spicetify upgrade won't install version 2.6

### ISSUE THREAD

**Issue by jrmain** [khanhas/spicetify-cli#973]
## ℹ Computer information
Windows 8.1 64-bit

- Spotify version:  1.1.65.643.g2d707698-a
- Spicetify version:  2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. Upgrade Spicetify: spicetify upgrade
2. Check Spicetify version: spicetify -v

### ✔️ Expected result

Should show the installed version is 2.6.

### ❌ Actual result

Shows the version is still 2.5.0-itsmeow-patch4.

Details:

PS C:\Users\(user)> spicetify upgrade
Fetch latest release info:
OK
info Current version: 2.5.0-itsmeow-patch4
info Latest release: 2.6.0
Downloading:
OK
Extracting:
OK
success spicetify is up-to-date.
info Please run "spicetify restore backup apply" to receive new features and bug fixes
PS C:\Users\(user)> spicetify -v
2.5.0-itsmeow-patch4

## 📷 Screenshots

None.

**Comment by afonsojramos** [comment]
Yeah, sorry, tried to rush the release, will be fixed on the next one!
