### ISSUE TITLE
Spotify not loading after upgrading Spicetify to version 2.6.0

### ISSUE THREAD

**Issue by spekkii** [khanhas/spicetify-cli#974]
## ℹ Computer information

- Spotify version: 1.1.66.578.gc54d0f69-a (Latest version)
- Spicetify version: 2.6.0
- Windows 10 Home build: 19042.1165

## 📝 Reproduction steps

Follow update instructions:
1. Upgrade spicetify to version 2.6.0 (run `spicetify upgrade`)
2. Run `spicetify restore backup apply`

### ✔️ Expected result

Spotify loads with the spicetify theme, extensions, and custom apps.

### ❌ Actual result

Spotify launches with an error box saying "Something went wrong, Try reloading the page" everything else is blurred out/doesn't load. Spotify just goes back to that error upon reloading. Some of the theme colors are loaded (seen in the "Reload Page" button)

## 📷 Screenshots

![Screenshot 2021-08-18 113429](https://user-images.githubusercontent.com/52278288/129875333-0a970540-c5a1-4992-ac34-a5883a560c8f.png)

The output I get after upgrading spicetify and running `spicetify restore backup apply`

![Screenshot 2021-08-18 115802](https://user-images.githubusercontent.com/52278288/129878727-fd9e07c8-a819-4d9f-82a1-b01c07640108.png)

**Comment by casungo** [comment]
This version is pretty messed up, the only solution is to wait for a fix
[This](https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-900560880) is the first time someone has reported it fyi

**Comment by Fosmos** [comment]
I think it's the custom apps. I removed them from the config and everything else worked fine

**Comment by spekkii** [comment]
> I think it's the custom apps. I removed them from the config and everything else worked fine

Thanks! I removed the custom apps and now Spotify is actually loading, UI is a bit bugged though.

**Comment by Fosmos** [comment]
Yeah. I noticed the fullAppDisplay icon doesn't show but if you hit F11 it still works as intended.

**Comment by meteorsquare** [comment]
New Spotify version messed up the Spicetify patches (including 2.6.0).

**Comment by meteorsquare** [comment]
Maybe I'm wrong, the 2.6.0/2.5.0-patch4 doesn't apply to Spotify effectively on earlier versions (I went back to 1.1.61.583.gad060c66-a) and went back to patch3. I'm sure I used patch3 on the latest version as well...

**Comment by spekkii** [comment]
> Maybe I'm wrong, the 2.6.0/2.5.0-patch4 doesn't apply to Spotify effectively on earlier versions (I went back to 1.1.61.583.gad060c66-a) and I went back to patch3 as that's my latest "working" patch. I'm sure I used patch3 on the latest version as well though...
> 
> *effectively, being that the themes and user.css coding is reflected on spiced up Spotify.

Yeah, I also downgraded Spotify to that version, the problem still persists.
How do you downgrade Spicetify though? Do I just reinstall it?

**Comment by meteorsquare** [comment]
You'll need to download from https://github.com/itsmeowForks/spicetify-cli/releases and look for patch3, then replace the files. I won't be able to help well because I'm in MacOS...
