### ISSUE TITLE
Is there anyway to make the pop up lyrics background transparent?

### ISSUE THREAD

**Issue by sdfgdfgfghjf67** [khanhas/spicetify-cli#976]
![em](https://user-images.githubusercontent.com/78664046/129903221-54da150f-6c27-4010-a926-2b605cc0f262.png)

Transparent background for pop up lyrics would be really good for something like this. If there is anyway to do this please let me know.

**Comment by TheGeeKing** [comment]
https://www.makeuseof.com/tag/peek-through-make-any-window-transparent-using-a-keyboard-shortcut/ if you are on windows, it might work
