### ISSUE TITLE
[question] Dev-tools menu is still available after reinstalling spotify

### ISSUE THREAD

**Issue by actionless** [khanhas/spicetify-cli#98]
Hi! I was trying to use command `spicetify backup apply enable-devtool` to get dev tools in spotify and it worked fine.
However when i re-installed `spotify` package (and removed ~/.cache/spotify dir) I still having dev tools menu activated when right-clicking on the empty space.
I wonder if that cached somewhere else than in ~/.cache/spotify dir?

**Comment by actionless** [comment]
ah, i found, it was in `~/.config/spotify/prefs`

**Comment by actionless** [comment]
(didn't knew it's just a pref, i thought spicefy injects some js code to get them working)

**Comment by khanhas** [comment]
`spicetify disable-devtool` was what you were looking for.

**Comment by actionless** [comment]
yeah, but i was looking how to restore it manually

**Comment by khanhas** [comment]
There is no difference between editing pref file manually and using `spicetify disable-devtool`.
Anyway, I'm glad it was resolved.
