### ISSUE TITLE
Link context menus color to a different key

### ISSUE THREAD

**Issue by parromtra** [khanhas/spicetify-cli#981]
Hello,

Since color keys in themes were changed, the "button-active" parameter affects both context menus BG and active button color while hovering cursor over it. As a result­­­ depending on the "button-active" color buttons become barely visible or invisible when I point them and context menus become too bright. Imho it would be better to link context menu color to a different key (main, sidebar, player etc.)

My theme config:
```
[dark-orange]
text               = ffffff
subtext            = aaaaaa
main               = 161616
sidebar            = 161616
player             = 161616
card               = 161616
shadow             = 080808
selected-row       = 202020
button             = da7600
button-active      = 161616
button-disabled    = 535353
tab-active         = 404040
notification       = 161616
notification-error = ff0000
misc               = 00ff00
```

How it looks:

![spot](https://user-images.githubusercontent.com/88559257/129987504-7f925b50-a167-4a70-a53e-b3fb2d1c129a.jpg)

Buttons coloring:

![image](https://user-images.githubusercontent.com/88559257/129987570-6da9c7b5-0af4-45b9-aec3-d6114c10d989.png)

![image](https://user-images.githubusercontent.com/88559257/129987640-bc9e4c08-42eb-4193-8c9e-e4221d3fb9a6.png)

Hover state:

![image](https://user-images.githubusercontent.com/88559257/129987740-91398c43-1ac3-4f7f-90b3-1fc590841a5d.png)

![image](https://user-images.githubusercontent.com/88559257/129987665-06d27563-cb89-49eb-913b-1d0749f97c92.png)

**Comment by noobyogi0010** [comment]
I would like to work on the fix for this. @parromtra

**Comment by afonsojramos** [comment]
This is due to the CSS remap if I'm not mistaken. Can you confirm @CharlieS1103 @TheGeeKing?

**Comment by TheGeeKing** [comment]
> This is due to the CSS remap if I'm not mistaken. Can you confirm @CharlieS1103 @TheGeeKing?

Don't really know this part of the themes. But it looks like it is due to how it was made. Will try to find code that does this color link and separate more colors parameters to have a better choice.

**Comment by CharlieS1103** [comment]
Might be css map, might be your theme, try to use another theme, if that doesn't work it's almost definitely css map. Doesn't seem like any elements of the player have been mapped yet.

**Comment by parromtra** [comment]
> > This is due to the CSS remap if I'm not mistaken. Can you confirm @CharlieS1103 @TheGeeKing?
> 
> Don't really know this part of the themes. But it looks like it is due to how it was made. Will try to find code that does this color link and separate more colors parameters to have a better choice.
> 
> If @parromtra or @noobyogi0010 has any idea of the file or anything else useful, I will take it.

**Comment by afonsojramos** [comment]
Then, that should be fixed with future CSS Mappings fixes, thank you @parromtra !
