### ISSUE TITLE
Causes spotify not to work

### ISSUE THREAD

**Issue by Wiisporter** [khanhas/spicetify-cli#989]
**issue with lyrics plus addon**

## ℹ Computer information

- Spotify version: 1.1.66.578
- Spicetify version:  Unknown

## 📝 Provide detailed reproduction steps (if any)

1. Run install commands
2. Spicetify apply
3. "Error Loading page"
4. Unload lyrics plus
5. Works fine

### ✔️ Expected result

Spotify/Spicetify works with lyrics plus

### ❌ Actual result

Spotify spits out errors and stops working

**Comment by akh8zm** [comment]
I got the same error message ("Error loading page") when trying to enable the `loopyLoop.js` extension (as well as lyrics-plus). Removing it from the config fixed it. 🤷

**Comment by TheGeeKing** [comment]
Hi @akh8zm,

if your Spotify version is 1.1.66 or greater and you have Spicetify 2.6 or older version, that's normal. You will need to upgrade to Spicetify 2.6.1 or roll back your Spotify version to have a more stable Spotify/Spicetify.

If on you are on Windows :

Block updates :
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

Rollback to 1.1.65.643 :
https://www.filepuma.com/download/spotify_1.1.65.643-29529/

For Mac users :

Block updates :
In the Application folder, right-click on the Spotify app and choose 'Get Info'

in the 'Get info' window, make sure you check 'Locked', right at the top.

Rollback to 1.1.59.714 (maybe newer versions work but I don't know so say it if you can try it) :
https://www.filepuma.com/download/spotify_1.1.59.714-28782/
