### ISSUE TITLE
Notification Text Bug

### ISSUE THREAD

**Issue by mohitgarg** [khanhas/spicetify-cli#99]
In the shuffle+ extension whenever a user clicks on the shuffle context or shuffle queue it displays a notification with some text message(`Shuffled ${count} items!`). I can see the notification bubble but not the text inside. I tried calling the `showNotification` method from the devtools as well but whatever text string I pass there is not being displayed as well.

My Spotify version is 1.1.18.611.g9cc9bdc9
and Spicetify version is v0.9.5

**Comment by khanhas** [comment]
Oh thanks!
They change something again. I will take a look when I have time.

**Comment by mohitgarg** [comment]
Thank you so much for fixing it.
