### ISSUE TITLE
Latest Spotify version breaks Home/Sidebar Config + Extensions

### ISSUE THREAD

**Issue by kxm613** [khanhas/spicetify-cli#990]
## ℹ Computer information

- Spotify version: 1.1.66.578.gc54d0f69-a (Latest version)
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. Reinstall Spotify/update to latest version
2. Run `spicetify backup apply`
3. Tried with multiple themes/extensions, Spicetify versions; the only thing that fixes it is downgrading Spotify.

### ✔️ Expected result

Spotify loads the theme, extensions, and Spicetify features including home and sidebar config.

### ❌ Actual result

Spotify only loads the theme, without home/sidebar config or any custom extensions. Additionally, it shows a color gradient on the background of albums/playlists that is supposed to be removed by the theme (see #971).

## 📷 Screenshots

__Version 1.1.65__ (from [uptodown](https://spotify.en.uptodown.com/windows/download/3835861))
![1.1.65.643](https://user-images.githubusercontent.com/89319900/130334898-de85420f-7e2f-48c4-8aa0-3ccb846ecf9d.png)

__Latest Version__
![1.1.66.578](https://user-images.githubusercontent.com/89319900/130334911-22c55e86-26ce-4244-823c-1dfeee5380ad.png)

**Comment by ZT2wo** [comment]
Is this due to ".main-topBar" changing to ".Root__top-bar", and I assume similar changes happened the sidebar.

**Comment by CharlieS1103** [comment]
Yeah you can see this issue very clearly in my theme, Dreary, all custom apps are broken as are sidebar config and home config.
