### ISSUE TITLE
What happened to the sidebar?

### ISSUE THREAD

**Issue by theofficialgrand1** [khanhas/spicetify-cli#997]
<img width="230" alt="Screen Shot 2021-08-24 at 4 59 30 PM" src="https://user-images.githubusercontent.com/78011648/130588572-b61ee11b-0512-498e-84fe-8691370bc795.png">

Anyone knows what happened to the sidebar, used to have Your Episodes section. And without the line between glitching out the theme.
![image](https://user-images.githubusercontent.com/78011648/130588721-ef4cb18e-9916-431a-99e8-d62b4b09f9d2.png)

**Comment by Akasiek** [comment]
Latest Spotify update broke some functionalities of Spicetify. Most custom apps aren't working. Just watch out for the patch
