### ISSUE TITLE
fullAppDisplay not working in Windows 11

### ISSUE THREAD

**Issue by kxmndz** [khanhas/spicetify-cli#998]
## ℹ Computer information

- Spotify version: `1.1.66.580.gbd43cbc9-a`
- Spicetify version: `2.5.0-itsmeow-patch4`
- Windows 11 version 21H2 (build 22000.160)

## 📝 Provide detailed reproduction steps (if any)

1. Have Spotify and Spicetify
2. Open a terminal
3. Run these commands
```
spicetify config extensions fullAppDisplay.js
spicetify apply
```
4. Wait for Spotify to reload

### ✔️ Expected result

There is a button to activate to full screen display at the top bar

### ❌ Actual result

The button to activate the full app display is not showing

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/71072915/130711321-256ac40b-e94e-4a55-a64e-a511b9edac72.png)

**Comment by Fosmos** [comment]
It actually does work, you just need to hit F11 on the keyboard. Not sure why the button doesn't show but the functionality still works (the preference menu for it is buggy though)

**Comment by afonsojramos** [comment]
@kxmndz when the next update of Spicetify is released I'll ask you to try again if possible, thanks!

**Comment by TheGeeKing** [comment]
> Spotify version: 1.1.66.580.gbd43cbc9-a
You should rollback to 1.1.65.643

If on you are on Windows :

Block updates :
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

Rollback to 1.1.65.643 :
https://www.filepuma.com/download/spotify_1.1.65.643-29529/

For Mac users :

Block updates :
In the Application folder, right-click on the Spotify app and choose 'Get Info'

in the 'Get info' window, make sure you check 'Locked', right at the top.

Rollback to 1.1.59.714 (maybe newer versions work but I don't know so say it if you can try it) :
https://www.filepuma.com/download/spotify_1.1.59.714-28782/

**Comment by RaspberryKitty1** [comment]
same issue with mine. 

Spotify for Windows
1.1.67.586.gbb5ef64e

button not showing and f11 does nothing. (I'm a free user)

**Comment by RaspberryKitty1** [comment]
> Downgrade seems to work for now

well not fully work I'm now on 1.1.65.643.g2d707698-a and spicetify 2.6.0
f11 now works but no extensions are loading their custom buttons.

**Comment by TheGeeKing** [comment]
> 
> > Downgrade seems to work for now
> 
> well not fully work I'm now on 1.1.65.643.g2d707698-a and spicetify 2.6.0
> f11 now works but no extensions are loading their custom buttons.

Maybe due to your theme

**Comment by afonsojramos** [comment]
Can you update to 2.6.6?
Instructions found here: https://github.com/khanhas/spicetify-cli/releases/tag/v2.6.6
